### ISSUE TITLE
Pro/Contra View for Motions

### ISSUE THREAD

**Issue by d-s-e** [OpenSlides/OpenSlides#1048]
Motions should have a second view to collect arguments during the discussion phase.
This could be realized with the following changes:

_Motion View:_
- A Button "Discussion" to toggle the "Discussion mode" in the "Manage motion" section
- Two edit fields to enter pro and contra arguments
- An "Update" Button for each of those fields to save the text and update the projector view

_Projector View:_
- When the "Discussion mode" is active, the content of the motion (motion text and reason) is replaced by two columns with headings "Pro" and "Contra"

**Comment by tsiegleauq** [comment]
Motion supports configurable "motion-comment-section(s)" which can be used to achieve this.
We, however, do not have a slide yet to show selected motion comments on the projector

**Comment by tsiegleauq** [comment]
#6023 list of speakers not supports pro and contra speeches, which indirectly resolves this issue
