### ISSUE TITLE
Session Management

### ISSUE THREAD

**Issue by d-s-e** [OpenSlides/OpenSlides#1073]
A possibility to load save and edit different "Projects".

Sometimes it would be nice if one could prepare slides for multiple events.

it would be fine, if those projects could also share templates and participants.

**Comment by emanuelschuetze** [comment]
You can export the  tables agenda, motions and particpants as csv - and import these lists in a new OpenSlides instance. OpenSlides does not support multiple instances in one database. Therefore you can use the [OpenSlides multi-instance Manager](https://github.com/OpenSlides/openslides-multiinstance-backend) which based on a generic image for new instances.
