### ISSUE TITLE
Apps should catch a signal when a person is deleted

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1083]
Every app should be able to decide what to to if a person is deleted. For example the motion app might remove deleted supporters but keep deleted submitters as EmptyPerson. We need a PersonIsDeleted signal in the person API. The signal must be sent when a person model deletes an object.

**Comment by ostcar** [comment]
The person api is nomore. Know, the normal post_save signal can be used.

**Comment by normanjaeckel** [comment]
Addition: These apps can now use the [on_delete](https://docs.djangoproject.com/en/1.7/ref/models/fields/#django.db.models.ForeignKey.on_delete) model field argument.
