### ISSUE TITLE
Zoom non-fullscreen PDF

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1097]

**Comment by lesteenman** [comment]
Is this relevant in OpenSlides 2, given there is no option for non-fullscreen while a PDF is showing?

**Comment by emanuelschuetze** [comment]
@normanjaeckel What do you mean exactly with this issue?
Currently you can project a pdf in full screen (100% or zoom in/out with black background). Do you mean show a pdf in full width in our default projector template with header/footer - and with vertical scrolling in this template?

**Comment by normanjaeckel** [comment]
Yes. I think in old OpenSlides versions it was not possible to get a PDF in full screen and then zoom and scroll, so to show a portrait format PDF in fullscreen and to scroll down e. g.

The header or footer of the projector template is not important.

**Comment by emanuelschuetze** [comment]
So we can Close this Issue? Zoom and scroll works already in master.

**Comment by normanjaeckel** [comment]
I hope so. :-)
