### ISSUE TITLE
Change icons

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1152]
Use icon wrench (background-position: -360px -144px;) for config.
Use icon th or icon th large for the overlays widget.
Use icon list-alt for agenda.
Use icon-stats for assignment.
Change icon of presentations widget (but here I have no idea, maybe just the paperclip?).

**Comment by emanuelschuetze** [comment]
in 2.0 we use a new UI with new icons (fontawesome)
