### ISSUE TITLE
Flexible submenu

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1187]

**Comment by normanjaeckel** [comment]
A specific hook has to be implemented one the client side with AngularJS.

**Comment by emanuelschuetze** [comment]
@normanjaeckel what's your requirement here? Maybe we can close this already or with 2.0?

**Comment by normanjaeckel** [comment]
I am not sure. It is about how to add more buttons to the submenu by a plugin. We have to fix the plugin API before we can see what to do here.

**Comment by jsaalfeld** [comment]
I think this is stale by now. If this still persists, please add some context and reopen the issue.
