### ISSUE TITLE
Easy projector scroll

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1204]
The following feature would be very nice: A user who has permission to manage the projector should be able to scroll on the full projector view. On smaller events the chairperson often wants to see the projector in full screen on his personal computer. At the moment he has to look at the often very small live view to use the scroll buttons.

Proposal: On the projector view some JS catches scrolling inputs from the browser and sends "them" as event to the scroll url. Very nice if you can control the projector on a tablet with scroll and even scale (zoom).

**Comment by jsaalfeld** [comment]
AFAIK: Projector scrolling is a thing in OS2.3 and it will be in OS3. Please reopen if I'm wrong.
