### ISSUE TITLE
HTML Editor does allow VERY little markup

### ISSUE THREAD

**Issue by Hackwar** [OpenSlides/OpenSlides#1205]
The CKEditor in 1.5 is configured to basically only allow headings, paragraphs, lists and a few tags for text-formatting. It strips all other tags and especially (almost) all attributes. There is no way to display a table or reformat parts of the output with inline styles. (I specifically wanted to display a list of candidates in 2 columns. Neither inline-css with column-count, nor tables were accepted by CKEditor.) It doesn't allow images, either.

Besides CKEditor, the input is also filtered on the server side, which is not as restrictive, but still removes lots of attribute values.

**Comment by emanuelschuetze** [comment]
After using jsPDF #1640 (instead of reportlab) we can configure our ckeditor with more html markups...
