### ISSUE TITLE
Create debian package

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1333]
We should create a package for Debian and Ubuntu.
Therefor we have to check that all requirements are available as package. And we need an init script (to start OpenSlides automatically after system reboot and to get a common start command like `/etc/init.d/openslides start`).

**Comment by corecache** [comment]
Years have passed - even a stable Debian release happened - hows the package coming along?

**Comment by ostcar** [comment]
Not so good. The problem is, that we use new python packages that are not the debian repositories. For examples [channels](https://pypi.python.org/pypi/channels).

Maybe it is a problem, that we make a braking change in design nearly on each release, but I think, it made the software better.

**Comment by jsaalfeld** [comment]
We set up a new Notebook for a collegue and noticed, that Debian still uses fairly old Python versions. We can run into some issues while packaging the software. We maybe even can get more dependencies to older versions to that.

Is it really necessary to create a package or are the Docker Images sufficient?

**Comment by tsiegleauq** [comment]
Since we will continue to develop OpenSlides and potentially update the python version again, Debian will most likely never catch up.

We could think about providing an AppImage which would (or rather could) include a full python installation.

**Comment by jsaalfeld** [comment]
@emanuelschuetze How do you see this? Could we maybe merge this issue with #3984 and create an AppImage instead?

**Comment by emanuelschuetze** [comment]
Closed this issues because we provide a docker compose setup - not a specific debian package.
