### ISSUE TITLE
Add toggle url for user is_present

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1347]
There are no urls at the moment...

**Comment by normanjaeckel** [comment]
Please check this after implementation of users app in AngularJS.

**Comment by ostcar** [comment]
The urls have to be in django, to they can be toggeld via url

**Comment by emanuelschuetze** [comment]
I doesn't need such a toggle url no longer. Currently, we have no qrcode feature which requires a toggle url to set user to present/absent.  Can be do in a new issue if requested.

So closed.
