### ISSUE TITLE
Remove JS-libs from the repo

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1357]
Find a way to list the third party javascript libs in a file similar to the requirements.txt for python libs.

The JS-libs should not be downloaded in the setup process from the user, but in the release process from us.

@normanjaeckel I give you the ticket because you did not like my solution.

This issue has to be fixed before we can move the code into a new repo.

**Comment by ostcar** [comment]
The new system is "bower".

I let this issue open until we moved all JS-libs to the new system.

**Comment by normanjaeckel** [comment]
@emanuelschuetze Please keep this in mind while developing the frontend. Use bower for everything and delete all remained JS libs at the end.

**Comment by emanuelschuetze** [comment]
Everything done here.
