### ISSUE TITLE
Use a globel user model to make this model pluggable

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1370]
Activate `get_user_model()` function in openslides/core/models.py or somewhere else. The goal is that is is possible to disable the users app and enabled a customized users app just by adding the customized code (e. g. as plugin) and changing settings values but without changing code in motion, assignment and mediafile app.
See also some TODOS in openslides/users/models.py and #1345 and #1348.

**Comment by ostcar** [comment]
duplicated: #1387
