### ISSUE TITLE
Update pdf.js

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1375]
Talked with @DebVortex we should update pdf.js to check if this update solves some reported problems (#1100 and #972).

Last release of pdf.js: 1.0.907 (16.10.2014).
Current version in OpenSlides: 0.8.541

@DebVortex Can you make a quick test if all API calls works with a latest release of pdf.js?

**Comment by emanuelschuetze** [comment]
@DebVortex We decided to make a 1.7 release before running directly to 2.0. For 1.7 we could update pdf.js to improve/stabilize the pdf.js functionality. Can you make a quick test with the new version in the next days so that we can merge the pdf.js end of the week?

**Comment by DebVortex** [comment]
Sorry that I was not able to test it already. I'm currently have a little problem where I'm not able to set up a venv for python 3. I will probably create a vagrant box to ship arround this the next days. I try to get you the information you need until the end of this week.

**Comment by emanuelschuetze** [comment]
Note: We need the pull request for 1.7 (currently the stable/1.6.x branch). This is python 2.7 only!

**Comment by DebVortex** [comment]
I created a Branch, basing of the 1.6.1 tag [here](https://github.com/DebVortex/OpenSlides/tree/feature/update-pdfjs). Everything still works as expected but I don't know if it solved the other problems you talked about.

**Comment by emanuelschuetze** [comment]
Fixed in #1396
