### ISSUE TITLE
Motion link in motion and personal info widget

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1376]
The link should not appear if the user has no permission to see the detail view.

**Comment by emanuelschuetze** [comment]
I think the required changes are to big for 1.7.
If we want to fix it then we have do it consequently for all links to another app (e.g. candidates/submitters to can_see_participants; agenda related item to motions/assignments). That requires a lot of specific if..else in template where the link is build. Or more generic code...

So my suggestion: -1 for 1.7

**Comment by normanjaeckel** [comment]
Ok. In 2.0 AngularJS can do this: Just fetch the object from the api and check status_code. If 403, don't add the link ...

**Comment by ostcar** [comment]
This widget does not exist anymore
