### ISSUE TITLE
Use pyvenv instead of virtualenv

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1382]
Python 3.3+ contains pyvenv which works like virtualenv:
https://docs.python.org/3/library/venv.html
We should change the OpenSlides install instruction (in README and manual?) to switch to pyvenv.

Note: Python3.3 does not install pip automatically. Python 3.4 does it.

**Comment by ostcar** [comment]
Test this once more with ubuntu 14.04

**Comment by emanuelschuetze** [comment]
@normanjaeckel It would be great if you can update the install instruction. Can you please test if pyvenv works on windows? (In my last short test it does not work...)

**Comment by normanjaeckel** [comment]
For Ubuntu 14.04 the command `sudo apt-get install python3.4-venv` is necessary.
