### ISSUE TITLE
User or Participant in Template

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1403]
Should we use the term "participant" or "user" in the frontend?

**Comment by emanuelschuetze** [comment]
I prefer "participant"! OpenSlides is a tool for assembly which is used by _participants_ of this event. "User" is to technical. And you use typical naming like "list of participants" (Teilnehmerliste) which does not work for "user". 

So for me we can close this issue and keep "participant".

**Comment by normanjaeckel** [comment]
But we renamed the app form participant to users. We did we do that?

**Comment by emanuelschuetze** [comment]
Yes, app name "user" is ok. But in frontend always "participants". Same like assignments (frontend: "elections").

**Comment by ostcar** [comment]
I can live with both. Please came to a agreement without me

**Comment by DerPate** [comment]
i think for constancy we should stay at participants user are right for the app its short and the devs know what it mean but for the attendants to a conference participants should be the right term to use

**Comment by emanuelschuetze** [comment]
+1 for keeping "participants"
@normanjaeckel ok?

**Comment by normanjaeckel** [comment]
Whatever ...
