### ISSUE TITLE
move ckeditor to bower

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1426]
At the moment ckeditor is installed as python dependency. This has the advantage, that it is integrated with django.

Now, we have bower to solve the javascript dependencies. We should also use it to get the ckeditor-files. With angular, the integration into django should not be important.

Another disadvantages of our python dependency is, that it is not widespread in the python world and there are no debian packages for it.

**Comment by ostcar** [comment]
See also: #1357

**Comment by DerPate** [comment]
there is already an angular plugin to use the ckeditor https://github.com/lemonde/angular-ckeditor.

**Comment by emanuelschuetze** [comment]
We already use the bower packages 'ckeditor' and 'angular-ckeditor', see https://github.com/OpenSlides/OpenSlides/blob/master/bower.json#L30
