### ISSUE TITLE
Anonymous not working properly

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1430]
* Create a motion with admin user.
* Activate anynousmus guest users.
* Try to see the motion with anonymous user:
  * Response HTTP 500, expected HTTP 200

The problem is that the method `motion.is_submitter(person)` tries to check the anonymous user. This fails because this user object is not like the others.

**Comment by ostcar** [comment]
This has nothing to do with the new anonymous user ( #1424) you get the same behaviour on commits before it.

I don't know why the 1.x releases were not affected. But there are a log of questions for this error on stackoverflow. For example: https://stackoverflow.com/questions/17623234/django-simplelazyobject.

I prepared a fix  for it in #1431
