### ISSUE TITLE
rest user required fields

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1443]
The rest user serializers has some required fields that should not be required.

* groups: should not be required
*username: should not be required but generated with api.gen_username. 
*firstname and lastname: one of them should be required

**Comment by normanjaeckel** [comment]
See #1457.

**Comment by ostcar** [comment]
Please let this open until you fixed it. Your meta issue is a nice idea, but it is much easier for me to follow and discuss on this issue.

**Comment by normanjaeckel** [comment]
Done with #1458.
