### ISSUE TITLE
Use angular-loading-bar

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1448]
Could be very useful e.g. for csv import:
https://github.com/chieffancypants/angular-loading-bar

**Comment by ostcar** [comment]
sounds nice!

**Comment by emanuelschuetze** [comment]
angular-loading-bar added with pull request #1513.
You can test it e.g. while csv user import.

**Comment by ostcar** [comment]
Please let this pull request open after the merge of #1513. I would like the bar for each request. For example the load of all the template files at the first request (which could take a notable time)

**Comment by emanuelschuetze** [comment]
The loading-bar is enabled for each request - but for testing it is nicer to run a (long) import request. For short list view request you will not see the loading-bar because it loads to fast.
