### ISSUE TITLE
Use migrations

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1451]
Activate migrations for all apps.

**Comment by ostcar** [comment]
@emanuelschuetze should we do this before the first alpha? This would have the advantages, that the users could update from one alpha to the next without deleting there database

**Comment by emanuelschuetze** [comment]
@ostcar Yes, it would be good to use migrations. What we have to do to activate this now?

**Comment by ostcar** [comment]
That is easy, but we should first merge this, because this will make migrations easier #1579 

The poll app and the projector app can me merged at a later time, because they do not create any database tables.

**Comment by ostcar** [comment]
This is done by #1580
