### ISSUE TITLE
Refactor users app.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1457]
What to do:

- [x] Move user related stuff from core to users app.
- [x] Clean up e. g. move code out of 'api.py' to more specific places.
- [x] Add new serializer for user creation.
- [x] Hide groups 'Anonymous' and 'Registered' from creation serializer.
- [x] Hide groups 'Anonymous' and 'Registered' for update requests. May be use another serializer.
- [x] Add possibility to delete users.
- [x] Add possibility to create, update and delete groups.
- [x] Hide default_password from normal users.
- [x] Clean up a little bit more

See also #1443 #1452

**Comment by ostcar** [comment]
Only the manager should see the default password.

**Comment by normanjaeckel** [comment]
All done, see #1642
