### ISSUE TITLE
create needed groups in create_or_reset_admin

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1462]
When all groups are deleted, the command create_or_reset_admin (called from) fails, so an user can not get access again.

**Comment by ostcar** [comment]
I think this is not so important. If you think differently, then please self assign this issue

**Comment by FinnStutzenstein** [comment]
@ostcar closed with PR #2370

**Comment by FinnStutzenstein** [comment]
@ostcar Ping.

**Comment by emanuelschuetze** [comment]
I'll close this because all done with #2370.
