### ISSUE TITLE
Use main menu in angular

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1469]
We need a solution to get a _generic_ main menu in angular base template. Only installed apps (and also plugins later) should be included into the main menu.

**Comment by emanuelschuetze** [comment]
#1513 shows only a temporary solution because main menu entries are placed manually. We need a more generic solution.

Also we need a solution to show the selected menu entry as activ! This is important for a first alpha of 2.0 - so I set it to "blocker".

**Comment by ostcar** [comment]
@emanuelschuetze I don't see this issue as a blocker. Please add the flag again with an explanation if you think otherwise.

**Comment by emanuelschuetze** [comment]
Now, it's good enough for 2.0a1.
