### ISSUE TITLE
Does logout have to send HTTP 200 even if a user was not logged in before?

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1471]
I think it should send HTTP 4xx. What do you think?

**Comment by ostcar** [comment]
I prefer 200. The result should be relevant. After a anonymous calls logout, he is logged out.

It is the same question for all other post request. Should the update view return a 4xx status code, when the data have not changed? Should the projector_activate url return an error code, when the slide is already activated?

**Comment by normanjaeckel** [comment]
I think logging out is somehow like a process. Someone who is logged in can logout himself for some reason. Maybe we want to add some statistics tools to make a timestamp whenever someon logs in or out. Then the process (log me out) was not successful if I was not logged in before. This is my fault, the server tells me (= HTTP 4xx).

**Comment by emanuelschuetze** [comment]
@normanjaeckel I don't know what is still open and what can I do here?

**Comment by normanjaeckel** [comment]
@emanuelschuetze It is about your (personal or professional) opinion. Should the server send 200 or 4xx in this case (and in many other cases like this)?

**Comment by normanjaeckel** [comment]
@boehlke says 4xx. :-)

**Comment by emanuelschuetze** [comment]
I tend to 4xx. But you can decide it.
