### ISSUE TITLE
Is get_absolute_url() still required?

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1475]
We probably do not need it in django anymore.

@emanuelschuetze will there be an function in django that has to know the url to a user? Maybe your user-pdf with the qr-code to toggle the user status?

**Comment by normanjaeckel** [comment]
I would prefer removing this (generic) method. Single use cases might find their way to get the same URL as AngularJS uses and we don't have to keep this in mind without actual need.

**Comment by emanuelschuetze** [comment]
I think we can remove it. Only the use case activate/deactivate user (maybe two single urls, without toggle state; that got's nothing to do with the qrcode pdf!) could be later provide a special url.

**Comment by ostcar** [comment]
I remove the method after we changed the dashboard to angular. We first have to remove the users widget. It needs the method.

**Comment by ostcar** [comment]
done
