### ISSUE TITLE
install OpenSlides failed with error in reportlab

### ISSUE THREAD

**Issue by cmdtstof** [OpenSlides/OpenSlides#1484]
opensuse tumbleweed
trying to install OpenSlides (pip install openslides in virtualenv)

Traceback (most recent call last):
      File "<string>", line 20, in <module
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8fcbwab7/reportlab

???
thanks

**Comment by normanjaeckel** [comment]
Can you please add a full Traceback? Do you have Python header files installed? On Ubuntu it is [this](http://packages.ubuntu.com/trusty/python-dev). On OpenSuse it is possbily the package python-devel but I am not sure.

**Comment by Steini-** [comment]
I've got the same problem.
Setup is a ubuntu 12.04 lts, latest openslides-download
This is the traceback from the installer:

Downloading/unpacking backports.ssl-match-hostname (from tornado>=3.1,<3.3->openslides)
  Downloading backports.ssl_match_hostname-3.4.0.2.tar.gz
  Running setup.py (path:/tmp/pip_build_christian/backports.ssl-match-hostname/setup.py) egg_info for package backports.ssl-match-hostname
    
Installing collected packages: reportlab, roman, sockjs-tornado, tornado, whoosh, backports.ssl-match-hostname
  Found existing installation: reportlab 3.0
    Uninstalling reportlab:
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1431, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 598, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1836, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 295, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/reportlab-3.0.egg-info'

**Comment by normanjaeckel** [comment]
Not sure whether this is the same problem.
@Steini- Do you use Virtual Environment Builder or do you want to install OpenSlides globally? Your traceback looks like a global install so do you used root permissions? `sudo pip install openslides`
The next thing? Your current installation seams to contain Reportlab 3.x. but OpenSlides 1.7 requires Reportlab 2.7. If you install OpenSlides globally you might get dependency problems with other applications. I strongly recommand using Virtual Environment Builder (virtualenv) as mentioned in the README.

**Comment by normanjaeckel** [comment]
I hope your problems are solved. Please comment again if something does not work properly.
