### ISSUE TITLE
Refactor version view using AngularJS

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1492]
See comment in #1488.

**Comment by emanuelschuetze** [comment]
The openslides-gui needs a possibilty to get the OpenSlides version. In the current pull request @andkit has to comment out the old `openslides.get_version()` way. 

https://github.com/OpenSlides/openslides-gui/pull/1/files#diff-9c4cc4d7a0b462d797d22c46f3f0c0e3R377 

Please provide a new solution to get the version string.

**Comment by emanuelschuetze** [comment]
It's a blocker for openslides-gui and a first alpha release of 2.0

**Comment by ostcar** [comment]
```python
from openslides import __version__
```

See http://legacy.python.org/dev/peps/pep-0396/#examples for example

**Comment by emanuelschuetze** [comment]
Ok, then in this issue is still open a new angular version view. How can angular get the version number? Via REST-API?

**Comment by ostcar** [comment]
Yes, we have to create a json-view for that. But is not an rest-API, because the version can not be changed by the client.

**Comment by normanjaeckel** [comment]
The server's version can be provided via such a view.

**Comment by emanuelschuetze** [comment]
done in #1570
