### ISSUE TITLE
List of all permissions for AngularJS

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1500]
We need a way to tell AngularJS which permissions exists. Try to avoid defining them twice.

**Comment by emanuelschuetze** [comment]
It's a blocker for the group-create/-update template.

**Comment by normanjaeckel** [comment]
For the moment you can use a hard coded list.

**Comment by normanjaeckel** [comment]
You can get the permissions via OPTIONS request on /rest/users/group/. There you got a JSON result and have access to all permissions via `resultData.actions.POST.permissions.choices`.
