### ISSUE TITLE
Validate html with travis

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1501]
With https://www.npmjs.com/package/gulp-html

**Comment by ostcar** [comment]
If we want valid html5, we need to get rid of the angular ng- tags. For example with:
https://github.com/pgilad/angular-html5

**Comment by ostcar** [comment]
The npm-package hulp-html needs java. I don't want to add another parser (next to node and python) to our dev tools. So we need another html validation lib.

**Comment by normanjaeckel** [comment]
Maybe use this: https://github.com/hoobdeebla/gulp-html-validator

**Comment by normanjaeckel** [comment]
Someone who wants to to this?

**Comment by ostcar** [comment]
@FinnStutzenstein can you decide if this is a good thing to do? If not, please close this issue

**Comment by jsaalfeld** [comment]
@tsiegleauq - Do you think this is a good Idea?


If a good validation is possible, we should, at least, give it a try.

**Comment by tsiegleauq** [comment]
No. `<os-[selector] ...>` or even `<mat-***>` will probably not be detected as valid html.

Angulars `(click)` `[input]` and `*ngIf` is also no valid HTML.
Parses will not, and potentially never, tell you if your HTML is fine or not. Browsers will.

**Comment by FinnStutzenstein** [comment]
We may have a linter that just checks for spacing, indentions, ...
This would be nice.

Our HTML is validated with the client tests already, because Angular checks the HTML during the build

**Comment by tsiegleauq** [comment]
- travis checks if the HTML is correct during NGbuild
- prettier corrects malformed HTML automatically

Issue lost it's relevance. Closing.
