### ISSUE TITLE
How to serialize data for the projector.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1502]
We have to decide how the REST API should provide data for the projector. Here my draft. Please comment.
```json
{
    "config": [
        {
            "id": 1, 
            "name": "core/customslide"
        }, 
        {
            "name": "invalid-slide-or-element"
        }
    ], 
    "projector_elements": [
        {
            "name": "core/customslide", 
            "template_name": "core/customslide_slide.html", 
            "context": {
                "id": 1, 
                "data": {
                    "id": 1, 
                    "title": "Hello", 
                    "text": "Foobar", 
                    "weight": 1
                }, 
                "collection": "core/customslide"
            }
        }, 
        {
            "name": "invalid-slide-or-element", 
            "error": "Projector element does not exist."
        }
    ]
}
```
`config` is the one and only model field of the projector model. To activate slides and overlays (together called projector elements) you have to save a list of dictionaries into this field. Every dict should contain at least a name. In my example the manager tried to activate a custom slide (pk=1) and additionally an invalid projector element.

`projector_elements` is the answer of the REST API. Every config entry is answered. If the entry is valid, you get `name` and some more data. This should harmonize with Autoupdate data and the like.

@ostcar @emanuelschuetze Please tell me if you like to get the data in another way.

**Comment by emanuelschuetze** [comment]
@normanjaeckel Why do you created a new branch "DjangoRESTFrameworkProjector" in our upstream repostory?
https://github.com/OpenSlides/OpenSlides/tree/DjangoRESTFrameworkProjector

**Comment by normanjaeckel** [comment]
I did, but this is fixed now. This was not intended.

**Comment by ostcar** [comment]
@normanjaeckel can this be closed?
