### ISSUE TITLE
Fix django urls in template

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1505]
e.g. in index.html:
  {% url 'core_version' %}
  {% url 'user_settings' %}
  {% url 'password_change' %}

Check other templates!

**Comment by ostcar** [comment]
@emanuelschuetze is this still open?

**Comment by emanuelschuetze** [comment]
There are still two old django links in index.html:
{% url 'user_settings' %}
{% url 'password_change' %}

**Comment by emanuelschuetze** [comment]
Already fixed. Closed.
