### ISSUE TITLE
How to translate strings during migration

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1508]
We need a solution to translate strings during migrations. Proposal 1: Prompt for user input on command line (or gui). Proposal 2: Try to use default environment variables.

Use case is my draft of a custom welcome slide which should be created during initial app migration. Here I want to save a translated string into the title field.

Who can help?

**Comment by ostcar** [comment]
I do not understand. What strings do you want to translate? Do you mean database migration?

**Comment by normanjaeckel** [comment]
Yes during database setup and migration. I changed the issue title some days ago.

**Comment by ostcar** [comment]
So you want to translate values inside the Database?

**Comment by ostcar** [comment]
We create models in the migration files, for example some custom slides. But there is no browser language at this moment. We have to set a language manually.

**Comment by normanjaeckel** [comment]
Not neccessary at the moment.
