### ISSUE TITLE
Rename apps, permissions and urls

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1509]
We want to use plural in all app names. So rename app name, urls and permissions for the apps:
* assignment -> assignment
* motion -> motions
* mediafile -> mediafiles

Note, that we want to unify the permission strings like in users app, e.g.
"users.can_manage" (instead of the old form: "users.can_manage_users")

This is a blocker for my further template work.

**Comment by ostcar** [comment]
Most done in #1510. 
I did not rename the url pattern names because most of the urls will be removed anyway. Please rename the url pattern names when you create the angular apps and reverence a view via the url name.

**Comment by emanuelschuetze** [comment]
Done in #1513.

**Comment by ostcar** [comment]
please leave the issue open, until the pull request is merged
