### ISSUE TITLE
Find a improved way to call node.title in the agenda tree in javascript

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1516]
At the moment we call "{{ (items | filter: {id: node})[0].title }}" in the angular template to get the title from an agenda item (or other attributes). We need to find a way to append the attributes of the agenda items to the agenda-tree-nodes.

**Comment by emanuelschuetze** [comment]
This issue causes that the search filter over ng-repeat does not work:
`ng-repeat="node in flattenedTree | filter: filter.search"`
`node` contains only the id and not the string which is searched (and displayed in table cell).

**Comment by emanuelschuetze** [comment]
Another subissue: How can you bind `tree` to item list view so that the list/tree is updated if one item is deleted?

**Comment by emanuelschuetze** [comment]
The main issue is done, but one thing is still open:
In the AgendaSortView is NOT updated if an item titel (e.g. of a custom slide) is updated. In the ItemListView it works the auto update as expected. For both controller the agenda tree is bind to scope, so I can't see whats the different.
@ostcar Please look at this subissue.
