### ISSUE TITLE
JavaScript errror "Error: currentValidationVars.privatScope is undefined"

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1520]
I get a javascript error in console if you load each page.
It is caused by including ng-fab-forms-module. It does not happens with a clean ng-fab-forms demo; so maybe a special OpenSides/angular problem in combination with the ng-fab-forms module?

**Comment by emanuelschuetze** [comment]
@ostcar Can you please look at this error?

**Comment by ostcar** [comment]
@emanuelschuetze Can you give me a description what I have to reproduce this error, please?

**Comment by emanuelschuetze** [comment]
Can't reproduce any more with current master.
