### ISSUE TITLE
'openslides start' can not specify special host/port

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1523]
* Make OpenSlides 2.0a1-dev package from current master: `python setup.py sdist` 
* Install OpenSlides in python3.4 venv: `pip install openslides-2.0a1-dev.tar.gz`
* run OpenSlides with different hosts and port combination:
 * openslides start -> browser opens http://0.0.0.0:8000
 * openslides start 127.0.0.1 -> browser opens http://0.0.0.0:8000; host 127.0.0.1 works also but it should work _only_ on 127.0.0.1
 * openslides start 127.0.0.1:8001 -> browser opens http://0.0.0.0:8000, port 8001 doesn't work

Define host and port should work, important especially for portable/gui version.

**Comment by emanuelschuetze** [comment]
Note: starting `python manage.py runserver 127.0.0.1:8001`works as expected (here: runs server on http://127.0.0.1:8001/). Seems to be a problem in our start script?

**Comment by ostcar** [comment]
Is this still open? I think our decision  was, that it is not possible to choose the host and the port with the start script and that the portable should use the commands be calling the python functions instead calling the openslides command via the command line.

**Comment by emanuelschuetze** [comment]
I'll check it.

**Comment by emanuelschuetze** [comment]
`python manage.py start` works only for 0.0.0.0:8000 (=localhost:8000). Define an other port/addres is not possible with start script. But user can run `python manage.py runserver 10.0.0.1:8001` e.g.

The portable script should run via runserver that modified ipaddress and port can used.
