### ISSUE TITLE
Use bulk mode for multiple create objects while import

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1533]
Make a "pre check" if all lines are importable. Show error and abort if not.
Import all lines at once if possible.

**Comment by emanuelschuetze** [comment]
pre check will be done in #1748 

So still open: find a way to use a bulk mode (= single request)

**Comment by emanuelschuetze** [comment]
We use `objects.bulk_create(..)` in openslides-votecollector now, see https://github.com/OpenSlides/openslides-votecollector/pull/35/files#diff-73fb58d31456c6a5f57d6c5f609a2a94R530

This should be used also in users and motions csv import.

**Comment by normanjaeckel** [comment]
Here is my patch with a draft of a mass import view endpoint: [UserMassImport.txt](https://github.com/OpenSlides/OpenSlides/files/645748/UserMassImport.txt)

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze @normanjaeckel Is this still a thing? Also for huge motion imports?

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Yes also for motion csv import we want a mass import. But motions is a bit more complex because we create new categories and users if not available. User mass import could be easier for first implementation. You can think about and look at Normans draft for user mass import (see above).

**Comment by FinnStutzenstein** [comment]
Ok, I think this is relatively easy because with the new csv import we check and clean up all data very well..

**Comment by jwinzer** [comment]
@emanuelschuetze @normanjaeckel Do you have plans to integrate bulk import into the master? If so when will it become available? Thanks.

**Comment by jwinzer** [comment]
js-data 3.0 has DS#createMany for bulk creation.
http://www.js-data.io/v3.0/docs/saving-data#creating-and-saving-new-records

**Comment by FinnStutzenstein** [comment]
The client is not the problem, but currently we do not have the plan to update js-data to 3.0. Instead just a request to a special mass-import endpoint is required.

Using `bulk_create` in python does not always work with our models (e.g. groups cannot be assigned to users on user bulk create). I'm working on a mass import of users in the first step, that only one request with all the data is required, and not X requests for X users. If this works, I'll go on to motions, agenda, ...

I currently have some things to fix with the diff view and pdf creation; If this is done, I hope to make a PR for the user import. @jwinzer Is there a special reason/situation you need a special mass import?

**Comment by jwinzer** [comment]
Thanks, Finn, for your fast response. I'm currently working on a plugin that needs to import a huge amount of records into its own model. As I'm on a tight schedule I will write my own bulk_create endpoint for now. A generic one will probably not work anyhow.

**Comment by FinnStutzenstein** [comment]
Yes, this is the way, we are going to go: A custom endpoint for massimporting, so every model of your plugin, that should be imported, should get a custom mass import view.

**Comment by jwinzer** [comment]
Perfect! I'm writing mine right now using Norman's patch above as an example.

**Comment by jsaalfeld** [comment]
@FinnStutzenstein Is this still an issue with client version 3.0?

**Comment by FinnStutzenstein** [comment]
Yes, in fact just a few operations support bulk create mode. With the new "stapelverarbeitungsmöglichkeiten" (what ever the englich term is ;) ) we may need more of them to make the operations fast and efficient.

**Comment by tsiegleauq** [comment]
We have a lot of bulk operations already. However, the creations of motions and users is too "bulky" to be handeled in a bulk operation for now.

**Comment by FinnStutzenstein** [comment]
Motions are still missing.
