### ISSUE TITLE
Reimplement CurrentListOfSpeakersProjectorView

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1542]
Reimplement a slide, which shows the current list of speaker.

See: https://github.com/OpenSlides/OpenSlides/pull/1539#discussion_r32514825

**Comment by ostcar** [comment]
This requires multiprojector.

A workaround would be to create a new backend page with a specific logic.

**Comment by FinnStutzenstein** [comment]
implemented in PR #2379 .

**Comment by emanuelschuetze** [comment]
should be done in current master
