### ISSUE TITLE
Implement functionality of 1.x for 2.0

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1543]
This is a meta issue which shows which functionality of OpenSlides is missing in the 2.0 release, but existed in OpenSlides 1.x.
- [x] Version view
- [x] Chat
- [x] Change (own) user settings
- [x] Change own password
- [x] Change password of other users (as manager)
- [x] PDF on projector
- [x] A generic main menu for plugins
- [x] Search
- [x] ~~CKEditor~~
- [x] ~~Use bleach for some REST fields so users can submit HTML.~~
- [x] ~~Choose own Logo instead of the OpenSlides logo~~
- [x] Add motion polls.

**Comment by normanjaeckel** [comment]
For the chat see # 1626 and #1627.

**Comment by normanjaeckel** [comment]
Bleach is not required at the moment.

**Comment by normanjaeckel** [comment]
For CKEditor see #944 and #1661.

**Comment by emanuelschuetze** [comment]
Chat and change password is already done. So still open:
* pdf.js (see #1664)
* search (see #1699)

The TODO "Choose own Logo instead of the OpenSlides logo" is not a 1.x function. So move it to 2.1.

**Comment by emanuelschuetze** [comment]
All done now.
