### ISSUE TITLE
ImportError at /rest/

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1548]
bad magic number in 'openslides.utils.main_menu': b'\x03\xf3\r\n'

Caused by commit fbf7d0e43d72c84b26036caf92e47ef5bcc7babc

**Comment by ostcar** [comment]
Strange, that the tests did not fail...

It will be fixed with #1545

**Comment by normanjaeckel** [comment]
Fixed in #1545.
