### ISSUE TITLE
TypeError after supporting a motion

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1551]
In OpenSlides 1.7:

TypeError at /motion/5/support/
check_permission() got an unexpected keyword argument 'pk'

openslides/utils/views.py in dispatch, line 67

**Comment by emanuelschuetze** [comment]
How can we fix this that users can patch their OpenSlides 1.7 installation manually? A short code example should be enough.

**Comment by ostcar** [comment]
Already fixed: https://github.com/OpenSlides/OpenSlides/commit/9b5d8a8bd4acd0d1969a7be6369f06fafe8b7038
