### ISSUE TITLE
Add motion.agenda_item to rest api

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1559]
Each motion should be able to reference to one agenda item.

**Comment by normanjaeckel** [comment]
Hm. This is problematic. According from OpenSlides 1.7 this would be an one-to-many relationship because one motion might be referenced in multiple agenda items. So if you like, I can implement such an array field.

**Comment by emanuelschuetze** [comment]
No, we should implement a simpler solution which supports a more typical use case of users:
Each motion can reference to only one(!) agenda item (in the motion form). So it is just one-to-one relationship. And ee does not need the "add motion to agenda" function from OpenSlides 1.x.

**Comment by emanuelschuetze** [comment]
This issue is not resolved.
@ostcar The pull request was still in discussion (see my last comment also in #1559) and was not ready to merge! For future please look carefully.

**Comment by normanjaeckel** [comment]
> So it is just one-to-one relationship.

We can do this but it needs some more work. Either we have to remove the Django style generic relations fields in the agenda Item model and refactor some methods but then we have to think about our own generic solution. Or we have to restrict the motion instances in some way not to use the possibilities (one-to-many) given by the database. This all would be more than we have in 1.7.

> And ee does not need the "add motion to agenda" function from OpenSlides 1.x.

I don't understand this. I think we still do not want *every* motion to be in the agenda, do we?

**Comment by emanuelschuetze** [comment]
@normanjaeckel Does I understand you correctly: If we would use a 'one motion to many agenda items' relationship it would be easier than 'one-to-one'? Than I could reduce it also on the GUI selection. And we could provide one-to-many later if somebody needs it.

>  I think we still do not want every motion to be in the agenda, do we?

Right. Our current (related agenda item) function in OpenSlides 1.x is not very useful if you want to reference _every_ motion to one agenda item. Maybe we can discuss if we keep this old function also in OpenSlides 2.0. I prefer to remove the old function and add the new one-to-one relation function only.

**Comment by emanuelschuetze** [comment]
Dicussed with @normanjaeckel 
We will remove the related item function and will replace it with a new feature to use only a reference to agenda item (like attachments or tags) in motions as foreign key.

**Comment by ostcar** [comment]
Please lets discuss this on telephone. I don't see how this can work.

**Comment by normanjaeckel** [comment]
Further discussion in #1567.

**Comment by emanuelschuetze** [comment]
This issue is not done and not a duplicate of #1567. So reopened. I'll discuss it with @ostcar

**Comment by normanjaeckel** [comment]
I think this is solved.
