### ISSUE TITLE
Generic list of speakers

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1567]
For OpenSlides 2.0 each detail view (e.g. of agenda item, motion, assignment) should be able to provide a list of speakers. Lists should not only restrict to agenda item.

Therefor we have to move the list of speakers code from agenda to core. Similar to tags.
New templates are required for each app.

**Comment by ostcar** [comment]
Please lets talk about this before you start to implement it. I don't think I like this idea

**Comment by normanjaeckel** [comment]
The question is whether we should also remove the related item feature or even generally refactor the handling of agenda, motion and assignments. @emanuelschuetze can you please discuss with @ostcar your ideas?

**Comment by ostcar** [comment]
See also #1280

**Comment by normanjaeckel** [comment]
New proposal:
* Remove title, text, comment from agenda items
* Remove agenda item create and delete views.
* Force every agenda item to have a generic relation either to a motion, an assignment, a custom slide or an user. This is done automaticly. An agenda item is created when one of the other objects is created (use a mixin to override the create or save method).
* Use unique together to ensure that it will always be a one-to-one relation.

**Comment by ostcar** [comment]
This is done
