### ISSUE TITLE
Link to mediafiles gone

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1575]
Try to upload a file and then just try to download it. The URL links to the start page instead to the uploaded content.

**Comment by emanuelschuetze** [comment]
With the current master it's not yet possible to upload a file via the mediafile-form view. For testing you can use the from in djangos' restframework page. Than the uploaded file is linked correctly and can be downloaded from mediafile-list view.
So what's your reported issue? The failed upload?

**Comment by normanjaeckel** [comment]
Upload a file through the REST Framework page. Then the link appears in OpenSlides's mediafile list view. The link is correct but if you click there, AngularJS moves you to the start page.

**Comment by emanuelschuetze** [comment]
Ok, I can reproduce it. @ostcar Any solution?
