### ISSUE TITLE
No permission for option requests

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1595]
At the moment the admin has no permissions for option requests for motion and assignment but for customslide. The reason is the new permission system. For an option request self.action is None, so check_view_permission returns False when self.action is tested for specific strings.

It could be a bug of the django rest framework that self.action is None for an option request. But I did not find the documentation for self.action in a django rest framework viewset, maybe it is not part of the public API.

We could treat self.action == None as option request, but I am not sure if there are other cases where self.action is None.

As long as this is not solved, the assignment page does not work because it needs the option request

**Comment by normanjaeckel** [comment]
Opened an issue here: https://github.com/tomchristie/django-rest-framework/issues/3115

At the moment we can solve this inspecting self.request.method.lower().

**Comment by normanjaeckel** [comment]
The fix is marked for Django RESt framework 3.1.4.

**Comment by ostcar** [comment]
fixed by #1602
