### ISSUE TITLE
Rename ForeignKey fields to FIELDNAME_id

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1597]
Please rename the field names of foreign keys, that only return the id to FIELDNAME_id.

For example the motion serializer has the field 'category' which is the id of the category.

On the client, I would like to add the category-object to the motion object, so motion.category.name returns the name of the category. But my problem is, that the attribute-name 'category' is already taken.

So it should be the same then in django. FIELD_id is the id of a ForeignKeyField and FIELD is the foreign object.

This is a blocker for #1596

**Comment by normanjaeckel** [comment]
Django REST framework seems not to support this by default. If it is really necessary we have to redefine all these fields by hand. Do we have a list of these fields?

**Comment by ostcar** [comment]
I think a generic solution is possible. I have a running version that works with ForeignKeys but not with Many2Many fields. I'm keep trying.
