### ISSUE TITLE
Remove field poll_number from MotionPoll model

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1601]
We do not need this field if we use the database id. See AssignmentPoll model.

**Comment by ostcar** [comment]
This is ok for me

**Comment by normanjaeckel** [comment]
If we wanted to get access to polls via the motion object (/motions/motion/1/poll/...) instead of using an extra route (/motions/motionpoll/...) we might have to keep this field. I am not sure how you want to implement this.

**Comment by normanjaeckel** [comment]
See #1607
