### ISSUE TITLE
Add chat

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1627]
See #1626.

The client side is still missing but it should be really simple. If you want to use two colors (grey for own messages and black for messages from others), you can just check the `user_id` of the chat object. If you want to use different colors, I suggest the client should make a modulo over the user id to get a color from a color table.

**Comment by emanuelschuetze** [comment]
see pullrequest #1679

**Comment by emanuelschuetze** [comment]
#1679 is merged. So closed.
