### ISSUE TITLE
Add zoom and scroll function for projector controls

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1633]
like in OpenSlides 1.x:
- zoom up/down
- scroll up/down
- reset zoom & scroll

**Comment by normanjaeckel** [comment]
Hm. What about just saving `{"zoom": "42"}` into the projector element config field? This would not be a global zoom but a zoom for one projector element.

**Comment by ostcar** [comment]
I think we need a global zoom. Maybe each projector model could have one more db-field for global config. This could also be useful when we start the multiprojector to give each projector a name, a room or another human readable identifier
