### ISSUE TITLE
Replace reportlab by jsPDF

### ISSUE THREAD

**Issue by dmth** [OpenSlides/OpenSlides#1640]
The current mechanism to generate PDFs and the HTML output, seems to require to do things twice.
First: HTML templating
Second: PDF templating

It might be reasonable to generate the PDF from the HTML or its templates.
At least two approaches exist for this:

First option: Generate PDF from Django templates:
https://github.com/chrisglass/django-xhtml2pdf -> https://github.com/xhtml2pdf/xhtml2pdf -> Reportlab

Second option: Use a JavaScript library which converts from html to pdf:
For example:  https://github.com/MrRio/jsPDF

I did not test any of the two options provided above.

**Comment by emanuelschuetze** [comment]
@dmth Thanks for your research!
jsPDF looks interesting! xhtml2pdf requires reportlab which we want to remove from our requirements.
So I'll make some tests with jsPDF.

**Comment by emanuelschuetze** [comment]
@DerPate As discussed in IRC please just test jsPDF and report here your feedback. Thanks.

**Comment by emanuelschuetze** [comment]
Closed. First PR #2284 with pdfmake is merged.
