### ISSUE TITLE
Projector clock shows wrong time

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1645]
The projector clock calculation is wrong! Clock shows e.g. "17:43" (but current time is "15:12").
This could be the reason why my countdown time is also wrong.

**Comment by emanuelschuetze** [comment]
It's a blocker for my countdown pull request #1634

**Comment by normanjaeckel** [comment]
Use `$scope.serverOffset = new Date().getTime() / 1000 - $scope.element.context.server_time;` in line 790 in core.js

**Comment by normanjaeckel** [comment]
Even better: `$scope.serverOffset = Date.now() / 1000 - scope.element.context.server_time;`

**Comment by emanuelschuetze** [comment]
Thanks! I fixed it in #1634 . Now the clock shows correct time.
