### ISSUE TITLE
Field name `filetype` is not valid for model `Mediafile`.

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1650]
Try to upload a new file via mediafile form view. Gets an error. The file is not uploaded:

"ImproperlyConfigured at /rest/mediafiles/mediafile/
Field name `filetype` is not valid for model `Mediafile`."

@boehlke Can you look at this error please?

**Comment by normanjaeckel** [comment]
@boehlke I can do this easily if you like (and have less time at the moment). No problem.

**Comment by boehlke** [comment]
Am 06.11.2015 um 11:51 schrieb Norman Jäckel:
>
> @boehlke <https://github.com/boehlke> I can do this easily if you like
> (and have less time at the moment). No problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSlides/OpenSlides/issues/1650#issuecomment-154378202>.
>
Gerne!
Thx.
