### ISSUE TITLE
Use pdf.js presentation function in angularjs

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1664]
We have to migrate our old pdf.js presentation code (from OpenSlides 1.7, mediafile app) to new angularjs client in OpenSlides 2.0 (master). It's one of our last feature which we have to migrate to 2.0 code base.

Here some required work packages:
* Move and integrate current pdf.js files to mediafiles/static/js/
* add the presentation controls (go to next/previous/first/custom slide, toggle fullscreen mode) to new sidebar div container (currently still in openslides/core/static/templates/core/projector-controls.html); buttons should send by ng-click an `update_elements` post request to rest api (see e.g. countdown controls)
* add new slide controller and slide template for presentation div container (see e.g. countdown in core/projector.js)

@boehlke: Can you try it in "your" mediafiles app? Let me know if you need some help.

**Comment by normanjaeckel** [comment]
Maybe use bower for the pdf.js lib.

**Comment by boehlke** [comment]
There is an angular integration für pdfjs: https://github.com/zyncro/angularjs-pdf
That might be a good starting point.

**Comment by emanuelschuetze** [comment]
Looks interesting, but angularjs-pdf has a hard old angular 1.2.8 dependency (we currently use last stable 1.4.7) and it looks not very maintained. But maybe we can use something of it or you find a fork.

**Comment by emanuelschuetze** [comment]
I looked again on your (updated) link: this angularjs-pdf project (with current version 1.2.5) is up-to-date and works with current angularjs stable. So go forward and create a pull request for a pdf.js integration in OpenSlides! We want to include it in 2.0b1 released on 2015-11-30. So we need your pull request the week before.
@boehlke Ok?

**Comment by boehlke** [comment]
This is more complicated than I thought. I will try to finish the implementation on friday.
