### ISSUE TITLE
Special motionpoll values should handled by rest api 

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1669]
As discussed in pull request #1663 and via Jabber:

a) The rest api should get the translated strings for the special MotionPoll results -1 and -2.
b) The rest api should accept "null" for yes/no/abstain in PUT request and set "-2" by default for these null values (or directly the string "undocumented").

https://github.com/OpenSlides/OpenSlides/pull/1663#issuecomment-155102225

**Comment by normanjaeckel** [comment]
All done.
