### ISSUE TITLE
Setup transifex and add German translations

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1672]
If possible create new version/branch on transifex:
https://www.transifex.com/openslides/

For angular-gettext `gulp pot` updates the template-en.pot file in https://github.com/OpenSlides/OpenSlides/tree/master/openslides/locale/angular-gettext. This could be the master document for transifex.

Additional, we need the django po file from https://github.com/OpenSlides/OpenSlides/blob/master/openslides/locale/en/LC_MESSAGES/django.po

@normanjaeckel Can you setup transifex for our new 2.0 translations please?

**Comment by emanuelschuetze** [comment]
Thanks for creating new 'Core 2.x' resources on transifex:
https://www.transifex.com/openslides/dashboard/all_resources/de/?project=openslides
One suggestion:
Please rename the JS-resources that all resources begin with "OpenSlides x.y ...", so that you can easily sort by name:
"OpenSlides JS 1.x" -> "OpenSlides 1.x JS"
"OpenSlides JS 2.x" -> "OpenSlides 2.x JS"
Rename also the description "Core-JS x.y" to "Core x.y (JS)" or similar.

**Comment by normanjaeckel** [comment]
Rename done.

**Comment by normanjaeckel** [comment]
Transifex is now enabled.
