### ISSUE TITLE
Use .bowerrc

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1678]
see discussion on users-de:
http://mail.openslides.org/pipermail/users-de/2015-November/000408.html

**Comment by ostcar** [comment]
@normanjaeckel can you check this?

**Comment by normanjaeckel** [comment]
Won't fix as discussed. The problem is in https://github.com/ck86/main-bower-files/blob/master/lib/index.js: This should be solved there.

Workaround: Use your own .bowerrc in the parent directory of OpenSlides root repo dir.
