### ISSUE TITLE
Add 'done' flag for mediafiles

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1682]
For better managing of many (pdf) presentation files, please add a 'done' flag for each file, like in agenda item list. Add also a filter in mediafiles list view for showing files which are not done.

@boehlke Can you implement it?

**Comment by boehlke** [comment]
Sure, but I am not certain if I can make it for the scheduled beta release.

**Comment by emanuelschuetze** [comment]
The milestone is set to 2.0 - not 2.0b1. So you have more time to implement it.

**Comment by boehlke** [comment]
2.0b2 is fine as well

**Comment by jsaalfeld** [comment]
Was this feature implemented? Is it still in scope?

**Comment by emanuelschuetze** [comment]
Yes, still a valid feature request. Keep it open.
