### ISSUE TITLE
Manager can't reset to default password for other users

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1686]
How can a manager reset the password of an user?

I try this, e.g. for user_id=2:
`$http.post('/users/user/2/reset_password/', {})`
but I get always `405 METHOD NOT ALLOWED`.

**Comment by normanjaeckel** [comment]
You forgot the `/rest/` prefix.

**Comment by emanuelschuetze** [comment]
Right. Thanks. Pull request #1690 created.
