### ISSUE TITLE
Use item.hidden instead of item.type = 2

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1694]
We should use item.hidden as boolean. Default false.
So it is easier (and more self-explaining) to use it in template, e.g. `ng-if="item.hidden"`

**Comment by normanjaeckel** [comment]
First we decided to use the IntegerField with choices because we are not sure whether we have to add another type later. Please let us test the handling of this system before we change the database field again.

**Comment by emanuelschuetze** [comment]
ok

**Comment by normanjaeckel** [comment]
Decision not to change the database fields at the moment. On client side, use 'is_hidden' for read only.

**Comment by emanuelschuetze** [comment]
`s_hidden` is already used on client side.
