### ISSUE TITLE
Assignments rest api requirements

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1706]
Some requirements for assignment rest api:
- nominate_other has no 'is already nominated' check
- autoupdate does not work after delete (other) candidate from list
(assignment detail view), reload helps
- status "blocked" (=3) is not checked while nominating candidate
-> Does we really still need this "blocked" status feature?? I think we can drop this old (ESG) feature which is not important for OpenSlides users...
- post request url for publish/unpublish polls is missing

**Comment by emanuelschuetze** [comment]
- delete request url for remove poll

**Comment by emanuelschuetze** [comment]
autoupdate issue see #1707

**Comment by normanjaeckel** [comment]
First bullet point ist fixed. All others have an own issue or are invalid.

**Comment by emanuelschuetze** [comment]
All done here.
