### ISSUE TITLE
Remove "blocked candidates" feature

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1708]
I think we can drop this old (ESG) feature which is not really important for all(?) OpenSlides users...

Discussed with @normanjaeckel - suggestions:
- rename "assignment_related_users" to "candidates"
- each candidate has a attribute "elected" (true|false)
- remove old "status" (1|2|3) attribute

We want to change it before 2.0.

@ostcar Is this suggestion ok for you?

**Comment by ostcar** [comment]
this is ok for me

**Comment by normanjaeckel** [comment]
We may start a poll on the mailing list whether someone uses the blocked feature before we remove it.

**Comment by emanuelschuetze** [comment]
I asked on openslides-users-de:
http://mail.openslides.org/pipermail/users-de/2015-December/000410.html

**Comment by emanuelschuetze** [comment]
I has been decided: we drop the blocken candidate feature for 2.0: 
http://mail.openslides.org/pipermail/users-de/2015-December/000411.html

@normanjaeckel Please start implement the suggestion of this issue (see first message: https://github.com/OpenSlides/OpenSlides/issues/1708#issue-119102003)
