### ISSUE TITLE
Check upgrade of angular-ui-tree

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1717]
works with 2.2.0
but does not work with 2.10.0
see #1712

**Comment by normanjaeckel** [comment]
We have to check release notes of this package from time to time to see whether they fix the problem in the future.

**Comment by emanuelschuetze** [comment]
I could isolate the problematic angular-ui-tree releases:
With >=2.10.0 there is the "Error: context is null". The last working release is 2.9.0.

I can't say which commit exactly caused the error (can't test single commits with bower because dist directory is updated only on releases), maybe this commit: https://github.com/angular-ui-tree/angular-ui-tree/commit/2559327c2af153c6c3d6f82037df517be032855b

**Comment by emanuelschuetze** [comment]
Pull request #1776 contains a fix to upgrade on 2.9.0. 

Still open: Upgrade to last stable release (currently 2.11.0) without errors.

**Comment by emanuelschuetze** [comment]
Same problem ("Context is null") with 2.13.0.

**Comment by emanuelschuetze** [comment]
Same problem with angular-ui-tree 2.15.0

**Comment by emanuelschuetze** [comment]
@ostcar Do you want to try to debug this "Context is null" bug? Should be enough for 2.1.

**Comment by ostcar** [comment]
no

**Comment by FinnStutzenstein** [comment]
Tested with angular-ui-tree 1.16.0 and 2.17.0: no error anymore! Sorting of agenda and motion categories works. I'll create a PR.
