### ISSUE TITLE
Add publish assignment poll function

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1718]

**Comment by emanuelschuetze** [comment]
Here my fix which needs adaptation on rest api side to provide new publishPoll function (see my mail):
https://github.com/OpenSlides/OpenSlides/compare/master...emanuelschuetze:fix1718?expand=1

**Comment by normanjaeckel** [comment]
Not tested: Adding `required=False` to the votes field in the serializer might do it.

**Comment by emanuelschuetze** [comment]
Works with #1778.

**Comment by normanjaeckel** [comment]
Is this done?

**Comment by emanuelschuetze** [comment]
yes, done.
