### ISSUE TITLE
motion.attachments can not iterate in template

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1722]
I tried to check like this:
``` 
<div ng-if="motion.attachments">
        <h3 translate>Attachments</h3>
</div>
```
And I get a JS error: `10 $digest() iterations reached. Aborting! ...`

**Comment by emanuelschuetze** [comment]
Same for customslide.attachments, see #1809

**Comment by ostcar** [comment]
the problem is only ng-if
