### ISSUE TITLE
Install webfont-opensans with all fonts by gulp

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1726]
https://github.com/sonicparke/webfont-opensans

**Comment by normanjaeckel** [comment]
Am I right that we just need OpenSans Regular? If yes I would propose to use https://github.com/FontFaceKit/open-sans and strip out unused fonts with gulp. This should be easy because this repo looks well maintained and has nice SASS files.

**Comment by emanuelschuetze** [comment]
No, we need in addition to Regular the font styles of Bold and Italic for nicer font face. If you split up these 3 font style note that the css still contains all font faces (and paths).

**Comment by normanjaeckel** [comment]
As discussed I try to add https://github.com/FontFaceKit/open-sans.

@emanuelschuetze Can we remove the font FontAwesome? I can not find it in projector.css so I think it is gone.

**Comment by emanuelschuetze** [comment]
> Can we remove the font FontAwesome?
No! FontAwesome is our important icon font for the web interface - and maybe later also for projector (e.g. clock). The projector redesign is still open.

**Comment by normanjaeckel** [comment]
I tried hard but the repo https://github.com/FontFaceKit/open-sans is somehow special. I propose to save all needed fonts in our own font repository. This we can keep clean and also keep our released package small.

**Comment by normanjaeckel** [comment]
See #1740

**Comment by normanjaeckel** [comment]
This is done.
