### ISSUE TITLE
Add whitespace before triple dots in template

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1729]
I like to do this because it's more beautiful.

**Comment by ostcar** [comment]
@normanjaeckel can you give an example?

**Comment by normanjaeckel** [comment]
The text of a button is `Select...` but I prefer `Select ...` for this button or just `Select` without dots at all. For me the dots without whitespace mean that this word is to be continued. The dots after a whitespace mean that the phrase or sentence is to be continued. We always have the second case. In my example `Select your favourite filter` not `Selecting`

**Comment by emanuelschuetze** [comment]
General UI information: The triple dots are useful if an additional dialog/page/button/etc. opens which provides more information/actions. In contrast to buttons/menu entries without dots which starts the action directly. Example: "Save" vs. "Save as..."

I collected some example applications which uses menu entries WITH and WITHOUT whitespace before dots.
WITHOUT:
- Firefox/Thunderbird
- Chromium
- LibreOffic
- VirtualBox
- Gvim

WITH:
- KDE Kontact
- Pidgin

So for me, there is a clear majority for "without whitespace"... I don't want to fix it.

**Comment by normanjaeckel** [comment]
WITH:
* GNOME Terminal
* Unity
* Gajim

**Comment by normanjaeckel** [comment]
Clear majority for "with whitespaces".

**Comment by emanuelschuetze** [comment]
convinced ;-), see #1771
