### ISSUE TITLE
Add versions of gui and portable to version view

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1747]

**Comment by normanjaeckel** [comment]
I don't know how to do this. Maybe the GUI and the portable have to set some custom environment variables before starting the server. Then I can get the version info from them.

**Comment by emanuelschuetze** [comment]
@ostcar What do you think?

**Comment by ostcar** [comment]
I would like a more general solution.

Each plugin should be listed in the version view. So the gui and the portable would be listed there, if they are (also) plugins. All they whould have to do is set them self inside the installed_apps list in the settings.

**Comment by jsaalfeld** [comment]
Is the portable version still in scope for OpenSlides with the Docker-Images in place?

**Comment by emanuelschuetze** [comment]
I think, it's not important for users/admin to see special version numbers for gui or portable in legal notice page. Gui and portable are no plugins and have currently no maintained version numbers/releases.
=> Closed.
