### ISSUE TITLE
Proposal: New login page before loading Angular site

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1750]
What do you think about creating a general login page which will be shown before the user can enter OpenSlides at all. We can use a standard Django view without AngularJS and this stuff. The advantage would be that we could clearly manage the first data fetching after login (just the first loading of AngularJS) and we can avoid a lot of useless HTTP requests. At the moment the first start generates 12 requests that get HTTP 403.

# Case 1: Guest disabled
- If anonymous user calls any url he gets the login view. We can solve this with a middleware or a smart filter in IndexView and optionally ProjectorView class.
- If a registered user calls an url he gets AngularJS just as in 2.0b1.
- In the top navigation bar there is no Login dialog but only a logout button. If the user clicks this, he posts the logout request and we force a full reload of the page.

# Case 2: Guest enabled
- Any user who calls an url gets AngularJS just as in 2.0b1.
- In the top navigation bar there is also a login button and dialog (but without the button "continue as guest", this is not neccesary any more). The client may force reload after login.

**Comment by emanuelschuetze** [comment]
Your suggestion sounds good. @ostcar What do you think?

**Comment by ostcar** [comment]
I don't like it. To solve it, we have to add django templates again that looks the same as the angular theme.

If the only goal is to get rid of the 403er, then there are other ways. The client knows if he is logged in. (It has a session cookie.) So the client could skip the requests, if he is not logged in. In the rar case, that the session is terminated, the 403er are no big deal.

**Comment by normanjaeckel** [comment]
Not closed: We need a small change on server side WhoAmI view with adaption on client side.

**Comment by emanuelschuetze** [comment]
@normanjaeckel can you explain the open "small change" a bit?

**Comment by normanjaeckel** [comment]
Still open:
- Closing Login Model should not be possible if guest users are disabled.
- If Guest is enabled: Open new page/tab, click continue as guest, then click login -> the continue as guest button is missing.

**Comment by emanuelschuetze** [comment]
All done. Test #1772.
