### ISSUE TITLE
Get user.id in user form

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1752]
We have to find a way to get the user.id for making a post request to rest password in user form in this line: see https://github.com/OpenSlides/OpenSlides/blob/master/openslides/users/static/js/users/site.js#L307
model.id does not has the user.id.

@ostcar Any idea?

**Comment by ostcar** [comment]
I don't understand what you are asking

**Comment by emanuelschuetze** [comment]
Here is the right line again (now fixed on 2.0b1 tag, the line in master is moving after merge last pull requests):
https://github.com/OpenSlides/OpenSlides/blob/2.0b1/openslides/users/static/js/users/site.js#L307
`$http.post('/rest/users/user/' + model.id + '/reset_password/', {})` 
I need the user.id from the selected/modified user in the form. `model` is not defined in the onClick function. 
But `model` is set in UserUpdateCtrl:
https://github.com/OpenSlides/OpenSlides/blob/2.0b1/openslides/users/static/js/users/site.js#L484
`$scope.model = user;`

**Comment by emanuelschuetze** [comment]
It found the solution in #1766 .
