### ISSUE TITLE
Show default admin password in login form only on first start

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1754]
How can we check that 
a) admin user has logged in successfully first time
b) admin user has changed the default password ('admin')

We have to decide after which case (a) or (b) the message on login form ("use admin|admin for first login") should be shown.

(b) was the default in OpenSlides 1.x.

**Comment by emanuelschuetze** [comment]
As discussed: Add new general config option 'loginString' for adding default password information for admin or demo user.

**Comment by ostcar** [comment]
@normanjaeckel I think we can close this. If not, then please reopen
