### ISSUE TITLE
Test plugin API

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1757]
Is JavaScript of plugin loaded?
Write example plugin or update one of our existing plugins to new plugin API.

**Comment by emanuelschuetze** [comment]
@ostcar Can you test it? I can continue update the existing plugins if you show me an example.

**Comment by ostcar** [comment]
no.

@normanjaeckel ?

**Comment by normanjaeckel** [comment]
See #1980.

**Comment by emanuelschuetze** [comment]
#1980 is merged, so closed here.

**Comment by normanjaeckel** [comment]
Some more tests required. I will do this.

**Comment by normanjaeckel** [comment]
Tests done. Plugin API works for now.
