### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1758]
Check and update requirements.txt, requirements_production.txt, bower.json

**Comment by emanuelschuetze** [comment]
@normanjaeckel Can you check the python requirements for 2.0b2 release please?

**Comment by normanjaeckel** [comment]
Checked  requirements.txt and requirements_production.txt. There are no newer releases. So we do not have to change anything. #1889 is just coding style.

**Comment by normanjaeckel** [comment]
Now also package.json is updated. Only bower.json is still open.
