### ISSUE TITLE
first load whoami and then load all data

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#1820]
when an anonymous gets some data and logs on later, then he could have castrated data

**Comment by emanuelschuetze** [comment]
see also #1460

**Comment by ostcar** [comment]
As a workaround http://www.js-data.io/docs/dsclear can be called when the operator changes. Either be adding a callback to operator.onOperatorChange() 

(See https://github.com/OpenSlides/OpenSlides/blob/2307bdc188753c4123db01096e154addda3d6a74/openslides/core/static/js/core/site.js#L37 as example)

or by adding the function at the beginning of loadGlobalData

**Comment by emanuelschuetze** [comment]
@ostcar I added DS.clear() to loadGlobalData, see https://github.com/OpenSlides/OpenSlides/compare/master...emanuelschuetze:fix1820?expand=1
But this does not fixed this issue.  Can you test it please!
My test: reload users list for anonymous, log in as admin, go to users data

**Comment by emanuelschuetze** [comment]
Again a more detailed instruction how to reproduce the current problem with DS.clear() in my test branch:
1. open (reload) /users/ as anonymous user -> no users visible in table!
2. click to elections and back to users -> all x users visible
3. now, login as admin and go to /users/ -> all x users visible (with internal data, like comments)

So, still open: (1) should show all users (after reload!). DS.clear() seems to be clear to much here? 

@ostcar Any hint?

**Comment by emanuelschuetze** [comment]
New suggestion pushed with reload page after login/logout. See #2003.

I discussed with @ostcar the problem with DS.clear(). Here the summary:

The [callbacks](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/users/static/js/users/base.js#L31) will be called if the response of Group.findAll() is back. In this time the other requests (e.g. motion.findAll()) are called.
There are two solutions (for the record):
* send all requests only then if whoami request is finished (very erffortful, maybe impossible!)
* create a new view or adapt whoami which gives back the request.user **and** all groups of request.user. If the group data are available after reload in whoami then OpenSlides does not have to wait on separate group request.

**Comment by normanjaeckel** [comment]
Hm. This is maybe not completely solved, see also #1460.

**Comment by normanjaeckel** [comment]
@emanuelschuetze I don't remember the last status of our discussion. Maybe move milestone.

**Comment by emanuelschuetze** [comment]
This issue should be done if #1460 is fixed. Moved to  milestone 2.1.

**Comment by emanuelschuetze** [comment]
see #2854
