### ISSUE TITLE
Assignment template tasks

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1838]
Assignment tasks:
* [x] detail: publish votes -> votes/elected not visible for normal users
* [x] detail: sort ballots reverse  (latest left)
* [ ] ~~poll: negative votes possible! (only for votes cast and votes invalid)~~
* [ ] poll: show error messages
* [ ] ~~add meta box as in motion (with posts and phase, set phase button for manager)~~

**Comment by normanjaeckel** [comment]
See #1848.

**Comment by normanjaeckel** [comment]
See #1866.

**Comment by normanjaeckel** [comment]
See #1867. All done here (or moved to other issues).
