### ISSUE TITLE
User create form: Is active should be True by default

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1846]
Normally we want new users to be active. If a manager runs in presentation mode he just can not tell the users the randomly generated passwords so there is no harm that they are active. It a manager runs OpenSlides in participant mode he always wants this flag to be true unless a user does suspicious things.

**Comment by ostcar** [comment]
The default is active, only the form is the problem. See also #1861

**Comment by emanuelschuetze** [comment]
closed this duplicate issue, see #1861
