### ISSUE TITLE
Autoupdate after changing user permissions does not work

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1855]
e.g. user gets chat permission -> should show chat link without reload

**Comment by ostcar** [comment]
This problem is not only for chat permission but for any permission. I try to solve it but it could be a design problem that we can not fix for the moment

**Comment by emanuelschuetze** [comment]
Solution should be on client-side: 
If group was changed (e.g. permission changed) client has to refresh page.

**Comment by normanjaeckel** [comment]
Additionally: If user changed and got a new group client has also to refresh page.

**Comment by matakuka** [comment]
This may be handled with autoupdate.py Autoupdate should send changes in operator privileges (just to the operator concerned), and the operator factory needs to $watch for changes. I think when this comes into place, all ng-ifs and os-perms will be updated automatically. 

I'll see what I can do.

**Comment by ostcar** [comment]
With #2794 we added autoupdate for the groups and therefore for the permissions. After the merge of this PR it should be possible for the client to watch the groups of the operator and do something if the permissions change.
