### ISSUE TITLE
Delegate user gets 403 after file upload

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1856]

**Comment by normanjaeckel** [comment]
Question:
If a delegate uploads a file and sends himself as uploader, all is fine. If he sends someone else, he gets 403. If he sends no uploader, then

a) 403
b) 200, the uploader remains empty.

I prefer b).

**Comment by emanuelschuetze** [comment]
(b) is ok for me.

**Comment by ostcar** [comment]
I prefer that he is added as uploader

**Comment by normanjaeckel** [comment]
Solution c) would be ok for me but I dont want to implement this.

**Comment by emanuelschuetze** [comment]
@normanjaeckel @ostcar ping! this is a blocker for me to finish all mediafile issues for 2.0b1.

**Comment by normanjaeckel** [comment]
The base fix (including solution b) is already merged. So this issue is only about solution c) if someone likes this.

**Comment by emanuelschuetze** [comment]
I think this is already done:
A delegate user can upload a file and was set as uploader.
