### ISSUE TITLE
Agenda child items disappear if manager sort items

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1857]
It a manager sorts agenda items (move some items as child) then some items (only the childs?) disappear after autoupdate in agenda list view for normal users.

Maybe a permission and/or tree problem?

**Comment by ostcar** [comment]
Works for me on current master. If you can reproduce it on the master, then please tell me how. If not, then close this issue

**Comment by emanuelschuetze** [comment]
I can't reproduce it any more. So closed.
