### ISSUE TITLE
allow 'trivial changes' in motion update

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1863]
Like in 1.7 we have to support the 'Keine neue Version erzeugen" checkbox in motion update view which shouldn't create a new version.

@normanjaeckel Looks like the rest api still have to provide this support, right?

**Comment by normanjaeckel** [comment]
With #1868 the server supports that you send and extra flag `disable_versioning: true` to disabled versioning. This flag does not check the config so you have to do this yourself for the form.

**Comment by ostcar** [comment]
@normanjaeckel what happens, when the config flag is set to False but the the client sets the flag to true in his request?

**Comment by normanjaeckel** [comment]
A manager client that sends `disable_versioning: True` can do this whatever the config says. A non staff client is not able to use this flag.

**Comment by ostcar** [comment]
ok
