### ISSUE TITLE
Fix serializers for PUT requests

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1871]
At the moment we have two bad hacks: In motion update view and user update view a non staff client can not send a PUT request because on the one hand he is not allowed to change some of the fields, on the other hand the serializer expects all these fields. It has to send a PATCH request and we strip out any field the are not on the whitelist.

(Another bad hack might be also to transform PUT requests to PATCH requests internally.)

I propose the following solution: We split up the serializers (maybe using class inheritance) so that non staff clients get serializers where the fields of the "blacklist" are set to read only fields. Maybe we can find help [here](http://www.django-rest-framework.org/api-guide/serializers/#dynamically-modifying-fields). Then the client can send PUT or PATCH as it like and also the API is not broken.

**Comment by ostcar** [comment]
So for read requests (get one or get all) it would be equal which serializer would be used? This is important to add caching in the future.

**Comment by normanjaeckel** [comment]
If we use the serializer info also to generate a correct OPTIONS view than the serializer has to know which fields would be read only for a specific client and which not.

**Comment by ostcar** [comment]
OPTIONS requests are not problem for the caching

**Comment by normanjaeckel** [comment]
I the proposed solution we have different serializers for different users.

We can do this for 2.1

**Comment by normanjaeckel** [comment]
Look also for PATCH requests in mediafiles and agenda.

**Comment by normanjaeckel** [comment]
Note to myself: Agenda is no problem. Mediafile is solved. Only motion is still open.
