### ISSUE TITLE
Motion diff view between two versions

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1874]
provide diff view link from version history table, like in 1.7

**Comment by donovaly** [comment]
The diff feature is in OS 1.5.1 but since it is not in OS 2.0 and in 2.1 there is an inline editing feature including a diff possibility, this issue could be postponed to OS 2.2.

**Comment by jsaalfeld** [comment]
This could be a feature for #3977

**Comment by tsiegleauq** [comment]
Motion versions do not exist anymore.
"Old" Motions can be re-created using the TimeTravelService. It this still relevant?

**Comment by emanuelschuetze** [comment]
>  It this still relevant?

No.
