### ISSUE TITLE
Allow to edit mediafile title only

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1881]
by using PATCH request like for users/motions

This is a blocker for me to finish my mediafile issues on template side. Should be fixed for 2.0b2.

**Comment by emanuelschuetze** [comment]
I use a PATCH request already in pull request #1884 (in update controller). So please provide the server side.

**Comment by normanjaeckel** [comment]
See #1885.

**Comment by emanuelschuetze** [comment]
Works with #1884
