### ISSUE TITLE
ValueError: The 'mediafile' attribute has no file associated with it

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1883]
After uploading two files via Django rest framework upload form I get an important error. Mediafile list is broken (no changes after reload!):

ValueError at /rest/mediafiles/mediafile/
The 'mediafile' attribute has no file associated with it.

**Comment by normanjaeckel** [comment]
I can not reproduce this.

**Comment by normanjaeckel** [comment]
Maybe #1885 solves it.

**Comment by emanuelschuetze** [comment]
Looks good with current master. Can't reproduce it any more.
