### ISSUE TITLE
403 after try to open customslide detail view for normal users

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1886]
Should be possible for normal users which has agenda.can_see permissions! Please fix for 2.0b2.

**Comment by emanuelschuetze** [comment]
@normanjaeckel hope you can fix this today?

**Comment by normanjaeckel** [comment]
A sorry. The question is why we have this view. It is new and did not exist in 1.7. The problem is that you want me to add agenda permissions to a core feature. Then I also have to check if the user has permission to see hidden items and the like. This disrupts our concept we have until now.

**Comment by normanjaeckel** [comment]
My proposal is to disable the detail view for non staff users (use the permission that already exist, this sould be core.can_manage_projector).
