### ISSUE TITLE
Change display name of permissions

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1895]
Change the display name of all permissions to simpler string. Use don't know about our app-model system. So please use the third string only - like in 1.7.

Example:
"agenda | item | Can manage agenda" ->  "Can manage agenda"

Maybe we keep an additional 'group display name' string, e.g. 'Agenda', for better grouping in a matrix later.

And how we should translate these strings? Should the client do this?

**Comment by normanjaeckel** [comment]
Translation is up to the client. I just changed the display_name.

**Comment by normanjaeckel** [comment]
Client translation still required.
