### ISSUE TITLE
Improve PDF presentation performance

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1910]
See #1903. E. g. do not use `update_projector` when activating a new PDF.

**Comment by emanuelschuetze** [comment]
@normanjaeckel What will be the right projector functions for which action?
e.g. activate new pdf -> prune_elements, update current pdf -> update_projector?

**Comment by normanjaeckel** [comment]
Yes: activate new pdf -> prune_elements, because it is a new projector element (and we say prune because we want to disable all old non permanent projector elements); update current pdf -> update_projector, because we just want to change some special values of the current projector element.

**Comment by emanuelschuetze** [comment]
Ok. And what's wrong with our current implementation in [site.js](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/mediafiles/static/js/mediafiles/site.js#L140)?

**Comment by emanuelschuetze** [comment]
Ah I see: If we activate a pdf (via prune) and then activate a second PDF (then we use update)... But it seems to works without problems, isn't it?

**Comment by normanjaeckel** [comment]
May be it works now but the code is complex although this if-else-condition is not necessary. It can be removed.

**Comment by normanjaeckel** [comment]
@emanuelschuetze wrote in #1903:
> [...] we will improve the whole pdf presentation performance later.
