### ISSUE TITLE
Manage.py start opens two browser windows instead of one.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1920]

**Comment by ostcar** [comment]
I have no interest in the start command. My solution would be to remove it.

**Comment by normanjaeckel** [comment]
Hm. How to start OpenSlides under Linux if you do not use the development version? Which command should `openslides` run? The start script is very important for a nice user experience although we do not need it as developers.

**Comment by ostcar** [comment]
The normal user has debug=False and therefore the reload function of tornado is disabled. So this bug does not occur for him.

**Comment by emanuelschuetze** [comment]
That's wrong! Please test 2.0b2 where debug=False by default (correct) but if you run `openslides start` two browser tabs opens.
