### ISSUE TITLE
Caching of REST data

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1953]
We need a caching mechanism for data provided by Django rest framework!

Example: Server sends an auto update to all clients that motion 42 is updated. Each client which currently shows motion 42 sends a GET request to server to receive the current motion 42 object. Each get request makes a DB query. This is a big performance issue if you want to use OpenSlides in participant mode...

So maybe we find a quick solution for 2.0?
See also the discussion in Oskars old pull request #1444 (which wasn't merged).
@normanjaeckel Can you describe your cache suggestion?

@boehlke As discussed today: Please add your ideas for @normanjaeckel .

**Comment by emanuelschuetze** [comment]
An important requirement: The caching mechanism have to check the permission of the requested user! (E.g. a manager is allowed to see more information from rest api than a normal user)

**Comment by normanjaeckel** [comment]
I am not sure whether the scenario is correct. The autoupdate data should  contain the updated motion data so that the clients do not have to fire new GET requests. But internally the server fires (multiple) GET requests to himself so build these data for the clients.

**Comment by normanjaeckel** [comment]
We have to separete any caching efforts from optimization of autoupdate process. See #2008.

**Comment by emanuelschuetze** [comment]
@normanjaeckel Is this issue fixed by our current caching system?

**Comment by normanjaeckel** [comment]
Should be done.
