### ISSUE TITLE
Gulp production bugs

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#1955]
* [x] Problem 1: the gulp tasks 'js-libs', 'fonts-libs' and 'ckeditor' runs very long! (>3min).
* [x] Problem 2: The two fonts (Roboto and Open Sans) are not installed correctly. You can't use it in template.

**Comment by emanuelschuetze** [comment]
Problem 1 is fixed with #1958.

**Comment by emanuelschuetze** [comment]
@normanjaeckel Any idea how we can fix problem 2? Looks like this was introduces with cssnano(?)...

**Comment by normanjaeckel** [comment]
Problem 23 fixed by #1960
