### ISSUE TITLE
Create own tinymce-i18n repository

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1973]
The repo should  provide all(?) or only used tinymce i18n files via bower. OpenSlides should install required tinymce-i18n files via bower. You can download all languages from http://archive.tinymce.com/i18n/index.php

Currently we added i18n files manually to 'openslides/locale/tinymce/'

See https://github.com/OpenSlides/OpenSlides/pull/1972#discussion_r52851184

**Comment by normanjaeckel** [comment]
This is done.
