### ISSUE TITLE
FileNotFoundError if mediafile is deleted on file system

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#1988]
If you delete an uploaded file from /media/file/ and then open the mediafile list view you get a FileNotFoundError which should be catched. (Otherwise you can't access to the the mediaflie list view any more.) 
```
[..]
openslides/mediafiles/serializers.py", line 27, in to_representation
        result['pages'] = PdfFileReader(open(value.path, 'rb')).getNumPages()
    FileNotFoundError: [Errno 2] No such file or directory:
```

**Comment by normanjaeckel** [comment]
Can not reproduce this error.

**Comment by normanjaeckel** [comment]
Ah it is only for PDF.
