### ISSUE TITLE
Error Handling for OpenSlides Linux

### ISSUE THREAD

**Issue by HerbertTot** [OpenSlides/OpenSlides#1990]
When OpenSlides is installed on a Server installation of e.g. Ubuntu, and you want to start openSlides, it terminates with the error: "can not find a browser". But after i modified the main.py and commend out the function startBrowser(), it runs perfect. 

So there shoud be e.g. a simple try and catch around the function startBrowser()

**Comment by emanuelschuetze** [comment]
You can use the command `openslides start --no-browser` to run OpenSlides without opening a browser.

See also `openslides start --help`:
```
 --no-browser          Do not launch the default web browser.
```
