### ISSUE TITLE
Mass assign users to groups

### ISSUE THREAD

**Issue by larsboehnke** [OpenSlides/OpenSlides#1991]
As a user I would like to mass select users and assign them to a specific group.

**Comment by emanuelschuetze** [comment]
Good use case. Thanks. I'll try to do it for 2.0.

**Comment by emanuelschuetze** [comment]
@larsboehnke Maybe you can test the current development version of OpenSlides master that the implemented feature is useable for you?

**Comment by larsboehnke** [comment]
@emanuelschuetze I try it later, thanks :+1:
