### ISSUE TITLE
Renaming --development option

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2001]
I think about if the option `--development` (of `openslides start --development`) has the right wording... It's not really a development feature to keep all settings/database etc. in the same directory and not in .config and .local. 

So my suggestion: rename this option (and the directory!) and improve the help text (`command for development purpose`) which is not really helpful to understand what this option make.

(split out this issue from #1998)

**Comment by normanjaeckel** [comment]
The directory only appears for developers. What should be the name of it? The `--development` option is for plugin developers. They can install openslides via pip and still use `openslides` with settings and user file in a local directory. So what should be the name of this option?

**Comment by emanuelschuetze** [comment]
> The directory only appears for developers. 

Why? I think this option is not useable for developers only! As I wrote there are also use cases that I want to install several 2.0 installations in parallel directories - each with it's own database in the `developement` directory. 
You are agreed, that this option is also a serious option for production use?

If you we should think about a better name for this option. E.g. `--local`, ...(I have no better idea)?

**Comment by emanuelschuetze** [comment]
as discussed: suggestion `--local-installation`
