### ISSUE TITLE
user.comment should visible only for managers

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2004]
because it is an internal comment (see also 1.7). Please adapt it in rest api.

**Comment by normanjaeckel** [comment]
Hm. @emanuelschuetze Please have a look at users/serializers.py and compare UserShortSerializer with UserFullSerializer. At the moment we user the first one for read access for users **without** the permission `users.can_see_extra_data` and the second one for the rest. This has nothing to do wih the permission `users.can_manage`. (Additionally we exclude the default password in some situations.)

I can now add some extra logic to hide the comment field for users with `users.can_see_extra_data` but without `users.can_manage` but then the permission `users.can_see_extra_data` is almost useless.

What about removing this permission from registered and anonymous group add adding it to the staff group. So the default would be that the comment field (and the presence and activation status) is hidden but anybody can configure the permissions as he/she likes.
