### ISSUE TITLE
Edit motion sends 5x autoupdate

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2007]
Edit a motion. Server sends autoupdate 4x (you get 4 get requets to server).

**Comment by emanuelschuetze** [comment]
@ostcar This was one of the last important 2.0 issues for you. Can you please look at this? Thanks.

**Comment by ostcar** [comment]
As we disgust on telephone. The reason for this bug is deep in our autoupdate system. I don't see any way we can fix this in the 2.0 or in any later version that is based on the same sytem

**Comment by ostcar** [comment]
A possible solution is to use https://docs.djangoproject.com/en/1.9/topics/db/transactions/#performing-actions-after-commit This needs at least django 1.9

For this solution we have to make sure that we use transaction in any view! 

In the post_save_signal we do not send the object to the clients but save the id and collection_string to a ```set```. With ```on_commit``` we call a function that goes throw this list, gets the object from the database and sends it to all clients.

This should be easy but needs a lot of testing.

**Comment by normanjaeckel** [comment]
Another solution would be to use a middleware: At the beginning of a request an empty dictionary is created. Every time a model is saved (trigger this by post_save signal) we add the root instance of the saved model to this dictionary. The key is a combination of collection name and id so if the same model is saved multiple times, the dictionary contains only the last instance. At the end of the request, the middleware refreshs alls instances in the dictionary from database and creates the JSON output for each and handles it to tornado SockJS autoupdate logic (`OpenSlidesSockJSConnection.send_object()`).

**Comment by normanjaeckel** [comment]
Test this after the so called big mode is committed.

**Comment by ostcar** [comment]
@emanuelschuetze is this still an issue?

**Comment by emanuelschuetze** [comment]
This works with current master:
Update a motion gets only a PATCH request. No GET requests after autoupdate. So closed.
