### ISSUE TITLE
Optimize autoupdate.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2008]
The autoupdate process has to be optimized. As discussed on phone we try the ideas of @boehlke and me but do not use Python model instances but pre-serialized strings to be handled by Tornados method to send data to all clients. See #1953.

**Comment by normanjaeckel** [comment]
Ah, next problem: At the moment we also forward the language settings to the internal RESt request, see [here](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/utils/autoupdate.py#L128). If I get a pre-serialized string I do not know how to transform this string concerning the correct language for each client user. One possibility might be to send all translatable data in all languages but then the client has to parse this. @emanuelschuetze Waht do you think?

**Comment by emanuelschuetze** [comment]
> One possibility might be to send all translatable data in all languages but then the client has to parse > this.

I don't like this... Then we have to parse a lot of strings on client-side (e.g. all config keys and default values). Is there still an other possibility?

And if you send always the English strings and the client will translate it - like motion states or users permissions?

**Comment by normanjaeckel** [comment]
Please see this [question and answer](http://stackoverflow.com/questions/35702776/why-does-tornados-wsgi-support-block-for-more-than-one-request/). It looks like that we should not use Tornado as WSGI server never ever but think about the big solution (or even a middle solution with built-in WSGI server from Django, Werkzeug or thelike or even a separate Tornado process) and do not spend any time optimizing the so called small solution. In any solution with the WSGI part in the same thread it would be pretty easy to run a DNS attack on the server. Just us Apache benchmark and send continously two requests at once. This would block the server regardless of its RAM and CPU power.

**Comment by normanjaeckel** [comment]
Hm. Maybe we are are little bit lucky that we don't use any of Tornado's async methods so we do not have the problem described above. Nevertheless I think that we better should find a middle solution right now.

**Comment by normanjaeckel** [comment]
See #2018 for the solution for the database problem. The problem with the blocking tornado still exists.

**Comment by emanuelschuetze** [comment]
DB optimizations done with #2018.
Can we close this issue?

**Comment by normanjaeckel** [comment]
The problem with the blocking tornado still exists. Nevertheless moved this to 2.1

**Comment by emanuelschuetze** [comment]
@normanjaeckel Is this issue still valid with current master?

**Comment by normanjaeckel** [comment]
I think it is invalid.
