### ISSUE TITLE
Projector Motions wrong election result

### ISSUE THREAD

**Issue by PaulchenP86** [OpenSlides/OpenSlides#2009]
Projector shows at election results (Motions) "-1" or "-2" instead of "Majority" or "undocumented"
![elecresult](https://cloud.githubusercontent.com/assets/17482167/13333162/ed378cbc-dc05-11e5-88d7-780bc43027d2.png)

**Comment by emanuelschuetze** [comment]
Thanks for reporting it! I'll fix it for 2.0.

**Comment by emanuelschuetze** [comment]
Fixed with #2015.
@PaulchenP86 Please note also the important motion poll fix in #2017.
So, current master should works for you now. Let us know if not...
