### ISSUE TITLE
Development / local installation option does not work for Django commands

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2013]
This works:
```
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install openslides-x.x.tar.gz  # Use correct filename here
$ openslides start --development
```
But the following not:
 ```
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install openslides-x.x.tar.gz  # Use correct filename here
$ openslides createsettings --development
$ openslides migrate --development
$ openslides runserver --development
```

**Comment by emanuelschuetze** [comment]
@ostcar Can you look at this issue please. Could be important for 2.0. (Note: the options --development was renamed with #2012 to --local-installation)

**Comment by ostcar** [comment]
At the moment the argument is only an argument for the start command and the createsettings command. See line 92 and 107 in \__main__.py. To fix this, it has to be a global argument, like --version.

Then setup_django_settings_module(settings_path, development=development) has to be called at a global place like 32 in \__main__.py.

I have no interest in fixing this.

**Comment by emanuelschuetze** [comment]
@normanjaeckel Can you look at this issue please?

**Comment by normanjaeckel** [comment]
The problem was introduced by the [grand refactoring of the start script about one year ago](https://github.com/OpenSlides/OpenSlides/commit/35024764cf38cb19395bd773d29f5b8d463f3024). Before the runserver and syncdb command were custom commands not Django commands.

Maybe you can use the [add_arguments() method](https://docs.djangoproject.com/en/1.9/howto/custom-management-commands/#accepting-optional-arguments).

**Comment by ostcar** [comment]
A hint how to use openslides with runserver with a specific settings:

1. Create the settings in a specific folder, for example ```mysettings/settings.py```

2. Go to this folder, for example ```cd mysettings```

3. Run openslides with the following command:
```
PYTHONPATH='.' DJANGO_SETTINGS_MODULE='settings' openslides runserver -p 12345
```

**Comment by normanjaeckel** [comment]
Conslusion of our last telephone conference: The `--local-installation` option is only a helper for the OpenSlides start command. So we do not implement it for the Django commands like runserver. This means you have to use either start or set the environment variables, see @ostcar's hint.
