### ISSUE TITLE
Add help text how to search partial words with whoosh

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2019]
The global search with whoosh allows to search for full words but also for partial words. 

Example: If you have an agenda item title "foobar" you can search for `foobar` or `foo*` to get the item as search result.

There should be at least a help text to explain how to find partial words. Or improve whoosh to support partial word searching without wildcard char (*).

**Comment by matakuka** [comment]
I'm doing this with #2239
