### ISSUE TITLE
Speech

### ISSUE THREAD

**Issue by PaulchenP86** [OpenSlides/OpenSlides#2029]
2b5: End current speech and "stop" doesn't work for the last speaker

**Comment by emanuelschuetze** [comment]
I can't reproduce it. I added some speakers to a list of speakers. For each speaker I can click "start" and "stop" - or "Begin next speech" and "End current speech".

So what's your observed problem? Do you see any errors on JS console?

**Comment by PaulchenP86** [comment]
Ok, I'm really not sure if is it a bug: If the last speaker ended his speech, I click on "stop", than he/she should not be longer the current speaker in my understanding

**Comment by emanuelschuetze** [comment]
That's exactly what currently happens...
* Add a user to list of speakers (user moves to 'next speakers')
* Click "start" (user moves to 'current speakers')
* Click "stop" (user moves to 'last speakers')

So all right for me. What's your problem with this behavior?

**Comment by emanuelschuetze** [comment]
Or do you mean the projector slide? There, always the last X speakers (you can change it in config) are shown in grey font color. So if the list is finished the last X speakers are on the slide. That's no bug.

**Comment by PaulchenP86** [comment]
No, that doesn't work for me, I get this error for the last speaker in js console (Safari):
"Error: No input to stringily
stringify@[native code]
endSpeech@http://localhost:8000/static/js/agenda/site.js:321:85
fn
callback@http://localhost:8000/static/js/openslides-libs.js:46237:19
$eval@http://localhost:8000/static/js/openslides-libs.js:38554:28
$apply@http://localhost:8000/static/js/openslides-libs.js:38654:30
http://localhost:8000/static/js/openslides-libs.js:46242:29
dispatch@http://localhost:8000/static/js/openslides-libs.js:17085:32
handle@http://localhost:8000/static/js/openslides-libs.js:16897:33
(anonyme Funktion)openslides-libs.js:35024
(anonyme Funktion)openslides-libs.js:31792
$applyopenslides-libs.js:38658
(anonyme Funktion)openslides-libs.js:46241
dispatchopenslides-libs.js:17084
handleopenslides-libs.js:16896"

**Comment by emanuelschuetze** [comment]
I found the bug and fixed it in #2040 ! It was an error in Safari only. Thanks for the JS console output. That was helpful.
