### ISSUE TITLE
Refactor agenda item manager methods

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2031]
This issue is valid after quickfix #2030 is merged.

Some of the methods evaluated a queryset and return a generator. In ItemViewSet get_queryset() we use such a generator but have to run it to filter a new queryset because the method must return a Django QuerySet instance. But now we hit the database two times. Try to fix this.

**Comment by ostcar** [comment]
This could be optimied when the first db-query would only get the ids of the items

**Comment by ostcar** [comment]
I don't think this optimization is so important.

**Comment by jsaalfeld** [comment]
Closed, since this isn't important (and maybe obsolete by the time)

**Comment by normanjaeckel** [comment]
(Even if not important) the issue is still valid.
