### ISSUE TITLE
Do not use raw SQL during migration.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2035]
At the moment we use a raw SQL query to create the default projector. I introduced this in #2018 because using `Projector.objects.create()` would fire the post_save signal and then our refactored autoupdate tried to get access on model attributes but this attributes do not exist during migration.

How can we avoid this? The best would be to use `Projector.objects.create()` but without fireing or receiving the autoupdate signal.

Any ideas?

**Comment by ostcar** [comment]
You could use https://docs.djangoproject.com/en/1.9/ref/models/querysets/#bulk-create which does not call save and therefore does not send the signal
