### ISSUE TITLE
404 after try to open a motion detail view as guest

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2038]
Split out issue from https://github.com/OpenSlides/OpenSlides/pull/2030#issuecomment-192706200

* As admin: Create a motion (and show motion as hidden item in agenda).
* Then try as guest to open motion detail view -> 404 of /rest/agenda/item/3

The client should not try to fetch agenda/item URL if the item is hidden.

**Comment by emanuelschuetze** [comment]
> The client should not try to fetch agenda/item URL if the item is hidden.

@normanjaeckel This is difficult because for the motion detail view we fetch the motion (via Motion.find()) and load their related agend item (with Motion.loadRelations(...) which fails if user has no 'see_internal_items' permission). But only when the related agenda item is loaded the client could check if this item is hidden.

see https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/js/motions/site.js#L62

Any hints?

**Comment by normanjaeckel** [comment]
Sorry I don't know much about this client relation loading stuff. Maybe you can go into the load relations method, catch the 404 error and set an empty/hidden item attribute to the motion in this case.

**Comment by emanuelschuetze** [comment]
@ostcar Any idea how we can solve this for 2.0?

**Comment by ostcar** [comment]
Do I understand correctly: You want to load the related item, but only if the item is not hidden. But the information if the item is hidden, is part of the item. So the only way to know if you have to load the item is by loading it?

So in conclusion, you have to load the item. If you don't like the (hidden) 404 (in the console) then the server has to be changed that in this case a nearly empty item object is returned to the client with has only the field {is_hidden: true}. I am not sure if the effort is worth it.
