### ISSUE TITLE
/rest/agenda/item/ is visible for users without agenda.can_see permission

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2047]
To reproduce: Activate guests. Disable the agenda.can_see permissions for guest group. Open /rest/agenda/item/ as guest
-> The guest user can see all agenda items. Expected: 403

**Comment by normanjaeckel** [comment]
I can't reproduce this.

![screenshot](https://cloud.githubusercontent.com/assets/2073844/13890906/3bb75878-ed4e-11e5-9831-a2db609ac34e.png)

**Comment by emanuelschuetze** [comment]
Right, with a fresh db it works for me, too.
