### ISSUE TITLE
Problematic version of setuptools.

### ISSUE THREAD

**Issue by frauenknecht** [OpenSlides/OpenSlides#2066]
Certain circumstances cause to fail with following error:

ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

In openslides/utils/plugins.py the statement 'from pkg_resources import iter_entry_points' caused this error with more recent versions of setuptools. It is the same with the latest version 20.6.7
At the moment we are using setuptools < 20 which brings up a version 19.7. 

It seems to be that all versions later than 19.2 are broken.

The only solution at the moment would be to pin the version to 19.2 in requirements.txt

**Comment by emanuelschuetze** [comment]
@frauenknecht Please prepare a pull request for requirements_production.txt and test that is works for your mac os portable.

**Comment by normanjaeckel** [comment]
The setuptools guys wrote that only https://github.com/pypa/setuptools/issues/229 was done between 19.2 and 19.3. They are discussing about the same error message and seem to have a solution. Can you check this please?

**Comment by frauenknecht** [comment]
OK, the setuptools guys got similar weird experiences. I have a python 3.5 virtual env. No py2 libs. Setuptools ist installed as a wheel; no eggs! I can do a  'python -c "from pkg_resources import iter_entry_points"' with any version of setuptools. No errors at all. But in the portable app the ImportError occurs with all versions 19.3 onward.

I still not get the point what my problem really is. But it is clear that the code line 
'from pkg_resources.extern import packaging' in pkg_resources.__init__.py caused the ImportError. This line was introduced in version 19.3. And it is also clear that the enviroment py2app builds is for some reason not suitable for setuptools versions greater than 19.2

I'm still investigating...

**Comment by frauenknecht** [comment]
According to my previous post, there is an obvious solution. Just make the packaging package an explicit dependency in py2app and everything works like a charme.

Lessons learned: In Versions 19.3 and later setuptools expects libs such packaging as a extern not a vendor lib. (The setuptools guys were talking about that in thier thread). I have no idea what is it good for, but this is exactly the change in the code.

This means: Bug fixed!

**Comment by emanuelschuetze** [comment]
Great. So I close this issue...
