### ISSUE TITLE
Motion form can't save if text editor field  contains default value

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2069]
Open new motion dialog. Enter title. Click save.
-> Motion can't save. Error message occurs on the top left corner: "Bitte füllen Sie dieses Feld aus."

Failure occurs only with angular-ui-tinymce 0.0.15. v0.0.14 works without problems.
Problematic commit is https://github.com/angular-ui/ui-tinymce/commit/1915e8ac99a4c13531ab2979bb0f30b96120134b. If you revert this commit it works.

**Comment by normanjaeckel** [comment]
Check if 0.0.16 is working (after it is released).
