### ISSUE TITLE
Support setuptools 20

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#2078]
At the moment we only support setuptools<20.0 but in Ubuntu 16.04 there is setuptools 20.3 in the packages. To make the creation of a ubuntu package possible after the 2.0 release, we should change the requirements_production.txt to support setuptools 20.

http://packages.ubuntu.com/xenial/python3-setuptools

**Comment by emanuelschuetze** [comment]
@normanjaeckel Can you make a PR please?

**Comment by ostcar** [comment]
I created the pr, but it is hard to test. I would be glad if one of you could do this

**Comment by emanuelschuetze** [comment]
@ostcar Please do not created a branch in our OpenSlides repo: 
https://github.com/OpenSlides/OpenSlides/tree/support-setuptools-20
Using your own repo for pull requests is better.

**Comment by emanuelschuetze** [comment]
@ostcar Why is it hard to test? What should be tested?

**Comment by ostcar** [comment]
Sry. I tried to edit the file on github directly. I did not know that this creates a new branch in our main repo.

It is hard to test, because a python package has to be created. I never did this.
