### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by preske87** [OpenSlides/OpenSlides#2089]
Good Morning,

did install openslides and now when trying to start it I get this

`Traceback (most recent call last):
  File "/usr/local/bin/openslides", line 9, in <module>
    load_entry_point('openslides==2.0', 'console_scripts', 'openslides')()
  File "/usr/local/lib/python2.7/dist-packages/openslides/__main__.py", line 25, in main
    parser = get_parser()
  File "/usr/local/lib/python2.7/dist-packages/openslides/__main__.py", line 150, in get_parser
    help_text))
TypeError: __init__() takes exactly 3 arguments (4 given)`

Environment is Debian Linux.

**Comment by emanuelschuetze** [comment]
You have to use Python 3.4+. See README.

**Comment by preske87** [comment]
Hello and thank you. I now have installed also 3.4.4, but how can I tell openslide to use python 3.4.?

**Comment by emanuelschuetze** [comment]
You need a virtual python 3.4 environment, see https://github.com/OpenSlides/OpenSlides/blob/master/README.rst#b-setup-a-virtual-python-environment-optional

**Comment by preske87** [comment]
Hello and Thank you, this made the trick. But now I am faced the next challenge: The port 8000 on my server is already in use; and starting `openslides` with parameter `--port` is replied with `unknown command: --port`
