### ISSUE TITLE
Support Schulze voting system

### ISSUE THREAD

**Issue by ximex** [OpenSlides/OpenSlides#2092]
https://en.wikipedia.org/wiki/Schulze_method

**Comment by emanuelschuetze** [comment]
@ximex Interesting feature request! Can you help implement this?

**Comment by ximex** [comment]
There are many already implementations:
- https://github.com/dgruss/schulze
- https://github.com/bjornlevi/schulze
- https://github.com/search?utf8=%E2%9C%93&q=schulze

We used the first one in our organization.

**Comment by PeterTheOne** [comment]
I would like to help with this, but I don't know much about the code base and python.. ^^

@emanuelschuetze can you outline what needs to be done to add another voting system? Or what files would need to be touched?

**Comment by normanjaeckel** [comment]
Hm. We should first discuss whether this should be a (configurable) core feature (means you can activate this method once per election/assignment or globally for all elections/assignments in the frontend config or if we want to have a plugin that adds a new module / main menu tab. The last approach has the advantage that we can develop all features we need for this but do not have to care about every aspect in our core modules (like PDF ballot papers ...). But of course this is only one way ...

**Comment by PeterTheOne** [comment]
I think it would be good if the core would support multiple voting systems out of the box.

**Comment by normanjaeckel** [comment]
Ok. Then we need a new entry for [this config var](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/assignments/signals.py#L18) and then someone has to implement the logic in backend and frontend. First one should have a look at the poll module and assignment/models.py and assignments/views.py and assignments/serializers.py. Just look for the config variable and try to add the differnent logic at the respective places.

**Comment by PeterTheOne** [comment]
Thanks, I will have a look..

**Comment by PeterTheOne** [comment]
https://github.com/bradbeattie/python-vote-core also looks good.

**Comment by jsangmeister** [comment]
Progress tracked in https://github.com/OpenSlides/OpenSlides/issues/6724
