### ISSUE TITLE
Move all config translations from REST API to client side

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2093]
The config labels and values should translated by client that an user can switch languages which also switch the config translations. So move all config translations to angular and translate it in JavaScript.

see also #2025

**Comment by emanuelschuetze** [comment]
@matakuka Do you want to try this issue? Please ask me if you need help or more info.

**Comment by emanuelschuetze** [comment]
You can make it as we do it for the permission strings, see:
https://github.com/OpenSlides/OpenSlides/blob/master/openslides/users/static/js/users/site.js#L966
Copy all config strings into core/site.js and remove the ugettext functions and imports from config strings in python files.

**Comment by emanuelschuetze** [comment]
Maybe this example commit deea2224344ad8c72338cdcca888afd2cf11e5b2 helps you to understand it better what to do.

**Comment by matakuka** [comment]
this issue is already merged in master (#2194), so it can be closed (I see no button to do it myself)
