### ISSUE TITLE
How can i update translation?

### ISSUE THREAD

**Issue by johnfelipe** [OpenSlides/OpenSlides#2094]
I translate to spanish but my instance

http://181.135.123.118:8001/login

Is not translate it 100%

Tnks

**Comment by PeterTheOne** [comment]
Have a look at https://www.transifex.com/openslides/openslides/

**Comment by normanjaeckel** [comment]
We can see [here](https://www.transifex.com/openslides/openslides/language/es/) that Spanish has 100% for OpenSlides 2.0.

@emanuelschuetze I can confirm that at least some strings in config view are not translated (checked language menu and browser settings).

**Comment by PeterTheOne** [comment]
> We can see here that Spanish has 100% for OpenSlides 2.0.

`403 Forbidden Access`

**Comment by emanuelschuetze** [comment]
@johnfelipe Thanks a lot for your finished Spanish translation! If you want to test your translation work in OpenSlides you have to follow the instruction here:
https://github.com/OpenSlides/OpenSlides/blob/master/openslides/locale/README.txt
May you can make a pull request with your both language files? Otherwise I will integrate it before we make our next 2.x release.
Can you help to finish the openslides.org translations? After that I'll make your work online...

@PeterTheOne You have to login to see the detail pages of transifex.

**Comment by johnfelipe** [comment]
Where i find this path?
openslides/locale/angular-gettext/template-en.pot
openslides/locale/en/LC_MESSAGES/django.po

I have this path only

/home/felipe/OpenSlides/.virtualenv/
/home/felipe/.config/openslides/

Pls help me to translate completly to spanish version

**Comment by normanjaeckel** [comment]
Try `/home/felipe/OpenSlides/.virtualenv/lib/python3.4/site-packages/openslides/locale/...`

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~$ cd /home/felipe/OpenSlides/.virtualenv/lib/python3.4/site-packages/openslides/locale/
	felipe@felipeurrego:~/OpenSlides/.virtualenv/lib/python3.4/site-packages/openslides/locale$ ./node_modules/.bin/gulp pot
	-bash: ./node_modules/.bin/gulp: No such file or directory
	felipe@felipeurrego:~/OpenSlides/.virtualenv/lib/python3.4/site-packages/openslides$ ./node_modules/.bin/gulp pot
	-bash: ./node_modules/.bin/gulp: No such file or directory

What is pwd for do `./node_modules/.bin/gulp pot`

**Comment by normanjaeckel** [comment]
Ah sorry. You can not use our development tools like gulp in a production instance. You have to use a development instance. See [DEVELOPMENT.rst](https://github.com/OpenSlides/OpenSlides/blob/master/DEVELOPMENT.rst).

**Comment by johnfelipe** [comment]
But i need production instance, how do that?
Uninstall latest?

**Comment by normanjaeckel** [comment]
You can checkout a development instance, then do your translation specific work and copy the respective files to the respective places in your production instance. Or you can even use a development instance for production if you set `DEBUG=False` in your settings.

**Comment by johnfelipe** [comment]
i translate correctly and is not 100% in spanish
Pls help me

**Comment by johnfelipe** [comment]
![nospanish2](https://cloud.githubusercontent.com/assets/428820/15379896/1058b1b8-1d37-11e6-8b73-8e0a57675913.png)
![nospanish](https://cloud.githubusercontent.com/assets/428820/15379897/105b9216-1d37-11e6-86fa-3bb187b75d45.png)

**Comment by normanjaeckel** [comment]
As you see [here](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/locale/angular-gettext/es.po#L345) the string "Change password" is not translated to Spanish in our current codebase. The last time we updated the codebase via Transifex was the 12th April 2016. All translations you made after this date (in Transifex) will come for the next release but they are not here at the moment. Meanwhile you can use you own translation file for your own (local) OpenSlides instance as described above (Checkout a local development codebase, change the file `es.po`, run the `translations` gulp task, restart you OpenSlides instance.).

**Comment by johnfelipe** [comment]
![aunfalta](https://cloud.githubusercontent.com/assets/428820/15516187/4bd10d6a-21b7-11e6-832b-3053c0a2461d.png)

![proyector](https://cloud.githubusercontent.com/assets/428820/15516270/b1018fb6-21b7-11e6-9b40-7f00d1fb7cb3.png)
![general](https://cloud.githubusercontent.com/assets/428820/15516271/b117bf48-21b7-11e6-9667-f146fdff7afd.png)

Agenda
Mociones
Las elecciones
Users

Still in english lang

i have already downloaded in

/home/felipe/OpenSlides/openslides/locale/angular-gettext/es.po
/home/felipe/OpenSlides/openslides/locale/es/LC_MESSAGES/django.po
/home/felipe/OpenSlides/openslides/locale/es/LC_MESSAGES/django.mo

and this is commands i use for compile

	cd OpenSlides

	source .virtualenv/bin/activate

	django-admin.py compilemessages

	node_modules/.bin/gulp --production

	python manage.py runserver 0.0.0.0:8001

pls help me for fix this translation issue

**Comment by johnfelipe** [comment]
anyone?

**Comment by emanuelschuetze** [comment]
I created a pull request with your updated Spanish translation files from transifex:
https://github.com/OpenSlides/OpenSlides/pull/2167

**Comment by emanuelschuetze** [comment]
I found the bug: The spanish language was not added to django settings file (global_settings.py). Now I added it with #2167. Spanish strings a now visible for e.g. config fields.

**Comment by johnfelipe** [comment]
Then i do git pull and update all or what is good process?

**Comment by johnfelipe** [comment]
git pull and nothing more?
