### ISSUE TITLE
Messages and timers during file presentation

### ISSUE THREAD

**Issue by lesteenman** [OpenSlides/OpenSlides#2096]
When starting a presentation from a file (PDF), I can't seem to show any other elements, like messages or timers. It seems that there is no way to change the presentation from fullscreen to non-fullscreen.

**Comment by lesteenman** [comment]
This would likely be fixed by solving #2098 as well, although being able to show messages during a fullscreen presentation is something I've always missed in OpenSlides 1.6.

**Comment by emanuelschuetze** [comment]
To show messages and countdowns during pdf presentation you have to reduce the z-index of the `.fullscreen` css class in projector.css:
https://github.com/OpenSlides/OpenSlides/blob/master/openslides/core/static/css/projector.css#L94
I think it's not desired to "disturb" a presentation with activated projector elements. If you have good use cases for it we can discuss it.

**Comment by lesteenman** [comment]
We have use cases for both, although one is arguably not too strong.

Speakers can use presentations, but they still have a limited time. Thus, being able to show the countdown during his slideshow would really help.

As for messages: We occasionally use them to hush people, or to announce a short break. For the latter, leaving fullscreen mode for a bit would not be too bad. 

However, I wonder why being able to disturb a presentation with activated elements would be considered bad. If you do not want to show the elements, you can hide them with one click. Are there use cases where you want to keep the elements in the background during a fullscreen presentation?

**Comment by normanjaeckel** [comment]
Sounds reasonable to we can reduce the z-index in v2.0.1. or 2.1.x

**Comment by emanuelschuetze** [comment]
Ok.
