### ISSUE TITLE
No possibility to leave fullscreen during file presentation

### ISSUE THREAD

**Issue by lesteenman** [OpenSlides/OpenSlides#2098]
It seems there's no way to exit the fullscreen mode in a file presentation, like there used to be in Openslides 1.6

**Comment by emanuelschuetze** [comment]
Do you have really use cases where you want to project a pdf file *without* fullscreen mode? Then your presentation is not fit into window.

**Comment by lesteenman** [comment]
Only combined with #2096. Having to leave a presentation altogether to show messages or timers is no real option, as you will lose track of the current page you were on.

**Comment by normanjaeckel** [comment]
So if #2096 is fixed we can close this issue?

**Comment by lesteenman** [comment]
If this is by design rather than an oversight, then I'd just close it right away.
