### ISSUE TITLE
Add time field for new agenda items.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2100]
We should discuss if we want to support that the user sets the agenda item time when he creates the item. At the moment he has to create it and then click "Quick Edit".

**Comment by donovaly** [comment]
That one cannot directly specify the time is a regression to OS 1.5.1, see the Benutzherhandbuch where this feature is still described:
https://docs.openslides.org/de/Tutorial_2.html

**Comment by emanuelschuetze** [comment]
I don't like it to put the duration field in all forms (topic, motions, assignments). It's too much. With our ne agenda table design we provide a new one-click editiable possibility for all the metadata (duration, comment, done, internal).
-> won't fix
