### ISSUE TITLE
Add Closed Caption to Projector

### ISSUE THREAD

**Issue by johnfelipe** [OpenSlides/OpenSlides#2102]
Is possible integrate CC to projector
http://181.135.63.86:3001/room/ID/26157?viewMode=broadcast, pls review this example, clic in "Activar" and with microphone speak spanish normally

Stay alert
Tnks

**Comment by johnfelipe** [comment]
Is possible integrate Caption Log 

![ccopenslides](https://cloud.githubusercontent.com/assets/428820/15397119/8c9bbe9c-1da4-11e6-942e-af268b44bee2.png)

**Comment by normanjaeckel** [comment]
What is your use case? Where do you want to display some extra content? You may write a plugin to add extra projector elements and an interface to control it.

**Comment by johnfelipe** [comment]
pls view this video

https://youtu.be/wvVl1eeMBRo?t=128

If council or assembly have a microphone connect, then projector may be show closed caption

**Comment by johnfelipe** [comment]
This is new ip for try this neccesary feature in councils and assemblies
http://181.135.63.86:3001/room/ID/26157?viewMode=broadcast

**Comment by emanuelschuetze** [comment]
Does I understand your feature request correctly: You search for a possibility to create a verbatim record (record each speaker into a protocol)?
I think, that's a special case (normally a protocol of decisions is sufficent for assemblies) which should be But you could implement a plugin for this.

**Comment by johnfelipe** [comment]
Closed caption is very good feature not for record transcription if not service online for hearing impaired, this have a repo https://github.com/a11yproject/Wordcast

**Comment by jsaalfeld** [comment]
If i get this right, then we are asked to implement a system to add closed captions to the projector for the hearing impaired.

Something like https://github.com/c3subtitles/L2S2

**Comment by jsangmeister** [comment]
outdated
