### ISSUE TITLE
Logo ist not shown

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2103]
In OS 2.0 the logo won't be shown:

- got to Settings -> Projector
- enable to show the logo

result: the logo is not shown in the projector

- now disable to show the logo

result: the logo is shown

- now go to another menu, e.g. the start page

result: the logo is still shown in the projector preview but no longer in the projector

**Comment by emanuelschuetze** [comment]
I can't reproduce it with current master. Works well to enable/diable logo and title.

**Comment by donovaly** [comment]
Yes, fixed in OS 2.1 dev.
