### ISSUE TITLE
Projector colors are not correctly shown

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2104]
in OS 2.0
- got to Settings -> Projector
- change the background color of the header/footer lines

result: the new color is correctly shown in the projector but not in the projector preview

- now go to the main page and refresh also the projector preview

result: the color is still not shown in the preview

**Comment by emanuelschuetze** [comment]
I can't reproduce it with current master. Works well for projector live view. (maybe it was an already fixed autoupdate problem)

**Comment by donovaly** [comment]
Confirmed fixed.
