### ISSUE TITLE
Feature request: change size of projector preview

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2105]
It would be very useful if one would be able to increase the size of the projector preview. The default settings are smaller than necessary. Look at the attached screenshot - there is space to increase the size. Since every monitor is different the default size should be kept as is but the user should be able to increase the size by dragging the projector window.
![os2-0-main-page](https://cloud.githubusercontent.com/assets/1828501/15165791/f4a4d100-1718-11e6-8d1e-df80007e24a6.png)

**Comment by donovaly** [comment]
This would be a nice feature but no reason to have this in for OS 2.1. I propose to put it in the OS 2.2. agenda to release OS 2.1 soon.

**Comment by tsiegleauq** [comment]
A projector preview does not exist anymore.
@emanuelschuetze can this be closed?

**Comment by emanuelschuetze** [comment]
We will work on a new preview for 3.x - This issue can be closed.
