### ISSUE TITLE
Startseite ist nutzlos

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2106]
Man kann auf der Startseite nichts Sinnvolles tun. Man kann sie nicht projizieren und sich selbst zu begrüßen ist unnötig. Zudem wird der voreingestellte Text der Startseite nicht übersetzt, wenn man die Sprache von OpenSlides ändert.

Die Startseite ist somit eigentlich überflüssig, es sei denn man hätte dort eine Übersicht über die Tagesordnung UND Anträge UND Wahlen.

**Comment by PeterTheOne** [comment]
> sich selbst zu begrüßen ist unnötig.

Es können sich mehrere User einloggen, damit macht es schon Sinn dort ein paar Infos ab zu legen..

**Comment by emanuelschuetze** [comment]
Please use English for public issues.

The front page is used for static information of an assembly (e.g. general information about hotel, event, agenda, etc.) which can customized of each organisator. It was a feature request of OpenSlides users who use it online with access for all participants.

**Comment by donovaly** [comment]
I knew that this topic is controversial. For me as a new user i still don't have a clue what I can use this page for. I mean to inform the participants about e.g. hotels I have to generate a custom slide by creating a new agenda topic. I still don't know how to fill the start page with custom text and how to display it.

**Comment by PeterTheOne** [comment]
@donovaly have a look at the settings, you can set the content there..

**Comment by donovaly** [comment]
> have a look at the settings, you can set the content there

Yes, I see there a text field, but that cannot the all. I mean with a custom agenda slide I can display whatever I want. For the start page I can only display unformatted text without useful links like e.g. links to hotel pages etc.

**Comment by PeterTheOne** [comment]
Let's continue here #2099

**Comment by donovaly** [comment]
> Let's continue here #2099

#2099 is a different bug report.

**Comment by normanjaeckel** [comment]
Please check whether HTML support does work properly. If yes this may be documented or even added to the help text.
