### ISSUE TITLE
feature request: possibility to project image files

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2107]
Currently one can only display PDF files via the menu Files. It should also be possible to display PNG and JPG/JPEG files because in a meeting it is common to use blackboards etc. for hand-written sheets. Images of these sheets should usually eventually be projected to summarize the results.

**Comment by lesteenman** [comment]
I'm intending to write a plugin that will support projecting video files, but I agree that image files are also a good use case, so I might include them in my plugin. However, this does raise the question (at least to me) if support for more media types should not be included in the core project? If so, I could integrate the feature much more cleanly than with a plugin.

**Comment by emanuelschuetze** [comment]
+1 to integrate images and video projection cleanly in OpenSlides core (mediafile app)!
@lesteenman Can you try a pull request?

**Comment by lesteenman** [comment]
Will do.

**Comment by donovaly** [comment]
> if support for more media types should not be included in the core project?

Yes, in my opinion at least common image file types should be supported to be displayed. I vote to support PNG, JPEG/JPG and, if possible, GIF and BMP.
At conferences people shoot photos with their smartphones of e.g. blackboards and these images should be displayed.
