### ISSUE TITLE
Add agenda estimated time (sum of the time of all agenda items and calculated end)

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2109]
This was a feature of 1.7

**Comment by donovaly** [comment]
I miss this too.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Please try this issue if you have time.

The idea of the feature: Each agenda item has a field 'duration' where the staff user can enter a hours or minutes. In agenda list view template should sum up all durations of all (visible and hidden) items and print the sum on top of the table (see e.g. the list view in OpenSldies 1.x: https://docs.openslides.org/de/_images/Agenda_02.png).
In agenda settings the user can set a start timestamp which is used to calculate the end time of the event (should also printed on top of agenda table).
