### ISSUE TITLE
Can not add tags for topic items

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2110]
Only for motions we can use tags at the moment.

**Comment by donovaly** [comment]
The tag feature also also not working for elections.

Bug #2139 has been marked as duplicate if this bug.

**Comment by emanuelschuetze** [comment]
@joelmacht Maybe you can try to add the tags form field also for agenda and assignments - after you finished your pull request #2187

**Comment by emanuelschuetze** [comment]
Tags for assignments already works (tags are shown in list and detail view).

Still open: tags for customslides and/or for agenda items? (needs-info)

**Comment by normanjaeckel** [comment]
As discussed: Add tags for custom slides. Show tags also in agenda.

**Comment by emanuelschuetze** [comment]
Still open: 
* Manage tags in topic form and show tags in agenda list / topic detail view.
* Manage tags in assignment form and show tags in assignment list / detail view.

**Comment by emanuelschuetze** [comment]
Still open:
 * Manage tags in topic form and show tags in agenda list / topic detail view.

**Comment by FinnStutzenstein** [comment]
Closed with new table design.
