### ISSUE TITLE
Language change does not work

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2111]
- in OS 2.0 click at the upper right and select a language of your choice. In my case the default is German and I select there English.

result:
- only the menu names are translated, but not the the submenus of the settings menu, see the attached screenshot. (It works for the other main menus.)

reloading the browser page of OpenSlides does only not work but resets the language back to German here (on Windows with Firefox)

![language-settings-bug](https://cloud.githubusercontent.com/assets/1828501/15198864/738b1a3a-17da-11e6-8c70-9b29f40d2512.jpg)

**Comment by emanuelschuetze** [comment]
This is already fixed in #2261
