### ISSUE TITLE
Title of files menu is broken

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2112]
I only get instead if the title
{{ getTitle(presentedMediafile) }}
see the attached screenshot.
![file-title-bug](https://cloud.githubusercontent.com/assets/1828501/15198847/5a66600a-17da-11e6-9483-ee497df9f032.jpg)

**Comment by emanuelschuetze** [comment]
I can't reproduce it with current master. Looks like an (already fixed?) JS error has blocked rendering the page.  Please reopened if you can reproduce it again.

**Comment by donovaly** [comment]
Confirmed fixed in OS 2.1 dev
