### ISSUE TITLE
"Image list" is untranslated

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2113]
- create a new agenda item
- in the edit field click on the image symbol to insert an image
- in the popup dialog you see the untranslated string "Image list", see also 
  ![image-list-bug](https://cloud.githubusercontent.com/assets/1828501/15199107/fb1b04c8-17db-11e6-842f-df58d7a21979.jpg)
  the attached screenshot

**Comment by donovaly** [comment]
If you use German for OpenSlides, sometimes the whole dialog is untranslated. If this is the case, also the tooltips for the icons in the edit agenda dialog are untranslated, see attached screenshot.
![agenda-translation-bug](https://cloud.githubusercontent.com/assets/1828501/15199611/0f5d2138-17e0-11e6-8665-86e6cbef63d2.jpg)

**Comment by emanuelschuetze** [comment]
We have to add "Image list" to the tinymce translation file manually (e.g. https://github.com/OpenSlides/tinymce-i18n/blob/master/langs/de.js). The image list plugin is not part of the tinymce core translation, see http://archive.tinymce.com/i18n/. 

For me this missing translation string is not a problem. We could wait until tinymce updated the translations in one of the next releases.

**Comment by donovaly** [comment]
Not yet done in OS 2.1dev.

**Comment by emanuelschuetze** [comment]
The current editor (CKEditor) does not has this image list field any more. Closed.

**Comment by donovaly** [comment]
> The current editor (CKEditor) does not has this image list field any more.

So should I remove this info from the docs?
I am wondering that this feature was just removed. I twas a nice feature to upload images and other files to OS to easily reuse them for different slides. Now the possibility of uploading an image to OS is quite useless or brings not much benefit.

**Comment by emanuelschuetze** [comment]
> So should I remove this info from the docs?

Yes. 

This inage list feature was removed by introducing CKEditor (which replace our old tinymce editor). For CKEditor there is no plugin for image list included. But we will add such a similiar image list feature for 2.2 - see #2924

**Comment by donovaly** [comment]
> For CKEditor there is no plugin for image list included.

OK, but how to I display now an image uploaded to OS in an agenda item or at least an image of my local disc? (I already prepared a test assembly for my first live assembly with OS. This contained pie chart diagrams etc. in agenda points.)

**Comment by emanuelschuetze** [comment]
see #2924 please
