### ISSUE TITLE
PDF display uses unwanted magnification

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2114]
- in the menu Files upload a PDF with the sheet size of A4
- click on the projector icon
- now look at the projector output

result: the PDF is displayed with a magnification of 200% - making it therefore often unreadable
- now look at the projector preview

result: there the PDF is correctly displayed

**Comment by donovaly** [comment]
Here is an example PDF:
[Flyer-1.pdf](https://github.com/OpenSlides/OpenSlides/files/301536/Flyer-1.pdf)

You can see that the default magnification is too large and definitely 100%. Maybe the bug is that the magnification is always displayed as "100%":
![bug-pdf-magnification](https://cloud.githubusercontent.com/assets/1828501/15841193/88c154a8-2c4f-11e6-8ee3-c10bbf74d01f.png)
(no matter how often you press the + or - buttons besides the "100%")

**Comment by emanuelschuetze** [comment]
100% means "full width" of the projector. 
Examples:
* If you project a widescreen presentation pdf you get black border on top/bottom. 
* If you project a A4 pdf you see the upper half of the page. But you can scroll down with the projector controls.

So this behavior is not a bug for me.
A valid feature request could be to show a PDF in full height (with black borders left/right for A4 page). Or better: By default each pdf projection should show the whole pdf document (= full width or height). For A4 = full height. For a widescreen presentaiton = full width.

@donovaly Is that what you wanted to report?

**Comment by donovaly** [comment]
> 100% means "full width" of the projector. 

Ah, now I understand.

> By default each pdf projection should show the whole pdf document (= full width or height). For A4 = full height. For a widescreen presentaiton = full width.
@donovaly Is that what you wanted to report?

Yes, this would be a solution.

Btw. with the OS developer version you sent me in July I cannot present any PDF file. With OS 2.0 it works.

**Comment by donovaly** [comment]
In OS 2.1 dev the situation is better but still not solved: On a A4 PDF one can now click on the button "reset zoom" but this results in a display where the whole projector width is used so that the majority of the PDF is invisible. Instead the whole height should be used.

**Comment by emanuelschuetze** [comment]
Summarize final suggestion to fix this issue:

By default each pdf projection should show the whole pdf document (= full width or height). 
* For DIN A4 page = full height (horizontal centered, with black borders left/right)
* For a widescreen presentaiton = full width (vertical centered, with black borders top/bottom).

**Comment by emanuelschuetze** [comment]
Duplicate, see #2097
