### ISSUE TITLE
Text field in agenda item edit dialog is too small

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2115]
The vertical size of the text edit field in the agenda dialog is too small. It is possible to have more than 10 lines of text to be projected but the text edit field is even too small for 4:

![agenda-edit-too-small-example-2](https://cloud.githubusercontent.com/assets/1828501/15199796/82f52dd8-17e1-11e6-86ba-44caf9887609.jpg)

If you want not change
 its size, it should be possible to increase the text edit field by dragging at e.g. the lower right. (Like it is for example possible with this text edit window in GitHub where I am writing this bug report:

![text-edit-field-github](https://cloud.githubusercontent.com/assets/1828501/15199841/e68cf02e-17e1-11e6-8271-f03c093299c7.jpg)

Here is another example that the small size makes it very hard to edit images that one selected (and that is obviously too big):

![agenda-edit-too-small-example-1](https://cloud.githubusercontent.com/assets/1828501/15199869/22ad5738-17e2-11e6-8b11-abefee737f25.jpg)

**Comment by donovaly** [comment]
This feature would be very useful so the milestone 2.1 should in my opinion be kept.

**Comment by donovaly** [comment]
> normanjaeckel closed this in caf5209 7 hours ago

Maybe, but his changes were removed by commit e315cbad:
The line
statusbar: false,
is now still in.

Please correct this or reopen the bug. For me with current master I still cannot resize the text input field.

**Comment by emanuelschuetze** [comment]
Already fixed in current master.

**Comment by donovaly** [comment]
Many thanks, works as expected.
