### ISSUE TITLE
inform users to acept cookies

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2118]
The default browser setting on some PCs (like mine) is to forbid cookies. Usually websites inform the user that cookies are necessary to use a certain feature. Openslides does not. One can try to log in but nothing will happen, no warning, no error message. One gets the same blank login window again and again.

So at least when an attempt to log in the user should be informed that he must enable cookies.

**Comment by emanuelschuetze** [comment]
@ostcar Does cookies really required for login state while using OpenSlides?
I deactivated cookies in Firefox and can login without problems, and I'm already logged in if I open a second window with same OpenSlides URL.

**Comment by ostcar** [comment]
When I deactivate cookies I get the same behaviour as donovaly.

At the moment cookies are required and I don't see, how we could get rid of them. We could replace them by something else, for example, we could same the session id into the local storage and send it with every request. But if we did that, we would only reprogram the functionality of cookies. So we would replace cookies with our own implementation of a cookie and I don't see the benefit of this.

Http is a state-less protocol. If we want some state, then we need a session id that has to be send with any request. Cookies are the best choice for that.

And I never get it what the big problem with (normal) cookies are. They are needed at least for the browser session. And I don't want to inform users about this. If someone disables a key part of a webbrowser then he should not be surprised if something does not work.

**Comment by donovaly** [comment]
> I deactivated cookies in Firefox and can login without problems, and I'm already logged in if I open a second window with same OpenSlides URL.

Then you already created a cookie that never expires (Firefox's default setting). To reproduce, disallow cookies and delete all cookies.

> And I never get it what the big problem with (normal) cookies are. 

Really? Just google:
https://www.google.de/search?hl=de&q=cookie&ie=utf-8&oe=utf-8&gws_rd=cr&ei=UF5LV-ngDqnagAaqh4PYBg#hl=de&q=krankenversicherung
on different computers and you will be amazed how the results differ.
See
https://de.wikipedia.org/wiki/HTTP-Cookie#Gefahren
and
https://de.wikipedia.org/wiki/Anonymit%C3%A4t_im_Internet#Cookies
for more information.

Because of different laws in different countries many lawyers recommended to opt-in for cookies. So by login in to OpenSlides the users accept a session cookie. Just inform the user about this in the login window and we'll be safe. It is important that it is a session cookie that will be removed after login out.

However, this bug report was that when a user disabled cookies get will go crazy because he won't be able to log in but gets the same login screen again and again. So he need the info that he will have to enable cookies.

**Comment by donovaly** [comment]
OK according to the
https://en.wikipedia.org/wiki/Directive_on_Privacy_and_Electronic_Communications
it is not necessary to inform users explicitly that OpenSlides sets a session cookie.

So please just inform users who disabled cookies that they will have to enable them first before the can log in. Like GitHub does: if I am opening the login dialog I will be warned that I have to allow cookies in case I have them disabled.

**Comment by normanjaeckel** [comment]
So lets add a small check that an alert pops if cookies are disabled.

**Comment by donovaly** [comment]
Yes, that would be sufficient.

**Comment by ostcar** [comment]
Its ok for me.

I should have been more specific on my last post. There are a lot problems with cookies, but **session-**cookies are necessary for http. There is no way around them. Personally, I use https://addons.mozilla.org/de/firefox/addon/self-destructing-cookies/ so I only have session-cookies.

**Comment by emanuelschuetze** [comment]
Ok also for me. 

Summary:
* Implement a check (while opening the login dialog) if cookies are disabled. If yes show a short message that the use has to accept cookies for OpenSlides login. Who want's to do this? ;-)
* @donovaly Add a sentence to the OpenSlides manual that (session) cookies are required for OpenSlides to login.

**Comment by donovaly** [comment]
> Add a sentence to the OpenSlides manual that (session) cookies are required for OpenSlides to login.

Done

**Comment by emanuelschuetze** [comment]
Still open in this issue:
Implement a check (while opening the login dialog) if cookies are disabled. If yes show a short message that the use has to accept cookies for OpenSlides login.

**Comment by donovaly** [comment]
Here is the message Wordpress outputs after an attempt to login without cookies enabled:

![wordpress-cookie-note](https://cloud.githubusercontent.com/assets/1828501/19862614/6433a4e6-9f91-11e6-91c9-3f37553fa40b.png)

**Comment by donovaly** [comment]
This is not fixed. Now we have this behavior:

- delete your browser cache and the cookies
- start OS and login as admin

result: You are logged in but not as admin but as standard user

- now try to logout

result this is not possible you only get the login window again

**Comment by emanuelschuetze** [comment]
@donovaly You have to update your static files (via gulp). Please wait for a new portable test version. I'll make it for you...

**Comment by donovaly** [comment]
> Please wait for a new portable test version. I'll make it for you...

I received this version but the bug persists exactly as I described it.

**Comment by emanuelschuetze** [comment]
Please verify it with next test version. It's already implemented.

**Comment by emanuelschuetze** [comment]
Done. Please reopen if you can't verify it.

**Comment by donovaly** [comment]
Confirmed fixed
