### ISSUE TITLE
feature request: use tooltips in edit participants dialog

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2119]
The edit participants dialog is quite large. So save space and get a better overview about the settings OpenSlides should use tooltips for every field in the dialog instead of static text below the fields.

![edit-participant-missing-tooltip](https://cloud.githubusercontent.com/assets/1828501/15231032/1ed66930-1899-11e6-93bc-3801250cf983.png)

**Comment by donovaly** [comment]
Not in OS 2.1 dev maybe something for OS 2.2.

**Comment by FinnStutzenstein** [comment]
@donovaly This can be closed. The form is now reuced.

**Comment by emanuelschuetze** [comment]
Closed. Already done in 2.1.

**Comment by donovaly** [comment]
Please reopen. The bug was about missing tooltips. It is still not clear to new users what the 
Participant number or Structure level i. Therefore tooltips would be helpful.

**Comment by tsiegleauq** [comment]
That's a fundamental design question. Tool-tips in Input fields are not supported by angular material. There are, however, mat hints. Little text under the input fields, that can be replaced by error messages.

@emanuelschuetze if we want that I can add them pretty easily. If not I gonna close this

**Comment by emanuelschuetze** [comment]
The participants form in OpenSlides 3 is not a dialog anymore. So there is no scroll problem. mat-hints are good in this form. Closed.
