### ISSUE TITLE
edit group properties is extremely error-prone

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2120]
Imagine you want to add to the group Delegates the properties "Can see the list of files" one clicks onto that item.

result: all other properties are deleted! As one cannot restore the default settings, one is lost.

It is even worse because if you clicked onto an item without pressing the CTRL key and you notice your error you might simply change to another menu item assuming that nothing was changed - but your change was automatically saved.

To solve this bug OpenSlides should
- allow to select/deselect items with simple mouse clicks (no need for a CTRL key)
- add a button to restore the default settings for the 4 default groups

**Comment by emanuelschuetze** [comment]
We plan a new interface to manage user groups and permission in a matrix (with checkboxes), see
#435. This should solve this issue. I let this issue open until #435 is resolved.

**Comment by emanuelschuetze** [comment]
We have no a nice group permission matrix (see #435) which resolved this issue.

**Comment by donovaly** [comment]
Great news. This fixes this bug properly.
