### ISSUE TITLE
translation of delegates group is broken

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2121]
- set OpenSlides' language to English
- go to the list of participant groups

result: there is a group with the german name "Delegierte"

![translation-bug-delegates](https://cloud.githubusercontent.com/assets/1828501/15232360/067eba24-18a1-11e6-9e5c-d262160c6347.png)

**Comment by emanuelschuetze** [comment]
Fixed in current master with new matrix.
