### ISSUE TITLE
text field for messages too small

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2124]
the text field for messages is too small:

![messages-bug](https://cloud.githubusercontent.com/assets/1828501/15264956/77ee1b30-197a-11e6-92ae-9e1e8de26d2f.jpg)

It is too small even for shorter messages since everything with more tan 3 words is not visible. The solution would be to use a text field that can display more than one line.

**Comment by donovaly** [comment]
Still in OS 2.1 dev. Could be postponed to 2.2 because it is nice to have for more convenience but should not extend the release cycle time of OS 2.1.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Closed with PR #2816 .

**Comment by donovaly** [comment]
Many thanks for implementing!

**Comment by donovaly** [comment]
This bug has the wrong milestone. It is fixed for 2.1 and should therefore have the 2.1 milestone, not the 2.2 milestone.

**Comment by emanuelschuetze** [comment]
Done
