### ISSUE TITLE
enhancement: show countdown when message is shown

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2126]
It is useful to have both displayed, the message and the countdown. For example one might inform that there is something in 5 minutes and the participants should see the 5 minutes count down. Currently only the message is shown while the time is greyed out:
![mitteilung-countdown-bug](https://cloud.githubusercontent.com/assets/1828501/15265037/d47f8f22-197b-11e6-8fd8-42d0305e4b15.jpg)

**Comment by donovaly** [comment]
This bug has the easy tag. But it is not yet fixed in OS 2.1dev: Now one can display a message and also start a countdown, but the countdown is grayed out so that the participants won't notice it:

![localhost 8000 2016-11-01 18-17-06](https://cloud.githubusercontent.com/assets/1828501/19899242/b24165aa-a05f-11e6-80ba-aba63720b3b8.png)

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Please use a higher z-index for countdowns.

**Comment by donovaly** [comment]
Confirmed fixed, but now there is the new bug: issue #2747
