### ISSUE TITLE
enhancement: allow to input messages like theme slide text (with text style, colors etc.)

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2127]
line breaks are useful to sort info. For example to display text like:

"Please get ready with the vote in 5 minutes.
The ballots are in room 2."

Here is an example showing another case where the automatic line breaking mechanism lead to a wrong output.
![mitteilung-essen](https://cloud.githubusercontent.com/assets/1828501/15265165/6ccbd28e-197e-11e6-8817-99ab1ed3c315.jpg)
This one can also be solved if the user is able to determine the line break.

**Comment by normanjaeckel** [comment]
Please check if HTML is supported (add `<br>`). If yes, this can be documented.

**Comment by donovaly** [comment]
> Please check if HTML is supported (add <br>).

This does not work.

But why can't the text field in which one has to enter the message text not be as feature rich like e.g. the text input field for agenda points?

**Comment by emanuelschuetze** [comment]
Easy solution: Allow HTML tags in message output on projector. 
Use `<div .. ng-bind-html="message"></div>` in [slide_message.html](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/core/static/templates/core/slide_message.html#L3).

Test it by enter e.g. `<br>` tag and check that the projector messages shows a line break.

**Comment by donovaly** [comment]
I don't agree that this bug is closed. it is very inconvenient that one cannot enter text for notifications in WYSIWYG mode. Why can I not use the same input method like e.g. for theme slides. It makes sense that notifications have e.g. italic or colored text. Forcing people to input raw HTML cannot be a solution. Who knows plain HTML? I do not and I guess most of the convention organizers/session chairs also don't know it.

**Comment by FinnStutzenstein** [comment]
@donovaly Do you have an Idea how to fit some kind of tiny editor (just bold, italic, multiline,...) in the message edit field? If you want to have WYSIWYG more space is needed. I would propose to have a button next to the plain text field, which opens a dialog with more editing options if there is the need to format the message.

**Comment by donovaly** [comment]
> I would propose to have a button next to the plain text field, which opens a dialog with more editing options if there is the need to format the message.

That would be a nice solution.

**Comment by FinnStutzenstein** [comment]
I'll try to make an example for this

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze closed with PR #2816 .

**Comment by donovaly** [comment]
Many thanks! This is a great feature.
