### ISSUE TITLE
import of participants does not check for doublings

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2129]
- import a CVS file with participants
- now try to import the same file again

result: OpenSlides does correctly nothing because the content is already in the system but it tells you that something will happen:
![import-bug-1](https://cloud.githubusercontent.com/assets/1828501/15269459/18a6c908-19ff-11e6-9423-c77f81941d5a.jpg)

- now imagine you get a phone call that surprisingly 15 persons will participate. So you will add them to you CSV file and import it again

result: OpenSlides imports also the already existing participants again and not only the new ones

**Comment by emanuelschuetze** [comment]
Already fixed in current master.

**Comment by donovaly** [comment]
Many thanks for the new feature to decide for every user if it should be overwritten or not. This eases real life a lot.
