### ISSUE TITLE
string "Encoding" not translated in German UI

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2132]
In the section to import participants there is a string "Encoding" when OpenSlides is in German:
![encoding-translation-bug](https://cloud.githubusercontent.com/assets/1828501/15269907/fdb716a2-1a0d-11e6-9331-6cb32fa06d99.jpg)
It should be "Kodierung".

**Comment by emanuelschuetze** [comment]
I changed the German string in transifex from "Encoding" to "Kodierung".

**Comment by emanuelschuetze** [comment]
Still open: update German translation file: locale/angular-gettext/de.po
