### ISSUE TITLE
enhancement: missing filter for selection of CSV files

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2133]
in the section to import participants click on the button "Search" to select a CSV file. Unfortunately this dialog misses a file type filter. Currently it is "*.":
![file-selection-filter-bug](https://cloud.githubusercontent.com/assets/1828501/15269947/1fc76d22-1a0f-11e6-9998-613d8ad6ac93.jpg)
but it should be "*.csv; *.txt" since only CSV files (or textfiles in general) are allowed. This eases to find the CSV file in folders with many files.

**Comment by normanjaeckel** [comment]
Hm. This dialog is created by your browser. Does anyone know how to tell the broweser that it should filter the files?

**Comment by PeterTheOne** [comment]
Use the `accept` attribute for the `input` field:

> The value must be a comma-separated list of unique content type specifiers: A file extension starting with the STOP character (U+002E). (E.g.: ".jpg,.png,.doc")
> A valid MIME type with no extensions
> audio/* representing sound files HTML5
> video/* representing video files HTML5
> image/* representing image files HTML5

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by emanuelschuetze** [comment]
@tsiegleauq Can you try this issue?

**Comment by donovaly** [comment]
Works fine now. Many thanks!
