### ISSUE TITLE
missing translation in import CSV preview

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2134]
In the section to import participants import a CSV file there are two buttons in the preview section that are not translated when OpenSlides is in German:
![import-preview-translation-bug](https://cloud.githubusercontent.com/assets/1828501/15270035/280e18d4-1a12-11e6-9230-dfdbee9deb7e.png)

**Comment by emanuelschuetze** [comment]
Fixed with #2530
