### ISSUE TITLE
regression: setting time for begin of event does no longer show a calendar

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2135]
- got to the menu Settings->Agenda and click there into thefield for the begin time

result: one can enter there anything, not only a date and the calendar is not shown

This is a regression to OpenSlides 1.5.1 where a calendar was shown, see this image from the 1.5.1 handbook:
https://docs.openslides.org/de/_images/Tutorial_2_01.png

**Comment by emanuelschuetze** [comment]
Already fixed in master.

**Comment by donovaly** [comment]
many thanks
