### ISSUE TITLE
regression: users are always sorted with their first name

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2136]
In the settings under users there is the option "sort users with first name".
This option is now useless because the sorting is always with the first name. This is a regression to older OpenSlides versions as one can see in this screenshot of the manual for OpenSlides 1.5.1:
https://docs.openslides.org/de/_images/Tutorial_3_03.png

**Comment by donovaly** [comment]
Still in OS 2.1dev
the bug is in my opinion only that OS has only one table column for the name of participants. Having 2 columns, one for the given name, one for the family name would fix this bug.

**Comment by donovaly** [comment]
When adding a second table column, bug #2564 must/should be fixed too.

**Comment by FinnStutzenstein** [comment]
With the new table layout I will implement sorting for first and last name as well as the default sorting could be set in the config (this currently dead option).

Another proposal: Set with this option, if always the last name is shown in front of the last name. This would affect the `get_short_name()` and `get_full_name()` functions. Example with this option set:
Meier, Dr. Roland
Or the default way (as OS does now):
Dr. Roland Meier

@donovaly @emanuelschuetze Your opinions?

**Comment by donovaly** [comment]
> Your opinions?

I still vote for 2 columns one for the given name including the title "Dr. Roland" and one for the family name "Meier".

**Comment by donovaly** [comment]
> emanuelschuetze closed this in #2591 3 hours ago

Note that bug #2564 is still not fixed but manifested by the commit. First name and Last Name is incorrect English. Only Germans might understand this correctly.

**Comment by donovaly** [comment]
Please reopen this issue. With the version emanuelschuetze sent me today, I still cannot sort using family name or given name.

**Comment by emanuelschuetze** [comment]
Reopened. If #2592 is merged you can sort as expected. Please close it all done for you.

**Comment by donovaly** [comment]
#2592 was meged but the bug is still not fixed. This is my unsorted users list:

![localhost 8000 2016-11-19 14-47-16](https://cloud.githubusercontent.com/assets/1828501/20455893/38c08ace-ae67-11e6-9fee-e72557b7c9cf.png)

Now I sort according to "Last Name" (which is still wrong English). The result is this:

![localhost 8000 2016-11-19 14-49-26](https://cloud.githubusercontent.com/assets/1828501/20455907/70420a54-ae67-11e6-8ae6-1d0572d239eb.png)

Schulze is sorted before Käßmann. So the sorting is wrong. The list also doesn't show me an indicator that the list is sorted and according to what. But when e.g. selecting according to the activity, I get such an indicator. So this indicator feature should also be taken for sortings.

**Comment by emanuelschuetze** [comment]
Works for me in current master ('Schulze' is sorted after 'Käßmann'). The indicator is shown in the sort drop down menu. - So all done. Please retest and reopen if you have some questions.

**Comment by donovaly** [comment]
> Please retest 

Done, now everything is working correct. I'll update the docs to the new user input mask.
