### ISSUE TITLE
blocker: user login system is broken

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2137]
- create a new user and give him the username "johndoe"
- set his password to "test"
- try to login

result: one cannot login with johndoe, but OpenSlides created his login info correctly:
![johndoe-bug](https://cloud.githubusercontent.com/assets/1828501/15277698/e6e19822-1b0b-11e6-852e-7242aa27f7ef.jpg)

The whole user login system seems to be broken because for many users I get the same problem. This makes OpenSlides 2.0 quite unusable.

**Comment by donovaly** [comment]
OK, it seems that as soon as one specifies a preset password, a user cannot log in!

It is even worse because if a user forgot his password and the admin presses "reset" to generate a new password. The password will be deleted but no new one will be created. it is simply empty.
 This is a nightmare since there is no way to make it possible that the user can log in.

**Comment by donovaly** [comment]
It is even more severe: Create a new user, then edit it and press "reset" behind the password field. As result the user won't be able to log in.
So whenever one enters manually a password or presses "reset" the user cannot log in.

**Comment by normanjaeckel** [comment]
What about the following:
- Edit a user
- Change its default password but dont click reset
- Just click save
- Then open the edit form again and click reset without editing the default password any more.

This should work but there might a bug nevertheless.

**Comment by donovaly** [comment]
> Edit a user
> Change its default password but dont click reset

Whenever I modify the field for the user password the user can no longer log in. The reset button also changes the password field and therefore triggers the same bug as I now found out.

> Just click save

OK I have now given the password "test". The user can still not log in.

> Then open the edit form again and click reset without editing the default password any more.

The I get the info that the password has been reset but I can still see in the login info PDF that the password is still "test". Now the user can log in with "test". What a weird bug and very hard to get it  it took me about an hour and dozens of login attempts. A MUST-FIX for 2.0.1!

**Comment by emanuelschuetze** [comment]
I don't understand the bug. I tested theses variants with the current master:

1. Create new user: first name "Max", last name "Mustermann", no other data.
2. Generate list of access data: the pdf shows the username ("Max Mustermann") and the generated password ("BPYepD6D").
3. Max can successfully login with username and password (tested in a private browser window).
4. Edit user Max: The default password field shows the generated password. Correct. Now Change the default password to "test". Click [Reset] button. Message "Password successfully resetted to: test" is shown. Save the edit dialog.
5. Max can successfully login with username ("Max Mustermann") and the changed password ("test"). Correct.

@donovaly So I can't see any bug (or blocker) here...

**Comment by emanuelschuetze** [comment]
@donovaly Please accept the pending github OpenSlides-team invitation so that we can assign issues to you.

**Comment by donovaly** [comment]
> @donovaly Please accept the pending github OpenSlides-team invitation so that we can assign issues to you.

I did not receive an invitation. Please re-invite me.

**Comment by donovaly** [comment]
> I don't understand the bug. I tested theses variants with the current master:
> Edit user Max: The default password field shows the generated password. Correct. Now Change the default password to "test".

Do nothing more than to write in "test"  and to click save. Then the user cannot log in despite the password PDF says correctly that it is now "test".

> Click [Reset] button.

Then and only then it will work. But this is nasty. I spent now so much time with this issue but never came to the idea that one needs to press reset after (sic!) the password has been changed.
As one has already changed the password it must be possible that this is enough - and the PDF shows already the changed password. So it is still a bug that the PDF shows a password that is in fact not the password.

 Message "Password successfully resetted to: test" is shown. Save the edit dialog.
    Max can successfully login with username ("Max Mustermann") and the changed password ("test"). Correct.

**Comment by emanuelschuetze** [comment]
> I did not receive an invitation. Please re-invite me.

Done. Please check your emails.

**Comment by emanuelschuetze** [comment]
Ok, I understand: The [Reset] button within the user edit form is not very self-explaining.  Especially if you change the password and want to reset it in one step.

Any idea how we can improve the password reset process for the admin?
Maybe we should outsource the reset action into a new dialog (e.g. only a input field for the new password and a button to reset the default password to this entered password?) What do you mean?

**Comment by donovaly** [comment]
What about this: make the background color of the password field red unless the reset button is pressed. Also "pulse" the button to clarify that this needs to be pressed. 

I added now also a note in the manual.

**Comment by emanuelschuetze** [comment]
Good idea. I'll try it.

**Comment by normanjaeckel** [comment]
See #412.
