### ISSUE TITLE
Reordering speakers has no effect on projector

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2138]
- create a speakers list
- move the last speaker to the top to be the next speaker

result: this works within OpenSlides but the change is not displayed in the projector or the live preview. One can update the browser window without success.

This is a regression to OpenSlides 1.5.1.

**Comment by emanuelschuetze** [comment]
I can confirm this bug. The modified order of the next speakers is not updated on projector. Also reloading the projector does not help.

**Comment by donovaly** [comment]
The fix for this bug is not released therefore the bug should stay pen, see my private email.

**Comment by emanuelschuetze** [comment]
The fix is available in current master and will released with our next version after 2.0: 2.0.1 or 2.1.
