### ISSUE TITLE
tag feature is provided for elections and agenda but not usable there

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2139]
There is the button "tags" in the menus for the agenda and for elections. But currently it is not possible to set a tag for an agenda point or for an election.
So either this will be made possible or the tag button should be removed.

**Comment by normanjaeckel** [comment]
See #2110. Maybe this is a duplicate.

**Comment by donovaly** [comment]
Yes, it is a duplicate of bug #2110.
