### ISSUE TITLE
Setup Selenium for automated GUI tests in browser

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#214]
see https://docs.djangoproject.com/en/dev/topics/testing#django.test.LiveServerTestCase

First, please setup selenium with some sample test cases and a short README.
Then, create a new ticket, that an OpenSlides tester can start creating with a full suite.

**Comment by ostcar** [comment]
@emanuelschuetze can this be closed?

**Comment by emanuelschuetze** [comment]
Yes, this issue can be closed. We will do tests in 2.0 with angularjs test framework.
