### ISSUE TITLE
Comment on ballot paper is too short

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2140]
For a typical election of persons, a typical comment on the ballot paper would be in German for example 

_Sie haben maximal 5 Stimmen. Damit der Wahlzettel gültig ist, müssen Sie mindestens eine Person wählen._

The length of this message is 104 characters but currently OpenSlides allows only a length of 79 characters for "poll_description_default". This is an unnecessary restriction since there is plenty of space on the ballot paper. Besides this this restriction makes is difficult to explain how the election works to the participants. But in my experience this is very important.

**Comment by emanuelschuetze** [comment]
We can test it with longer comment fields (e.g. 256) but we have to check that linebreaks looks good an the candidate lists is not overridden by long comment.

**Comment by emanuelschuetze** [comment]
BTW: If we have implement the client-side pdf creation with jsPDF we can improve this issue.

**Comment by matakuka** [comment]
At the moment, the comment field can only support two lines of text (~90) without the candidate list going out of bounds (in the case of four candidates). Moving the spaces around (e.g. less indentation) would need some rework on the ballot as a whole, which may be the best to do when doing the client-side implementation.

**Comment by emanuelschuetze** [comment]
Ok, let us wait until we use jsPDF.

**Comment by donovaly** [comment]
For me the bug is fixed because now in OS 2.1dev the description is also printed on the ballot paper. So fine BUT the field "Default comment on the ballot paper " in the election setup can be removed. Currently it is not used, neither in the projector nor the ballot paper.

**Comment by donovaly** [comment]
> For me the bug is fixed because now in OS 2.1dev the description is also printed on the ballot paper.

closing

> BUT the field "Default comment on the ballot paper " in the election setup can be removed. Currently it is not used, neither in the projector nor the ballot paper.

This is now bug #2563.
