### ISSUE TITLE
No translation for ballot paper

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2141]
- use OpenSlides with English menus
- create an election
- create the ballot paper

result: the ballot paper is in German

**Comment by malteger** [comment]
The language of the texts in the generated PDFs seems to be set from the browser language only. I have the same issue if I try to print ballot papers in German. You should consider adding a language setting somewhere.

**Comment by emanuelschuetze** [comment]
Right, currently (in OpenSlides 2.0) the language of generated pdfs is based on the browser language. It's independent from the client side language chooser which impacts on html templates only. We have the same issue for all config fields: the are generated and translated from server side. And the server detected the browser language not any client-side language choice.

Our plan is for future versions to bring all translations to client-side (also pdf which should generated from JavaScript by jsPDF, see #1640). Additional we have to save the language choice in cookie that OpenSlides can remember the choice after reload.

**Comment by donovaly** [comment]
> Our plan is for future versions to bring all translations to client-side (also pdf which should generated from JavaScript by jsPDF, see #1640).

Bug #1640 is now closed but the bug is still in OS 2.1dev

**Comment by emanuelschuetze** [comment]
Retested with current master, where we use always client side pdf creation: Election ballot pdf is now in the requested language. So fixed for me.

**Comment by donovaly** [comment]
Confirmed fixed.
