### ISSUE TITLE
Wrong number of eligible persons

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2142]
- create an election and say that there have 3 persons to be elected
- add 5 candidates to the candidate list
- in the first voting round mark only 1 persion as elected
- start the second voting round
- print the ballot paper for this voting

result: OpenSlides adds this "_2. Wahlgang, 4 Kandidaten/innen, 3 verfügbare Posten_".
So the number of candidates is correct but since one person was already elected, there are now only 3 available position not 3

**Comment by normanjaeckel** [comment]
This a a question of design: How can we display the number of available posts after some candidates are marked as elected? We have the assignment list view, the detail view, the PDF and the ballot papers. We need different solutions for these cases. @emanuelschuetze Any suggestions?

**Comment by donovaly** [comment]
still in 2.1dev

**Comment by emanuelschuetze** [comment]
still open: remove string in list view "x required"

**Comment by donovaly** [comment]
I still get this bug with beta3. It is OK that you removed the strings about the required candidates but one problem persists:

- follow my initial comment
- after 1 person was elected start the second voting round

result: still all candidates are on the list and I cannot remove the elected person for the second voting round. But I have to print a ballot paper for the second round without the already elected person.

**Comment by emanuelschuetze** [comment]
Confirmed. I fixed it with #3051.

**Comment by donovaly** [comment]
> I fixed it with #3051.

Confirmed fixed.
