### ISSUE TITLE
election option "publish election result only for elected candidate" has no effect

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2145]
In the settings of OpenSlides under elections there is an option "publish election result only for elected candidate". But setting/unsetting this has no effect on existing elections or on new elections.

**Comment by normanjaeckel** [comment]
Confirmed. @emanuelschuetze Do you want to hide the election results for non-elected candidates only on the projector or also in the interface or do you even want me to hide them in the REST API? I do not remember the behavior of 1.7.

**Comment by emanuelschuetze** [comment]
I removed the unused config option in pr #2230
