### ISSUE TITLE
enhancement: remove already selected candidates from selection list

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2146]
- create an election and add some candidates to its list
- now try to add a person again that is already on the list

result: OpenSlides correctly issues an error message that the person is already on the list:

![candidate-exists-already](https://cloud.githubusercontent.com/assets/1828501/15373079/2ab64586-1d44-11e6-96c9-6f041dd7503a.jpg)
But it would be more convenient if already selected users will automatically be removed from the selection list so that they cannot be selected accidentally and pollute the list unnecessarily.

**Comment by emanuelschuetze** [comment]
Same user selection field is used also for list of speakers, motion submitters/supporters which should work like the candidate field for elections.

**Comment by donovaly** [comment]
This can in my opinion be postponed to 2.2

**Comment by emanuelschuetze** [comment]
The motion submitters/supporters form fields already support it - selected users are disabled in drop down list.

Still open: drop down lists for candidates and list of speakers.

**Comment by tsiegleauq** [comment]
This issue was addressed in OpenSlides 3
