### ISSUE TITLE
linebreaks can occur inside info blocks

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2147]
The info blocks are not protected against linebreaks. In this example:
![info-button-bug](https://cloud.githubusercontent.com/assets/1828501/15375991/b48c44f0-1d52-11e6-8fe6-f78c5f7f8340.jpg)
the blocks for the tag "Soziales" is destroyed by a linebreak.

**Comment by PeterTheOne** [comment]
A space before "Soziales" might prevent this kind of line break, also `white-space: nowrap;` on the "Soziales" element might help.

**Comment by donovaly** [comment]
> A space before "Soziales" might prevent this kind of line break

It does not. I cannot add a space. Besides this we cannot assume that average users know such trickery. They just create a tag. How could they know that there are some blanks necessary?

> also white-space: nowrap; on the "Soziales" element might help.

How could one enter HTML code? I click on edit for the motion and there I can select a tag via a combobox listing the tags one has created before.

**Comment by PeterTheOne** [comment]
Sry, I meant that a developer could do this.

**Comment by emanuelschuetze** [comment]
@joelmacht Can you try this issue?

**Comment by joelmacht** [comment]
Yes, I will have a look at it once I'm set up.
