### ISSUE TITLE
input field for identifier of motions is missing

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2148]
- create a new motion by clicking on the New button

result: there is no field for the identifier. To get an identifier one has edit the motion after its creation. there there is a field to specify the identifier. This is annoying because during events it is quite common that motions are made while the event is already running so that one needs custom identifiers  depending on the topic of the motion.

Since the dialog to create a new thing is the same as to edit it, I think that the missing field here is a bug.

**Comment by donovaly** [comment]
OK, I see now that this behavior is intended. So I hereby request a change as enhancement.

**Comment by normanjaeckel** [comment]
Please test again your expected behaviour if you changed the motion config value to number the identifier manually. Please use the current master because of our recently fixed config bug.

**Comment by donovaly** [comment]
How can I test master? I have atm absolutely no time to run compilers and scripts. So all I could do is to test a compiled binary.

**Comment by emanuelschuetze** [comment]
@donovaly Do you use the windows portable version? I could provide you a current snapshot version for windows if you like. Or you can create a development version yourself be following the [install instruction](https://github.com/OpenSlides/OpenSlides/blob/master/DEVELOPMENT.rst#2-installation-on-windows). What do you prefer?

**Comment by donovaly** [comment]
> Do you use the windows portable version?

Yes.

> I could provide you a current snapshot version for windows if you like. 

Yes, please. I won't have time to compile OpenSlides by myself - real life stuff and vacation ;-). Just write me a private mail.

**Comment by donovaly** [comment]
I had again a closer look and think now that the current behavior makes sense. Delegates cannot specify an identifier. This has to be done by an admin as reviser. Otherwise the chances are high to break the identifier system leading to confusions. When importing motions via CSV it is possible to specify identifiers because the import is done by the admin preparing and planning the event.
