### ISSUE TITLE
missing translation in settings for motions

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2149]
- use OpenSlides with German menus
- go to the settings and there to motions and there to general

result: the combo box to select a workflow is not translated:

![translation-bug-motion-settings](https://cloud.githubusercontent.com/assets/1828501/15411279/2cd3dda2-1e1f-11e6-99c7-72332ea8e3dd.png)

**Comment by emanuelschuetze** [comment]
Fixed with #2261
