### ISSUE TITLE
regression: motion setting for workflow has no effect

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2150]
- go to the motion settings and set there that the default for new motions is the complex workflow

result: the change doesn't have an effect - the simple workflow is still used for new motions

**Comment by normanjaeckel** [comment]
Please test again with current master. This might be a problem of our config bug which was recently solved.

**Comment by emanuelschuetze** [comment]
Tested with current master: The complex workflow is used for new motions. So resolved.
