### ISSUE TITLE
missing button to return from tag overview

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2151]
- go to the menu for motions
- click there on the button "Tags"

result: one sees the list of existing tags. What is missing is a button to go back to motions. For all other things there is such a back button.

**Comment by emanuelschuetze** [comment]
Right, but we have the problem that this tag list view is used from agenda, motions and elections list view. So we can't remember from which list view the user is come to the tag list.
I think this is not so bad because you can navigate via main menu items. I would close this issue if nobody has a better idea. Ok?

**Comment by normanjaeckel** [comment]
Is there something like a referer in AngularJS State?

**Comment by emanuelschuetze** [comment]
There is a open discussion about a "previous state" in ui-router:
https://github.com/angular-ui/ui-router/issues/92

**Comment by donovaly** [comment]
> So we can't remember from which list view the user is come to the tag list.

Hmm, why not simply adding a button that does the same as if I would use the back button of the webbrowser?

**Comment by emanuelschuetze** [comment]
Because you cannot be sure that the user comes directly to tag list view without any turn about e.g. tag edit view. One example:
motion list -> tag list -> tag form -> tag list
(a back action would be go to tag form view)

**Comment by donovaly** [comment]
But from my view as bug reporter this would do the job. I just want a way to go back without the need to use the browser. So it is fine if the button is named "go back" and does the same as the browser back button.

**Comment by emanuelschuetze** [comment]
Ok, this is easy: A new "Back" button on the top of the tag list view which use the browser back action.

**Comment by emanuelschuetze** [comment]
@matakuka Can you try this issue?

**Comment by donovaly** [comment]
Works fine. many thanks!
