### ISSUE TITLE
category change in a motion does not change its identifier

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2152]
- go to the motion settings and set there that motions will be numbered according to their categories
- create a new motion and specify a category

result: it is correctly numbered with the prefix of the category

- now click on QuickEdit and change the category
- click on Update

result: the identifier is still the one of the former category

**Comment by emanuelschuetze** [comment]
This behaviour is desired. Sometimes you want to move a motion (from a formal category, e.g. "Initiativanträge I") to a thematical category (e.g. "Bildung B"). But it is important to keep the origin category. If you want you can change the category manually.
So, won't fix (at the moment with our current motion model.)

**Comment by donovaly** [comment]
OK, I'll describe this in the docs.
