### ISSUE TITLE
regression: version history of motions is no longer available

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2153]
- create a new motion with the complex workflow 
- set the status to permit
- edit the motion
- click on the motion

result: there is no version history:

![no-version-history](https://cloud.githubusercontent.com/assets/1828501/15411948/1ac2f256-1e24-11e6-8356-765f30ad3a2d.jpg)

This is a regression to OpenSlides with its very useful feature to show and compare different versions:
https://docs.openslides.org/de/_images/Motion_04.png

**Comment by emanuelschuetze** [comment]
I can't confirm the bug. After your 4 steps I get a version history which shows a 2nd version, see:

![issue2153](https://cloud.githubusercontent.com/assets/2075427/15628191/6c74af1c-24fb-11e6-8ff6-b0d40275fc17.png)

You should test it again. For me everything works. Can I close this issue?

[Assigned to @donovaly ]

**Comment by donovaly** [comment]
Hmm, indeed  can no longer reproduce this. Strange.
