### ISSUE TITLE
regression: motion option to deactivate versioning has no effect

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2155]
- set the motion option in the settings to allow the deactivation of versioning
- now edit a motion

result: regardless of the option to activate/deactivate versioning there is an option for a trivial change in the edit dialog that allows to deactivate versioning

So this is either a regression to OpenSlides 1.5.1 or the change is desired to offer turning off the versioning. If so the motion settings option should be removed.

**Comment by emanuelschuetze** [comment]
I tested it with current master:
* set config option to allow the deactivation of versioning
* create new motion in complex workflow
* set state of motion to 'permit'
* now change the motion text (without checking 'trivial change') -> new version is created
* permit the new versoin
* change again the motion text (with checking 'trivial change') -> NO new version is created

Works as expected. Closed.

**Comment by donovaly** [comment]
This bug is not fixed:
- assure that "Allow to disable versioning" is NOT checked in the motion settings

so one can expect that when creating/editing motions one cannot use prevent the versioning. But now
- edit a motion that is in permit state

result: there is still the selectable option "Trivial change" that prevents the versioning.
expected result: if "Allow to disable versioning" is not checked in the motion settings, the "Trivial change" checkbox in the editing window of motions is disabled.
