### ISSUE TITLE
Description on agenda not viewable

### ISSUE THREAD

**Issue by lesteenman** [OpenSlides/OpenSlides#2157]
The description for an agenda item is only visible for users with edit rights. It would be logical to make an agenda item clickable, and show the description then.

**Comment by normanjaeckel** [comment]
This a question of design. Do we want to give non-staff users access to the so called custom slides.

Attention: At the moment at the list of speakers view there is a dead button to the custom slide detail view (for non-staff users).

**Comment by emanuelschuetze** [comment]
Fixed in current master with introducing new topic slides (which replaced old custom slides)
