### ISSUE TITLE
regression: motion setting do disable supporters has no effect

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2160]
- go to the settings menu and enable there in the motions section the option to remove supporters

result: the supporters are not removed when the motion creator edits the motion in the first phase/status

This is obviously a regression bug.

**Comment by normanjaeckel** [comment]
I can not reproduce this bug. I tested with a delegate as motion submitter.

**Comment by donovaly** [comment]
Indeed, it works here now too. So this bug cen be closed.
