### ISSUE TITLE
enhancement: option to number every line in a motion text

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2163]
At least at events of the German SPD party every line of the motion text needs to be numbered. Without the numbering motions won't be accepted because it is important for discussions and for the motions to change the motion text.

It doesn't harm if then also the motion reason will be numbered per line.

**Comment by emanuelschuetze** [comment]
The feature request 'line numbering in motions' is already scheduled for OpenSlides 2.1.

**Comment by emanuelschuetze** [comment]
Feature "line numbering" is implemented with #2292.
