### ISSUE TITLE
missing translation in motion QuickEdit

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2164]
- use OpenSlides with German translation
- create a motion and subsequently use QuickEdit to edit it

result: the description of the field "Schlagwörter" is untranslated:
![motion-quick-edit-missing-translation](https://cloud.githubusercontent.com/assets/1828501/15455727/81445962-205d-11e6-8245-066d2f8ecbcf.png)

Also the English string is incorrect it should be "select some tags".

**Comment by emanuelschuetze** [comment]
Confirmed. The string "select some options" is not marked for translations.
We just use the default string for all select fields ("select some options").

**Comment by donovaly** [comment]
In OS2.1dev I don't see Quick Edit anymore. If this is a bug please tell me. If not, I will change the docs accordingly.
