### ISSUE TITLE
regression: csv import of motions does no longer add new participants

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2165]
- try to import motions e.g. with this CSV file:

identifier,title,text,reason,submitter,category
Kat A-1,Satzungsänderung,"Die Mitgliederversammlung möge beschließen, in §8 Absatz 1 der Vereinssatzung die Zahl fünf durch sieben zu ersetzen.","Die vielen Aufgaben erfordern eine Erweiterung des Beirates auf sieben Mitglieder.",Dr. Hans Schulze,Kategorie A
B1,Titel 2,Text 2,Begründung 2,Antragsteller 2,Kategorie B
,Titel 3,Text 3,Begründung 3,,

- in the preview you see that OpenSlides will import the motions and that it will add new categories because they don't yet exist AND that it will create a new participant:
![motion-import-bug](https://cloud.githubusercontent.com/assets/1828501/15455811/77e42fd0-205f-11e6-8d7e-1b144ad0f90c.jpg)

result: the new categories are correctly created while the new participant is not created. Instead the creator of the imported motion is always the administrator.

**Comment by emanuelschuetze** [comment]
Another issue of csv import:
Categories are multiple created (e.g. 2 motions with category "foo" creates 2 categories "foo").

**Comment by donovaly** [comment]
Confirmed fixed in OS 2.1 dev
