### ISSUE TITLE
Import is not completely processed

### ISSUE THREAD

**Issue by larsboehnke** [OpenSlides/OpenSlides#2166]
We just imported 169 delegates as a CSV file. Few of them does not have a structure level. The preview says that 169 delegates will be imported. But only 133 are finally imported.

<img width="356" alt="bildschirmfoto 2016-05-25 um 00 10 26" src="https://cloud.githubusercontent.com/assets/11321756/15521651/246f3fde-220d-11e6-9ec7-6893e6639301.png">

If you want me to send over the import file please write me to lars.boehnke@pfadfinden.de due to privacy issues.

**Comment by emanuelschuetze** [comment]
I send a private message to Lars...
It would be interesting which users are not imported? Only the users without a structure level?

**Comment by larsboehnke** [comment]
A first idea was that only delegates with no structure level were not imported. Yes, they were not imported but that makes only 13/37 - still 20 missing.

**Comment by larsboehnke** [comment]
Ok, every delegate with the group '1' (which means guest group, default by system) was not imported

**Comment by normanjaeckel** [comment]
It is intended that nobody can be member of the group with id 1. This group exists only to control the permissions of guests, that are clients without any login. (This requires that the guest system is activated in the config.)

The same for group with id 2 (registered). Nobody can be a regular member of this group but all registered users (even those who do not belong to any group) gain permissions from this group.

May be we just have to document this properly. @donovaly

**Comment by larsboehnke** [comment]
@normanjaeckel the UI is not clear on this point

**Comment by emanuelschuetze** [comment]
The user csv import site says `Default groups: Delegates 3, Staff 4`. There is no comment that you should not use group id 1 and 2.
@larsboehnke Do you have a suggestion how we can improve the UI?

**Comment by donovaly** [comment]
> May be we just have to document this properly. @donovaly

Done: https://github.com/donovaly/openslides-docs/blob/master/de/OpenSlides-Handbuch.pdf

**Comment by emanuelschuetze** [comment]
@larsboehnke Any idea how we can improvethe csv user-import page that we can prevent your error for setting default group 1. Is the help text and the documentation enough? If yes we can close this issue because all done.

**Comment by emanuelschuetze** [comment]
I closed this issue. There is a help text in users import view which says that the default groups are 2 (delegates), 3 (staff) and 4 (committees). Group 1 (default group) is automatically set to users who have no other groups (see also help text in new group permission matrix for further explanation).
