### ISSUE TITLE
regression: version history of motions is no longer comparable

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2172]
- create a new motion with the complex workflow
- set the status to permit
- edit the motion
- click on the motion

result: there is a version history but one cannot compare the versions:
![](https://cloud.githubusercontent.com/assets/2075427/15628191/6c74af1c-24fb-11e6-8ff6-b0d40275fc17.png)

This is a regression to OpenSlides 1.5.1:
![motion_04](https://cloud.githubusercontent.com/assets/1828501/15636985/10e7e492-260f-11e6-9221-13fc0e396380.png)

**Comment by emanuelschuetze** [comment]
Right, the diff feature of 1.7 is still missing in 2.0. We already have a issue for that: #1874.
So closed this issue as duplicate.
