### ISSUE TITLE
setting to remove all suportes from a motion when editing has no effect

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2174]
- use the option to remove all supporters of a motion when the submitter edits the motion in basic state
- create a motion as user A
- log in as user B and support the motion
- now edit the motion as user A

result: user B is still on the supporter's list. So the option doesn't seem to have an effect

**Comment by donovaly** [comment]
I forgot to say that I set the minimal supporters to 2 to enable the supporter system.

**Comment by normanjaeckel** [comment]
I can not confirm this. Please check if user A in your example has not the permission to manage motions.

Nevertheless a warning in the edit dialog as in 1.7 is missing.

**Comment by donovaly** [comment]
User A created the motion. Both users are delegates.

Maybe I misunderstood the settings options. So what does it do by design?

**Comment by normanjaeckel** [comment]
Please try again with current master.

**Comment by donovaly** [comment]
Duplicate of bug #2160
