### ISSUE TITLE
Documentation for big mode

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#2177]
Create an example documentation for the big mode.

This could be done in a documented ansible playbook.

**Comment by emanuelschuetze** [comment]
Short instruction for big mode is done in current [README](https://github.com/OpenSlides/OpenSlides#installation-for-big-assemblies) and [DEVELOPMENT](https://github.com/OpenSlides/OpenSlides/blob/master/DEVELOPMENT.rst#installation-openslides-in-big-mode) files.

**Comment by ostcar** [comment]
One thing, that is not described in this files is, that you have to start more then one daphne server. The clients are connected to daphne. If there only one (single-threaded) daphne server, then it needs a long time to send a message to all the clients.

I thing that you should start as many daphne servers, as you have CPU cores + 1. The Problem is, that each daphne server as to listen on a different port and that all clients have to connect equally to each port.

I fixed the the [ansible script](https://github.com/openslides/openslides_ansible), to start [5 daphne servers](https://github.com/OpenSlides/openslides_ansible/blob/master/tasks/main.yml#L172) and [configured nginx](https://github.com/OpenSlides/openslides_ansible/blob/master/templates/nginx_upstream.j2) to spread the connections equally to all daphnes. See [this commit](https://github.com/OpenSlides/openslides_ansible/commit/15c52a4f44de7a7805863a222309027b4de67af8) for an résumé.

Also, after merging https://github.com/OpenSlides/OpenSlides/pull/2794, there is a new dependency for the big mode and a new config variable that has to be changed. But this is already described in the development file.
