### ISSUE TITLE
Config values are created always in English

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2193]
A bug was introduces with 2221b23 (Redesign of the config variables.) which should fix the big mode:
After db creation all config values are always in English (also if my browser language is German). See e.g. title and text of welcome page after new db creation. Before this commit the config value language depends on the browser language (correct).

@ostcar I think it's your turn because you introduced the bug ;).

**Comment by ostcar** [comment]
@emanuelschuetze is this still an issue? see #2194

**Comment by emanuelschuetze** [comment]
#2261 will fix this issue.
