### ISSUE TITLE
404 for js-data-http.js.map

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2196]
From #2170 (Big mode):
On Linux I get a 404 for js-data-http.js.map: `HTTP GET /static/js/js-data-http.js.map 40` 

Looks like gulp does not copy the map file into js static folder. Check if this file is required.

**Comment by matakuka** [comment]
I'll take a look.

**Comment by matakuka** [comment]
I cannot replicate this bug in current master, although I vaguely remember seeing it on one of my branches this week.

**Comment by emanuelschuetze** [comment]
Can't reproduce it any more. Closed.
