### ISSUE TITLE
assignment phases translated by browser setting, ignoring openslides setting

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2197]
The assignment election phases "Voting", "Searching for candidates" and "Finished" are not translated. 
Affects demo.openslides.org (2.0) and current master.
The strings are marked for translation in the [assignments/models.py#63-67](https://github.com/OpenSlides/OpenSlides/blob/b3582f462e032b0f5f855447f7bfcf80e706f65f/openslides/assignments/models.py#L63-L67) and are translated in the .po files, but will appear in english (tested german and spanish).

**Comment by matakuka** [comment]
The cause seems to be different sources for information of what the current language is. Setting the Browser (Firefox-esr 45.2.0) language to exclusively german or spanish translates these values correctly, but only after a complete reload of the project.
Then, changing the language again with either methods (selecting language in openslides or selecting browser language) requires another reload. My guess is that [migrations/0001_initial.py](https://github.com/OpenSlides/OpenSlides/blob/b3582f462e032b0f5f855447f7bfcf80e706f65f/openslides/assignments/migrations/0001_initial.py#L30) does not note any changes after a certain point

**Comment by matakuka** [comment]
the cause might be related to #2025

**Comment by emanuelschuetze** [comment]
Right, we have to move the translations of assignment phase strings to client side (from models.py to assignments/site.js) - like in #2194. Then you can switch the language by using the OpenSlides language chooser (without changing the browser language and reloading...)
