### ISSUE TITLE
wrong info how to change the logo in the projector page

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2205]
In the settings under projector settings there is the description tha the logo can be changed by copying a file to "static/img/logo-projector.png" in your OpenSlides user folder. This is wrong:

- Instead one needs to replace the file "logo-projector.png" with a file of the same name
- the location of the file "logo-projector.png" is in the subfolder

\Lib\site-packages\openslides\core\static\img

of the OpenSlides user folder.

**Comment by emanuelschuetze** [comment]
I think the settings description is correct. Try it with the portable windows version:
Go to the user data directory "openslides". Create there the folders "static\img". Copy your custom png logo file to "openslides\static\img\logo-projector.png".
Then reload the projector view (sometimes clear browser cache helps!). -> Now you should see the new logo on projector.
