### ISSUE TITLE
"Back" Button in Tags-submenu is not translated

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2207]
When entering a "tag"-Menu, the button for "Back to overview" is labeled with "Back", which will note be translated.

Change the Label from "Back" to "Back to overview", so the translation can happen

![bildschirmfoto von 2016-06-28 15-08-45](https://cloud.githubusercontent.com/assets/10233032/16416437/8696571a-3d42-11e6-9408-9123e62ba2f7.png)

**Comment by tsiegleauq** [comment]
also mentionable, it is the same behavior for the "tag" sub page for
Agenda -> Tags,
Motions -> Tags,
Elections -> Tags

**Comment by emanuelschuetze** [comment]
Fixed with #2231
