### ISSUE TITLE
Load css files for each app

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2209]
Load css files per each app in angular - like js files.

**Comment by FinnStutzenstein** [comment]
Can we then split up these massive app.js and projector.js? I would like this much..

**Comment by emanuelschuetze** [comment]
> Can we then split up these massive app.js and projector.js?

You mean *.css... Yes, we should do it for 2.2

**Comment by normanjaeckel** [comment]
We should setup Sass by the way. But first we should think about #3011 because jspm has also a css loader plugin which can be used easily.

**Comment by FinnStutzenstein** [comment]
Why using a css loader, if we can just concat all css together?
```
gulp.task('css', function () {
    return gulp.src([
            path.join('openslides', '**', 'static', 'css', '**', '*.css'),
        ])
        .pipe(concat('openslides.css'))
        .pipe(gulp.dest(path.join(output_directory, 'css')));
});
```

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein I think we can close this issue because #3507 is merged, right?
