### ISSUE TITLE
Add hint in group list view

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2215]
Add a hint in the template of the group list view that the groups registered and anonymous are special in some way and that all users gain permissions esp. from the group registered so that group permissions in the other groups (delegates, staff, committees, ...) are additional.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel closed with PR #2260 ?

**Comment by emanuelschuetze** [comment]
Yes, done with #2260. Closed.
