### ISSUE TITLE
file upload broken in master

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2223]
I installed OpenSlides (just now again) like in explained in https://github.com/OpenSlides/OpenSlides/blob/master/DEVELOPMENT.rst on two arch linux machines. File Upload does not work. It works on the OpenSlides Demo though.

What I am doing in detailed:
python manage.py start
in webbrowser
login with "admin" "admin"
Go Files -> New
Fill Form to upload an image

![bildschirmfoto von 2016-07-08 22-19-21](https://cloud.githubusercontent.com/assets/10233032/16700474/842d8d0c-455a-11e6-9608-ea558401825f.png)

Klick save and get to see the File List

![bildschirmfoto von 2016-07-08 22-19-28](https://cloud.githubusercontent.com/assets/10233032/16700489/9a58356e-455a-11e6-8879-133b9f13fd86.png)

Inspection of the link results to the supposedly correct path:

![bildschirmfoto von 2016-07-08 22-19-59](https://cloud.githubusercontent.com/assets/10233032/16700500/aa86eeda-455a-11e6-9742-5f56ce310319.png)

Once I click the link to the image ("world") I get to back to "http://localhost:8000/" again instead of seeing the image I just uploaded in a new tab. This error exists on two of my machines but might be the result of insufficient writing privileges of a OpenSlides sub-process?

This is what the console documented after I clicked the "world" link shown above:

> [2016/07/08 22:20:34] HTTP GET /media/file/world-icon--0_nbmqyUT.png/ 200 [0.01, 127.0.0.1:42978]
> [2016/07/08 22:20:34] HTTP GET /angular_js/site/ 200 [0.02, 127.0.0.1:42978]
> [2016/07/08 22:20:36] WebSocket CONNECT /ws/ [127.0.0.1:43196]
> [2016/07/08 22:20:36] HTTP GET /users/whoami/ 200 [0.02, 127.0.0.1:42962]
> [2016/07/08 22:20:36] HTTP GET /core/url_patterns/ 200 [0.03, 127.0.0.1:42954]
> [2016/07/08 22:20:36] HTTP GET /core/servertime/ 200 [0.04, 127.0.0.1:42978]
> [2016/07/08 22:20:36] HTTP GET /rest/core/config/ 200 [0.05, 127.0.0.1:42974]
> [2016/07/08 22:20:36] HTTP GET /rest/core/chatmessage/ 200 [0.08, 127.0.0.1:42970]
> [2016/07/08 22:20:36] HTTP GET /rest/core/projector/ 200 [0.10, 127.0.0.1:42966]
> [2016/07/08 22:20:36] HTTP GET /rest/motions/workflow/ 200 [0.12, 127.0.0.1:42954]
> [2016/07/08 22:20:36] HTTP GET /rest/users/group/ 200 [0.14, 127.0.0.1:42962]
> [2016/07/08 22:20:36] HTTP GET /rest/users/user/1/ 200 [0.03, 127.0.0.1:42962]
> [2016/07/08 22:20:36] WebSocket DISCONNECT /ws/ [127.0.0.1:43196]
> [2016/07/08 22:20:36] HTTP GET /core/servertime/ 200 [0.02, 127.0.0.1:42962]
> [2016/07/08 22:20:37] WebSocket CONNECT /ws/ [127.0.0.1:43200]

Here is the file I am using:
![world-icon--0](https://cloud.githubusercontent.com/assets/10233032/16700580/34d93a34-455b-11e6-83d2-20c9f4438611.png)

**Comment by normanjaeckel** [comment]
Hm. This looks like a bug beeing introduced by the change of the backend server (from tornado to django-channels). Maybe the use of "insecure" does only work for statics but not for media. @ostcar ?

**Comment by emanuelschuetze** [comment]
@ostcar @normanjaeckel This regression blocks us by working on issues with mediafiles (e.g. motion pdf with included images). Can one of you help to find the bug here?

**Comment by ThomasJunk** [comment]
Note:
The actual upload is not broken. The file is in the according (=correct) folder. Any requests to retrieve the file are failing.

**Comment by ThomasJunk** [comment]
I don't know, whether this regression was introduced during django channel upgrade or even earlier.
Suspicious commit may also be 8d638a908d6405dfda81db7e04d0e6b5c6656628 where routing was changed heavily.

As far as I can see is `/media/` not mapped, though configured in settings as `MEDIA_URL`.

```
urlpatterns += [
    url(r'^(?P<url>.*[^/])$', RedirectView.as_view(url='/%(url)s/', permanent=True)),
    url(r'^rest/', include(router.urls)),
    url(r'^agenda/', include('openslides.agenda.urls')),
    url(r'^assignments/', include('openslides.assignments.urls')),
    url(r'^motions/', include('openslides.motions.urls')),
    url(r'^users/', include('openslides.users.urls')),

    # The urls.py of the core app has to be the last entry. It contains the
    # main entry points for OpenSlides' browser clients.
    url(r'^', include('openslides.core.urls')),
```

Have I overlooked some setting?

**Comment by emanuelschuetze** [comment]
The channels commit fe64941aabd0228fc8090ca21f2f99df5204ee20 introduces the problem. With OpenSlides 2.0 the routing of uploaded mediafiles works successfully.

**Comment by emanuelschuetze** [comment]
@normanjaeckel Any idea?

**Comment by ThomasJunk** [comment]
@emanuelschuetze 
You're right. I just read the diff again. I think line 150 of autoupdate.py solves the mystery. 
 ` (r'%s(.*)' % settings.MEDIA_URL,` was the line, I was searching for. 
This is the part of the configuration of tornado 🌪. If I understand that correctly, Tornado delivered the media files. I suppose that with the replacement of Tornado, there is no handling of the `/media/` route anymore.

**Comment by normanjaeckel** [comment]
Yes. One may try to (re)add the media handling to the urls.py. The static file handling which was formerly also done by Tornado is now done with the `insecure` option in the start command and the corresponding line in the urls.py. We need a way like this for media files.

In a big production environment the admin may configure a frontend webserver like Apache to serve static and media directly so we do not need to pay much attention on performance here.

**Comment by ostcar** [comment]
Here is described how: http://stackoverflow.com/a/28063707
