### ISSUE TITLE
Add hook to load custom CSS

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2224]
Add a hook to load custom static files like CSS and fonts. At the moment you can place some files in your personal user data directory but they are not loaded by default. We may add an empty CSS and JS file for this so that is easier to customized template in some way.

**Comment by jsaalfeld** [comment]
It will be possible with the OpenSlides 3 client to add a custom theme or to alter the theme in your way. That way it would be easier to modify Themes.
