### ISSUE TITLE
avoid <img src={a-foreign-server}>

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2228]
in tinymce, please either block the possibility to refer to images on external servers
OR (better)
change the behavior of OpenSlides for foreign images.
After the user refers to an external image, automatically download the image to the OpenSlides server, add it "as a file" and refer to the image like you would do to a local file.

Please avoid every reference to external servers like this:
![bildschirmfoto von 2016-07-18 15-17-08](https://cloud.githubusercontent.com/assets/10233032/16916177/d8b45538-4cfb-11e6-9fc8-5ce7589dca23.png)

Why is this important:
- external Servers are never reliable
- content of external servers might change
- constant internet connection can never be guaranteed
- (either your connection fails or the external server goes offline)
- we can not "work" with external image ressources (e.g. convert them into base64). We need to convert them to use the local javascript based PDF generator (based on pdfmake, see http://pdfmake.org/ for details) on which I am working on right now. The usage of "toDataURL()" and "getImageData()" in external ressources is never safe. See: https://developer.mozilla.org/de/docs/Web/API/HTMLCanvasElement/toDataURL

There are hacks and workarrounds (such as https://coderwall.com/p/pa-2uw/using-external-images-with-canvas-getimagedata-and-todataurl), but I would rather consider not using them, since they maybe open security holes.

**Comment by tsiegleauq** [comment]
Just to remind you, even with the changes to the file handling from [this commit](https://github.com/OpenSlides/OpenSlides/pull/2284/commits/92a541215f6d438d7d11eb231ce39b33c5bd163a), external images still cause problems during PDF generation. It does not work.

@emanuelschuetze 
@normanjaeckel 
@ThomasJunk

**Comment by emanuelschuetze** [comment]
As discussed, we can close this issue if #2705 is fixed. We don't need to avoid images from foreign server.

**Comment by tsiegleauq** [comment]
> We don't need to avoid images from foreign server.

We always gonna need to avoid images from foreign servers because of inconsistent data and CORS header issues.
https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

Image transformation to base64 in the client should only access the OpenSlides server.

**Comment by FinnStutzenstein** [comment]
Without editing the source code of text directly, one cannot paste foreign images into OS in fact that we have now a custom ckeditor image plugin. Imho this is enough "protection" to prevent normal users from using foreign images.

If you have a dufferent opinion please explain and reopen.
