### ISSUE TITLE
Loss of candidates when deleting a poll.

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2244]
While working on a different issue, I found, that in a (not totally improbable) use case, I can make a candidate disappear from the candidate's list. 
1. Make an assignment
2. Start the election, enter values.
3. Mark John Doe as "elected" (by activating the star), but don't publish.
   (At this point: Create pdf --> incorrect list of candidates, missing John Doe)
4. Delete this round of election, without "unelecting" John Doe.
5. Make new round of election
   --> John Doe is no candidate anymore, does not appear on the list, and cannot be added again

Use case: An election round is processed, and in the last check before publishing, an error is noted, making it necessary to do the election again. The administrator just deletes the wrong election. Result: Anyone "elected" in the first election round disappears from the list and cannot be added anymore.

The cause is that a candidate must be `candidate && not elected` to appear on the list. If a round of votes is deleted, the "elected" flags of the round are not, leaving us in a case of "elected without election".

**Comment by emanuelschuetze** [comment]
There is a simple workaround: Just remove the elected candidate from candidate list and readd again from drop down list.

The pdf from step (3) shows now all candidates - also the elected candidates.

I think we can close this issue. The workaround works good enough.
