### ISSUE TITLE
Unnecessary amount of traffic and lag on editing config texts

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2245]
When writing text in the /config form, for example, 'general_event_welcome_text', after every keystroke the field is sent as a PUT request, creating traffic, lag and server usage.

**Comment by emanuelschuetze** [comment]
#2261 fixes this issue. I added a 'wait period' of 1 sec (`ng-model-options="{debounce:1000}"`) before a put request was send.
