### ISSUE TITLE
user import preview silently drops users because of missing columns

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2247]
The use of the import preview in `/users/import` is that you can see which user has to be imported manually/reformatted. However, some users don't even appear on the list: Those with the incorrect number of entries.
**Expected behaviour**: one (partially filed?) line with some information on the line saying *"this user won't be imported"*, or a *"line %s could not be imported because it is badly formatted"*. So the importer can go to the matching line in the csv and check there what/who is wrong.
**Resulting behaviour**: The user silently disappears from the list. On a quick glance, it is impossible to see that a user is missing. One has to compare the number of lines with the number of users imported, and if there is a mismatch, scan the list manually for missing entries.

**Comment by normanjaeckel** [comment]
See #2218.

**Comment by emanuelschuetze** [comment]
I thins this is fixed with new channels release (see #2271)
