### ISSUE TITLE
autoupdate mechanism is broken after introduction of django channels

### ISSUE THREAD

**Issue by ThomasJunk** [OpenSlides/OpenSlides#2248]
Introduced with commit fe64941aabd0228fc8090ca21f2f99df5204ee20

Bug 1)
2016-08-03 12:39:00,523 - ERROR - worker - Error processing message with consumer 
…
  File "/home/thomas/python/OpenSlides/openslides/utils/autoupdate.py", line 89, in send_data
    instance = Model.objects.get(pk=message_pk)
…
openslides.motions.models.DoesNotExist: Motion matching query does not exist.

Steps to reproduce:
Create a new motion

Always reproducible.

Bug 2) 
2016-08-03 12:53:44,475 - ERROR - worker - Error processing message with consumer openslides.utils.autoupdate.send_data:
Traceback (most recent call last):
  File "/home/thomas/python/env/lib/python3.5/site-packages/channels/worker.py", line 111, in run
    consumer(message, **kwargs)
  File "/home/thomas/python/OpenSlides/openslides/utils/autoupdate.py", line 93, in send_data
    'id': instance.get_rest_pk(),
UnboundLocalError: local variable 'instance' referenced before assignment

Steps to reproduce:
upload media.
delete media.

Always reproducible.

The according code is: 

```
def send_data(message):
…
    if not message['is_deleted']:
        Model = get_model_from_collection_string(message['collection_string'])
        instance = Model.objects.get(pk=message['pk'])
…
    for user in itertools.chain(get_logged_in_users(), [AnonymousUser()]):
    …
            'id': instance.get_rest_pk(),
    
        if not message['is_deleted']:
   …
```

If a message is in the state of 'is_deleted' the `instance` is never defined. Therefore instance.get_rest_pk() is called before defined. 

As far as I can does `instance.get_rest_pk()` equal `message['pk']`. That would fix (2).

But in case, a 'create' message is processed `Model.objects.get(pk=message['pk'])` should fail, since there isn't an object to retrieve. 

Is there any way to distinguish messages per type other than `is_deleted`?
Where are (possible) messages defined? 

As a Newb I need some help :]

@ostcar @normanjaeckel

**Comment by normanjaeckel** [comment]
Added fix for case 2. In case 1 Model.objects.get(pk=message['pk']) should not fail because the object is already created before the autoupdate process starts to distribute the message to the clients.

**Comment by normanjaeckel** [comment]
Creating works for users, custom slides and thelike but not for motions. So I think this is a special motion problem.

**Comment by emanuelschuetze** [comment]
Case 2 is now fixed (and merged) with PR#2250. Thanks to @normanjaeckel .

Still open: the `openslides.motions.models.DoesNotExist` error

**Comment by ThomasJunk** [comment]
I am looking into that.

**Comment by ThomasJunk** [comment]
@normanjaeckel 

> Creating works for users, custom slides and thelike but not for motions. So I think this is a special motion problem.

I don't know. I played with the autoupdater and got the following interesting straces:

[trace1.txt](https://github.com/OpenSlides/OpenSlides/files/401880/trace1.txt)
[trace2.txt](https://github.com/OpenSlides/OpenSlides/files/401879/trace2.txt)

trace1.txt is from simply creating a poll.
trace2.txt is from creating a motion.

For debugging reasons, I added `print(json.dumps([(k, v) for k, v in message.items()]))` at the very beginning of the autoupdater.py

Line 1 from trace1.txt contains the `recvfrom` systemcall. That is, when the `POST` is received at the server. 

Line 23 contains my Print-statement `write(1, ..` to stdout.

Between line 1 and 23 there is in Line 17 and Line 20 a `write` to a `fd` belonging to sqlite.
I suppose, that at this point $somewhere data is written to sqite. 

Line 24, 25 have an `open`-call to sqlite.
Line 26 has the `sendto` (according to the socket acquired on line2).

So there is no problem with __polls__.

Another picture is for __motions__:
Between `recvfrom` and `write(2` a write to stderr, there is only one write, `write(1` in line 5, which is my `print`.

So, I think my statement
> But in case, a 'create' message is processed Model.objects.get(pk=message['pk']) should fail, since there isn't an object to retrieve.

holds in as far, that the message is send _too early_. 

To reproduce: 
`sudo strace -q -s9999 -e network,open,write,close -tt -y -v -f -p $pid -o ~/$filename`

The `-e` flag specifies which systemcalls, you wish to trace (here: _network,open,write,close_)

**Comment by normanjaeckel** [comment]
I can't explain: `send_data` is called by `inform_changed_data` which is called by `inform_changed_data_receiver` which is a Django signal receiver that is connected to the `post_save` signal. This signal is fired after `model.save()` is called so I would expect that the data is already available.

I have an idea. @ThomasJunk do you want to check it? In `motions.serializer.MotionSerializer.create()` we use an atomic transaction. So we call `model.save()` and then do some other stuff before the transaction is finally committed to the database. Maybe the Channel is faster than this.

**Comment by ThomasJunk** [comment]
Hm. Seem really tricky :D 

Out of curiosity: It would be interesting to know, whether this occurs only with sqlite or any other backend ... 

I'll have a fresh look tomorrow ;)

**Comment by ThomasJunk** [comment]
Huh?! Okay: Here are my findings:
According to the [documentation](https://docs.djangoproject.com/ja/1.9/topics/db/transactions/#tying-transactions-to-http-requests), everything works like _expected_, only that we are expecting the wrong things(?): 

> A common way to handle transactions on the web is to wrap each request in a transaction. Set ATOMIC_REQUESTS to True in the configuration of each database for which you want to enable this behavior.

> It works like this. Before calling a view function, Django starts a transaction. If the response is produced without problems, Django commits the transaction. If the view produces an exception, Django rolls back the transaction.

> Middleware runs outside of the transaction, and so does the rendering of template responses.

In our context, it reads like this:

`transaction.atomic` starts a transactional context, when the request ist received. Then whatever is done during the transaction is written (read: _within the transactional context, which is not finished_) to the database. After the _database stuff_ (in our case `Model.save()`) is done: _simply _nothing_ happens.
The request is processed further. _After that has happened without exception_, the final `commit` is written in the transaction and changes become persistent. Middleware runs outside, means that there is a possible _race_ of writing and _reading_ where in case of _motions_ `get` wins over `save`.

If that is true - and the interpretation holds to the made observations - this renders `transaction.atomic` in the context of a _realtime_ / _websocket_ context useless?
 
Just for fun, I removed the `transaction.atomic` from the `create` and it seems to work like a charm.

At first I thought `transaction.atomic` of being something like `transaction isolation levels` (aka `read dirty/uncommited | read committed | repeatable read | serializable` ), but this seems not to be the case.

Could anybody confirm my findings?

**Comment by ThomasJunk** [comment]
@normanjaeckel 

> Maybe the Channel is faster than this.

From the above: it is not really _faster_ it is as a middleware (?) _cheating_ :D

**Comment by emanuelschuetze** [comment]
I tested successfully case 1 with pull request #2256: 
After creating new motion there are no `openslides.motions.models.DoesNotExist` any more.
