### ISSUE TITLE
Majority indicators on polls

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2258]
(I am currently working on:)

Creating an indicator for each election candiate to see if a certain mayority is reached:
- relative mayority (more votes than other candidates)
- absolute mayority (50% + 1 of the valid votes)
- two/third mayority (66% + 1 of the valid votes)
- ... (suggestions?)

I think it should be a button with a drop-down menu (to select the mayority calculation). Candidates that pass the calculation will be displayed differently, so a voting committee can easily see which candidates reached the threshold. On mouseover/click, an informative text is displayed that tells details:
- which of the mayorities is reached/not reached
- how many votes are missing/in excess for the respective step
- example: `John Doe got 50 of 100 votes. This is the relative mayority (10 votes). This is not the absolute mayority of 51 votes (1 vote missing). This is not a two-third mayority of 67 votes (17 votes missing)`

I guess there will be some questions on the more complicated voting methods and their mayority calculations, especially in connection with e.g. yes/no/abstain method.

**Comment by normanjaeckel** [comment]
Do not forget to care about the yes-no-abstain election modus. Then the  meaning of the terms of majority changes ...

**Comment by matakuka** [comment]
Indeed it gets complicated. My *feeling* says the percentages are is always on the base of the valid votes, but I did not dig into the deeps of democratic calculations yet. I will soon prepare a list/chart of all election modes and possible results.
**When this list is done, I will need advice from a more user side view**, being "which is the correct definition of majority `#n`".

What I'm doing beside this democrato-mathematic stuff:
- creating two (server-side) poll variables that sort the candidates after the poll has been commited: 
 - `position` in the list of candidates on account of `Yes` votes (if candidates share the amount of yes votes, lower `No` Votes are first). 
   - Server-side because else I would need to retrieve every candidates' votes before displaying a result. Also, this sorting could get useful elsewhere (sorting the result slide by position instead of name) 
 - `is_uniqe` Set to False if there are other candidates with the same amount of votes.
   - If there are more candidates than posts left, the resulting color/message should be a warning, allowing for a second election round. If not, it is just a question of ego who is displayed first, which I would leave to `orderBy name`.
- client side calculations:
 -  votes | yesvotes > than (`Yes * 3 / 2`| `Yes /2` |`Yes * (whatever)`?
   - TODO here: which is the base?
 - is `unique= false` relevant for the current position? (If there are less or equal candidates than posts available, we can return a "green") 
- display as table column `majority reached` in the election result view:
 - color code: 
    - red: did not reach the (configurable) criteria to be elected
    - yellow: ambigious result: e.g. "There is one post, but two candidates share the same amount of votes"
    - green: reached criteria and the software  calculation recommends election
 - text (in ascending order of priority?):
   - `relative majority: position: n` (n being less or equal than available posts)
    -  `absolute majority` (over 50% of [calculationbase])
    - `two-third majority` (over 66% of [calculationbase])
- popup or similar: Tell the manager how far from each majority threshold the candidate is.
 
Spotlight: What to display if four candidates for one post reach a 2/3 majority, because the voting method allowed for several "yes"? --> only the one with best yes/no relation should get green

**Comment by matakuka** [comment]
Further thoughts on this: 

1) Config for the formula, so that a manager can decide. `*` being the default. Accesible from config and directly from the voting result pages, as popup/overlay:
 - Select the conditions for majority (green):
  -   `*Over*|At least`  `33|*50*|66|own number` percent of `all votes|*all valid*|all valid without abstains|sum of all Yes votes`
   - relative majority by `n` votes over other candidates. If candidates are equal, order by `No/Abstains` (yes/no)?
 - partial success (yellow): 
   - `first n candidates with relative majority`
   - `first n candidates with relative majority that reach the conditions`
   - `all candidates that reach the conditions`

2) If there are more winners than posts, it will always be a "partial success". 

3) If there are less candidates with at least "partial success" than posts, a warning will be displayed.

4) Each candidate will have an "explanation" popup when clicking on the `majority reached?` indicator. There will also be a `suggestion: elect` button, which will pop up a `confirm election?` and then marks the candidate as elected. 

5) A button should appear that transports either
- all remaining candidates
- only "partially successful" candidates

to a next voting (behaviour now: all "not elected" candidates).

6) The whole system breaks and therefore is disabled when "-1"(majority) or "-2" (undocumented) appear. There, a "majority" should get a green if there are enough posts available, else "yellow". If those cases are mixed with positive numbers, this should result in an error (ideally, already upon validating the poll form)

**Comment by matakuka** [comment]
**How to handle config?**
As for now, the config I am using for determining the majority is a list of javascript objects (example see below).  I am unsure where to store this amount of configs (server side or in javascript).
- each user should have a personal setting, not demanded by server
- it would be nice to "remember" those settings for a next meeting
- it may be one, two or more conditions
- there should be predefined options for frequent use cases

example: 
```
var std_majority_calculation = {
    cond1 : { 
        method: 'relative',
        active: true,
        precondition: true,
        autosort: true,
        positions_considered: 'posts',
        positions_amount: 0,
        distribute: true},
    cond2 : {
        method: 'percent',
        active: true,
        amount: 66.6666666666,
        equal: false,
        precondition: false}
};
```
Without going into deep details, this example has two conditions:  *must have a relative majority (cond1), and must reach more than 66,66% of votes (cond2)*. More (or less) conditions could be configured. The software gives "green" if *all* conditions are met, and "yellow" if only some are met or several users could not be sorted and could equally be winners.
So, if in a first round, no one reaches a 2/3 majority, you still can pick the "5 best results" and carry them to a next round.

**Comment by matakuka** [comment]
PR see #2509

**Comment by emanuelschuetze** [comment]
Done with #2509
