### ISSUE TITLE
New category sort view

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2259]
Add a new view to sort all motions of a category via drag&drop (similar to agenda sort view).

A button "numbering" should renumber the identifer of each (sorted) motion, e.g. B 1, B 2, ...
You can use the code snippet from my test branch to see the right post request url: https://github.com/OpenSlides/OpenSlides/compare/master...emanuelschuetze:NumberCategories2#diff-8ace1613d1310b7a1a40a1676da3cb6cR1027

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze The numbering with the post request works fine, but:
The motions will be numbered after their id; If I reorder them, the numbering function don't get the information about the new order and orders them still after their id's. I mean, somehow I have to pass the new order to numbering, so it could renumber the motions correctly.

Is it a good way to pass a list of the new sorted id's to numbering, so numbering could iterate through this list and reidentify the motions?

**Comment by emanuelschuetze** [comment]
Good question. 
@normanjaeckel Looks like the [numbering function in views.py](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/views.py#L305) should be expand that a sorted motion list can be pass by client with the post request.

**Comment by normanjaeckel** [comment]
See #2273.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Please test #2273

**Comment by emanuelschuetze** [comment]
#2273 is merged now.
