### ISSUE TITLE
Feature requests: Search improvements

### ISSUE THREAD

**Issue by ghost** [OpenSlides/OpenSlides#2263]
Search could need (see also #2255):
- [ ] 'repairing' of special characters, so a `=` (and others) doesn't erase/shorten the query.
- [ ] separating words and searching for occurrence of both words (`John President` returns presidents named John, not only a person named "John President")
  - this could be done by splicing the query, sending first word to server, and filtering results for occurrence of second word
- [ ] tolerance towards Upper/lowercase changes (`john` returns `John`)
- [ ] tolerance to mis-spelling? (`Jon` also returns `John`)
  - Discussion needed: How much tolerance should there be? We should avoid spamming lots of "similar" replies
- [ ] search for certain aspects only (like `name:John` not returning items that only have "John" in  the description)
- [ ] return the context the result relies on ("'Election: Master of the Universe' is returned for a search for John because John is candidate there")
- [ ] stopping queries that result in useless answer spam (query: `is`)

**Comment by matakuka** [comment]
- [ ]  suboptions. I search for `users`named `John`, but only want to get the Johns that are `present` | `elected` | `in group "delegates"`

**Comment by jsaalfeld** [comment]
Since the client will be completely rewritten, I think these issue won't be relevant anymore. Please reopen if I'm wrong.
