### ISSUE TITLE
Feature request: Unproject slides

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2264]
Provide a fast method for each slide to be "unprojected" again. 

*If a manager projects a slide and sees it is a mistake (e.g. slide is displayed too early), the first "panic reaction" is clicking on the "project" button again, which, in most cases, does nothing.*

**Desired:** Display a neutral slide (starting slide? slide saying: "One moment please..."? Blank slide?) if no slide is marked for projection, and add the possibility to unmark the projected slide

**Comment by matakuka** [comment]
I think the best place for such a button would be in core/projector-controls. This would avoid accidental double-clicking, but can be reached fast in an expected place. I'll prepare some suggestion (but it has lower priority).

**Comment by emanuelschuetze** [comment]
Good idea to unproject slides! - My suggestion: each activated project button should unproject the slide by clicking a second time (then the button is deactivated / no longer a primary button).
What do you mean with projector-controls?

**Comment by matakuka** [comment]
I mean the drop-down menu on the right (I called it projector-controls as the template has this name).

The disadvantage of the "click/click again solution" is that it could be frustrating if the server or javascript somehow reacts in different speeds than the user assumes 
- "doesn't work! I'll click again" | "I doubleclick on everything, especially blue buttons" = two state changes where one is intended.

A big red (or blue) button on the right is a failsafe option (although the Average_User[myself] did indeed click on the "project" button again)

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Maybe you can do this in your multiprojector pr.

**Comment by FinnStutzenstein** [comment]
It is already implemented ;) I thought it is a good idea to have this feature.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze done with multiprojector.
