### ISSUE TITLE
Unhandled error with category numbering

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2265]
I got an unhandled error when trying to number all motions in one category. Setup:
Category A:
- Motion One, ID: X
- Motion Two, ID: A 2
  Category B:
- Motion Three, ID: A 1

Obviously, the numbering of category A fails, because ID "A 1" is already defined. But it gives a traceback and this [html document](https://github.com/OpenSlides/OpenSlides/files/411264/error.html.txt) (you have to rename it back to .html) in the response. There should be some error-checking and validation to give an structured error to display, maybe which motion is blocking the numbering, so the user can fix it by himself.

**Comment by emanuelschuetze** [comment]
I'll test it

**Comment by emanuelschuetze** [comment]
Tested: After trying to renumbering I get a correct error message:
![test](https://cloud.githubusercontent.com/assets/2075427/21954746/f6e209dc-da5a-11e6-92fb-5de8b191adee.png)

So I think we can close it. @normanjaeckel ok?
