### ISSUE TITLE
500er error with djangorestframework>=3.4.0

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2275]
When trying to edit ones group permissions, I get `OPTIONS http://192.168.46.10:9999/rest/users/group/ 500 (Internal Server Error)` with all versions of `djangorestframework` 3.4.x. it works with version 3.3.3.

**Comment by emanuelschuetze** [comment]
@normanjaeckel Any idea?

**Comment by normanjaeckel** [comment]
https://github.com/tomchristie/django-rest-framework/issues/3751

They swipped out our metadata content so we have to readd it in GroupViewSetMetadata.get_field_info.

**Comment by normanjaeckel** [comment]
Problem not fixed. We have to change  GroupViewSetMetadata.get_field_info and then update to djangorestframework 4.x

**Comment by matakuka** [comment]
Maybe it is just a minor change: 

openslides/users/views.py:176 pp.

```
if field.field_name == 'permissions':
            for choice in field.choices:
```
gets you a `"agenda | item | Can manage agenda"`

The difference will be that choices is no dict any more, and I don't know a) where it is used and b) if you need other information from choices{} somewhere

**Comment by normanjaeckel** [comment]
We can see [here](https://github.com/tomchristie/django-rest-framework/pull/4021/files) that they removed the choices field completely. There should not be a dict any more and not even a string. But we have to readd the content we had before at this place.
