### ISSUE TITLE
Allow fake models for autoupdate cycle

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2278]
At the moment our autoupdate collections (see `collection_string`) have to be Django models. It is not possible to use an non Django model Python object to send information via autoupdate by a plugin. In autoupdate.py `send_data` we use `Model = get_model_from_collection_string(message['collection_string'])` and `instance = Model.objects.get(pk=message['pk'])` which force to use Django models.

Proposal: Lets add either some logic or a small layer in between so that plugins can create fake models to send calculated data to the clients. Example: A plugin wants to add an API endpoint. All users should be informed if this endpoint is triggered.

**Comment by normanjaeckel** [comment]
@ostcar Any comments on this? If not I would try something the next days.

**Comment by ostcar** [comment]
I think fake_models sounds a bit hacky. It should also be possible, to send something else then a model to the clients. There could be a function send_custom_data(dict) that sends the dict to the client.

The bigger problem is the client side, which has to decide if a model is received or thomething else. But I think this can be solved. We already have a receiver on the client-side. So there can be more then one function on the client, that gets the data. Each function has to look at the data and decide, if it should do something with it or ignore it. For example:
```javascript
if ('collection' in data) {
  do_something();
} else {
  ignore();
}
```

**Comment by normanjaeckel** [comment]
Please let us know if you need fake models in plugins.

**Comment by ostcar** [comment]
This is solved, see https://github.com/OpenSlides/OpenSlides/issues/2468#issuecomment-435772953
