### ISSUE TITLE
Followup for issue #2284

### ISSUE THREAD

**Issue by ThomasJunk** [OpenSlides/OpenSlides#2288]
After merging of #2284 there are several points left:

* Extract PDF-Components to separate module (core/site.js, motions/site.js)
* Beautify code indentation (use 4 instead of 8 spaces) in (core/site.js)
* There are open issues regarding Firefox and PNG #2287 
* Line numbering is not implemented
* For printing of multiple motions, one needs to implement a ContentProvdider which does the job.
Idea: MotionContentProvider has a method `motionContentProvider.getContent(motion, $scope, User);` which generates an Array for one motion. To render multiple motions, one could iterate over the array of motions and concat the results 
Pseudocode: 
`return motions.map(function(motion){  ... return motionContentProvider.getContent(motion, $scope, User);   }).reduce(  function(o,n){ var tmp=o.concat(n); return tmp;  },[] )`.

...more to come

**Comment by ThomasJunk** [comment]
In order to completely substitute reportlab, ballot papers have to be generated via pdfMake.
I scribbled  together a quick version at the playground of pdfMake.
To enhance, the borderstyle of the used table has to be a little tweaked.

[stimmzettel.txt](https://github.com/OpenSlides/OpenSlides/files/428136/stimmzettel.txt)

**Comment by normanjaeckel** [comment]
I think we also need the circles or boxes where you can check your vote.

**Comment by tsiegleauq** [comment]
I also noticed that (insanely) huge images do not display in PDF.
Somewhat large images also render ober the page-width.

This is not really an issue, since I would absolutely expect that it creates insanely huge images, but we can and should solve it nevertheless.

**Comment by tsiegleauq** [comment]
I created issues out of the information provided here. I guess this can be closed now.

**Comment by emanuelschuetze** [comment]
Ok, closed.
