### ISSUE TITLE
Error: pdfMake is not defined in /motion

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2294]
*in current master*
to reproduce:
1. create a motion
2. enter motion detail page
3. click "pdf"

`Error: pdfMake is not defined 
$scope.makePDF/<@http://.../static/js/motions/site.js:821:19`

**Comment by tsiegleauq** [comment]
Cannot reproduce.
You are either not on current Master or did not delete your cache.

if
`less openslides/motions/static/js/motions/site.js | grep pdfMake`

dies return something for you, you are on Master and just need to wipe your browsers cache.
If this does not return a thing you are not on master.

**Comment by matakuka** [comment]
sorry, was a cache problem

**Comment by tsiegleauq** [comment]
to never fear about cache problems again try to "Disable cache (while DevTools is open)" in your chrome/chromium or "deactivate cache while toolbox open" on firefox
