### ISSUE TITLE
make ballot papers with pdfmake

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2298]
By @ThomasJunk  from #2288 

> In order to completely substitute reportlab, ballot papers have to be generated via pdfMake.
I scribbled together a quick version at the playground of pdfMake.
To enhance, the borderstyle of the used table has to be a little tweaked.

[https://github.com/OpenSlides/OpenSlides/files/428136/stimmzettel.txt](url)

Ballot paper shall contain the Motion number, the title of the motion, options for "yes", "no" "abstention".
An A4 Page shall contain 6 "section" with bullet papers.

We also need the circle somehow

**Comment by emanuelschuetze** [comment]
options are: Yes/No/Abstain (not abstention)
