### ISSUE TITLE
Motion catalog over pdfmake

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2299]
By @ThomasJunk from #2288 
 
> For printing of multiple motions, one needs to implement a ContentProvdider which does the job. Idea: MotionContentProvider has a method motionContentProvider.getContent(motion, $scope, User); which generates an Array for one motion. To render multiple motions, one could iterate over the array of motions and concat the results Pseudocode: return motions.map(function(motion){ ... return motionContentProvider.getContent(motion, $scope, User); }).reduce( function(o,n){ var tmp=o.concat(n); return tmp; },[] ).

The motion catalog shall contain:

---
(Page One:)
Heading: "Motions"

(if there are any categories, a list of categories with the Prefix and Name on first page)
Heading2: "Categories"
{Prefix} {Name}

(page two if there are categories, still one if there aren't, a table of contents with the following setup)
Heading2: "Table of Contents"
"Motion" {if set: the Category prefix} {Number}: {title} {space or dots to end of page} {page number}

---
Followed by the printable versions of the motions were every Motion is on a new page.

The page number shall be absolute to the number of pages of the catalog and not be relative to the motion.

The differences to the current ReportLab implementation are the page numbers in the toc as well as the Heading "Table of Contents"

If this is not the case or there are other requirements correct me here

@emanuelschuetze 
@normanjaeckel

**Comment by emanuelschuetze** [comment]
@tsiegleauq yes, as discussed
