### ISSUE TITLE
Line numbers in PDF for Motions

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2300]
by @ThomasJunk from #2288

> Line numbering is not implemented

Line numbers have been intruduced in #2292 and need to be in the PDF as well.
According to what I saw all the required information are in the plain HTML code, so if line numbers are activated in a motion the PDF shall be generated with containing line numbers.

Superscript and Subscript numbers are currently not possible with pdfmake [https://github.com/bpampuch/pdfmake/issues/36](url)

**Comment by emanuelschuetze** [comment]
There are two different kinds of line numbering:
1. outside - should work in pdfmake
2. inline - superscript style is prefered, but you can also use just a smaller font size.
This issue has high priority.

**Comment by tsiegleauq** [comment]
> but you can also use just a smaller font size This issue has high priority.

I can do it that way. We can change it again once pdfmake starts supporting superscript and subscript.

**Comment by tsiegleauq** [comment]
@emanuelschuetze 
I looked a little deeper into this.
As you might remember, my very first statement was that the line-number plugin shall rather be designed to work with the PDF-plugin than vice versa, since the PDF plugin is designed to crawl over HTML-code and parse it into a PDF and should be as generic as possible to be compatible with the upstream of makepdf.

After looking into the line numbers plugin I saw that all required information is present in the HTML source code, so adapting it into the PDF-creation should not be too difficult.

**However**, the information might be in the HTML code, but not in the motion object itself!
Therefore, we would need to "just guess" when a new line starts.

Considering all the `<br />`, `<span>` and `<p>` is not hard, but counting untill the 81st character is actually impossible, since I did not design the parser to count the printed characters. Considering that would require a full rewrite of the pdf-generator.

The PDF generatior already supports protected spaces, tables, and some sort of distances, therefore it seems much more reasonable to change the line number plugin to work with the current state of the pdf generator

**Comment by emanuelschuetze** [comment]
As discussed: Use `motion.getTextWithLineBreaks(version)`, see
https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/js/motions/base.js#L154 and
https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/templates/motions/motion-detail.html#L276
