### ISSUE TITLE
scale insanely large images for PDF generation

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2301]
By myself in #2288 

> I also noticed that (insanely) huge images do not display in PDF.
> Somewhat large images also render over the page-width.
> 
> This is not really an issue, since I would absolutely expect that it creates insanely huge images, but we can and should solve it nevertheless.
> 
> Or maybe this can get fixed in pdfmake's upstream?

**Comment by lesteenman** [comment]
High-resolution images seem to cause issues either way, since it renders very slowly. If they could be optimized before rendering, it would likely help a lot.

**Comment by tsiegleauq** [comment]
this does not sound like an issue to me. If the user wants to use a full grown image, he shall live with the consequences. Image manipulation over JS is not that easy and the python image library is frowned upon in OpenSlides.

Waiting a little for the document to be generated is completely normal, since you need to convert a lot of stuff into base64 which takes a while.

If this is too much for some reason you might want to create a dedicated issue for that.
