### ISSUE TITLE
Permissions to see objects on the projector.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2302]
See discussion [here](https://github.com/OpenSlides/OpenSlides/pull/2241/files#diff-6c3a4eee52612ead0a8e34f29168811cR148). Then question is whether we want to move down restrictions for **all** users if a slide needs to display some speakers, candidates, submitters and thelike. Or if we want to implement some kind of reload of the projector if some user changes. Or if we want to add some more data like the name of the user to our models (speaker model, poll option, ...).

**Comment by normanjaeckel** [comment]
@ostcar What do you think?

**Comment by ostcar** [comment]
I like our current way. If you add permission for some users then the only Thing we need is a way to request some users to the rest api. For example: give the users with the ids 5, 46 and 50. Dango Rest framework and js-data support this.

**Comment by matakuka** [comment]
The problems I am having on slides with "can_see_projector" only¹:
- Getting a subitem (Assignment -> agenda_item) only works upon reloading the page (F5). Changes in agenda_item are not updated, unless I have can_see_agenda. This applies both to Agenda.find() and Assignment.loadRelations()
- Displaying speaker lists (in the new overlay or in the existing agenda list of speakers) requires can_see_usernames. A get_requirements of item.speakers.all() does not work, and item.speakers will change before I access the projector.py again.

¹setup: load the non-privileged user in a different browser or in "private mode" so you don't share cache with the projector managing browser

**Comment by emanuelschuetze** [comment]
was done by #2394
