### ISSUE TITLE
Find a nice "fullscreen" icon

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2316]
low priority:

find a bootstrap icon for fullscreen buttons, as in openslides/agenda/static/templates/agenda/current-list-of-speakers.html:6 (see #2235)

**Comment by FinnStutzenstein** [comment]
These [icons](http://fontawesome.io/icons/) are included. There is one fullscreen icon, but it is not the prettiest. You may make an [icon request](https://github.com/FortAwesome/Font-Awesome/issues).

**Comment by matakuka** [comment]
[arrows-alt](http://fontawesome.io/icon/arrows-alt/) would be my preference.

**Comment by FinnStutzenstein** [comment]
or [expand](http://fontawesome.io/icon/expand/)?

**Comment by emanuelschuetze** [comment]
@matakuka Please use the fa-expand icon for fullscreen. Thx.
