### ISSUE TITLE
(Restricted) data are not cleared on logout

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2322]
Admin logs in on browser, logs out, Joe logs in on the same browser, has the cache of Admin. 

Joe won't receive any updates he is not allowed to receive, but can still access the (cached) data. 

The only thing stopping him from doing so is that the data is not _shown_. Still, it is a security concern, and I have had cases where I could see data I was not allowed to (user names).

`sessionStorage.clear();` on logout might resolve this; we will need to go fetching all the resolves Joe should have access to when Joe logs in, which might affect the user experience in terms of speed.

**Comment by matakuka** [comment]
This will affect #2295, as with this, the "beginning" will not be on page load, but on user login.

**Comment by normanjaeckel** [comment]
I can not reproduce this with current master.
