### ISSUE TITLE
Motion inline line numbers do not support long words

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2327]
When entering long words, the inline line numbers have some strange behavior

![bildschirmfoto von 2016-08-29 00-45-39](https://cloud.githubusercontent.com/assets/10233032/18037362/01ec2290-6d82-11e6-94b6-da340c0eb7d9.png)

**Comment by normanjaeckel** [comment]
@tsiegleauq Can you please also post the outside and the none view of this motion that we can compare the things easier?
@CatoTH Can you reproduce this?

**Comment by tsiegleauq** [comment]
Hi.
> Can you please also post the outside and the none view of this motion that we can compare the things easier?

Outside:
![bildschirmfoto von 2016-08-29 02-05-46](https://cloud.githubusercontent.com/assets/10233032/18037800/2e7c2b6a-6d8d-11e6-9b94-680e8db3bb38.png)

None (could also look cleaner)
![bildschirmfoto von 2016-08-29 02-05-53](https://cloud.githubusercontent.com/assets/10233032/18037802/37a0cb24-6d8d-11e6-84cd-a60812f56aee.png)

Basically, this is my testing string. (I used it to research stuff about the line-printing behaviour for the pdf)

`123456789123456789123456789123456789123456 78912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912 345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678912345678 9123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789`

**Comment by emanuelschuetze** [comment]
@CatoTH Can you look at this issue please? In None mode there should be added linebreaks if line is to long.

**Comment by tsiegleauq** [comment]
to show some more "legitamte" words in the german language, which actually allows words with 92 characters and more, see this example:

![bildschirmfoto von 2016-09-09 13-04-27](https://cloud.githubusercontent.com/assets/10233032/18385028/5ba5c24a-768e-11e6-9979-5f9ea9e5933b.png)

![bildschirmfoto von 2016-09-09 13-04-37](https://cloud.githubusercontent.com/assets/10233032/18385032/62914fd4-768e-11e6-9eaf-3e49af8d7bd7.png)

![bildschirmfoto von 2016-09-09 13-04-46](https://cloud.githubusercontent.com/assets/10233032/18385034/670cfb76-768e-11e6-8897-ff9855563723.png)

**Comment by CatoTH** [comment]
I wonder what the desired output would be. With a line length of x, some words will need to be split. The most simple improvement would be to add hyphens at the end of the line. It also would be possible to use an algorithm to break the words according to hyphenation rules (e.g. the one used by https://github.com/mnater/Hyphenator), which would be more correct, though it would add quite a bit of additional complexity.

**Comment by normanjaeckel** [comment]
I think we do not need hyphenations at the moment but we can open an issue for this.

**Comment by emanuelschuetze** [comment]
Talked with @CatoTH:
We think we can ignore this issue. Long lines (e.g. urls) should simple break after x chars (also for clear rendering in pdf). 

So my suggestion: close this issues now.

**Comment by emanuelschuetze** [comment]
No reaction. So I'll close this. Please reopen if someone has a specific suggestion.
