### ISSUE TITLE
Agenda Tree does not autoupdate correctly

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2329]
**Problem:**
The agenda list (agenda/base.js:AgendaTree) keeps deleted entries. A page reload does not help if you have cache enabled.

**Probable cause:**
Autoupdate does not correctly send information on deleted data

The cause for this starts in utils/autoupdate.py: 119
```
                 'pk': root_instance.pk,
```
The root_instance calling the "send delete information" is queried for "which object is deleted?", but the object *is already deleted* at this point and can't be queried anymore. In the end, *pk:null* is sent to javascript.

AgendaTree currently seems to be the only function affected, because it uses the (correct, desired) *"resolve, then watch all updates sent per autoupdate"* model. 

All functions correctly using the resolve should have this problem. = most functions don't use resolve the way it is intended

**Comment by emanuelschuetze** [comment]
@normanjaeckel Any idea?
