### ISSUE TITLE
Load angular-gettext language files from plugins

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2339]
Find a way to load angular-gettext json files from plugins

Currently [here](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/core/static/js/core/base.js#L128) the language file from OpenSlides core is loaded - depending on selected language: `gettextCatalog.loadRemote("static/i18n/" + lang + ".json");`

**Comment by emanuelschuetze** [comment]
Any idea how we can implement a generic solution in core?

**Comment by normanjaeckel** [comment]
We can use a plugin registration hook. All plugins have to register themselves over there. Then the language factory can use some API of our hook to loop over all plugins.

**Comment by emanuelschuetze** [comment]
@normanjaeckel I need your help here. Can you implement this or give me a code example that I can try it?

**Comment by normanjaeckel** [comment]
Something like:

```javascript
// core
.provider('OpenSlidesPlugins', [
    function () {
        var provider = this;
        provider.plugins = [];
        provider.registerPlugin = function (plugin) {
            provider.plugins.push(plugin);
        };
        provider.$get = [
            function () {
                return {
                    getAll: function () {
                        return provider.plugins;
                    }
                };
            }
        ];
    }
])


// Plugin
.config([
    'OpenSlidesPluginsProvider',
    function () {
        OpenSlidesPluginsProvider.registerPlugin({
            name: ...,
            whatElseDoYouWantToKnow: ...
        });
    }
])



// Core again

.someAngularStuff('SomeAngularStuff', [
    ...
    'OpenSlidesPlugins'
    ...
    function (..., OpenSlidesPlugins, ...) {
        ...
        OpenSlidesPlugins.getAll()  // This should return everything that has been registered before.
    }
])

**Comment by FinnStutzenstein** [comment]
Is it possible to load two or more languagefiles at once?
