### ISSUE TITLE
Possibility for plugins to set a verbose name in the permission matrix

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2341]
A plugin that adds new permissions is shown in the matrix with a technical name. It should be possible to use a human readable verbose name. Example https://github.com/OpenSlides/openslides-votecollector.

**Comment by FinnStutzenstein** [comment]
A simple solution (but not the best) would be to make an entry for each existing plugin in the `users/site.js`. Like for the app users: [entry for users](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/users/static/js/users/site.js#L1055)

A smarter solution is to iterate through all registered plugins. So where do the plugins register? I quickly recognized the `MainMenu`-Provider. Is this the right place?

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Ping

**Comment by normanjaeckel** [comment]
We have a new plugin provider now so we can use this. See somewhere in core/base.js I think.
