### ISSUE TITLE
Label for "commit a bill"

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2342]
In complex workflow we have a state "committed a bill" with the action word "Commit a bill". Is this correct? I think the word we need is "committed" / "commit" but the extra part "a bill" does not belong to the sense of this state because we do not deal about legislative bills in special but about motions in general.

**Comment by emanuelschuetze** [comment]
My suggestion for a much better wording:
 "Refered to committee" / "Refer to committee" (action word) 
(In German we use already the right expression: "In Ausschuss verwiesen" / "In Ausschuss verweisen")

@normanjaeckel ok? If yes you can just change it in #2344.

**Comment by emanuelschuetze** [comment]
and the recommendation could be:
"Referral to committee" (German: Verweisung/Überweisung in Ausschuss? - I'm not sure here)

**Comment by normanjaeckel** [comment]
Ok. Changed.
