### ISSUE TITLE
Add doc export for motions

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2346]
Export selected motions from motion list view as doc (or docx) format.

Try e.g. [html-docx-js](https://github.com/evidenceprime/html-docx-js)

**Comment by normanjaeckel** [comment]
> Altchunks [the feature of html-docx-js, NJ] were not supported by Microsoft Word for Mac 2008 and are not supported by LibreOffice and Google Docs.

I think this is not what we want ...

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze closed with #2381
