### ISSUE TITLE
Go to motion line number

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2347]
Add new input field with button to motion detail template: "Go to line number ..."
The motion detail template should scroll down to specific line number and highlight the line.

**Optional:**
Add a checkbox 'also for projector' (if user has projector_can_manage permission) to scroll/highlight also to the given line number on projector.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Currently, no line numbers are supported on the projector, are they? So this should be the first step to change the line number mode on the projector.

**Comment by emanuelschuetze** [comment]
You habe to change the config value to show line numbers on projector.
