### ISSUE TITLE
Add new ui element to generate valid json for motion comment field config

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2348]
The motion config "Comment fields for motions" required valid json if user wants to add private fields, e.g. `[{"name": "foo", "public": false},{"name": "bar", "public": true}]`.

This issue should help the user to generate such json string automatically. Suggestion: User just enters comment fields comma separated in the input field. All fields are listed below the input with a checkbox for each field to switch it to private (default: public).

**Comment by emanuelschuetze** [comment]
Wait until #2283 is merged.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze In PR #2283 is one ToDo left: 

> // TODO: Hide non-public fields for unauthorized users.

How do you define an unauthorized user? I saw, you have added a new permission (`motions.can_see_and_manage_comments`). Does the `see` applies to all comments or just the public comments? My current approve is this:
```
if (!operator.hasPerms('motions.can_see_and_manage_comments')) {
    // remove all comments with public == true
    fields = _.filter(fields, function (field) {
        return field.public;
    });
}
```
