### ISSUE TITLE
Projector resolution: Config.get() is undefined

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2349]
Since #2318 I'm getting "Config.get(...) is undefined (/static/js/core/projector.js:70:24)" when working on projector slides.
I think it must be `Config.find(...).then( function() {do something})` in order to work?

(also typo : last-conf.height in line 72 should be last_conf)

**Comment by FinnStutzenstein** [comment]
So sometimes the Config isn't resolved? I didn't get this Error before. I'll test `find.then`.

**Comment by normanjaeckel** [comment]
Config is exposed in loadGlobalData (core/base.js). Also you should use $scope.config(...) instead of Config.get(...).

**Comment by normanjaeckel** [comment]
Ah , I see. The Config.find() in loadGlobalData is not finished when the projector controller tries to access config values. So the solution is not to fire a new loadGlobalData but to wait until the next watch cycle.
