### ISSUE TITLE
Add warning if channel layer is full

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2353]
In default config we use an in-memory channel layer. If this layer is full (autoupdate.py line 125) there should be a warning or a hint on the console so the admin can think about big solutions ...

**Comment by emanuelschuetze** [comment]
workaround: encrease the number of capacity to 10.000 to prevent warning (current default: 1000).

**Comment by ostcar** [comment]
I don't thin, that this is the right way. What we should do is find all places in the code where send() is called and handle the error. For example by trying to send it again 0.1 seconds later. Or log an error message, when it is not possible, even after some time.

A channel full error is an indicator, that the protocol server is not working correctly. If you set the capacity to an high value, there is a bigger chance, that a message is not send with no way to get informed about it.

**Comment by normanjaeckel** [comment]
Hm. We have only one place where the Channel layer can be full. I think I implement a blocking sleep with a warning, ok?

**Comment by ostcar** [comment]
Actually, I currently count 9 places where a channel full can be occur. Look for ```.send(``` in the autoupdate.py
