### ISSUE TITLE
Increase capacity in channel layer config in global data

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2359]
Try something like (proposed by @ostcar):
```
CHANNEL_LAYERS = {
    "default": {
        "CONFIG": {
            "capacity": "1000",
        },
    },
}
```
Find a proper capacity number. 10 (the default) seams too small.

**Comment by emanuelschuetze** [comment]
@ostcar will do this in his next pull request about autoupdate.

**Comment by emanuelschuetze** [comment]
Already done in current master.
