### ISSUE TITLE
Requirements for German law: §§ 118 ff. AktG insb. § 130 AktG

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#236]
In German only (from Norman):

"Prüfung der Anforderungen an eine Verwendung des Systems bei börsennotierten und nichtbörsennotierten Aktiengesellschaften in deren Hauptversammlung. Zu prüfen wäre, welche Anforderungen das AktG sowie typische Gesellschaftssatzungen an den Ablauf (Leitung, Debatte, Stimmabgabe) und die Protokollierung der Hauptversammlung (z. T. notarielle Beurkundung erforderlich) stellt.

Denkbar ist z. B. auch die signierte elektronische Stimmabgabe, wenn die Stimmabgabe ohnehin namentlich erfolgt, was bei Aktiengesellschaften ja oft der Fall ist, da die Abstimmenden unterschiedliche Stimmrechte haben.

Grundsätzlich dürfte die Verwendung des Systems erstmal kaum Probleme bereiten, solange offizielle Antragstellung, Abstimmung und Protokollierung außerhalb des Systems (durch den Notar) erfolgen. Zu prüfen wäre, wie die einzelnen Elemtente rechtssicher integriert werden können."

**Comment by FinnStutzenstein** [comment]
@ostcar @normanjaeckel Is this still up to date?

**Comment by normanjaeckel** [comment]
Of course. OpenSlides for Hauptversammlungen would be very nice.

**Comment by jsaalfeld** [comment]
I would suggest to think about integrating Mailvelope (sounds funny to use a mail plugin, but bare with me). With that addon you can digitally sign texts, messages or data objects with gpg and therefore create a trusted signature which can be used in the process. Would that be sufficient @normanjaeckel ?

**Comment by ostcar** [comment]
I don't think this is an issue for this repository. The task is, to make a recherche, what a Hauptversammlung needs. This is not a coding issue. So I would suggest to close this issue here.
