### ISSUE TITLE
Add line number type hint for motion spans

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2361]
Hi.
There is no way to identify from HTML if line numbers in Motions are ment to display inline or outline. 
In order to provide the full line number functionality in the PDF we need a separation of the line number type provided by html

currently we can only identify that via js using scope.lineNumberMode

I need some further information in HTML. 
currently we have stuff like
<span class="on-line-number" data-line-number="1" (.....) >

To parse between inline and outline I need something like

line-number-type="inline" ("outline")

**Comment by tsiegleauq** [comment]
since line numbers for PDF supposedly got some priority, we may shall solve this issue quickly.
Any suggestions?
@emanuelschuetze
@normanjaeckel 
@CatoTH

**Comment by tsiegleauq** [comment]
we discussed this a little. Right now we can work without further information, but we honestly should consider providing further information later on, after we cleaned up the code and bought PDF generation in pdfmake upstream

**Comment by CatoTH** [comment]
@tsiegleauq We could just modify the markup on the fly in motions/pdf.js before calling convertHTML(). Replacing the line numbers by other tags or adding some data about the line numbering type shouldn't be a big problem.

(Not sure if that is really more elegant, though, as the way line numbers are rendered should be consistent for the whole document and not decided for each node individually.)
