### ISSUE TITLE
Autoupdate is completely broken

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2377]
current Master (last commit ...5075):
```
pip install -r requirements.txt -U
rm -r bower_components/
rm -r node_modules/
npm install
rm -r personal_data/
python manage.py start
```
Login and navigate to participants. Open the sidebar and click on `project Administrator`. The button stays white, the projector isn't updating. You have to reload the page to see the changes. Cache is disabled.

Do am I the only one having this problem? This is a total blocker..

pip freeze:
```
asgiref==0.14.0
autobahn==0.16.0
beautifulsoup4==4.5.1
channels==0.17.2
coverage==4.2
daphne==0.15.0
Django==1.10.1
djangorestframework==3.4.6
flake8==3.0.4
html5lib==0.999999999
isort==4.2.5
jsonfield==1.0.3
jsonschema==2.5.1
mccabe==0.5.2
natsort==5.0.1
Pillow==3.3.1
pycodestyle==2.0.0
pyflakes==1.2.3
PyPDF2==1.26.0
reportlab==3.3.0
roman==2.0.0
six==1.10.0
Twisted==16.4.0
txaio==2.5.1
webencodings==0.5
Whoosh==2.7.4
zope.interface==4.3.2
```

**Comment by normanjaeckel** [comment]
The problem might be that autoupdate is disable in some new migrations files. Try to restart the server. The second run of `python manage.py start` should work.
