### ISSUE TITLE
Save version information in database

### ISSUE THREAD

**Issue by cobii** [OpenSlides/OpenSlides#2378]
If you want to reopen an old database file (database.sqlite) you shuould be able to find some Informations about the used Software.

**Comment by ostcar** [comment]
I think this is partly solved. Django creates a migration tables. In it is the information of the last used migration file. By looking into this table (manually) and into the git history, you could find the openslides version, that was used.

I have no intension to improve this in sqlite. But if we switch no a nosql database, this sounds like a good idea.

**Comment by jsaalfeld** [comment]
I think this will be fixed with #3977

**Comment by ostcar** [comment]
The pr #3977 has nothing to do with this issue

**Comment by tsiegleauq** [comment]
Covered in #4896
The server now has a unique "SchemaVersion"
