### ISSUE TITLE
how to order the candidates on ballot papers?

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2387]
When selecting candidates for an election, currently the order on the printed ballot papers is: Last entered candidate is first on list, first candidate last. On a long list, a voter may be irritated where to find the candidate of preference.

Alternatives would be:
- let the administrator decide on the order
- order by first/ last name

**Comment by emanuelschuetze** [comment]
Sorting of candidates is already done with #2782.
