### ISSUE TITLE
Startup of webclient

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2403]
- Do not use find and findAll except for user detail view. There use also find in resolve and controller (test this).
- User list view: special findAll with pagination. Do this in the controller.
- Forms with user (e.g. supporters): New api view that returns id and name, maybe using whoosh.
- When a autoupdate message comes in, users are loaded via loadRelations.
- On autoupdate connect the server sends all collection elements via websocket (see projector).
- On login and logout we disconnect the websocket connection and all ongoing HTTP requests to /rest and then eject all data from DS and state.go to home. Then reconnect.
- Also send whoami after autoupdate connect and first (mass) message comes in.

**Comment by emanuelschuetze** [comment]
see #2854
