### ISSUE TITLE
error in gulp watch

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2408]
`./node_modules/.bin/gulp watch` does not work on my machine after npm install.

gulp-angular-templatecache@2.0.0 has some error (showing as syntax error here, but I did not dig deeper).
Workaround: `npm install gulp-angular-templatecache@1.9.1`

(see [original issue on gulp-angular-templatecache](https://github.com/miickel/gulp-angular-templatecache/issues/129) )

Discussion needed: Do we *need* 2.0.0 somewhere?

**Comment by normanjaeckel** [comment]
Hm. Please try to use Node 4.x This should work, I think.

**Comment by matakuka** [comment]
With Nodejs 4 it works.
