### ISSUE TITLE
Trigger autoupdate by own save method

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2416]
At the moment we use Django's post_save signal but it would be nice if we only trigger our autoupdate when using our own save method. So we can have customized save calls (with a flag to disable autoupdate) and automaticliy disable autoupdate during migrations.

@ostcar Any comments?

**Comment by ostcar** [comment]
This should be possible. But you have to make sure, that .objects.create() and .objects.update() also call our save method and not the one django provides.

We also need a delete() method.

**Comment by normanjaeckel** [comment]
Ok let's make a list:
* save() should trigger autoupdate by default
* delete() should also do this 
* create() should also do this
* update() does not do this at the moment. Should enable it by default or only by option?

Anything left?

**Comment by ostcar** [comment]
I think that .update() does it at the moment. Django probably calls .save(). But I am not sure.

**Comment by normanjaeckel** [comment]
update() is a manager method that performs an own SQL query to update multiple instances at once. So it does not call save in a loop.

**Comment by normanjaeckel** [comment]
At the moment we have skip_autoupdate for instance save and delete but not for other instance methods and for manager methods. These are missing.

**Comment by jsaalfeld** [comment]
@normanjaeckel @ostcar - Is this still an issue?

**Comment by ostcar** [comment]
Yes. But since there is a easy workaround by manually calling inform_changed_data() and that we already use it, I don't see any need to fix this issue.

When we switch to another database, then his system has to be rewritten. So maybe it will get solved automaticly. I think this issue can be closed
