### ISSUE TITLE
Projector container should not listen on the same channel as real projector.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2417]
At the moment we send mass of data to the projector container but it uses only some small projector and config data. We should not send all other stuff (motions and thelike) to it.

@ostcar How can we do this?

**Comment by ostcar** [comment]
At the moment the projector container uses the loadGlobalData function. This is not necessary, because it is called manually. You could call Config.findAll() in it instead.

**Comment by FinnStutzenstein** [comment]
With multiprojector the resolution does not come from config, but from the projector which is shown in the iframe. So this should be changed to Projector.find(id). The projector container should only get the displayed projector as data and autoupdates for this, if the resolution has changed.

**Comment by normanjaeckel** [comment]
Yeah but what about the autoupdate data? The projector container still connects to ws/projector I think.

**Comment by ostcar** [comment]
Could we save the resolution right now to the projector element and not to the config, so we do not have to change the concept in the future?

**Comment by FinnStutzenstein** [comment]
Can we make the projectorcontainer connect to site and specify in get_requirements the required projector. Technical the projector container isn't a projector. It is some kind of site which shows the projector, so this would make sense?

**Comment by emanuelschuetze** [comment]
As discussed with @normanjaeckel and @FinnStutzenstein 
We need a 3rd channel for projector container which sends the required data (projector, some configs) only. Not really important for 2.1.

**Comment by normanjaeckel** [comment]
This is high for more than three months. Maybe it is not high ... ?

**Comment by jsaalfeld** [comment]
Since the client will be completely rewritten, this shouldn't be an issue anymore. Please reopen if I'm wrong.
