### ISSUE TITLE
Projector sidebar runs over main content

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2420]
Scale a small browser window. At the beginning the projector side bar icon and the bar is on the right side. If you scroll down, the icon and the bar jumps on top of the main content.

![bildschirmfoto vom 2016-09-23 13 00 10](https://cloud.githubusercontent.com/assets/2073844/18783742/da61a838-818d-11e6-9aa7-9115287b3588.png)

**Comment by FinnStutzenstein** [comment]
I cannot reproduce that on chromium. Which browser do you use?

**Comment by normanjaeckel** [comment]
Firefox 48.0
