### ISSUE TITLE
re: Installation Instructions (Virtualenv)

### ISSUE THREAD

**Issue by lesteenman** [OpenSlides/OpenSlides#2431]
What distribution uses the notation of the README.md to set up a virtualenv? Each example I've come across uses `virtualenv [-p python3.4] .virtualenv` rather than `python3 -m venv .virtualenv` that's in the README. The latter notation also does not work for me.

**Comment by lesteenman** [comment]
Suggestion: Either make it clear which version should be used to use that notation, add/replace it with the different notation, or remove the line altogether, simply stating that a virtualenv should be set up first. Wrong instructions are bad instructions, even if they are only wrong in some environments.

**Comment by normanjaeckel** [comment]
The line works for me and it uses the built in venv package instead of the additional `virtualenv` package well known from Python 2 times.

What is your error message? You have to have a `python3` bin that is present e. g. in Ubuntu 14.04 but of course we did not test all other distros.

Proposal. We add the other form/way as hint or remark.

**Comment by emanuelschuetze** [comment]
Since python 3.3 you can use the built-in module 'venv', see https://docs.python.org/dev/library/venv.html#module-venv .

**Comment by lesteenman** [comment]
> Error: Command '['/home/erik/projects/Test/.virtualenv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1

According to http://askubuntu.com/questions/488529/pyvenv-3-4-error-returned-non-zero-exit-status-1, it's one particular version of Ubuntu that shipped with a broken version.

**Comment by normanjaeckel** [comment]
Hm. We do not propose to use `pyvenv` but only `venv`.

**Comment by lesteenman** [comment]
Ok. If this is specific to that one Ubuntu release, I suppose this will be solved automatically in future installs.

**Comment by emanuelschuetze** [comment]
I think we can close this. If you need more information please reopen.
