### ISSUE TITLE
PDF generation fails when using invalid HTML

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2433]
As discussed previously [here](https://github.com/OpenSlides/OpenSlides/pull/2430), PDF generation fails when trying to parse text which is not in a somewhat valid HTML format.
This is due to the usage of this function

`var image_sources = map($(content).find("img"), function(element) {
    return element.getAttribute("src");
});`
`
originally introduced [here](https://github.com/OpenSlides/OpenSlides/pull/2284/commits/546c4e65f64e2e350e5d73cd73c9b902914f4f62).
This function tries desperately to parse the string (content) to a $document object and throws an error if it fails.

**Comment by FinnStutzenstein** [comment]
I stumbled over this when I wrote the docx export: Imported motions could contain öäü,... but if I edited the text, tinyMCE saved this as correct html (with &uuml,...). Whats about to convert every plain text internally to html?

**Comment by tsiegleauq** [comment]
yep. Thats the way to go.
