### ISSUE TITLE
Text with line numbers is not shown in motion pdf

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2441]
How to reproduce this regression:
* Create a new motion with example text.
* Create pdf of this motion (without line numbers) -> Ok.
* Switch to line numbering mode inline or outside.
* Create pdf again (with line numbers) -> PDF contains no motion text! 

I need a fix today!

**Comment by tsiegleauq** [comment]
Does it work if you manually edit the motion and then export?

**Comment by emanuelschuetze** [comment]
No, same result (empty text) for manually created (or edit) motions.

**Comment by tsiegleauq** [comment]
that's odd. I Should be home like 12:15 and then I can work on a fix

Am 27.09.2016 11:32 schrieb "Emanuel Schütze" <notifications@github.com>:

**Comment by emanuelschuetze** [comment]
Thanks!

**Comment by tsiegleauq** [comment]
I looked into this.
I (still?) use the 

`$scope.lineBrokenText`

to get the text with the line breaks. This does not seem to exist anymore. Did any behaviour with $scope.lineBrokenText changed recently?

@CatoTH : did you changed something according to the $scope.lineBrokenText - function?

Any furter information on this?
@emanuelschuetze 
@normanjaeckel

**Comment by tsiegleauq** [comment]
I noticed in the current master there now is the
"linenumbering.js" function.

You obviously missed to pass the new information about line broken text to the pdf-generation the last migration process. Any information about how to get line broken text now?

**Comment by FinnStutzenstein** [comment]
@tsiegleauq [this](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/js/motions/base.js#L184) is the entry point for the linenumbering service if you want to have linenumbers in the motions detail view. (callback can be undefined, highlight should be 0 if not used)

**Comment by tsiegleauq** [comment]
@FinnStutzenstein thanks a lot. Works like a charm!
