### ISSUE TITLE
Cannot import the CSV motion exmaples.

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2447]
I struggle to import the motion examples.

I tried both the "CSV example file" provided by the "import" subpage and the csv provided by the OpenSlides Online Demo.

I am on ArchLinux Stable and use Chromium 53.0.2785.116 (64-bit)
I am on OpenSlides Master.

What I did / steps to reproduce:

- deactivate
- rm -rf personal_data 
- source .virtualenv/bin/activate
- pip install -r requirements.txt
- npm install
- python manage.py start --local-installation
- node_modules/.bin/gulp watch (in other console)
- delete cache
- login with admin admin
- motions/import
- download CSV
- import the same CSV

I provide a big screenshot with the whole JS console output and the terminal output [as pastebin](http://pastebin.com/RsDT2z7K)

![bildschirmfoto von 2016-09-27 14-21-28](https://cloud.githubusercontent.com/assets/10233032/18873158/46aee414-84be-11e6-8d92-3ff57311c773.png)

**Comment by emanuelschuetze** [comment]
@tsiegleauq It should be fixed with new channels version 0.17.3 and #2271 (now only one worker is used. this does not look your sqlite db). Please reopend if not fixed.
