### ISSUE TITLE
Group not set when importing participants

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#2450]
![users](https://cloud.githubusercontent.com/assets/20415092/18918063/dea6a30c-8599-11e6-97a1-142413e3e348.PNG)
When importing the attached list of participants 'groups' are only imported for one of the participants. See attached screen shot.
[os_users.csv.txt](https://github.com/OpenSlides/OpenSlides/files/497402/os_users.csv.txt)

Server reports sqlite3.OperationalError: database is locked.
This seems to be an sqlite3 issue.

**Comment by FinnStutzenstein** [comment]
Does an error appear on the server?

**Comment by FinnStutzenstein** [comment]
@jwinzer This is a known issue: #2198 
Please try to use the `--nothreading` option at startup. If this doesn't work and still 4 workers are started try to fix it with the workaround I described in issue #2442.

**Comment by emanuelschuetze** [comment]
It should be fixed with new channels version 0.17.3 and #2271 (now only one worker is used. This does not lock your sqlite db). Please reopend if not fixed.
