### ISSUE TITLE
Search for participants with the given number

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2454]
If you want to add a participant to a list of speakers or as a candidate for an election, one could search for the name in the select chosen form field. If you have a great number of participants one would like to search not for the name, but for the number because of two reasons:
1. There could be two persons with the same name and
2. searching for a number is shorter.

This is currently not possible.

**Comment by emanuelschuetze** [comment]
Searching for participant number already implemented - number is placed in full name with structure level.
