### ISSUE TITLE
Ballot tabs are all closed.

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2456]
After every autoupdate and action modifying the ballot all taps are closed. Expectation: The last tab is always open automaticly.

This is a screenshot after I clicked on "new ballot":
![taps](https://cloud.githubusercontent.com/assets/8439581/18946453/33b4864e-862f-11e6-8bf1-1ea0e30ad300.jpg)

I just had a quick look in the DOM: the active classes for the tab-content div as well as the li-element are not set correctly. This may be the start point to fix this issue.

**Comment by emanuelschuetze** [comment]
This issue is very annoying. @FinnStutzenstein Maybe you can look at this if you have time.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze with updated dependencies the tabs aren't closed anymore. The page just scrolls up. Please verify.

**Comment by emanuelschuetze** [comment]
Verified. Tabs not closed any more. Only scroll jumbs (see #2555). Closed here.
