### ISSUE TITLE
Feature request: Benchmark for server and client performance

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2459]
This should include simulations of clients with active javascript to receive autoupdates and create requests. Additionally the server should have a huge list of participants (and some topics, motions, elections). The need for it is to test new systems, like trying to run OpenSlides on a RaspberryPi to get some kind of recommendation how much participants could handle the system. Also with a lot of simulated clients (probably >1000) one could test OpenSlides in big mode with a different webserver, database system and caching solution.

**Comment by jsaalfeld** [comment]
There is a benchmark at https://github.com/OpenSlides/openslides-performance - but it can and should be overhauled for the OS3 client and server architecture.

**Comment by thkoch2001** [comment]
I see that the https://github.com/OpenSlides/openslides-performance repo has been archived. What is the best practice to load test an OpenSlides installtion before an event?
