### ISSUE TITLE
Feature request: native voting support

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2460]
Currently OpenSlides is not 100% paperless: For polls ballot papers have to be printed, cut and be handed out. Also this take some time for big assemblies.

There is now support for electronic polls, but only with extra hardware. Not every assembly want to use extra soft- and hardware to make the voting faster.

OpenSlides should give the participants a possibility to vote over their browsers and so OpenSlides should implement a native voting support. Pros:
- Very fast voting
- no extra (expensive) hardware needed
- could directly implemented in OpenSlides, so it is not so error prone like extra hardware.
- But always give the option to print ballot papers if someone have forgot their smartphone or tablet. So a part of the assembly could vote over OpenSlides, and the other part with ballot papers.
- named, non anonymous voting should be easy to implement

Things that make this a little bit complicated:
- Anonymous voting: The participant has to log out, get some kind of random token from a tokenpool and could vote with this token. Then for the token is just saved: the token is used.

And one big improvement for OpenSlides:
Now, only present participants could vote. With this feature distributed assemblies are possible. Not all participants have to be present, but they can vote from their home, if the OpenSlides instance is reachable over the internet.

**Comment by emanuelschuetze** [comment]
We need a concept for a token based anonymous voting (for assignments).

**Comment by emanuelschuetze** [comment]
First draft of a concept:
https://github.com/OpenSlides/OpenSlides/wiki/De%3A-Konzept-Wahlen-in-OpenSlides

**Comment by emanuelschuetze** [comment]
Done! We have a new voting plugin:
https://github.com/OpenSlides/openslides-voting
