### ISSUE TITLE
isProjected should return a list of projector ids 

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2462]
Split out from #2379 for later rework (wait untile #2379 is merged):
The function `isProjected` (in core/base.js and maybe in other apps which override this function) should return a list of all projector ids which project the requested object. This is important for future if OpenSlides UI supports to project an object to multiple projectors.

Example:
The motion 42 is projected on projector 1, 2 and 4. `motion.isProjected()` should return `[1,2,4]`. The projector button consider this list (and show the default button and/or split button blue and select the ul list elements of the projector 1,2 and 4).

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze I will change the `isprojected`-Function. But we have to find a concept of selecting multiple projectors. For now, I think the projectorbutton should only take the first element of the list and have the same behavior like now. So like the former hardcoded `Projector.get(1)`. If this OS is going to support one item one multiple projectors the Projector buttons should be change as a part of this new Feature.
