### ISSUE TITLE
Countdown and Message as model

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2464]
New discussion with @emanuelschuetze: We create new countdown and message models (with access permissions, viewset, serializers, ...) and use the general projector button to control them. Countdowns are not coupled to the projector any more.

( @FinnStutzenstein It is a little bit like it was before in you pull request, but we also want to change the control buttons decouple it from the projector. Maybe some work has to be done twice. Sorry. You can ask @emanuelschuetze about details you you are interested. )

**Comment by emanuelschuetze** [comment]
Note: The projection buttons for countdown and messages should become round corners after using the default button (see #2514).
