### ISSUE TITLE
Support multiple current list of speakers slide

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2466]
The current list of speakers slide should use another approach: We do not want to use the global config but save into the projector config to which projector the slide references. So we later can have multiple current list of speakers slide which reference to different projector.

Then we also can fix the bug in the current behavior (buggy get_requirements() in agenda/projector.py). To fix this, all related slides have use a projector element method update_data() and add the agenda item id to the projector rest api (read-only) result. So the current list of speakers slide can get out this data without looping over all related apps.

**Comment by tsiegleauq** [comment]
> The current list of speakers slide should use another approach: We do not want to use the global config but save into the projector config to which projector the slide references.+

Solved

> Then we also can fix the bug in the current behavior (buggy get_requirements() in agenda/projector.py). To fix this, all related slides have use a projector element method update_data() and add the agenda item id to the projector rest api (read-only) result. So the current list of speakers slide can get out this data without looping over all related apps.

Outdated since this code does not exist anymore. Lost Of Speakers is it's own model now
