### ISSUE TITLE
Multiple deletes should send only one autoupdate

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2469]
send one websocket message (via informed_changed_data) for multiple objects

Example: For votecollector we want to clear all votes of a poll. Currently each delete sends an autoupdate. So the voted seats in seating plan disappear successive. Expected: all voted seats should vanish at once.

**Comment by emanuelschuetze** [comment]
@ostcar @normanjaeckel Is this issue done?

**Comment by ostcar** [comment]
This should be fixt but it is possible, that there needs to be a change in the votecollector. You have to make sure, that inform_changed_data is called ones with a list of objects:

https://github.com/OpenSlides/OpenSlides/blob/master/openslides/utils/autoupdate.py#L139

**Comment by emanuelschuetze** [comment]
Already done.
