### ISSUE TITLE
Minor tasks for multiprojector

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2471]
Some minor tasks splitted out form multiprojector pull requests #2379 

 - [ ] Projector side bar: Use 'check' icon instead of the 'video-camera' icon in the projectorSelector drop down for selected porjector. (video-camera is for 'project' a slide only)
 - [ ] Use spinner icon for loading projector iframe. (Currenly while loading the iframe box is empty. User could think the projector does not work.)
 - [x] Deselect of a projection default should not send a post request.
 - [ ] agenda item list: fix break in projector button dropdown (for subitems and 1 proejctor only)

**Comment by FinnStutzenstein** [comment]
1. OK.
2. This is some kind of an angular/js problem: The page is loaded very quick. The ready event raises simultaneously to the manage pages ready event. But the content is loaded dynamically via autoupdate and js. So currently I have no possibility to get the information, whether the page is ready with all js and angular stuff or not.
(My idea: With a ready information/event, I could hide a spinner icon in front of the projector)
3. Do you mean an autoupdate request? By selecting a projection default just one post request is send on the current master, but I get two autoupdate messages from the same projector (the projector which gets the new projection default).

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Please make a new issue for task 2. Then this issues is finished.
