### ISSUE TITLE
Set Category name field to unique=True

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#2472]
I want to use Category.name as the weight name for weighted voting. Therefore the name should be unique.

**Comment by normanjaeckel** [comment]
Ok.

**Comment by normanjaeckel** [comment]
For migrations we have to trim the name up to 200 chars and then add unique numbers for identic names.

**Comment by jsaalfeld** [comment]
Is this issue still relevant?

**Comment by p-murli** [comment]
Hey, I'm a beginner and I'd like to take up this issue if it is still open. Could you guide me on how I should get started?

**Comment by emanuelschuetze** [comment]
Currently, a unique field is not required for category name or prefix. Initially the category name should be used for voting plugin which uses now an extra field). So let us focus on important and required issues for 3.0 only and move this to 3.1.

**Comment by jsaalfeld** [comment]
First of all: Thank you @p-murli for wanting to take care of this issue.

If you want to participate generally in this project, you can see the old client over at https://demo.openslides.org/ and get a bit familiar with it.

A second step would be to build the system on your own. To do that, you have to clone the repository and get a [virtual environment ready ](https://github.com/OpenSlides/OpenSlides/blob/master/README.rst#b-setup-a-virtual-python-environment-optional) for the server backend:

    python3 -m venv .virtualenv
    source .virtualenv/bin/activate
    pip install --upgrade setuptools pip

Then you can [configure the backend](https://github.com/OpenSlides/OpenSlides/blob/master/DEVELOPMENT.rst#d-finish-the-server):

    pip install --requirement requirements.txt
    python manage.py createsettings
    python manage.py migrate

And finally run the server:

        python manage.py runserver

But without a nice frontend, it would be rather useles, wouldn't it? ;)
So, we need to enter the client directory with a second console and [manage our npm stuff](https://github.com/OpenSlides/OpenSlides/blob/master/client/README.md):

    cd client
    npm install

and than, finally run the frontend as well:

    npm start

now you can reach the client at localhost:4200 and click around in it. You see, the files outside the `client` folder from the root folder are for the backend and the files inside the `client` folder are for the frontend. Both need to run simultaneously.

Now you can get to the issue itself and search a bit around in the python code to see  the `category` implementation and understand how that works. Best is to look into #2497 as well and see what changed. Any changes you save in the python backend code or the typescript frontend code will result in a refresh of the server and the changes take effect immediately. With that you will find pretty fast the root the issue! As soon as you found it, you can make a PullRequest from your forked repostory. It will be reviewed and eventually merged!

**Comment by jsaalfeld** [comment]
If you are more into the frontend-related stuff, you can take a look at #3980 and get yourself a look at the angular7 application, that is powering the frontend.

**Comment by tsiegleauq** [comment]
> I want to use Category.name as the weight name for weighted voting

By now, category has a weight value to allow sorting. So the original cause of this issue was addressed

**Comment by tsiegleauq** [comment]
@FinnStutzenstein might be relevant for "current development?" If so, might consider it for 3.2 I'll set it to TODO for now.

**Comment by FinnStutzenstein** [comment]
No I think it is not relevant. The original reason was to do couple this with the voting plugin, which will not exist for OS3. Also I do not want to introduce an artifical usecase-blocker: If someone wants to have duplicate category names, they should do it.
