### ISSUE TITLE
Discussion: Remove show as agenda item and agenda parent on edit forms

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2486]
These two options can lead to huge confusion: If you have a child item of a hidden agenda item and you click edit, the form provides an option to you that is out of use for this moment. We should say that managing the existing agenda (hidden or non hidden and also the structure) should be done in the agenda tab only. We should use the extra form fields only for create forms.

**Comment by emanuelschuetze** [comment]
already fixed.
