### ISSUE TITLE
PDF generation fails if no submitter is set

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2487]
In the latest version it happens sometimes that no submitter is set for a motion.
If there is no submitter, the PDF generation fails with the error:

`angular.js:13920 Error: "id" must be a string or a number!`

**Comment by emanuelschuetze** [comment]
Please try to reproduce it. Try to fix it or otherwise close it.

**Comment by tsiegleauq** [comment]
cannot reproduce anymore. Even if I manipulate the motion and remove the submitter, pdf generation always works now. No fix needed here.

**Comment by donovaly** [comment]
> cannot reproduce anymore.

So fixed in 2.1 as well -> milestone can be changed from 2.2 to 2.1.
