### ISSUE TITLE
Remove chat history

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2502]
Add a possibility to remove all chat messages (on server) to clean chat history in the chatbox.

**Comment by normanjaeckel** [comment]
Suggestion: @emanuelschuetze or somewhere else makes a commit with a button and a bootbox dialog. I can add a view point and fit them together in a second commit.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze @normanjaeckel Where should this button be placed in the ui? Somewhere in the chat or in the settings?

**Comment by emanuelschuetze** [comment]
I prefer the chat window because we have not an explicit chat config section.

Maybe we can provide this button only for manager? But that means we need a new permission, e.g. "core.can_manage_chat"?

Otherwise each normal user (who is allowed to use the chat) can clear all messages on server - for all users. Could be a bit dangerous operation...

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze or use the permission can_manage_config? But if sometimes the chat gets more functions, a manage chat permission could be helpful.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Done with #2516.
