### ISSUE TITLE
Project agenda button has wrong dropdown menu

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2517]
The projector button for agenda has no option any more to project main items only or all sub items... And if you have only one projector you get the default projector in the drop down list.
Maybe it's lost while a merge conflict?

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze If there are no subitems, this option is hidden from the user.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Yes. But if you have only one projector and no subitems the drop down menu should NOT displayed for agenda project button.
