### ISSUE TITLE
Entering votes for Assignments is extremly hard to use

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2520]
I would consider the following function nearly unusable.

![bildschirmfoto von 2016-10-19 10-32-46](https://cloud.githubusercontent.com/assets/10233032/19511441/83139f8c-95e7-11e6-920e-04694116122a.png)
- Scrolling with the browser bar does not work on chrome and ff
- Scrolling with the mouse wheel does not work on Firefox (v 49.0.1-1 on Arch Linux)
- In Chrome, you can only scroll if the mouse is floating over the Entering area
- when clicked in a flied and using the mouse wheel, you will change the entries.
- Also: are all these options really necessary? Maybe you can find a better way to preent the data

I quick-hacked a template in GIMP that would probably bring some improvements:

![openslidesuiimprove](https://cloud.githubusercontent.com/assets/10233032/19512541/bf2c2da4-95ec-11e6-9831-d13b955ce3fc.png)

**Comment by emanuelschuetze** [comment]
Done in 2.3
