### ISSUE TITLE
different approach for iframes

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2521]
The problem is described in #2471. I was thinking about using ng-include to just include the projector (as a div; this div could be scaled like the iframe now, too). For the `/projector/1` url (projector container) this is working; the container calls the ´/webclient/projector/` so the projector has its own realm and gets autoupdates. But how to handle this in the sidebar or manageview?

Because the projector gets included in the webpage, the page is the site and projector at the same time. This is not the way OpenSlides is current going with the strict separation between the site and projector; There have to be many changes to implement this in an useful way but I think it's possible.

I could create an PR with my experiments for using the projector in a div if someone wants to try this out.

Other idea: Render the projector on serverside and just updating a picture with the projector content and broadcast it with the autoupdate when the projector changes. I think this is some kind of over complicated and the server has a lot to do; whats about videos? Not my favorite. 

Any Ideas, discussion?

**Comment by emanuelschuetze** [comment]
As discussed with @FinnStutzenstein and @normanjaeckel 
won't fix
