### ISSUE TITLE
'--local-installation' requires 'openslides start'

### ISSUE THREAD

**Issue by toothstone** [OpenSlides/OpenSlides#2532]
The readme says to use `openslides --local-installation`, which fails for me:
>  (openslides)[root@vm ~/openslides] openslides --local-installation 
Traceback (most recent call last):
  File "/usr/local/bin/openslides", line 9, in <module>
    load_entry_point('openslides==2.0', 'console_scripts', 'openslides')()
  File "/usr/local/lib/python3.4/dist-packages/openslides/__main__.py", line 41, in main
    known_args.callback(known_args)
AttributeError: 'Namespace' object has no attribute 'callback'

If I run `openslides start --local-installation`, it works as expected.

**Comment by emanuelschuetze** [comment]
@toothstone Many thanks for your report! It is fixed in master now. (BTW: We will release 2.1-beta1 in the next weeks)
