### ISSUE TITLE
New group permission matrix requires double-clicking

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2541]
The new user group policy feature of OS is great!

There is nevertheless a bug: Whenever you want to add a setting and therefore click in a checkbox nothing happens. One needs to click on the same box again. The same happens upon unchecking - you have to click twice.

If this behavior is desired, it should be described in the title line.

**Comment by FinnStutzenstein** [comment]
@donovaly This was not desired; if you (un)check a permission, you need to double (un)check it. If you (un)check another permission, do you need to double click also at the second, third, ... time?

**Comment by FinnStutzenstein** [comment]
OK, you have always to double click.

But: with the first click the permissions are updated correctly. You can see this in the rest API, or just reload the page. Than the checkbox displays the correct status. So this is some kind of an autoupdate problem I think on js site.

**Comment by donovaly** [comment]
> So this is some kind of an autoupdate problem I think on js site.

What should I do? Document that a double click is required or is there any chance that this will be fixed?

**Comment by FinnStutzenstein** [comment]
@donovaly I hope this will be fixed.. I used to work some time ago..

It is not a js problem: I created a new group (no permissions) and clicked on can_see_projector. On the first click _one_ request is send to the server with this payload:
```
{id: 5, name: "test", permissions: ["core.can_see_projector"], hover: false}
```
And get as response:
```
{"id":5,"name":"test","permissions":[]}
```
But in the rest API I can see that the permission is set. 

The second click just creates another request to set the permission (the client does not know that the permission is already set; payload is the same) and now the response contains the new permission.

Someone with good knowledge of the new cache and autoupdate system may have a look on server site whats going wrong there..

**Comment by normanjaeckel** [comment]
@ostcar Any idea for this cache problem?

**Comment by emanuelschuetze** [comment]
This problem was introduces with caching commit 368873e7385ac86e0de1833de0ad32023489506f (maybe it is a similar problem as #2597?)

**Comment by donovaly** [comment]
Many thanks. Works fine.
