### ISSUE TITLE
OS 2.1: translation bug in user group policy feature

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2542]
After starting OS 2.1dev I see in the group policy page an untranslated group name named "Previous group Registered":
![group-policy-translation-bug](https://cloud.githubusercontent.com/assets/1828501/19838760/4b5080b8-9ed6-11e6-9606-7758ca1b1128.png)

Besides that the name is in English, it is quite senseless.
Background info: I imported an existing OS 2.0 database to OS 2.1 as Emanuel told me. So maybe this user group is a bug in the database import.

**Comment by normanjaeckel** [comment]
This group only appears if one migrate an OpenSlides 2.0 database to 2.1. You can rename or remove the group, if you are sure that the permissions for your users are set correctly. We have to describe this in README or in docs.

**Comment by donovaly** [comment]
OK, I will describe it, Please leave this bug open until this is done.

**Comment by donovaly** [comment]
Done now.
