### ISSUE TITLE
OS 2.1: some user groups cannot be deleted

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2543]
OS 2.1s new group policy feature one cannot delete a group. When the mouse pointer is over a group name OS offers to edit or delete the group. I have there a group named "Previous group Registered" (see also issue #2542). When I click on the thrash bin icon to delete the group I get a confirmation dialog. i pres there OK but then nothing happens. The group still exists.

If a group cannot be deleted, OS should not offer to delete it.

**Comment by normanjaeckel** [comment]
Bug in GroupViewSet destroy(). Only the default group should be protected.
