### ISSUE TITLE
Don't allow to delete user groups "staff" and "delegates"

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2544]
OS 2.1s new group policy allows to delete every user group. OS offers predefined groups like "delegates". In my opinion it is not a good feature that one can delete these groups. The purpose of OS is to provide a tool for conventions and there will always be delegates and a "staff".

So in my opinion these groups should not be deleteable.

But maybe there are good reasons to allow this?

**Comment by FinnStutzenstein** [comment]
@donovaly the reason to allow this was to keep OS as customize able as possible. If a group of people use this, but not for an assembly they might have totally different need for different groups.

It could be changed if someone has other arguments

**Comment by donovaly** [comment]
> If a group of people use this, but not for an assembly they might have totally different need for different groups.

OK, if there are good reasons. I just wanted to assure that this is not a bug.

**Comment by normanjaeckel** [comment]
There is still a bug here: If you delete staff group before you add the users manager perms to another group, you can lockout yourself and it is not possible to reset admin via command line.
