### ISSUE TITLE
OS 2.1: missing default user groups

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2545]
In OS 2.0 all unregistered users were put into the user group "guests" automatically, all registered were put to the group "registered".

This is no longer the case. I am sure there is a reason but I cannot find a way to put new users to a certain group. This was a very valuable feature because e.e.g a journalist should be able to participate as guest and should NOT nave all permissions of the group "standard" automatically.

Probably I just did not yet understand the new concept. Since I need to document it please give me this info if this bug report is invalid.

**Comment by normanjaeckel** [comment]
Yes we changed the concept. All users without any group gain the permissions of the default group. Also all guests gain these permissions. If you want your guest to see less stuff then several registered users you have to create a new group for your special registered users and put them in. Then setup the permissions (less for default and more for your new group).

**Comment by donovaly** [comment]
> If you want your guest to see less stuff then several registered users you have to create a new group for your special registered users and put them in.

OK, but I did not yet understand why a working feature was removed. I mean why can OS not offer a group called "guest" with sensible permission settings anymore? Now one has to invest some time to decide what permissions are sensible for guests.

**Comment by normanjaeckel** [comment]
Many people did not understand the differenc between anonymous guests and registers users. So we decided to provide only one default group for all who do not gain any special permissions. The old behaviour is still possible if one creates and uses respective groups.

**Comment by donovaly** [comment]
OK, is now documented.
