### ISSUE TITLE
OS 2.1: translation bug in motions settings

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2546]
- use English menus in OS 2.1 dev
- go to the motion settings

result: all field contents are in German instead of English:

![motion-settingstranslation-bug](https://cloud.githubusercontent.com/assets/1828501/19839320/e95ed13e-9edf-11e6-93bc-9a4fec17527e.png)

**Comment by emanuelschuetze** [comment]
I can't reproduce it with current master. Please retest it with your next test version. And maybe clear your browser cache.

**Comment by donovaly** [comment]
Confirmed fixed.
