### ISSUE TITLE
OS 2.1: missing feature to project motion text change proposals

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2548]
The new feature of changing motion text is very awesome! Many thanks for this, this is what I was personally looking for.

Allow me nevertheless a bug report:

Currently I can visualize a change proposed by a participant of the conventions:

![localhost 8000 2016-10-30 21-10-37](https://cloud.githubusercontent.com/assets/1828501/19839613/5f72d35c-9ee5-11e6-8e9e-d3a9d1119df8.jpg)

What is now only missing are these 2 things:
- I cannot find a way to project the view of the above screenshot. But this is what people like to see before they vote for or against a change.
- It is already perfect that there are the thumbs up/down icon behind a change. When pressing e.g. thumbs up because the participants voted for the change, I cannot display the result. I mean I click on "Resolution" but in the projector still the unchanged motion text is shown. During a convention we often have the case that people want to see the final text before the next topic is called.

**Comment by donovaly** [comment]
Could anybody please tell me how to get this feature? I once discovered and were so amazed. But now I don't know how to get this feature.

**Comment by emanuelschuetze** [comment]
This is still a missing feature to project each view of motion. Currently only original view can be projected.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Closed with PR #2796 .

**Comment by donovaly** [comment]
Many thanks, however, the line numbering does not yet work correctly, see bug #3027.
