### ISSUE TITLE
Motion text display bug

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2549]
OS  makes a mistake in projection motion texts: The gray box with the motion status is drawn too deep so that the motion text lines are broken. This also breaks the great new line numbering feature:

![localhost 8000 2016-10-30 21-23-31](https://cloud.githubusercontent.com/assets/1828501/19839715/3eeccc12-9ee7-11e6-8e73-c92bd0271c09.png)

**Comment by donovaly** [comment]
I have to correct myself: The gray box is not drawn to deep. The box will later grown when the election results are displayed:

![localhost 8000 2016-11-08 23-53-26](https://cloud.githubusercontent.com/assets/1828501/20120806/9b533850-a60e-11e6-92e0-068ea4adc313.jpg)

The bug is probably that OS allows more than 70 characters per line but the the gray box limits the characters per line to 70 (71 if I counted correctly). It the space between the line number and the text is slightly reduced one could use 72 chars ber line. This is a sensible maximum limit. All the typographic advices I know say that one should not use more than 70 characters per line to keep the readability.

**Comment by emanuelschuetze** [comment]
I think about this issue and I think this is not a bug because you can solve it:
* by changing the line length in motion settings (default 80 chars)
* by changing the projector resolution to get more space for full motion lines (default 1024x768).

So "wan't fix" for changing the default line length.

**Comment by donovaly** [comment]
@emanuelschuetze you misunderstood me. The proper bugfix would be to set the default character number per line to 70. Currently the default is 80. I also explained why 80 chars is no good default value in terms of readability.

**Comment by emanuelschuetze** [comment]
I think we can move this to 2.2.

**Comment by donovaly** [comment]
> Can you test it please?

Yes, but I need a new version of OS 2.2 beta to do this.
