### ISSUE TITLE
OS 2.1: Line numbering style change is not respected

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2551]
- In OS 2.1dev go to the motion settings and set the line numbering to "außerhalb".
- create a new motion, and display it

result: the line numbers are correctly displayed
- now change in the motion the numbering to "off" or "innerhalb"

result: the projector still displays the old numbering while inside OS the numbering is correct

**Comment by emanuelschuetze** [comment]
This is not a bug. The line numbering mode in motion detail view is for this site only - not for projector. The line numbering mode on projector can changed only in settings > motions > Default line numbering.

**Comment by donovaly** [comment]
Is now documented.
