### ISSUE TITLE
OS 2.1: non-public data shown after logging out

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2552]
- log in as admin and open the page with the participants

You see now a list with all users. This is list is a non-public list. For example you don't want that a journalist gets it.
- log out

result: OS still shows the list:

![localhost 8000 2016-10-30 22-31-10](https://cloud.githubusercontent.com/assets/1828501/19840184/211bc792-9ef1-11e6-9bd3-09987e2c2959.png)

Some content is cleared but the perfect solution would be to clean everything when logging out.

**Comment by FinnStutzenstein** [comment]
@donovaly @emanuelschuetze this only works, if guests are enabled. But this list is public per default (look in the permissions). But not everything is shown, so this is OK.

**Comment by donovaly** [comment]
> But this list is public per default (look in the permissions).

I see now, thanks.

> But not everything is shown, so this is OK.

I agree -> Closing this bug.
