### ISSUE TITLE
OS 2.1: wrong language in PDF of elections

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2553]
- assure that you use German menu language
- in the election settings under "Titel für PDF-Dokument (alle Wahlen)" see that there is by default the content "Wahlen" (don't change anything there!)
- now go to the elections menu and press the PDF button

result: the PDF has the title "Elections"

OS only shows the desired title if you explicitly set one. The default title is never used.

**Comment by donovaly** [comment]
The same bug appears for the creation of the motion list. The preset in the settings is the title "Anträge" but one gets in the created list "Motions".

**Comment by emanuelschuetze** [comment]
Already fixed in current master.

**Comment by donovaly** [comment]
Confirmed fixed.
