### ISSUE TITLE
Election results are mangled

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2554]
- create a new election where e.g. 3 persons can be elected
- put 4 persons on the candidate list
- now start the vote, and therefore press the enter vote button

Here is a screenshot of such an election:

![ballot-bug](https://cloud.githubusercontent.com/assets/1828501/19840645/0a73a276-9efb-11e6-9d71-3c38137fcf9c.png)

so there are 3 bugs:
1. OS allows negative votes
2. OS does not check the vote numbers. In the example there are 35 valid votes, but only 34 are used for the 4 candidates. In real life such mistakes occur often so OS should help here and e.g. highlight the field "valid ballots" if the sum of the above fields does not match it. It should also highlight the field "casted ballots" if the valid plus the invalid votes does not match its number.
3. After saving OS tells me that there are 35 invalid votes (also if I use "0" instead of "-1":

![ballot-bug2](https://cloud.githubusercontent.com/assets/1828501/19840665/748d0706-9efb-11e6-8f2e-307b081381dd.png)

At least problem 3 must be fixed for the final 2.1 release.

**Comment by donovaly** [comment]
Concerning problem 3, the PDF one can generate after the vote is correct. It is incorrect inside OS and also in the projector while the projector view is different from the one inside OS.

**Comment by emanuelschuetze** [comment]
I think we should rework the election voting result dialog for 2.2 - then with a new feature for plausibility tests.

**Comment by donovaly** [comment]
Invalid: "-1" stands for majority. Thus the bug report was incorrect.
