### ISSUE TITLE
OS 2.1: regression: PDF of motions is no longer created

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2556]
- go to the motions menu of OS
- press there the button "Export all"

result: clicking on PDF or CSV does nothing, only clicking on DOCX generates the desired file with the overview about all motions.

**Comment by emanuelschuetze** [comment]
@donovaly Please open the JavaScript console in your browser (F12 in Firefox/Chrome) and then reload the page and click again on pdf export. Do you see any JavaScript errors?

**Comment by emanuelschuetze** [comment]
I think on of your (old) motions has some html markup which failes while converting into pdf. Try to export only a filtered plain text motion.

**Comment by donovaly** [comment]
Hmm, Hmm, strange today I cannot reproduce the bug anymore. I get now a PDF and a CSV.
Closing.

**Comment by donovaly** [comment]
This bug is not fixed in current master. Here is my database:

[db.zip](https://github.com/OpenSlides/OpenSlides/files/601465/db.zip)

Use it, start the server, go to motions and try to get a PDF of the motion list. Result: nothing happens.
This must be fixed for OS 2.1.

**Comment by emanuelschuetze** [comment]
We fixed a lot of pdf creation errors in master. So please retest and reopen if something is still wrong.

**Comment by donovaly** [comment]
> please retest

Done, the PDF is now correctly created.
