### ISSUE TITLE
OS 2.1: ballot setting without any action

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2563]
The field "Default comment on the ballot paper " in the election setup should be removed. It is not used, neither in the projector nor the ballot paper.

**Comment by normanjaeckel** [comment]
Hm. If yoiu add a new election you can set a default comment for ballot papers. This string is used if a new ballot is created. But you can not change the comment string for a single poll.

**Comment by donovaly** [comment]
Yes, I can set a comment, but it won't appear anywhere.

**Comment by normanjaeckel** [comment]
Add new election with a comment. Add candidate and create ballot. Now click ballot paper. The comment is in the subtitle of the ballot paper.

**Comment by donovaly** [comment]
Aha, thanks. I'll update the docs.

**Comment by emanuelschuetze** [comment]
I think this is done. Otherwise please create

**Comment by donovaly** [comment]
Now it's done.
