### ISSUE TITLE
wrong English translations for participant names

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2564]
- use OS 2 with English menus
- create a new participant

result: OS uses the terms "First name" and "Last name". These terms are incorrect English.

Instead of "First name" one should use "Given name". This is also used in the passports and therefore more or less the standard term.
Instead of "Last name" one must use "Surname". This is also used in the passports and therefore more or less the standard term.
(see also https://en.wikipedia.org/wiki/Surname)

**Comment by emanuelschuetze** [comment]
I can't see in dictionaries that first/last name is not correct:
https://www.dict.cc/?s=vorname
http://www.linguee.de/deutsch-englisch/search?source=auto&query=vorname
http://dict.leo.org/ende/index_en.html#/search=vorname&searchLoc=0&resultOrder=basic&multiwordShowSingle=on&pos=0

So I am not convinced. @normanjaeckel What do you mean?

**Comment by normanjaeckel** [comment]
If given name and surname is more common in official documents and stuff like this we may change to this wording.

**Comment by emanuelschuetze** [comment]
Ok, I'll do this...
