### ISSUE TITLE
OS 2.1: wrong text in sorting of categories

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2565]
With German menus the text is currently this one:

![localhost 8000 2016-11-01 19-10-03](https://cloud.githubusercontent.com/assets/1828501/19901325/06089e4a-a067-11e6-95dd-d3a6100fa679.jpg)

The first sentence is Ok but the second sentence misses the subject. I propose this

"Klicken Sie anschließend auf den Knopf um neu zu nummerieren.
or
"Klicken Sie anschließend auf den Knopf um die Bezeichner neu zu nummerieren.

The English translation of these sentences must be adapted as well.

**Comment by emanuelschuetze** [comment]
Changed English string to: "Drag and drop motions to reorder the category. Then click the button to renumber."

**Comment by emanuelschuetze** [comment]
Done in current master.
