### ISSUE TITLE
OS 2.1: motion blocks cannot be edited in the agenda

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2566]
- create a motion block and put in on the agenda
- in the agenda list click below the block name on _Edit_

result: this is impossible, only the _QuickEdit_ works

**Comment by emanuelschuetze** [comment]
confirmed.
Additional, clicking on the motion block name (in agenda) should open the motion block detail view.

**Comment by FinnStutzenstein** [comment]
I get `Error: Could not resolve 'motions.motion-block.detail.update'`.
It should be `motions.motionBlock.detail.update`.

**Comment by FinnStutzenstein** [comment]
The PR #2622 is just a Hotfix for this Problem. The main reason this fails is described in Issue #2480 .

**Comment by emanuelschuetze** [comment]
Already fixed in current master. @donovaly Please retest.

**Comment by donovaly** [comment]
Confirmed fixed.
