### ISSUE TITLE
Refactor motion save method

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2571]
Splitted out from [#2535 comment](https://github.com/OpenSlides/OpenSlides/pull/2535#discussion_r85429193):

Find a way to refactor the motion save method that we can prevent such commands to get title/text/reason (from last version) when we want to save e.g. the state only:
```
  motion.title = motion.getTitle(-1);
  motion.text = motion.getText(-1);
  motion.reason = motion.getReason(-1);
```
Norman: "either we refactor the REST API at this point or you add a new viewpoint like set_state."

**Comment by jsaalfeld** [comment]
Since the client is completely rewritten, this shouldn't be an issue anymore. Please reopen if I'm wrong.
