### ISSUE TITLE
OS 2.1: display bug with name of amendment motion identifiers

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2573]
- in the motion settings enable amendment motions and set the prefix "-Ä"
- open a motion and create a new amendment motion

result: in the general motion list the amendment motion is displayed like this:

![localhost 8000 2016-11-02 00-58-52](https://cloud.githubusercontent.com/assets/1828501/19912060/19b75798-a098-11e6-9f6d-cbd8897d4800.png)

so the prefix is not visible

**Comment by FinnStutzenstein** [comment]
@donovaly If the identifier is too long it now breaks in line. Is this OK?
![motion_identifier_col](https://cloud.githubusercontent.com/assets/8439581/19999466/d70a00c6-a272-11e6-87e5-553fcae0ab2a.jpg)

**Comment by donovaly** [comment]
> Is this OK?

That would be the solution. Many thanks.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze I'll create a PR.
