### ISSUE TITLE
OS 2.1: typo in voting result checkbox

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2574]
See the screenshot:

![virtel-typo](https://cloud.githubusercontent.com/assets/1828501/19912274/82361b64-a099-11e6-9719-13659a89e92c.jpg)

It should read "Dreiviertelmehrheit"

**Comment by emanuelschuetze** [comment]
Already fixed in master

**Comment by donovaly** [comment]
> Already fixed in master

Not for me. Now I don't get German text in the combobox, only English text (while all other strings are correctly in German).

**Comment by emanuelschuetze** [comment]
Have you tested (and Installer) the current master (from today)? My last portable Version for you does NOT contain this fix.

**Comment by donovaly** [comment]
> Have you tested (and Installer) the current master (from today)?

Yes, I pulled from Git the latest master. Then i created a new folder where I put in all the files from the 2.1 dev version your sent me and finally put in the files from master.

I see now that in your version there is a folder named "openslides/static/tinymce" I cannot find anything about tinymce on master. Where is it?
I cannot find the whole folder "openslides/static" including its subfolders with i18n files in master.

I guess I should learn how to build a portable Win build by myself. if you could call me and explain me that would be nice. I fear that i would otherwise only pollute the bugtracker with issues that are already fixed.
Having an up to date version would be helpful because I see in the commits that e.g. some PDF generation issues have been fixed recently.

**Comment by FinnStutzenstein** [comment]
I checked this: First I have the same typo. But I did a `pip -U -r requirements.txt` and `npm install` and now I have the updated translation without the typo.

**Comment by donovaly** [comment]
> I did a pip -U -r requirements.txt

pip does not have the option "-U" and "-r" on my machine. I have Python 3.5.2 installed. Do I need a special Python version?

**Comment by FinnStutzenstein** [comment]
Sorry I mean pip _install_ -U -r requirements.txt

**Comment by donovaly** [comment]
> I mean pip install -U -r requirements.txt

Many thanks, that works. But I get this error:

```
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;
__file__='c:\\users\\muso\\appdata\\local\\temp\\pip-build-odnerq\\twisted\\setup.py';
f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');
f.close();
exec(compile(code, __file__, 'exec'))" install --record c:\users\muso\appdata
\local\temp\pip-y_rpm0-record\install-record.txt --single-version-externally-man
aged --compile" failed with error code 1 in c:\users\muso\appdata\local\temp\pip
-build-odnerq\twisted\
```

(I had to downgrade to python 2.7 because some programs are still not ready for Python 3.x). If Python 3 is required that should be pointed out.

I also get the error: 'error: Microsoft Visual C++ 9.0 is required.' But I have MSVC++ 14 installed and use it everyday. MSVC 9 is from 2008 and it is strange that this is still required.

**Comment by FinnStutzenstein** [comment]
Oh sorry, I didn't know that you are using Windows. I just can speak for OpenSlides on Linux, so there is no c++ MS dependency, but python 2.7 works fine (on my machine no python 3.x is installed).
@emanuelschuetze may have some experience with OS on Windows.

**Comment by emanuelschuetze** [comment]
@donovaly Can you verify my translation fix with your last portable version?

**Comment by donovaly** [comment]
> Can you verify my translation fix with your last portable version?

Yes, but note that the combobox is now only displayed after inserting the results, see issue #2613.
