### ISSUE TITLE
OS 2.1: PDF generation fails for motions with formatted text and line numbering

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2576]
- create a new motion
- open the motion and click on the PDF button

result: everything works fine

- now highlight some text of the motion and make its background e.g. red (you can use inline editing or the normal editing)

result: now one does no longer get a PDF when clicking the PDF button

**Comment by tsiegleauq** [comment]
Can not reprocude. I get a PDF with red background in the current master.

However, there is some invalid HTML after inline-editing the Motion. But the PDF does render anyway.
[Antrag-3 (2).pdf](https://github.com/OpenSlides/OpenSlides/files/566788/Antrag-3.2.pdf)

**Comment by donovaly** [comment]
Aha, the bug only appears, if
- one uses text color or background color, strike through or underlining

AND
- line numbering

Without line numbering, it always works.

**Comment by emanuelschuetze** [comment]
@tsiegleauq Still open in current master:
* create a motion with some text
* set for the first word a background color 'red'
* create motion pdf _without_ line numbers
=> Failure 1: the full paragraph is filled with background color!

* create motion pdf with _inline_ numbering
=> Failure 2: PDF creation fails with `TypeError: Cannot read property 'toString' of null`

* create motion pdf with _outline_ numbering
=> Failure 3: PDF creation fails with `angular.js:13920 TypeError: Cannot read property 'length' of null`

**Comment by donovaly** [comment]
Confirmed fixed, but I found #3048.
