### ISSUE TITLE
assignment_related_users.user is not defined in assignment list

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2581]
If you parse thrgough the (filtered) Assignments in the assignmentList, the user is not defined in

`Assignmentsassignment.assignment_related_users.user`

![bildschirmfoto von 2016-11-02 17-26-08](https://cloud.githubusercontent.com/assets/10233032/19937602/30f71bc0-a122-11e6-99c7-3dda587bb8cd.png)

this is not the case if you really are _in_ an assignment.

I filter the assignments using:

```
angular.forEach($scope.assignmentsFiltered, function(assignment) {
    console.log(assignment);
});
```

This makes it impossible to render the assignment catalog over PdfMake.
If this is a bug, this can be labeled as **blocker**

**Comment by emanuelschuetze** [comment]
already done in #2610
