### ISSUE TITLE
OS 2.1: creating PDF ballot paper for motions does not work

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2583]
- create a new motion
- start a vote on it

One gets now:
![localhost 8000 2016-11-02 22-52-14](https://cloud.githubusercontent.com/assets/1828501/19948851/0acce9a2-a14f-11e6-9bfd-ec3e86cad0bb.jpg)

- click on the PDF button

result: nothing happens. This bug is independent of line numbering

**Comment by emanuelschuetze** [comment]
I can't reproduce it with current master - it works fine for me in Chrome and Firefox. So please retest it later with new 2.1-beta1 (which we release hopeful in the next week).

**Comment by donovaly** [comment]
> please retest it

Done, I can confirm that this is fixes with today's master
