### ISSUE TITLE
OS 2.1: exporting the motion list to CSV is broken

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2584]
- create a new motion
- in the reason text of the motion set a background color for a word
- go to the main motion list and choose to export everything as CSV

result: the exported file ends with the background color. For example I get only this:

`identifier,title,text,reason,submitter,category,origin"K 1","Titel 2","<p>Text 25kl</p>","<p><span style="background-color: `

This bug is independent of line numbering and only the CSV export is affected. PDF and DOCX work correct.

**Comment by donovaly** [comment]
The bug also occurs of the motion text or the reasoning text contains a weblink.

**Comment by FinnStutzenstein** [comment]
@donovaly Could not be recreated:

Creating one motion with text color, strike through, background color. Export as CSV:
```
identifier,title,text,reason,submitter,category,origin
"1","test","<p>Die <span style="color: #99cc00;">Versammlung</span> <span style="text-decoration: line-through;">m&ouml;ge</span> beschlie&szlig;en,</p>","<p>Die <span style="background-color: #ff0000;">Begr&uuml;ndung</span> folgt.</p>","Administrator","",""
```
Delete the motion, import the CSV. Everything is ok; the CSV is parsed correctly and the formatted text is correctly shown.

Also format just one word in the reason with a background color does not break the export and import.

**Comment by donovaly** [comment]
> Could not be recreated:

With today's master I still get the bug. The new created motion is the first in the motion list and I used the button "Export all" above the list of all motions.

**Comment by FinnStutzenstein** [comment]
Could you test this with the current master?

**Comment by donovaly** [comment]
> Could you test this with the current master?

The bug is still present.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze can you test this?

**Comment by donovaly** [comment]
The bug is still present with current master.

**Comment by emanuelschuetze** [comment]
Successfully tested with current master. Can't reproduce it. So fixed.
@donovaly Please retest it with next testversion and reopen if it something is still wrong.

**Comment by donovaly** [comment]
> Please retest it with next testversion

This bug is now fixed, thank you.
