### ISSUE TITLE
Operator is not load at reload

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2588]
The group permission matrix uses the operator factory to [query the operator's groups](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/users/static/js/users/base.js#L59) to determinate if the user could lock himself out of the configuration. If there is the danger, red ban icons are shown at user manage and see permissions.

But on reload these icons are not there and there is a js error `operator.user is undefined`. Also the loading indicator is red. clicking on another app (also frontpage is ok) the loading indicator turns blue. Additionally there is no network traffic, so this is a pure js/client issue. Now clicking on user/groups the ban icons are there and `operator.user` is the current active user.

Other way around: going to the frontpage and reload the page. Now the loading indicator is red. Switching to user/groups the operator gets load and everything works fine.

As the conclusion on page load the operator is not set but after the first state change. But I expect that the operator gets set when the page is loaded; so the operator is available for every app on a reload.

**Comment by emanuelschuetze** [comment]
To reproduce it:
Reloading the groups list view gets JS error:`TypeError: Cannot read property 'groups_id' of null`

**Comment by emanuelschuetze** [comment]
see #2854
