### ISSUE TITLE
conflicting versions of jquery and angular-bootstrap

### ISSUE THREAD

**Issue by matakuka** [OpenSlides/OpenSlides#2593]
I just (re)installed Openslides from an older version, and `npm install` stumbled on this error: 
`Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3`.

Changing jquery on [bower.json](https://github.com/OpenSlides/OpenSlides/blob/master/bower.json#L5) to "1.9.1 - 2.9.9" resolved this issue for now, but I'm not sure if a higher jquery is actually needed somewhere, or if there's just some obscure misconfiguration on my system.

**Comment by FinnStutzenstein** [comment]
the user import uses `_.uniqWith` which is new in Version 4.0.
But why do you installed an older version of OS? The current master works fine and do not have this issue.

**Comment by matakuka** [comment]
I did install the new version, when I still had a (pretty old) old version running on this system. So it may be an update issue, and nothing that happens on a clean install.

**Comment by emanuelschuetze** [comment]
@matakuka Is this reproduceable for you? Otherwise I would close this issue.

**Comment by emanuelschuetze** [comment]
Please reopen if you can reproduce it.
