### ISSUE TITLE
OS 2.1: cannot login anymore as admin

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2595]
I just checked out today's master and now I cannot login anymore as admin. I have cookies enabled.

After an attempt to login I get this message:

![localhost 8000 2016-11-07 22-46-40](https://cloud.githubusercontent.com/assets/1828501/20077328/446559ce-a53c-11e6-8eaf-0c502cb4a547.jpg)

I now reset the admin in the OS server and retried but I get the same error.

**Comment by normanjaeckel** [comment]
Hm. Please open network console (press F12) and give us the network answer of your login request.

**Comment by donovaly** [comment]
I pulled today's master and with this I can now login. I have no other explanation that one of today's commits fixed the problem.
