### ISSUE TITLE
OS 2.1: impossible to creat ballot PDF for motions

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2607]
- create a new motion
- open this motion and create a new election
- press the PDF button to generate ballot papers for this election

result: nothing happens

**Comment by donovaly** [comment]
This is fixed in today's master

**Comment by donovaly** [comment]
Sorry, this reappeared again today despite that I have not changed anything in my OS version.

Something is fishy in general with the motions. I hope that fixing issue #2614 will fix this as well.

**Comment by emanuelschuetze** [comment]
I have an idea...
@donovaly Can you give me the error output of your JS console (type F12 in Chrome/Firefox to open it)? Does the error told something about font error with the Roboto font?

**Comment by donovaly** [comment]
> Does the error told something about font error with the Roboto font? 

You were right:

``
Error: Font 'Roboto' in style 'bold' is not defined in the font section of the document definition.
i.prototype.provideFont@http://localhost:8000/static/js/openslides-libs.js:72:19440
s/<@http://localhost:8000/static/js/openslides-libs.js:73:7140
s@http://localhost:8000/static/js/openslides-libs.js:73:6835
n.prototype.buildInlines@http://localhost:8000/static/js/openslides-libs.js:73:7713
r.prototype.measureLeaf@http://localhost:8000/static/js/openslides-libs.js:73:839
r.prototype.measureNode/<@http://localhost:8000/static/js/openslides-libs.js:72:31959
n.prototype.auto@http://localhost:8000/static/js/openslides-libs.js:73:9497
r.prototype.measureNode@http://localhost:8000/static/js/openslides-libs.js:72:31673
r.prototype.measureVerticalContainer@http://localhost:8000/static/js/openslides-libs.js:73:1079
r.prototype.measureNode/<@http://localhost:8000/static/js/openslides-libs.js:72:31785
n.prototype.auto@http://localhost:8000/static/js/openslides-libs.js:73:9497
r.prototype.measureNode@http://localhost:8000/static/js/openslides-libs.js:72:31673
t/<@http://localhost:8000/static/js/openslides-libs.js:73:2610
n.prototype.auto@http://localhost:8000/static/js/openslides-libs.js:73:9497
r.prototype.measureTable@http://localhost:8000/static/js/openslides-libs.js:73:4797
r.prototype.measureNode/<@http://localhost:8000/static/js/openslides-libs.js:72:31912
n.prototype.auto@http://localhost:8000/static/js/openslides-libs.js:73:9497
r.prototype.measureNode@http://localhost:8000/static/js/openslides-libs.js:72:31673
r.prototype.measureVerticalContainer@http://localhost:8000/static/js/openslides-libs.js:73:1079
r.prototype.measureNode/<@http://localhost:8000/static/js/openslides-libs.js:72:31785
n.prototype.auto@http://localhost:8000/static/js/openslides-libs.js:73:9497
r.prototype.measureNode@http://localhost:8000/static/js/openslides-libs.js:72:31673
r.prototype.measureDocument@http://localhost:8000/static/js/openslides-libs.js:72:30655
i.prototype.tryLayoutDocument@http://localhost:8000/static/js/openslides-libs.js:72:23671
i.prototype.layoutDocument@http://localhost:8000/static/js/openslides-libs.js:72:23450
r.prototype.createPdfKitDocument@http://localhost:8000/static/js/openslides-libs.js:70:13420
r.prototype._createDoc@http://localhost:8000/static/js/openslides-libs.js:69:16269
r.prototype.getBuffer@http://localhost:8000/static/js/openslides-libs.js:69:18223
r.prototype.download@http://localhost:8000/static/js/openslides-libs.js:69:17487
obj.createPoll@http://localhost:8000/static/js/openslides.js:9103:13
anonymous/fn@http://localhost:8000/static/js/openslides-libs.js line 7 > Function:2:278
t@http://localhost:8000/static/js/openslides-libs.js:5:25412
ua[t]</<.compile/</</i@http://localhost:8000/static/js/openslides-libs.js:8:9160
Cn/this.$get</h.prototype.$eval@http://localhost:8000/static/js/openslides-libs.js:6:3582
Cn/this.$get</h.prototype.$apply@http://localhost:8000/static/js/openslides-libs.js:6:3814
ua[t]</<.compile/</<@http://localhost:8000/static/js/openslides-libs.js:8:9210
he.event.dispatch@http://localhost:8000/static/js/openslides-libs.js:2:18833
he.event.add/p.handle@http://localhost:8000/static/js/openslides-libs.js:2:16887
``

**Comment by emanuelschuetze** [comment]
@donovaly Should be fixed in current master. Please retest.

**Comment by donovaly** [comment]
Confirmed fixed.
