### ISSUE TITLE
Try to upload an encrypted PDF breaks server.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2609]
Create a PDF file with a password (using LibreOffic e. g.). Try to upload this file: You get a server error: PyPDF2.utils.PdfReadError: File has not been decrypted.

**Comment by emanuelschuetze** [comment]
It's not a blocker for 2.1b1 for me...

**Comment by normanjaeckel** [comment]
Not only the upload of the file seems impossible. If someone uploads an encrypted file the complete mediafile app is unavailable for all users and managers.

**Comment by FinnStutzenstein** [comment]
Whats about catching the error and display a message, that these files are not supported?

**Comment by normanjaeckel** [comment]
Sounds good.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Can you try it?
