### ISSUE TITLE
OS 2.1: regression: no longer possible to set vote majority

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2613]
- create a new motion
- create a new vote

result: the combobox to select the necessary majority does no longer appear. This is with the OS 2.1 version emanuel sent me today. It worked before.

**Comment by donovaly** [comment]
I see now that the combobox is displayed but first after one inserted the vote results. It might be that this new behavior is desired. if so please tell me that i can update the docs accordingly.

**Comment by emanuelschuetze** [comment]
I can't reproduce it with current master. Please try it again with next test version and note that the default value of settings variable (motion > required majority) is not 'disabled'.

**Comment by donovaly** [comment]
> Please try it again with next test version and note that the default value of settings variable (motion > required majority) is not 'disabled'.

The problem persists. motion > required majority is set to "simple majority".

As I said, the combobox appears now after one entered the voting result. Formerly it was displayed immediately. Both methods are acceptable, I only need to be sure what I could document.

**Comment by emanuelschuetze** [comment]
Should be fixed in 2.1b1. Please reopen if not.

**Comment by donovaly** [comment]
> Should be fixed in 2.1b1.

Yes, I'll update the docs accordingly asap.

**Comment by donovaly** [comment]
> I'll update the docs accordingly asap. Done, but found bug #3021.
