### ISSUE TITLE
OS 2.1: double-click required to create a change recommendation

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2615]
- go with the mouse between the line number of a motion text line and the first character of the line
- click on the appearing plus button

result: nothing happens

It only works if one double-clicks on the button. This might look as a minor problem but it cost me a lot of time to find out why i cannot create a change recommendation by clicking on the button.

**Comment by emanuelschuetze** [comment]
This behaviour is correct:
First you have to click the start line, finally you have to click the end line of your change recommendation.
In your special case if you want to change one line only you have to click two times on the plus button (start/end line is here the same).

Any idea how to improve this?

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze I would prefer this behaviuor:

- the first click selects the clicked line --> you can change this line
- on a second click, the region is expanded (but the second click is not necessary)

I don't know if the region has to be fix to change the text, if not one could change the region while editing this.

**Comment by donovaly** [comment]
I agree with the proposal of @FinnStutzenstein.

**Comment by CatoTH** [comment]
The problem here is that changing the text is done in an overlay. So if the first click opens the overlay already, you won't be able to select the second line anymore.
I agree that this behavior is somewhat confusing an some clarification would be helpful, though...

**Comment by donovaly** [comment]
I described the behavior now in the docs. I leave it up to you developers if you change it or not.

**Comment by normanjaeckel** [comment]
What about open a small tooltip oder hint after the first click like “Move down or click on the same line to create a change recommendation ...”?

**Comment by emanuelschuetze** [comment]
@normanjaeckel Yes, I also think about this solution with @CatoTH.
@CatoTH Please try to implement this.

**Comment by CatoTH** [comment]
Here's a proposal:
![bildschirmfoto 2016-11-19 um 16 51 43](https://cloud.githubusercontent.com/assets/533440/20456552/0c088880-ae79-11e6-93a6-cac1ec37c199.png)

**Comment by donovaly** [comment]
Looks good.

**Comment by emanuelschuetze** [comment]
Done in current master.
