### ISSUE TITLE
OS 2.1: highlighting motion lines feature is killed by change recommendation feature

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2617]
- open a motion
- create a change recommendation
- view the changes and click in this view on the trash button

result: there are no changes anymore but OS displays an unnecessary change summary box and, more important, the feature to highlight a motion text line is gone:

![localhost 8000 2016-11-11 00-27-05](https://cloud.githubusercontent.com/assets/1828501/20198588/b0d0bb6a-a7a5-11e6-9305-d6b6075f8650.png)

**Comment by emanuelschuetze** [comment]
confirmed.

**Comment by donovaly** [comment]
Confirmed fixed
