### ISSUE TITLE
OS 2.1: change recommendation cannot be created without line numbering

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2618]
This might be a feature but it is not clear why:
- open a motion, set the line numbering to inline or turn it off
- try to create a change recommendation

result: this is impossible

**Comment by emanuelschuetze** [comment]
That's correct. To create a new change recommendation you have to show the line numbers in outline mode because you have to select line numbers (which is to complicated in inside mode and not possible in none mode).

**Comment by donovaly** [comment]
OK, Ill document this behavior.
