### ISSUE TITLE
OS 2.1: comment field for motions does not appear

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2624]
In the motion settings an can add a comment field. But I cannot see a place where I can use my created comment field.

**Comment by emanuelschuetze** [comment]
If you create a motion comment field in setting, go to a motion update form. You find the motion comment field in an editor at the end of the update form dialog. Hope this helps you.

**Comment by donovaly** [comment]
> go to a motion update form. You find the motion comment field in an editor at the end of the update form dialog.

What is a motion update form? When I edit a motion I cannot see a comment anywhere. Do you have a screenshot for me please?

**Comment by donovaly** [comment]
Ping.

**Comment by emanuelschuetze** [comment]
Test with a fresh database:
* Add a (private) motion comment field "foo"
* create new motion 
-> in motion form dialog (at the end) you find a editor field with label "foo". There you can enter some comments...
* save motion and open motion detail view
-> "foo" comment is listed at the end of this page

So works for me.

**Comment by donovaly** [comment]
> Add a (private) motion comment field

Ah, this is a new feature that was no described. I described it now in the docs.
