### ISSUE TITLE
fix scroll battle and move calculations to server side

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2636]
See PR #2620

**Comment by FinnStutzenstein** [comment]
Does anyone has an idea how to calculate the offset (in px) on the serverside? The main problem is described in PR #2360 

Assuming this:
```
L1: 1 short text 2 text long text ..... bla
L2: bla bla 3 another text.. 4 text text
L3: text text text
```

So on the client side I can just query what the offset of every line is. But how does the server should calculate this?

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze As we didn't find any solution, we should remove this feature (remove all code for projector scrolling; if it's needed sometimes later, Github will have it), make a new issue 'scroll projector to a given line' (Milestone 2.2) and close this.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Yes, please remove the scroll projector feature for 2.1 and create a new issue for 2.2.

**Comment by emanuelschuetze** [comment]
Issue for 2.2 created: #3010
