### ISSUE TITLE
Multiprojector manage view needs a lot of performance in Firefox

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2638]
Test this with firefox:
* Create 3 projectors.
* Click identify button.
* Reload the page.
Firefox needs very long for loading the full page... Sometimes (on small machines) Firefox freezed or crashed. Chrome works better.

@FinnStutzenstein Any idea how to improve the loading performance of this heavy projector page?
@donovaly Thanks for reporting.

**Comment by FinnStutzenstein** [comment]
See #2521 .

**Comment by donovaly** [comment]
With Firefox 50 it is slightly better. In my opinion the performance is OK now since pressing Identify is not often necessary. Nevertheless the performance could be improved.

**Comment by emanuelschuetze** [comment]
I think we can move this to milestone 2.2...

**Comment by emanuelschuetze** [comment]
Currently, I see nothing to improve it. Please reopen if required...

**Comment by donovaly** [comment]
With Firefox 58 I cannot see a problem anymore. It is as quick as necessary.
