### ISSUE TITLE
missplaced comma in default PDF documents

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2639]
since the last PDF iteration there is a misplaced comma (',') under the headline
perhaps one wanted to test doubled headlines? 

@emanuelschuetze 

![bildschirmfoto von 2016-11-16 11-04-45 - 1](https://cloud.githubusercontent.com/assets/10233032/20343025/1be11eb8-abed-11e6-92bd-7c98e9631f4f.png)

**Comment by emanuelschuetze** [comment]
fixed in #2640
