### ISSUE TITLE
CSV-Import: Escaping of quotation marks

### ISSUE THREAD

**Issue by CatoTH** [OpenSlides/OpenSlides#2645]
Hi,

After trying for a while, I couldn't figure out how to correctly import richt text using the CSV-import. Especially quotationmarks seem to make problems, and none of the examples have any kind of hint how to properly escape them.
The usual way would be to escape a " by either a double "" or an \". However, both variants are not unescaped in the import. Is there any hint in how to include quotes, line breaks and commas in the imported text? Or is this feature just missing?

Bye,
  Tobias

**Comment by emanuelschuetze** [comment]
Good question. I tried the csv motion import with the following motion csv example file - with `<p>..</p>` and `<b>..</b>` tags (which are used in imported motion) and some quotes:
```
identifier,title,text,reason,submitter,category,origin
,Satzungsänderung § 2 Abs. 3,"<p>Die Versammlung möge beschließen, die Satzung in <b>§ 2 Abs. 3</b> wie folgt zu ändern:</p>
<p>Es wird vor dem Wort "Zweck" das Wort "gemeinnütziger" eingefügt.</p>",,Max Mustermann,Satzungsanträge,
```

After importing, only the double quotes at begin and end of motion text are not removed:
```
"
Die Versammlung möge beschließen, die Satzung in § 2 Abs. 3 wie folgt zu ändern:

Es wird vor dem Wort "Zweck" das Wort "gemeinnütziger" eingefügt.

"
```
Seems that the replace line in motion import [site.js](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/js/motions/site.js#L1539l) does not work... Maybe you can help us and can make a pull request?

Any more problems with csv import?

**Comment by CatoTH** [comment]
After trying for a bit, it seems like the import only works when an even number of quotation marks is in the string:

```
identifier,title,text,reason,submitter,category
"LTW 1","LTW-Programm - PRÄAMBEL","Ich bin ein "Test" und so",,Landesvorstand,Landtagswahlprogramm
```
Works, while
```
identifier,title,text,reason,submitter,category
"LTW 1","LTW-Programm - PRÄAMBEL","Ich bin ein " Anführungszeichen",,Landesvorstand,Landtagswahlprogramm
````
does not not.

Also, the import is not possible if a comma is inside quotation marks:
```
identifier,title,text,reason,submitter,category
"LTW 1","LTW-Programm - PRÄAMBEL","Ich sagte "Test, Test 2" ins Mikro",,Landesvorstand,Landtagswahlprogramm
```

Having unescaped quotation marks and commas is probably somewhat confusing for the parser. Usually, quotation marks are escaped by "" or \" for that reason - which, as far as I know, was the standard in OS1 as well.

**Comment by FinnStutzenstein** [comment]
@CatoTH Pleasy retry with new csv import.

**Comment by emanuelschuetze** [comment]
@CatoTH I tested it successfully with Antragsgrün CSV export. Please test it yourself and reopen if something does not work.

**Comment by CatoTH** [comment]
@emanuelschuetze Yes it works now. It's still a bit picky about line breaks (it doesn't import anything anymore if the line breaks of the motion text are using \r), but I can work around that. So it's fine for me now. :)
