### ISSUE TITLE
blocker: OS can no longer display anything on a projector

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2646]
- create 2 projectors
- choose projector 2 in the projector preview window
- now try to display the agenda on projector 2 

result: nothing is displayed in it

- now manage and delete the second projector

result: now it is impossible to display anything. No matter what you try, the projector view keeps blank. Also restarting the server does not help. To be honest I am totally lost. All I get is this error in the server console when pressing the identify button:

[2016/11/19 02:16:09] WebSocket CONNECT /ws/projector/1/ [127.0.0.1:50196]
2016-11-19 02:16:09,751 - ERROR - worker - Error processing message with consumer openslides.utils.autoupdate.ws_add_projector:
Traceback (most recent call last):
  File "D:\OpenSlides\2.1test\lib\site-packages\channels\worker.py", line 120, in run
    consumer(message, **kwargs)
  File "D:\OpenSlides\2.1test\lib\site-packages\channels\sessions.py", line 180, in inner
    result = func(message, *args, **kwargs)
  File "D:\OpenSlides\2.1test\lib\site-packages\channels\auth.py", line 73, in inner
    return func(message, *args, **kwargs)
  File "D:\OpenSlides\2.1test\lib\site-packages\channels\sessions.py", line 64, in inner
    return func(message, *args, **kwargs)
  File "D:\OpenSlides\2.1test\lib\site-packages\channels\auth.py", line 89, in inner
    return func(message, *args, **kwargs)
  File "D:\OpenSlides\2.1test\lib\site-packages\openslides\utils\autoupdate.py", line 75, in ws_add_projector
    projector = Projector.objects.get(pk=config['projector_broadcast'])
  File "D:\OpenSlides\2.1test\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\OpenSlides\2.1test\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
openslides.core.models.DoesNotExist: Projector matching query does not exist.
[2016/11/19 02:16:10] HTTP POST /rest/core/projector/1/control_blank/ 200 [0.03, 127.0.0.1:50189]
[2016/11/19 02:16:14] HTTP POST /rest/core/projector/1/clear_elements/ 200 [0.05, 127.0.0.1:50189]

**Comment by donovaly** [comment]
I forgot to mention that this is with today's master.

**Comment by donovaly** [comment]
I am completely lost. I deleted the browser cache, used another browser erased my complete OS file directory. I still cannot project anything anymore as soon as I use my database:

[db.zip](https://github.com/OpenSlides/OpenSlides/files/601193/db.zip)

This database worked OK with git version from Wednesday.

**Comment by emanuelschuetze** [comment]
Sorry, I can't reproduce it with the portable version of yesterday (and a fresh! database). I can create a 2nd projector and project each slide to projector 1 and 2. Maybe you have enabled the "blank" and/or "broadcast" option of one projector?? Can you verify that it works if you start with a fresh (empty) openslides data directory? I havn't try it with your database.

**Comment by emanuelschuetze** [comment]
Ah, with your database I can see the server problem... 
`openslides.core.models.DoesNotExist: Projector matching query does not exist.`
I can't find a way to resolve it via GUI. So we have to fix it on server side...
@normanjaeckel Please look at this problem
@donovaly For further testing please use a fresh db.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze look at the trace:
```
File "D:\OpenSlides\2.1test\lib\site-packages\openslides\utils\autoupdate.py", line 75, in ws_add_projector
projector = Projector.objects.get(pk=config['projector_broadcast'])
```
This line is only executed, if broadcast is activated (see line 74)..

Maybe @donovaly deleted the projector that was broadcasting. If this is a problem, a check on serverside on projector delete is necessary.

**Comment by FinnStutzenstein** [comment]
Can you look in the config, which projector was broadcasted?

**Comment by normanjaeckel** [comment]
I can confirm the following:
Create second projector. Set broadcast to this second projector. Then delete it. The error `openslides.core.models.DoesNotExist: Projector matching query does not exist.` occurs.

**Comment by FinnStutzenstein** [comment]
Ok, I will try to fix this this evening.

**Comment by normanjaeckel** [comment]
Fix is coming. To reset your damaged database run
`$ python manage.py changeconfig projector_broadcast 0`

**Comment by donovaly** [comment]
> Maybe @donovaly deleted the projector that was broadcasting. 

Yes, as I described in my initial comment. It was a mistake but I fear others might do this as well.

> To reset your damaged database run
$ python manage.py changeconfig projector_broadcast 0

There is no file manage.py in my OS directory.

**Comment by donovaly** [comment]
> Maybe @donovaly deleted the projector that was broadcasting. 

Yes, as I described in my initial comment. It was a mistake but I fear others might do this as well.

> To reset your damaged database run
$ python manage.py changeconfig projector_broadcast 0

There is no file manage.py in my OS directory.
