### ISSUE TITLE
Use Angular cache for majority calculation

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2650]
After #2557 is merged we use `MotionPollDetailCtrlCache` and `AssignmentPollDetailCtrlCache` to provide a custom cache for the majority calculcation setting. But we should not use our own stuff here but use Angular $cacheFactory e. g.

Who can do this?

**Comment by jsaalfeld** [comment]
Since we rewrite the whole client, this shouldn't be an issue anymore. Please reopen if I'm wrong.
