### ISSUE TITLE
regression: display bug in new participant handling

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2652]
After #2592 from @FinnStutzenstein has been merged there is now a display bug:

- go to the agenda and display it
- now go to the participant list and click there on a name of a participant

result: OS indicates that this user is now displayed while still the agenda is correctly displayed:

![localhost 8000 2016-11-19 15-04-11](https://cloud.githubusercontent.com/assets/1828501/20455987/9ef00e94-ae69-11e6-9c96-55e99c128e6f.png)

If you really want to display the user this is no longer possible because one cannot unpress the display button - regression.

**Comment by FinnStutzenstein** [comment]
I checked the file histroy for the user-detail.html: I think I have just overseen this project-button with the Multiprojector feature and nobody recognized it (almost one month ago) ;) @donovaly has eagle eyes ;)
If one creates a second projector, this button does not have the dropdown menu and its all old code in this template. I'll create a PR for this...

**Comment by emanuelschuetze** [comment]
This is already fixed.

**Comment by donovaly** [comment]
Confirmed fixed.
