### ISSUE TITLE
missing translation for agenda title in the projector

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2653]
- use English as language for OS
- display the agenda

result: one gets in the projector "Tagesordnung" instead of "Agenda":

![localhost 8000 2016-11-19 15-07-12](https://cloud.githubusercontent.com/assets/1828501/20456016/d21941cc-ae6a-11e6-8eb4-02266291e2c5.png)

I thought I already reported it and the reason is that OS uses the browser language instead of its own language settings. But I cannot find this bug report.

**Comment by emanuelschuetze** [comment]
We can't switch the language for projector on-the-fly in OpenSlides. You have to change your default browser language.
-> Won't fix.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze I was thinking of a configvalue "Projector language" . Then the languagecontroller (needed on the projectorside) could get the language from the config. Then the language on all projectors is the same. Your opinion?

**Comment by emanuelschuetze** [comment]
Sound good. But not very important for 2.1. Let us move it to 2.2.

**Comment by donovaly** [comment]
Please reopen this bug because it is not fixed in beta 3:

![localhost 8000 2017-02-14 01-04-41](https://cloud.githubusercontent.com/assets/1828501/22908971/a0b1820e-f251-11e6-9f05-057dc21891b1.png)

**Comment by normanjaeckel** [comment]
@emanuelschuetze Please check milestone of this issue.

**Comment by emanuelschuetze** [comment]
@donovaly You can change the projector language in "Settings > Projector" to your desired language. Works for me.

**Comment by donovaly** [comment]
> You can change the projector language in "Settings > Projector" to your desired language. 

Ah, many thanks for the info. I added this new setting now to the docs.
