### ISSUE TITLE
OS does not notify when a login attempt failed

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2654]
- disable cookies in your browser and afterwards delete all cookies in your browser
- start the OS server and try to login as admin
- OS now correctly warns you that cookies are required, proceed anyway to login as admin

result: your are correctly not logged in but without any notice that the login failed. You see the content of OS as if you were a guest. That is in principle correct. but users might still wonder why they cannot do anything. Therefore OS must issue an error message If a login attempt failed. if it failed because of disabled cookies, this should displayed. with this info.

The error message should be displayed like a message with red text to assure that the users really get this/cannot overlook it.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein If you find a quick solution for 2.1 please implement. Otherwise we move it to 2.2.

**Comment by FinnStutzenstein** [comment]
@donovaly @emanuelschuetze hiw do you disable cookies? In you browser settings or with a plugin (which plugin)?

**Comment by donovaly** [comment]
> how do you disable cookies?

In the browser settings. In some organizations they are by default disabled. I don't know how this is technically done but I have seen this. Personally I always browse with disabled cookies unless I need them (like now to use GitHub). To achieve this one can explicitly disable them or use the safe browse mode. Also on my smart phone there is a privacy browse mode that denies cookies by default.

**Comment by FinnStutzenstein** [comment]
@donovaly please retest, should be fixed with the PR.

**Comment by emanuelschuetze** [comment]
@donovaly please reopen if this is not fixed for you.

**Comment by donovaly** [comment]
> @donovaly please retest, should be fixed with the PR.

This is fixed in beta3. many thanks!
