### ISSUE TITLE
regression: impossible to change password for users

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2656]
- login as admin
- go to the Participants menu
- under a name of a participant click "Change password"
- input a new password, e.g. "test" and click on "Change password"

result: OS shows a success screen:

![localhost 8000 2016-11-19 17-10-11](https://cloud.githubusercontent.com/assets/1828501/20456678/5b0abb4a-ae7b-11e6-99c6-168ec2b5dbb2.jpg)

but in effect nothing was changed. If you go back to the list and try to change the password again you see that the password was no changed. Also the PDF with all participants show the old password and the user can still only login with the old password.

This is a major regression in terms of functionality. I would even say a must fix for OS 2.1.

**Comment by FinnStutzenstein** [comment]
@donovaly We changed the behavior of the "initial password" (previous "default password"). This initial password is not more changeable. This is set on the users creation (if not given its a random string). If the user changes his password, he sets his own password but the initial password stays the same. So the user has some kind of two passwords, but the initial passwords works only until the user changes his password.

In this view the admin does not change the initial password but the real password. He may could set it back to the initial password, for this reason the initial password is printed below the input box. We thought of this this situation: A user goes to the admin: "I've forgot my password" and than the admin has to possibilities. Reset to the initial password and give the user the login-pdf or just let the user type in his new password.

**Comment by donovaly** [comment]
Many thanks, I understood it now and will document it.
