### ISSUE TITLE
blocker: identifying a projector makes it unusable

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2658]
- manage projectors
- create a new projector
- go to e.g. the agenda menu
- go back to manage projectors and delete the second projector
- press "Identify"

result:

![localhost 8000 2016-11-19 18-59-29](https://cloud.githubusercontent.com/assets/1828501/20457378/5acacc24-ae8a-11e6-8980-cb641b3bfd31.jpg)

No matter what I do, it is impossible to project anything on the default projector anymore. I can log out, delete my browser cache but nothing helps. Even restarting the server does not help. I am lost.

**Comment by donovaly** [comment]
> @FinnStutzenstein FinnStutzenstein added a commit to FinnStutzenstein/OpenSlides that referenced this issue 7 hours ago 

I tried this fix but this does not help me, also not with a new database. As soon as I press identify, I can no longer project anything.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze please verify this. I do not know why this didn't work without the fix. When creating the message and countdown PR this was working perfectly..?

**Comment by emanuelschuetze** [comment]
With current master (which includes now the pr #2529) the identify feature works as expected: after some seconds the identify messages are removed.
@donovaly Please retest with next test version.

**Comment by donovaly** [comment]
> after some seconds the identify messages are removed.
@donovaly Please retest with next test version.

But now nothing happens. There is no identify message shown anymore.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze closed with PR #2663

**Comment by donovaly** [comment]
Thanks, this is now fixed as I wanted.
