### ISSUE TITLE
ugly linebreak in projector preview

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2660]
- project the agenda
- scroll two times and zoom in one step
result:
![localhost 8000 2016-11-19 19-30-31](https://cloud.githubusercontent.com/assets/1828501/20457582/ac6121ce-ae8e-11e6-9c23-35ba70da2ff1.jpg)

- now zoom out twice
result:
![localhost 8000 2016-11-19 19-27-52](https://cloud.githubusercontent.com/assets/1828501/20457574/8c5f150c-ae8e-11e6-805f-62b620e213fa.jpg)

This looks ugly and is unnecessary since there is enough space to increase the width of the projector preview a bit so tat two negative values can be displayed in one line.

**Comment by emanuelschuetze** [comment]
I can confirm it in Chrome for values "-1" and "-1" - but in projector mangage view only (not in side bar).
@FinnStutzenstein Please look at this (minor) issue.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze  Closed with PR #2751

**Comment by donovaly** [comment]
Confirmed fixed.
