### ISSUE TITLE
Edit projector view does nothing when projecting the whole agenda

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2661]
- project something of your choice
- in the projector preview press the leftmost button besides the zoom buttons to edit the projector view

result: nothing happens

**Comment by FinnStutzenstein** [comment]
Could not recreate this: Tested with motion, topics, user, election in preview and manage view.

**Comment by donovaly** [comment]
I see now, that the bug only appears when projecting the whole agenda. Then click on the edit projector view button and nothing appears.

The fix would be to disable this button when the whole agenda is displayed since nothing could then be edited.

**Comment by donovaly** [comment]
Confirmed fixed, thanks.
