### ISSUE TITLE
Projector address inconsistent

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2662]
- create 3 projectors
result: projector 3 has the address
http://localhost:8000/projector/3/

- now delete projector 3
- create subsequently a new projector.

result: one has still 3 projectors, but the third one has now the address
http://localhost:8000/projector/4/

It should have the address
http://localhost:8000/projector/3/
because the projector that had formerly this address was deleted.

**Comment by emanuelschuetze** [comment]
The projector id is the (unique) database id. If you delete a db entry (projector) the counter increments for new created entry. We can't change this behaviour. BTW: It is the same behaviour as e.g. for motions (where we print the sequential number in pdf).

**Comment by donovaly** [comment]
OK.
I have a documentation for this ready that I could push as soon as my doc pull request is in.
