### ISSUE TITLE
missing translation in the access data PDF

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2664]
- use English menus in OS
- go to the menu Settings-> Participants and assure that in the field "Help text for access data and welcome PDF" is the default text (press Reset).
- now go to the Participants menu
- change the menu language of OS to German
- create the Zugangsdatenliste PDF

result: While the PDF is in German you have the English text "[Place for your welcome and help text.]" in there. But if you look at the participant settings you see the correct German default text "[Platz für Ihren Begrüßungs- und Hilfetext.]"

The same bug appears for the "Title for access data and welcome PDF" field content in the participant settings.

**Comment by emanuelschuetze** [comment]
Confirmed. Fixed with #2742.

**Comment by emanuelschuetze** [comment]
Fixed.

**Comment by donovaly** [comment]
Confirmed fixed.
