### ISSUE TITLE
regression: missing QR code in the access data PDF

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2665]
The access data PDF has no longer a QR code - regression to OS 2.0.

**Comment by tsiegleauq** [comment]
Yep we have been aware of this, however, nobody made an exclusive issue for that!
We need to find and vandalize JS libraries for QR-Code generation.

**Comment by tsiegleauq** [comment]
pdfmake now supports qr-code generation:

[https://github.com/bpampuch/pdfmake/blob/master/examples/qrCode.js](https://github.com/bpampuch/pdfmake/blob/master/examples/qrCode.js)

**Comment by donovaly** [comment]
Many thanks for fixing this. But has it need tested if the QR code points to the correct link? I cannot test it because I run OS on my private PC not a website. So if somebody could just test the QR code this would be nice.

**Comment by tsiegleauq** [comment]
Hi. I just point to the value `Config.get('users_pdf_url')`
If this value is correct, the QR should work. Tested it during development

**Comment by donovaly** [comment]
Thanks for testing.

**Comment by donovaly** [comment]
This bug has the wrong milestone. It is fixed for 2.1 and should therefore have the 2.1 milestone, not the 2.2 milestone.

**Comment by emanuelschuetze** [comment]
Done
