### ISSUE TITLE
wrong participant group number in csv example file and description

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2666]
When importing participants, OS states "Default groups: Delegates 2, Staff 3 Committees 4". But in the offered example file the group number 5 is used for the committee.

This is all wrong: currently the group 6 is the one for delegates and 4 for staff. At least on my system.
When using the offered example file I only get garbage since e.g. the committee has group 5 but there is no such group in OS. I expected that there is a group for committees as described and if it does not exist it should be created during the import.

Maybe I completely misunderstood the feature but it is nevertheless quite unusable as it is.

**Comment by donovaly** [comment]
Hmm, with a new database I see that the described default groups are correct but the example file is then wrong.

Besides this I think the problem is that if you create a group, delete it and create a new group, the group number is permanently increased. I would say there should only be numbers for the number of existing groups. So if there are 4 groups there should only group numbers from 1 - 4.

No matter how you decide I think it is essential that one see the actual group number in the group matrix/table.

**Comment by emanuelschuetze** [comment]
You're right. Currently, with new group matrix, we can't see any more the group id. 
Suggestion: We print all available groups (with corresponding ids) in tne users import view - instead of hard coded groups.

**Comment by donovaly** [comment]
Something has to be done here for 2.1 because even with a brand new database it is not possible to import users assuring that they get the delegate status. but this is essential for many meeting, especially political party meetings.
