### ISSUE TITLE
ugly display of import participant table

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2667]
Use german menus and try to import participants via a CSV table. Result:

![localhost 8000 2016-11-20 18-39-55](https://cloud.githubusercontent.com/assets/1828501/20464879/4868328e-af51-11e6-8902-ee87f3a1aa28.png)

This could easily be fixed by introducing line breaks in the table header line. "Teilnehmendennummer" is a very long word and having it in 2 lines would help a lot. The same for "Gliederungsebene	".

Btw. why "Teilnehmendennummer"? Googling shows only 51 hits while "Teilnehmernummer" gives 136.000 hits. As a native German I also have never heard or read Teilnehmendennummer.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Can you improve the preview table. Maybe with adding a second line below the name like in users list table? And use "No." if number is set.

**Comment by emanuelschuetze** [comment]
Done with #2820.
