### ISSUE TITLE
blocker: regression: groups are ignored when importing participants

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2668]
- take this CSV file:
[Teilnehmer.zip](https://github.com/OpenSlides/OpenSlides/files/602222/Teilnehmer.zip)
result: in the preview table everything is correct but after exporting you can see that the groups were not set.

This is a major regression and even a blocker because in reality it is very important that the delegates really have delegate rights.

**Comment by emanuelschuetze** [comment]
Duplicate (see #2727). Already fixed with #2734.

**Comment by donovaly** [comment]
Confirmed fixed.
