### ISSUE TITLE
List of speakers offers inexisting features

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2669]
Below the projector preview there is a new section "List of speakers". This is a great feature but it only makes sense if the currently projected thing has a speakers list.

Take for example the case that you project a user. Cklick in the list of speakers on the projection symbol and/or press the microphone icon.
Result: nothing happens because a user has technically  no speakers list.

The fix would simply be to disable the speakers list buttons if the currently projected thing provides no speakers list.

This issue is in principle the same as issue #2661.

**Comment by emanuelschuetze** [comment]
Confirmed._

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Please fix this by disabling the button - like you do it for #2661.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze I was on it yesterday but i got confused what these buttons should do: Manageing the list of speakers or the _current_ list of speakers? The title is only LoS, but the source has something with current projected slide..
Please explain what the desired behaviors of these two buttons are.

**Comment by emanuelschuetze** [comment]
BTW: If you have only one projector the project button in section "list of speakers" gets 404:

`5 POST http://localhost:8000/rest/core/projector/undefined/activate_elements/ 404 (Not Found)`

**Comment by donovaly** [comment]
Is this fix in beta 3? I am asking because there the speaker's list feature is still not working correctly:

If a users is projected, the List of speakers' button must be inactive/blocked because a user cannot have a speaker's list.

**Comment by emanuelschuetze** [comment]
I think it is fixed in beta3 / current master:
If you project a user the projector sidebar section "list of speakers" shows 2 buttons:
* Project list of speakers button -> this is always active because it project an overlay which is empty if there is no list of speakers for current slide
* Manage list of speakers button -> This button is inactive if a user is projected.

=> Works all as expected.

**Comment by donovaly** [comment]
> Project list of speakers button -> this is always active because it project an overlay which is empty if there is no list of speakers for current slide

And I thought it should be inactive for things that cannot have a speaker's list. I find it a bit confusing that it is always active since it promises a feature that does not exist in every case.

**Comment by emanuelschuetze** [comment]
The feature (show overlay) exists always - but only for "special" slides (agenda item, motions, elections) there are a list of speakers. But the overlay is shown always. Otherwise it would be very confused if a projected element was unprojected automatically... 
=> won't change anything here.
