### ISSUE TITLE
Static impressum page

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#267]
Insert some short (technical) information about the OpenSlides-System and Project for offline users. May be at /config/version/

**Comment by emanuelschuetze** [comment]
Currently, in 2.0b1, we have a new HOME page for custom (welcome) information (title, text) with permission check. Should be enough...

**Comment by ostcar** [comment]
I would like to talk about this at our next telephone  meeting

**Comment by emanuelschuetze** [comment]
We want to add an impressum page which needs a new impressum text as config.
We reuse the version page.

**Comment by normanjaeckel** [comment]
Todo: More template improvements.
