### ISSUE TITLE
importing agenda items offers inexisting setting

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2672]
- import an agenda item via a CSV file.
- in the field "is_hidden" set a '1' to activate it

result: after the import the item is nit listed as agenda item, but when opening the Quick edit you see that the option to display as agenda item is set.
- if you do now nothing but to press "update" in the quick edit (without changing anything) the item gets now really displayed as agenda item.

The bug is that for agenda items there is no is_hidden feature. What is instead necessary is to to specify whether an agenda item is displayed in the agenda as such or not.

**Comment by emanuelschuetze** [comment]
Should be done with new agenda table. Please retest.

**Comment by donovaly** [comment]
Confirmed fixed. I will document it when the missing translations I mentioned in PR #2742 are in.
