### ISSUE TITLE
missing translation in the motion sorting

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2675]
- use German menus
- go to the motion list
- click on "Sortieren"

result: The string "Creation date" is in English:
![localhost 8000 2016-11-21 02-17-07](https://cloud.githubusercontent.com/assets/1828501/20467927/c0d423ce-af90-11e6-9fa2-6350d3fe8d28.jpg)

**Comment by emanuelschuetze** [comment]
Will be fixed with #2742

**Comment by emanuelschuetze** [comment]
Please test it later.

**Comment by emanuelschuetze** [comment]
Fixed.

**Comment by donovaly** [comment]
This string is now translated but when sorting according to the state there is another translation issue, see #2955.
