### ISSUE TITLE
Missing translation in motion edit dialog

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2676]
- use German menus
- create a new motion

result: There is the English word "Words" and there is a spurious "p":
![localhost 8000 2016-11-21 03-37-34](https://cloud.githubusercontent.com/assets/1828501/20468953/fd5a0c4a-af9b-11e6-9ff1-878b48fc3211.jpg)

**Comment by emanuelschuetze** [comment]
Probably we will change the editor (see #2720)...

**Comment by emanuelschuetze** [comment]
Done (now we use ckeditor)

**Comment by donovaly** [comment]
confirmed fixed
