### ISSUE TITLE
Speakers list is empty for elections

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2684]
- create a new election with 2 persons to be elect
- select 3 candidates
- click on "List of speakers"

result: the speakers list is empty. This is a regression to OS 2.0 where the candidates were automatically put on the speakers list. It is easier to remove a few persons from this list in case they are not present etc. than to add almost all candidates to the list. So if possible the behavior of OS 2.0 should be restored.

**Comment by emanuelschuetze** [comment]
You have to create a ballot first. Then all candidates are added to the list of speakers. Can you confirm this?

**Comment by donovaly** [comment]
> You have to create a ballot first. Then all candidates are added to the list of speakers.

This works but this is strange behavior because normally persons speak before the election begins. So starting the ballot before is very unintuitive. The behavior of OS 2.0 was better: add all selected candidates automatically to the speaker's list.

**Comment by emanuelschuetze** [comment]
@donovaly Is it ok for you to move this improvement to 2.2?

**Comment by donovaly** [comment]
> Is it ok for you to move this improvement to 2.2?

OK. I thought however that is easy to fix.

**Comment by donovaly** [comment]
> You have to create a ballot first. Then all candidates are added to the list of speakers.

This is now described in the docs.

**Comment by donovaly** [comment]
I reject my wish. I described in the docs that one has to start the ballot to fill the speaker's list. It is maybe unintuitive but has the advantage that one starts when one can be sure that the list of candidates is fixed.

**Comment by donovaly** [comment]
This bug has a milestone. The milestone can be removed because nothing will be done (WONTFIX or is no real bug).
