### ISSUE TITLE
enhancement: only one button to publish/project election results

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2685]
- create an election
- project the election
- start it and enter election results
- mark one person as elected

result: The elected person is immediately displayed as such in the projector.

- now press the "Publish" button.

result: nothing happens neither in the projector view nor inside OS.

**Comment by donovaly** [comment]
Damn.
OS is so unintuitive in this respect. Why do one have to press 2 buttons to display the results? The "Publish" button should be sufficient. There is no need for an additional projection button (or for the publish button).

**Comment by emanuelschuetze** [comment]
@donovaly Right the current ui concept is not very intuitive...
Suggestion: We remove the "publish" button and use the "project" button only for publish and project because very often you will publish all results in one step with project the result slide.
Important for me: Don't use hidden project function behind a button which does not say clear that clicking on it changes the projector.
@donovaly Would this suggestion ok for your?

**Comment by normanjaeckel** [comment]
I do not understand how this publish/unpublish concept should work. What if I want to pubulish results in the backend but do not want to project anything? How can I revert publishing results (if it was a mistake)?

**Comment by emanuelschuetze** [comment]
> What if I want to pubulish results in the backend but do not want to project anything? How can I revert publishing results (if it was a mistake)?

Right, both would be not possible with this "easy publish concept" (one project&publish button). Maybe we could add a new "unpublish" button for revert. Publish for backend only is not really important I think.

**Comment by donovaly** [comment]
> What if I want to publish results in the backend but do not want to project anything?

Just don't press the project button.

> How can I revert publishing results (if it was a mistake)?

Unpress the project button.

In my opinion after entering the election results they are already published. You can change the results any time by re-entering the results. So I don'*t see any reason why one need the Publish button.

**Comment by emanuelschuetze** [comment]
we like the posibility to publish election results, should be undo. this requires an extra button. So we don't know a better concept - so we wont't change it at the moment. Please reopen if you have a nice idea.
