### ISSUE TITLE
Translation: legal notice

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2693]
The legal notice does not get translated in the view, but in the config.

**Comment by emanuelschuetze** [comment]
Can't confirm this: Open /legalnotice/. Title and link text in footer shows "Impressum" in German.
Please retest it.

**Comment by emanuelschuetze** [comment]
Ah, I see. You mean the leagel notice config value not the title...

**Comment by emanuelschuetze** [comment]
Maybe you can try a fix...

**Comment by FinnStutzenstein** [comment]
Closed wich #2719
