### ISSUE TITLE
Add hook to get settings values in client

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2697]
We want to set some custom settings values like special labels or disabling some buttons. These values should be available in the client.

**Comment by normanjaeckel** [comment]
@ostcar I would like to add several new values to settings.py like `MOTION_FEATURE_FOO = 'bar'`. Now I want to read these values in the client. What would be the best way to do this?

I think you do not want me to render the index.html to add such stuff because we might want to serve the index.html by HTTP proxy server. I also can not use gulp for this because end users my want to change the settings.py but do not have node or gulp. I can imagine to hook my (special) settings values into our config REST (read only of course and hidden in client config interface). Is this better than adding a new URL which the client has to call before loading?

**Comment by ostcar** [comment]
I would add a new view/url.

When we redesign the startup process, then this new view could be merged together with the whoami view to one startup-view that returns a dict with different values.
