### ISSUE TITLE
convert image in file system to base64

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2705]
To be able to change certain logos in the PDF document we need a procedure to convert a given (image) file in the file-system of the OpenSlides server to base64. Preferably over JS

@emanuelschuetze we did talk about this today, please assign me to this issue.

**Comment by tsiegleauq** [comment]
**maybe** we do not need this anymore? it looks like relative file-paths somewhat work now in the latest version? I would need to try that out though.

See: [https://github.com/bpampuch/pdfmake/blob/master/examples/images.js](https://github.com/bpampuch/pdfmake/blob/master/examples/images.js)

**Comment by tsiegleauq** [comment]
nevermind.
```
    {
      // under NodeJS (or in case you use virtual file system provided by pdfmake)
      // you can also pass file names here
      image: 'myImageDictionary/image1.jpg'
    }
```

therefore, we still gonna need a function to convert something to base64

**Comment by FinnStutzenstein** [comment]
Do you have the file loaded in JS or do you just have the URL of the image (like /static/image.jpg)?

**Comment by emanuelschuetze** [comment]
...only the url of the image (on server side).

**Comment by FinnStutzenstein** [comment]
`images` is a list of image urls

```
var imgPromises = [], resolvedImages=[];
images.forEach(function (img) {
    imgPromises.push(
        $http.get(img, {responseType: 'arraybuffer'}).then(function (resolvedImage) {
            // TODO: convert resolvedImage to base64
            resolvedImages.push(resolvedImage);
        })
    );
});
// wait for all images to be resolved
$q.all(imgPromises).then(function () {
    //TODO: prozess these images that should now be resolved in 'resolvedImages'
});
```
This is a (modified) part of the [docx-exporter](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/js/motions/docx.js#L368). There I load images directly from urls.
You now just need to konvert the image to base 64. Maybe you use [this](http://stackoverflow.com/questions/9267899/arraybuffer-to-base64-encoded-string).

**Comment by tsiegleauq** [comment]
we did this before in a previous version. converting images to data URL is not the deal, keeping it sync is.

**Comment by tsiegleauq** [comment]
@FinnStutzenstein using promises and Promise.all() was a good hint!
I am able now to convert any lists of images locally without making too ugly code.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all
