### ISSUE TITLE
Link to MotionBlock detail view in agenda missing

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2710]
First, a permission check in isAllowedToSeeOpenLink (agenda/site.js) is missing for `motions/motion-block`.

But then the replacement in item-list.html `item.content_object.collection.replace('/','.')` creates wrong state: `motions.motion-block.detail` - expected: `motions.motionBlock.detail`.

Looks like it is related to #2480

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze what happens to the hotfix in pr #2622 ?
This issue is a duplicate of issue #2566
