### ISSUE TITLE
Cache not correctly updated on user import.

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2727]
When importing some users the group memberships are not shown in the list view. Looking at the networktraffic, the `groups_id` is correctly send to the server and the server has the `groups_id` in the response, so the server has saved the group memberships.
Looking at the rest API, no groups are set. If you restart the server (or wait some more time) the cache gets updated and now the user have groups set in the rest API and in the list view.

@normanjaeckel @ostcar Please have a look at this, i think this is a cache bug.

**Comment by normanjaeckel** [comment]
Confirm also for adding one new user if you use only one worker.
