### ISSUE TITLE
Move AgendaCsvExport factory to separate file

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2728]
Splitted our remark from [PR#2721](https://github.com/OpenSlides/OpenSlides/pull/2721#pullrequestreview-11170090):

"Please move this factory to a speparate angular module in a separate file (like for PDF)."

**Comment by FinnStutzenstein** [comment]
Note to myself: do the same for motions, ...
Maybe one "AgendaExport" factory for csv and pdf.
