### ISSUE TITLE
Motion csv import ignores motions which contains style attributes

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2741]
This motion csv example shows and imports the `test2` line only. `test1` is ignored.
```
identifier;title;text;reason;submitter;category
;test1;"foo <b style="text-decoration: underline;">bar</b>";;Max;
;test2;"foo <b>bar</b>";;Max;
```
@FinnStutzenstein Any idea why?

**Comment by FinnStutzenstein** [comment]
Oh, now I see... The semikolon is the seperator, so this is split up wrong.. (underline**;**)

**Comment by emanuelschuetze** [comment]
Ah, right...

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Closed.
