### ISSUE TITLE
Regression: Countdown time change is no longer taken into account

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2747]
- Assure that you don't have any countdown in your OS
- now create a new countdown
- now edit this new countdown because you want to change its time from 1:00 to 5:00
- do  this change and press the blue button with the checkmark to save this

result: the time is still 1:00 not the 5:00 you set

- edit the countdown again and you can see that the 5:00 is there

This is a regression bug.

**Comment by emanuelschuetze** [comment]
> result: the time is still 1:00 not the 5:00 you set

Confirmed. Now you have to click the "Stop" button. The time is reset to 5:00.

Yes, we should reset it automatically after pressing blue save button.
@FinnStutzenstein Please fix it if you have time...

**Comment by FinnStutzenstein** [comment]
closed with PR #2751 .

**Comment by donovaly** [comment]
Confirmed fixed, Many thanks Finn for all your great work in fixing!
