### ISSUE TITLE
Incosistent time handling in agenda import/export

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2748]
OS offers an example CSV file to see how agenda entries are added to a CSV import file. This file uses the format "hh:mm" for the duration. So let's test it:

- download the offered CSV example file
- use this file for an import
- now export the resulting agenda

result: in the exported CSV the duration has the format "mm". This is inconsistent and confusing although the exported file can be used for another import.

To be consistent either the format "hh:mm" or "mm" should be used for import and export.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Let us use always "hh:mm". Can you change it in csv export please?

**Comment by donovaly** [comment]
The time issue is now fixed, but a dataloss bug has been introduced, see #2954.
