### ISSUE TITLE
Wrong sorting by 'assignment.assignment_related_users.length'

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2750]
Splitted out from [#2742](https://github.com/OpenSlides/OpenSlides/pull/2742/files#diff-743ecf6da36e2c2e458d718572e809e1):

I changed the sort field `open_posts` to `assignment.assignment_related_users.length` (= number of candidates). But the sorting by this number is not correct.

@FinnStutzenstein Do you know whats wrong here?

**Comment by FinnStutzenstein** [comment]
Note for myself: Why there is an `assignment` (is it really `assignment.assignment.assignment_related_users`)? Does `assignment_related_users.length` work?

**Comment by emanuelschuetze** [comment]
> Does assignment_related_users.length work?

Yes, I'll make a pull request.
