### ISSUE TITLE
More options for select mode

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2754]
Motions:

- [x] set status
- [x] set category
- [x] set motionblock

Users:
- [x] set/unset is_active
- [x] set/unset is_present
- [x] set/unset is_committee

**Comment by FinnStutzenstein** [comment]
Closed with PR #2801

**Comment by donovaly** [comment]
This bug has the wrong milestone. It is fixed for 2.1 and should therefore have the 2.1 milestone, not the 2.2 milestone.
