### ISSUE TITLE
Feature: Create custom workflows on client site

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2758]
Needs discussion:

Whats about a new list view with the ability to create new and edit existing workflows? Technically each workflow is a network graph with the states in the nodes. I came across [VisJs](http://visjs.org/index.html) which seems to manage the graphs very well. Especially the [editing example](http://visjs.org/examples/network/other/manipulation.html) is exactly the mode we need to create custom graphs. For assemblies with a strict regulations how to name states or have special workflows that doesn't match the default ones this would be helpful.

@emanuelschuetze @normanjaeckel @ostcar Whats your opinion about this possible feature?

**Comment by emanuelschuetze** [comment]
Already done in 2.3
