### ISSUE TITLE
Proposal for temporary solution for startup process

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2775]
What do you think about:
1. We create a full width overlay with the text "Please wait ...".
2. After successful login this overlay is activated.
3. In the background we do **not** set the operator but we fire the window.location.replace command immendiatelly.
4. After successful whoami response (which contains the user and the group) the overlay is disabled.
5. The operator does not fire find requests any more. We ensure that the user is there by whoami response.

**Comment by emanuelschuetze** [comment]
see #2854
