### ISSUE TITLE
PDF formatting problems

### ISSUE THREAD

**Issue by CatoTH** [OpenSlides/OpenSlides#2777]
Currently, there seem to be some problems with formattings in the PDF-Export, probably a follow-up to https://github.com/OpenSlides/OpenSlides/issues/2576 .
For example, STRONG text does not appear as bold anymore, and (numbered) line breaks within STRONG-tags are removed.

An example can be seen in the "converts a simple html string" test case in pdf.service.test.js, which fails probably after https://github.com/OpenSlides/OpenSlides/commit/b1f4def7430f17bd376af718f4373369b61482d9.

**Comment by emanuelschuetze** [comment]
I found an other problem with line numbers, reported in #2776:

If you create a motion pdf with outside line numbers the line numbers are displayed only in the first line of each paragraph. The other line numbers are missing. Example:

```
1 foo foo foo
  foo foo foo
  foo foo foo

4 bar bar bar
  bar bar bar
  bar bar bar
```

**Comment by CatoTH** [comment]
@emanuelschuetze Can you please check if your problems are solved by https://github.com/OpenSlides/OpenSlides/pull/2795 ?
If not, could you please provide me with the exact HTML so I can test it (and write test cases for these cases)?
