### ISSUE TITLE
Improve relation to agenda item.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2779]
At the moment we often send two single autoupdate messages if a agenda related instance is created or changed. These blobs should be bundle together to improve performance for the websocket handler (daphne).

**Comment by normanjaeckel** [comment]
At the moment I do not have any idea how to solve this without much effort.

**Comment by normanjaeckel** [comment]
Maybe we use a django middleware here. Or something like [this](https://github.com/django/channels/blob/69c59ee8b4924cd346e0a2b1724979375ad9924c/channels/message.py#L66).

**Comment by FinnStutzenstein** [comment]
More from PR #2886 : If one creates a new object the client waits until it's created and then modified the coupled agenda item. This could be done on server side.

**Comment by emanuelschuetze** [comment]
@normanjaeckel I think we can close this issue because #3341 is merged, right?
