### ISSUE TITLE
String name conflict for agenda items

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2780]
In the agenda list the items that should not be part of the official item list are now marked as "Internal entry".

In contrary when using a CSV file, one needs to specify the property "is_hidden". On importing OS also tells you that this property means "is hidden". But after accepting the import one sees no longer a property called "hidden".

Since it cost me some time to understand that hidden = internal others might have the same problems. To avoid these confusion the property "is_hidden" in the CSV file and the import preview should be renamed to "is_internal". Then we are consistent.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein will improve the csv import that you can use a custom (translateable) csv header row. Then we can resolve the name conflict by using "internal" also in csv file.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Closed.

**Comment by donovaly** [comment]
Confirmed, thanks for fixing.
