### ISSUE TITLE
Table handling in motions: line numbering, display and complicated tables

### ISSUE THREAD

**Issue by mkrambach** [OpenSlides/OpenSlides#2784]
As of merge of PR #2720, table handling has some issues left.
If I disallow tables on ckeditor, the table's content will just be written as plain text in the order sent by the copy/paste (mostly top-down, left-right). If I allow it (current state), the tables will be inserted as html table, 
but with remaining issues:

- More complicated tables are not supported yet (multirow, multicol, ...)
- Display: depending on the mode, tables can look very ugly. This should mostly be a css design thing.
- Line numbering: each `<td>` currently gets an own line, which is not correct. I'm not entirely sure how to properly handle it, though (as a td could get several lines long inside a single "row").

**Comment by normanjaeckel** [comment]
Please check whether this is an issue for 2.1

**Comment by emanuelschuetze** [comment]
moved to 2.2

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Is this still a thing?
