### ISSUE TITLE
Move CKEDITOR_BASEPATH into openslides-libs.js

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2787]
Splitted out from #2720:
Move the following line from index.html at the beginning of openslides-libs.js (have to set before ckeditor.js is loaded):
```
<script>
  window.CKEDITOR_BASEPATH = '/static/ckeditor/';
</script>
```

**Comment by matakuka** [comment]
That commit 4268a44 is not a solution, it was merely an experiment which did not work.

**Comment by emanuelschuetze** [comment]
Suggestion: add this line with gulp at the beginning of openslides-libs.js.

@flanagan Can you try this?
