### ISSUE TITLE
regression: parsing issues for style attributes in PDF

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2811]
Since [this commit](https://github.com/OpenSlides/OpenSlides/pull/2795/commits/159720b98392389eea455f5a8b28803493c731bc) by @CatoTH  an old bug appears again that was previously fixed in [this pull request](https://github.com/OpenSlides/OpenSlides/pull/2744).

the issue was briefly describes by @emanuelschuetze like the following (from [this issue](https://github.com/OpenSlides/OpenSlides/issues/2576))

```
create motion pdf without line numbers
=> Failure 1: the full paragraph is filled with background color!
```

meaning the following:
this declaration in motion
![bildschirmfoto von 2017-01-04 14-57-18](https://cloud.githubusercontent.com/assets/10233032/21644569/534dcff0-d28e-11e6-9345-f6213cfb0295.png)

now _again_ results in this PDF content

![bildschirmfoto von 2017-01-04 14-59-23](https://cloud.githubusercontent.com/assets/10233032/21644592/771b0056-d28e-11e6-9154-fda7de1ecc34.png)

The marked line [here](https://github.com/OpenSlides/OpenSlides/pull/2795/commits/159720b98392389eea455f5a8b28803493c731bc#diff-54e2f27cb7e6355c91d8e0238305d932R747) is causing this issue, since _parsing does not stop_. Next time, pleast do not just revert changes in order to fix issues.

**Comment by normanjaeckel** [comment]
What about adding the karma tests to our Travis CI?

**Comment by emanuelschuetze** [comment]
@tsiegleauq This issue is still valid in current master.

**Comment by emanuelschuetze** [comment]
Same error was reported by @donovaly in #3059 . There was also an other styling bug in attached example pdf: 
* Strike through a word -> word is still in normal style in pdf.

**Comment by tsiegleauq** [comment]
> Strike through a word -> word is still in normal style in pdf.

did this just reappear? Striking through worked in last weeks master.

**Comment by emanuelschuetze** [comment]
@tsiegleauq Please retest today with current master.

**Comment by tsiegleauq** [comment]
nevermind, I'd mistaken the strike through with the cancel function in change recommendation. Did not test real strike through for a while tho.

**Comment by emanuelschuetze** [comment]
@tsiegleauq ping, please fix this issue tomorrow.

**Comment by donovaly** [comment]
Confirmed fixed, many thanks.
