### ISSUE TITLE
Inmemory cache does not save all data

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2828]
I have 2002 users in my database. If I start the server with inmemory cache and guest enabled and run `time curl localhost:8000/rest/users/user/`, I have to wait for about 11 or 12 secs. Before the first run in utils/collection.py line 317 I run `print(len(missing_ids))` and got 2002. A second run returns about 1790.

I do not know why my users aren't saved to the cache after the first run.

@ostcar Can you reproduce this?

**Comment by ostcar** [comment]
It was really hard to reproduce it. I used the current master with a fresh settings and fresh db and updated all requirments. First I ran into this one, so I switched to postgres: https://github.com/OpenSlides/OpenSlides/issues/2812 

This I ran into this one: #2829, so I installed the current version of twisted

Then I could reproduce you error and find the django config value MAX_ENTRIES: https://docs.djangoproject.com/en/1.10/topics/cache/#cache-arguments

You can set this to a higher value in our config. But I would not recommend it. the inmemory cache is not build for big assemblies. If you have an assembly with 2000 users, then you should use the big mode with the redis cache.

**Comment by normanjaeckel** [comment]
Ok. This needs discussion. What should be our default for small assemblies. I can imagine an assembly with only some managers and no active participants (Präsentationsmodus) but with 200 motions and 200 imported participants. The the cache should be able to handle this. What is the disadvantage of a high MAX_ENTRIES number? (Of course assemblies with more than 20 active users should use the big mode, that is not the question. Or do we also recommend the big mode for events with more database objects?)

**Comment by ostcar** [comment]
I have no interest in discussing this. I think the real discussion is, if we can make redis an hard requirement. If we do so, then this issue can be closed.

the inmemory cache is a python dict. So the only problem with a big mx_entries seems to be, that it will use more memory. max_entries is a feature that will removed old cache values and keeping the needed memory at a fix state.

**Comment by normanjaeckel** [comment]
Ok. An itermediate solution would be to increase the number to a realitic value for small assemblies with medium amount of data: 1000 entries per app -> 10000 objects are no problem for memory I think.

**Comment by emanuelschuetze** [comment]
Ok, I'll set it to 10000.
