### ISSUE TITLE
Fix double save_to_cache() call

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2835]
[Here](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/utils/collection.py#L190) we call save_to_cache but this call is not necessary if the element was initialized with from_instance. But if it was initialized with from_values it is necessary. How can we solve this circular problem?

**Comment by ostcar** [comment]
I don't think, that we have to solve this in the 2.1 release. Even when save_to_cache is called twice, it will be only some ms slower.

**Comment by donovaly** [comment]
This bug has the wrong milestone. It is fixed for 2.1 and should therefore have the 2.1 milestone, not the 2.2 milestone.
