### ISSUE TITLE
user without permission can execute funktion where servers says no

### ISSUE THREAD

**Issue by flanagan** [OpenSlides/OpenSlides#2849]
Deligate user can see and execute a function but has no right to execute it.
He should't even see it.

@normanjaeckel 

![2017-01-14-102743_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1702162/21953931/8bab63ea-da44-11e6-9604-410e05686ce9.png)

**Comment by FinnStutzenstein** [comment]
@flanagan can be closed; please reload the page. There is currently no watcher watching the permission changes. I'll create an issue.

**Comment by flanagan** [comment]
done
