### ISSUE TITLE
Watch permission changes on client side

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2851]
If an admin change a permission the DOM tree (os-perms, ...) should update directly and show/hide elements that are connected with the permission.

Example: Delegate views an election; admin removes 'can_nominate_himself' --> 'Add me' button should disappear.

**Comment by normanjaeckel** [comment]
See #1855

**Comment by emanuelschuetze** [comment]
this is a duplicate of #1855, closed.
