### ISSUE TITLE
Remove OPTION request for assignment phases.

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2885]
same as #2862 . See [this function](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/assignments/static/js/assignments/base.js#L319). This is called within some assignment resolvers.

**Comment by donovaly** [comment]
This bug has the wrong milestone. It is fixed for 2.1 and should therefore have the 2.1 milestone, not the 2.2 milestone.
