### ISSUE TITLE
Small template changes on the fly

### ISSUE THREAD

**Issue by maweki** [OpenSlides/OpenSlides#2887]
Hi,
I am currently running 2.0 in a virtualenv (`~/OpenSlides/venv`) and there are a few tiny issues I need to fix. I want to look into fixing bugs in master as well but my event is on Saturday and I just want to get this single thing working.

I changed `agenda/static/templates/agenda/slide-list-of-speakers.html` in `~/OpenSlides/venv/lib64/python3.5/site-packages/openslides` and restarted `openslides` but the template in the browser does not change. Am I missing something?

**Comment by normanjaeckel** [comment]
Hm. I would expect that the template changes. Did you clean your browser cache? Please have a look at the browser dev tool console (press F12) (network tab) and see what network connections run. Have a look whether your new template file is loaded (HTTP 200 and not HTTP 304). Please ping me here if it does not work.

**Comment by emanuelschuetze** [comment]
I tested it successfully with a 2.0 installation on linux (with virtualenv). You changed the right file. After reload everything is fine (changed). So look like you have not clean your browser cache!

BTW: I would recommend to use a fresh git checkout of OpenSlides-master which has a lot of improvements. Advantage: You can manage your personal changes with git.

**Comment by emanuelschuetze** [comment]
Please reopen if you need more help.
