### ISSUE TITLE
Support multible events in one instance

### ISSUE THREAD

**Issue by Apfelkuchen91** [OpenSlides/OpenSlides#2889]
It would be very helpful, when I can use OpenSlides in one instance for more than one event.

As an example:
- https://demo.openslides.org/event1
- https://demo.openslides.org/event2
- https://demo.openslides.org/event3

So the admin must only setup one instance with the corporate template and in each meeting can OpenSildes be used.

**Comment by emanuelschuetze** [comment]
For this use case we created the OpenSlides multiinstance application where you can manage multiple instances:
https://github.com/OpenSlides/openslides-multiinstance-backend
https://github.com/OpenSlides/openslides-multiinstance-app

Each OpenSlides instance hat its own database with agenda/participants/motions/etc. OpenSlides itself will not support multi instances.  Hope this helps.
