### ISSUE TITLE
Error 'Unknown provider' for 'edit profile' and 'change password' view

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2892]
Open 'edit profile' view:
* Unknown provider: userProvider <- user <- UserPasswordCtrl <- UserProfileCtrl

Open 'change password' view:
* Unknown provider: userProvider <- user <- UserPasswordCtrl

**Comment by normanjaeckel** [comment]
This has to do with the removement of the resolvers.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze I can not recreate this. In current master I can see and use the change password and edit view without any issues.

**Comment by emanuelschuetze** [comment]
I can still reproduce both errors with current master.

**Comment by FinnStutzenstein** [comment]
can you make a screenshot of the error and the code line where this happens?

**Comment by FinnStutzenstein** [comment]
Ah, sorry my mistake. I'll fix this with the resolver PR.
