### ISSUE TITLE
Hide 'Show as agenda item' in create dialogs if user has not the right permission

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2894]
If the user has no `agenda.can_manage` permission this option is useless, because the user has no permission to change this.

Discussion: Now the default is that everything is on create time an internal item. Does this make sense or should it be always a real agenda item?

**Comment by emanuelschuetze** [comment]
Right, we have to hide the "Show as agenda item" in motion and assignment form.

The default (internal item) is ok because it's the safest option.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze I checked this. The user needs `agenda.can_see agenda.can_see_hidden_items agenda.can_manage`. I think this are too much permissions needed to set this. A simple `can_manage` should be enough, or not?

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Yes, 'agenda.can_manage' should be enough to see this checkbox.
