### ISSUE TITLE
Logout after password change

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2897]
If you change your password and reload the page, you have to relogin.

**Comment by FinnStutzenstein** [comment]
When sending the password change request to /rest/users/set_password everything is ok.
The next request (for instance clicking on a project button) will be rejected with 403 - forbidden. The interesting thing is the OpenSlidesSessionID-Cookie: It is included in the second request, but the response header is:
```
Set-Cookie: OpenSlidesSessionID=""; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/
```
So the session handling on the server is broken. I think the session id changes with the password change, so the password is part of the session id creation.
@ostcar Do you have an idea with the sessions?

**Comment by FinnStutzenstein** [comment]
Ok, I looked in the django implementation. See [this](https://github.com/django/django/blob/f3c43ad1fd9556f0fd026a5dfa93c67a5cf186ca/django/contrib/auth/base_user.py#L134) line. The session key is generated with the password. If the password changes, the session id changes too. I think we have three possibilities:

1. Override the session key generation not to use the password
2. when processing the set_password request, change the sessionid from the user
3. force a reload on client and the user has to relogin

**Comment by FinnStutzenstein** [comment]
Another question: Why do we have a custom [AuthenticationMiddleware](https://github.com/OpenSlides/OpenSlides/blob/4b03a7ad5b3a7b5af66118f332b9f03bf86d1e93/openslides/utils/auth.py#L75) if it is not enabled in the global settings?

**Comment by ostcar** [comment]
Our AuthenticationMiddleware was removed from @normanjaeckel in this commit: https://github.com/OpenSlides/OpenSlides/commit/d7936c53e3124b9c6d2dc0e56b8a5191c341ca31#diff-a8f854a332fc77a1ed965fc94d7925df

Maybe he can tell us why he did it. It is strange, that the code works at the moment. Now, ```request.user``` is always a DjangoAnonymousUser and not our AnonymousUser. If anything works fine with the DjangoAnonymousUser, then maybe we can remove our Sessions backend, AnonymousUsers and any function that we added for it?

For this issue I would prefer the solution 2. I don't like to change a django security feature and I also don't like a forced logout.

**Comment by normanjaeckel** [comment]
Why not just use `update_session_auth_hash` from django.contrib.auth on server side in the password change view?

I do not know why I changed the middleware settings. Maybe I thought that we do not have any problems with the anonymous user any more ... Just remove the old code.

**Comment by FinnStutzenstein** [comment]
With option two I thought exactly on @normanjaeckel proposal.
But why does the DjangoAnonymousUser has permissions when the check in `has_perm()` should return false?
I make a debug print giving me the permission string, user type and the result `has_perm`. When using the anonymous user (type: DjangoAnonymousUser) this function always return false but in the client the anonymous user have the permission of group 1. Something is broken and does not care about the result of `has_perm()`.

I tested a little bit:
- Anonymous enabled; one window as anonymous and one with the admin.
- The admin sees 15 agenda items; the anonymous none (he should see all).
- The admin toggles 'internal entry'. Now the anonymous gets an autoupdate and the item is in his list (always with correct internal entry state)

The permissions works somehow (Why??):
- The anonymous has no permissions for users. The list is empty (ok). Admin changes a user; No autoupdate for anonymous.
- The anonymous gains the users.can_see_names permission. Reload of client. Now the list is still empty, but with an autoupdate from admin, the list gets the changes entry (same as the agenda item)

Here, the permissions are broken:
- Changed the [access_permissions](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/access_permissions.py#L19) to always return false. So nobody has the permission to see motions. Anonymous as well as the admin have access.

@ostcar @emanuelschuetze Can you recreate all these things? If yes, there have to be something to fix...

**Comment by normanjaeckel** [comment]
Please retest with current master after #2909 is merged.
