### ISSUE TITLE
How to use the docker image?

### ISSUE THREAD

**Issue by nowrap** [OpenSlides/OpenSlides#2903]
hello!
i've installed the the OpenSlides docker container like this:
`docker pull openslides/openslides`

But i can't get it started. I tried:
`docker run -i -t  openslides/openslides`

But only a python shell is opening:
`Python 3.5.2 (default, Dec 16 2016, 03:12:14)`
`[GCC 4.9.2] on linux`
`Type "help", "copyright", "credits" or "license" for more information.`

I am not very familiar with docker or python. The README.rst doesn't mention the docker container.

Some commands i could get running in the shell, like:
`help()`
`help> modules`
`help> openslides` 

Maybe someone can point me in the right direction and/or update the README file ;)

**Comment by emanuelschuetze** [comment]
@boehlke You created the Dockerfile. Can you explain a bit the usage, please?

**Comment by boehlke** [comment]
Hello!

The docker image is work in progress because we are still working on the final production setup.
Right now, you need a supervisord.conf mounted in at /supervisord.conf and a directory containing settings.py mounted at /data

If you would like to work on the setup, I can go more into detail. Otherwise please wait one or two months until the Docker setup is production ready.

Cheers
André

**Comment by nowrap** [comment]
hello!
some more details would be great, like an example supervisord.conf. 
Can i use the settings.py from "openslides start --local-installation"?

**Comment by ximex** [comment]
@boehlke any updates here? Some infos about the `supervisord.conf` and `settings.py` would be great

**Comment by nowrap** [comment]
Any news on this case?

**Comment by cljk** [comment]
Building the image seems to fail also...?!

```
>docker build .
Sending build context to Docker daemon  47.71MB
Step 1/33 : FROM python:3.5
3.5: Pulling from library/python
ad74af05f5a2: Pull complete
2b032b8bbe8b: Pull complete
a9a5b35f6ead: Pull complete
3245b5a1c52c: Pull complete
032924b710ba: Pull complete
04553eee3384: Pull complete
7dec7cade174: Pull complete
3b0d7efc53f6: Pull complete
Digest: sha256:175d88a6c5a11f8df61a60a85d6aaef792eb0c5cfb30c45520f093bcf1fe8262
Status: Downloaded newer image for python:3.5
 ---> 56b15234ac1d
Step 2/33 : RUN apt-get -y update && apt-get -y upgrade
 ---> Running in 5a3de62bed7c
Ign http://security.debian.org jessie/updates InRelease
Ign http://security.debian.org jessie/updates Release.gpg
Ign http://security.debian.org jessie/updates Release
Get:1 http://security.debian.org jessie/updates/main amd64 Packages [537 kB]
Ign http://deb.debian.org jessie InRelease
Ign http://deb.debian.org jessie-updates InRelease
Ign http://deb.debian.org jessie Release.gpg
Ign http://deb.debian.org jessie-updates Release.gpg
Ign http://deb.debian.org jessie Release
Ign http://deb.debian.org jessie-updates Release
Get:2 http://deb.debian.org jessie/main amd64 Packages [9063 kB]
Get:3 http://deb.debian.org jessie-updates/main amd64 Packages [17.8 kB]
Fetched 9618 kB in 7s (1254 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 ---> faed26223fa4
Removing intermediate container 5a3de62bed7c
Step 3/33 : RUN apt-get install -y libpq-dev supervisor curl
 ---> Running in 75fc979e9c36
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version.
libpq-dev is already the newest version.
Suggested packages:
  python-distribute python-distribute-doc
The following NEW packages will be installed:
  python-meld3 python-pkg-resources supervisor
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 369 kB of archives.
After this operation, 1670 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  python-pkg-resources python-meld3 supervisor
E: There are problems and -y was used without --force-yes
The command '/bin/sh -c apt-get install -y libpq-dev supervisor curl' returned a non-zero code: 100
```

**Comment by emanuelschuetze** [comment]
As discussed with @boehlke he will create a docker-compose.yml for a stand alone OpenSlides instance in "big mode" which can be started directly. The setup of big mode is documented in [DEVELOPMENT.rst](https://github.com/OpenSlides/OpenSlides/blob/master/DEVELOPMENT.rst#openslides-in-big-mode).

**Comment by cljk** [comment]
Hint .... error in building image of Dockerfile lies in line 4 - you need to add `--allow-unauthenticated`.
```

FROM python:3.5
RUN apt-get -y update && apt-get -y upgrade

RUN apt-get install -y libpq-dev supervisor curl vim --allow-unauthenticated
```

But result of
```
docker build . -t openslides

docker run -i -t openslides
```
is the same

```
Python 3.5.4 (default, Oct 10 2017, 02:35:38) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```

**Comment by boehlke** [comment]
@cljk Thanks for this fix. Concerning your other issue (running the image): The image contains all required dependencies and builds the client assets, but does not contain a proper entrypoint. You can run the "small mode" using
```
  docker run -i -t openslides/openslides /app/manage.py start
```
You might want to mount the "personal_data" directory, for example
```
  mkdir /tmp/personal_data
  sudo chown 1000:1000 /tmp/personal_data
  docker run -i -t -v /tmp/personal_data:/app/personal_data -p 8000:8000 openslides/openslides  /app/manage.py start
```
--> goto http://localhost:8000

The chown is required because the openslides user in the container has that ID.

**Comment by jsaalfeld** [comment]
Since today we got a repository that takes care of starting OpenSlides in a virtualized environment:

https://github.com/OpenSlides/openslides-docker
