### ISSUE TITLE
Reset config value gets JS error

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2919]
Clicking "Reset" button for a config option gets JS error:
 
`Error: "id" must be a string or a number!`

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Please retest. Should be fixed with PR #2918 . (Or should I say I didn't get this error there and fixed the CKEditor error)

**Comment by emanuelschuetze** [comment]
Retested: No error. So fixed. Thanks.
