### ISSUE TITLE
CKEditor in config: Cannot read property 'isInline' of null

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#2921]
If you have an editor open in Config and change into another app, you will get this error.

Changing state from a motion with active inline editing to another state works; @matakuka Do you know, if the editor become disabled if you leave a motion? Did someone implements this already?

**Comment by matakuka** [comment]
Sorry, this issue escaped my attention; I will look into it now.

**Comment by matakuka** [comment]
I could not reproduce it yet, and I do not have much of an idea what might be the cause of this.

**Comment by FinnStutzenstein** [comment]
Could someone else reproduce this? I'm using chromium on Ubuntu 16.04 LTS? Until now it seems to be a bug that only happens on my machine. (tested also with FF, no errors)

**Comment by emanuelschuetze** [comment]
I can reproduce the error:
* create new motion
* open motion detail view
* activate and deactdivate inline editing mode
=> Error
```
Uncaught TypeError: Cannot read property 'isInline' of null
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.focusManager.f (ckeditor.js:227)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.focusManager.<anonymous> (ckeditor.js:228)
    at ckeditor.js:29
```

@matakuka Can you reproduce it?

**Comment by matakuka** [comment]
Strange, I cannot reproduce it with @emanuelschuetze s example, not on Firefox nor Chromium.
I am suspecting this is due to some version mismatch in some libraries.

**Comment by matakuka** [comment]
After a completely clean install of node_modules and all bower components I am getting this error, too.

**Comment by matakuka** [comment]
With a new install, the requirement `"ckeditor": "~4.6.1"` pulls ckeditor 4.6.2, with the error.

If I have or require exactly ckeditor 4.6.1, I do not have this error.

@emanuelschuetze , @FinnStutzenstein : Does it affect us in more ways than an annoying console error? If not, I'll postpone the debugging and/or filing a bug report to ckeditor for later

**Comment by matakuka** [comment]
And here is the bug report for it: https://dev.ckeditor.com/ticket/16825.

We could either try the workaround, or keep ckeditor at 4.6.1.

As there apparently are no security changes nor features we need in the 4.6.2 version, I prefer keeping the version 4.6.1 version.
