### ISSUE TITLE
Regression: No Header, Footer or Table Style in generated PDF

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2923]
Due to [this pull request](https://github.com/OpenSlides/OpenSlides/pull/2917), PDF documents no longer contain Headers, Footers nor Table styles.

PDF in Master is now **unstable**
why has this Pull request even been approved in the first place?

@emanuelschuetze @normanjaeckel @FinnStutzenstein

**Comment by FinnStutzenstein** [comment]
Do you know whether the elements are just lists/dicts or are they evaluated as a function during the  pdfMake.createPdf()?

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein header and footer are functions. Maybe they are not useable after convert to JSON?

**Comment by FinnStutzenstein** [comment]
> JSON ist eine Syntax für das Serialisieren von Objekten, Arrays, Nummern, Strings, Booleanen und null. 
([from MDN](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/JSON))

So functions are just deleted from the object.
Is it possible to evaluate the functions before passing to the worker? Whats about the tables?

**Comment by tsiegleauq** [comment]
for easier access we have functions that returns the code for the header and the footer

See [here for the footer]([url](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/core/static/js/core/pdf.js#L200)) and [here for the header](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/core/static/js/core/pdf.js#L164)

Everything is always jusrt JSON.

The overall PDF document is also nothing but plain old JSON before generation. Basically it works like shown [here](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/core/static/js/core/pdf.js#L212) (just ignore the styles, this is pretty verbose)

To make this more abstact, the basic content looks kind of like this

```
pdfDoc = {
    pageSize: 'A4',
    pageMargins: [80, 90, 80, 60],
    header: header(),
    footer:(),
    content: content(),
}
```
