### ISSUE TITLE
Nicer error messages, if the server is down

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#2949]
For example: 

1. Start openslides
2. login as admin
3. go to the "overlay" to cretae a new user.
4. stop openslides
5. click on save.

Only a red par appears with no text at all

**Comment by FinnStutzenstein** [comment]
In almost every update/edit/create controller we have [this code for error messages](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/js/motions/site.js#L1353). We've to stay DRY; make a factory out of it (e.g. `ErrorMessage`) and make the error message nicer in there.

Additionally: Catch the error if the websocket connection fails. Then show some kind of hint that the user isn't connected anymore.

@emanuelschuetze If there is enough time before 2.1 I'll do this.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Ok, please try it for 2.1.
