### ISSUE TITLE
missing translation in motion state sorting

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#2955]
- use German menus
 - go to the motion list
 - click on "Status"

result: The string "review" is in English:
![localhost 8000 2017-02-14 01-10-42](https://cloud.githubusercontent.com/assets/1828501/22909158/c58dd086-f252-11e6-8112-d4457dcf59ff.png)

it should be "Benötigt Überprüfung"

**Comment by emanuelschuetze** [comment]
I fixed it in transifex and I'll update it with next German translation file update. 

@donovaly Please change it also in OpenSlides manual, if required. Thanks.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Could this be closed?

**Comment by emanuelschuetze** [comment]
@donovaly We still wait for your ok here. Can you please test the new translation and check if we need a new screenshot in manual?

**Comment by emanuelschuetze** [comment]
@donovaly ping: Do you have updated this in manual? Can we close this?

**Comment by donovaly** [comment]
> @donovaly We still wait for your ok here. Can you please test the new translation and check if we need a new screenshot in manual?

I use beta 3 and cannot see any change before I get beta 4.
However this string is not references in the manuals and no screenshot update is necessary.

**Comment by donovaly** [comment]
> Can we close this?

Not yet because now there are inconsistencies:
![localhost 8000 2017-03-07 00-01-20](https://cloud.githubusercontent.com/assets/1828501/23634215/66ce0c64-02c9-11e7-8a73-f9eafc997827.png)
either all items in the list should begin with a small letter or not

**Comment by emanuelschuetze** [comment]
I changed "Benötigt Überprüfung" and "Verworfen" in Transifex. "Erledigt" can not changed because we use the same string (with capital) also in other views (e.g. agenda list view) were we need the capital. But I think, it's not bad that this special string begins with capital. So fixed.

**Comment by normanjaeckel** [comment]
I have to check something here.

**Comment by emanuelschuetze** [comment]
As discussed with @normanjaeckel 
We change "Done" to "done" in motion list view only.

**Comment by donovaly** [comment]
Confirmed fixed.
