### ISSUE TITLE
Send only data to client which user is allowed to see

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2956]
* Create some data (agenda items, motions, assignments, users, mediafiles).
* Create a new group (keep all permissions deactivated)
* Create a new user and add the new group.
* Login as this new user in a new (private) tab.
* Now go to search view (enter '/search/' or click on search button in navigation bar)
* Enter a blank " ".

=> motions, users and mediafiles are visible!!! But user cannot open detail view of these search entries. 

@normanjaeckel Any idea why not agenda items and assignments?

This is a serious security issue!

**Comment by normanjaeckel** [comment]
As discussed check motion and mediafile access_permissions.py:get_restricted_data. Users should already work.
