### ISSUE TITLE
Autoupdate problem after changing permissions

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2957]
* Create a new group (keep all permissions deactivated)
* Create a new user and add the new group.
* Login as this new user in a new (private) tab.
* Now activate (as admin) the following permissions and observe the UI
  of the user tab:

* [x] a) activate 'agenda.can_see' -> no agenda items visible in list, reload required.
* [x] b) activate 'agenda.can_see_internal_items' -> no internal items visible in list, reload required.
* [x] c) activate 'motions.can_see' -> no motions in list, reload required.
And a lot of JS errors: `TypeError: Cannot read property 'allow_submitter_edit' of undefined`
* [x] d) activate 'assignments.can_see' -> no assignments visible in list, reload required!
* [x] e) activate 'mediafiles.can_see_hidden' -> no hidden files visible in list,
   reload required!
* [x] f) activate 'users.can_see' -> only one user (me), no other users visible in list,
   reload required!

**Comment by FinnStutzenstein** [comment]
What's missing: When a group gains a base (`can_see`) permission, they need to get all data for the app.

On the server we have to watch for changes in any groups permissions. If a group gains a base permission, we have to send all app data to users of this group. The easiest way to get the data is the `get_startup_data` from every app.

@normanjaeckel Where is the best place to watch the changed permissions on the server?

**Comment by normanjaeckel** [comment]
Permissions can only change when a user becomes member of a new group (or is removed from the group) or when a group gets more or less permissions. So something like a permission change signal may be fired in these two views. Then all apps may describe an receiver that fires inform_changed_data for specific changed permissions. This receiver can be connected to the signal somewhere in apps.py. That's one solution. Another is that the receivers only return objects and that the group viewset fires them together with the changed group.

**Comment by emanuelschuetze** [comment]
Fixed with #2995
