### ISSUE TITLE
Empty line-number span-tag after adding change recommendation

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2961]
After one added a new change recommendation, an empty `<span>`-tag with valid line-number information is generated, which will result in an "empty-but-numbered" line during PDF-generation.

to give a brief example:
This motion...
![bildschirmfoto von 2017-02-15 12-42-03](https://cloud.githubusercontent.com/assets/10233032/22973120/0500c338-f37d-11e6-83ea-716f37a3f1a9.png)

gonna have this html sourcecode:
(there are 2 span tags which is an error)

![bildschirmfoto von 2017-02-15 12-43-35](https://cloud.githubusercontent.com/assets/10233032/22973135/138c0ad4-f37d-11e6-8373-b8a9ffc54290.png)

gonna (correctly) result in this PDF-content:

![bildschirmfoto von 2017-02-15 12-41-31](https://cloud.githubusercontent.com/assets/10233032/22973149/25d6db42-f37d-11e6-9387-283c8a733898.png)

(the empty-but-numbered line is number 4 is displayed correctly)

Alter the change recommendation generation, so no empty HTML lines are generated anymore.

@emanuelschuetze : as dicussed earlier

@CatoTH : probably an issue for you?
I gonna look into the code and provide as much information as possible in this issue.

**Comment by tsiegleauq** [comment]
It seems like there are some leftovers which not get deleted after the algorithm in die diff.js is finished. Seems like we try to renew / replace some oldHTML and newHTML and do not clean up the old HTML information. Code seems little woolly tho.

[diff.js](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/js/motions/diff.js)

**Comment by emanuelschuetze** [comment]
Fixed in #2969
