### ISSUE TITLE
Clearing chat messages produces console error

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2965]
Add some chat messages and then clear them. We get a console error and an unclear behavior in other clients concerning the bagde with the number of currently unread messages. Proposal: The badge should be set to zero and disappear.

**Comment by emanuelschuetze** [comment]
Confirmed. The JS error is `TypeError: Cannot read property 'id' of undefined`.
Your proposal is ok for me but has a low priority for 2.1.
