### ISSUE TITLE
Create generic method to change collection name to camel case on client side

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2983]
See discussion in #2973. The `formName.charAt(0).toUpperCase() + formName.slice(1) + 'Form'` lines and the so called hotfixes have to be refactored.

**Comment by emanuelschuetze** [comment]
I think this JS error should handle in this issue:
Open list of speakers (item detail) view of a motion block. Click "back to motion block" button:
`Error: Could not resolve 'motions.motion-block.detail' from state 'agenda.item.detail'`
