### ISSUE TITLE
Do not allow users to update some fields of themselves.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#2984]
At the moment any user can update himself and then change more than just his name. We have to restrict this. See #2973.

**Comment by FinnStutzenstein** [comment]
Coupled with issue #1871 . Is this possible to fix for 2.1?

**Comment by emanuelschuetze** [comment]
As discussed with @normanjaeckel 
Normal user should be allowed to update username and about me only.
@normanjaeckel Please add your commit to #3001.

**Comment by emanuelschuetze** [comment]
Done with #3001
