### ISSUE TITLE
Motion: Diff HTML code ordered wrong

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2997]
The following Motion:

![bildschirmfoto von 2017-02-22 10-54-20](https://cloud.githubusercontent.com/assets/10233032/23206338/8e5793da-f8ed-11e6-94c0-a1404e5f03e9.png)

results in the following HTML code:
![bildschirmfoto von 2017-02-22 10-49-25](https://cloud.githubusercontent.com/assets/10233032/23206353/99f0ce96-f8ed-11e6-807f-c8b521a423eb.png)

The line
`<ins> hierbei und </ins>`

should **rather be _inside_** the 
`<span class = .... > ... </span>`

The reason for this: During PDF generation we interpret both `<p>` and `<span>` as a paragraph.

Meaning, the resulting PDF would look like the following:

![bildschirmfoto von 2017-02-22 10-48-59](https://cloud.githubusercontent.com/assets/10233032/23206531/41189672-f8ee-11e6-8d0a-7dcd79d59666.png)

This usually happens when you make an "insertion" in the end of a line.

@emanuelschuetze 
@CatoTH 
I did send you the database over E-Mail last week

**Comment by tsiegleauq** [comment]
Addition: This happens if you use the change-function and alter the beginning of the line.

**Comment by CatoTH** [comment]
Could you please check if this is fixed by #3026?

**Comment by emanuelschuetze** [comment]
Successfully tested with #3026.

**Comment by emanuelschuetze** [comment]
Fixed in master now.
