### ISSUE TITLE
Motion: CKEditor creates too many P-Tags

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#2998]
After editing some diff content, the CKEditor creates too many `p` tags.
the results are inconsistent views in both motion, projection (/projector) view and PDF.

We need to alter ChangeRecommencationCreateCtrl (site.js#1358)

@emanuelschuetze - as discussed, please assign me to this issue.

**Comment by tsiegleauq** [comment]
That looks like a server sided issue. We probably need to create a difference "`def create(...)`" function inside the motions views.py in the "MotionChangeRecommendationViewSet" class.
basically, we have to parse the `<p>` tags out.

I struggle to create my own "create" function, since I never learned how to _django for OS_ properly.
I'd take over this again next week if nothing else happens here.

* make create function MotionChangeRecommendationViewSet
* re-parse motion-object
* validate the HTML code after a change recommendation

**Comment by emanuelschuetze** [comment]
Fixed with #3132
