### ISSUE TITLE
User without 'agenda.can_see_hidden_items' cannot open list of speakers view of (hidden) motion

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3003]
To reproduce:
* Create new (empty) group with persmissions "motions.can_see" and "agenda.can_see"
* Create new user and add this new group to user.
* Create new motion.
* Login as user and go to motion detail view.
* Click on "list of speakers" button
=> Failed with "Cannot read property 'id' of undefined" (because the related agenda item is hidden).

Expected: User can see the motion and the agenda, so he should also allowed to see the list of speakers view of this motion.

Is there a possibility to show the list of speakers of such related (hidden) agenda items - also if user has no permission to see hidden items in agenda? A user cannot understand why he can see the motion but not the hidden agenda item of the motion (with its list of speakers view).

**Comment by FinnStutzenstein** [comment]
Proposal: new permission `agenda.can_see_list_of_speakers`: With this permission a user can always see the list of speakers (of every item) but is not allowed to see the agenda (if no `can_see`/`can_see_hidden`)

Opinions?

**Comment by emanuelschuetze** [comment]
As dicussed with @normanjaeckel :
We want to show list of speakers if `agenda.can_see` is active. Then also for (hidden) motions the item detail view is allowed to see. Then we don't need a new permission `can_see_list_of_speakers`.
