### ISSUE TITLE
Scroll projector to a given line

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3010]
see #3008 (PR) and #2636 (Issue)

**Comment by FinnStutzenstein** [comment]
@normanjaeckel I have an idea how to solve this issue: With notify, the client can send a request to the one projector to scroll to query the position. The Projector responds and the client post a request to /set_scroll/. For this we need to pass notifies to projectors, like we do this for users. Can you implement this?

**Comment by normanjaeckel** [comment]
Hm. But which projector should be called if we have more than one?

**Comment by FinnStutzenstein** [comment]
There is just one projector, where the motion can be projected. If e.g. in two tabs the projector is open, the client gets 2 responses, so we will take the first one coming, because the projector should always give the same answer, because it should display the motion always the same.

**Comment by normanjaeckel** [comment]
So you mean that if we have 1 manager that clicks on "highlight and scroll to line xy", this client sends the message to all of the 3000 projector clients that are open at the moment. Then it receives 3000 answers and just handle the first one for the HTTP POST request 'set_scroll'. Right?

**Comment by FinnStutzenstein** [comment]
In this extreme situation, yes. The server may send this request just to one projector, because we know that all projectors (with the same id) are equal..

**Comment by FinnStutzenstein** [comment]
@normanjaeckel What is about this proposal?
https://github.com/FinnStutzenstein/OpenSlides/tree/scrollProjectorToLine

**Comment by normanjaeckel** [comment]
Hm. And what if no projector is active at the moment? The callback remains registered and is triggered if later someone opens a projector and hits the button again ...

I feel that this way is somehow hacky ... but I am not completely against it.

**Comment by FinnStutzenstein** [comment]
We should merge this into the master. It's hacky, yes, but better then nothing. We can change the implementation, if we find a better solution.

**Comment by normanjaeckel** [comment]
Should be fixed with OpenSlides 3. Just ensure that that projectors do not ask each other about the scroll heigth.

**Comment by jsaalfeld** [comment]
As @normanjaeckel this should be fixed.
