### ISSUE TITLE
Use Yarn instead of npm

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#3012]
We should evaluate switching to [Yarn](https://yarnpkg.com/lang/en/) and stop using npm. See [this announcement](https://code.facebook.com/posts/1840075619545360) to understand some issues.

@FinnStutzenstein Are you interested in looking at this (if you have some free time after 2.1 release)?

**Comment by FinnStutzenstein** [comment]
I did  some further reading and yes, we should try using it. We are allowed then to avoid the issues with npm as well as (hopefully) reduce the deps (currently I have 469 folders in my node_modules). But we should wait until 2.1 is released.
