### ISSUE TITLE
MotionCreateCtrl sends illegal PUT request to agenda

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#3016]
Login as delegate and create a new motion. The client sends a PUT request to the agenda. The server sends 403 (which is correct in this case) but the client shouldn't try to send this request.

**Comment by FinnStutzenstein** [comment]
This is the same issue as #2779 . The client tries to modify the created agenda item, but it has to wait for the motion (and so the agenda item) to be created. If the agenda item is more coupled with the containing object, this should be done on server side.

**Comment by emanuelschuetze** [comment]
I moved this to 2.2 because #2779 has also 2.2 milestone.

**Comment by emanuelschuetze** [comment]
Already fixed.
