### ISSUE TITLE
button in election setup not completely visible

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3020]
- create a new election
- in the appearing window look at the field number of persons to be elected

result. the button to decrease the number is not completely visible:

![localhost 8000 2017-02-28 23-45-59](https://cloud.githubusercontent.com/assets/1828501/23438085/bcf4c762-fe10-11e6-88c4-804268b2a282.jpg)

(the top bar is missing)

**Comment by emanuelschuetze** [comment]
This up/down buttons are a feature of your browser. On Firefox and Chromium on Linux it looks good. We can't change it. 

=> won't fix / can't fix
