### ISSUE TITLE
OS does not respect necessary majority of elections

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3021]
- create a new election with one person to be elected
- select 2 candidates
- insert the result: one vote for every candidate

The election looks now like this:
![localhost 8000 2017-03-01 00-01-22](https://cloud.githubusercontent.com/assets/1828501/23438475/4bcb0da6-fe12-11e6-872d-cbf6eb8f7836.jpg)

So nobody reached the quorum. The bug is that OS allows you to mark a person as elected nevertheless that it violets the set necessary majority. In reality this could cause big troubles, just imagine an admin marks somebody accidentally as elected...

**Comment by emanuelschuetze** [comment]
For activate the elected checkbox it is technical not required to get an exact quorum, e.g. if you enter "-1" (majority) no quorum is calculated. 
I don't like to add more logic to catch this case. The "required majority" feature is just a assistence for the admin to decide if a candidate is elected. But the admin can always ignore such information and set it directly to is elected. Use case: The plenum elected a candidate via acclamation. No results are  logged but the elected candidate should be marked. This is possible now.

=> won't fix.

**Comment by donovaly** [comment]
OK, I'll add a sentence to the docs.
