### ISSUE TITLE
missing translation in text field footer line

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3023]
- use OS with german menus
- create e.g. a new participant

result: in the text field "Über mich" there are only english words in the footer line:
![localhost 8000 2017-03-01 00-37-13](https://cloud.githubusercontent.com/assets/1828501/23439557/7eeb38fa-fe17-11e6-8117-20de91842c60.jpg)
(body, p and strong)

Btw. what does "p" mean? i gues this means "paragraph", but if so, why is only the meaningless abbreviation"p" is used and why do the user need to know that it is a paragraph?

**Comment by emanuelschuetze** [comment]
The status line in the footer contains the HTML DOM structure of the entered text. This is just a technical information which can ignored from normal user.  But sometimes an admin wants to know the  nested html tags (e.g. to reduce the formatting which was copy&paste from word). It's a plugin of CK Editor. We can't change the content.

=> won't fix
