### ISSUE TITLE
Motion: PDF-headers duplicated while line-number-outside 

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#3025]
When using the outside line number mode, headers get displayed twice in PDF.

![bildschirmfoto von 2017-03-01 12-09-39](https://cloud.githubusercontent.com/assets/10233032/23457417/285fa65e-fe78-11e6-8de7-095816ee1123.png)

surprisingly, it only happens when using line numbers outside. With line numbers inside and line numbers off, everything works as it is supposed to.

**Comment by tsiegleauq** [comment]
I found the bug, and that's weird.
The first (with the line number) gets displayed, cause of the `h1` (2 3 4 5) Tag is processed. that's correct.
The other one gets processed, cause a `span` Tag gets processed, which is the weird part.

The correct structure (which should also be healthier for line-numberin purpose would be:)

```
<span>
  <h1> HEAD </h1>
</span>
```

But what CKEditor is doing in here:

```
<h1>
  <span> HEAD </span>
</h1>
```

The PDF routine is doing everything correctly (`h`-tags should not be treated differently to other tags).
So the CKEditor routine has to be changed.

@emanuelschuetze

**Comment by emanuelschuetze** [comment]
@tsiegleauq I'm not sure if we can fix easily this CKEdtior behavior. Maybe you can make a quick fix today in your pdf code? I want to make a 2.1b4 release tomorrow.

**Comment by tsiegleauq** [comment]
There can not be a quick fix for that on PDF generation side. Adding
special cases for this requires a whole re-write of the parser.
