### ISSUE TITLE
missing tooltip for motion text highlighting

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3028]
- open a motion
there are 2 fields above the motion text that are not self explanatory and don't have a tooltip:

![localhost 8000 2017-03-02 00-15-44](https://cloud.githubusercontent.com/assets/1828501/23485817/6ee5498e-fedd-11e6-9cbb-f9a00a7d9532.jpg)
This field should have a tooltip "set line number to be highlighted" (or something similar)

![localhost 8000 2017-03-02 00-16-57](https://cloud.githubusercontent.com/assets/1828501/23485841/95fcf940-fedd-11e6-980a-a53b656bc716.jpg)
This button should have the toolbar "jump to the highlighted line" (or similar)

**Comment by emanuelschuetze** [comment]
Right, we should add a tooltip to the "Go to" button. @FinnStutzenstein Can you do it please?

**Comment by donovaly** [comment]
There is still no tooltip for the line number selection field.

**Comment by emanuelschuetze** [comment]
@donovaly It was fixed yesterday in master. So please retest next 2.1b4 release.

**Comment by donovaly** [comment]
> It was fixed yesterday in master.

I looked at https://github.com/OpenSlides/OpenSlides/commit/4744e1ca99dfe17d8449cdc1bf81e9fdbb793ee0 and there I see that a tooltip for the button was added but not for the field.

**Comment by emanuelschuetze** [comment]
@donovaly I improved the tooltip/popup in #3042

**Comment by donovaly** [comment]
> I improved the tooltip/popup in #3042

This change introduced a regression: it is now no longer possible to project the highlighting as before. The corresponding button has been removed. But this was a very useful feature. Please bring it back.

**Comment by emanuelschuetze** [comment]
It is not a regression - and it does not deal with this pull request. This scoll-to-projector-line-feature was removed in #3008 (because there was a defect which we can not fix quickly for 2.1). We created a new issue to reimplement this feature for 2.2 (see #3010).

**Comment by donovaly** [comment]
> It is not a regression

You misunderstood me. I am not speaking about the feature that the projector scrolled to the highlighted line, it is that in beta 3 I could highlight a line and this highlighting was also shown in the projector. I could manually scroll to the line in the projector.
Now what should I do if people want to discuss on line 38? I can highlight it in OS but not in the projector. OK, I could make the corresponding line yellow by editing the motion but this is an error-prone hack.

**Comment by emanuelschuetze** [comment]
scroll-to-line and highlight-a-line is the same feature which we moved to 2.2 (see #3010).

**Comment by donovaly** [comment]
> scroll-to-line and highlight-a-line is the same feature which we moved to 2.2 

Hmm, for beta 1 and beta3 the line highlighting feature works as expected. Yes the projector view did not jump to the line, but the line was highlighted and I could scroll to it manually.
I understand that there are issues with this features but at least for me it was a useful one. Now it is not only lost but the remaining part is also quite useless because highlighting a line only in OS administration but not in the projector does not help me for an assembly.
Don't beat me for it but maybe a feature with bugs might be better than no feature.
I promise to be quiet now.

**Comment by emanuelschuetze** [comment]
Sorry, but we will do it for 2.2.
