### ISSUE TITLE
motion text highlight button always enabled

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3029]
The button to jump to the highlighted motion text line is always enabled. But if no line is selected to be highlighted:
![localhost 8000 2017-03-02 00-21-08](https://cloud.githubusercontent.com/assets/1828501/23485963/4383a564-fede-11e6-8047-0ec090e2e3bc.png)
, the "go" button does of course nothing and should be disabled.

**Comment by emanuelschuetze** [comment]
Already fixed in current master - please retest next 2.1b4 release.
