### ISSUE TITLE
Wrong diff display of change recommendations

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3030]
- create a new motion (assure that you have set in the OS settings to number outside)
- now enable inline editing and add a change recommendation to the first line of the text
- in the appearing change edit window add a word and make the text color of the inserted word green
- strike through the word before the inserted one and make it read
- save the change recommendation

The changed version looks now like this:
![localhost 8000 2017-03-02 00-39-31](https://cloud.githubusercontent.com/assets/1828501/23486508/d5ffaa94-fee0-11e6-97b4-dec0677daa30.png)

OK, but now view the diff:
![localhost 8000 2017-03-02 00-41-11](https://cloud.githubusercontent.com/assets/1828501/23486540/ff2310a0-fee0-11e6-9cd7-796a5a09ea84.png)

This is obviously wrong.

**Comment by donovaly** [comment]
I know that I don't need to explicitly change the color etc, it was just an example that changing the text formatting leads to problems. When I just add a word, change recommendations work fine.

**Comment by emanuelschuetze** [comment]
Tested. Work for me in current master. Diff version shows the colors/formatting of changed version.

Please retest with 2.1beta4 and reopen if not fixed.

**Comment by donovaly** [comment]
> Please retest with 2.1beta4 and reopen if not fixed.

Please reopen because this is not fixed: the stroke through word does not appear in red although I just set this color as described in my initial comment.

**Comment by emanuelschuetze** [comment]
Retested. Works for me in current master: 
the stroke through word appers in red.

**Comment by donovaly** [comment]
Now it works. Many thanks.
