### ISSUE TITLE
Stopping the OS server closes whole browser

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3045]
Assuming you use your browser to administrate OS. Besides this you have other browser tabs open.

Now you are ready with OS or you want/need to restart it. Therefore you click in the OS console on Stop server.
Result: the browser will be closed instead of the tabs used by OS. The problem is that one looses this way work for other thinks. For example I was also editing in GitHub and the closure of the browser deleted my cookies and therefore I lost work.

So stopping the OS server should either only close the browser tabs of OS or simply logging the current OS user out and keep everything in the browser.

**Comment by emanuelschuetze** [comment]
Do you mean the openslides portable for windows? And you click only on the "Stop server" button to exit the full browser? Which browser do you use?

**Comment by donovaly** [comment]
> Do you mean the openslides portable for windows?

Yes.

> And you click only on the "Stop server" button to exit the full browser?

No, I did not want to to close the browser. I just wanted to restart the OS server, therefore I stopped this. but this also closed my browser - which should not have happened.

> Which browser do you use?

The latest Firefox in the 64bit version.

Btw. I don't think this bug is pressing.

**Comment by emanuelschuetze** [comment]
Fixed with https://github.com/OpenSlides/openslides-gui/pull/14

**Comment by donovaly** [comment]
Confirmed fixed. Many thanks!
