### ISSUE TITLE
PDF with list of all motions misses line numbers

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3048]
- enable in the OS settings to number outside
- open a motion and click on the PDF button

result: everything is fine

- now go to the motion list and export there to PDF

result: now the line numbers are missing. The same is with DOCX export.

**Comment by emanuelschuetze** [comment]
Already fixed in current master: line number settings is used also for all-motions-pdf. For Docx we can't use same line numbering algorithm, so there it is disabled.

**Comment by donovaly** [comment]
> Already fixed in current master

Confirmed fixed. But I found #3059 as new PDF bug.
