### ISSUE TITLE
CSV with list of all motions has <p> tags

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3049]
- enable in the OS settings to number outside
- go to the motion list and export there to CSV

result: one gets a CSV where the motion text and reason is surrounded by `<p>` HTML tags. I assume the problem has to do with #3031 and/or #2998.

**Comment by emanuelschuetze** [comment]
Yes, motion text/reason is saved as HTML, because we allow to format the text/reason in CKEditor.

To keep all formatting we export all used/saved html tags also in csv. Thats required if we want to import it later again in OpenSlides.
