### ISSUE TITLE
Autoupdate on permission change (extended)

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#3057]
The following cases are still missing:
- [ ] Send deleted object if a permission is removed.
- [ ] Handle assignment of a new group to a user.
- [ ] Handle remove of a group from a user.

**Comment by normanjaeckel** [comment]
See #2995

**Comment by FinnStutzenstein** [comment]
@normanjaeckel How important is this issue?

**Comment by jsaalfeld** [comment]
Is still issue still relevant @normanjaeckel?

**Comment by FinnStutzenstein** [comment]
This is still relevant but will be fixed soon. We are working on dropping django permissions and have full control over them.

**Comment by ostcar** [comment]
@FinnStutzenstein my PR has nothing to do with this. I even ported the TODO in the code see the todo in master: https://github.com/OpenSlides/OpenSlides/blob/master/openslides/users/views.py#L338

and the todo in the PR: https://github.com/OpenSlides/OpenSlides/pull/3979/files#diff-f55d52aee36d029764cb51e19c5b105bR317

**Comment by FinnStutzenstein** [comment]
OK. WIll it be easier to solve with the new permission system?

**Comment by ostcar** [comment]
No. Its the same problem what one element has to be send via autoupdate when another element is changing.

**Comment by tsiegleauq** [comment]
now accepting bets regarding the closure of this issue.
![image](https://user-images.githubusercontent.com/10233032/85268362-b3913500-b476-11ea-9b3b-c5b0cfa3ace1.png)

**Comment by FinnStutzenstein** [comment]
This wont be fixed in OS3 ;)

But we will take care about permission changes in OS4 properly.
