### ISSUE TITLE
regression: popup text for change recommendations no longer readable

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3068]
- create a new motion (assure that you have set in the OS settings to number outside)
- now enable inline editing and try to add a change recommendation to the first line of the text

result: one cannot read the popup text:
![unbenannt](https://cloud.githubusercontent.com/assets/1828501/23684378/c1ea4c22-039e-11e7-9328-492fd7773a18.png)

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze try to give this popup a higher z-index.

**Comment by donovaly** [comment]
Confirmed fixed.
