### ISSUE TITLE
Motion line highlighting does not work for line with change recommendation in diff mode

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3077]
* Create a motion with some lines of text.
* Create a change recommendation for line 2.
* Show diff mode.
* Go to line 2 => Failure, second line is not highlighted! (works for original, changed and final version only, but not for diff mode). BTW: Scrolling to line 2 works.
* Go to line 1 or 3 => Ok, line is successfully highlighted

**Comment by FinnStutzenstein** [comment]
@CatoTH Please check this: Add the missing `highlight` parameter [here](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/js/motions/base.js#L737). But this destroys the diff view:
Before:
![diff](https://cloud.githubusercontent.com/assets/8439581/24039724/7ddf036e-0b06-11e7-9f26-b05f63af7596.jpg)
With highlight (line 2 or 3 does not make a difference):
![diff_highlight](https://cloud.githubusercontent.com/assets/8439581/24039741/8e37a14e-0b06-11e7-8983-6b48332b1b75.jpg)

**Comment by CatoTH** [comment]
I wrote a patch for this.
However, I had to write a dedicated function for adding the highlight-classes afterwards. I think, it would make sense to use this new function for all highlighting uses and remove the highlighting functionality from the line numbering function. That should reduce the complexity of the single functions as a side effect.

**Comment by emanuelschuetze** [comment]
fixed with #3096
