### ISSUE TITLE
enhancement: don't show all motions in the agenda

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3080]
Currently all motions appear in the agenda, either as official agenda entry or as internal entry.

This is a big problem, because for larger assemblies (tens of motions) this pollutes the agenda. But an agenda is there to keep the overview. Therefore normally "motions" is the agenda point and the assembly managers will handle the different motions within this point. Maybe they add some main motions as subitem to this point, but never all motions because the motions menu is already the electronic version of the printed book of motions.

So it would therefore be very helpful if motions would not appear in the agenda, except
- the option to appear in the agenda is set
- an option to set it as internal entry

**Comment by FinnStutzenstein** [comment]
@donovaly The last year we done some improvements there. You can now collapse childrens of agenda items and use better (persistend) filter options to hide items. Is this issue solved in your opinion?

**Comment by donovaly** [comment]
Yes, this is fixed with OS 2.3.
