### ISSUE TITLE
ugly button layout in upload file window

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3082]
- go to the Files menu and try to upload a file

result: 
![localhost 8000 2017-03-13 00-22-03](https://cloud.githubusercontent.com/assets/1828501/23837132/d2de6098-0783-11e7-9660-6f0aea0f1f2c.jpg)

The "Durchsuchen" button is displaced.

**Comment by tsiegleauq** [comment]
happens in firefox (Both ESR and current) under Linux for me.

![bildschirmfoto von 2017-03-29 11-58-32](https://cloud.githubusercontent.com/assets/10233032/24449246/2257cf10-1477-11e7-80bd-9294546b743c.png)

Not so in chrome.

![bildschirmfoto von 2017-03-29 11-58-55](https://cloud.githubusercontent.com/assets/10233032/24449250/2618e4ae-1477-11e7-9fd9-b37472d76bae.png)

**Comment by tsiegleauq** [comment]
This is a bug in "angular formly".
Reported it [here](https://github.com/formly-js/angular-formly/issues/736).

as long as we are using formly there is nothing we can do about that.

**Comment by donovaly** [comment]
This issue is still in OS 2.2b1

**Comment by donovaly** [comment]
With the build from today and Firefox 59 this is not fixed. Please reopen.

**Comment by FinnStutzenstein** [comment]
Can you provide another screenshot please?

**Comment by emanuelschuetze** [comment]
I can't reproduce it any more with firefox in current master.
@donovaly Please retest with next test version.

**Comment by donovaly** [comment]
Oh, beta 3 got a new upload dialog. I will describe it right now. It should also be announced.
