### ISSUE TITLE
PDF generation message is untranslated

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3083]
- use OS with German menus
- go to e.g. an election and press the PDF button

result: a message at the bottom of the screen appears telling at first that the PDF is in the creation process and eventually that it has been generated:
![unbenannt](https://cloud.githubusercontent.com/assets/1828501/23879370/e93bb2ea-084c-11e7-8bd0-4e72bba1b05f.jpg)

This message is untranslated in English not German.

**Comment by emanuelschuetze** [comment]
Fixed with #3115

**Comment by donovaly** [comment]
confirmed fixed.
