### ISSUE TITLE
Go back from agenda entry jumps to wrong list

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3084]
- Assume you have an agenda like this:
![localhost 8000 2017-03-14 23-39-33](https://cloud.githubusercontent.com/assets/1828501/23925613/5b48e1aa-0910-11e7-9c78-9c9ea58a898a.png)

- click on the agenda item that is a motion.
- now click the button to go back

result: OS jumps to the motion list and not to the agenda list.

This could e.g. be fixed by having 2 buttons, one goes back to the agenda one back to the motions list. So like it is already the case for the current speaker's list:
![localhost 8000 2017-03-14 23-50-18](https://cloud.githubusercontent.com/assets/1828501/23925774/16079f68-0911-11e7-9264-99d64cfde9c5.png)

**Comment by jsaalfeld** [comment]
This will be fixed in the rewrite of the OS3 client. If this issue still persists, please reopen the issue.

**Comment by tsiegleauq** [comment]
In fact, it's not and that's a wont-fix from my side.

* Create a motion
* Go Agenda
* Click on the Agenda item holding the motion
* See motion detail page
* use back button

Will (and should) navigate you to the motion list. Our "back" function is supposed to bring you to the parent view. If you want visit the previous page, use the browsers back button.
