### ISSUE TITLE
making agenda subitems is extremely difficult

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3087]
- take this CSV-file:
[OV-JHV-TOPliste.txt](https://github.com/OpenSlides/OpenSlides/files/849285/OV-JHV-TOPliste.txt)
- try to sort the agenda points this way:
![localhost 8000 2017-03-17 00-50-53](https://cloud.githubusercontent.com/assets/1828501/24023451/b2d799fa-0aac-11e7-962b-495cba350ae2.png)

result: this is very difficult. This should be improved somehow.

**Comment by emanuelschuetze** [comment]
already fixed in #3482

**Comment by donovaly** [comment]
Many thanks, it works fine now. I only have this idea for an improvement: #3554
