### ISSUE TITLE
regression: no longer possible to us a custom logo

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3091]
Copying a custom _logo-projector.png_ file to the \static\img folder has no longer an effect. 

regression to prior OS 2.1 versions

**Comment by donovaly** [comment]
OK, the favicon works, but not the logo.

**Comment by FinnStutzenstein** [comment]
This works for me, did you clear your browser cache?

**Comment by emanuelschuetze** [comment]
Please reopen if clear browser cache does no help.

**Comment by donovaly** [comment]
> did you clear your browser cache?

Sorry, a beginners fault. Yes clearing the cache works.
