### ISSUE TITLE
inappropriate layout of custom topics

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3092]
- add a new agenda item but don't set it as agenda point
- project it

result: there is too much space above the title:
![localhost 8000 2017-03-17 02-27-06](https://cloud.githubusercontent.com/assets/1828501/24025222/80c6dd06-0ab9-11e7-9426-97cb0ed5ff8f.jpg)

**Comment by FinnStutzenstein** [comment]
Hmm.. This space is always there. When I project a motion, i get the same space.
@emanuelschuetze I think we can make this space half as big. OK?

**Comment by donovaly** [comment]
Many thanks.
