### ISSUE TITLE
PDF of motions contains duplicated paragraphs

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3095]
- create a new motion
- add some text for the motion and its reason
- insert an URL to the motion ad the reasoning text
- Save the motion and export it as PDF

result: the paragraphs with the URL appear duplicated in the PDF:

View in OS:
![localhost 8000 2017-03-18 00-50-39](https://cloud.githubusercontent.com/assets/1828501/24066705/272d2202-0b75-11e7-9317-82b15cfc5904.png)
View in the PDF:
![domain date time](https://cloud.githubusercontent.com/assets/1828501/24066704/248e0d40-0b75-11e7-8f93-8c03f8cc3b30.png)

This bug might be a duplicate of the current PDF generation problems.

**Comment by tsiegleauq** [comment]
this looks quite similar to the header issue. why don't we get CKEditors source code generation fixed?

**Comment by donovaly** [comment]
Confirmed fixed. Many thanks.
