### ISSUE TITLE
default font size in DOCX export should be 12 pt

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3098]
Export all motions as DOCX to create a book of motions.

Participants of an assembly complained that the default font size of 10 pt is too small. Especially the elders. I also agree that 12 pt is a more appropriate default font size.

Yes, the assembly admins can change the font size later in Word but it would save time, if the default is already a better readable one.

**Comment by emanuelschuetze** [comment]
I like the current font size 10pt. Let us keep this font size in 2.1 and wait for more feedback.

**Comment by donovaly** [comment]
Closing for now.

**Comment by donovaly** [comment]
This bug has a milestone. The milestone can be removed because nothing will be done (WONTFIX or is no real bug).
