### ISSUE TITLE
Possible to start new election round for finished elections

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3099]
- go to an election that already took place. Its phase is therefore "Finished"
- click on "new ballot"

result: a new ballot is started. This must be impossible because after an election has been finished be the assembly leaders it cannot be changed. For political parties this is even a restriction in the German laws for political parties.

It is OK that one can reset the state from "Voting" to "Searching for candidates" because participants are allowed to enter a motion to change the voting process during the voting phase.
So to fix this bug, only the state "Finished" must not be resettable. If something went wrong one is forced to make a new election. Maybe other users of OS don't have such a strict rule. If so, there should be an option to block resetting the "Finished" phase.

**Comment by donovaly** [comment]
Please reopen, because this is not completely fixed: 

- go to an election that already took place. Its phase is therefore "Finished"
- go to an election round and delete it

result: the finished ballot is deleted. This must be impossible because after an election has been finished by the assembly leaders it cannot be changed. For political parties this is even a restriction in the German laws for political parties. Changing means no new ballot and also not deleting a ballot nor changing voting counts.
If changes are necessary one must reset the phase. This assures that nothing is changed mistakenly.

**Comment by emanuelschuetze** [comment]
confirmed. Fix see #3156

**Comment by donovaly** [comment]
Confirmed fixed.
