### ISSUE TITLE
scrolling projector view is very slow

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3100]
- create an election with e.g. 25 candidates and project it
- in the projector all candidates are listed, since the list is too long to fit into the projector view, scroll down the projector view

result: it takes on my PC 8 seconds until the scrolling is finished: The first 6 second nothing happens (the browser is even frozen during this time) and then it needs 2 second to scroll. On my Laptop it takes not 8 but 12 seconds.

It would be nice if this could be improved for OS 2.1 final.

**Comment by donovaly** [comment]
This bug can also reproduced with an agenda that has e.g. 25 entries: project the whole agenda and then scroll the projector view.

**Comment by emanuelschuetze** [comment]
Can't reproduce with current master. Please retest it with 2.1 (final). Could be fixed with #3111.

**Comment by donovaly** [comment]
> Please retest it with 2.1 (final). Could be fixed with #3111.

Please reopen. Unfortunately it is not fixed. Scrolling is still unacceptable slow (as slow as reported). Too bad that this cannot be sped up fore OS 2.1.

**Comment by emanuelschuetze** [comment]
@donovaly Can you retest again with 2.2-beta please? Thanks.

**Comment by donovaly** [comment]
> Can you retest again with 2.2-beta please?

This bug is now fixed, tested with Firefox 58.
