### ISSUE TITLE
Changing voting phase freezes the browser

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3102]
- create an election with e.g. 25 candidates and project it
- now change the phase from "Searching for candidates" to "Voting"

result: it takes on my PC 8 seconds until this action is finished. During this time the browser is frozen. On my laptop it takes up to 20 seconds. During my first assembly with OS and my Laptop, OS was even frozen for such a long time that I had to restart the OS server to be able to continue. 

Therefore would like to have this fixed for OS 2.1 final.

**Comment by FinnStutzenstein** [comment]
Tested with PR #3111 : I do not have such issues. It is fast and my browser doesn't freeze. @donovaly Please retest, if you have an OS version with this PR included.

**Comment by emanuelschuetze** [comment]
Works also for me. @donovaly Please reopen if this is still a problem for you with 2.1.

**Comment by donovaly** [comment]
Many thanks, now it takes only 3 seconds on my PC, so about 66% boost in speed. I still wonder why it takes that long, but OK, 6 seconds on my laptop is more acceptable than the previous 20 seconds.

Nevertheless during the 3 or 6 seconds my browser (latest Firefox 64 bit) is still frozen.
