### ISSUE TITLE
Wrong display of ballot round

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3104]
- create an election
- start the first ballot
- start a second ballot
- change back to the first ballot and press there "publish"

result: the second ballot is opened. The publishing was success but the wrong display of the ballot is very confusing because one doesn't see the success and is wondering why one is now in the second ballot.

**Comment by FinnStutzenstein** [comment]
As discussed with @emanuelschuetze : This is a problem from one of our dependencies. I would like to make either a different approach for the tabs or write our own tabset for this. Unfortunately this relatively small bug needs a huge amount of time and effort to fix, so both cases are for 2.2.

**Comment by donovaly** [comment]
Still in OS 2.3b4.

**Comment by donovaly** [comment]
I noted this yesterday but in my opinion this can be postponed to OS 2.3.

**Comment by jsaalfeld** [comment]
This will be fixed in the rewrite of the OS3 client. If this still persists in the new client, please reopen this issue.
