### ISSUE TITLE
regression: PDF of all elections is no longer created

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3106]
- create e.g. 2 dummy elections
- go to the menu Settings->Elections and change there the option "The 100-%-base of an election result consists of" to "All valid ballots"
- go back to the overview of elections and click on the "Export all" and then on "PDF"

result: nothing happens. Only if the option "The 100-%-base of an election result consists of" is in its default state one gets a PDF.
-> regression to OS 2.0

**Comment by emanuelschuetze** [comment]
Confirmed. I get a JS error:
```
TypeError: Cannot read property '4' of null
    at Assignmentspolloption.getVotes (base.js:31)
    at pdf.js:158
    ...
```

**Comment by emanuelschuetze** [comment]
I think this is already fixed with #3114.

**Comment by emanuelschuetze** [comment]
Confirmed.

**Comment by donovaly** [comment]
Confirmed fixed
