### ISSUE TITLE
missing autoupdate for motion text length config

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3107]
- Set in the OS Settings for motions a line length of 70.
- create now a new motion
- paste e.g. this text:
"In political parties it is common that a commission has to have a look at hundreds of motions. Their job is to deny invalid motions and to give recommendations. Therefore it would be an improvement in the workflow if one would be able to import the motions with the recommendation. At the moment one would have to set the recommendation for every motion which could take a lot of time."
- save the motion and project it

result: still up to 80 chars fill a line. This is a regression to prior OS 2.1 versions where this worked.

Moreover, assume the case that you have e.g. 20 motions using 80 chars line length. Now you see in the rules that only 65 chars are allowed in one line. Therefore you change the line length to this value. result. nothing happens. I expect all motions to be changed automatically. Otherwise it would be a nightmare in real life.

**Comment by emanuelschuetze** [comment]
You have to reload after changing the line length config. Then the changed value is used for new line length calculation.

We have to add autoupdate for this config value.

**Comment by donovaly** [comment]
> You have to reload after changing the line length config.

Aha. Nevertheless, this corrects the view in the projector, but in the projector preview still the default 90 characters are used. Should I open this as new bug?

**Comment by donovaly** [comment]
> Should I open this as new bug?

Done: #3143

I added now a hin to the docs that one needs to refresh the page view to get the changed line length.

**Comment by FinnStutzenstein** [comment]
@CatoTH I've added a `console.log(lineLength);` [here](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/js/motions/base.js#L244). If you change the line length, the projector gets an autoupdate, the `getTextWithLineBreaks` gets called (the `console.log` is called) and I've got the correct new line length in this function. But the view doesn't update. Please have a look.

**Comment by CatoTH** [comment]
This appears to be a problem with the caching. The PR should fix it by adding the line length to the cache key.
