### ISSUE TITLE
enhancement: show number of currently participating people

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3108]
During long party assemblies it is common that people leave the venue for some time or some people arrive late while others leave. Therefore the number of electors change all the time. The party rules requires that the current number just before an election must be know and in some parties it must also be announced before the voting begins. Otherwise candidates who lost could sue the party to repeat the election.

It would therefore be helpful to see the number of participants the with "is present" tag somewhere. Currently I have to filter all present people and count manually - that costs a lot of time.

I expect this is not difficult to achieve so maybe this could be added for OS 2.1?

**Comment by emanuelschuetze** [comment]
> Currently I have to filter all present people and count manually - that costs a lot of time.

If you have filtered for 'is present' then you get a number of filtered and total participants (e.g. 23 / 108 participants) on top of the table.  So works already with current master.

**Comment by donovaly** [comment]
Sorry, strange that I haven't seen it during the assembly.
