### ISSUE TITLE
enhancement: allow to select a database

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3110]
I was asked if I could prepare several assemblies using OS. I would therefore have cases that there is an assembly on Saturday and one on Sunday. My spare time is limited and therefore I would have to prepare both the same day.

Currently I have to put the files db.sqlite3 to different folders and put in the db.sqlite3 file I need into OS' working directory to work with the one of the desired assembly.

It would make life much easier if it is possible to give the database a unique name and if there would be a button in the OS program above "Start server" where one could select a database to be used.

**Comment by jsaalfeld** [comment]
This can be done via the `settings.py` you can change the name of the database there. Once you ran the `createsettings` command you can check the `settings.py` and rename the database path to your desire.
