### ISSUE TITLE
Increase performance for pdf generation

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3116]
wait for new pdfmake release which fixes https://github.com/bpampuch/pdfmake/issues/798

**Comment by tsiegleauq** [comment]
according to [this comment](https://github.com/bpampuch/pdfmake/issues/798#issuecomment-287861694), the current version is much faster in some browsers. But maybe they continiue to enhance this

**Comment by emanuelschuetze** [comment]
Fixed with pdfmake 0.1.29
