### ISSUE TITLE
Support vote-counting of participants taking place (present votes for an election at a certain time)

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#313]
It would be necessary to know how many votes each participant has. There are forms of elections where a participant has more than one vote (because of number of shares he/she has or so). Or a person might have received proxy-votes (voting for another member, which is not present - taking into account how many votes that member has).

And it would be necessary to know how many votes in total are present in the elections at any given time. This happens in some elections when a person comes late, leaves early, leaves for 10 minutes (and thus can't participate in a certain number of elections) or so.
I think it might be an idea to log when the maximum number of votes changes for the elections following that point in time (and why that change happened).

**Comment by jsaalfeld** [comment]
As far as I know this issue should be implemented by now.

Please reopen if otherwise.
