### ISSUE TITLE
Find generic solution for whitelist in getFormOrStateForCurrentSlide

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3130]
Currently, the method `getFormOrStateForCurrentSlide` in core/base.js uses hardcoded collection strings of (core) apps which provide an EditForm to open this in a dialog by clicking on "edit current slide" button.

We have to find a generic solution (and something where plugins can register their collection strings for this function), see also discussion in #3127.

**Comment by jsaalfeld** [comment]
Since the client will be completely rewritten, this won't be an issue anymore. If it still persits, please reopen the issue.
