### ISSUE TITLE
Bring the HTML to PDF generator upstream in PdfMake

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#3136]
After the release of OpenSlides 2.1, we should try to completely remove the Code for HTML to PDF Generation and rather bring the parser upstream into the PdfMake library.

Our Benifits:
- More people would profit from this (I get questions about this feature a lot)
- The OpenSlides JS codebase gets much smaler
- More thoughts on PDF Generation in general (hopefully I can find help for the image-to-base64 issues)

We'd need to create the (upstream)parser flexible enough so one can inject an own payload (i.e - special treatment for line numbering etc, own styles, etc)

Also see [this discussion](https://github.com/bpampuch/pdfmake/issues/205#issuecomment-285599927).

**Comment by helloworld87** [comment]
I fixed the translation with matrix. colspan and rowspan will be special treated

**Comment by vinayak5192** [comment]
Look forward for this feature with PdfMake

**Comment by manuelph** [comment]
+1

**Comment by tsiegleauq** [comment]
use:
https://github.com/Aymkdn/html-to-pdfmake
