### ISSUE TITLE
line length not respected by projector preview window

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3143]
- Set in the OS Settings for motions a line length of 90 (default)
- project a motion
- now set in the OS Settings for motions a line length of 70.
- refresh the browser page (because of bug #3107)

result: the new line length is now used for the projection and the motion in OS' main browser window. But the projector preview window still shows the motion with wrong line length.

**Comment by FinnStutzenstein** [comment]
You also have to reload the main OS page. Then the preview is correct.

It seems that this issue and issue #3107 are different, but technically it the same problem. @emanuelschuetze Please close this duplicate.
