### ISSUE TITLE
deleting displayed file not correctly handled

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3145]
- add a an image file
- display the file 
- use fullscreen display
- now delete the file
- finally press the fullscreen button

result:
![localhost 8000 2017-03-25 17-15-28](https://cloud.githubusercontent.com/assets/1828501/24324019/f80255d2-117e-11e7-8736-cbf030c40aba.jpg)

This is a very rare case so I am fine if you say WONTFIX.

**Comment by emanuelschuetze** [comment]
I can reproduce it. Moved to 2.2

**Comment by FinnStutzenstein** [comment]
@donovaly Please check again. We have improved many things related to deleting projected elements.

**Comment by emanuelschuetze** [comment]
I tested it successfully with @normanjaeckel. Fixed.

**Comment by donovaly** [comment]
Confirmed fixed.
