### ISSUE TITLE
inconsistent spacings in projector view

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3147]
Currently every type of slide uses another spacing below the header line.

For example for elections, projector space is unnecessarily wasted:
![localhost 8000 2017-03-25 18-11-04](https://cloud.githubusercontent.com/assets/1828501/24324454/f1aab42e-1186-11e7-81e6-e552b86aefeb.png)

While for agenda items there should be a bit more space between the header and the first text:
![localhost 8000 2017-03-25 18-14-53](https://cloud.githubusercontent.com/assets/1828501/24324474/09d4f352-1187-11e7-89d4-411b0fe7b468.png)

Since I guess it is easy to fix, maybe something for OS 2.1.

**Comment by donovaly** [comment]
Many thanks. I have seen you fixes a lot of bugs during your meeting. Could you please send me a new test version of OS2.2 or release a beta 2. This way I can test the bugfixes and start the documentation update.

**Comment by donovaly** [comment]
Not completely fixed. The second case is now fixed, but the first case (see the initial comment) has still too much whitespace.

**Comment by emanuelschuetze** [comment]
@donovaly Can't reproduce it. Please provide new screenshots.

**Comment by donovaly** [comment]
> Please provide new screenshots.

It is now better than in the initial comment:
![whitespace](https://user-images.githubusercontent.com/1828501/39162811-97f3808c-4777-11e8-9274-a50cb32fac34.jpg)

Nevertheless I think the spacing between the line below "Wahl" could be smaller. Also the space between the description and the candidates could be smaller (but I am not sure).

**Comment by emanuelschuetze** [comment]
I think for 2.2 it's ok. We have more important issues. So I closed.
