### ISSUE TITLE
New profile page for each participant

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#315]

**Comment by emanuelschuetze** [comment]
@normanjaeckel can we close this issue. We have a simple about-me field.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel @emanuelschuetze Ping. This issue is too old.

**Comment by emanuelschuetze** [comment]
@normanjaeckel For me this issue is done (currently we have the user detail view). If you need more please create a new issue.
