### ISSUE TITLE
refactoring: duplicate line highlighting code

### ISSUE THREAD

**Issue by CatoTH** [OpenSlides/OpenSlides#3150]
I had to reimplement the line highlighting function in a separate function in order to make it work in inline diff mode. Right now, this leads to two redundant functions, doing the same thing:
- lineNumberingService.highlightLine() , the new function
- the implicit function in the lineNumberingService.insertLineNumbers()-function, triggered by the "highlight"-parameter.

In my opinion, the latter one should be removed, to simplify the insertLineNumbers()-functions and prevent redundant code.
(Probably a post-2.1-issue)

**Comment by jsaalfeld** [comment]
Since the algorithms will be rewritten for the 3.0 client, this shouldn't be an issue anymore. If otherwise, please reopen @CatoTH.
