### ISSUE TITLE
regression: spell-checking of browser cannot be used anymore

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3151]
- create a new motion
- save it and now edit it inline
- misspell a word purposely

result: the spell-checker of your browser (in my case Firefox) will underwave the misspelled word correctly:
![localhost 8000 2017-03-27 00-16-59](https://cloud.githubusercontent.com/assets/1828501/24335684/bc2a569a-1282-11e7-9b0d-aff8558471ef.jpg)
but I cannot right-click anymore one the misspelled word to correct it or to set the language of the text. This is a regression to the former text editor used by OS in 2.0 and 2.1 beta 2.

**Comment by donovaly** [comment]
I am not sure if disabling the editors' context menu is the best solution. Maybe CKeditor also provides a spell-checker? If not, I cannot decide if e.g. the editor's context menu for tables is more useful than the spell-ckecking. So all I want to say is I don't insist in fixing this bug, maybe there are good reasons for a WONTFIX. However, spell-checking is in my opinion a feature that is necessary for motion texts.

**Comment by emanuelschuetze** [comment]
I also think about this priority and I decided:
Having a working spell checking (in known browsers context menu) is more important and useful than a special list feature context menu entry (e.g. for changing bullet point type circle/square) or table design (remove/add new line). Both cases are very rarly (special lists and tables are not typically in motions). And there is a workaround to do this in HTML code view of CKEditor.

So I prefere to make spell checking working with browsers context menu for 2.1!

**Comment by donovaly** [comment]
Confirmed fixed.
