### ISSUE TITLE
regression: German names for motion categories

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3152]
- use OS with English menus
- open a motion
- click on the category

result:
![localhost 8000 2017-03-27 00-25-34](https://cloud.githubusercontent.com/assets/1828501/24335782/1266086e-1284-11e7-82de-4b46d349b52e.jpg)
The category options are German.

**Comment by emanuelschuetze** [comment]
Sorry, but the category entries are user entries (and come from system)! You can enter category names in languages as you want...

**Comment by donovaly** [comment]
Ah, sorry.
