### ISSUE TITLE
displaying PDF files always uses fullscreen

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3169]
- upload a PDF to OS
- display it

result: OS uses always fullscreen. You can press the button to turn off fullscreen but nothing will happen.

**Comment by Rikorose** [comment]
It would also be nice if one could set a default opening behavior (open always in full screen, or not in full screen). Maybe separate options for PDF / pictures / videos.

**Comment by donovaly** [comment]
> It would also be nice if one could set a default opening behavior (open always in full screen, or not in full screen). Maybe separate options for PDF / pictures / videos.

Could you please report this as separate issue? Because these are enhancements and should not be forgotten when this this bug will be closed/fixed.

**Comment by emanuelschuetze** [comment]
2 suggestions:
* Change the fullscreen icon in pdf presentation control panel to a "reset" icon (this action resets the zoom level to default (fullscreen))
* Project each image in fullscreen by default (fullscreen button is enabled).

**Comment by donovaly** [comment]
I cannot see that this is fixed. Now I always get fullscreen.  I cannot find a way to make it smaller.

**Comment by donovaly** [comment]
I have to correct myself. There is in OS 2.2b1 no longer a button to toggle fullscreen. I think this bug can be closed when bug #3552 is fixed.

**Comment by emanuelschuetze** [comment]
I close this issue and keep #3552 still open.
