### ISSUE TITLE
Missing person in AUTHORS file

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3170]
https://github.com/OpenSlides/OpenSlides/blob/0086b513d08839f4e201db991db3f64fafefb6c6/AUTHORS
misses me ;-)

**Comment by emanuelschuetze** [comment]
@donovaly You are author of the openslides manual (see https://github.com/OpenSlides/openslides-docs/blob/master/AUTHORS). You have not contributed a pull request to openslides-core. Thats our rule when we add new names to AUTHORS. See e.g. all contributors with there commits here: https://github.com/OpenSlides/OpenSlides/graphs/contributors
An other reason why we maintain the AUTHORS file correctly is that we can ask all contributors if we want to change the license of OpenSlides.
Hope this way is ok for you.

**Comment by donovaly** [comment]
> Hope this way is ok for you.

Yes.
