### ISSUE TITLE
Agenda text cannot be saved

### ISSUE THREAD

**Issue by Rikorose** [OpenSlides/OpenSlides#3173]
When I enter some text in the agenda text field, the text cannot be saved and always changes back to `['text']` (in html source code: `<p>[&#39;text&#39;]</p>`). In motions or elections, the text or description fields are working fine. 

![image](https://cloud.githubusercontent.com/assets/16517898/24541514/123eecd0-15f8-11e7-9de9-bcd8c15940ce.png)

**Comment by FinnStutzenstein** [comment]
Confirmed. Fix is already in the review process.

**Comment by donovaly** [comment]
This is such a nasty bug that it deserves in my opinion an immediate 2.1.1 release. 

I apologize that I haven't seen it. I tested a lot but the last 2 weeks before the release I only used CSV imports. So if possible an automated test should be created.
