### ISSUE TITLE
Rewrite login- und logout view

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#3178]
With django 1.11 the login and logout view is deprecated https://docs.djangoproject.com/en/1.11/releases/1.11/#django-contrib-auth

Our login and logout view are based on this deprecated views, so they should be rewritten.

**Comment by normanjaeckel** [comment]
We do not use django's function based login view but only the ``login()`` function in ``django/contrib/auth/__init__.py`` that handles the login itself. This function is not deprecated. The same for logout. So I think nothing has to be done here.
