### ISSUE TITLE
Unresolved reference OptionForm

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#3179]
OptionForm missing. Is get_vote_form obsolete?
See https://github.com/OpenSlides/OpenSlides/blob/master/openslides/poll/models.py#L196

**Comment by emanuelschuetze** [comment]
Ok, the python function `get_vote_form` (with the import ` from openslides.poll.forms import OptionForm`) seems to be unused and can be removed.
@normanjaeckel Please look at this and clean up. Thx.

**Comment by normanjaeckel** [comment]
Poll form was removed in https://github.com/OpenSlides/OpenSlides/commit/fbf7d0e43d72c84b26036caf92e47ef5bcc7babc. I remove the last code snippets now.
