### ISSUE TITLE
Add 'noLinebreaks' parameter for motion.getTextByMode

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3183]
Currently I get the text with `getTextByMode` and then clearing the linenumbers with `lineNumbeirngService.stripLinenumbers(...)`. This is not very efficient.
@CatoTH Do you may add this parameter?

**Comment by CatoTH** [comment]
@FinnStutzenstein Just to make sure: do you want the plain motion text, or the motion text with inserted line breaks (but without the numbers)?

**Comment by FinnStutzenstein** [comment]
I want plain text for csv and docx export, so without the `<span ...linunumber stuff...></span>`. I need the original text, the changed text and the agreed text (no diff view here), so I used `getTextByMode`.

**Comment by CatoTH** [comment]
Could you have a look if the parameter added in the PR is what you need?
