### ISSUE TITLE
Cleanup new changelog

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3203]
Question: For every entry in the changelog are numbers linking to github. Should link to the PR or the issue? Currently they are mixed.

**Comment by emanuelschuetze** [comment]
We want to reference always the pull request in CHANGLOG to give more details what was changed. The commit message should always referenced to the fixed issue number (if an issue is available).

So which changelog entry is wrong?

**Comment by FinnStutzenstein** [comment]
# 2705 --> # 3181
Done in PR #3207
