### ISSUE TITLE
Missing indentation in motion pdf

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3205]
If you add some change recommendations (with deletions in the end of the line) which goes beyond the line an indentation is missing, see examples (line 1 and 5; line 3 with INS works as expected):

![change-recommendations-pdf-20170419](https://cloud.githubusercontent.com/assets/2075427/25174074/86c3431e-24f6-11e7-9341-24810a66d006.png)

**Comment by tsiegleauq** [comment]
Can not reproduce, since when I try to change a motion and delete a word, somehow the how line gets cancelled and then replaced in green...
Can still try to fix it, but cannot test it here.
