### ISSUE TITLE
Wrong font color in motion pdf (in IE11 only)

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3206]
IE 11 has a problem to render a font color in motion pdf correctly.

An example:

**HTML-Code of motion text:**
```
<p><span><span style="color:#000000">Lorem ipsum dolor sit amet,
consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean
massa. Cum sociis natoque penatibus et magnis dis parturient montes,
nascetur ridiculus mus.</span></span></p>

<p><span><span style="color:#000000">Donec quam felis, ultricies nec,
pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In
enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam
dictum felis eu pede mollis pretium. Integer tincidunt. Cras
dapibus.</span></span></p>

<p><span style="color:#000000"><span><span>Vivamus elementum semper
nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor
eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus
in, viverra quis, feugiat a.</span></span></span></p>
```

**PDF-Output (IE 11):**
Failure: Font color of line 1-7 are grey (instead of black)!

![grey-text](https://cloud.githubusercontent.com/assets/2075427/25174601/2e702d10-24f8-11e7-987e-ea7ace52f119.png)

**PDF-Output (Chromium):**
Successfully: Font color of all lines is black.

![pdf-output-chrome](https://cloud.githubusercontent.com/assets/2075427/25174721/8cdda81e-24f8-11e7-8b8b-6122c9392757.png)

If you disable the line numbers the generated PDF in IE11 has a correct black font color. But a different font-color (e.g. red) was also ignored by IE. In Chromium it works correctly. So something wrong with span and font-color parsing by using IE11...

Workaround: Don't use IE11 to generate motion pdf files correctly!

**Comment by FinnStutzenstein** [comment]
I cannot reproduce this, I get the same output as in #3217 .

**Comment by tsiegleauq** [comment]
@FinnStutzenstein : in IE11? :-O

- patchlevel
- system
- x32 / x64

**Comment by FinnStutzenstein** [comment]
False alarm; I did not recognize the linernumbermode=outside.
