### ISSUE TITLE
"asgi_redis is too old"

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#3224]
Current master cannot be executed.

`RuntimeError: Your version of asgi_redis is too old - it must be at least 1.2.0`

To fix I need to run:
`pip install -r requirements_big_mode.txt`

To install the necessary version of asgi_redis
We might consider to put this into 
[requirements_production.txt](https://github.com/OpenSlides/OpenSlides/blob/master/requirements_production.txt)

**Comment by normanjaeckel** [comment]
Current master in non big mode works without problems. Also a fresh install of big mode works. asgi-redis is installed in version 1.3.0. So this might be only an update problem.

**Comment by tsiegleauq** [comment]
> So this might be only an update problem.

doubt it.

did the npm install and pip install -r routine as usuall.
You might want to checkout current master in a new directory to reproduce this issue.
requrements-productive.txt now seems dependant on asgi_redis.

**Comment by normanjaeckel** [comment]
```bash
$ rm -r .virtualenv/
$ rm -r personal_data/
$ python3 -m venv .virtualenv
$ source .virtualenv/bin/activate
$ pip install -U setuptools pip
$ pip install -r requirements.txt
$ python manage.py start
```
This works without any problems. asgi-redis must not be required if use_redis is False in settings.

**Comment by FinnStutzenstein** [comment]
Tested a fresh `git clone` with the described setup: Works for me. asgi_redis shouldn't be installed, if you just install the requirements.txt?

**Comment by tsiegleauq** [comment]
Hmmm. Seems I just took time older requirements into new setup or something. Thanks for clarification.
