### ISSUE TITLE
Motion PDF Change Recommendation: Lower the distance between change recommendation entries

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#3232]
Sometimes the Distace between the change reco and the motion text is (still) too big.
 
@CatoTH already introduced the inline CSS class `merge-before` to lower the distance in the PDF if there is no distance wanted in [this pull request](https://github.com/OpenSlides/OpenSlides/pull/3132/files).

~~Sometimes it happens that we do not have `<p>` but `<span>` to determine a new line (i.e. copy and paste a the motioncontent from word), so we probably just need to expand the usage of 'merge-before' to `span` aswell.~~
OK seems we always have `<p>` tags maybe its just enough to add the 'merge-before' into the `<p class="delete">` and we dont even need to alter the span

Steps to reproduce:

- Put this code into a new motion

`<p><span><span>Es war einmal eine alte Geis, die hatte sieben junge Geislein, und hatte sie lieb, wie eine Mutter ihre Kinder lieb hat. Eines Tages wollte sie in den Wald und Futter holen, da rief sie alle sieben herbei und sprach &#39;liebe Kinder, ich will hinaus in den Wald, seid auf eurer Hut vor dem Wolf, wenn er herein kommt, so fri&szlig;t er Euch alle mit Haut und Haar. Er verstellt sich oft, aber an seiner rauhen Stimme und an seinen schwarzen F&uuml;&szlig;en werdet ihr ihn erkennen.&#39; Die Geislein sagten, &#39;liebe Mutter, wir wollen uns schon in Acht nehmen, Ihr k&ouml;nnt ohne Sorge fortgehen.&#39; Da meckerte die Alte und machte sich getrost auf den Weg.</span></span></p>`

- change reco with line numbers line (i.e.) 3.

view PDF and HTML code

**Comment by emanuelschuetze** [comment]
Reproduced with current master and example html code. The margin below and above the change recommendation line should be removed that the whole paragraph is displayed "en block".

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Same as in PR #3272 :
I can remove the top space (bottom space is no more there) by removing the marginTop when merge-before is set. Do we want to have the gab in the text or not?

**Comment by emanuelschuetze** [comment]
I want to have only margins/gabs between _real paragraphs_ (independent of any change recommendation). Example:

```
Paragraph xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Paragraph xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Paragraph xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

If there are change recommendations inside a paragraph (with inline or block diff mode) NO(!) margin between change recommendation and begin/end of paragraph is desired. Expected behavior:
```
Paragraph xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxx--(xxx)---YYYxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Paragraph xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
+ yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Paragraph xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
If there is a change recommendation which replaced a whole paragraph, please keep the original margin of the paragraph. Example:

```
Paragraph xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

- Paragraph xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
+ NEW PARAGRAPH yyyyyyyyyyyyyyyyyyyyy
+ yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

Paragraph xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

Hope this helps. Otherwise ask me again.

**Comment by emanuelschuetze** [comment]
I found a reproduceable bug with a undesired margin above a change recommendation (inline diff mode):

* Create a short motion text.
`Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget 
 dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, 
 nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
 sem.`
* Add a change recommendation for line 2: Add a word.
* Create a pdf in diff mode => Ok. Looks good without any margin within the paragraph.

![issue3232-a](https://cloud.githubusercontent.com/assets/2075427/26622115/9d756b3c-45e9-11e7-94b5-a634313d1559.png)

* Now remove the change recommendation.
* Edit the motion text in ckeditor's source code editor and add a `<span>..</span>` around the paragraph text: `<p><span>Lorem ipsum...</span></p>`
* Create again the same change recommendation in line 2.
* Create a pdf in diff mode =>  Failure. PDF contains a undesired margin above the created change recommendation:

![issue3232-b](https://cloud.githubusercontent.com/assets/2075427/26622116/9d790fbc-45e9-11e7-9221-83ed29482a76.png)

We have to find a way to ignore unused `<span>..</span>` tags which are introduced by copy/paste from word.

**Comment by FinnStutzenstein** [comment]
Not a pdf parser problem:
@CatoTH In the case Emanuel described, no merge-before is inserted into the diff text's p tag. This happens, because the `outerContextStart` and the `innerContextStart` are empty. Please fix this.

**Comment by FinnStutzenstein** [comment]
Addition: If I delete or insert text, the p tag gets the class `delete`/`insert` but also the `merge-before` is missing.

**Comment by CatoTH** [comment]
I created a pull request for this issue, hopefully this fixes the problem. I moved some functionality from the MotionChangeRecommendation-class to the diff-service in order to make it easier to test it via karma.

**Comment by CatoTH** [comment]
A new attempt to solve the issues around split items. Could you have a look at #3288, if the html produced now can be used for the PDF as well? Basically, the merge-before-class would become obsolete and is replaced by os-split-before (and os-split-after), indicating that the given tags has been split by the diff and no extra margin / padding should be applied before / after it. As these classes are set to every element that has been split, it should be a bit easier to produce a consistent behavior with these classes.

**Comment by emanuelschuetze** [comment]
Retested with current master. Example:

1. Create a motion text with one paragraph.

2. Create 3 change recommendations (replace, insert, deletion), see screenshot (looks good):
![motion-margintest-1](https://user-images.githubusercontent.com/2075427/28969905-beef387c-7926-11e7-89bb-3336cfef7880.png)

3. Show diff view (looks good):
![motion-margintest-2](https://user-images.githubusercontent.com/2075427/28969931-dd79c384-7926-11e7-875d-fc809e4a00e0.png)

4. Now generate the pdf of diff view.  Each change recommendation has undesired margins on top! See screenshot:
![motion-margintest-3](https://user-images.githubusercontent.com/2075427/28969974-0d14ebd2-7927-11e7-97d0-cba9d6b2aa6f.png)

**Comment by tsiegleauq** [comment]
looks still like `<p>` Tags without `merge-before` ;-)
Something is appearing over and over again.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Please look at this pdf layout issue in next time. Thanks!
