### ISSUE TITLE
Change recommendations and office programs

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3247]
If you copy some text from an office text program, It sometimes generates overloaded html:
![dom](https://cloud.githubusercontent.com/assets/8439581/25886347/81a119e8-355d-11e7-8c27-e04917dd7a41.jpg)
The problem is, that the style attribute `color: #000000;` overrides the color set by the class `insert` and `delete`. This just happens, if you change complete paragraphs.
When changing just a word, the tags `<ins>` and `<del>` are used. my proposal: Do not use the classes `insert` and `delete` but put the tags around every changed text, because every color specified by office gets overridden.

If the html view is correct, the pdf should be fixed, too.

**Comment by CatoTH** [comment]
I wonder what the correct behavior should be. It would be relatively easy to just remove the color attribute here, but then, intended changes in the colors would not be displayed. Just removing color-attributes that are black, as here?

**Comment by FinnStutzenstein** [comment]
If this is easier to remove the attribute, this is great! At least black should be removed.

I was also thinking about that. IMHO we should override the color, to be consistent and it is not irretating having different colors for test and the strike. @emanuelschuetze My give his opinion.

**Comment by FinnStutzenstein** [comment]
@CatoTH From Issue #3243 
> expected: added/removed lines should be override all custom text colors by using red/green color

**Comment by emanuelschuetze** [comment]
@CatoTH ping, this issue is important. Hope you can fix this asap. Ask me if you need more information. Thanks.

**Comment by CatoTH** [comment]
The pull request cancels out any inline color-styles inside of inserted or deleted paragraphs.
It does not fix the unnecessary massively nested SPAN-soup in the example shown above, though.
