### ISSUE TITLE
Load css from plugins like js.

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3253]
This may be solved with #2209 together. Currently I have to put css into the templates with style-tags. This is not very efficient and clear.

A plugin could deliver a `css_files` array, like we do this with js already.

But a very nice way would be that OS automatically discovers js- and css-files and includes them into the index.html

**Comment by FinnStutzenstein** [comment]
New Proposal: Because of the new build process for all css files with sass (see #3507 ) the gulp build process has to be run after every change in plugins. This could not be done e.g. with the windows portable build.

So I would recommend a js provider where each app can register its css files. The provider then creates link-tags and load the css file into the DOM. Each app can have its own build process may using sass, plain css or the tool in flavor of the plugin's author. He/She just have to register the one or many resulting css files in js.

**Comment by normanjaeckel** [comment]
Sounds good.

**Comment by jsaalfeld** [comment]
With the rework of the client this shouldn't be an issue anymore. If it still persists, please reopen it.
