### ISSUE TITLE
Black screen on page changing with a projected pdf

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3259]
Project a pdf file and change the page. A black screen appears while changing.

Problem: The display properties (zoom, page number, visible, ...) is saved into the projector config. When changing the page, the projector config is updated and so the projector reloads the elements. The `ng-repeat` over all elements rebuild the DOM. In fact, the `ng-pdf` with the `canvas` is removed and immediately placed by angular. So the canvas reloads --> this causes the black screen.

Solution: Do not save the display information into the projector config. I would like to have a JSON-field in the mediafile model (name like 'display_information'), so updating e.g. the page number do not reload the projector elements. Also this helps syncing if we want to display one pdf on multiple projectors, so all projectors display the pdf equally.

@normanjaeckel can you change the mediafile model?

**Comment by normanjaeckel** [comment]
Sorry but I do not like this solution. It would be impossible to project different pages of a file on different projectors.

I strongly recommend not to store projecting details into the projected model (like a specific line number into motion model or the number of last speakers to be shown into the agenda item etc.) to keep our modeling and multi projecting stuff clean.

The problem of angular's ng-repeat has to be solved separately. (Example: Imagine a projector that shows a motion, a clock, a countdown and a custom mediafile pdf image in the corner at once (feature provided by a plugin). If I change the motion all other projector elements flutter.) Maybe we have to use Angular2 or React or whatever is more powerful in updating the DOM than AngularJS.

**Comment by FinnStutzenstein** [comment]
Changing the motion will not result in a reloading of the elements, because the projector entry does not update.
But yes, the ng-repeat problem should be resolved. But the only thing I can imagine is to write a custom ng-repeat, that checks explicit for changes and do not clear and rebuild the whole DOM.

**Comment by normanjaeckel** [comment]
Sorry, with "change the motion" I mean project another motion instead of the current one.

**Comment by FinnStutzenstein** [comment]
I have found a solution -- but now, we cannot zoom the pdf anymore, because the used player does not support to set the zoom (just the initial zoom). Only a `zoomIn()`, `zoomOut()`, `pageFit()` is provided. Thus the player doesn't initialize on every change anymore, the zoom is fixed to the initial zoom.

Please try out my branch `Issue3259` --> page changing works, zooming not.

Some options: First, make a fork of the used viewer and implement this (should be easy) and try to bring this upstream. Or use another viewer. Or write our own viewer (some more work..).

**Comment by emanuelschuetze** [comment]
I tested your branch `Issue3259` with a pdf presentation:
* Page changing works without black screen. Very good. 
* Zooming of a pdf presentation is not important because the initial zoom starts with fullscreen which is enough.
* Every page changing action gets a `TypeError: canvasScope.clearCanvas is not a function`.
* Is there a possibility to preload the whole pdf? If you load a pdf file with e.g. 15 pages with a lot of images and text boxes the first load of each page needs a few (mili) seconds. After some page up/down movements the pdf pages loads directly.
