### ISSUE TITLE
Unknown provider

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3263]
JS-Error in current master if you open motion list view:

`Unknown provider: PdfImageConverterProvider <- PdfImageConverter <- MotionPartialContentProvider <- MotionPdfExport`

Introduced with lsat pull request #3239.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Can you give me a hint how to fix it?

**Comment by FinnStutzenstein** [comment]
The provider has been renamed:
Just change 'PdfImageConverter' to 'ImageConverter'
Strange; i did a grep to check, that I didn't forget anything...

**Comment by emanuelschuetze** [comment]
Thanks!
