### ISSUE TITLE
Wrong change view, when deleting parts in lists

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3269]
When deleting parts in a list item, extra list bullets are shown in the change view:

Normal view:
![deletion_prev](https://cloud.githubusercontent.com/assets/8439581/26389061/40ba5c36-4058-11e7-8bb0-c36982a1a1f8.jpg)

Change view:
![deletion_changeview](https://cloud.githubusercontent.com/assets/8439581/26389064/455ed7b2-4058-11e7-8765-13c1b77f70d5.jpg)

**Comment by CatoTH** [comment]
Could you check if the pull request fixes the problem?
You need to recreate the change recommendation, though, as the patch adds a "os-split-li"-class to the list item in the change recommendation.

**Comment by FinnStutzenstein** [comment]
The PR works (also without recreating the change recommendation). PDF is still wrong, but this I will do in another PR.
