### ISSUE TITLE
Problems when requesting changes inside OLs

### ISSUE THREAD

**Issue by CatoTH** [OpenSlides/OpenSlides#3270]
This happens if a line inside a numbered list is changed:
![bildschirmfoto 2017-05-24 um 21 54 03](https://cloud.githubusercontent.com/assets/533440/26422812/96cd3648-40cb-11e7-9d3a-601420da2011.png)

This is a styling problem for once, and a problem in the diff when encountering the start="2" attribute inside of <OL start="2">.

**Comment by CatoTH** [comment]
The styling part of it should be fixed by #3288

**Comment by FinnStutzenstein** [comment]
@CatoTH Can you check again, if this issue can be closed?

**Comment by CatoTH** [comment]
Yes, looks good now:
<img width="614" alt="bildschirmfoto 2017-08-02 um 20 48 16" src="https://user-images.githubusercontent.com/533440/28889313-f52a4224-77c3-11e7-8394-7dd2c140aa57.png">
