### ISSUE TITLE
Check isort release

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#3281]
Isort 4.2.8 is broken. We will set to 4.2.5 and have keep on watching ...

https://github.com/timothycrosley/isort/issues/543

**Comment by normanjaeckel** [comment]
New isort has fixed the `--check-only` flag but we have still the problem with flake8, see https://github.com/timothycrosley/isort/issues/550

**Comment by normanjaeckel** [comment]
See also https://github.com/PyCQA/pycodestyle/issues/652

**Comment by ostcar** [comment]
I think this is solved. We currently use the newest releases of isort and flake8. If not, please reopen
