### ISSUE TITLE
problems at installation 

### ISSUE THREAD

**Issue by falavu** [OpenSlides/OpenSlides#3289]
Hallo liebe MacherInnen von Open Slides,
darf man hier als Nicht-Programmierer auch in Deutsch schreiben? 

Beim Versuch, für einen Verein auf einem OSX-Rechner (10.12 mit PIP 9.0.1) OpenSlides zu installieren, beginnt es leider gleich mit Fehlermedungen: 

Nach einigen Zeilen in schwarz (also normal Befehle, denke ich), die erste Meldung: 
```
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for twisted
  Running setup.py clean for twisted
```

Die Zeile »Failed building …« ist in Rot. 
Dann geht es aber von alleine weiter mit ganz vielen Zeilen in Schwarz (Hunderte?). 
 
Am Ende steht dann wieder was von Error: 
```
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'clang' failed with exit status 1
```
    
Die folgenden Zeilen stehen wieder in Rot: 

```Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/pip-build-apoof4/twisted/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/pip-EZtKQc-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/pip-build-apoof4/twisted/```

Kann jemand sagen, was das Problem ist? 
Ganz herzlichen Dank. 

Falavu (nein, das ist kein richtiger Name, nur mein Pseudonym)

**Comment by normanjaeckel** [comment]
Die Installation wurde möglicherweise nur mit Python 2.7 durchgeführt. OpenSlides benötigt aber Python 3.4 oder höher.

----

Please try it again using Python 3.4 or higher, not Python 2.7.

**Comment by falavu** [comment]
Hi Norman,
danke für den Hinweis. Ich hatte nur "pip install openslides" im Terminal eingegeben – so, wie es in der Doku steht. 
Wie kann man den Installer dazu bringen, dass er die Version 3.6.1 verwendet?
Auf macOS ist nämlich außer 2.7 auch 3.x installiert.
Herzlichen Dank

**Comment by normanjaeckel** [comment]
Man kann eine virtualenv benutzen, siehe README Schritt 1 b. Wenn die venv mit Python 3 initialisiert wird, läuft der Installer (pip) innerhalb der venv auch unter Python 3.

----

Please use a virtualenv, see README step 1 b.

**Comment by emanuelschuetze** [comment]
@falavu: Hat Dir der Tipp von @normanjaeckel geholfen?

Bitte öffne den Issue einfach wieder, wenn Du noch Probleme hast. Danke.
