### ISSUE TITLE
Support quoted/balanced list of speakers

### ISSUE THREAD

**Issue by mforsa** [OpenSlides/OpenSlides#3294]
The current list of speakers supports only a first in first out sorting. It would be nice, if there is a balanced sorting by numbers of contributions too. So people who talk little are favoured than talkative people.

**Comment by normanjaeckel** [comment]
Would be a nice feature, but needs some discussion: What should be the source of the balancing?

- only the respective agenda item
- all agenda items
- configurable

**Comment by mforsa** [comment]
For my opinion there are more possible sources:
- only the current agenda subitem
- the whole agenda item

For my needs it should be only the respective agenda item.
But I think a configurable source would be nice.

**Comment by tsiegleauq** [comment]
Is this still relevant? The list of speakers can be sorted via drag and drop.
I am not planning to add some automatic kind of sorting.

**Comment by emanuelschuetze** [comment]
This is a "TODO" milestone issue - not for 3.0. Let us keep the idea open for future.

**Comment by tsiegleauq** [comment]
OpenSlides will, most likely, never support automatic quoting. This is something the administration has to handle manually.
By now, the list of speakers supports certain stuff not make quoting easier, including:
- number how many times a speaker was speaking before
- highlight the first contribution
- show a speakers gender
- show pro, contra and arbitrary marked speaker

everything necessary to resolve this issue has been done.
