### ISSUE TITLE
Block double change recommendations

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3298]
If I double-click on the save button when creating a change recommenadtion. thwo of them are created and I get massive js errors:
![wrong_change_reco](https://user-images.githubusercontent.com/8439581/27181025-067dcf96-51d6-11e7-95f8-198285ae15c9.jpg)

@CatoTH Do you have time to fix this on server side? Maybe make the combination (motion_id, line_from, line_to) unique?

**Comment by CatoTH** [comment]
I wrote a fix that should prevent any kind of overlapping change recommendations on the server side (throwing an 500 error instead).
