### ISSUE TITLE
More debug infos

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3316]
I would prefer to include some debug output in OpenSlides. The worker and client are very quiet. Debugging on productive systems is not much fun. I would prefer that the client prints out some status information, when it gets the first autoupdate, when trying to reconnect ws connections, logging about network things, ...
Something equivalent would be nice for more worker output

**Comment by normanjaeckel** [comment]
What about the following: We use the settings DEBUG option (or even extend it) and provide its value also to the client on startup (via WebclientJavaScriptView). Then the client can log things to the console. If DEBUG is false, client and server should be as quiet as possible.

For our customer container solution you may add a short option in the webinterface to control the DEBUG value of the instance.

**Comment by FinnStutzenstein** [comment]
Outdated.
