### ISSUE TITLE
Add liststyle attribute to pdf's

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3338]
When  a new pdfmake version with [this commit](https://github.com/bpampuch/pdfmake/commit/69e4264f9a111d73d63f2fb3e266e7e399526706) is published, fix the non-hidden bullet points in pdf (they should be hidden). See issue #3269 .

**Comment by emanuelschuetze** [comment]
pdfmake 0.1.33 is released with "lists - own item type (listType)".
