### ISSUE TITLE
Rework motion comments

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3350]
The motion comments system is some kind of overcomplicated, not clear and broken:

Why are the comments are saved in an array? So the order just determinate which comment goes to which field. Removing or adding fields in the config does not change the motions, so the content of the comments may shift between fields. Also the code assigning the comments to field in the motion controller is not very nice to read.
The implementation of special comment fields is not straight forward. In several places (pdf and docx generation, inline editing for comments, config, ...) we have to check, if the comment field is a special field. Why are there no global defined methods in the client, that on one place is defined, what comment is a special comment. Ich I add a field like 'forText', I have to change so many places.

My proposal is to give the comment fields an id. Maybe a database model, but then we have to change too much. On adding a field, the server gives this field the next available number. The comments in the motions are saved as a dict assigning id <-> comment. So the comments don't get shuffled on randomly deleting fields, we do not have to save empty strings for 'no comment' and keeping track of the comments to field assignment is clear.

@normanjaeckel @emanuelschuetze

**Comment by normanjaeckel** [comment]
Hm. Comments with id is ok for me. I do not remember the reason but I thought we could not use an extra model for the comment fields. Maybe it is because we want to handle it in the config.
