### ISSUE TITLE
Sorting of agenda items does not work

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3387]
Try to sort an agenda item in agenda sort view (by drag&drop). Moved item is not saved and moved back after autoupdate.

Any idea what's going wrong in last pull requests?

**Comment by emanuelschuetze** [comment]
I tested the last angular-ui-tree releases (2.22.6 and 2.22.5). Same problem. So it seems to be not a ui-tree problem. Because 2.22.5 was released in feb 2017.

**Comment by emanuelschuetze** [comment]
I tested also the master by going back until commit 9c1d2319ac50627806780b8e524236244bc7909f (from 2017-07-07). Same problem... Strange.

**Comment by FinnStutzenstein** [comment]
Works fine for me. Can someone confirm this issue?

**Comment by emanuelschuetze** [comment]
Retested successfully with angular-ui-tree 2.22.5! But it does NOT work with latest release (2.22.6).
=> So fix is to use 2.22.5 until angular-ui-tree is fixed. See #3397

**Comment by normanjaeckel** [comment]
Follow up reason for this.

**Comment by jsaalfeld** [comment]
With the rework of the client, this shouldn't be an issue anymore. If it still persists, please reopen.
