### ISSUE TITLE
Prevent autoupdate on first login.

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3392]
If a users is going to log in the first time, Django will update the hashed password in the database and an autoupdate will result: The [setter method](https://github.com/django/django/blob/master/django/contrib/auth/base_user.py#L103) will be called, because the hashed password is not up to date anymore ([hasher changed](https://github.com/django/django/blob/master/django/contrib/auth/hashers.py#L49)).

@normanjaeckel Can we update the encrypted password right at users creation time and do not trigger an autoupdate?

**Comment by normanjaeckel** [comment]
The problem of using the default has on user creation time is ... the time. The default hash is too slow for mass user creation. I propose that we override the checker method and skip autoupdate on Django's password hashing update thing.

**Comment by FinnStutzenstein** [comment]
Did I get this right? On creation the password is hashed with the default hasher, and we want md5 (given in the settings)?

**Comment by normanjaeckel** [comment]
I didn't have a look into the code. I thought we use md5 for mass user creation (mass import and also example data generator). We use this explicitly without anything in the settings. And the default hash is used by Django if the user logs in the first time.

Only for tests we adapt the settings and changed the default hash to md5 to fasten all tests.

**Comment by FinnStutzenstein** [comment]
Checked: we use md5 for all initial passwords in the user/serializer.py and also in the create-example-data plugin. But I think we can use the default hasher. I testet the creation of 5000 users and 5000 admins with the plugin and it took 6.2 seconds with md5 and 8.5 seconds with pbkdf2_sha256. For me this does not make any big difference here. Also the initial issue is fixed when using the default hasher.

**Comment by normanjaeckel** [comment]
Ok for me.
