### ISSUE TITLE
Disable last login field

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3395]
We try to make a read-only OS instance, so no writing to the database is permitted. On login, the `last_login` field for the user is updated. Because the DB raises an error, the user cannot log in.
@normanjaeckel Whats about not to delete this field in the DB, but just to disconnect [this signal](https://github.com/django/django/blob/eedc88bd4a8468c2a0daa8346c9b57183dd77782/django/contrib/auth/apps.py#L23)? If this is ok for you, I'll make a PR.

**Comment by emanuelschuetze** [comment]
+1

**Comment by normanjaeckel** [comment]
Ok for me. Maybe use a settings option to we can opt-in to disconnect the signal.
