### ISSUE TITLE
Motion cache is not updated

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#3396]
https://github.com/OpenSlides/OpenSlides/blob/37b2996b6cbc585988a921426e3c8fe613403b94/openslides/motions/serializers.py#L277

@normanjaeckel I think this is a bug. If you call
```python
state = motion.state
state.required_permission_to_see = 'some perm'
state.save()
```
then the root_rest_element of state (=Workflow) is updated through the autoupdate system and therefore only the cache of the Workflow is updated. But this means, that the cache of the motion is not updated, so there is still the old required_permission_to_see in it.

I think it is not a good idea to hardlink a string from one root_rest_element in a value from another. I do not understand why this field is needed at all. It should be possible to get the permission throw the state.

**Comment by normanjaeckel** [comment]
I agree. The client should care about this by resolving motion -> state -> required_permission_to_see

 @FinnStutzenstein Can you have a look at the client code?

**Comment by FinnStutzenstein** [comment]
@normanjaeckel @ostcar Yes, we should remove the `required_permission_to_see` from the motion model. But this is not a thing for the client. If you search for this property, I just get two hits: `motions/serializer.py` and in `motions/access_permissions.py`. So this field is not used on the client side, in fact the clinet already resolves the permission the way Norman described.

**Comment by normanjaeckel** [comment]
Ok. You can remove it.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Currently, we use in some custom workflow states the `required_permission_to_see` attribute. So please let us discuss before you remove it.

**Comment by emanuelschuetze** [comment]
Already reported in #3455:

Similar problem when a user gets a new permission (e.g. "motions.can_see_comments"). The user see the new comment fields but without content. Also reload does not helps because the restricted user cache contains was not updated (with new comment field values). Deleting the specific cache key helps. After reload the config values are visible in OpenSlides. - The REST api already shows the correct values.

Any hints how to fix this?

**Comment by ostcar** [comment]
see https://github.com/OpenSlides/OpenSlides/pull/3600

You have to [remove the cache for the user](https://github.com/ostcar/OpenSlides/blob/39da8f942fb4ef43603cb570122007c4b7c72b45/openslides/utils/cache.py#L399), when the permissions change

**Comment by emanuelschuetze** [comment]
> You have to remove the cache for the user, when the permissions change

@ostcar Do you have time to create a pull request?
