### ISSUE TITLE
Complete line is marked, if first word is changed

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3401]
If you just change one word, it should be marked red and the replacement should be next to it in green. Works fine for all words except the first. Easy to reproduce: make a motion with some text and make a change recommendation for just the first word. The full line gets marked.

@CatoTH Can you have a look?

**Comment by CatoTH** [comment]
@FinnStutzenstein The Pull Request https://github.com/OpenSlides/OpenSlides/pull/3408 should fix this problem
