### ISSUE TITLE
Wrong change reco, if text has styles

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3402]
If you change a word in a motion text with a style, not the single word gets marked as changed, but the full line. To reproduce make a new motion with text and change the foreground color of the full text to blue. Now there are span-tags with `style="color: #0000ff;"` between the p-tags and the text. With those extra span tags, the diff is wrong.
Removing the span-tags and make a new change recommendation, the diff is just one word as expected.

**Comment by CatoTH** [comment]
@FinnStutzenstein The Pull Request https://github.com/OpenSlides/OpenSlides/pull/3407 should fix this problem
