### ISSUE TITLE
Inline Editing inserts line breaks, colliding with diff

### ISSUE THREAD

**Issue by CatoTH** [OpenSlides/OpenSlides#3409]
If a motion is edited using the inline editing mode, new line breaks are inserted at an earlier point than where they should be.

**Comment by FinnStutzenstein** [comment]
So this is a (wrong?) behavior of the CKEditor? Do you have an idea for a fix or what we maybe can change in the CKEditor config?

**Comment by CatoTH** [comment]
For once, I've written a patch that handles data like that, once it's in the database like that. I'll have a look if we can normalize that when saving the HTML after inline-editing.

**Comment by jsaalfeld** [comment]
Since we will eventually ditch CKeditor and rewrite the whole client, this won't hopefully be an issue anymore. If it persists, this issue should be reopened.
