### ISSUE TITLE
Reduce Injections

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3453]
Split up/Idea of #3444 :
The controllers are heavily flooded with injections. This is the result of a very DRY like structure, great! But often some injections are always present: `gettextCatalog`, `ErrorMessage`, `Projector`, ...
Can we restructure the injections and bundle important things together. This should be done for core features as well as per-app.
The disadvantage is, that more things than necessary are imported, e.g. the `MotionCreateCtrl` does not need `MotionComments`. But this is in my opinion not a huge point. So we can simplify e.g. for the `MotionDetailCtrl`: It needs just `MotionBundle`, `ChangeRecommendationBundle`, `SomeCoreThings`, ..

Todo: Is there a way of doing this in angularjs?

Opinions?

**Comment by normanjaeckel** [comment]
+1

`MotionBundle` in this example can be a factory that provides the injections and it is easy to use a abbrevation:
```javascript
app
.factory('MotionBundle`, [
    `gettextCatalog`,
    function (gettextCatalog) {
        return {
            gettextCatalog: gettextCatalog,
        };
    }
])

.controller('MotionDetailCtrl', [
    'MotionBundle',
    function (MotionBundle) {
        var b = MotionBundle;
        ...
       var someString = b.gettextCatalog('...');
    }
])
```

I am not sure which abbrevation is the best here. Some better proposals?

**Comment by normanjaeckel** [comment]
Additionally: Please let's check if we can use a factory for the go-to-top-button, see #3444, after this issue is solved.

**Comment by jsaalfeld** [comment]
Since the client is completely rewritten, we should create a new issue if this problem persists.
