### ISSUE TITLE
Do not fire a watcher on hovering in list views

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3462]
Noticed in the motion list view: Add a `console.log("Watcher!");` to the motions-watcher. Now just hover from motion to motion. The watcher gets fired every time. This is a huge impact on performance.

I suspect the motion.hover to fire the watcher. Needs to be confirmed and fixed.

**Comment by emanuelschuetze** [comment]
Done in 3.0
