### ISSUE TITLE
Installation on Armbian fails

### ISSUE THREAD

**Issue by cweickhmann** [OpenSlides/OpenSlides#3477]
This is just a quick comment that apparently OpenSlides does not install on ARM-based Debian.
Following the install tutorial
`pip install openslides`
produces the following error
```bash
...
    creating build/temp.linux-armv7l-3.4
    creating build/temp.linux-armv7l-3.4/src
    creating build/temp.linux-armv7l-3.4/src/twisted
    creating build/temp.linux-armv7l-3.4/src/twisted/test
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/home/linaro/openslides/.virtualenv/include -I/usr/include/python3.4m -c src/twisted/test/raiser.c -o build/temp.linux-armv7l-3.4/src/twisted/test/raiser.o
    src/twisted/test/raiser.c:4:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/linaro/openslides/.virtualenv/bin/python3 -u -c "import setuptools, 
tokenize;__file__='/tmp/pip-build-fzfy91zh/twisted/setup.py';f=getattr(tokenize, 'open', 
open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))"
install --record /tmp/pip-2kyt_exe-record/install-record.txt --single-version-externally-managed
--compile --install-headers /home/linaro/openslides/.virtualenv/include/site/python3.4/twisted"
failed with error code 1 in /tmp/pip-build-fzfy91zh/twisted/
```

Does anyone have an idea why this is? Maybe it is easy to fix, and I'd be up for it (I think having a Raspi as Openslides Server at the projector would be bliss!) but I don't know where to start...

Bests!

**Comment by normanjaeckel** [comment]
Please check if you have installed some build tools: build-essential packages (``build-essential``) and header files and a static library for Python (``python3-dev``). This is because a dependency of OpenSlides (Twisted) is not prebuild (but I am not sure at the moment).

**Comment by cweickhmann** [comment]
Indeed installing `twisted` did the job. Actually, I had `build-essential`and `python3-dev`already installed and with a very similary setup it worked right out-of-the-box with an amd64 architecture.
Thanks for pointing the dependency to `twisted` out!
