### ISSUE TITLE
Do not send unnecessary autoupdates.

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3485]
![personal_note_autoupdate](https://user-images.githubusercontent.com/8439581/32664127-9929b6b0-c630-11e7-8298-728de7f2e77b.jpg)

My user gets autoupdates for personal notes without any content. We can skip autoupdates without a content to save some performance.

**Comment by FinnStutzenstein** [comment]
Ok, I do see the problem.
On one side [this code](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/utils/collection.py#L301) makes it clear that sending "deleted" is right for actual clearing the users data. I agree with this for I think every model except personalNote.

But on the other side, for personal notes, they do not get send to wrong users at any time. So sending deleted for personal notes is too much. Whats about to return None for "deleted", but some kind of other status code for personal notes, that this is OK, that no "deleted" autoupdate is send?

**Comment by normanjaeckel** [comment]
Hm. I do not think that it is a good idea to implement personal-note-specific code to the generic autoupdate system. But we can add a different status code object so that that autoupdate system skips the element.

**Comment by emanuelschuetze** [comment]
Looks like this issue is fixed by #3539. (Successfully tested with master - only one autoupdate if personal not is updated.). So closed.
Please reopen if something still open.
