### ISSUE TITLE
imported users are buggy

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3499]
To recreate: import a user (e.g. 'Max') with the csv import and the default password 'max'. Try to login with Max/max. This does not work. Then set a new password for Max and try to login with this one -> does not work either! (Why??)

Next, try to import a user with an empty default password. Use to login the generated one -> works. Change the password and use the new one -> works.

@normanjaeckel @emanuelschuetze I do not have any clue here.

**Comment by emanuelschuetze** [comment]
> To recreate: import a user (e.g. 'Max') with the csv import and the default password 'max'. Try to login with Max/max. This does not work. Then set a new password for Max and try to login with this one -> does not work either! (Why??)

Looks like you forgot to set the option "is_active" for the user in the csv import file, right? When I set this option I can successfully login with the imported user.

**Comment by jsaalfeld** [comment]
I think this won't be an issue anymore with the rewritten csv import in OS 3.0. If it is still an issue, please reopen.
