### ISSUE TITLE
Wrong sorting of motions/assignments/participants which begins with umlauts

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#351]
On /assignment/ they are sorted, but "Ö" comes after "Z". Maybe use other sorting options.

**Comment by emanuelschuetze** [comment]
@normanjaeckel can you try to evaluate how we can do this in angular list views?

**Comment by normanjaeckel** [comment]
Sorry, no time for this.

**Comment by jsaalfeld** [comment]
The sorting will be tested by @tsiegleauq. Eventually a sorting function will be implemented which is consistent along all spoken languages and browsers.

**Comment by tsiegleauq** [comment]
```
Array.sort( (a,b) => a.localeCompare(b))
```
done ;-)

@MaximilianKrambach takes care about sorting in OpenSlides 3. #3963

**Comment by MaximilianKrambach** [comment]
I'm unsure if this will be fixed as of #3963 and #4112

**Comment by ostcar** [comment]
works
