### ISSUE TITLE
Drag-and-drop file upload

### ISSUE THREAD

**Issue by serge1peshcoff** [OpenSlides/OpenSlides#3510]
Hello there.
I am the IT responsible of one big event (800+ people), where we are using OpenSlides to display presentations/videos on stage and on the Internet. And sometimes we need to upload a lot of files to the OpenSlides in a short time, and it takes a lot of time to fill all the values into the upload form, find the file in the filesystem etc.

I was thinking that it'd be cool to have the ability to upload new files by drag-and-dropping it. And I think that this could make a life more easier for a lot of OpenSlides users, because it's easier to drag file to the Files menu rather then pressing a button, filling in all the info and then clicking Save. And it should save some time if you need to upload a lot of time (especially if you don't have that much time, like in our case).

The way I see it, is to add the drag-and-drop area to `Files` area so the user can drag the file from the filesystem to it. The user would also be able to upload file the old way.

The new workflow would be something like that:
- user goes into `Files` tab and drags the file onto the area
- a `New file` dialog is displayed with the file path filled in
- user fills in other values, like file name, hidden/not hidden etc. and press `Save` and it's saved.

I want to implement it by myself, since it doesn't seem like a big deal to me (although I didn't look at the code structure thoroughly yet) and make a PR to this repository.

What do you think about this idea? Do you think that's a good idea and would you merge it into your repository if it'll be implemented properly?

(I've opened this issue as a platform for discussion, because I had some cases when I implemented some feature for some tool that I use and the author said that they didn't need it, making this work pointless, I don't want to implement something that won't be merged.)

Thanks in advance.

**Comment by emanuelschuetze** [comment]
Nice feature request! Yes, please create a pull request. We will test and review it. If everything ok we will merge it into OpenSlides core.

**Comment by serge1peshcoff** [comment]
Btw do you have an instruction how to run it locally for development and stuff like that? The thing is I didn't have a lot of Python experience so far, so I have no idea how to run it locally.

(Also it'd be cool to have this in README to make the life easier for the future developers, I can make a PR on that one I'll know how to do it)

**Comment by emanuelschuetze** [comment]
Please read the [DEVELOPMENT.rst](https://github.com/OpenSlides/OpenSlides/blob/master/DEVELOPMENT.rst) which should help your for setup a local development installation based on master.
