### ISSUE TITLE
Add line number mode to getTextByMode

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3512]
The config says, that the line length is only used, if the line number mode is not none.
If you get motion text with `getTextByMode`, the line numbering mode cannot be passed. We need this to fully specify, how we want to get the motion text [during the pdf creation](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/motions/static/js/motions/pdf.js#L342). Can you add an additional param `lineNumberMode`?

**Comment by CatoTH** [comment]
@FinnStutzenstein If I remember correctly, we agreed that ths should be handled in the PDF generation, just as in the HTML-view where the markup remains unchanged while the different modi are switched using CSS. In this pull request https://github.com/OpenSlides/OpenSlides/pull/3562 , I added the necessary statement that removes the linebreak if line numbering mode is set to "none". I hope, this is sufficient?
