### ISSUE TITLE
Upgrade python requirements

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3522]
Check release notes if we can easily upgrade our python requirements, e.g.:
* bleach to 2.x
* django to 2.0.x
* djangorestframework to 3.7.x
* jsonfield to 2.0.x
* setuptools to 38.x
* ...

**Comment by emanuelschuetze** [comment]
@normanjaeckel Can you do this in the next weeks?

**Comment by normanjaeckel** [comment]
Sorry. Maybe I do not have enough time. Lets have a phone call ...

**Comment by jsaalfeld** [comment]
should be done now.

Task for the not-so-easy-upgrades is over at #3582
