### ISSUE TITLE
cannot specify projector logo

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3551]
The look is important. Therefore I requested the feature to change easily the projector logo.

In OS 2.2b1 I see no in the projector settings this hint:

> "You can replace the logo by uploading an image and set it as the "Projector logo" in "files"."

Therefore I uploaded an image but cannot find a way to make this the projector logo, neither in the Files nor the Settings menu.

**Comment by emanuelschuetze** [comment]
You have to move the mouse over the table row with the uploaded logo file (PNG, JPG or GIF supported only for logo). Then you get a hover menu in the row with a small image icon to select where the logo should be displayed.

**Comment by emanuelschuetze** [comment]
This works already with 2.2b1.

**Comment by donovaly** [comment]
> Then you get a hover menu in the row with a small image icon to select where the logo should be displayed.

I get only this menu:
![missing-logo-setting-menu-item](https://user-images.githubusercontent.com/1828501/35514820-bb7a66c2-0507-11e8-8f13-9542df2b6239.png)

**Comment by donovaly** [comment]
Ah, one needs to set at first a permission to do that even for the admin account. This should be done automatically, see my last comment in issue #3557.
(I'll keep this bug report open until you decides  about the automatic database conversion.)

Besides this, many thanks for the projector logo feature! it works fine and is a big help since I am sure almost every user will have to use its custom logo image.

**Comment by emanuelschuetze** [comment]
@donovaly Please retest it with 2.2b2. Old databases should migrate now that a admin use has already the required permission to  manage logos.

**Comment by donovaly** [comment]
> Please retest it with 2.2b2.

I did, but now there is no longer a permission group for admins:
![screenshot-localhost 8000-2018-02-23-00-02-12](https://user-images.githubusercontent.com/1828501/36569168-fcbc1314-182c-11e8-89e7-d53ab70e462d.png)

Despite that I am logged in as admin, I cannot set the logo. I used a fresh OS 2.2 setup and copied there my database I used to write the docs for OS 2.1

**Comment by emanuelschuetze** [comment]
@donovaly Please retest with next beta (2.2b3). Migration should be fixed.

**Comment by donovaly** [comment]
Thanks, the migration of permissions is now done.
