### ISSUE TITLE
missing icon for add image button in text edit fields

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3553]
- create a new agenda item
- try to insert an image into the Text field

result: there is no icon for the button to do that:
![missing-image-button-icon](https://user-images.githubusercontent.com/1828501/35312735-477a12fc-00bd-11e8-8ab6-1715b4e175c7.png)
therefore users won't see it.

**Comment by FinnStutzenstein** [comment]
Thanks for reporting, I noticed this also some times ago and tried to fix this. Somehow the ckeditor changes the css classes of this button. I need to track this a little bit, so this is WIP
