### ISSUE TITLE
enhancement: enable automatic renumbering of agenda entries

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3554]
After changing the sorting of the agenda items one has to press the numbering button to update the numbers. This can be avoided: I cannot find a use case where one changed the sorting but wants to keep the old numbering, therefore the numbering should automatically be updated after the sorting is finished.

**Comment by FinnStutzenstein** [comment]
You may want this, if the user does not work with any numbering.

**Comment by donovaly** [comment]
> if the user does not work with any numbering.

Sure but OS knows is numbering is already used or not.

**Comment by emanuelschuetze** [comment]
A typical use case: If an agenda item is moved while a formal meeting all agenda items have to keep their old number that everyone can identifier the (already) printed agenda item.
=> WONTFIX
