### ISSUE TITLE
missing tooltip for export of single motion

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3555]
Motions have 2 buttons to export to PDF:

- one for the personal note. This button has correctly and usefully a tooltip
- one for the whole motion. This button misses a tooltip

**Comment by emanuelschuetze** [comment]
Confirmed.

**Comment by emanuelschuetze** [comment]
Fixed in #3687

**Comment by donovaly** [comment]
Confirmed fixed.
