### ISSUE TITLE
regression: no longer possible to add speakers to an agenda item

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3557]
- go with the mouse over an agenda item
- select from the context menu "List of speakers"

result: despite you are admin you can only put yourself to the speaker's list.
For assemblies where participants don't use OS, it is necessary that the admins can add every person to the speaker's list.

This is a regression to OS 2.1.

**Comment by emanuelschuetze** [comment]
You tested with an old database, right? - Then please go to the permission matrix ("groups") and add the permission "Can manage list of speakers" to the staff group. This is a new permission in 2.2.

**Comment by donovaly** [comment]
> You tested with an old database, right?

Yes. I used the one I used for OS 2.1 to create the docs.

>  - Then please go to the permission matrix ("groups") and add the permission "Can manage list of speakers" to the staff group. This is a new permission in 2.2.

Thanks, this works. But why isn't it automatically added when using an existing database with OS 2.2? I am pretty sure many users will use their existing databases to save work and therefore will get the same problem than I.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein @normanjaeckel Should we add database migrations to add the new permissions (for managing list of speakers and logos) for admin group? With new database everthing is ok. Only for migration from 2.1 to master the admin does not get the missing 2 permissions.

**Comment by normanjaeckel** [comment]
-1 for adding new permissions to existing groups. We can not ensure that a group pk=3 or a group with the string "admin" is intended for the user to something special. Maybe he uses the group for some other things. So a migrating user has to opt-in I think.

I am ok with a solution that adds the new permissions only to groups that have some of the old manage permissions that were required to use the (same) feature in former versions of OpenSlides.

**Comment by donovaly** [comment]
> We can not ensure that a group pk=3 or a group with the string "admin" is intended for the user to something special.

I think it is save to add the new permissions to these groups that have already all permissions except of the new ones. Then it is clear the database is from OS 2.1 and that users of this group are used to manage an assembly.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Can you implement the same migration process as for 'logos and fonts' in #3568 ?

**Comment by emanuelschuetze** [comment]
@donovaly Migration works for me in current master. Please retest with your old database.

**Comment by donovaly** [comment]
This seems to work now in beta3, many thanks.
