### ISSUE TITLE
Upgrade python requirements

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#3582]
Check the release notes and update the whole requirements. Especially lay an eye on:

- [ ] Channels 2.0
- [x] Django 2.0

Issues: There is no straight and easy upgrade path to use the new versions of those. They brake some stuff (i.E. response objects are now immutable and the structure of groups in channels changed).

**Comment by ostcar** [comment]
will be fixed with #3784

**Comment by emanuelschuetze** [comment]
Done for OS 3.0
