### ISSUE TITLE
Listen on IPv6

### ISSUE THREAD

**Issue by andi98** [OpenSlides/OpenSlides#3586]
Hey guys!

We're using OpenSlides on a IPv6-only virtual machine (we have a HTTPS-Proxy with IPv4 in front of it) and it looks like if the integrated webserver does not listen on IPv6 by default:

```
root@openslides:~# netstat -tuln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 ::1:25                  :::*                    LISTEN
```

It would be nice if the webserver could listen on IPv4 and IPv6 by default :)
Thanks!

**Comment by jsaalfeld** [comment]
In Version 1.10.8 of Django ipv6 is not enabled out of the box for the small web server. It will come by default with Version 2.0 of Django. Unfortunately the update from Django 1.10.8 to 2.x is not that easy, but will be documented in #3582.

The built-in webserver should not be used in a productive environment, therefore I would suggest to use a proper webserver (like nginx) in front. With that architecture you shouldn't have any issues with IPv6 support.
