### ISSUE TITLE
missing line wrap in list view

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3587]
- open the agenda list
- decrease the width of the browser window
- hover with the mouse over an agenda item

result:
![unbenannt](https://user-images.githubusercontent.com/1828501/36572722-addcae64-183d-11e8-93e8-13b3befd5f0f.png)

There is no automatic line wrap and the context menu protrudes over the margin.

**Comment by jsaalfeld** [comment]
This is fixed in the new layout of the openslides 3 client. If this issue still persists there. please reopen this issue.
