### ISSUE TITLE
Show information if speaker was added >1 for same list of speakers

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3589]
Feature request:
If a speaker was added the second time (or more) as speaker to the same list of speakers an information message with the count should show for the manager in detail view.

Use case: Each participant may add to a list of speakers not more than once. The manager has to check if a person was already on the list of speakers before he/she can be added.

**Comment by normanjaeckel** [comment]
> Is this behaviour desired?

Yes

**Comment by tsiegleauq** [comment]
![image](https://user-images.githubusercontent.com/10233032/63758792-9faf8d80-c8bc-11e9-8208-cc8a6d5c3a73.png)
