### ISSUE TITLE
Selected motions are not exported

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3591]
- go to the motion list
- select there one motion:
![screenshotundefined](https://user-images.githubusercontent.com/1828501/36598155-847ce458-18ab-11e8-8db8-97c9065d32de.png)
- now use the button "Export all"

result: I get a PDF or DOCX with all motions, but I want only the selected one "A1".

Strangely when I use the search field to select a motion I correctly only get the selected motion exported.

**Comment by jsaalfeld** [comment]
This will be fixed with the OS 3 client. If it persists there. Please reopen this issue.
