### ISSUE TITLE
Motion export button name is misleading

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3592]
The button to export motions is named "Export all". This is misleading because if you select only some motions, only the selected motions are exported. Therefore the button should just get the name "Export". Then it is clear that either all or only the selected motions will be exported.

**Comment by donovaly** [comment]
I see now that the button text changes from "Export all" to "Export filtered" when motions are filtered by the search field. However, when motions are filtered by selecting some the button text is still "Export all" instead of "Export filtered" or "Export selected".

This should be fixed together with issue #3591.

**Comment by jsaalfeld** [comment]
This will be reworked with the OpenSlides 3 client. If it will persist there. Please reopen the issue.
