### ISSUE TITLE
missing linebreak protection in projection of election results

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3593]
As you can see in this screenshot:
![screenshot-localhost 8000-2018-02-23-19-44-32](https://user-images.githubusercontent.com/1828501/36611163-e25c9bd2-18d2-11e8-8e6b-2a623eaf466d.png)

OS breaks the line between the value and the % character. This looks ugly. There should be a protected space between the number and the unit.
The line must also not be broken after the opening and before the closing brace.

**Comment by emanuelschuetze** [comment]
Fixed in #3593

**Comment by donovaly** [comment]
The bug is no longer visible but I don't understand how you assure it won't appear on other displays. I mean there should be a block group to prevent that "%)" is broken. Maybe you solution already assures this, then please ignore my comment.

**Comment by donovaly** [comment]
OK, as I assumed the fix for this bug introduces a new one: #3727
