### ISSUE TITLE
wrong decimal sign with German locale

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3594]
As you can see in this screenshot:
![screenshot-localhost 8000-2018-02-23-19-44-32](https://user-images.githubusercontent.com/1828501/36611163-e25c9bd2-18d2-11e8-8e6b-2a623eaf466d.png)

OS uses a dot as decimal sign. Since the local is German it must use a comma instead.

**Comment by jsaalfeld** [comment]
This will be reworked with the openslides 3 client. Please reopen if it will persist there.
