### ISSUE TITLE
enhancement: another symbol for absention in election results

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3595]
As you can see in this screenshot:
![screenshot-localhost 8000-2018-02-23-19-44-32](https://user-images.githubusercontent.com/1828501/36611163-e25c9bd2-18d2-11e8-8e6b-2a623eaf466d.png)

OS uses the average sign as symbol for abstention. I have no clever idea right now but this can lead to confusions and therefore another symbol should be used.

**Comment by jsaalfeld** [comment]
This will be reworked in the OS 3 client. Please reopen if the issue will persist there.
