### ISSUE TITLE
regression: missing number of positions in election list

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3596]
OS 2.1 kindly displayed also the number of positions in the election list:
![wahlubersicht](https://user-images.githubusercontent.com/1828501/36615271-e9eeb5c6-18df-11e8-9371-780b19af727b.jpg)

This helped a lot to keep the overview.
In OS 2.2b2 this information does no longer appear:
![screenshot-localhost 8000-2018-02-23-21-23-33](https://user-images.githubusercontent.com/1828501/36615245-de728542-18df-11e8-910d-0eaad5f5d864.png)

Please bring it back.

**Comment by emanuelschuetze** [comment]
This was a design decision while we redesign all list tables.
The number of posts is mostly obviously (normally "1", or you can read it in title, e.g. "5 Beisitzer/innen").
If the posts is not reached the badge number is marked orange. If candidates >= posts the badge is grey. Sould be enough.
=> Won't fix.

**Comment by donovaly** [comment]
> If the posts is not reached the badge number is marked orange. If candidates >= posts the badge is grey.

But nobody in the audience knows that. Of course one can add the number of posts to the title. The OS staff persons might forget this and my experience is that the audience is permanently asking "How many persons can be elected?" Therefore the number of posts should appear automatically. If you don't agree please add a setting to get this. This way admins like me can enable this while others are not bothered.

> The number of posts is mostly obviously (normally "1"

Ehm, no. For my next assembly we have for example to elect 2 chairman/woman, 4 vice chairman/woman, 2 revisors, 16 members of the managing board, 3 members of the arbitration committee, 12 members of the "Antragskommission", ...

**Comment by jsaalfeld** [comment]
This will be remodeled with the new client. If this issue still persists there. Reopen the issue.
