### ISSUE TITLE
regression: missing status and position number in election projection

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3597]
OS 2.1 displayed the status and number of positions in the election projection:
![wahl-projektor](https://user-images.githubusercontent.com/1828501/36615487-b594b41e-18e0-11e8-9076-cd91a8794a97.jpg)

In my experience the information of the number of posts is important for the participants to be able to follow the assembly.

In OS 2.2b2 this information does no longer appear:
![screenshot-localhost 8000-2018-02-23-21-32-35](https://user-images.githubusercontent.com/1828501/36615585-14a57f2e-18e1-11e8-96bd-df5e5138ef82.png)

This should be brought back.

**Comment by emanuelschuetze** [comment]
The meta box was annoying for many users of OpenSlides. So we decided to remove this information which is not really important (status is obviously, posts can be written in title or description).
=> Won't fix.
