### ISSUE TITLE
regression: missing bar in election result projection

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3598]
Don't laugh at me but in my party more then 50% of participants of an assembly are retired persons. Also younger persons often have problems to read all projected text. Therefore a good design of the projection view is important.

In OS 2.1 the election result therefore contained result bars:
![wahl-projektor-ergebnis](https://user-images.githubusercontent.com/1828501/36616324-9fa23d4a-18e3-11e8-8959-73ac5ae0914f.jpg)

In OS 2.2b2 they are missing:
![screenshot-localhost 8000-2018-02-23-21-48-04](https://user-images.githubusercontent.com/1828501/36616343-af53f364-18e3-11e8-9dbd-e283ac2c7513.png)

This is  a regression that makes it harder to realize the result with one look. If you are sitting away from the screen you might not be able to read the numbers and even if you can read them, it takes much longer to check the result than with the bar. With the bar you can see with one look who won. Therefore please bring the bar back.

**Comment by emanuelschuetze** [comment]
We decided to remove the bars to get more space for result. Especially with 16:10 or 16:9 projector ratio you have limited height. And its more important to see all candidates without scrolling than a nice bar.

**Comment by donovaly** [comment]
> We decided to remove the bars to get more space for result.

Well, the bars are one of the features my audience liked a lot. Color and structure helps. To save space, why aren't the numbers are placed behind the bars?

Therefore my proposal is to bring back the bars and write the numbers behind them.

**Comment by donovaly** [comment]
This issue popped up again on today's assembly. People want the bars.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze I would suggest to implement the bars again.

**Comment by emanuelschuetze** [comment]
Moved to milestone 2.3 - sorry.
