### ISSUE TITLE
wrong agenda import status information

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3601]
- try to import this agenda CSV file:
[Tagesordnung.txt](https://github.com/OpenSlides/OpenSlides/files/1755963/Tagesordnung.txt)

result: OS tells you that the topics will not be imported:
![screenshot-localhost 8000-2018-02-25-13-20-44](https://user-images.githubusercontent.com/1828501/36641357-bc1418c6-1a2e-11e8-8770-a51bbfdaade9.png)

But the preview is correct and when clicking on "Import 2 topics" they are correctly imported.

**Comment by emanuelschuetze** [comment]
Confirmed.

**Comment by donovaly** [comment]
This bug is not fixed. No matter if items have a duration or not, I get always the info:
![screenshot-localhost 8000-2018-03-11-05-28-23](https://user-images.githubusercontent.com/1828501/37249725-150ba5f2-24ed-11e8-8bff-ca1af94c5386.png)

The info "0 topics will not be imported" is superfluous and can lead to confusions.

**Comment by donovaly** [comment]
Importing motions has the same problem:
![screenshot-localhost 8000-2018-03-11-05-33-54](https://user-images.githubusercontent.com/1828501/37249755-d06f85ac-24ed-11e8-92df-1e1d8bc716a5.png)

**Comment by emanuelschuetze** [comment]
Fixed in #3687

**Comment by donovaly** [comment]
Confirmed fixed.
