### ISSUE TITLE
wrong Roman agenda subnumbering 

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3602]
- in the agenda settings select under "Numeral system for agenda items" "Roman"
- number your agenda

result: the subnumbers still appear with Arabic numbers:
![tagesordnung-speziell-nummeriert](https://user-images.githubusercontent.com/1828501/36642714-f63ec9c8-1a43-11e8-8cfb-62fda9e89c55.jpg)

Maybe II.1 is more clear than II.I however, in the books I own the use either always Arabic or Roman. If Roman.Arabic is preferable, OS should add a setting to assure or avoid this.

**Comment by jsaalfeld** [comment]
This will be reworked in the 3.0 client. If the issue still persists there, please reopen the issue.

**Comment by FinnStutzenstein** [comment]
I think that is a server issue, because there are numbered there.
@normanjaeckel can you verify this?

**Comment by emanuelschuetze** [comment]
> "... the behavior is desired."
