### ISSUE TITLE
regression: agenda cannot be reimported

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3603]
- create an agenda with a few items
- export it as CSV
- delete all your agenda items.
- import the CSV file you just exported to bring the agenda back

result: despite that the import preview is correct, nothing will be imported.

Here is my CSV file (only renamed to .txt that I can upload it to Github) I got when exporting my agenda with OS 2.2b2. importing is fails.
[agenda-export.txt](https://github.com/OpenSlides/OpenSlides/files/1756239/agenda-export.txt)

This is a regression to OS 2.1.

**Comment by emanuelschuetze** [comment]
Confimed with your agenda-export.csv

**Comment by emanuelschuetze** [comment]
server error while import: {"agenda_duration":["Dieses Feld darf nicht Null sein."]}

**Comment by donovaly** [comment]
This bug is not fixed because now the time is overwritten:
![screenshot-localhost 8000-2018-03-11-05-17-47](https://user-images.githubusercontent.com/1828501/37249638-bce4d5ca-24eb-11e8-9d8b-d59c2d73ba7d.png)

To create the screenshot I used OS' example file:

Titel,Text,Dauer,Kommentar,Interner Eintrag
Demo 1,Demo text 1,1:00,test comment,
Break,,0:10,,1
Demo 2,Demo text 2,1:30,,

**Comment by emanuelschuetze** [comment]
Fixed in #3687

**Comment by donovaly** [comment]
Confirmed fixed.
