### ISSUE TITLE
missing translation in agenda export file

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3604]
- use OS with German menus
- export the agenda as PDF, DOCX and CSV

result: For the PDF and DOCX the filename is the German word "Tagesordnung" while for CSV it is the English "agenda-export".

**Comment by emanuelschuetze** [comment]
same for motions-export.{docx|csv} and users-export.csv.

**Comment by donovaly** [comment]
Please reopen, this is also not fixed with the build from today.

**Comment by emanuelschuetze** [comment]
Retested with current master: CSV-Export file calls "Tagesordnung.csv".
@donovaly Please confirm.

**Comment by donovaly** [comment]
Confirmed fixed. Note, that in beta 3 the export to PDF fails now, see #3726.
