### ISSUE TITLE
enhancement: allow to specify filename for agenda exports

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3605]
When exporting the agenda OS doesn't allow you to choose a filename. This should be possible to avoid extra work for the OS admins because every agenda needs to have its own unique name. Currently the exported file needs to be renamed after the export. It would be better to set the correct name directly when exporting.

**Comment by tsiegleauq** [comment]
whenever you export something you download it. The web browser is then asking you where to save the file you are downloading and how to name it. That should be enough to specify the filename.
