### ISSUE TITLE
Cannot deselect logo/font file

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3606]
1. Upload a logo file.
2. Set a logo config in mediafile list view, e.g. "pdf header logo"
3. Try to deselect the marked logo (by unselecting "pdf header logo").
=> Problem 1: Server error: `PUT http://localhost:8000/rest/core/config/logo_pdf_header/ 400 (Bad Request)`
-> Response: {"detail":"path has to be given."}
4. Delete logo file
=> Problem 2: PDF export error: Cannot create new pdf because pdf header logo is required. 404.
Workaround: Update config entry in database manually and remove logo path for config.

Same problem for custom font files. Cannot deselect an already marked font file.

**Comment by donovaly** [comment]
related to #3625
