### ISSUE TITLE
missing translation of group names

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3607]
- use OS with German menus
- open the group rights view
- try to change the name of the group "Mitarbeitende"

result: OS uses the English term "staff" for this group in the dialog:
![screenshot-localhost 8000-2018-02-27-02-12-46](https://user-images.githubusercontent.com/1828501/36705245-63ee97a2-1b64-11e8-9a8e-4b2906275cc7.png)

**Comment by donovaly** [comment]
Please reopen, with the build from today this is not fixed.

**Comment by emanuelschuetze** [comment]
Can not see any missing translations in group dialogs. Please retest with next test version and clear browser cache.

**Comment by donovaly** [comment]
This is now fixed in beta 3.
