### ISSUE TITLE
enhancement: allow participant names presence feature

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3608]
One of the new features of OS 2.2 is the feature to quickly change the presence of persons. For party assemblies with several hundred participants this can be a useful feature. However, as it is, it is not useful for every admin:

At the moment one can only insert there the participant number to change the presence. As e.g. party assemblies don't use numbers but names (many members don't want to be a number) it should be possible to insert also names to change their presence.

**Comment by jsaalfeld** [comment]
I think this will be possible with the 3.0 client, since the searches will be reworked completely. If not, please reopen.
