### ISSUE TITLE
Include File and Presentation-Support for PowerPoint and Impress

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#3609]
In the last couple of days I heard from several sources and potential users that this essential feature is missing from OpenSlides. They'd like to upload PowerPoint or Impress Slides to use them in Presentations, so they don't have to switch screens between OpenSlides and the Presentation Software. 

In #128 @normanjaeckel said that this won't be fixed, but this issue is also more then 4 years old and a lot has happened ever since. I'd like to see a new discussion about this topic.

**Comment by geniusupgrader** [comment]
I really think this would be a killer feature. It gets into the realm of controlling other presentation programs. But don't know if this is the goal of OpenSlides.

@jsaalfeld: I would suggest to close this issue and move it into more manageable chunks:

- PowerPoint support

Probably it will be easier to implement other JavaScript/HTML5 Presentation Frameworks first, like: 

- impress.js (as you mentioned)
- or reveal.js

This could be also an extra issue:

- External File support

But what exactly do you mean by file support? which files?

**Comment by normanjaeckel** [comment]
Hm. New discussion is ok for me.

In the past we said that OpenSlides is not a redesign of PowerPoint. So everybody who wants to show slides on an event should export them to PDF. OpenSlides supports PDF presentations. The question for me is: Why do people want to use native PowerPoint or Impress and not PDF files? Because you have nice transitions?

I am not sure how you can display a PowerPoint screen inside a browser.

**Comment by geniusupgrader** [comment]
I was yet not really aware that OpenSlides supports PDF...
But with Impress and reveal.js: of course its beneficial, because you use your native tool for building the presentation, then its open source and its based on text imput which allows all kinds of cool things like git support and the like. And yes.. nice transitions..

**Comment by jsaalfeld** [comment]
> Why do people want to use native PowerPoint or Impress and not PDF files?

My assumption would be, that this is something the user knows. This is especially the case for smaller groups that use OpenSlides, maybe even without a designated administrator or without a video control workstation. For the non tech-savvy user it may be intimidating to export PDFs and use that as a file format. A PDF export may be normal for experienced users, but it certainly is not a thing for everyone.

A big technical issue I see with letting the users use Impress of PPT is the handling of fonts and other custom details in their presentation. In my opinion it would be rather difficult (if not impossible) to handle those correctly.

If my assumption is true, it would may be sufficient to deliver some kind of explanation for the user, how  they can export their presentations to PDF and use it within OpenSlides.

PS: Any kind of explanations for the users would be a great addition to OpenSlides ;)

**Comment by geniusupgrader** [comment]
PDF embedding from powerpoint and libreoffice impress is fine and sufficient. Though, some more explanation to import pdf in openslides (and maybe an explanation exporting pdf from powerpoint?) could be useful.

I open a new feature request for embedding html presentation frameworks (like reveal.js and impress.js).

**Comment by lennard7001** [comment]
How about adding the support to watch websites in an iframe. Then you can export ypu PPT as HTML and sometimes People want to show a website without opening a new browser window. This would solve 2 problems, i think.

**Comment by jsaalfeld** [comment]
After a long discussion this could be theoretically possible with #221. But in general there won't be a special implementation fort this.
