### ISSUE TITLE
Mark Participants as "Present" in bulk (or enable to elect people that are not marked as present)

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#3610]
Not every event has something like a "check-in". Mostly those check-ins are to ensure that only people can vote that are "present". But what happens if someone has a distributed event and uses OpenSlides or if someone should be elected that is not present?

The last use-case I heard was about an event were some members can elect people of a 10k Members-Pool. Of course not everyone of those 10k people is present, but everyone of those 10k members could be a candidate for the election. Therefore the current implementation of "only present members could be elected" is not valid for every use case. Thus I would propose to either mark (or unmark) Participants as "Present" in bulk (like in the "select" option in the Participants view, but with "set" options for all selected members) or to enable at an election, that also people can be voted, that are not marked as present.

In case of an distributed event, could the "Present"-Flag also be set, as soon as the user logs in on the time of the event?

**Comment by emanuelschuetze** [comment]
works already in 2.2b2
