### ISSUE TITLE
Add new Participants on-the-fly

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#3611]
For some events it is not possible to gather and import all participants beforehand. Therefore a possibility to add participants on-the-fly is needed.

The idea is, that on every field, where you can select a participant (i.E. Elections, List of Speakers, ...) needs a possibility to add new participants on-the-fly. This could be archived by a button next to the search-box or via an option that sits above the results or if no result is found. This Option should have a similar layout to the current _add Participant_ option, but just contain 3 elements (First Name, Last name and Structure level). That way more open discussions and meetings can be held, were no actual list of participants is known beforehand.

**Comment by normanjaeckel** [comment]
I think we had such a feature in v1.x, right?

**Comment by jsaalfeld** [comment]
> I think we had such a feature in v1.x, right?

Never heard of that feature before. I think it would add to Featureset of OpenSlides significantly and open it up for organisations and events with a more open approach (maybe even more, if we allow just to enter one of the 3)
> (First Name, Last name and Structure level)

**Comment by frederikheld** [comment]
Is this feature already released? It was added to milestone 3.0 which is already closed. But I can't find it. Do I need to activate it somewhere before it shows up in the UI?

**Comment by tsiegleauq** [comment]
@frederikheld 
> It was added to milestone 3.0 which is already closed
was postponed to TODO, which means that it was not implemented in 3.0 and not on schedule for any upcoming release.

Since #5307 the the List Of Speakers has an option to create users if they were not found, which addresses this issue. We did not, however, implemented it for any other search selector
