### ISSUE TITLE
wrong names when participants are created by motion import

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3615]
I want to import a motion. In the motion import CSV I have e.g. these lines:
`B1,Titel 2,Text 2,Begründung 2,Prof. Dr. Hans Wurst,Kategorie B,,,,`
`,Titel 3,Text 3,Begründung 3,Dr. Hans Schulze,,,,,`

- I import and in the preview OS tells me that it will create two new participants:
![screenshot-localhost 8000-2018-03-01-03-08-58](https://user-images.githubusercontent.com/1828501/36823645-6c82a7dc-1cfe-11e8-848a-b25d577dca7d.png)

- now check how the 2 new persons were imported:
![screenshot-localhost 8000-2018-03-01-03-09-35](https://user-images.githubusercontent.com/1828501/36823665-82c61a60-1cfe-11e8-9d60-569cf63053c9.png)
and
![screenshot-localhost 8000-2018-03-01-03-10-04](https://user-images.githubusercontent.com/1828501/36823660-7cf66324-1cfe-11e8-95ab-483ab335c85a.png)

result: the title is not recognized by OS when new users are created via motion imports.
This is not easy to fix because it is unknown what is a title. It can be "Herr A. Schulz" (the title is "Herr") or "A. Tom Schulz" (the title is "A." for a certain reason) or "Tom A. Schulz" (without a title and "Tom A." is the given name).
The only way to fix this is to require in the CSV file for the motion author field to use this format:
`"title,given name,family name"`
So the quotes form the name block and the commas define the separation in the name. For example the line in the CSV file would then look like this one:
`B1,Titel 2,Text 2,Begründung 2,"Prof. Dr.,Hans,Wurst",Kategorie B,,,,`

**Comment by jsaalfeld** [comment]
Since the CSV report was rewritten, this shouldn't be an issue anymore. Please reopen if otherwise.
