### ISSUE TITLE
regression: missing translation for Recommendation

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3618]
- use OS 2.2 with German menus

result:
![screenshot-localhost 8000-2018-03-02-01-53-29](https://user-images.githubusercontent.com/1828501/36877910-e4e0a9ae-1dbc-11e8-8baa-c13c957f70fc.png)

This is a regression to OS 2.1.

**Comment by donovaly** [comment]
Still in OS 2.2b4.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Didn't we just want to put the`{{ config('motions_recommendations_by') }}` into translation tags and mark the word `Recommendation`? I'll put this into a PR.

**Comment by emanuelschuetze** [comment]
@donovaly: You have to enter/change the motion config settings 'Name of recommender' . It's a custom input field - the content was not translated. So please check and change the value. By default this field is empty. Maybe you entered the English string "Recommendation". Typically users enter a committee like "Antragskommission" or similar.
=> It's not a translate issue. So closed.

**Comment by donovaly** [comment]
> You have to enter/change the motion config settings 'Name of recommender'

I did this, it is "Empfehlung". So the bug exists for me. Please reopen.

Please don't close bugs before i have a chance to have a look.

**Comment by emanuelschuetze** [comment]
Sorry, this works for me as expected:
* Create new database where config 'Name of recommender' is empty.
* Enter "Empfehlung" into this field.
* Go to motion detail view. In each language the string "Empfehlung" is visible. This label does NOT looking for any translation. 

So no translation bug. Please verify and close. I moved it to 2.3 for you.

**Comment by jsaalfeld** [comment]
Since there was no action here in the last couple of month, this can be closed.

Hopefully it won't be an issue anymore with client version 3.0.
