### ISSUE TITLE
enhancement: allow to set motion block to "Show as agenda item" in the list of blocks

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3619]
- create a new motion block
result: you can set the option "Show as agenda item"

- create another new motion block and don't set "Show as agenda item"
- later you decide that this block should be shown in the agenda and try to set the option in the list of motion blocks.
result: there is no way to show a block on the agenda if you haven't done this when creating the block.

What you can do is to change the state in the agenda list. it took me while to see this, therefore it would be helpful to allow to set "Show as agenda item" when editing existing blocks in the block list.

**Comment by jsaalfeld** [comment]
With the remodeling of the client in version 3.0 this shouldn't be an issue anymore. Reopen if otherwise.
