### ISSUE TITLE
misleading button name for personal notes of motions

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3620]
- create a motion
- open the motion and scroll down to the personal note

result: the button to create/edit the personal note is named "inline editing".:
![screenshot-localhost 8000-2018-03-02-03-32-19](https://user-images.githubusercontent.com/1828501/36880694-57456b26-1dca-11e8-82ba-5cd2b98fbd44.png)
This is misleading because the personal note has nothing to do with the motion text and how it is edited. The button should therefore only have the name "Edit".

**Comment by jsaalfeld** [comment]
This won't be an issue anymore with the 3.0 client. If otherwise, this should be reopened.
