### ISSUE TITLE
wrong term in motion settings

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3622]
In the motions settings one can set the "Prefix for the identifier for amendments".
- set there the prefix "-Ä"
- now create an amendment of a motion with the identifier "Kat A-1"

result: the amendment motion gets automatically the identifier "Kat A-1 -Ä 1".
So in fact it is a suffix because the set "-Ä" will be attached BEHIND the identifier. So the setting should get the name "Suffix for the identifier for amendments"

**Comment by jsangmeister** [comment]
If still relevant: It is, in fact, a prefix. If you create a motion with number (identifier was renamed to number in OS4) `42` and create an amendment for that, the amendment gets the number `41-Ä01`. So the `-Ä` is the prefix for the "actual" amendment number, which is `01`.
