### ISSUE TITLE
weird half-characters in go to line dialog of motions

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3623]
- open a motion
- click there on the go button to highlight a certain motion text line

result: there are 2 half-characters in the field for the number:
![screenshot-localhost 8000-2018-03-03-02-21-10](https://user-images.githubusercontent.com/1828501/36928846-dc57d9e2-1e89-11e8-82d7-285e3dcfafa2.png)

**Comment by jsaalfeld** [comment]
Since the new client is completely rebuild, I think this wouldn't be an issue anymore. Reopen if this will persist in client version 3.0.
