### ISSUE TITLE
projector logo and header image cannot be unset

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3625]
- set a file as logo for
 ~ Projector logo
 ~ Projector header image

result: the logos appear correctly

- now unset both logos

result: both logos are still in the projector and the projector preview. Refreshing the browser window doesn't help. This bug only appears for these 2 logo types, for the other logo types unsetting works correctly.

**Comment by donovaly** [comment]
> This bug only appears for these 2 logo types, for the other logo types unsetting works correctly.

This is wrong. They disappear in the current OS session but after restarting the OS server they reappear.

This bug is very annoying because one wrong click in the logo settings will destroy your header projector bar permanently and there is no way to repair this. In my case one accidental click leads to this ugly projector ooutput:

![screenshot-localhost 8000-2018-03-04-01-39-48](https://user-images.githubusercontent.com/1828501/36940831-fa57cace-1f4c-11e8-91cd-bd3a6e6c1fe1.png)

Even deleting the image I accidentally set as logo doesn't fix it.

**Comment by FinnStutzenstein** [comment]
Duplicate. Should be fixed with #3630
