### ISSUE TITLE
regression: new ballot is not displayed

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3627]
- create a new election
- start there a new ballot

result: the ballot is not displayed:
![screenshot-localhost 8000-2018-03-04-01-25-58](https://user-images.githubusercontent.com/1828501/36940784-0becc764-1f4b-11e8-9cfb-fc39e9aefe56.png)

it took me a while to understand that I have to clock on the word "Ballot 1". Then I can see the ballot and do something:
![screenshot-localhost 8000-2018-03-04-01-28-28](https://user-images.githubusercontent.com/1828501/36940794-5d2c228c-1f4b-11e8-92f3-3ab8600dd747.png)

OS should directly display the new ballot.
This bug only appears once. For example if you delete the ballot and create a new one the ballot is already automatically displayed.

This is a regression to OS 2.1.

**Comment by donovaly** [comment]
Still in OS 2.3b4.

**Comment by FinnStutzenstein** [comment]
Same problem as in #3104 .

**Comment by emanuelschuetze** [comment]
Will be fixed (with new controls) in OS 3.0.
