### ISSUE TITLE
Upgrade angular-pdf

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3632]
In #3590 we locked angular-pdf to v1.3.0 which fixed the reported bug #3552 with firefox:
"angular-pdf 1.3.1 does not work in Firefox with PDF documents >127kb."

Note for upgrading of angular-pdf (and pdf.js): Test large (>127kb) example pdfs in Firefox carefully.

**Comment by jsaalfeld** [comment]
* [test_130534.pdf](https://github.com/OpenSlides/OpenSlides/files/1784802/test_130534.pdf)
* [test_131702.pdf](https://github.com/OpenSlides/OpenSlides/files/1784803/test_131702.pdf)

Those are the testing PDFs. [test_130534.pdf](https://github.com/OpenSlides/OpenSlides/files/1784802/test_130534.pdf) works with newer versions, but * [test_131702.pdf](https://github.com/OpenSlides/OpenSlides/files/1784803/test_131702.pdf) doesn't.

**Comment by jsaalfeld** [comment]
This (hopefully) shouldn't be an issue anymore with client version 3.0. We will reopen if it appears again.
