### ISSUE TITLE
Feature request: embedding web presentation frameworks (like reveal.js and impress.js)

### ISSUE THREAD

**Issue by geniusupgrader** [OpenSlides/OpenSlides#3635]
Because openslide is based on web technologies, it should support embedding other web presentation frameworks (like reveal.js or impress.js).

(Referencing #3609)

**Comment by jsaalfeld** [comment]
We discussed this internally. Maybe it will be possible with #221 to embed such a presentation as an iframe, but in general it will not be implemented for this cause.
