### ISSUE TITLE
Title-Change-Recommendations are not in every case possible

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3645]
- open a motion and click on the plus sign before its title
- insert a change recommendation and save it
- delete the recommendation because you have e.g. made a typo
- try to create a new, this time correct, recommendation

result: this is not possible. One has first to go back to the motion list, then open the motion again.

Title-Change-Recommendations are new since #3626.

**Comment by CatoTH** [comment]
@donovaly I cannot really reproduce this error right now. Did you switch to original view again when trying to re-create the second change recommendation (as this is not possible in diff-view)?

**Comment by donovaly** [comment]
I am using a build Emanuel sent me on Friday.

> Did you switch to original view again

1.  I go with the mouse before the first character of the title and press the appearing plus button to create a change
1. I delete the title change recommendation by pressing the red trash can icon behind the thumb icons
1. I go with the mouse before the first character of the title and now I don't get the plus button to create a new change

**Comment by CatoTH** [comment]
Do you see the menu to switch between different change recommendation modes?
<img width="604" alt="bildschirmfoto 2018-03-11 um 17 32 52" src="https://user-images.githubusercontent.com/533440/37255833-56e31f9a-2552-11e8-8bfb-afb1c6925153.png">
Does is make any difference if you switch to the "Original Version"? Creating recommendation is done in the Original Version, while deleting them with the trash icon is on the "Diff version"...

**Comment by donovaly** [comment]
> Do you see the menu to switch between different change recommendation modes?

Yes. In this view I deleted the change and wanted to add a new one subsequently.

> Does is make any difference if you switch to the "Original Version"?

I don't understand. I can only delete the change in the diff version, I do this, Afterwards I cannot select a version because I am correctly back to the motion without any changes. In this state I just want to create a new title change.

**Comment by CatoTH** [comment]
Ok, I think I found the problem. The motion does not switch back to the original view after deleting the title change recommendation if it is the last one, therefore this problem ocurres. I've created a patch for it.

**Comment by donovaly** [comment]
See also the related bug #3672.
