### ISSUE TITLE
Possibility to change to a dyslexic friendly font

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#3653]
According to [Wikipedia](https://en.wikipedia.org/wiki/Dyslexia) Dyslexia "[...] affects 3–7% of the population, however, up to 20% may have some degree of symptoms."

To be more accessible (i.e. read longer motions etc), out would be nice to have the possibility to change to a dyslexic friendly font. There are free to use fonts out there to use for free.
 * https://opendyslexic.org/download/

The new font should, like language, be a user setting, so everyone that can read better with such a font could access OpenSlides.

**Comment by FinnStutzenstein** [comment]
If you can get the font as woff or ttf, you can upload it in the files section and set this font for Pdf and the projector. The only thing needed is to change the font of the main page itself, but this is easy. If this is required, I'll create a PR tomorrow to change the font of the main page.

**Comment by emanuelschuetze** [comment]
>  If this is required, I'll create a PR tomorrow to change the font of the main page.

Not required for our 2.2 release - so let us move it to a later milestone.

**Comment by jsaalfeld** [comment]
@FinnStutzenstein to this date, the following packages are available:

* [OpenDyslexic2 Alt-A (Windows, MacOS, Linux OTF).zip](https://github.com/OpenSlides/OpenSlides/files/1815003/OpenDyslexic2.Alt-A.Windows.MacOS.Linux.OTF.zip)
* [OpenDyslexic2 (Windows, MacOS, Linux OTF).zip](https://github.com/OpenSlides/OpenSlides/files/1815004/OpenDyslexic2.Windows.MacOS.Linux.OTF.zip)
* [OpenDyslexic 3 (Beta - Windows, MacOS, Linux TTF).zip](https://github.com/OpenSlides/OpenSlides/files/1815005/OpenDyslexic.3.Beta.-.Windows.MacOS.Linux.TTF.zip)
* [OpenDyslexic For Android (CyanogenMod Theme).zip](https://github.com/OpenSlides/OpenSlides/files/1815006/OpenDyslexic.For.Android.CyanogenMod.Theme.zip)
* [OpenDyslexic Mono (Windows, MacOS, Linux OTF).zip](https://github.com/OpenSlides/OpenSlides/files/1815007/OpenDyslexic.Mono.Windows.MacOS.Linux.OTF.zip)

(I'm not sure how a font is in "beta" state, though)
