### ISSUE TITLE
enhancement: Missing high-DPI support

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3662]
- start the OS server on a laptop with high-DPI resolution (in my case it is a laptop with Win 10)
result: the font in the OS window is blurred:

![blurred-font](https://user-images.githubusercontent.com/1828501/37628830-a14f1004-2bdb-11e8-81bf-dc147b5b2c72.jpg)

This is how it looks on non-high-DPI screens:
![clear-font](https://user-images.githubusercontent.com/1828501/37628849-b6e25dcc-2bdb-11e8-8f5b-0812933e3cc9.jpg)

**Comment by jsangmeister** [comment]
tool no longer exists
