### ISSUE TITLE
enhancement: setting to define where motion numbering begins

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3664]
In 2 events with OS 2.2 the main problem was that one cannot define how motions are numbered. Some motions must be numbered beginning with the title (including the lines consumed by the title), some motions are numbered excluding the title lines. 

The problem in the particular case was that some motions were introduced with the motion title numbered and the rules say that the numbering cannot be changed. Therefore in my events the participants sat there with the printed out PDF and different line numbers on the projector.

It would help to set at least an offset for the numbering. So that e.g. the admin can begin the numbering with 3 if the title consumes 2 lines.

**Comment by jsangmeister** [comment]
OS4 now has a `start_line_number`
