### ISSUE TITLE
missing possibility to change the page in agenda and motion list

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3667]
My experience is that assemblies are hectic. Participants and the assembly managers requested frequent changes in displaying a certain motion, the agenda list, the motion list etc.

For me it was hard, because to switch to a certain list page I had to scroll down. There is only at the bottom of the list a way to change the list page:
![page-switch-bottom](https://user-images.githubusercontent.com/1828501/37627135-59056b70-2bd3-11e8-9882-1c1c8d698249.jpg)
It would be very helpful if these buttons are also at the beginning of the list.

**Comment by donovaly** [comment]
I see now that there is a way to switch between pages on top of the list. For consistency reasons OS should use the same button layout on top of the list and below it.

**Comment by FinnStutzenstein** [comment]
I'm strongy against putting new buttons on top of the list. This would just consume more space and will blow up the layout with even more buttons. The little arrows are nice and subtle, the pagination buttons below the list can be bigger.

**Comment by emanuelschuetze** [comment]
I agree with @FinnStutzenstein: Keep the current (small) pagination buttons.

=> Closed.

**Comment by donovaly** [comment]
> This would just consume more space and will blow up the layout 

OK then. I'll document this now for OS 2.2.
