### ISSUE TITLE
missing info when server is stopped

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3669]
- stop the OS server
result: OS never tells when it finished to stop the server:
![stopping-server](https://user-images.githubusercontent.com/1828501/37628958-4cf7da80-2bdc-11e8-9622-c1a2085b72a2.jpg)

I think it should tell when it is finished that the admin knows when he can close the window.

**Comment by FinnStutzenstein** [comment]
Not relevant anymore since there is no portable version in OS3.3+
