### ISSUE TITLE
diff version of changed motion not displayed

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3670]
- in a motion make an inline change
- project the motion and select there to display the diff version

result: only the original version is displayed:
![screenshot-localhost 8000-2018-03-20-02-31-53](https://user-images.githubusercontent.com/1828501/37630813-e7e013a0-2be6-11e8-8c88-683b3655e1f0.png)

**Comment by emanuelschuetze** [comment]
Should be fixed with #3685. @donovaly Please reopen if not fixed.
