### ISSUE TITLE
inline editing must preserve original line numbering

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3671]
- use outline numbering in motions
- some participant applies to add a sentence to the motion. Therefore use inline editing and add the sentence
- the assembly agreed to the change, thus accept the change

result: the line numbering has changed. Now the participants have their printed motion text with other line numbers than the projected text. My experience is that this causes troubles.

**Comment by tsiegleauq** [comment]
Cannot really reproduce anymore. Inline editing dies also not exist anymore.
Not sure if this is relevant or not, but it will most likely not be targeted in 3.0

**Comment by donovaly** [comment]
> Cannot really reproduce anymore. Inline editing dies also not exist anymore.

Closing then.
