### ISSUE TITLE
Title-change recommendations impossible after inline edits

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3672]
- make a change to a motion via inline editing
- view either: the changed, diff or final version
- try now to make a title change

result: this is impossible. Only if one views the original version one can change the title. This is not suitable in practice. It is simply too stressy to check that the view is the original one. I failed in a real assembly to  make a title change because I realizes the issue first after the assembly.

**Comment by donovaly** [comment]
Related to bug #3673

**Comment by tsiegleauq** [comment]
It seems it can not be reproduced for OpenSlides 3.
Closing for now, please reopen if you notice this again.
