### ISSUE TITLE
Rework of motion numbering exception handling

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#3680]
See #3652.

We should not raise Validation error inside the transaction block and also catch IntegrityError outside this block. One of this things is enough.

**Comment by FinnStutzenstein** [comment]
We added the Validation Error, so the user gets better information instead of just returning that _something_ was wrong. Maybe we just exit the loop and set an `error` variable, so we can make a response after the atomic block.

**Comment by normanjaeckel** [comment]
Sounds better.
