### ISSUE TITLE
Dockerfile failing at step 9

### ISSUE THREAD

**Issue by lennard7001** [OpenSlides/OpenSlides#3703]
When you try to
`docker build https://raw.githubusercontent.com/OpenSlides/OpenSlides/master/Dockerfile`

You'll just get get
`Step 9/29 : COPY package.json yarn.lock bower.json gulpfile.js /app/`
`COPY failed: stat /var/lib/docker/tmp/docker-builder090560909/package.json: no such file or directory`

I would try to find it out myself right now but I don't have time today anymore. If someone knows a fix it would be nice since I'm working on a better Docker integration.

**Comment by jsaalfeld** [comment]
Since today we got a repository that takes care of starting OpenSlides in a virtualized environment:

https://github.com/OpenSlides/openslides-docker
