### ISSUE TITLE
Can't get plugin working with OpenSlides 2.2b3

### ISSUE THREAD

**Issue by serge1peshcoff** [OpenSlides/OpenSlides#3711]
I'm trying to make this plugin https://github.com/OpenSlides/openslides-presenter work with OpenSlides 2.2b3, but doesn't work somehow. I've forked it, removed the limit from requirements.txt so I would be able to install it, but when I run it, it fails with this error:

```
Error: [$injector:modulerr] Failed to instantiate module OpenSlidesApp.site due to:
[$injector:modulerr] Failed to instantiate module OpenSlidesApp.openslides_presenter.site due to:
[$injector:nomod] Module 'OpenSlidesApp.openslides_presenter.site' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.11/$injector/nomod?p0=OpenSlidesApp.openslides_presenter.site
minErr/<@http://agora.aegee.org:8000/static/js/openslides-libs.js:10292:12
module/<@http://agora.aegee.org:8000/static/js/openslides-libs.js:12357:17
ensure@http://agora.aegee.org:8000/static/js/openslides-libs.js:12281:38
module@http://agora.aegee.org:8000/static/js/openslides-libs.js:12355:14
loadModules/<@http://agora.aegee.org:8000/static/js/openslides-libs.js:14893:22
forEach@http://agora.aegee.org:8000/static/js/openslides-libs.js:10549:11
loadModules@http://agora.aegee.org:8000/…
```

I'm pretty sure because it can't load `/js/openslides_presenter/base.js`, which is required, and it's not there indeed.

How do I install plugins in 2.2 so they would work? And if they need to be rewritten in some way, what is required?

**Comment by FinnStutzenstein** [comment]
Hi, wich setup do you use (windows portable, a `manage.py` command like `start` or `runworker`)? What does you mean with "is not there"? The js files should be located in `openslides_presenter/static/js/openslides_presenter/` and the first `openslides_presenter` directory should be copied (or linked) into the `OpenSlides` directory next to `openslides`.

**Comment by serge1peshcoff** [comment]
@FinnStutzenstein 
 I've installed OpenSlides as a PIP module, like described in README:

    pip3 install openslides git+https://github.com/OpenSlides/openslides-presenter

If I'm doing it wrong, please can you describe the proper way to do it? That way I can make a PR on `openslides-presenter` to update README to include the proper installation instructrions, so everybody would do it the right way.

**Comment by FinnStutzenstein** [comment]
In your `pip install` you use the main repo `OpenSlides/openslides-presenter`. Did you meant to use `serge1peshcoff/openslides-presenter`?

If sou, you forked from https://github.com/i3anaan/openslides-presenter and not from the main `openslides-presenter` repo. The fork from `i3anaan` is not up to date. The last commit in `OpenSlides/openslides-presenter` is important to get compability with OS 2.2b3.

So please delete your fork and fork again from `OpenSlides/openslides-presenter` and add your commit (which was working). That should do the business.

**Comment by serge1peshcoff** [comment]
@FinnStutzenstein okay, thanks from clarification, I will try to do it in the evening and will keep you updated.

**Comment by serge1peshcoff** [comment]
@FinnStutzenstein that indeed works, thanks for the clarification ;)
I have one more question: the i3anaan repository had the feature of displaying the projector on a presenter page (as iframe). I think it's quite useful and I want to add this feature exactly as it was in i3anaan's repository, but in a way it would work in OpenSlides 2.2 and newer. If I'll make a PR on that, would you accept it?
If yes, that I'll implement it and would make a PR to openslides-presenter repo, so everybody would be able to use that.

**Comment by FinnStutzenstein** [comment]
I just take i3anaans commits and put them on the current master and removed the OS version requirement. https://github.com/OpenSlides/openslides-presenter/pull/3

**Comment by FinnStutzenstein** [comment]
@serge1peshcoff You can now use the original plugin :)
