### ISSUE TITLE
Serverside websocket handling

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3716]
Current situation short:
- We use `Group` from channels to group websocket connection from site and projector
- For the site we also have the WebsocketUserCache to fix the issue, that we cannot associate user ids with reply channels.
- the ws_disconnect_* is not always calles. This results to massive keys in the WebsocketUserCache as well as in the redis entries for channels' `Group`. Those have an expire date, but it is with one day too high.

We should take care of it ourself: Do not use `Group` from channels and other features, just the send, connect and disconnect.

So we have to rethink our cache model, so get uniform keys with all requirements we need. Also we add for each reply channel an expire date, that _is not_ controlled (or the ky deleted) by redis. If a worker sees an expired key, it should be deleted _and_ the websocket connection should be force closed. The client - if active - will rebuid the connection.

**Comment by ostcar** [comment]
Will be fixed with: https://github.com/OpenSlides/OpenSlides/pull/3784

**Comment by FinnStutzenstein** [comment]
Done in 3.0
