### ISSUE TITLE
Files that are projected but hidded are inaccessible

### ISSUE THREAD

**Issue by serge1peshcoff** [OpenSlides/OpenSlides#3725]
So I have an hidden file and I want to broadcast it.
If I'm doing it as an admin (meaning having all rights) this will work okay.
If I'll log in as a user who doesn't have the rights for seeing this file, the API would return HTTP 403 error for this file, meaning that if the user would open the projector, he won't be able to download the file and the blank white screen would be displayed.

Can that be resolved in some way? (Not sure though on how it could be resolved)

**Comment by FinnStutzenstein** [comment]
Actually this would be possible. In the [serve method](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/mediafiles/views.py#L74) we could implement a check, if the mediafile is projected and if the user has the `can_see_projector` permission.
But do we want this? If you have private files, this is a way to publish them without get actually notified, that you made the files public if you project them. Maybe just for non hidden files.
Some more opinions?

**Comment by serge1peshcoff** [comment]
I can't provide a single way how to solve it but I will post an example of how we use it.
We are using OpenSlides for displaying the presentations on stage, and also for users to be able to  log in through the website and see files/projector by themselves. In our setup, all files are private when they are uploaded, and after they are broadcasted via beamer, they are made public so everybody would be able to see them.
We are using the admin account for broadcasting, and it's okay for admin account, since the person behind it can access hidden files as well, but for users who cannot see the hidden files, when they'll go to the beamer page, they will see the white screen, since the file would be not accessible.

**Comment by serge1peshcoff** [comment]
@normanjaeckel I agree, that makes sense.

**Comment by FinnStutzenstein** [comment]
Who wants to do this?

**Comment by tsiegleauq** [comment]
This is fixed in OpenSlides 3.0
Hidden files do not exist anymore. The projector also shows files that are not accessible for your current group, as it should.

Not sure if to close - adding as TODO, since it might be included in an 2.3.1

**Comment by FinnStutzenstein** [comment]
Yes, in OS3 this is fixed. Not sure for OS2; @emanuelschuetze Is this still important for older OS versions?

**Comment by emanuelschuetze** [comment]
> @emanuelschuetze Is this still important for older OS versions?

No
