### ISSUE TITLE
missing linebreaks in election/voting result

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3727]
As you can see in this screenshot:
![screenshot-2018-4-29 openslides projektor 1](https://user-images.githubusercontent.com/1828501/39409043-3373aed0-4be0-11e8-8083-5c92cf8ef220.png)
has no linebreak machanism.

I assume this is because of the fix for bug #3593.

You might argue that 5555 abstains is an unusual thing but OS is translated to other languages. For example in Russian instead of "Enthaltung:" you have "Воздержаться:" (13 instead of 11 chars) so that the issue will be triggered if e.g. 22 people voted abstain.

I think a clean solution is
- allow linebreaks
- assure that the line cannot be broken in these positions:
-- after the '('
-- between '%)'
-- between the value and the '%' character

**Comment by emanuelschuetze** [comment]
done in current master (3.2-beta)
