### ISSUE TITLE
Wrong calculation of election results

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3736]
- look at this screenshot:
![screenshot-2018-5-9 wahl listenfindungskommission openslides](https://user-images.githubusercontent.com/1828501/39789594-1915ab30-5331-11e8-82d1-f0f26c9339ac.png)
There were 49 valid ballot papers. I entered the yes votes and used -2 for No votes because we did not distinguish between No or absent.

As you can see OS calculates for every case -4.08%, no matter how many yes votes somebody got.

**Comment by donovaly** [comment]
Here a maybe better example:
![screenshot-2018-5-9 wahl programmkommission openslides](https://user-images.githubusercontent.com/1828501/39789739-093fa7fa-5332-11e8-932a-9c8d8549419f.png)
Again 49 ballot votes in total. Only the yes votes were counted. So for the person that got 43 yes votes, it is not clear if there were 6 No or Absent votes. Therefore I entered "-2" for No and for absent.

**Comment by donovaly** [comment]
> So, just leaving out the (-4.08%) if one have entered -1 or -2 is sufficient?

Yes. -1 and -2 are special values and no real votes. There can't be a negative vote.

**Comment by donovaly** [comment]
There is a related bug that OS allows to enter negative votes in general, see #3739.

**Comment by emanuelschuetze** [comment]
How to reproduce:
- create a new election with 1 post and 1 candidate
- create a new ballot
- enter votes: Yes: 43, No: -2, Abstain: -2; Valid votes: 49
- now change the config for 100%-base to "All valid votes"
- Reload assignment detail view
=> Error -> No and Abstain should not get any percentage values!
Yes: 43 (87.76%)
No: undocumented (-4.08%)
Abstain: undocumented (-4.08%)
