### ISSUE TITLE
no way to prevent automatic speaker's list setting

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3737]
- create a new election to elect 2 persons
- add 2 persons as candidates.
- since the 2 candidates are not at the assembly some other persons speak for them
- now start a ballot

result: OS puts the 2 candidates automatically on the speaker's list

There is no way to prevent this. This is a problem because in real assemblies some persons are not at the assembly. Therefore the speaker's list consist of candidates and other persons. For some elections the assembly rules are so that candidates are not speaking at all. (e.g. election to preside the assembly)
Therefore there must be a way to prevent the automatic addition to the speaker's list.

**Comment by FinnStutzenstein** [comment]
I will create a sconfig for this, because it's the same with countdowns coupled with the list of speakers. Some people like and need this feature, but other people have a different workflow and this interrupts them.

**Comment by donovaly** [comment]
How is this fixed? I ask because I need to document the a new setting to change the behavior of the speaker's list.
