### ISSUE TITLE
Refactor motion comments

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3744]
Since we got the ability to have motion comments, much requests for improving those reached us, e.g. permissions for single fields (by giving a group the right to edit this field, others to see..).
The current situation is very hacky in many ways:
- We often have bugs there -> An indicator for a not well thought out implementation/structure
- The amount of time consumed by implementing new things relating to comments is hugh and grows.
- Comments are saved as JSON, so no validation from the DB is done. This results in much code to check permissions (e.g. see PR #3743 ).
- Special fields for recommendation and state are saved in the comments -- it does not make sense... They should be attributes of a motion.
- Fields are also JSON saved in the config. They should be separate models and so they can be extended e.g. with relations to groups.

For the future we strongly need to refactor those: Make a MotionCommentField model to customize the fields. Make a manage view for the fields. Make a `MotionComment` model with the comment and unique relations a field and a motion. Move the special fields to attributes of motions. This would make so much more sense and is easier to manage.

**Comment by normanjaeckel** [comment]
I agree. I do not exactly remember but I think motion comments was only a small extra feature in former times and then grew up. So extra models with extra views and thelike sounds good for me.

**Comment by ostcar** [comment]
You could also create a GenerelComment class. Any other class, for example the motion class could reverence them: Motion: {'id': 5, ..., 'comment_ids': [1,4,6,7]}, Assignment: {'id': 3, ... 'comment_ids': [2,3,5]}

**Comment by FinnStutzenstein** [comment]
closed with #3842
