### ISSUE TITLE
how to save a image file（e.g jpeg）to svs file

### ISSUE THREAD

**Issue by caishengzao** [OpenSlides/OpenSlides#3753]
excuse me,i use openslide-python api to open a svs file successfully，and then i want to slice the file into several part but still save them as svs files ,but i don't find the related Python API in openslide-python...

**Comment by FinnStutzenstein** [comment]
Hi, I think you posted in the wrong projekt. For the package `openslide-python` check out [openslide-python on GitHub](https://github.com/openslide/openslide-python). Thanks!
