### ISSUE TITLE
Migrating from GitHub to Gitlab?

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#3756]
Since [Microsoft acquired Github](https://www.theverge.com/2018/6/3/17422752/microsoft-github-acquisition-rumors) today we should discuss if we want to keep supporting the big, closed source software platform GitHub or if we want to support the more-[OpenSource](https://about.gitlab.com/product/open-core/) Software approach from [GitLab](https://about.gitlab.com).

**Comment by normanjaeckel** [comment]
+1 for migrating to another platform. But we have to check their features carefully.

**Comment by ostcar** [comment]
+1. It should be easy to "test-migrate". It will only be official, when you announce it and lock this repository.

**Comment by jsaalfeld** [comment]
I suggest to "mirror" the project over to GitLab and continue using GitHub.

The namespace [OpenSlides](https://gitlab.com/OpenSlides) was already reserved by me.

Since Microsoft stated, that GitHub continues to be an independent company I don't think there will be any harming changes to the ecosystem for now. But it will be great to have a backup-solution up on our sleeve - in case something happens.

**Comment by Mabahe** [comment]
GitLab is hosted on Microsoft Azure Cloud :smile: So you need to think about hosting a own GitLab instance.

[UPDATE] They just announced to move from Azure to Google https://about.gitlab.com/2018/06/25/moving-to-gcp/
