### ISSUE TITLE
Add Privacy Policy and Legal Notice Links to Login Page

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/OpenSlides#3757]
While OpenSlides generally displays a footer with links to the privacy policy and other legal information, there are no such links on the login page (`/login`).  That means there is no way to obtain this information *before* logging in, and for visitors without accounts it is entirely unavailable.

According to the GDPR (and possibly other legislation) this is not acceptable.  Similarly, at least in Germany, the imprint must be public.

For these reasons, the same pages or links that are shown within OpenSlides should also be made available from its login screen.

**Comment by serge1peshcoff** [comment]
@gsiv is there any ETA for that? I'm asking because we want to use OpenSlides during one of our events, it's in the beginning of October and we need the system to be GDPR-compliant. Is there a chance it'd be implemented by October?

**Comment by emanuelschuetze** [comment]
There is already a privacy policy page in OpenSlides 2.2 - see https://demo.openslides.org/privacypolicy. But this page is only available _after_ login (if you have disabled the anonymous/guest access). That's the reason of this issue. But of course you can use OpenSlides already with the current GDPR page.

**Comment by FinnStutzenstein** [comment]
No, you cant. This information has to be available before the login. If this blocks some usecases of OpenSlides, we should make this possible.

**Comment by FinnStutzenstein** [comment]
I'll find a simple way to show the information before the login.

**Comment by serge1peshcoff** [comment]
@FinnStutzenstein awesome, thanks ;)
