### ISSUE TITLE
Fix old remarks

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#3760]
Pleas fix remarks here (https://github.com/OpenSlides/OpenSlides/pull/3734) and here (https://github.com/OpenSlides/OpenSlides/pull/3723). Thanks.

**Comment by normanjaeckel** [comment]
In #3723 the remark is to file  openslides/agenda/static/templates/agenda/list-of-speakers-partial-management.html at line 6 and below.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Where is the remark for #3273 ? No one has commented anything there..

**Comment by FinnStutzenstein** [comment]
Ah I see.. Somehow we had an unicode (U+FFFC) object replacement character in there...
