### ISSUE TITLE
Remove 'action_word' field for states

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3776]
As discussed in #3772 we want to remove the 'action_word' field.

Action words are sometimes irritating for users, e.g. if a motion was accepted the user has to click on "accept" (action word) to get "accepted" (state name). But often users think already in "accepted" if they search for the end state.

**Comment by jsaalfeld** [comment]
Since #3772 is merged, this can be closed (hopefully).

**Comment by FinnStutzenstein** [comment]
No, this is not done. But on the server the fix is easy; the main issue is to not use the field in the client. If we do not do that, it's resolved easily.

I would suggest removing the field now, so we cannot use it in the client ;)

**Comment by FinnStutzenstein** [comment]
Done.
