### ISSUE TITLE
Rewrite get_win32_app_data_dir()

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#3802]
Use a better/easier way to get %APPDATA% dir on windows.

See https://github.com/OpenSlides/OpenSlides/pull/3797#issuecomment-414441113 and https://stackoverflow.com/questions/13184414/how-can-i-get-the-path-to-the-appdata-directory-in-python

**Comment by tsiegleauq** [comment]
Sounds like an issue for OpenSlides-Portable to me.
