### ISSUE TITLE
Add superadmin

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#3821]
Add a new user field is_superuser. Everybody with this flag has all permissions. The client prohibits that one resets this flag for himself if he is the last existing superadmin.

The manage command create-or-reset-admin asks for a username and sets this user (new if not existing) as superadmin and resets the password.

The Group admin may be removed.

Maybe as a fixed group.

**Comment by normanjaeckel** [comment]
See #3859.

**Comment by ostcar** [comment]
This should be fixed with #3910
If not. Please reopen.
