### ISSUE TITLE
Add capacity option to channels settings

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#3829]
Maybe we need a customized value for the capacity settings of channels.

**Comment by ostcar** [comment]
We already have that.

You can write: `CHANNEL_LAYERS['default']['CONFIG'] = {'capacity': 10000}` into your personal settings file.

Do you mean, that we should change the default value in the settings template?

**Comment by normanjaeckel** [comment]
I just wonder whether we should ass a high (default) value in our settings template. We started to discuss this last week but were interrupted ...

**Comment by ostcar** [comment]
I don't see any negative effect with a high default value. At least with redis as a backend.

**Comment by jsaalfeld** [comment]
Personally, i just start another instance.

But is this still relevant with the separation of client and server in OS3?

**Comment by FinnStutzenstein** [comment]
Other question: Does channels 2 still have a queue to buffer data, so does it still have this config value?

**Comment by ostcar** [comment]
Yes, but only for some cases.

**Comment by emanuelschuetze** [comment]
We have already a capacity option in [settingy.py.tpl](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/utils/settings.py.tpl#L91)
