### ISSUE TITLE
Material Icons instead of Fontawesome

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#3874]
This is open for discussion. Right now, we are using "FortAwesome / Fontawesome"
https://github.com/FortAwesome/angular-fontawesome

Our GUI templates were designed using Material Designs.

Sometimes OpenSlides needs rather exotic icons that Material Icons **might** not offer.
(needs research)

Angular treats Material Icons like a font (which might lead to issues with custom fonts), FontAwesome icons are treated like an SVG.

The interface would be more consistent using Material Icons.

Including material icons (while actually have them installed from npm) is not _that_ trivial as well.
https://github.com/angular/angular-cli/issues/2662

I personally would change over to Material Icons, since FontAwsome seems to be highly proprietary.
https://fontawesome.com/license

**Comment by FinnStutzenstein** [comment]
> Angular treats Material Icons like a font (which might lead to issues with custom fonts), FontAwesome icons are treated like an SVG.
FA-Icons do exist as a font. But the currently used implementation uses SVGs. We might use a different implementation.

> The interface would be more consistent using Material Icons.
In which means? The icons look good at the moment.

FontAwesome is a great choice and users are used to the icons there. They deliver everything we need and they are implemented. Lets stay there.
