### ISSUE TITLE
unnecessary exclamation mark in amendment paragraph dialog

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3880]
The new dialog to select a paragraph for an amendment has an unnecessary exclamation mark in its title:
![motion-amendment-paragraph2](https://user-images.githubusercontent.com/1828501/45659190-82dad980-baf3-11e8-97a3-3aee4b6518e2.png)

I understand that this new feature excited the proggramer but users don't like these exclamation marks when there is nothing of special attention.

**Comment by FinnStutzenstein** [comment]
Nice :'D
