### ISSUE TITLE
impossible to go back from amendments to motion

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/OpenSlides#3881]
- open a motion with e.g. 2 amendments
- click o the amendments button to see the amendments of this motion
- now try to go back to the motion

result: this is not possible because you can only go back to the list of motions. This is annoying for conferences with many motions because you loose time to select the motion in the motion list. The solution is a back button to the motion of the amendments like there is in all other lists.

**Comment by FinnStutzenstein** [comment]
You are in the amendment list for one specific parent motion, right? If so, you can click on the selected lead motion.
![amendment_back](https://user-images.githubusercontent.com/8439581/45667638-4b335800-bb1a-11e8-97d6-6adb6842fa1d.jpg)

**Comment by donovaly** [comment]
> You are in the amendment list for one specific parent motion, right?

No, I am in the list of amendments:

![screenshot_2018-09-18 antrage openslides](https://user-images.githubusercontent.com/1828501/45676998-665e9180-bb33-11e8-8800-48f46a7f4bb8.png)

So there is no button to go back to the motion, only to the list of motions.

**Comment by donovaly** [comment]
Please reopen. Please think about usability and intuition. In all cases I can use buttons at the upper right to jump back. Why not here? Just add a new button to jump back to the motion.

Also please don't treat me as idiot and close the bug without discussion. I mean when I as experienced user don't find the way to jump back, other users won't find it as well! Therefore it is worth to consider my proposal as valuable for OS.

**Comment by emanuelschuetze** [comment]
Ok, we'll think about an usability improvement for 3.0.

**Comment by tsiegleauq** [comment]
#3909 introduces a head bar which always (should) have a back button to address cases like this.
However, this specific view (motion amendments) is not yet implemented in OpenSlides 3, so I am not closing this issue now.

@donovaly perhaps you may confirm if the current version fits to your expectations?

**Comment by tsiegleauq** [comment]
with #4523, the global back button will navigate to the parent motion if the user is seeing a (single) amendment. There is no amendment list (yet) but this feature is in development

**Comment by emanuelschuetze** [comment]
Navigation reworked in OS3.
