### ISSUE TITLE
Client error on motions

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#3912]
Old client does not work on motions tab because motions_comments config var was removed but is still in use in base.js.

**Comment by tsiegleauq** [comment]
how is this a blocker?

**Comment by FinnStutzenstein** [comment]
Surely this is a blocker, if you want to test with the old client. The question is, if we should fix this, or whether @normanjaeckel and @ostcar can use the new client for testing and development. Do you miss something for your development, we should implement with a higher priority?

**Comment by ostcar** [comment]
Can you tell if the new clint is usable? When we merge the change in the autoupdate format, it will break the old client totally.

So I would like to use the new client if possible and remove the old one.

Is it also possible to merge the OpenSlides 3.0 branch into the master branch?

**Comment by emanuelschuetze** [comment]
@ostcar yes, feel free to merge OS 3 branch into master. But create a 2.x stable branch first, please.

**Comment by FinnStutzenstein** [comment]
For the new bit features (history and changeId) the new client should be "ready enought" to test and implement these features.

**Comment by tsiegleauq** [comment]
> Can you tell if the new clint is usable?

Well, it does not break stuff ;-)

If you demand something specific for your progress just contact us and we provide a new view asap.

**Comment by ostcar** [comment]
Ok. I merged the OS 3 branch into master. To be sure, that the old branch is not used anymore, I deleted it. The commit ID was 1b3a2876425a7f14c635bb81d699ce2d35391412

**Comment by ostcar** [comment]
The effect was, that all open pull request where closed. (If I knew this before, I suggested, that they changed there branch, before I deleted the OS 3 branch.) I tried to find all closed pull requests, change the branch and reopened them. But maybe I overlooked one. So please see, that all you pull requests are still open

**Comment by normanjaeckel** [comment]
Can be closed.
