### ISSUE TITLE
Missing Material Icons

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#3921]
As mentioned in an earlier PR, there are some Material Icons missing.
The reason for that is simple: [Google did not update their repository yet](https://github.com/google/material-design-icons/issues/786).

Once the linked issue is resolved, we should be safe to update `material-design-icons` in our package.json and include the missing icons.

Currently (required but) missing icons include, but are not limited to:
* [how_to_vote](https://material.io/tools/icons/?icon=how_to_vote&style=baseline) (Should be in the navigation for assignments)
* [save_alt](https://material.io/tools/icons/?icon=save_alt&style=baseline) (Would be nice to have for download / export)

There are two ways to address this problem.

1. simply wait until google provides an update (which might happen tomorrow, next month or next year)
2. follow one of the approaches provided in the thread above to include a patched version of `material-design-icons` manually.

I would, at least, wait until we want to release a (beta? final?) version of OpenSlides 3 before I follow the manual approach. The few missing icons are by no means crucial and there should be an updated at some time.

**Comment by MaximilianKrambach** [comment]
note: save_alt is already included and used, but uses the same symbol as save (a floppy disc instead of a 'put into a box' symbol)

**Comment by tsiegleauq** [comment]
There is a very promising project that addresses our issue. It also provides a much faster search function for icons.

https://github.com/jossef/material-design-icons-iconfont

**Comment by GabrielInTheWorld** [comment]
I take this one

**Comment by jsaalfeld** [comment]
We could take https://github.com/ryanoasis/nerd-fonts and patch, with the scripts in there, our own font version with the needed icons. That would have the smallest footprint possible and should be very friendly for mobile devices and small bandwith-capacities.
