### ISSUE TITLE
Integration tests for os3 - with backend?

### ISSUE THREAD

**Issue by ghost** [OpenSlides/OpenSlides#3930]
For os3, I also want to begin including some extended tests ( e.g. login as admin -> create a tag -> update a tag -> remove a tag ([example](https://github.com/OpenSlides/OpenSlides/pull/3927/files#diff-e674b9b4bc550bbec081f7c9c3beca40R32)) ).

For this, the running tests would need some kind of (fresh/empty) database. I have several options:

1. Creating a dummy database (angular-in-memory-web-api); here I would never interfere with any 'real' database. However, I would need to update the 'dummy' database every time the real database migrates.

2. Using the django backend defaults. This means that, for the tests to run, a database needs to be running. In travis this should not pose a major problem, but on local tests we might get a 'dirty' database if someone confuses the test database and some production version.

3. Don't do these tests at all. For me, creating and maintaining these tests (especially as we are still relatively early in os3) can help catch errors quite a lot. However, almost nobody likes or cares about tests, so I am unsure if this is not a dead end in two months' time.

**Comment by MaximilianKrambach** [comment]
ping on an opinion @tsiegleauq @FinnStutzenstein @emanuelschuetze (maybe other contributors?)

**Comment by MaximilianKrambach** [comment]
After direct communication, we will continue with:

- Client tests will be run against a mock HttpService, and receive mocked responses.
- These mock services, the mock database structure and examples will be placed at some central point, to ease updates (if e.g. urls change).
- The server is already being tested separately

**Comment by jsaalfeld** [comment]
> * The server is already being tested separately

If we mock the HttpService, shouldn't run the server-tests against the same Mockup-Input to just have one source of Test-Data and ensure that client and server will play well together?

**Comment by tsiegleauq** [comment]
@jsangmeister is currently creating UI tests with cypress that might address these issues
