### ISSUE TITLE
Persistent Login-Cookie -OR- Secret Login URL

### ISSUE THREAD

**Issue by henryk** [OpenSlides/OpenSlides#3933]
(This is a wish/feature request. If someone tells me which solution would be acceptable I can also look into it myself, but I'm currently not familiar with the code base.)

Use case: For my assembly I'd want a small single-board computer that is connected to the projector, is unattended, and boots directly into `chromium-browser --kiosk --app=https://openslidesurl/projector/1/`.
BUT: I also do not want the projector URL to be publicly accessible. (While agenda items, and, consequently, the OpenSlides instance are internet-public, the list of speakers is not.)
I have deactivated projector permissions from the default group, created a new user for the projector PC and assigned projector permissions. 

Problem: In the current design, login cookies are ephemeral, and no unattended method to access the projector URL with no user interaction seems to exist.

I'd wish for, either

- A) a "[X] Save login" checkbox, so that the projector PC can be prepared once and then boot/re-boot without further interaction   (may be more fragile, since the browser might lose cookies or session due to crashes or date/time confusion, etc), or
- B) a method to log-in with username/password in the URL (`/projector/1/?user=foo&password=bar`), or a secret link/token (`/projector/1/?token=...something`)

**Comment by jsaalfeld** [comment]
Alternatively, you can setup an `nginx` to block the get-through and only let you pass if you survive the `.htaccess` request. Which can easily be added as a command line parameter.
