### ISSUE TITLE
Fix todos in README and DEVELOPMENT

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#3935]
There are currently some TODOs in the README.rst and DEVELOPMENT.rst file. They have to be fixed before the release.

**Comment by FinnStutzenstein** [comment]
- [ ] Dependencies incl. the script generating those has to be adapted. I did removed them in the README
- [ ] Validate the Nginx config. I changed it but not tested:
```
TODO: Check and validate this new configuration. /static should not be needed. Everything should be delivered
      static except the (ws|wss|media|rest|apps).
      Add a suggesten, that also meda files is served be nginx, but then, all
      users (even anonymous) can receive them.
```
- [ ] check if yarn works. See #3012 .
- [ ] check the `apt` dependencies.

**Comment by emanuelschuetze** [comment]
done for 3.0
