### ISSUE TITLE
Category numbering: Make a seperate number-button

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3969]
See PR #3970 : All motions in a category are automatically numbered, if the category is saved. This is not a wanted behavior, in fact there are people who do not use this feature, while this would break with their use of identifiers.

I think of a seperate number-motions-button or so. Maybe Christine has some suggestions.

**Comment by tsiegleauq** [comment]
A "Number motions" was now found in a dedicated "sort view"
