### ISSUE TITLE
Shift + Enter to submit forms

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#3980]
Since I am heavily testing data creation, it would be nice to have a shortcut to submit forms.
I would suggest to hold shift and hit enter to submit the forms.

This is more of a comfort feature for power users (and us developers of course)

**Comment by MaximilianKrambach** [comment]
I'm rather used to `ctrl`+ `enter`. Is there any standard? (I'm getting confused by things like this quite a lot lately)

**Comment by FinnStutzenstein** [comment]
I do shift+enter. But why not both?

**Comment by tsiegleauq** [comment]
was resolved by #4025 and #4060
