### ISSUE TITLE
CSV exports for other listViews

### ISSUE THREAD

**Issue by MaximilianKrambach** [OpenSlides/OpenSlides#3983]
PR #3931 introduced the possibility of csv export, but only implemented it in the user list view.

The other list views need csv export, too.

This is mostly a copy&paste task

**Comment by MaximilianKrambach** [comment]
reference: #4056

**Comment by MaximilianKrambach** [comment]
@jsaalfeld  please confirm that all needed csv exports are now covered:

(covered csv exports: User, Motions, call list, agenda)

**Comment by jsaalfeld** [comment]
I've got nothing in my books about the call-list, but it sure is nice to have!

Additionally I got something like a "Änderungsantragsübersicht" or "Amendment list".

**Comment by FinnStutzenstein** [comment]
Note: call list was an extra feature for a client, but now in master

**Comment by MaximilianKrambach** [comment]
Amendment list is not yet existant, so we can close this issue, as everything is covered.
