### ISSUE TITLE
Update Portable Version for OpenSlides 3.0

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#3984]
We currently have some Issues open for the Portable Version of OpenSlides.

* [ ] #3669
* [ ] #3662
* [x] #1747 
* [ ] #1336 

Will we still provide a portable version of OpenSlides 3.0? We have the Docker Images and documentation for them in place. They should work on every platform and it will reduce overhead on releasing a new version.

**Comment by emanuelschuetze** [comment]
Currently, we will try to provide OpenSlides 3.0 as portable (for Windows) as long as we use portable components (e.g. python packages etc.)

**Comment by jsaalfeld** [comment]
Then we'll need to update the process to create a new portable binary. With the new client in place it could be a bit tricky to get all the needed files and provide them properly and in a stable way.

**Comment by emanuelschuetze** [comment]
Currently, the portable for 2.3.x required a pypi package of OpenSlides only.

**Comment by FinnStutzenstein** [comment]
Haven't the UI of the portable version an own repo? So some issues may be better places there..

**Comment by tsiegleauq** [comment]
I agree. This issue belongs to [OpenSlides Portable](https://github.com/OpenSlides/openslides-portable)
