### ISSUE TITLE
Is a link to Privacy Policy and Legal Notice needed on the projector?

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#3990]
Since the GDPR states, that the Privacy Policy and Legal Notice should be reached from every page of a website and the projector is technically a website, I asked myself if we need a way to display them (maybe just if hovered over the bottom of the page with a mouse) on the projector.

**Comment by normanjaeckel** [comment]
I think we can argue that the projector page can only be reached via OpenSlides main site. Therfor it is reasonable that the user goes back (via browser) and then can find the link to the privacy policy page. The GDPR does not contain a strict rule that the Privacy Policy and Legal Notice must be reached from every technical website (see Art. 12 GDPR that states that information shall be provided in a concise, transparent, intelligible and easily accessible form).

**Comment by jsaalfeld** [comment]
If the anonymous user is activated, it can be reached in full-screen mode without visiting the main-page first. So there should be at least a permission-check.

The most elegant way would be to blend it in on default and to have a setting, based on the browser-session, to hide the banner with the imprint and privacy policy. I think that this should fulfill the statement "easily accessible form".

**Comment by ostcar** [comment]
Or, we could not save any data when visiting the projector page. Then a privacy page is not needed.

Therefore we should rewrite the projector page, that it does not set a cookie. I don't know if it does. I only needs to use a cookie and not set it.

**Comment by jsaalfeld** [comment]
This is technically quiet hard and not always achievable. Somehow the requests to the projector have to be routed. That, unfortunately, is already an issue, since we cant guarantee that no ip logging happens on routers on that system.

**Comment by ostcar** [comment]
This problem can not be solved with a privacy page. How do you write in the privacy page, that the ip is saved, if you don't know, that it is. You have to write how is saving the data.

I don't think it is necessary to add the link to the projector page. But if you feel better with that link, please add it.

I hope you never get hired by netflix and add the privacy link to any video in full screen mode.

**Comment by jsaalfeld** [comment]
> I hope you never get hired by netflix and add the privacy link to any video in full screen mode.

Since the video, that plays full-screen is on the same page as the info-page about the video and that page has, of course, the privacy policy in the footer, I see no issue there.

Our problem is, that the projector can be reached without visiting a site first, were you have to fullscreen the projector first, which contains a link to the privacy policy. So if the anon-user is activated a link to the projector can be spread and everyone can access it, without having the option to see the policy. This way could actually be a workaround for the issue.

> This problem can not be solved with a privacy page. How do you write in the privacy page, that the ip is saved, if you don't know, that it is. You have to write how is saving the data.

When I setup a server I know what is saved and logged and for how long (of course). But disabling that specifically for the projector is next to impossible without having some kind of information, even for a short time, in the system. And since you can reach the page, without ever seeing another kind of landing page first, it has to be there when anon-access is activated, but not if you have to login first.

**Comment by tsiegleauq** [comment]
I just close this now...
