### ISSUE TITLE
ngx translate interpolation

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3995]
From #3968 : The interpolation from the translate service does not work. I don't know whether this is because I used it wrong, or something else. The docs is relatively silent about the interpolation.
```
this.translate.instant('The server cound not be reached ({{ code }}).', {code: e.status});
```

**Comment by tsiegleauq** [comment]
with the changing to `.po` files we will not be to put parameters to `instant` or `get` anyways.
Simply put the translated string into a const and add the error code after that.
