### ISSUE TITLE
Limit the width of pages to 1200px

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#3998]
All component pages should have a max width of 1200px.
This will probably require some adjustment of the site.component.scss or even the main site.scss

**Comment by jsaalfeld** [comment]
What about 4k Monitors? Should we really hold back the space we have?

**Comment by tsiegleauq** [comment]
It was supposed to shorten mouse movement paths.
It's supposedly more usable to have a smaller interaction surface.

**Comment by tsiegleauq** [comment]
was resolved by some "UI-Improvemend" PRs
