### ISSUE TITLE
PO-loader and language errors

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#4003]
from #3989 
- [x] We need to test and implement the direct po loader
- [x] Selecting the third language seems to be broken. The browser-language and the default language files are being transmitted fine, requests to other files fail.
- [x] "languages" should not be translated (I don't know what is "English" in russian :-( )

**Comment by tsiegleauq** [comment]
only thing missing here:
Languages should not be translated.

**Comment by emanuelschuetze** [comment]
> Languages should not be translated.

done
