### ISSUE TITLE
Session Storage

### ISSUE THREAD

**Issue by MaximilianKrambach** [OpenSlides/OpenSlides#4004]
For 3.0, we'll need a session storage.

Currently, I'd want to save sort and filter definitions there (see #3963 ), but I can imagine that we may have more persistent settings (pagination size?)

I'll check myself if such a service is easily done (as it seems from internet descriptions)

**Comment by MaximilianKrambach** [comment]
Question is @FinnStutzenstein @tsiegleauq : Are there any plans/restrictions/works on it, or can I boldly go on to where I want to be?

**Comment by tsiegleauq** [comment]
[StorageService](https://github.com/OpenSlides/OpenSlides/blob/master/client/src/app/core/services/storage.service.ts)

We are using [IndexedDb](https://developer.mozilla.org/de/docs/IndexedDB) over [ngx-pwa/local-storage](https://github.com/cyrilletuzi/angular-async-local-storage).

You can store your sort settings there aswell if you need to.

**Comment by MaximilianKrambach** [comment]
There seems to be a mismatch between documentation and usage there. Is it subscribable, or an async/await (I'm guessing latter)? And, as I see it, I shall submit stringified json?

**Comment by FinnStutzenstein** [comment]
Oh, the docs might need an update. You can put json in there, but not instances of classes.
