### ISSUE TITLE
Enhancing Drag and Drop component to work with nested lists/trees

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#4017]
It should be possible to enhance the drag and drop module in OpenSlides in a way, that Items can be dropped in nested lists or tree structures (i.e. in Agenda Overviews). It is currently not possible to do this with the shipped code of angular: 

 - [ ] https://github.com/angular/material2/issues/13796

Therefore @FinnStutzenstein will temporarily implement https://github.com/500tech/angular-tree-component, which offers drag and drop support (and seems to be the successor of the https://github.com/angular-ui-tree/angular-ui-tree which was used in OpenSlides 2.x). As soon as the above mentioned issue is closed, we should switch it out for the angular given elements.

**Comment by tsiegleauq** [comment]
Done by #4489
