### ISSUE TITLE
Client-side file-type validating on upload

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#4024]
As emerged from #4019:

> We should really include some kind of client-side validation on the file itself. We should consider checking if the file-type of a selected files corresponds with the selected file. If one manages to upload an executable masked as a font, it will be processed on the server later on, which can lead to issues. Same with other displayable files which can or will be executed on a clients desktop.

> I agree, however, that might be a bigger discussion.

**Comment by tsiegleauq** [comment]
never trust a client.
