### ISSUE TITLE
CSV-Export Options should be defined in the config

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#4035]
The Options for the CSV-Export are currently hard-coded in the `csv-export.service`. Since different countries have different "standards" for CSV (some countries prefer `;` as seperator and `\n` as newline etc.), this should be definable in the global configuration.

**Comment by emanuelschuetze** [comment]
This is already a config option: settings > general > "Separator used for all csv exports and examples".
We have to use this in current implementation.

**Comment by jsaalfeld** [comment]
Ok. Will take a quick look. Thanks for sharing!
