### ISSUE TITLE
OpenSlides histrory build lock

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#4039]
See #3977. We need a solution for the case that more than one server/worker start and try to build the history (as we do for the cache build).

**Comment by tsiegleauq** [comment]
@normanjaeckel @ostcar the history is now delivers over a dedicated requiest. Is this issue still relevant?

**Comment by normanjaeckel** [comment]
Yes. I think it has something to do with the server/worker start.

**Comment by tsiegleauq** [comment]
@FinnStutzenstein @normanjaeckel this was labeled `high` for 3.1
Either resolve this soon; or remove the label and change the milestone.
