### ISSUE TITLE
Include prettier into travis

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4045]
@jsaalfeld This might be a task for you integrating the prittier into travis (after linting and before tests) to raise an error, if the code is not formatted correctly

**Comment by jsaalfeld** [comment]
Code shouldn't be altered when commited.

I don't know what prettifying should do, what linting doesn't?

**Comment by jsaalfeld** [comment]
Did a small local test by just adding the line `const this = "that";` in some file. Ran the linter: no error. The pretty gave back an error and didnt alter the code. So will add a task for that.

**Comment by jsaalfeld** [comment]
As soon as we have #4031 in place, we could switch to use that dockerfile to run the tests. That should significantly speed things up, since we don't need a whole re-build of dependecies (and so on) for every build-task.
