### ISSUE TITLE
.htaccess proxy not working

### ISSUE THREAD

**Issue by lafidi** [OpenSlides/OpenSlides#4053]
I am trying to set up OpenSlides on my all-inkl.com shared webspace hosting. They support Python 3.5 and everything works quite fine. The only Problem I have is when opening the page using my browsers. I get the login prompt and as soon as I enter valid credentials (admin-admin) I geht the attached blank page:
![screenshot_2018-12-07 startseite openslides](https://user-images.githubusercontent.com/29579394/49662297-b0c51f80-fa4b-11e8-8d6e-3ef9b282d969.png)

I can see on the console that my computer tries to fetch different pages and always uses alternating ports:
`[2018/12/07 18:14:09] HTTP GET /ws/site/ 200 [0.02, 127.0.0.1:48388]`
`[2018/12/07 18:14:14] HTTP GET /users/whoami 301 [0.03, 127.0.0.1:48400]`
`[2018/12/07 18:14:14] HTTP GET /users/whoami/ 200 [0.06, 127.0.0.1:48402]`
`[2018/12/07 18:14:14] HTTP GET /ws/site/ 200 [0.04, 127.0.0.1:48404]`
`[2018/12/07 18:14:20] HTTP GET /users/whoami/ 200 [0.07, 127.0.0.1:48416]`
`[2018/12/07 18:14:21] HTTP GET /ws/site/ 200 [0.02, 127.0.0.1:48418]`
`[2018/12/07 18:14:26] HTTP GET /users/whoami/ 200 [0.13, 127.0.0.1:48428]`
`[2018/12/07 18:14:26] HTTP GET /ws/site/ 200 [0.03, 127.0.0.1:48430]`

This is my .htaccess file:
`RewriteEngine On `
`RewriteRule (.*) http://localhost:8000/$1 [L,P]`

Do you have an idea why this doesn't work? I think it might be an issue.

EDIT: Made output prettier

**Comment by lafidi** [comment]
Yes, I can access it manually.
According to my console output it can be accessed (always having HTTP status 200).

**Comment by tsiegleauq** [comment]
`HTTP GET /users/whoami 301 [0.03, 127.0.0.1:48400]`
Indicates "Moved permanently". If `:8000/rest` or `:8000//users/whoami` are accepting get requests, OpenSlides is usually working just fine.
I don't have the required setup to reproduce your issue right now.

Just guessing:
from: https://github.com/OpenSlides/OpenSlides#a-check-requirements
> Make sure that you have installed Python (>= 3.6) on your system.

I suppose OpenSlides 2.3 (stable) and 3.0 are not compatible with Python 3.5 anymore.

If there is an issue on server side, you might be more lucky with an older version like [2.2](https://github.com/OpenSlides/OpenSlides/releases/tag/2.2) which was supporting python 3.4

**Comment by lafidi** [comment]
> I suppose OpenSlides 2.3 (stable) and 3.0 are not compatible with Python 3.5 anymore.
Hmm, I somehow mixed it up in my head. I was sure, Openslides 2.3 would work with 3.5. 
After some debugging I think that it is a Problem with proxying the websockets. I will give up now, so no Openslides on a webserver install, but a local one.

**Comment by jsaalfeld** [comment]
To get an idea how you can setup OpenSlides 2.3 in a "big_mode" setup, you can check the 2.3 release of the docker-compose setup: https://github.com/OpenSlides/openslides-docker/tree/81d300e10dfe96e48a795a51f6dee2e7ba288ec5

You can see the nginx settings there and take a look at the settings that need to be in place to have proper instance running.

**Comment by tsiegleauq** [comment]
I guess this was either resolved or not relevant anymore.
