### ISSUE TITLE
Deleting Mediafile does not update attachment-ids

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#4055]
- upload files
- create motion with attachments (possible soon:tm: but should be the same in the old client)
- delete the attached file from Mediafiles
- see `/rest/motions/motion/`

expected: `"attachments_id": []`
result: `"attachments_id": [<ID-of-non-existing-mediafile>]`

**Comment by FinnStutzenstein** [comment]
Looked into the motion model: this is a m2m relationship. I guess the cache is not updated. Todo: make a inform-changed-data on mediafile delete of all affected models, if this is the problem (not verified yet).
