### ISSUE TITLE
Check for ngx translate extract issue

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4078]
See hotfix #4077 and the issue at ngx translate extract https://github.com/biesbjerg/ngx-translate-extract/issues/118

**Comment by MaximilianKrambach** [comment]
Not sure if it fits here: the po2json tool 'destroys' strings with curly brackets (by adding an extra backslash), which causes translated default email templates to be invalid.

**Comment by tsiegleauq** [comment]
Cannot reproduce this issue in current angular 7.2.5
@FinnStutzenstein please test again and close this issue if it seems to be fixed
