### ISSUE TITLE
daphne/gunicorn (wsgi generally?) does not correctly deliver static fonts

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#4091]
While developing version 2.x (possibly older versions) it was always possible to deliver the website statically through the `python manage.py runserver`, `openslides start` (when installed via `pip install openslides`) or `daphne` (next to serving them separately for development or production purposes).

This is an advantage for server-development, since just one command is needed to serve the needed contents to test the changes with the client, without setting up the development-server or a separate server.

As described in #4083 the above described commands only deliver the static webpage, but don't seem to deliver the correct CSS or images. There need to be some changes in the configuration how the `wsgi` server contents on the client side of things should be delivered.

**Comment by tsiegleauq** [comment]
Additionally:
The client can be build using `npm run build` on `OpenSlides/client` directory (requires angular CLI)
The productive build can be found under `OpenSlides/openslides/static` where all required JS files, CSS files, font files and images are present.

The Django command `python manage.py runserver` delivers the static content  on `localhost:8000` using some unnamed WSGI webserver.
The WSGI webserver fails to correctly provide the font files, resulting in invisible material icons, as can be seen in @ostcar 's screenshot in #4083

**Comment by jsaalfeld** [comment]
I invested a bit in the issue. It seems that the `wsgi` application delivers _most_ of the contents correctly (CSS, JavaScript, HTML and Images). But it stumbles at the fonts. When you start OpenSlides via `python manage.py runserver`and acces `http://localhost:8000` you are greeted with the screenshots like in #4083.

When you open your developer console, you will notice the following errors, that lead to the display-errors:

```
localhost/:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Regular.73f0a88bbca1bec19fb1.woff2
localhost/:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Regular.73f0a88bbca1bec19fb1.woff2
localhost/:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Regular.35b07eb2f8711ae08d1f.woff
localhost/:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Regular.35b07eb2f8711ae08d1f.woff
agenda:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Medium.90d1676003d9c28c0499.woff2
agenda:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Medium.90d1676003d9c28c0499.woff2
agenda:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/MaterialIcons-Regular.570eb83859dc23dd0eec.woff2
agenda:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Bold.b52fac2bb93c5858f3f2.woff2
agenda:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Bold.b52fac2bb93c5858f3f2.woff2
agenda:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Medium.1d6594826615607f6dc8.woff
agenda:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Medium.1d6594826615607f6dc8.woff
agenda:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/MaterialIcons-Regular.012cf6a10129e2275d79.woff
agenda:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Bold.50d75e48e0a3ddab1dd1.woff
agenda:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Bold.50d75e48e0a3ddab1dd1.woff
agenda:1 Failed to decode downloaded font: http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/MaterialIcons-Regular.a37b0c01c0baf1888ca8.ttf
localhost/:1 OTS parsing error: invalid version tag
localhost/:1 OTS parsing error: invalid version tag
localhost/:1 OTS parsing error: invalid version tag
localhost/:1 OTS parsing error: invalid version tag
agenda:1 OTS parsing error: invalid version tag
agenda:1 OTS parsing error: invalid version tag
agenda:1 OTS parsing error: invalid version tag
agenda:1 OTS parsing error: invalid version tag
agenda:1 OTS parsing error: invalid version tag
agenda:1 OTS parsing error: invalid version tag
agenda:1 OTS parsing error: invalid version tag
agenda:1 OTS parsing error: invalid version tag
agenda:1 OTS parsing error: invalid version tag
agenda:1 OTS parsing error: invalid version tag
agenda:1 OTS parsing error: invalid version tag
```

When you try to access one of the mentioned fonts, i.E. the first one: `http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Regular.73f0a88bbca1bec19fb1.woff2`, you'll notice, that you will be redirected to `http://localhost:8000/styles.390dd2c0ffe3a954b1d6.css/Roboto-Regular.73f0a88bbca1bec19fb1.woff2/` and behind that adress the `index.html` will pop up. Therefore you can't access the fonts somehow and the `index.html` will be loaded instead. The `index.html` cant be decoded as a font and therefore no `material-icons` or custom fonts will be rendered.

When you look into your static folder, the correct files will be there and if you run `python manage.py collectstatic` the font files will be in `collected-static` as well. But it somehow seems, that the `wsgi`-Server won't or can't provide them correctly.

**Comment by FinnStutzenstein** [comment]
Actually, I wrote the code for this. The "wsgi-application" is the index view from OpenSlides: https://github.com/OpenSlides/OpenSlides/blob/master/openslides/core/views.py#L88 somewhere there, the issue happens. I can take a look tomorrow, or you, if you want to.
The logic is simple: try to deliver the requested file. If it does not exist, deliver the main.

Maybe the issue is the appended "/" in the urls.py...

**Comment by jsaalfeld** [comment]
It seems that you pointed the right way. I added some print statements to the mentioned function:

```
HTTP GET /styles.390dd2c0ffe3a954b1d6.css/MaterialIcons-Regular.a37b0c01c0baf1888ca8.ttf 301 [0.00, 127.0.0.1:47168]
request:   <AsgiRequest: GET '/styles.390dd2c0ffe3a954b1d6.css/MaterialIcons-Regular.a37b0c01c0baf1888ca8.ttf/'>
path:      styles.390dd2c0ffe3a954b1d6.css/MaterialIcons-Regular.a37b0c01c0baf1888ca8.ttf/
response:  <django.http.response.FileResponse object at 0x7f0b9c1bba90>
404?:      Yes
HTTP GET /styles.390dd2c0ffe3a954b1d6.css/MaterialIcons-Regular.a37b0c01c0baf1888ca8.ttf/ 200 [0.01, 127.0.0.1:47168]
HTTP GET /assets/img/favicon.png 301 [0.00, 127.0.0.1:47168]
request:   <AsgiRequest: GET '/assets/img/favicon.png/'>
path:      assets/img/favicon.png/
response:  <django.http.response.FileResponse object at 0x7f0b9c5f26a0>
404?:      No
```

The `ttf`-File is not in a folder `styles.390dd2c0ffe3a954b1d6.css` in the `collected-static` or `static` folder, it is just in the main folder. The favicon is actually in the `assets/img` folder from the `collected-static` or `static` folder. Thats the reason the fonts are not found. So the question is: Why is the `css`-filename in the path prefixed in first place?

**Comment by jsaalfeld** [comment]
If you append the following in the https://github.com/OpenSlides/OpenSlides/blob/master/openslides/core/views.py#L88 function, directly at the beginning, the site will be served correctly.

```
        fonts = ['woff2', 'woff', 'ttf', 'eot']
        if any(font in path for font in fonts):
            """
            Remove the `css`-Folder-Thingy
            """
            path = path.split('/', 1)[-1]
```

So the correct point has to found, where the `css`-folder will be prefixed to the font.

**Comment by FinnStutzenstein** [comment]
So, the issue lays in the client, sending the (wrong?) request url. The thing to check: what does angular do there? The server does exactly what the angular docs says about delivering a production build: Deliver all static files, if found, else the index.html

**Comment by tsiegleauq** [comment]
> So, the issue lays in the client, sending the (wrong?) request url.

so it seems, but I doubt that.
on django-wsgi, the client requests (i.e.):
`http://localhost:8000/styles.d1586b629dca15a1ea80.css/Roboto-Medium.90d1676003d9c28c0499.wof`

the same build of the client, simply copied to nginx, requests:
`http://localhost/Roboto-Medium.90d1676003d9c28c0499.woff2`

I don't thing there is an error in the configuration of angular

**Comment by jsaalfeld** [comment]
> I just tried to `wget` it and received the correct file. Even though the `/` was appended at the end.

I just compared the answers between https://nightly.demo.openslides.org/ and a locally setup instance with the small hack from [my last comment](https://github.com/OpenSlides/OpenSlides/issues/4091#issuecomment-452649789). A difference in the answers is indeed, that `nging` delivers the files directly, without appending the `/` at the ending.

When the https://nightly.demo.openslides.org/ requests the `styles.css` file it immediately receives a response. When the locally setup instance through the wsgi-server asks for the same file it first receives a `301` and points the browser to the same file, but with a `/` appended. So it effectively points to not to `styles.css`, but to `styles.css/`. This may be the issue as @FinnStutzenstein indicated initially, since the font-files are declared in the `styles.css` without a leading `/` the browser may interprets the `styles.css/` he gets pointed at not only as `css`-file but also as *folder*. Because the font-files are not declared with a leading `/`, so it is clear to the browser that they are on root level (or effectively at the same level as the `css`-file), it may confuse the browser to think that the font-files in the "folder" with the name `style.css`.

It is not possible and recommended to add `/` to the beginning of the font-file declarations in the `css`-file, but it should be possible to eliminate the trailing `/` in delivering the files through the wsgi-server to prevent the browser from thinking that the `css`-file is a folder.
