### ISSUE TITLE
Sort and filter refinements

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4098]
Some things I noticed.

Motions:
- [ ] "no workflows set" is not possible and should be removed.
- [ ] states should be splitted by first and last states. Last states are all states, with no following states, first states are all others.
- [ ] motion block filter should hide, if no blocks are in the db.
- [ ] if multiple filters are selected, there must be the plural (2 FILTERS)
- [ ] when sorting descending for identifier, the order should be (empty)->4->3->2->1. Currently empty identifier are always on the bottom

Assignments:
- [ ] What is the entry "Assignment" in the sort-menu? Maybe "Title" would be better.

Users:
- [ ] The group-filter is missing

Agenda:
- [ ] The filter-menu is missing

Should be done sometime..

**Comment by MaximilianKrambach** [comment]
> when sorting descending for identifier, the order should be (empty)->4->3->2->1. Currently empty identifier are always on the bottom

There should be some consent on what to do some time in this project. I had this discussion last week with @emanuelschuetze), with the result that empty/undefined stuff always should come last.

For the others: I'm working on these in between more important stuff
