### ISSUE TITLE
Handle deleted elements that are on the projector

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#4105]
See https://github.com/OpenSlides/OpenSlides/pull/4081#discussion_r246116913

When an element, that is on a projector, is deleted, we shoud/could do something. Either remove that element from the projector, send an error to all clients or something else.

**Comment by FinnStutzenstein** [comment]
Whats easy is just to ignore entries on the client. Means, that elements, where no data is found (I still have to look in your PR how the data is handeled), are skipped. This results in configurations, that may be crowded with dead entries, so I would prefer to take some extra steps on the server..

I think we must just care about direct mappings between models and slides. So, if a user is deleted, just user slides must be removed. If we couple models to slides (Is this a good idea? May this be helpful in the future?), the step of removing all slides in the generic delete method of all models seems simple to me.

**Comment by ostcar** [comment]
as discussed.
