### ISSUE TITLE
Dialogs should not easily close

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#4116]
please enable shift-enter to save Dialogs (some probably already do)
please prevent that you can close the dialog using "escape" button
please prevent that you can close a dialog by clicking on the grayed out part of the screen

**Comment by GabrielInTheWorld** [comment]
I take this one.

**Comment by FinnStutzenstein** [comment]
This PR is just for the create change reco dialog. Either rename this issue to the specific dialog, of fix all others, too. If this should be the case for every dialog, we might find a generic solution.
