### ISSUE TITLE
Improve password reset process

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#412]
It is confusing for new users. Insert a new button which does the two steps in one.

**Comment by normanjaeckel** [comment]
@emanuelschuetze You might find a smart solution with AngularJS.

**Comment by emanuelschuetze** [comment]
I'll look at it later - for 2.0

**Comment by normanjaeckel** [comment]
This is not solved. The process is still complex.

**Comment by emanuelschuetze** [comment]
Can you explain what you see as perfect solution here? Maybe we can make a new issue with this requirements to close this old, very long issue.

**Comment by normanjaeckel** [comment]
The solution is explained in my post from 3 Apr 2013 with your comment from 15 Apr 2013.

**Comment by emanuelschuetze** [comment]
Ok, I see..

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze closed with PR #2314 .

**Comment by emanuelschuetze** [comment]
Done with #2314. Closed.

**Comment by donovaly** [comment]
Many thanks! This solves a lot of troubles.
