### ISSUE TITLE
example_data_generator doesn't create users or assignments

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#4172]
The current version of the `example_data_generator` only creates `motions` and `topics` (or it adds the `motions` as `topic`).

But it does not create `admin_users` or `staff_users`, even though the script shows no error:
```
$ python manage.py create-example-data
Start creating 100 topcis ...
100 topcis successfully created.
Start creating 100 motions ...
100 motions successfully created.
Start creating 100 assignments ...
100 assignments successfully created.
Start creating 100 staff users ...
100 staff users successfully created.
Start creating 100 default users ...
100 default users successfully created.
```

It seems they are _somewhere_, because on a second execution the script throws an error:
```
$ python manage.py create-example-data
Start creating 100 topcis ...
100 topcis successfully created.
Start creating 100 motions ...
100 motions successfully created.
Start creating 100 assignments ...
100 assignments successfully created.
Start creating 100 staff users ...
FAILED: The requested staff users to create are already existing...
Start creating 100 default users ...
FAILED: The requested staff users to create are already existing...
```

But the users are not selectable (as in motion assignemnts) or viewable (as in user overview) in the client. Assignments are also not visible in the client. Motions and Topics work as expected.

**Comment by emanuelschuetze** [comment]
Still the same error with current master...
```FAILED: The requested staff users to create are already existing...```

**Comment by emanuelschuetze** [comment]
Retested with fresh (sqlite) database. Works now. 100 normal users and 100 staff users are created successfully.
