### ISSUE TITLE
Restructure personal notes

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4180]
The current personal note service works for the peronal note component. But every ViewMotion must save the personal note inside it, to sort and access it everywhere.
Add the personalnote to the motion repo, which cares about setting these information right. Use the personal note service for updating the notes.

Fixes performance issues in https://github.com/OpenSlides/OpenSlides/blob/master/client/src/app/site/motions/services/motion-repository.service.ts#L115 and in https://github.com/OpenSlides/OpenSlides/blob/master/client/src/app/site/motions/components/motion-detail/motion-detail.component.ts#L489

**Comment by FinnStutzenstein** [comment]
More: With #4229 the personal notes need a repository serice. The personal note service should make usage of the personal note repository.

**Comment by emanuelschuetze** [comment]
done in #4992
