### ISSUE TITLE
RuntimeError: SET_NULL_AND_AUTOUPDATE is used in an invalid usecase. Please report the bug!

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#4192]
Create a motion. Create an "Ändernugsantrag". Now try to delete the original motion.

You get the Runtimeerror

**Comment by emanuelschuetze** [comment]
I can't reproduce it with current master... Can you try again please?

**Comment by normanjaeckel** [comment]
Can't reproduce too.

**Comment by FinnStutzenstein** [comment]
Should be fixed with #4447 . Can you try it again?

**Comment by emanuelschuetze** [comment]
> Should be fixed with #4447 

Yes, confirmed.
