### ISSUE TITLE
OpenSlides 2.3 is Always in OfflineMode

### ISSUE THREAD

**Issue by mwaeckerlin** [OpenSlides/OpenSlides#4208]
![grafik](https://user-images.githubusercontent.com/4056726/51906824-6023d000-23c5-11e9-803d-05009f0a3532.png)

I try to run OpenSlides 2.3 (the current stable release) in docker.

`Dockerfile`:
```Dockerfile
FROM mwaeckerlin/base
ENV VERSION                     "2.3"
ENV SOURCE                      "https://files.openslides.org/releases/${VERSION}/openslides-${VERSION}.tar.gz"
RUN apk add --no-cache --purge --clean-protected -u python3 python3-dev gcc libc-dev
WORKDIR /tmp
RUN wget -qO- $SOURCE | tar xz
WORKDIR /tmp/openslides-${VERSION}
RUN python3 setup.py install

USER ${RUN_USER}
CMD openslides start --local-installation

EXPOSE 8000
```

Compile it and run:
```bash
docker run -it --rm --name openslides -p 8000:8000 -u root mwaeckerlin/openslides openslides
```

So basically, the installation is as follows:
 - get an Alpine Linux (the same problem occurs in Ubuntu too)
 - install `python3`, `python3-dev`,  `gcc` and `libc-dev`
 - download and extract https://files.openslides.org/releases/2.3/openslides-2.3.tar.gz
 - run `python3 setup.py install`
 - run `openslides start --local-installation`
 - connect to http://localhost:8000
 - enter user: `admin`, password: `admin`

Then you always get the error message: `Offline mode: You can use OpenSlides but changes are not saved.`

What's the problem?

**Comment by tsiegleauq** [comment]
There is a dedicated OpenSlides repository for docker and docker related questions. See the readme: [Using the Dockerfile](https://github.com/OpenSlides/OpenSlides#using-the-dockerfile)

You can find OpenSlides docker [here](https://github.com/OpenSlides/openslides-docker)

**Comment by mwaeckerlin** [comment]
> There is a dedicated OpenSlides repository for docker and docker related questions.

Well, @tsiegleauq, I can open the same ticket there too, but I don't think the problem is related to docker. And I am not using their Dockerfile, because that does not work either. I tried to reproduce the problem as simple as possible, and that's the spec above.

**Comment by tsiegleauq** [comment]
> I don't think the problem is related to docker. 

If you think there is a bug in OpenSlides, try to reproduce and document it (here) without using docker. For the time being, I am closing this issue. @jsaalfeld will (most likely) take that on OpenSlides/openslides-docker

> I am not using their Dockerfile

In this case you might help to enhance our Dockerfiles on OpenSlides/openslides-docker ;-)

**Comment by mwaeckerlin** [comment]
It's strange: Now it works. I cannot explain it, there is no difference in the setup.

Yes, I recommend to use [mwaeckerlin/openslides](https://github.com/mwaeckerlin/openslides): It works and it is much simpler and straight forward.
