### ISSUE TITLE
change the session cookie name

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#424]
If another django project runs on localhost, both apps use a cookie with the same name. So we have to find a way to change the name of the cookie name.

**Comment by FinnStutzenstein** [comment]
@ostcar Can be closed. The cookie is named `OpenSlidesSessionID` as well as the csrf token `OpenSlidesCsrfToken`.

**Comment by ostcar** [comment]
If there are two different OpenSlides instances on the same domain, then this is not fixed. But you can argue, that this is not important.

If you like, you can close this issue.

**Comment by emanuelschuetze** [comment]
I would close this. @FinnStutzenstein What do you mean?

**Comment by FinnStutzenstein** [comment]
Close :)
