### ISSUE TITLE
Update workflows for allow_submitter_edit

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#4245]
@normanjaeckel As discussed please adapt built-in workflows (remove 'allow_submitter_edit' flag for submitted in simple workflow and permitted in complex workflow) and create migration file.

**Comment by emanuelschuetze** [comment]
see #4236

**Comment by normanjaeckel** [comment]
See #4703

**Comment by emanuelschuetze** [comment]
Done.
