### ISSUE TITLE
Check for terser update (>3.16.0)

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#4248]
`npm run build` (production build) failed because terser released today v3.16.0 which is broken! 
Hotfix: downgrade to 3.14.1 (see https://github.com/OpenSlides/OpenSlides/pull/4247/commits/a4fcc4312178dafb2425467c57d945add5f7d376)

Check for next terser release.

**Comment by tsiegleauq** [comment]
Upstream Issue:
https://github.com/webpack-contrib/terser-webpack-plugin/issues/66

**Comment by MaximilianKrambach** [comment]
seems to be solved in 8f83fc1bd51029f3f4d05d2aedef0146a9d7f00b (Feb, 20 2019)

**Comment by emanuelschuetze** [comment]
> seems to be solved in 8f83fc1 (Feb, 20 2019)

No. In current master we use a pinned version of terser in package.json ("3.16.1") instead of a "^3.16.1". We have to test if a current terser version works.

**Comment by tsiegleauq** [comment]
from the [thread I mentioned on Feb the 3 of 2019](https://github.com/webpack-contrib/terser-webpack-plugin/issues/66#issuecomment-461023846)

> @afide1 Hey, its been fixed, all you need to do is update terser-webpack-plugin to v1.2.2 +

I'll give it a try later.

**Comment by tsiegleauq** [comment]
Terser is working just fine in angular 8.1 and 8.2
