### ISSUE TITLE
Error Messages in ajax-requests

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#425]
If a request does not run as expected, we send a error-message with messages.error(...). Sometimes this messages is returned before the view reaches his normal return-statement.

If it is a ajax-request, we have to find a way to send the error-messages in a json-package.

See 'def set_publish_status(request, poll_id):' in assignment.views. Line 253 in the current revision.

**Comment by emanuelschuetze** [comment]
no longer required in angular 2.0 client
