### ISSUE TITLE
fix category sorting in BaseSortListService

### ISSUE THREAD

**Issue by MaximilianKrambach** [OpenSlides/OpenSlides#4282]
Currently the baseSortListService sorts motions by categories after `motion.category.toString()`, whereas we rather want to sort it like in the #4275 sortViewCategoriesByConfig function.
This wasn't directly achieved and is hereby left for later.

**Comment by GabrielInTheWorld** [comment]
Still happening?

**Comment by tsiegleauq** [comment]
Categories are now sorted by their "weight". The sorting can be adjusted at runtime
https://github.com/OpenSlides/OpenSlides/blob/1d718dcb740066a5b8474033352c1bbd69a49102/client/src/app/core/repositories/motions/category-repository.service.ts#L87-L88
