### ISSUE TITLE
Seperate Schema changes and Data Changes in Migrations to prevent Errors

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#4311]
To prevent errors like #4266 or #4310 from happening, we should separate the Schema and Data Changes in Migrations. The following Migrations are still prone to this error and should be separated and looked at (grepped for `RunPython` in the `openslides`-folder):

  - [ ] `openslides/agenda/migrations/0002_item_duration.py`
  - [ ] `openslides/agenda/migrations/0005_auto_20180815_1109.py`
  - [ ] `openslides/core/migrations/0001_initial.py`
  - [ ] `openslides/core/migrations/0007_auto_20180130_1400.py`
  - [ ] `openslides/core/migrations/0014_changed_default_font.py`
  - [ ] `openslides/core/migrations/0002_misc_features.py`
  - [ ] `openslides/core/migrations/0008_changed_logo_fields.py`
  - [ ] `openslides/core/migrations/0004_auto_20170215_1624.py`
  - [ ] `openslides/users/migrations/0002_user_misc_default_groups.py`
  - [ ] `openslides/users/migrations/0007_superadmin.py`
  - [ ] `openslides/users/migrations/0003_group.py`
  - [ ] `openslides/motions/migrations/0005_auto_20180202_1318.py`
  - [ ] `openslides/motions/migrations/0011_motion_version.py`
  - [ ] `openslidesmotions/migrations/0002_misc_features.py`
  - [ ] `openslidesmotions/migrations/0021_state_access_level.py`
  - [ ] `openslides/motions/migrations/0003_motion_comments.py`
  - [ ] `openslides/motions/migrations/0006_submitter_model.py`
  - [ ] `openslides/motions/migrations/0012_motion_comments.py`

**Comment by normanjaeckel** [comment]
Please avoid to harm my PR #4148. ;-)

**Comment by FinnStutzenstein** [comment]
All current migrations work in postgres now and the two types of migrates are seperated.
