### ISSUE TITLE
Add option to print current IP adress(es) to projector

### ISSUE THREAD

**Issue by Hackwar** [OpenSlides/OpenSlides#4327]
I'm going to use OpenSlides on a Raspi with the ansible scripts and the plan is, that I simply plug it into a network outlet and my laptop into another and then I should somehow find out the IP adress. However I have no deeper access to the network infrastructure and thus have no idea what IP the raspi is going to get assigned. Thus I have no idea how to access the projector. It would be cool if I could setup the raspi at home to display a page with the current IP adress and thus when I plug in the raspi into the projector, I get a big message how to access it. :-)

**Comment by normanjaeckel** [comment]
@ostcar Any idea? I remember a discussion about this IP address guessing ...

**Comment by FinnStutzenstein** [comment]
The server can find out the ip. On startup, the server can add a Slide to all projectors with the ip. The slide can be displayed as message. This should be fairly simple.

**Comment by tsiegleauq** [comment]
Relevant for 3.1? I don't really mind this feature

**Comment by FinnStutzenstein** [comment]
> The server can find out the ip.

Yeah not really if I think about it. E.g. is the setup is more than just one worker (e.g. a nginx infront of the worker), the server cannot find out the ip. we _could_ introduce this feature, but for the majority of cases it will be wrong.

**Comment by emanuelschuetze** [comment]
Moved to 3.2

**Comment by ostcar** [comment]
This is not relevant anymore for OpenSlides 4. Since we require https, it is not possible to connect with a valid certificate.
