### ISSUE TITLE
New interface to set user groups and permission (as matrix)

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#435]
We need a better overview of all groups and their permissions at one(!) page with possibility to enable/disable special permissions via mouse click.

Suggestion: build overview as matrix table like [permissions dialog in Gallery3](http://codex.galleryproject.org/Gallery3:Modules:permissions_dialog_usability):
```
         read   write  ...
role 1    X       -
role 2    X       X
role 3    -       -   
```

**Comment by emanuelschuetze** [comment]
We have to discuss the ui concept. Implement it in angular should be easy. It's a 2.1 feature...

**Comment by normanjaeckel** [comment]
Short note to everybody who concerns: After merge of this feature it is (more or less) necessary to reset the database because we do not have any migrations between the old and the new built-in groups.

**Comment by ostcar** [comment]
Is it possible to create migrations? One gole of OpenSlides 2.0 was, that there is no need to recreate the Database. At least from 2.0 to 2.1 an Update should be possible.

If I would be still active in OpenSlides, I would Veto this pull request without a migration

**Comment by Shirk** [comment]
I’m strongly with @ostcar - migrations should be of huge concern as having to reset your database is probably the worst thing you can do to a user without having a major release jump to argue for it.

**Comment by normanjaeckel** [comment]
See #2315.
