### ISSUE TITLE
CSV User import fails on big datasets

### ISSUE THREAD

**Issue by Hackwar** [OpenSlides/OpenSlides#4356]
For an event I wanted to import all our members into the DB to then be able to select the people present. I created a CSV file with all 1800 names and selected to import it and the preview is correct, but when importing it, it takes several minutes and then a timeout error is displayed at the top. The import is not done, at least not at that time. I wouldn't consider a CSV file with 1800 rows of first and last name particularly big and would expect it to import all of this in a matter of maybe a minute or less.

I'm using this on the OpenSlides 2.3 Windows portable package on a quite potent 8-core i5 system with more than enough RAM (16GB).

**Comment by Hackwar** [comment]
It also resulted in the process crashing and the sqlite DB later on being corrupted after killing the process.

**Comment by tsiegleauq** [comment]
SQLite will find it's limits for that amount of data (>500). The use of a "real" database and caching is required for more than 1000 users. SQLite is really just to play around and developing OpenSlides.
The easiest thing for you to do is to setup OpenSlides BigMode

Please see:
https://github.com/OpenSlides/OpenSlides#installation-for-big-assemblies
and:
https://github.com/OpenSlides/OpenSlides/blob/master/DEVELOPMENT.rst#openslides-in-big-mode

**Comment by Hackwar** [comment]
I've used the script by @ostcar to set this up on a raspi with the bigmode setup (and provided some fixes for that script) and that had the same issue. It honestly actually looks more like the import is having problems with reading the data.

**Comment by ostcar** [comment]
We don't support sqlite anymore
