### ISSUE TITLE
User import: CSV File Format

### ISSUE THREAD

**Issue by Hackwar** [OpenSlides/OpenSlides#4357]
On my first import attempt of my user CSV file, I had a file with just first and lastname as the only columns in it. The file contained the column headers as described below the import. This resulted in the firstname being put into the title field and the lastname in the firstname field. Since we have the column headers present, can't you map that correctly?

**Comment by Hackwar** [comment]
This happened on OpenSlides 2.3

**Comment by tsiegleauq** [comment]
Apparently, you missed the hints directly under the import page ;-)
You can download the example.csv, adjust it to your need and upload it.
These field in the _correct order_ are required.
`Title, Given name, Surname, Structure level, Participant number, Groups, Comment, Is active, Is present, Is committee, Initial password Email`

```
Please note:
Required comma or semicolon separated values with these column header names in the first row:
Title, Given name, Surname, Structure level, Participant number, Groups, Comment, Is active, Is present, Is committee, Initial password Email
At least given name or surname have to be filled in. All other fields are optional and may be empty.
Only double quotes are accepted as text delimiter (no single quotes).
Download CSV example file
```
![image](https://user-images.githubusercontent.com/10233032/53330010-bf560100-38ed-11e9-87e3-ef3e60705e49.png)

**Comment by MaximilianKrambach** [comment]
Perhaps an additional info: We currently do not map the header names, but only  their order. This is due to a design decision far back, where the headers were made translatable.

So we can't know which header is which, and we have to rely on that order. Some 'advanced import' may be possible, but is low priority.

I'll reopen and self-assign this (would be for 3.1+, though).

**Comment by tsiegleauq** [comment]
you forgot to reopen
