### ISSUE TITLE
Scrolling necessary in modals even in Full HD

### ISSUE THREAD

**Issue by Hackwar** [OpenSlides/OpenSlides#4358]
When editing a motion, etc. in a modal, the modal is often enough higher than the screen and there is no scrollbar. My screen is Full HD and I'm using OpenSlides 2.3.

**Comment by tsiegleauq** [comment]
Cannot reproduce. Tested on current firefox and current chrome.
What browser are you using?

**Comment by Hackwar** [comment]
I'm using current firefox, but I have a slightly smaller window. Besides the taskbar at the bottom of my screen, I have the menu bar displayed in my browser, the tabs, the adress bar and a bookmarks bar, so my usable screen area is 933px high.

**Comment by tsiegleauq** [comment]
I am curious if there will ever be a 2.3.1, since the milestone got removed.
was something planned there @emanuelschuetze?

**Comment by emanuelschuetze** [comment]
There is no 2.3.1 milestone any more. We currently develop 3.x only. This issue can be closed.
