### ISSUE TITLE
TS-Lint-Plugin shows wrong deprication warnings on overloaded methods

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/OpenSlides#4413]
If an overloaded method has members that are deprecated, the ts-lint-plugin seems to show a deprecation warning for every method with the same name.

An issue was filed in the upstream repository and this issue is for tracking this error: https://github.com/Microsoft/typescript-tslint-plugin/issues/59

**Comment by jsaalfeld** [comment]
The issue shifted to: https://github.com/Microsoft/TypeScript/issues/30181

**Comment by tsiegleauq** [comment]
Not an OpenSlides issue.
