### ISSUE TITLE
Change password for user is missing

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4428]
In the list view is no link to the change user password page (as an admin). Neither is in the detail view. This must got lost somehow.

**Comment by MaximilianKrambach** [comment]
An administrator should only reset the password to the default one, or reset and give a new default password. Admin should not just assign a new password for someone.

What is indeed missing is the `ResetPasswordConfirmComponent` which seems to be used nowhere right now (resetting to the default password)

**Comment by MaximilianKrambach** [comment]
see #4431

**Comment by MaximilianKrambach** [comment]
fixed with #4431
