### ISSUE TITLE
Track serviceworker issues to resolve #4458

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4460]
The angular issue for this: https://github.com/angular/angular/issues/20970
PR (currently work-in-progress): https://github.com/angular/angular/pull/21842

If this is upstream and released, we can revert the changes in #4458 and use the `registerImmediately` strategy to load the SW.

**Comment by tsiegleauq** [comment]
Thanks.
However, that might not be the only thing. We already tried to remove all `setInterval` and `setTimeout` from OpenSlides without ever reaching a stable ApplicationRef state

**Comment by FinnStutzenstein** [comment]
see comment in #4458 : It may not be our mistake, becuase `interval` and `setInterval` are not used much and `setTimeout` *should* not be a problem..

**Comment by tsiegleauq** [comment]
Was basically resolved in https://github.com/OpenSlides/OpenSlides/pull/4462
Since upstream stuff might change, I leave that open nevertheless. Perhaps we can clean up the app component after this was resolved upstream

**Comment by FinnStutzenstein** [comment]
I guess we have not to change anything, even if the upstream gets more features. So I'll close this issue.
