### ISSUE TITLE
Fix required_users_to_see in some motion state cases (access level problem)

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#4465]

**Comment by normanjaeckel** [comment]
Problem here is that motions can be in different access level (state). But at the moment the logic only checks the can_see permission. To check also the can_see_metadata permission e. g. I have to handle the requesting user to the "required_user" system. @ostcar I propose to remove the can_see_permission check in utils access_permission and do this check in every app. (An in motion app I can do extra checks according to access level.) Ok?

**Comment by ostcar** [comment]
ok. But please keep in mind, that this method is called very often, so every implementation has to be very fast (no db request, if possible, no redis requests etc.)

**Comment by emanuelschuetze** [comment]
@normanjaeckel Is this still relevant after rework access levels for motions? I think we can close it...

**Comment by emanuelschuetze** [comment]
done in 3.0 I think
