### ISSUE TITLE
Fix redirection on legal notice and privacy policy

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4474]
Wait for #4473 and #4471 to be merged. A reload on the LN or PP redirects to login. This needs to be excluded in the `OpenSlidesService`. Maybe check why `redirectUrl` may not be set correctly.

**Comment by tsiegleauq** [comment]
This will also affect links which were generated by the reset-password function.

Furthermore, this issue [have been resolved bevore](https://github.com/OpenSlides/OpenSlides/pull/4251)
