### ISSUE TITLE
Missing Autoupdate for motion change recommendations

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4491]
CRs are accessible via their own model or as a root res element of motions. If a CR is created for a motion, just the CR-model gets an autoupdate. The motion is not updated. Also the cache is inconsistent: There is a CR in it's own model but no CR listed in the motion (there is an empty array, if the motion was newly created).

**Comment by normanjaeckel** [comment]
See #4193. The Change Recommendation was added in motion serializer in #4194. I can now try to trigger some kind of signals, but I am not sure whether @ostcar will like it ...

**Comment by emanuelschuetze** [comment]
@normanjaeckel It is important to get a (hot) fix for this issue. Later we can discuss a better solution.

**Comment by normanjaeckel** [comment]
I added a hotfix: @ostcar What's your opinion?

**Comment by FinnStutzenstein** [comment]
To track this: #4506
