### ISSUE TITLE
Difference “is_committee” and the “Committee” group?

### ISSUE THREAD

**Issue by soerface** [OpenSlides/OpenSlides#4503]
When creating a new participant, you can add them to the group "Committee". Also, you can tick the “Is a committee” checkbox at the end of the page.

I can't find any documentation about this, what is the difference between the two?

**Comment by emanuelschuetze** [comment]
The "is a committee" flag is just for statistic and filter.
The built-in group "Committee" is for users which using a committee account (e.g. as submitter).
You can decide if you need the flag or/and the group.
