### ISSUE TITLE
Projector messages are escaped too much

### ISSUE THREAD

**Issue by soerface** [OpenSlides/OpenSlides#4504]
On the projector view you can create message overlays. When using Umlauts in the text, it will be properly displayed on the projector, but on the admin page the title of the message will be escaped wrongly (`&ouml;` visible)

![image](https://user-images.githubusercontent.com/967243/54243459-d1a87f80-4528-11e9-99aa-aea3e9187276.png)

**Comment by emanuelschuetze** [comment]
I can confim it.

**Comment by tsiegleauq** [comment]
OK. Will consider that when reworking messages.
(First community reported OS3 issue :tada:)

**Comment by FinnStutzenstein** [comment]
Yes, this view will be removed and messages will be created in the projector detail view. We will make sure, that umlauts are escaped correctly there.

**Comment by tsiegleauq** [comment]
Solved via #4547
