### ISSUE TITLE
Jump to page x in list views

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/OpenSlides#4526]
Currently the user can't jump to a selected page. The same behavior is seen when going back to the page the user was before he navigated to a detailed/ other route.

This issue relates to https://github.com/angular/material2/issues/7615

**Comment by tsiegleauq** [comment]
No pages in the list view anymore

**Comment by divStar** [comment]
> 
> 
> How about converting the `.mat-paginator-range-label` to a mat-select so a user can choose the range directly.
> 
> Would look like this:
> ![image](https://user-images.githubusercontent.com/22171609/41898966-88306d50-792b-11e8-955b-97291bab04d2.png)

So there's still no "Jump to page" or "Jump to range" label + selection box? Is there a reason? Should we be implementing our own solutions?

**Comment by tsiegleauq** [comment]
> > How about converting the `.mat-paginator-range-label` to a mat-select so a user can choose the range directly.
> > Would look like this:
> > ![image](https://user-images.githubusercontent.com/22171609/41898966-88306d50-792b-11e8-955b-97291bab04d2.png)
> 
> So there's still no "Jump to page" or "Jump to range" label + selection box? Is there a reason? Should we be implementing our own solutions?

I suppose you were commenting in the wrong issue tracker. We are not using paginated list views anymore. If you are having a problem using OpenSlides, please open a new issue.
