### ISSUE TITLE
PDF-Creation for elections fail

### ISSUE THREAD

**Issue by hpd1979** [OpenSlides/OpenSlides#4528]
Hi, 
if the candidate list is to long (i.e. more than 16 candidates) you got a PDF with two white sheets.

P.S.: The bug occurs in the Windows-portable Version of Openslides 2.3

**Comment by tsiegleauq** [comment]
Cannot reproduce on [demo](https://demo.openslides.org/). Made 20 candidates, printed the ellection PDF, printed the ballot, both seem fine. 

Seems to be a local issue or an issue in the windows portable version.

**Comment by hpd1979** [comment]
We made 28 candidates, printed the PDF an voila to white sheets. We reduce the candidates to 16 and voila you get the a "normal" voting sheet. 
Probably really a issue of the windows portable, we changed nothing on the local windows portable version. So it as out of the box...

**Comment by tsiegleauq** [comment]
Assignments allow to create either the "Assignment" PDF or the "Ballot Paper PDF".
Currently, it is not clear what you try to create. I can create both the Assignment PDF and the Ballot PDF without hassle on demo.

Other relevant information: to reproduce that include your Opearion System, Browser and Patch version

**Comment by tsiegleauq** [comment]
Closed due to inactivity and missing information

**Comment by AnanasPizza** [comment]
Used this demo system and created a ballot paper here:
https://demo.openslides.org/18/assignments/3

Result attached, broken pdf.

[Wahl - Wahl des Vorstandes - stimmzettel (1).pdf](https://github.com/user-attachments/files/25813460/Wahl.-.Wahl.des.Vorstandes.-.stimmzettel.1.pdf)

**Comment by Elblinator** [comment]
@AnanasPizza Please open a new Issue for that. 
And give screenshots of what you want to share, we do not like to download PDFs from github
The History of this issue is not relevant due to the issue being about OS 2.3 and now OS being on version 4.2 (and soon 4.3)
