### ISSUE TITLE
implementing assignments functionality

### ISSUE THREAD

**Issue by MaximilianKrambach** [OpenSlides/OpenSlides#4558]
Related to #4537:

Due to delays on my part, it may be more efficient to split some requirements off this rather big chunk. These could be separated
(the idea is making the PR mergeable, and then continue with these:)

- [x] sorting list of candidates
- [x] debugging/fixing the potential server issue
- [x] pdf creation (ballots and results)
- [x] layout and page animation (WIP: #4577)
 - [x] layout: mobile view
- [ ] Clarify handling of ex-candidates (#4581)
- (optional) Display the elected candidates  in the summary (#4579)

**Comment by tsiegleauq** [comment]
I consider elections feature complete. The missing point has it's own issue already, this can therefore be closed.
