### ISSUE TITLE
Set font information for uploaded file is allowed for admin group only

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#4572]
Try to set font style for an uploaded font file as staff user (with manage permission) -> 403!
Try to set it as admin -> 200

**Comment by normanjaeckel** [comment]
The staff user should get the permission core.can_manage_logos_and fonts and the client should check this permission in mediafiles interface.

**Comment by emanuelschuetze** [comment]
Right! With this addtional permission it works as expected.

I think we should move the permission "can_manage_logos_and_fonts" from core to mediafiles. What do you think?

**Comment by normanjaeckel** [comment]
Hm. The technical issue here is that the client offers changes of config variables in the mediafile app. So for this permission it is the same. The permission is checked in core app in ConfigViewSet. So it belongs to core. But from its meaning it belongs to mediafile ... I do not know, what to do.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Is this still relevant?

**Comment by emanuelschuetze** [comment]
> The technical issue here is that the client offers changes of config variables in the mediafile app. So 
> for this permission it is the same. The permission is checked in core app in ConfigViewSet. So it 
> belongs to core. 

Ok, I understand... Then let us do this quick solution: Show the logo controls (checkboxes in menu) only for users with "can_manage_logos_and_fonts" permission. Currently the controls are listen to "mediafiles.can_manage".

@tsiegleauq Can you change the permission check please?

**Comment by emanuelschuetze** [comment]
already done in 3.0
