### ISSUE TITLE
Handling of removed candidates

### ISSUE THREAD

**Issue by MaximilianKrambach** [OpenSlides/OpenSlides#4581]
How to handle candidates that have removed their candidature during an assignment?

1. Create an assignment with candidate A and B
2. Create a poll
3. Remove candidate A
4. Try to mark Candidate A as elected - results in error, but the candidate is still in the poll options

**Comment by GabrielInTheWorld** [comment]
Is this still existing?
It seems, that any error is catched, but the candidate still stays in the poll options.

**Comment by emanuelschuetze** [comment]
is elected is removed in current master (3.2-beta)
