### ISSUE TITLE
Implement mark down or similar for texts

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#461]
It would be good if the admin could choose a mark up language for texts in the system. Django can do this, please enable it!

**Comment by FinnStutzenstein** [comment]
@ostcar @emanuelschuetze We do have now a WYSIWYG editor. Do we need any markup?

**Comment by emanuelschuetze** [comment]
Currently we use CKEditor with HTML markup for a lot of text fields. This should be enough for formatting. -> closed.
