### ISSUE TITLE
Original motion is not projected after amendment

### ISSUE THREAD

**Issue by elanfer** [OpenSlides/OpenSlides#4677]
Used version: dd66e7505dcac024524f0f6bd3eab96cef069540

When creating an amendment to a motion that is in complex workflow, a amendment takes the system default workflow (which may differ to the selected workflow of a motion) on creation and the original motion cannot be projected anymore. After switching the workflow type to the same of the original motion, the projection works again. 

**How to reproduce?**
1. create a motion in complex worklfow (definition after installation)
2. create a amendment to this motion (will be created in simple workflow)
3. Try to project the original motion

**Debugging Output** 
JS console gives the output: `motion 1 can not be on the state with id 1`

**Comment by tsiegleauq** [comment]
Confirmed.

@FinnStutzenstein it seems you want to provide a server side fix for that? That *could* be fixed in the client as well during the creation of an amendment, however, I would not recommend that.

Furthermore, changing the workflow of an amendment should not be possible itfp

**Comment by FinnStutzenstein** [comment]
> Furthermore, changing the workflow of an amendment should not be possible

Hmm, maybe someone has another workflow for amendments... @emanuelschuetze ? If so, we should have a config field for the default workflow of amendments and make sure, that the client/server can handle different workflows of main motion and an amendment. Why even does the server throw an issue (question to myself ;), the output from Eric suggests that this is server output..)?

If not, I would agree with that. What should happen, if the main motion's workflow ill be changed? I would suggest, that also the states of all amendments will be reset to the new workflow's first state. Then we should make a workflow change non-trivial in the UI, e.g. moving the workflow selector out of the edit-view and handle this seperate with a dialog confirming changing all amendments, too.

**Comment by elanfer** [comment]
Yep, there could be other workflows that are used for amendments, for example, an amendment may not be observed by several extra commissions like an original motion and the workflow for deciding an amendment can be much quicker. So having different workflow options for original motion and amendments is useful in my opinion. 
So a fix that the projection is working for motions with amendments that have different workflows than the motion might be the best way.
