### ISSUE TITLE
Check motion slide code

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4683]
In PR #4682 I added a todo. @CatoTH can you heck, if this is correct. This resulted in a `cannot read property map of undefined`. To recreate: Create a complex motion and an amendent (a standard one, without paragraph selection). Project the lead motion.

**Comment by CatoTH** [comment]
Hm, it doesn't hurt. But that is data being sent from the server directly, right? Maybe It would make sense to filter the amendments on the server side already.

**Comment by FinnStutzenstein** [comment]
Can you please chack the server code and make the required changes there?

**Comment by CatoTH** [comment]
Ok, I have to correct myself. It probably is better not to rely on amendment_paragraphs being an array, it being null for amendments is probably better (or at least not worse). Therefore, doing this on client side should be just fine. Maybe just move the early return a bit to the top, as the operations above are not necessary in that case. :-)
