### ISSUE TITLE
Enhance the reset password confirm view

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4685]
This is the current reset password confirm view and it is not beautiful. Whats todo (in my opinion):

- Add the blue banner with the OS logo, as in the login view.
- Make the buttons nicer
- General: do we want clicked links to appear magenta-ish?

![reset-pssword-confirm](https://user-images.githubusercontent.com/8439581/57504604-66dfae80-72f5-11e9-8ddb-4459dcca2f4a.jpg)

**Comment by GabrielInTheWorld** [comment]
Could you tell, please, when this issue happens? Thanks!

**Comment by FinnStutzenstein** [comment]
In my case every time i paste the reset-pw-url into the browser and load the page.
