### ISSUE TITLE
Add transaction to speaker management

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#4697]
It happened in production that a user is twice on the list of (coming) speakers (probably race condition by different workers). So we have to add a transaction or a lock here.

**Comment by FinnStutzenstein** [comment]
What type of locks can we use? If two requests are served by different worker processes, we may need a distributed lock, e.g. using the cache's locking feature. I thing a threading.Lock (and so a asyncio.Lock) is not enough.

Another way would be a DB transaction, where we make sure, that between the check, if the user is there, and the insertion noone makes changes.
