### ISSUE TITLE
Projector socket connection cannot be established

### ISSUE THREAD

**Issue by InterFelix** [OpenSlides/OpenSlides#4720]
I am using the OpenSlides Docker image in an nginx reverse proxy environment. We have a little problem with the projectors not working if OpenSlides is not accessed via HTTPS. There is no automatic redirect, I also couldn't find any information on configuring automatic redirect directly in OpenSlides. The WebSocket connection for the projectors is not established over HTTP, our nginx doesn't even get requests or throw exceptions.

**Comment by tsiegleauq** [comment]
> We have a little problem with the projectors not working **if OpenSlides is not accessed via HTTPS**

Sounds like it's working alright.

HTTP, OpenSlides, Nginx and Projectors are usually no problem.
Please try to reproduce this issue **without docker**. Every docker related issue goes to (depending what your setup was build on): 

https://github.com/OpenSlides/openslides-docker-compose
or
https://github.com/OpenSlides/openslides-docker

**Comment by tsiegleauq** [comment]
Closed due to inactivity
