### ISSUE TITLE
Config CSS mobile

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4724]
Two fixes required for the mobile config view:

1) Checkbox labels need to break
![Screenshot_20190518-184820](https://user-images.githubusercontent.com/8439581/58016960-5a323600-7aff-11e9-87c3-1fcd6521e1f2.jpg)

2) The help text is sometimes very long. Either we do need more static space or maybe it is possible to make this space dynamic.
![Screenshot_20190518-184850](https://user-images.githubusercontent.com/8439581/58016961-5a323600-7aff-11e9-9025-4ce9fafbb54c.jpg)

**Comment by GabrielInTheWorld** [comment]
@FinnStutzenstein please close as discussed
