### ISSUE TITLE
OpenID Connect Login

### ISSUE THREAD

**Issue by throwException** [OpenSlides/OpenSlides#4736]
I would like Support for OpenID Connect Login. This should automatically create new accounts for everyone authenticated with the configured OpenID Connect server with the claimed username, displayname and email address. It should also have a mechanism obtain group memberships from a profile API and automatically assign these upon login.

This would make Openslides more useful for organization with already employ an Single-Sign-On solution for their members.

I suggest testing against Yahoo! ID and Keycloak.

**Comment by tsiegleauq** [comment]
Would indeed be nice to have.
We used to support login over SAML as a plugin back in OpenSlides 2.X, therefore I consider knowledge about alternative login approaches to exist somewhere:tm: in the team.

However, I expect that to be quite time consuming to develop.
A pull request for this feature from the community would be very welcome.

might be relevant: [Allow Self-Registration](https://github.com/OpenSlides/OpenSlides/issues/4288)

**Comment by Atroposswiss** [comment]
+1 for @openID :)

**Comment by JamesofScout** [comment]
+1 For openid

**Comment by jsangmeister** [comment]
SAML login is now possible in OS4.

**Comment by Gusser93** [comment]
+ 1 For openid (which is not SAML (which is not the topic of this issue…))

**Comment by thegcat** [comment]
I reopened this specific issue in #6726 and provided a possible example integration.
