### ISSUE TITLE
Followup issue for #4639

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4738]
There is some workaround for https://code.djangoproject.com/ticket/30493 in the client code. If this issue is resolved and the next django version available, the `agenda/mixin.py` can be adapted to always give the `agenda_item_number` in every title information.

**Comment by FinnStutzenstein** [comment]
```
 def title_information_add_agenda_item_number(self, title_information):
        title_information["agenda_item_number"] = self.agenda_item.item_number
```

**Comment by FinnStutzenstein** [comment]
The fix is now in `django:master` :). The next release (2.2.2) is expected to be on June, 3, so we then have to upgrade django.

**Comment by GabrielInTheWorld** [comment]
Is this still existing?

**Comment by FinnStutzenstein** [comment]
Yes, we are waiting for a major release.
