### ISSUE TITLE
Ensure a proper version of packages in travis-ci

### ISSUE THREAD

**Issue by MK-intevation** [OpenSlides/OpenSlides#4749]
#4748 is just a hotfix in pinning down `angular/cli` in `travis.yml`; it would be better/more elegant to ensure that `client/package.json` and `travis.yml` always use the same version of `angular/cli`.

(The same for ensuring a certain version of node.js, although taht did not (yet) break things)

**Comment by MaximilianKrambach** [comment]
just a note: `export NG_FORCE_TTY=FALSE` would have probably solved the specific 'dialog of angular/cli stalling the build' problem, but that seems to be a temporary fix, and was removed again

**Comment by tsiegleauq** [comment]
we are now using github actions and installing packages usind npm ci, thus this was fixed now
