### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [OpenSlides/OpenSlides#4794]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/OpenSlides/OpenSlides/blob/master/client/package.json#L80

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by tsiegleauq** [comment]
has been added by @GabrielInTheWorld in https://github.com/OpenSlides/OpenSlides/pull/4598 (implementing the license crawler).

**Comment by FinnStutzenstein** [comment]
So it can be removed, right?

**Comment by tsiegleauq** [comment]
Most likely. Haven't had the time yet to dig deeper into that.

**Comment by DanielRuf** [comment]
> So it can be removed, right?

In general, yes it can be removed.

**Comment by tsiegleauq** [comment]
Solved via #4804
thanks @DanielRuf
