### ISSUE TITLE
The user cannot change the permission for 'can manage list_of_speakers'

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/OpenSlides#4824]
This is caused, because this permission exists twice - like seen in the picture below:

![double_list_of_speakers](https://user-images.githubusercontent.com/10206688/60727546-7159a580-9f3e-11e9-91e3-e0333abc6036.png)

**Comment by FinnStutzenstein** [comment]
Does this still happen?

**Comment by GabrielInTheWorld** [comment]
> Does this still happen?

No, this is fixed.
