### ISSUE TITLE
Client production build

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#4849]
I noticed, that Travis build took fairly long: 14-15 minutes for the production build, which run twice. I guess, this behavior came with Angular 8. @tsiegleauq @emanuelschuetze @GabrielInTheWorld  Do production builds on your machines also take longer or are they run twice? I didn't test this yet.

**Comment by emanuelschuetze** [comment]
`npm run build` of master needs ca. 12min on my local machine.

**Comment by tsiegleauq** [comment]
https://github.com/angular/angular-cli/issues/13734

https://github.com/angular/angular-cli/issues/14604
