### ISSUE TITLE
Refactor motion-pdf-catalog.service

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#4851]
Please refactor [motion-pdf-catalog.service.ts (line 123ff)](https://github.com/OpenSlides/OpenSlides/blob/master/client/src/app/site/motions/services/motion-pdf-catalog.service.ts#L123) as discussed with #4845:
- prevent page break after last category (in toc)
- add missing table [header](https://github.com/OpenSlides/OpenSlides/blob/master/client/src/app/site/motions/services/motion-pdf-catalog.service.ts#L120) for all table headers if exportSubmitterRecommendationl is enabled

**Comment by tsiegleauq** [comment]
add missing table header for all table headers if exportSubmitterRecommendationl is enabled was resolved with #4876
