### ISSUE TITLE
Amendment sorting in motion overview incorrect

### ISSUE THREAD

**Issue by cobii** [OpenSlides/OpenSlides#4881]
Amendmends are sorterd 1, 10, 11 ,12, 2, 3, 4, 5, 6, 7, 8, 9

**Comment by tsiegleauq** [comment]
- OpenSlides version
- Python version
- Browser with version

OpenSlides 3 is sorting like you would expect, see the screenshot below.

what you describe is logic sorting. In OpenSlides 2, it's meant to sort this way.

In your `settings.py` chance the following add leading zeros to new motions:
`MOTION_IDENTIFIER_MIN_DIGITS = 1`
to
`MOTION_IDENTIFIER_MIN_DIGITS = 3`

![image](https://user-images.githubusercontent.com/10233032/62131642-d903d600-b2db-11e9-9313-20d211d5e9a7.png)

**Comment by tsiegleauq** [comment]
Closed, due to inactivity and since this is not an issue
