### ISSUE TITLE
Elections: Could not add a new candidate and enter votes afterwards

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/OpenSlides#4914]
**Describe the bug**
If a user removes or adds a candidate in an election, the users in the existing poll-options get lost. So, in the assignment-poll there are no users and clicking on the "Enter votes"-button will lead to an error.

**How to Reproduce**
Steps to reproduce the behavior: preferably on [nighty](https://nightly.demo.openslides.org)

1. Go to 'Elections'
2. Click on 'New candidate' or remove an existing one
3. Click on 'Enter votes'
4. See error in the console and a white dialog.

**Expected behavior**
The users still exist and votes can be entered.

**System information**

- OpenSlides-Version: latest
- Python Version: 3.7
- Device: Notebook
- OS: Arch/Manjaro
- Browser: firefox, chrome
- Browser-Version: [e.g. 22]

**Additional context**
Add any other information to comprehend your problem

**Screenshots**
![Fail](https://user-images.githubusercontent.com/10206688/62929536-fb592180-bdba-11e9-98a9-9a045e4c435a.png)

**Comment by emanuelschuetze** [comment]
Can't reproduce it anymore.
