### ISSUE TITLE
<ctrl> Key deletes mark from marked text in the part "reason" of a motion 

### ISSUE THREAD

**Issue by cobii** [OpenSlides/OpenSlides#4986]
**Describe the bug**
When you want to copy a text from the "reason" part of a motion and use  "ctrl"+"c"  the mark dissapear emiditly. It's equal if you are a "Guest" or have admin rights.
* Marking Text and use context menu with right klick work.
* The word "reason" can be marked and copied via "ctrl"+"c".

**How to Reproduce**
1. Mark text in the "reason" section. 
2. press "ctrl"  maybe "cmd" on macOS

**System information**

- OpenSlides-Version: OpenSlides 3.0-gruene-20190905 (Lizenz: MIT) 
- Device: Desktop
- OS: WIN10  1803
- Browser: 
  * Chrome Version 76.0.3809.132 (Offizieller Build) (64-Bit)
  * FF 69

**Comment by tsiegleauq** [comment]
Thanks a lot for reporting this! Will be fixed soon
