### ISSUE TITLE
Project media file from folder results in 404

### ISSUE THREAD

**Issue by pitpalme** [OpenSlides/OpenSlides#5027]
**Describe the bug**
Adding a media file - here: a logo - in a folder and trying to project the file results in 404.

Not Found: /media//foobar/logo.png
HTTP GET /media//foobar/logo.png 404 [0.03, 127.0.0.1:55035]

**How to Reproduce**
1. Go to "Files"
2. Click "Create new folder" on top right
3. Name: "foobar", access group "Default"
4. Click "Save"
5. Click on folder name ("foobar") to "chdir()" into folder
6. Click "Add" on top right
7. Drag file (image format) onto drop area
8. Access groups "Default"
9. Click on "Upload"
10. Click media files menu right of file entry (three dots)
11. Click on "Project"
12. Select "Default projector"
13. Click on "Project"
14. Open projector view
15. Media file URL contains two slashes - between media root and path: "/media//foobar/..."

**Expected behavior**
The media file should be projected and visible.

**System information**

- OpenSlides-Version: 3,0
- Additional version information (if any): [e.g. commit hash or installation-month]
- Python Version: 3.7
- Device: MacBook
- OS: macOS Mojave
- Browser: Safari
- Browser-Version: 12.1.2

**Additional context**
Add any other information to comprehend your problem

**Screenshots**
<img width="538" alt="image" src="https://user-images.githubusercontent.com/748801/64996707-f833e280-d8de-11e9-8946-0706fee36e69.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/748801/64996739-0eda3980-d8df-11e9-9256-4d9dd84e3b78.png">

**Comment by tsiegleauq** [comment]
I can confirm this on nightly and demo.
However, I cannot confirm this on my local instances of OpenSlides. No matter if I use redis, SQlite or postres.

Seems like a setup issue

@gsiv @FinnStutzenstein any ideas?

**Comment by tsiegleauq** [comment]
Was a little more severe than I thought. Thanks for reporting that.
