### ISSUE TITLE
Event date on projector footer in unix time

### ISSUE THREAD

**Issue by pitpalme** [OpenSlides/OpenSlides#5028]
**Describe the bug**
The event date and time is show on projector footer as unix time, instead of natural date and time.

**How to Reproduce**
1. Go to "Settings" / "General"
2. Configure "Event date"
3. Open projector
4. See footer, right side

**Expected behavior**
Event date as "17.09.2019 15:00" .

**System information**

- OpenSlides-Version: 3,0
- Python Version: 3.7
- Device: MacBook
- OS: macOS Mojave
- Browser: Safari
- Browser-Version: 12.1.2

**Additional context**
Add any other information to comprehend your problem

**Screenshots**
<img width="698" alt="image" src="https://user-images.githubusercontent.com/748801/64997394-e6533f00-d8e0-11e9-979b-2c7eb4ae952c.png">
<img width="147" alt="image" src="https://user-images.githubusercontent.com/748801/64997384-ddfb0400-d8e0-11e9-9b73-ad329a8ff4ea.png">

**Comment by tsiegleauq** [comment]
Apparently it was originally supposed to be a string and not a date/timestamp
