### ISSUE TITLE
Buggy Input in Settings/Custom Translations

### ISSUE THREAD

**Issue by tosel** [OpenSlides/OpenSlides#5039]
**Describe the bug**
When you enter a new custom translation in the settings tab the following happens:
You begin typing and after three seconds auto-save saves the entry and you lose focus of the input-field. This menas you have to re-enter the input-field every three seconds.

**How to Reproduce**
1. Go to Settings
2. Click on Custom Translation
3. Add a new Custom Translation
4. See error as described above

**Expected behavior**
Stay in the input-field. When you enter a text in an input-field elsewhere in the settings-tab the text saves a second after you stop writing and you do not lose focus of the input-field.

**System information**

- OpenSlides-Version: 3.0
- Python Version: 3.6
- Device: PC
- OS: Windows 10
- Browser: chrome, edge

**Comment by tsiegleauq** [comment]
related to:
https://github.com/OpenSlides/OpenSlides/issues/4034

**Comment by tsiegleauq** [comment]
fixed in #4878
