### ISSUE TITLE
Closing list of speakers not shown

### ISSUE THREAD

**Issue by tosel** [OpenSlides/OpenSlides#5040]
**Describe the bug**
When you close the list of speakers this is not shown to the projector. In the backend everything changes perfectly but nothing is shown to the projector.

**How to Reproduce**
1. Go to Tagesordnung
2. Click on the list of speakers
3. Close this list
4. Nothing happens on the projector

**Expected behavior**
Display a notice/badge that the list of speakers is now closed.

**System information**
- OpenSlides-Version: 3.0
- Python Version: 3.6
- Device: PC
- OS: Windows 10
- Browser: chrome

**Comment by tsiegleauq** [comment]
That is currently intended. I am not sure if everybody would welcome that change.
@emanuelschuetze ?

**Comment by tosel** [comment]
In the previous 2.x version this has always been displayed. We would welcome such a sign for our events ;)
Thank you for your quick answer.

**Comment by emanuelschuetze** [comment]
We will think about this. Maybe we can show the lock icon on projector for a closed list of speakers - like in the detail view.

**Comment by tosel** [comment]
That would be great. 
Thank you

**Comment by tsiegleauq** [comment]
As far as I see, very little effort is required here.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Did you think about it? ;)

**Comment by emanuelschuetze** [comment]
As discussed: @tsiegleauq will add a lock icon on projector if list of speakers is closed

**Comment by tsiegleauq** [comment]
fixed by #5154
