### ISSUE TITLE
Unify config names

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#5098]
Currently there are some (boolean) configs for hiding and showing things. This might be confusing, if one needs to enable hiding some feature to see another one. These names can be unified to not confure users. 

See #5088

**Comment by tsiegleauq** [comment]
while we are at it, related issue #3622

**Comment by normanjaeckel** [comment]
Lets reopen a new issue if there are concrete renaming proposals.
