### ISSUE TITLE
Add permission type: "change username"

### ISSUE THREAD

**Issue by elanfer** [OpenSlides/OpenSlides#5124]
**Is your feature request related to a problem? Please describe.**
If you have a shared user account, which you want to use for special guests, the change of the username should not be allowed. Otherwise, a single person in this account can kick the others out by changing the username. Moreover like in other systems, administrators might not want that usernames can be changed, this is, for example, important if you follow a strict naming schema. 

**Describe the solution you'd like**
Add a new permission type 'change username', similar to other types that can affect the user profile.

**Comment by tsiegleauq** [comment]
could also be combined with the permission to change the password. If you may not change the password, you also may not change the username

**Comment by elanfer** [comment]
> could also be combined with the permission to change the password. If you may not change the password, you also may not change the username

I would go for an extra permission type. Otherwise, it will conflict with the username schema scenario I mentioned before. Because then you have users that maybe should change their passwords, but they should not be allowed to change their username to conflict a username rule.

**Comment by emanuelschuetze** [comment]
So, some common use cases for shared accounts are:
* diable changing password
* diable changing username
* disable adding personal notes in motions
* ...

Anything else?

**Comment by emanuelschuetze** [comment]
done in OS4 for change password (`can_change_own_password`)
