### ISSUE TITLE
Reorder of candidates and vote results

### ISSUE THREAD

**Issue by rudipf** [OpenSlides/OpenSlides#5125]
As noticed during convention, hence the bad description. Close if it is too badly described

**Describe the bug**
A reordering of candidates after opening the "Wahlgang" 

**How to Reproduce**
Version 3.0
Create "Wahl"
Enter Candidates
Close "Kandidatensuche"
Reorder Candidates
Open and Close "Wahlgang"
EnTer Results (Approval voting)
-> Results are displayed mixed up

**Comment by FinnStutzenstein** [comment]
We are currently implementing many more features around polls (elections and motions) and this particular feature will be present in the next release 3.1.

**Comment by tsiegleauq** [comment]
That's definitely a bug.

**Comment by FinnStutzenstein** [comment]
@tsiegleauq Oh yes, I think I misread the issue. We had a similar idea in the past where you could order the candidates *per poll* and not the assignment ones. I thought that was requested here.
