### ISSUE TITLE
Countdown in 3.0 behaving erratic

### ISSUE THREAD

**Issue by rudipf** [OpenSlides/OpenSlides#5126]
Observed during convention. Hence the bad description:

Version is 3.0 Browser is Firefox
Up to three different Countdowns are used and displayed , only one is running down

Countdown should _always_  jump to negative times displayed in red, after running down
Observed Behaviour:
Countdown jumps to a starting value above the original setting, without apparent reason
(We're using Stopwatches on our smartphones now)

**Comment by tsiegleauq** [comment]
Cannot reproduce. 
Having 5 different countdowns running like crazy works without flaw in my firefox

Please try to reproduce your issue on [nightly](https://nightly.demo.openslides.org/login) and/or [demo](https://demo.openslides.org/) and try to describe your bug more detailed, preferably using the bug-report template.

Wild guess: It **could** be a server or setup-issue. The clients [countdown-time-component](https://github.com/OpenSlides/OpenSlides/blob/master/client/src/app/site/projector/components/countdown-dialog/countdown-dialog.component.ts) simply listens to `core/servertime`. It does not have much own intelligence.

For instances hosted on the [openslides-server](https://openslides.com/), I can try to reproduce it locally.

![image](https://user-images.githubusercontent.com/10233032/68579064-970a3480-0473-11ea-9507-0657c25e30bb.png)

**Comment by tsiegleauq** [comment]
Closed due to inactivity. Could not be reproduced
