### ISSUE TITLE
No simple way to number candidates

### ISSUE THREAD

**Issue by rudipf** [OpenSlides/OpenSlides#5127]
As discovered during the convention

Depending on the details of the voting, it might be usefull to display the canidate list as a numbered list (Starting at 1) instead of a list with bullet points.
There is no obvious way to achieve this.

(Using notepad++ for now )

**Comment by FinnStutzenstein** [comment]
Hi, we can implement a setting for numbered/unordered candidate lists. This can be done system-wide in the config, on a per-assignment basis oder even per poll. How fine would you like to control this setting?

Also @emanuelschuetze

**Comment by rudipf** [comment]
Would love to see said option on ".../assignments/nn"

**Comment by FinnStutzenstein** [comment]
Server-side done in #5130 . TODO: Include this in the client.

**Comment by jsangmeister** [comment]
Done in https://github.com/OpenSlides/OpenSlides/pull/5207. Will be coming with 3.2
