### ISSUE TITLE
double slash in media URL

### ISSUE THREAD

**Issue by lafidi** [OpenSlides/OpenSlides#5136]
Hi,
I am using openslides 3 installed using PIP.

I uploaded some media files using the standard upload function in the files tab.
When clicking on a file, it is opened in the browser as expected.
When I try to project a file (PDF) it is not shown and the following error is raised:
`[2019-11-15 11:53:34 +0100] [1604] [WARNING] django.channels.server HTTP GET /media//Praesentationen/Antrag1.pdf 404 [0.02, 192.168.110.109:55672]`
Do you have an idea how to get rid of the double "/" which can also be found when the front-end is debugged using the browser's debugging tools.

Thanks for your support

Some more Output:
`[2019-11-15 12:10:38 +0100] [1702] [INFO] django.channels.server HTTP POST /rest/core/projector/1/project/ 200 [0.13, 192.168.110.109:36458]`
`[2019-11-15 12:10:39 +0100] [1702] [WARNING] django.request Not Found: /media//Praesentationen/Newsletter 2019-05 Helferzugang Anschreiben.pdf`
`[2019-11-15 12:10:39 +0100] [1702] [WARNING] django.channels.server HTTP GET /media//Praesentationen/Newsletter%202019-05%20Helferzugang%20Anschreiben.pdf 404 [0.03, 192.168.110.109:36392]`

**Comment by emanuelschuetze** [comment]
Please use current master. The reported mediafile bug is already fixed in master. We will release 3.1 in the next weeks...
