### ISSUE TITLE
timestamp in pdf-export / Agenda

### ISSUE THREAD

**Issue by bengoshii** [OpenSlides/OpenSlides#5183]
When you export the agenda to pdf the pdf shows the unix timestamp for the event instead of the human reading date.

The bug is not new:
https://github.com/OpenSlides/OpenSlides/issues/2440
and
https://github.com/OpenSlides/OpenSlides/issues/2413
but both bugs are closed.

- OpenSlides-Version 3.0

**Comment by emanuelschuetze** [comment]
This bug is already fixed in 3.1 - you can check it in current demo.openslides.org

**Comment by bengoshii** [comment]
No, it isn't. I just updated to 3.1 and the problem is the same (and I cleared the cached to be on safe side).

**Comment by bengoshii** [comment]
Sorry for reopening. Problem is solved.
For other people with the same error: After updating to 3.1 you have to put the date in the preferences new. Then the date will shown in human format instead of unix timestamp.
