### ISSUE TITLE
List of speakers covers motion reason

### ISSUE THREAD

**Issue by TheJoKlLa** [OpenSlides/OpenSlides#5203]
**Describe the bug**
An active list of speakers hiddes a long reason text on the projector. 

**How to Reproduce**
1. Create mention with long reason text
2. Show mention on projector
3. Add somebody to the speakers list
4. Set speakers list in "Einblendungs" mode

**Expected behavior**
Text of mention reason should float around the speakers list.

**System information**

- OpenSlides-Version: 3,1

**Screenshots**
![OpenSlide](https://user-images.githubusercontent.com/25747734/73396814-74552280-42e2-11ea-9e6e-385c31b8fd55.png)

**Comment by tsiegleauq** [comment]
I suppose that was intended.

**Comment by emanuelschuetze** [comment]
We cannot change it. It's an overview element. But you can use a second projector to show the current list of speakers in full screen.

**Comment by tsiegleauq** [comment]
Technically possible, but would annoy everyone else.
You may want wo write an own `motion-slide-component`
