### ISSUE TITLE
Moving Countdown

### ISSUE THREAD

**Issue by TheJoKlLa** [OpenSlides/OpenSlides#5204]
**Describe the bug**
The font of the countdown have a different number width, so by counting down the digits are moving on the projector.

**How to Reproduce**
1. Show Countdown on projector
2. Start Countdown

**Expected behavior**
Monospaced font or in div centered countdown

**System information**

- OpenSlides-Version: 3.1

**Comment by jsangmeister** [comment]
Fixed with #5378.
