### ISSUE TITLE
Motion Preamble is not shown in Motion creating

### ISSUE THREAD

**Issue by TheJoKlLa** [OpenSlides/OpenSlides#5205]
**Describe the bug**
You can set the motion preamble in the settings of openslides, but when you are creating an motion the preamble is not show over the decision field.
So a lot of our members create a mention with the preamble additional to the default.

**How to Reproduce**
1. Set a default motion preamble, example "The parliament decides, "
2. Create a new motion
3. Our Users set the decision to, "The parliament decides, to do ...", because the preamble is not shown.
4. Save the motion
5. See in the motion the Decision "The parliament decides, The parliament decides, to do ..."

**Expected behavior**
Motion preamble is shown atop of the decision field, like in the mention overview.

**System information**

- OpenSlides-Version: 3.1
***Example Images***
1. Step
![2020-02-03 15_53_15-Einstellungen - Anträge - OpenSlides](https://user-images.githubusercontent.com/25747734/73663484-ed1afc80-469d-11ea-8190-13e560f2dd7a.png)
2. Step, see no motion preamble
![2020-02-03 15_54_06-Neuer Antrag - OpenSlides](https://user-images.githubusercontent.com/25747734/73663485-edb39300-469d-11ea-8d0c-10d08f28147a.png)
3. Step, what our members do
![2020-02-03 15_55_49-Neuer Antrag - OpenSlides](https://user-images.githubusercontent.com/25747734/73663482-ed1afc80-469d-11ea-8a0f-bc820244d655.png)
4. Step, see the duplicate
![2020-02-03 15_56_57-9_ Test - OpenSlides](https://user-images.githubusercontent.com/25747734/73663483-ed1afc80-469d-11ea-80cd-2acfec3e9c0f.png)

**Comment by tsiegleauq** [comment]
Nothing to reproduce here. Try to stick to the issue template.

> **How to Reproduce**
> Steps to reproduce the behavior: preferably on [nighty](https://nightly.demo.openslides.org)
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **System information**
> 
> - OpenSlides-Version: [e.g. 2.1, 2.2, 2.3, 3,0]
> - Additional version information (if any): [e.g. commit hash or installation-month]
> - Python Version: [e.g. 3,5, 3.6, 3.7]
> - Device: [e.g. iPhone6, Notebook]
> - OS: [e.g. Andoird 7, iOS8.1, Windows 10]
> - Browser: [e.g. chrome, firefox, opera, edge, safari]
> - Browser-Version: [e.g. 22]
> 
> **Additional context**
> Add any other information to comprehend your problem
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by TheJoKlLa** [comment]
I hope the new description is clear enough

**Comment by TheJoKlLa** [comment]
While checking the motion edit mask, i suspect the decision title for the input field is missing.

**Comment by tsiegleauq** [comment]
Clear enough. Thanks.

@emanuelschuetze 
it was proposed to show the "motions_preamble" config variable in the motion create form above the first TinyMCE.

**Comment by emanuelschuetze** [comment]
> it was proposed to show the "motions_preamble" config variable in the motion create form above the first TinyMCE.

good idea. we should implement this.

**Comment by emanuelschuetze** [comment]
already done in 3.2-dev
