### ISSUE TITLE
Add definitions for full-qualified field and thelike

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#5213]
Can someone add some regexes to the openslides4-dev branch?

I propose the following regex for the full-qualified field (with a small change to our pad entry):

`^[a-z][a-z0-9_]*/[1-9][0-9]*/[a-z][a-z0-9_]*$`

There is no reason why collection should not contain digits and underscores at least in the middle or at the end (e. g. `citizen_1st_class_vip_super_user`) ;-)

**Comment by FinnStutzenstein** [comment]
https://github.com/OpenSlides/OpenSlides/wiki/DE:-Konzept-OpenSlides-4#19-einheitliche-namensgebung

We should keep collections simple. There is no need to allow numbers in them, becuase this is an indication for structuring collections. (This might be possible, but this is too complex for now. E.g. how should the client know, which structured collections exist?)

**Comment by normanjaeckel** [comment]
No numbers in collection is ok for me.

**Comment by jsangmeister** [comment]
They exist (at least) in the datastore: https://github.com/OpenSlides/openslides-datastore-service/blob/main/datastore/shared/util/key_types.py#L18 ff.
