### ISSUE TITLE
Move getIds endpoint back to reader

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#5217]
Can you move the getIds endpoint back to the reader? I do not think that this has anything to do with the writer.

**Comment by FinnStutzenstein** [comment]
Yes it does, because in the way we implemented it (not pushed yet), a call to get_ids will manipulate the database. So write and get_ids are the only two calls writing to the DB. It is easy to change the url and host for get_id, isn't it?

**Comment by normanjaeckel** [comment]
What is the db change if I call getIds?

For me it is not ust about using another URL bit using another service class which must be injected and some points of the code. But of course I can solve it if it is really necessary.

**Comment by jsangmeister** [comment]
It's documented and probably resolved by now; closing this.
