### ISSUE TITLE
Allow “majority“ as vote count

### ISSUE THREAD

**Issue by justcomplaining** [OpenSlides/OpenSlides#5269]
If a result is obvious, it is tedious and unnecessary to count the majority and much easier to only count the minority. At the moment, we circumvent the problem by just setting the majority to the maximum number (999 or something like that) but a dedicated "majority" option would look much better. Exact percentages should not be available in this case (as the total number is not available).

**Comment by emanuelschuetze** [comment]
OpenSlides suppors already the "majority" flag for motion votes. You can enter "-1" as special value which means "majority". Or you click on the majority checkbox. Try it out in our current demo: demo.openslides.org.
