### ISSUE TITLE
User-import via text does not work

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/OpenSlides#5306]
**Describe the bug**
When a user tries to import new users by using the text-importer, the preview works correctly. If the user then clicks on the "Import" button, an issue occurs with no description - although the server responds with statuscode "200".
The userlist was not updated, too.

The csv-import works fine.

**How to Reproduce**
Steps on current master-branch.

1. Go to 'users/import'
2. Enter a username, which does not already exist, for example "Batman"
3. Click on 'Preview'
4. Then click on 'Import'
5. See error, that nothing is imported.

**Expected behavior**
The users are imported correctly and the userlist will contain the new created users.

**System information**

- OpenSlides-Version: current master
- Additional version information (if any): [e.g. commit hash or installation-month]
- Python Version: 3.8
- Device: Notebook
- OS: Arch-Linux
- Browser: chrome
- Browser-Version: 80

**Comment by FinnStutzenstein** [comment]
Should be fixed with #5303

**Comment by GabrielInTheWorld** [comment]
> Should be fixed with #5303

No, this is still the behaviour on the latest master-branch.

**Comment by FinnStutzenstein** [comment]
Did you test #5303 or master?

**Comment by jsangmeister** [comment]
Can confirm. Will look into this

**Comment by FinnStutzenstein** [comment]
Sorry, I meant #5305 . The fix from joshua (#5313) is exactly the fix for this issue (There is a `parseFloat` in #5303, but this is OK), so it can be merged.
