### ISSUE TITLE
Cannot set manually created workflows as default

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#5318]
**Describe the bug**
Manually created workflows cannot be set as default workflow for both motions and amendments

**How to Reproduce**
- motions/workflow
- hit plus
- name the workflow whatever
- save
- workflow list should be "simple workflow, complex workflow, whatever"
- settings/motions
- no "whatever" in default workflow

**Expected behavior**
Manually created wokflows should be available as default workflow

**System information**

- OpenSlides-Version: 3.1
- Additional version information (if any): master
- Python Version: 3.8
- Device: All
- OS: All
- Browser: All

**Comment by FinnStutzenstein** [comment]
Hi, I know, that this bug exists and the reason why; I suggest that we talk about it, because it is not as easy to fix, when real-time updates should work. What should work currently just fine is restarting the server (This should work I hope), which may not a solution desired for production use ;)
