### ISSUE TITLE
Note generic relations in models.txt

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#5337]
We should add a note in models.txt which relation is a generic relation the other side:

E. g. here: https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/models.txt#L385

**Comment by FinnStutzenstein** [comment]
Hi, I stumbled upon the same "issue". Here is what I've done in the client (search for `possibleViewModels` for other relations). E.g. tags: https://github.com/OpenSlides/openslides-client/blob/master/client/src/app/core/repositories/relations.ts#L453

Can you propose a syntax for the models.txt?

**Comment by normanjaeckel** [comment]
```
Interface mediafile {
   ...
   attachment_ids: (*/attachment_ids)[];  // may refer to topic or motion
}
```

**Comment by FinnStutzenstein** [comment]
Hm, this is a bit informel as a comment. It is not enforced, that it is required to specify the foreign models.

**Comment by jsangmeister** [comment]
Suggestions:

    attachment_ids: (<topic|motion>/attachment_ids)[];

    attachment_ids: (<topic,motion>/attachment_ids)[];

    attachment_ids: ({topic|motion}/attachment_ids)[];

    attachment_ids: ({topic,motion}/attachment_ids)[];

**Comment by FinnStutzenstein** [comment]
I like the set notation. I'll create a PR.
