### ISSUE TITLE
Check motion_category

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#5338]
In models.txt the motion_category collection is sometimes only called category. This has to be fixed.

**Comment by FinnStutzenstein** [comment]
Do you have some examples?

**Comment by normanjaeckel** [comment]
https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/models.txt#L417

https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/models.txt#L10

**Comment by FinnStutzenstein** [comment]
Done in #5327
