### ISSUE TITLE
Remove relation from motion to workflow

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#5339]
In v3.x we do not have a direct relation from motion to workflow. The relation works over the state. So I propose also to remove this relation in models.txt for v4.x.

https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/models.txt#L530

**Comment by FinnStutzenstein** [comment]
Yes you are right; I'm currently working on the relations and I'll add this to #5327 .

**Comment by FinnStutzenstein** [comment]
Done.
