### ISSUE TITLE
Show begin of event and duration in the agenda

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#5345]
**Is your feature request related to a problem? Please describe.**
You can configure the event date and time in the agenda settings. Since OpenSlides 3.0, it was never evaluated.

**Describe the solution you'd like**
We should show date, the time and the predicted finishing time in the agenda. The predicted finishing time can easily be calculated in the client. We should keep in mind that a conference can take multiple days - additional information might be required.
For example, we might want to be able to create a time table for large events.

**Describe alternatives you've considered**
Alternatively, we could remove the setting entirely. It seems that it was not required in the last couple of mayor events.

**Additional context**
During universal lock down and remote conferencing, this feature might be getting more interesting. Currently, there is clear way for a user to know when a conference starts (end ends). Administrators are supposed to enter this information in the starting page, add it in the e-mail or use alternative ways of communication.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze has to decide this. Removing an unused feature is the best way, but we may think about users that still have to migrate from OS2 to OS3. This feature was implemented back in OS2 and we decided not to drop features. But is it is unused...

**Comment by emanuelschuetze** [comment]
done in OS4
