### ISSUE TITLE
SAML client authentication error can_see_frontpage

### ISSUE THREAD

**Issue by philippst** [OpenSlides/OpenSlides#5353]
Thank's a lot for this great OS project! 😍
Can you help us on the following issue?

**Describe the bug**

After configuration OpenSlides SAML authentication, we are facing a issue right after user is authenticated and redirected back to OpenSlides. Instead of a working OpenSlides UI, the loading indicator is stuck and console shows `Authentication Error! Required: "core.can_see_frontpage"`. 

This issue only happens right after SAML authentication / redirect. Reloading webpage resolves problem.

Debugging `AuthGuard::canActivate` and `Operator::hasPerms` methods indicate, that user object / user permissions are not set at the time the router guard is checked (async, done once?). Later on the operator methods return the expected user data. But this does not seem to affect loading indicator / frontpage any more.

**How to Reproduce**

*SAML Authentication required to reproduce issue.*

1. Set up and configure SAML IDP
2. Open OpenSlides login mask (user unauthenticated)
3. Authenticate via SAML IDP
4. User agent is redirected back to OpenSlides
5. Front page is stuck with loading indicator and console error `Authentication Error! Required: "core.can_see_frontpage"`
6. After reloading OpenSlides page (pressing F5) everything is working (user is authenticated as expected, required permissions available)

**Expected behavior**

After authenticating user via IDP and redireting to OpenSlides, user expects working ui.

**System information**

- OpenSlides-Version: 3.2
- Additional version information (if any): master / latest
- Python Version: [e.g. 3,5, 3.6, 3.7]
- Device: PC
- OS: Windows 10
- Browser: Chrome / Firefox
- Browser-Version: current

**Additional context**

- Issue can not be reproduced using OpenSlides internal authentication; seems to be related to SAML authentication / redirection procedure
- No further issues regarding SAML configuration, user sync, logout, etc. is working as expected

**Comment by FinnStutzenstein** [comment]
HI, thanks for the report! Coincidentally I was working on this logic this morning for the next upcoming OpenSlides4 release. Yes, it seems that the operator is not fully loaded. I never experienced this in a local setup, I'll have a look.

**Comment by FinnStutzenstein** [comment]
I didn't come to an error page since I was stuck on a spinner, that didn't disappeared. Did you had an issue with the spinner before?

**Comment by philippst** [comment]
Yes, exactly I was stuck at the spinner in Chrome too. But just here in this described situation, no other spinner problems so far.

Your pull request looks good to me. I can confirm that these changes solve this bug. Thanks a lot!

**Comment by tsiegleauq** [comment]
@FinnStutzenstein any relevance for 3.4?

**Comment by FinnStutzenstein** [comment]
I think not
