### ISSUE TITLE
Only the admin group can control the projector

### ISSUE THREAD

**Issue by Wannenhero** [OpenSlides/OpenSlides#5361]
**Describe the bug**
Giving a participant group the permission "Can manage the projector" allows them to edit color, size etc. of the projector, but not to set countdowns etc. on the projector. Like this, only the admin group can actually control what happens on the projector.

**How to Reproduce**
Steps to reproduce the behavior on [nighty](https://nightly.demo.openslides.org)

1. Log in as admin
2. Add new user as member of group "Staff"
3. Check that group staff has permission "Can manage the projector"
4. Login as that new user
5. Click on projector in the menu on the left
6. Click on the default projector

You get taken to the Projector view filling the whole tab

**Expected behavior**
After step 6 i would expect to land at the page managing the projector. This is what happens when you do step 5 and 6 as admin. 

**System information**

- OpenSlides-Version: 3.2master (same on [nighty](https://nightly.demo.openslides.org))
- Additional version information (if any): commit c5dd2ea261e4fcde89388d2a98b5f37993aec5c3
- Device: Notebook
- OS: Arch Linux
- Browser: firefox
- Browser-Version: 76.0.1

**Comment by tsiegleauq** [comment]
Already resolved in #5359

**Comment by tsiegleauq** [comment]
#5359 was merged. Closing.
