### ISSUE TITLE
CSV export of participants doesn't contain usernames

### ISSUE THREAD

**Issue by Wannenhero** [OpenSlides/OpenSlides#5362]
**Describe the bug**
The CSV export of participants does not contain usernames.

**How to Reproduce**
Steps to reproduce the behavioron [nighty](https://nightly.demo.openslides.org)

1. Go to 'participants'
2. Click on the menu on the top right
3. Click on 'export as CSV'
4. Open the downloaded file

The downloaded file participants.csv contains no column with usernames. 
![Screenshot of participants.csv](https://user-images.githubusercontent.com/23235949/81506006-cea74b80-92f3-11ea-8d07-793e7a690497.png)

**Expected behavior**
The downloaded file participants.csv should contain a column containing usernames.

**System information**

- OpenSlides-Version: 3.2master (same on [nighty](https://nightly.demo.openslides.org))
- Additional version information (if any): commit c5dd2ea261e4fcde89388d2a98b5f37993aec5c3
- Device: Notebook
- OS: Arch Linux
- Browser: firefox
- Browser-Version: 76.0.1

**Comment by tsiegleauq** [comment]
I suppose that's intended. Upon importing the CSV again the user name is optional and will be generated for you. What you are proposing is a feature.

**Comment by tsiegleauq** [comment]
#5598
