### ISSUE TITLE
Use tinymce 5.3+

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#5383]
With pullrequest #5382 tinymce was pinned to version 5.2.2 because toolbar icons are not found with version 5.3+.

**Comment by hjelperne** [comment]
Hi, I am using tinymce (along with tinymce-vue) in a vue project and experienced the same issue (icons not found) after updating from 5.2.1 -> 5.3.1. 
I manually added 
`import "tinymce/icons/default/icons"`
in main.js 
and after that everything appears to be working again.
Not sure why this was necessary though - didn't need it before..
Just thought I would mention it in case it relates to your project somehow.

**Comment by tsiegleauq** [comment]
It feels like TinyMCE's minor versions include breaking changes almost every time.

**Comment by grekier** [comment]
In 5.3, they moved the icons to a different folder so it needs to be added depending on your setup. I can confirm that importing works fine when webpack is used.
