### ISSUE TITLE
Adopt schema changes in OS3 to OS4

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#5406]
- [x] agenda items now have tags
- [x] Jitsi configs in core: `general_system_conference_auto_connect`, `general_system_conference_show`
- [x] ~~Fonts: `font_monospace`~~ (invalid, not in schema anymore)
- [x] Agenda config: `agenda_show_first_contribution`
- [x] Assignment config: `assignment_poll_default_type`
- [x] Motion config: `motion_poll_default_type`
- [x] Changes in https://github.com/OpenSlides/OpenSlides/pull/5376

Note: I'm not sure, if I had adopt some of them already...

**Comment by jsangmeister** [comment]
Added all settings related fields in #5460

**Comment by FinnStutzenstein** [comment]
See #5477

**Comment by FinnStutzenstein** [comment]
TODO: https://github.com/OpenSlides/OpenSlides/pull/5564/files

**Comment by FinnStutzenstein** [comment]
- [ ] https://github.com/OpenSlides/OpenSlides/pull/5644/files
- [ ] https://github.com/OpenSlides/OpenSlides/pull/5695/files
- [ ] https://github.com/OpenSlides/OpenSlides/pull/5707/files
- [ ] https://github.com/OpenSlides/OpenSlides/pull/5718/files
Done until #5783
