### ISSUE TITLE
Lower the required Chromium version

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#5413]
Currently Debian has Chromium 80 as the stable version (https://packages.debian.org/search?keywords=chromium). I was greeted with an "unsupported browser" this morning. Can you please lower the version? Currently, no debian-chromium user can use OpenSlides (without explicitly install the testing version).

**Comment by FinnStutzenstein** [comment]
And from my experience: Chromium 80 is well supported ;)

**Comment by FinnStutzenstein** [comment]
Additionally: If your browser is supported, there is no way to navigate back to OpenSlides. A close-button or so would help there.

**Comment by tsiegleauq** [comment]
You can skip the warning by clicking the OpenSlides logo. Once logged in, you'll only be greeted with the warning if automatic redirection from the login to OS was not working (i.e. the ooerator was gone)

**Comment by emanuelschuetze** [comment]
@tsiegleauq Please set chromium min version to 80 today. Thx.

**Comment by tsiegleauq** [comment]
#5414
