### ISSUE TITLE
Änderungsantrag zu null

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#5426]
**Describe the bug**
When creating a amendment the title will be `Änderungsantrag zu null` (in german, did not test other languages).

**How to Reproduce**
Currently visible on [nighty](https://nightly.demo.openslides.org) (17.6.2020)

- enable amendments in the settings
- create a motion in the Complex workflow, with a t tile and some text
- create an amendment. Select a paragraph, change something, click on `create`

Happens on current master (->nightly)

**Comment by tsiegleauq** [comment]
Confirmed. Complex workflows do not have an identifier. falling back to identfier-or-title should be enough

**Comment by FinnStutzenstein** [comment]
Done in #5427
