### ISSUE TITLE
PDF export fails

### ISSUE THREAD

**Issue by leonfc** [OpenSlides/OpenSlides#5439]
**Describe the bug**
Cannot export PDFs from any view in self-hosted instance (docker), "Creating PDF file ..." notification remains visible as the following type error is thrown: `i.columns[0].stack is undefined` (in  `0-es2015.4397f10b4da010d91d4e.worker.js:1:1401935`)

**How to Reproduce**
Cannot reproduce on demo/nightly system.

**Expected behavior**
Successful pdf generation.

**System information**

- OpenSlides-Version: 3.2
- Additional version information (if any): master
- Python Version: 3.7.7
- Device: Notebook
- OS: Linux
- Browser: Tested with latest Firefox and Chromium

**Additional context**
- Installed from https://github.com/OpenSlides/openslides-docker-compose
- Running behind Traefik reverse proxy
- When clicking any "Export as PDF" button, firefox prints `Please prefix the URL "media/ourlogo.png" with a slash.`, then a few HTTP GETs to the file, then a GET to the script that throws the error, then the error.

**Comment by leonfc** [comment]
The problem was that one image was selected as header left/right and footer left/right all at once, after choosing one everything is working. If this is meant to be like that, a warning would be helpful at this point IMO. Maybe this behavior correlates with image size - I didn't test other images.

**Comment by FinnStutzenstein** [comment]
> The problem was that one image was selected as header left/right and footer left/right all at once, after choosing one everything is working.

This is a good hint! Maybe @GabrielInTheWorld  or @tsiegleauq can check the behavoir, if one image used multiple times fails. My guess is that this is not related to the deployment, so it should be recreateable in the dev setup. But it still can be a deployment thing...

**Comment by tsiegleauq** [comment]
it's most likely in my pdf code

**Comment by tsiegleauq** [comment]
Seems like footer-left logo is broken. Once you set a left footer loko pdf generation fails. The same logo on the three other corners seems to work fine.
