### ISSUE TITLE
Time calculation in the list of speakers is wrong

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#5445]
With this dataset for a speaker, the shown time is wrong.
```
             {
                "id": 14,
                "user_id": 58,
                "begin_time": "2020-06-19T13:58:43.072571+02:00",
                "end_time": "2020-06-19T13:58:20.616786+02:00",
                "weight": null,
                "marked": false
            },
```
LOS:
```
Max Mustermann -1:23 m (Startzeit: 19.6.2020, 13:58:43)
```
It should be -0:23m

Please ignore why we got a negative time here, this is another issue. But with negative intervals, the time method is wrong. THis should be checked. Maybe there are other bugs...

**Comment by ostcar** [comment]
I am not sure if this is an issue for the client or server. Please remember: If you change any data format on the server, then ping me so I can also change the data format in the autoupdate-service

**Comment by FinnStutzenstein** [comment]
Purly client and nothing OS3+/OS4 related.

**Comment by tsiegleauq** [comment]
yes. `Math.floor(-23/60)` will result in `-1`. And `"-0"` is 0. A whole lot of fun this one.
