### ISSUE TITLE
blanked Pages on macOS

### ISSUE THREAD

**Issue by duhrkah** [OpenSlides/OpenSlides#5459]
**Describe the bug**
Pages not showing entries.

**How to Reproduce**
Steps to reproduce the behavior: preferably on [nighty](https://nightly.demo.openslides.org)

Open some Pages like Poll or Patricipant

**Expected behavior**
On e.g. Windows-PC the Page is showing the created Participants, on macOS it only shows the number of entries in the left corner, but the page is blanked.

**System information**

- OpenSlides-Version: 3.2-master
- Python Version: 3.7.3
- Device: MacBook Air 2018
- OS: macOS Big Sur,  Version 11.0 Beta & macOS Catalina 10.15
- Browser: Safari
- Browser-Version: [13 & 14

**Additional context**
Is happening on every OpenSlides Instance is installed, even on different systems.

**Screenshots**
[screenshot](https://prnt.sc/ten7fn)

**Comment by tsiegleauq** [comment]
It seems like nGrid does not render. @duhrkah can you try to use Chrome and Firefox to see if the problem also appears there?
