### ISSUE TITLE
Reverse Proxy Setup (Loading Data Screen)

### ISSUE THREAD

**Issue by BerberBerthold** [OpenSlides/OpenSlides#5469]
I have set up openslides, and it seems to work just fine, it is running and listening to port 8000 on localhost.

Now I would like to access it from a public address, so I have set up an apache webserver and added a reverse proxy with the following configuration.

```
<VirtualHost *:8443>
	ServerAdmin webmaster@localhost
	ServerName example.com

	
	Include /etc/letsencrypt/options-ssl-apache.conf
	ServerAlias www.example.com
	SSLCertificateFile /path/to/fullchain.pem
	SSLCertificateKeyFile /path/to/privkey.pem

	ProxyRequests Off
	<Proxy *>
		Order deny,allow
		Allow from all
	</Proxy>
	<Location />	
		ProxyPass http://localhost:8000/
		ProxyPassReverse http://localhost:8000
	</Location>
</VirtualHost>
```
Obviously the domain name and the paths to the certificates were adjusted.

I can reach the server, and I can log in, but after logging in, I get a "Loading Data" screen that doesn't go away and I can't proceed.  This doesn't happen when I just login on my machine locally.  Apparently the server tries to access or provide some files, but it can't when I access it via the apache reverse proxy.

Can anyone help?

**Comment by tsiegleauq** [comment]
You need to forward `/apps` `/media` `/rest` and `/ws` from your local webserver to `http://localhost:8000` (your OpenSlides server).
This is more a question about apache than a question about OpenSlides, hence I cannot really help with apache configuration. We are usually using nginx for our productive setups, you can see an example configuration [here](https://github.com/OpenSlides/openslides-docker-compose/blob/master/client/nginx.conf) and try to adjust it to apache.
