### ISSUE TITLE
Backend can't reach the authentification service

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/OpenSlides#5475]
When you execute `make run-dev` in the main repo and try to execute an action, the backend returns a `400: Bad Request`. If you look into the log of the backend, it says the following:

    DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9004
    DEBUG:openslides_backend.services.authentication:Cannot reach the authentication service on http://localhost:9004. Error: HTTPConnectionPool(host='localhost', port=9004): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb840fc6f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
    DEBUG:openslides_backend.services.authentication:Auth cannot be reached. Fall back to guest mode.

I don't know if the issue stems from a wrong configuration in the backend, the auth service or the docker containers.

**Comment by FinnStutzenstein** [comment]
Move to the backend, not a setup error. `AUTH_HOST` and `AUTH_PORT` are set correctly.
