### ISSUE TITLE
make run-prod fails

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#5482]
**Describe the bug**
In the readme is a description how to start openslides4:

https://github.com/OpenSlides/OpenSlides/blob/4484d1e4ef5274e6868fe2b1840814673d2e0282/README.md

Currently, they do not work.

**How to Reproduce**
```
$ git clone git@github.com:OpenSlides/OpenSlides.git
$ cd OpenSlides
$ git checkout openslides4-dev  # needed, until OS4 is released
$ make run-prod
```
This produces:
```
git submodule status | awk '{ gsub(/[^0-9a-f]/, "", $1); gsub("-","_",$2); print toupper($2)"_COMMIT_HASH="$1 }' > .env
docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
WARNING: The OPENSLIDES_DATASTORE_READER_PORT variable is not set. Defaulting to a blank string.
WARNING: The OPENSLIDES_DATASTORE_WRITER_PORT variable is not set. Defaulting to a blank string.
WARNING: The OPENSLDIES_AUTH_SERVICE_COMMIT_HASH variable is not set. Defaulting to a blank string.
WARNING: The OPENSLDIES_AUTH_SERVICE_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file is invalid because:
Service backend has neither an image nor a build context specified. At least one must be provided.
make: *** [Makefile:25: build-prod] Fehler 1
```

**Expected behavior**
Start OpenSlides without errors and warnings.

Could someone help me to start OpenSlides4 so I can work on #5476?

**Comment by ostcar** [comment]
Ok. I found the information here: https://github.com/OpenSlides/OpenSlides/pull/5476/files#diff-f785e9e46b9afd2567df7a658338db17

So #5476 fixes this issue.

**Comment by FinnStutzenstein** [comment]
In #5476 it won't be fixed in the way, that it works, but it will be fixed because there is a new notice, to not use prod ;) dev is currently the way to go.

https://github.com/OpenSlides/OpenSlides/pull/5476/files#diff-04c6e90faac2675aa89e2176d2eec7d8R21
