### ISSUE TITLE
UI: result page seems empty when too short

### ISSUE THREAD

**Issue by kaffeeringe** [OpenSlides/OpenSlides#5525]
When I call the user overview, scroll down a page and then type in the name of a user it seem as if there's no result, because the page stays scrolled down. I have to scroll up to find the search result. I already thought there were users lost until I found out I had to scroll up.

**How to Reproduce**
Steps to reproduce the behavior: preferably on [nighty](https://nightly.demo.openslides.org)

1. Go to 'users"
2. Scroll down a page or two
3. type in the lastname of a user
4. See an empty page that you have to scroll up to see the result

**Expected behavior**
I expect the page to show the result without scrolling

**System information**
Your install ;-) https://spdsh.openslides.com

**Additional context**
Add any other information to comprehend your problem

**Screenshots**
See? "1 von 107" but the page seems to be empty - until you scroll up:
![Screenshot_2020-08-25 Teilnehmende - OpenSlides](https://user-images.githubusercontent.com/367592/91146530-4c327400-e6b7-11ea-970e-82dc0b6d409a.png)

**Comment by tsiegleauq** [comment]
The size of the virtual scrolling components do not update automatically after manual filtering. That's simply a side effect of virtual scrolling and thus clearly a wontfix from me. I leave this issue open untill I can pin down the error in ngrid.

**Comment by emanuelschuetze** [comment]
done in os4
