### ISSUE TITLE
UI: Enummeration doesn't disappear when I disable it

### ISSUE THREAD

**Issue by kaffeeringe** [OpenSlides/OpenSlides#5526]
**Describe the bug**
The agenda stays enummerated when I disable the enummeration.

**How to Reproduce**
Steps to reproduce the behavior: preferably on [nighty](https://nightly.demo.openslides.org)

1. Go to 'Agend'
2. Click on 'Settings'
3. Remove the check on enummeration 
4. When there was an enummeration before it doesn't diappear.

**Expected behavior**
It should disappear. There seems to be no way to really remove the enummeration

**System information**
https://spdsh.openslides.com

**Screenshots**
![Screenshot_2020-08-25 Tagesordnung - OpenSlides](https://user-images.githubusercontent.com/367592/91169902-64ff5180-e6d8-11ea-92c6-fd74d0051cc9.png)
See: Enummeration is diabled - you see the missing function in the menu. But there's still the TOP-enummeration in the agenda.

**Comment by tsiegleauq** [comment]
There is no automatic way to remove the enumeration from the agenda. The option in the settings page is not supposed to remove the agenda numbers from the current agenda, it is supposed to offer the possibility to update the current enumation by the given weight fields in the agenda.
Thus: this is not a bug report but a feature request.

You can manually alter the agenda number by clicking on the third table column, where the visibility indicator is.
![image](https://user-images.githubusercontent.com/10233032/91178036-de04a600-e6e4-11ea-93e4-da172ac14b23.png)

**Comment by kaffeeringe** [comment]
I won't argue ove th equestin whether it's a bug or a missing feature when I disable a feature and it won't disappear. :-D

**Comment by FinnStutzenstein** [comment]
The label might be misunderstanding and can be improved (@emanuelschuetze do you have a proposal?). The config is meant to disable the action of numbering items, so one can disable it to prevent others from renumbering the agenda. It is not meant to disable/hide the numbering in the actual agenda. This one would be a feature request. But the string `Enable numbering for agenda items` can really be interpred in both ways and should be clearer.

**Comment by kaffeeringe** [comment]
Shouldn't that be a matter of group permissions?

**Comment by tsiegleauq** [comment]
> Shouldn't that be a matter of group permissions?

It's also hidden by "can_anage_agenda". Using group permissions you can limit what your users might see and do, using the configuration pages you can limit what your administrators (and OpenSlides itself) are capable of altering and using. This feature is therefore meant to disallow administrators from (accidentally) altering the topic numbers automatically. Automatic numbering is absolutely destructive; when someone has a more manually and sophisticated style of numbering the agenda you may really want to avoid that.

**Comment by kaffeeringe** [comment]
Maybe it's also more of a question how TOPs are displayed. At the moment every bit on information in the agenda is equally important, because they are displayed in the same format. How about displaying "TOP 4.4.3.1" in grey?
