### ISSUE TITLE
case-sensitive usernames are irritating

### ISSUE THREAD

**Issue by kaffeeringe** [OpenSlides/OpenSlides#5528]
**Describe the bug**
Not really a bug: I experienced users having problems with case-sensitive usernames. I made them usernames like SVoss - so they recognize their names in them. But they seem not to be used to case-sensitive usernames. Moreover it might confuse users and admins if there are SVoss, sVoss, Svoss and they are all different users...

**Comment by jsangmeister** [comment]
will not change
