### ISSUE TITLE
Mail all invites

### ISSUE THREAD

**Issue by kaffeeringe** [OpenSlides/OpenSlides#5532]
**Is your feature request related to a problem? Please describe.**
When I want to invite users I have to send every mail manually.

**Describe the solution you'd like**
I'd like to be able to sent the invites to all or to certain groups.

**Comment by tsiegleauq** [comment]
you already can.

- use multiselection
- select all users you want to invite
  - you may filter by groups and hit "select all" before you do so
- click [ ... ] menu and hit "send invitation email"
![image](https://user-images.githubusercontent.com/10233032/91728038-d2145a80-eba2-11ea-9ec1-d82bd9d9348c.png)
