### ISSUE TITLE
Add possibility to store/gather Files elsewhere

### ISSUE THREAD

**Issue by Mannshoch** [OpenSlides/OpenSlides#5540]
**Is your feature request related to a problem? Please describe.**
We have to store Data we need for our Archive.
Upload new data and creating new data happens outside our Nextcloud

**Describe the solution you'd like**
Include the possibility to add another store for searching Data or saving/uploaded Data.
(Sorted by Priority)
- [ ] Add possibility to store data (may as Plugin)
  - [ ] WebDAV
  - [ ] Nextcloud
- [ ]  Add Possibility to search existing Files inside connected Data-stores
    - [ ] Create a Plugin to use OpenSlides inside Nextcloud

**Describe alternatives you've considered**
Upload files after you saved them as usual.

**Additional context**
Problem, If you use this tool more in a way as collaboration tool. People upload files which are not finale saved into the Data-store.
Also this kind of store allows selecting important Documents which have to be stored along the meeting-protocol.

**Comment by tsiegleauq** [comment]
I can hardly decipher your requirements. Apparently you wish to replace OpenSlides own data-blob-store with another service, i.e nextcloud.
@FinnStutzenstein @reiterl since you are taking care of the File Store in OS4 this might be interesting for you.

**Comment by Mannshoch** [comment]
If we use OpenSlides for our meeting as protocol, we need to store the meeting content in a way we could recover what we descided and in a way our particcipants could gatehr their data and jobs they have
