### ISSUE TITLE
Requirements to run OpenSlides on a server at home

### ISSUE THREAD

**Issue by InterestingIndeed** [OpenSlides/OpenSlides#5549]
Hey,

we are planning to use OpenSlides for a big online meeting. Because we don't have the necessary funding, I am trying to run OpenSlides on a computer/server from my home. I couldn't find any information about that endeavour anywhere else so I am trying to post my question here:

Is it possible to use my old pc as a server to run OpenSlides from home (8GB Ram, 500GB SSD, i5-3k, nVidia 1050)? 
If the hardware requirements are met, what do I have to consider when configuring the server (apart from the OpenSlides installation, which seems to be straight forward)? 
Would you recommend trying to use a home server for that (about 150 participants connecting at once) to someone who has a basic idea about ssh and installing stuff on computers and people to help who have an IT background (but no own servers)?

OR: Would you recommend renting out server capacity from somewhere else than OpenSlides directly (we want to you it for one day, so buying 3 months of OpenSlides would be a huge waste of money for us). 

If this is not the right place for my questions, could you please point me to a better place to ask them?

Best regards!

**Comment by tsiegleauq** [comment]
For individual support you might want to access the support tracker via support@openslides.com

> Is it possible to use my old pc as a server to run OpenSlides from home (8GB Ram, 500GB SSD, i5-3k, nVidia 1050)?

Technichally yes, thus said, the RAM *might* not be enough to serve 150 people at once. Especially electronic voting was apparently a heavier task. I'd also recommend to clean the history periodically (If you work with motions a lot), that might save you a lot of storage.

> If the hardware requirements are met, what do I have to consider when configuring the server (apart from the OpenSlides installation, which seems to be straight forward)

If you can, use the docker image. If you want to install OpenSlides manually using python, do not let your users access the Django development server, but proxy the OpenSlides server through nginx (or apache) and configure postgresql to replace sqlite. Needless to say, you have to have your port forwarding accordingly so users can reach your server over the internet. Besides that you should be good to go.

> Would you recommend trying to use a home server for that

The actual bottleneck will, most likely, be your upload bandwidth from your home server to the internet. Depending on your location, home internet connections have proven to be very limited in terms of upload bandwidth.

> OR: Would you recommend renting out server capacity from somewhere else than OpenSlides directly (we want to you it for one day, so buying 3 months of OpenSlides would be a huge waste of money for us).

That's comprehensible. In any case, using a dedicated server and not using your home internet will be the safer option.
