### ISSUE TITLE
Check projector field in models.txt

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#5557]
https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/models.txt#L738

@FinnStutzenstein Please check if there is a misstake here: agenda_item is in the list but not topic. I would have expected it exactly the other way (see all other objects that are related here).

The same with projection.

If you change models.txt please open an issue in backend repo.

**Comment by FinnStutzenstein** [comment]
Ah, both should be there. Topic is clearly missing. But you can also project agenda items.

There is a catch here: We have "special" items to project, like the complete agenda (currently done via a dummy-collection `agenda/item-list`) and the dummy collection `core/clock`. Putting these dummies into the database would work (the client and AUservice would not have problems), but for the backend it is dirty if even not possible, right?

I do have another solution (use the meeting for special things), but this is a later milestone. Currently it is just important to know, if you can support dummy collections or not...

**Comment by normanjaeckel** [comment]
I think dummy collections are not supported at the moment.
