### ISSUE TITLE
npm WARN deprecated request

### ISSUE THREAD

**Issue by depate** [OpenSlides/OpenSlides#5577]
**Describe the bug**

A warning shows up while bootstrapping the OpenSlide docker images.

**How to Reproduce**

1. Go to 'OpenSlides/docker'
2. './build.sh all'
3. See error:

```
Step 7/19 : RUN npm install -g @angular/cli@^10
 ---> Running in fb6dae780f73
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```

**Expected behavior**

**System information**

- OpenSlides-Version: 3.2

**Comment by tsiegleauq** [comment]
That's Angulars internals. Matters very little.

**Comment by depate** [comment]
Ok, I see. Thanks.
