### ISSUE TITLE
Voting results shows different percentages on projector and election view

### ISSUE THREAD

**Issue by fblaese** [OpenSlides/OpenSlides#5585]
**Describe the bug**
When using "per candidate" 100% bases, OpenSlides shows different percentages on projector and election view.
Percentages are evaluated as expected (per candidate) in projector view.
However the exported PDF and the results in the election overview show different percentages, which are not evaluated per candidate. Instead, all yes/no(/abstain) votes are used as 100% base.

Also, even in projector view, the percentages are not calculated correctly all the time: If a voter does not select any of the Yes/No/Abstain options for a candidate, the vote should be counted as abstain. However, it isn't displayed at all (see last candidate in screenshot), but is included in the 100% base.

**How to Reproduce**
1. Create election
2. Add new ballot
3. Voting type: nominal, Voting method: Yes/No(/Abstain) per candidate
4. Select any "per candidate" 100% base
5. Vote

**Expected behavior**
Both projector, election view and PDF export show the same percentages, which are evaluated per candidate.

**System information**

- OpenSlides-Version: 3.2
- Python Version: 3.7.3
- Device: Desktop
- OS: Linux
- Browser: Chromium
- Browser-Version: 85

![2020-09-29_21-26](https://user-images.githubusercontent.com/7596226/94606247-779e1500-029a-11eb-8b4a-b79702e886b5.png)

**Comment by FinnStutzenstein** [comment]
> However the exported PDF and the results in the election overview show different percentages, which are not evaluated per candidate. Instead, all yes/no(/abstain) votes are used as 100% base.

@tsiegleauq Can you check the usage of the 100%-base?

**Comment by tsiegleauq** [comment]
That one is odd.

**Comment by fblaese** [comment]
The merged patch fixes the discrepancy between voting and projector view.

However, the percentages are still broken:

When selecting "per candidate" 100% bases ("Yes/No per candidate" in this case), I thought that percentages are calculated per candidate. So with 1 voter and 4 candidates, every candidate vote should be 100%. But OpenSlides still calculates percentages with respect to total votes (3 yes/no votes in this case):
![2020-10-07_15-29](https://user-images.githubusercontent.com/7596226/95337334-07068200-08b2-11eb-81b1-4f8641fc9fa7.png)

So either the textual description does not reflect the intent of the developer or the calculation is still wrong..

**Comment by tsiegleauq** [comment]
They are correct. to all votes is your 100% base.

@emanuelschuetze
