### ISSUE TITLE
Move models.yml validator to another place (or not)

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#5586]
See #5572.

@ostcar @FinnStutzenstein It should be discussed what to do with the validator code.

**Comment by FinnStutzenstein** [comment]
With the issue here (https://github.com/OpenSlides/OpenSlides/pull/5587) when changing the schema, I now have a strong opinion that the validation code should live right next the the thing to validate. When the schema changes, the validation code can directly be updated, too.

**Comment by ostcar** [comment]
Lets talk about this at the next telco. One other solution would be to use a git submodule (I don't believe, that I am suggesting this 🙂 )

**Comment by jsangmeister** [comment]
What's the consensus here? I would agree with @FinnStutzenstein

**Comment by FinnStutzenstein** [comment]
Not talked about it yet. But yes, I would say, that this code should be here.

**Comment by FinnStutzenstein** [comment]
@ostcar Can you do this please. #5612 is another reason, we should directly be able to fix it while we are working on the format.

**Comment by ostcar** [comment]
I would say #5612 is a reason not to move the tool.

If it is in the same repo, the models.yml file and the validator can only be changed together. We would be forced to create pull requests where one developer changes the models.yml and I (or someone with how can write golang) changes the validator. This sounds mutch more complicated then changing the validator in a separate repo and only change the version number here.

**Comment by jsangmeister** [comment]
But it makes no difference for the workflow. Either I create a PR with changes to the `models.yml` and then you create a PR in the other repo with changes to the validator, or I create a PR and then you push your changes to the validator on top of that. Where you push your changes shouldn't matter for you. So, it makes no difference if change the validator, but it offers us the possibility to let one developer make all changes. 

Also, you don't need go skills for changes like in #5612. Also also, @FinnStutzenstein, @tsiegleauq and me will have a go crash course in the near future so hopefully our ability to change the validator ourselves will greatly increase.

**Comment by ostcar** [comment]
It it more complicated for me to create a commit on top of your pr, then create my own.

Of cause @FinnStutzenstein or @tsiegleauq can change the go code in the separate repo.

**Comment by FinnStutzenstein** [comment]
> It it more complicated for me to create a commit on top of your pr

this isn't what we want: we want to change the validation code by our own.

**Comment by ostcar** [comment]
Ok. Then the solution is, that you continue writing the validator.Then you can do it how you like and where you like.

Therefore I have one question. Do you want to continue writing the validator in golang or do you want to rewrite it in another language like python? If you want to write it in golang, then I would create a separat models-package with the code that can be shared between the validator and the autoupdate service. If you want to rewrite the validator in another language, then I would move the code to the autoupdate-repo

**Comment by FinnStutzenstein** [comment]
Go is fine
