### ISSUE TITLE
Rename some fields in the model.yml

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/OpenSlides#5590]
- `HTML` and `HTMLVideo` should be named `HTMLStrict` and `HTMLPermissive` as @normanjaeckel already suggested, since the point will most certainly come when we add tags to the permissive type and then the name doesn't fit
- `datetime` should be called `timestamp` since we save it as a timestamp

Feel free to add other suggestions here.

**Comment by FinnStutzenstein** [comment]
> float and decimal

In voting, we do not want floting point numbers, but ones with fixed precision. This must be considered while implementing (numbers as strings, decimal handling)

**Comment by jsangmeister** [comment]
Ah, yes, forgot about that. Deleting that
