### ISSUE TITLE
Autopilot shows List of speakers box when not permitted

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#5594]
Autopilot shows an empty List of speakers box when can_see_list_of_speakers is False.

![image](https://user-images.githubusercontent.com/20415092/94810753-bd6ef080-03f4-11eb-8d6f-8cf875c38c92.png)

The box should not appear.

**Comment by tsiegleauq** [comment]
It appears and is empty. Works as intended. To prevent heavy flickering, I am not hiding this box.
