### ISSUE TITLE
Display vote weight totals

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#5595]
If vote weight is activated vote weight totals should be calculated and displayed next to "total heads", e. g. admins need to see vote weights present when filtering by "is present".

![image](https://user-images.githubusercontent.com/20415092/94811342-86e5a580-03f5-11eb-9107-85ba9124a93a.png)

I consider this an important issue.

**Comment by tsiegleauq** [comment]
meh. The projectors PollData entries are strings instead of numbers.
