### ISSUE TITLE
OpenSlides behind Apache Reverse Proxy? (Loading data. Please wait ...)

### ISSUE THREAD

**Issue by corsch** [OpenSlides/OpenSlides#5596]
I'm new to OpenSlides and have an issue running OpenSlides (Docker-Compose) behind an Apache Reverse Proxy.

When logging into OpenSlides (https://slides.SITE.de) I just get "Loading data. Please wait ..."
But when I login to http://127.0.0.1:8000 via SSH-Tunneling I can login normally.
Unfortunately HAProxy or nginx are no option right now.

Does anyone host an OpenSlides instance behind a Apache Reverse Proxy and can give me a nudge?

**Comment by tsiegleauq** [comment]
I suppose that's more of an apache question than an OpenSlides issue. We have been using nginx so far, the configuration is documented in the docker files.

I leave this issue open for a while so you might get help from the community

**Comment by corsch** [comment]
Maybe I can adapt the configuration from nginx to apache.

Can you give me a nudge where I can find the configuration file?
Your old link, from a similar issue (https://github.com/OpenSlides/OpenSlides/issues/5469), from 2014 is broken.
(https://github.com/OpenSlides/openslides-docker-compose/blob/master/client/nginx.conf)

**Comment by son1x** [comment]
I have the same problem while using Apache2 and the ReverseProxy Function

**Comment by FinnStutzenstein** [comment]
This is mostly an issue with WebSockets (a working connection is required to close the spinner). At least Nginx needs a special config for WebSockets. I never used Apache, so I cannot help there.

**Comment by corsch** [comment]
I can cofirm that the issue is related to WebSockets in Apache Reverse Proxy.

I've tried the proxy_wstunnel module without success.
I'll update this "Issue" as soon as I have a working solution.

**Comment by JayVii** [comment]
Had a same issue, but I stumbled upon [this StackOverflow](https://stackoverflow.com/a/60475533) which presented the solution. My working Apache Config:

```
<VirtualHost *:443>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        ServerName "example.com"
        ServerAlias "slides.example.com"

        RewriteEngine On
        RewriteCond %{HTTP:Connection} Upgrade [NC]
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteRule /(.*) ws://0.0.0.0:8000/$1 [P,L]

        ProxyPreserveHost On
        ProxyPass        / http://0.0.0.0:8000/
        ProxyPassReverse / http://0.0.0.0:8000/
</VirtualHost>
```

**Comment by abeckDev** [comment]
I had the same issue like @JayVii and his Apache Config was very helpful.
However, I also needed to enable the ```mod_proxy_wstunnel```.

So if the config above won't work for you check if enabling the following modules might be helpful for you as well: 

```bash
sudo a2enmod proxy
sudo a2enmod proxy_balancer
sudo a2enmod proxy_http
a2enmod proxy_wstunnel
```

**Comment by FinnStutzenstein** [comment]
@corsch Does it work fow you? Can the issue be closed?

**Comment by ditschi** [comment]
Had the same issue. the solution by @JayVii  worked for me as well.

**Comment by corsch** [comment]
Sorry for the late answer, I'll check on this weekend if it is also working for me.

**Comment by thommierother** [comment]
I am trying openslides 3.3 with haproxy as ssl accelerator and apache2 as reverse proxy on the openslides app server, using the apache config from 

https://github.com/OpenSlides/OpenSlides/issues/5596#issuecomment-729940572

but without success yet. I see code 500 errors for all websocket requests on ressource /ws/ and thus an endless spinner in the UI. Any idea how to fix this? 

The required proxy mods are all installed here, as recommended earlier (proxy_http, proxy_wstunnel).

Thx, Thommie

**Comment by jsangmeister** [comment]
OpenSlides3 is no longer maintained.
