### ISSUE TITLE
Projector does not handle special entries -1, -2 for analog vote

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#5597]
Projector displays:
![image](https://user-images.githubusercontent.com/20415092/94816285-e21a9680-03fb-11eb-96e8-a780b1fc8688.png)
instead of:
![image](https://user-images.githubusercontent.com/20415092/94816380-04141900-03fc-11eb-8faf-cfa990c895db.png)

**Comment by tsiegleauq** [comment]
meh. The projectors PollData entries are strings instead of numbers.

**Comment by FinnStutzenstein** [comment]
> The projectors PollData entries are strings instead of numbers.

Do they come from the server? If so, we should fix it there
