### ISSUE TITLE
Error when creating a user

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#5601]
**Describe the bug**

I get a `<ngx-mat-select-search> must be placed inside a <mat-option> element` in the console, when opening the user create form.

**How to Reproduce**
1. Go to /users/new

Note that I used a prod build from the current master. I do not know, if this happens in dev.

**Expected behavior**
No error.

**Additional context**
I guess this comes from the search-value-selector for groups, but I do not know for sure.

**Comment by tsiegleauq** [comment]
this is due to an update in ngx-mat-select-search, not limited to users. Happens all the time, bit is nothing critical.
