### ISSUE TITLE
Add management scripts

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#5606]
after changes in #5605 to:

- [ ] (un)set `is_demo_user` for a user given by id
- [ ] (un)set `jitsi_domain`, `jitsi_room_name`, `jitsi_room_password` for a meeting given by id
- [ ] (un)set `enable_electronic_voting`

Use python or bash only.

TODO: direct datastore access isn't good for migrations. I prefer actions here -> We need protected actions. @jsangmeister We should talk first about migrations.

**Comment by jsangmeister** [comment]
> We need protected actions

I already implemented it in https://github.com/OpenSlides/openslides-backend/pull/176/ (called `internal` actions), since e.g. the list of speakers has to be created, which is easier with an action.

**Comment by FinnStutzenstein** [comment]
Ok, so there is a "helper" action. How is it called? How do you protect internal actions that they are not called via `/system/action/handle_request`?

**Comment by jsangmeister** [comment]
> How is it called?

I just implement the possibility to have internal actions for now. The specific actions still have to be implemented. If you already have specifics in mind, feel free to create an issue.

> How do you protect internal actions that they are not called via `/system/action/handle_request`?

The `actions_map` maps all action names to their classes. When looking up the name, I just check if the internal flag is set.

**Comment by FinnStutzenstein** [comment]
With the routing setup in general, you can handle internal actions when the url `/internal/action/handle_request` is used, so you have to check, which route is used, and if the action is internal and the internal route is used, it is ok. With this mechanism, we expose internal actions to our internal infrastructure, e.g. for managing scripts. But this is controlled: You can define partial-internal-actions or whatsoever (actions, that should never be called stand-alone), even if they are internally exposed.

**Comment by jsangmeister** [comment]
Currently, all requests in the backend arrive at `/` (at least internally). See for example all tests or https://github.com/OpenSlides/openslides-backend/blob/68f1d80de632dd7a9a9ae0b662020182384e950a/openslides_backend/http/application.py#L46, where the route is checked against `/health`.

**Comment by jsangmeister** [comment]
> Scripts and code can use actions that are not registered to the action_map so I think we do not need an extra routing.

Not if these scripts are running outside of the backend and commuincate with it by sending normal HTTP-Requests

**Comment by FinnStutzenstein** [comment]
> Not if these scripts are running outside of the backend and commuincate with it by sending normal HTTP-Requests

Exactly, this will be the way to go: These scrips are used for managing running instances. HTTP requests to trigger managements things is good since it is tool-independent. This does not mean, that these scripts should not be present in the backend, but if so, we need an extra way to execute them. Including them in the nromal routing, this step is unified.

**Comment by normanjaeckel** [comment]
Why not just use a special header? A route or path does not look like to be intended for such things ...

**Comment by FinnStutzenstein** [comment]
> A route or path does not look like to be intended for such things ...

Our complete internal-route protection sets up on this. I do not want to maintain two seperate ways of handling internal stuff. Regarding the header: It can be set from outside. If you want to have it a secret, it has to be maintained. If the haproxy should not forward this header it has to be maintained.

**Comment by FinnStutzenstein** [comment]
I main the auth service and DS uses this routing difference. It is not hard to implement...
