### ISSUE TITLE
Autopilot displays Clock panel

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#5611]
If the projector has the clock enabled Autopilot displays **Clock** in the top panel and does not update the panel to reflect the currently selected projector element:

![image](https://user-images.githubusercontent.com/20415092/95173134-93347e80-07b8-11eb-9f00-66f2e16959f5.png)

**Comment by jwinzer** [comment]
MORE: The top panel does not auto-update when projector content changes. It requires a browser refresh.

**Comment by FinnStutzenstein** [comment]
@tsiegleauq Maybe we should exclude projector elements with "stable=True" (clock, CLOS, CLOS-Chyron, ..)

**Comment by tsiegleauq** [comment]
cosed by #5617
