### ISSUE TITLE
Add "can_see_vote_weight" permission

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#5616]
User list view must only show vote weight if permission "Can manage users" is given. The user detail view already behaves this way.

**Comment by tsiegleauq** [comment]
is that simply cosmetic or a real secret that the users should not know of?

**Comment by jwinzer** [comment]
In general a user is not permitted to know the vote weight of other users. An example is an owners community (Eigentümergemeinschaft).

**Comment by normanjaeckel** [comment]
I think in apartment owners communities according to German law every member is allowed to know the number of votes or the vote weight of all other members. Otherwise he cannot control whether a motion is applied or not ... ;-) @emanuelschuetze ?

**Comment by jwinzer** [comment]
Hi Norman, you might be right but I know of other assemblies where vote weights are kept secret.

**Comment by tsiegleauq** [comment]
Good points. We might address them all by making a new permission: "can_see_vote_weight"

**Comment by jwinzer** [comment]
Alright. Just keep in mind that a user must be able to see his own vote weight independent of can_see_vote_weight.

**Comment by FinnStutzenstein** [comment]
> Alright. Just keep in mind that a user must be able to see his own vote weight independent of can_see_vote_weight.

This should already work currently.
