### ISSUE TITLE
Cannot see if I've successfully received vote delegations before a vote.

### ISSUE THREAD

**Issue by bernhardreiter** [OpenSlides/OpenSlides#5623]
Being logged in as a user (Group Delegates), how can I see which other users I do present
before an actual vote starts?

#### How to reproduce
 * As admin delegate a few votes to a user U
 * Log in as user U
 * Got to "Show profile". Observation: There is no indication of which voting rights I've currently got.
(Also found no other place where it is shown, unless a vote is in progress.)

#### Expected behavior
Would expect the information as part of the "Show profile" information page.

#### System Information

- OpenSlides-Version: OpenSlides 3.3-master-20201008  (as running on demo.openslides.org)

**Comment by tsiegleauq** [comment]
currently, the `can_manage` permission is required to see all kinds of vote delegations in the users detail view, the `ownpage` property was not used. That's a bug indeed.
