### ISSUE TITLE
SAML settings SP values

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#5624]
SP values need to be updated to

        "entityId": "https://sp.domain.xyz/apps/saml/metadata/",

        "assertionConsumerService": {
            "url": "https://sp.domain.xyz/apps/saml/?acs",

        "singleLogoutService": {
            "url": "https://sp.domain.xyz/apps/saml/?sls",

https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/saml/saml_settings.json.tpl#L5

**Comment by FinnStutzenstein** [comment]
Ok, can you create a PR?
