### ISSUE TITLE
Alignment of a description cannot be justified

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/OpenSlides#5631]
**Describe the bug**
Text in the description of motions, assignments and topics cannot be aligned as justification.
It works if the line numbering of motions is set to "within" or "off".
The various HTML elements have the property "text-align: justify".

**How to Reproduce**
Steps to reproduce the behavior: preferably on [nighty](https://nightly.demo.openslides.org)

1. Go to 'motions'
2. Click on one motion or create a new one.
3. Edit a motion so, that its description extends over several lines.
4. Then mark that description and click on "Absatz" -> "Ausrichtung" -> "Blocksatz".

**Expected behavior**
The alignment of the description should be justified.

**System information**
- OpenSlides-Version: 3,3
- Device: Lenovo ThinkPad E585
- OS: Linux Arch
- Browser: Chrome
- Browser-Version: 86

**Comment by tsiegleauq** [comment]
That's ~~probably~~ due to the fixed line length. Not entirely sure if this behavior is worth fixing, since strict line numbers and justified alignment seem kind of contradictory.
@CatoTH what is your opinion in this one?

**Comment by CatoTH** [comment]
Sorry for the late response.
Technically, it would be possible if aligning the block did not only use the CSS property "text-align: justify;", but also "text-align-last: justify;". However, the downside of it would be that the last line of each paragraph would be forcefully justified, too, which would look really awkward for mort paragraph. So technically it would be possible to do that, but aesthetically, I have a hard time imagining it would be a preferable solution...

**Comment by emanuelschuetze** [comment]
won't fix - for motion text
