### ISSUE TITLE
bulk_alter_groups not working with SAML Users

### ISSUE THREAD

**Issue by ManniLoe** [OpenSlides/OpenSlides#5640]
**Describe the bug**
In an installation (docker setup according to readme) with enabled **SAML** authentication, the bulk altering of Users, especially adding / removing groups to multiple users ist not working.

**_Example:_**
(can be reproduced on multiple instances)
Creating an internal User additionally to the existing SAML users.
UserId 55 is an SAML-User
UserId 124 is an internal User
Request-Body Api-Call _/rest/users/user/bulk_alter_groups/_ 
`{"user_ids":[124,55],"action":"add","group_ids":[11]}`

**_Result:_**
internal Users 124 is added to an group (id 11), SAML User 55 has no aditional group.

No error is shown.

**How to Reproduce**
Steps to reproduce the behavior: preferably on [nighty](https://nightly.demo.openslides.org)

1. Having SAML enabled
2. Having at least one SAML User logged in
3. Create a new internal User
4. Click on 'bulk edit'
2. Select one internal and on saml User
3. Click on 'add / remove groups', choose on, add the group
4. See groups of the users

**Expected behavior**
Bulk adding / removing of groups is working with all user.

**System information**

- OpenSlides-Version: 3.2 / master
- Python Version: 3.8
- Browser: chrome / firefox

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze We explicitly excluded SAML users form these bulk actions. Whats your opinion here?

**Comment by tsiegleauq** [comment]
Was there a reason why we do so?

**Comment by ManniLoe** [comment]
In my opinion, SMAL users should not be excluded here. The leading system for group assignment should be OpenSlides.

If there was a reason for this, would a parameter in the system settings be interesting?

**Comment by emanuelschuetze** [comment]
> In my opinion, SAML users should not be excluded here. 

+1 (I see no reason to exclude SAML users.)
