### ISSUE TITLE
Empty material dialogue after submitting a vote via auto pilot view

### ISSUE THREAD

**Issue by elanfer** [OpenSlides/OpenSlides#5653]
**Describe the bug**
When a vote is started and users try to vote via the autopilot an empty material dialogue appears (see screenshot). Normally it should ask for if the user really wants to submit the vote. This only happens in autopilot view. In motion detail the dialogue is filled with the correct content.

**How to Reproduce**
(following)

**Expected behavior**
Material dialogue that asks if the vote should really be submitted.

**System information**

- OpenSlides-Version: OpenSlides 3.3-master-20201008 
- Platform: OpenSlides Hosting
- Browser: Chrome

**Screenshots**
![photo_2020-10-25_15-30-44](https://user-images.githubusercontent.com/6481985/97110090-87f9b200-16d7-11eb-8aa3-7c3d632eb2bf.jpg)

**Comment by tsiegleauq** [comment]
Cannot reproduce using the default delegate settings in a fresh OpenSlides database.
Are there any more information about how to reproduce this behavior?

![image](https://user-images.githubusercontent.com/10233032/97874477-54430b80-1d19-11eb-8a43-f78e427ac1c1.png)

**Comment by elanfer** [comment]
Sadly I do not have any further information except that like in #5660 there was a broken relation in the motions set, perhaps that caused this behaviour?

**Comment by tsiegleauq** [comment]
not reproducible; closed due to inactivity
