### ISSUE TITLE
LiveStream/Jitsi only visible for Admins - Permission-Problem!

### ISSUE THREAD

**Issue by rabauss** [OpenSlides/OpenSlides#5661]
**Describe the bug**
On a new docker swarm (yesterday built) only admins can see the livestream toolbar + jitsi integration.
Switching the group to delegates, staff or committees immediately hides the toolbar!

**How to Reproduce**
1. Login as admin on https://nightly.demo.openslides.org
2. Set a live stream url e.g. https://ardevent2.akamaized.net/hls/live/681512/ardevent2_geo/master.m3u8
3. Switch to a non admin user (a:a)
4. You won't see the bottom toolbar

**Expected behavior**
The live stream toolbar should be visible for all users if you've set the streaming url - this is given in the official demo!

I guess there are some wrong permissions in the clean database. But insertion of `can_see_livestream` in table `auth_group_permissions` for the non admin groups did not change the behavior. Maybe you have to do some cache clear? Unfortunately I'm not familiar with the permission construct!

**System information**
- OpenSlides-Version: 3.2 - commit: 5502e5337a9a0fe88416668d4383ebc2c39a7920
- Python Version: -- Docker Swarm --
- Device: all
- OS: all
- Browser: chrome + firefox

**Comment by tsiegleauq** [comment]
Cannot reproduce. Works fine and as intended. This is either a docker exclusive issue or an issue with your setup.
Ensure that your users have the live stream permission. You can run OpenSlides without cache by using the "new private window" feature of your browser.
New databases will have the live stream permission disabled by default which is correct.

![image](https://user-images.githubusercontent.com/10233032/97863716-b5fa7a00-1d07-11eb-8478-40e83d6a8b36.png)

**Comment by rabauss** [comment]
Okay, I see - now it's no longer reproducible in the nightly - I'll give you feedback after testing my docker setup with the current version!

**Comment by rabauss** [comment]
I'm sorry for this issue - I did not find the group settings in my first test of openslides.
It's quite good hidden in the submenu - not so intuitive :-/

Of course it's all working fine with the livestream url, if you have set the permissions correctly
