### ISSUE TITLE
forgotten password

### ISSUE THREAD

**Issue by manuelw99** [OpenSlides/OpenSlides#5663]
**Describe the bug**
Text in forgotten password mail is wrong. URL ist 127.0.0.1:8000 not my real domain. When I send the username and the initial passwort, everything is right. (System-URL is settet in the participants-setting)

**System information**

- OpenSlides-Version: 3.3

**Screenshots**
![image](https://user-images.githubusercontent.com/57299417/97725667-bd830e80-1ace-11eb-8784-fd54698f87ea.png)

**Comment by jsangmeister** [comment]
Should work now in OS4
