### ISSUE TITLE
Assignment view does not update when clicking banner link

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#5664]
If an assignment page is displayed, e.g. /assignments/1 with a banner link pointing to /assignments/2 clicking the link will not update assignment details.

Adding this code to [https://github.com/OpenSlides/OpenSlides/blob/master/client/src/app/site/assignments/components/assignment-detail/assignment-detail.component.ts](url) seems to fix the problem:

```
    private navigationSubscription: Subscription;

    public ngOnInit(): void {
        this.observeRoute();

    public ngOnDestroy(): void {
        if (this.navigationSubscription) {
            this.navigationSubscription.unsubscribe();
        }
        super.ngOnDestroy();
    }

    public observeRoute(): void {
        this.navigationSubscription = this.router.events.subscribe(navEvent => {
            if (navEvent instanceof NavigationEnd) {
                this.cleanSubjects();
                this.getAssignmentByUrl();
            }
        });
    }
```

**Comment by FinnStutzenstein** [comment]
@tsiegleauq I think it is not low, since we alsready got another report for it: #5667

**Comment by FinnStutzenstein** [comment]
@jwinzer Can you create a PR for this issue?
