### ISSUE TITLE
File / Image permissions not applied correctly

### ISSUE THREAD

**Issue by f-fritz** [OpenSlides/OpenSlides#5665]
**Describe the bug**
"Can see the list of files" does not only toggle visibility of the "Files" menu but also impacts the ability to access the file at all. Without setting the "Can see the list of files" permission for a group the members are not able to access the file (via URL, e.g. when embedded on a slide) even though the file's access group would allow the user to access the file.

Edit: this may not be bug but is not very intuitive at least

**How to Reproduce**

1. Disable the "Can see the list of files" option in Participants > Groups > Files for a group of restricted users
2. Upload an image
3. Set the group access to the restricted user group or leave empty
4. Reference/embed this image in a topic or on the "Home" page
5. (It is correctly displayed when logged in as the admin - but inaccessible as any other user)
6. Enable the "Can see the list of files" option in Participants > Groups > Files
7. Images are now accessible - but the "Files" menu is now visible as well.

**Expected behavior**
As you could hide specific files by setting the access groups respectively I would rather expect the "Can see the list of files" permission to show or hide the "Files" menu without having an effect on file accessibility by URL. So that I am still able to access all files with respective access groups even when the "Files" menu is hidden as I'd like to reduce the amount available Menus for participants as much as possible.

**System information**

- OpenSlides-Version: 3.3
- Additional version information (if any): 7277a1bb01f02239a3b9a7cfa3aab61460940b22
- Server OS: Ubuntu server 20.04.1 LTS
- Docker version 19.03.13, build 4484c46d9d, docker-compose version 1.27.4, build 40524192
- Client Device: Mac Pro macOS 11.0 public beta, iPhone XS iOS 14.2 public beta
- Browser: Safari 14.0.1, Chrome 86.0.4240.111, Firefox 81.0.1, iOS Mobile Safari

**Additional context**
Add any other information to comprehend your problem

**Screenshots**

<img width="1616" alt="Screenshot 2020-11-01 at 14 02 47" src="https://user-images.githubusercontent.com/46245228/97803705-62c2f180-1c4b-11eb-93fd-53859c4112ac.png">

**Comment by jsangmeister** [comment]
Should be fixed in OS4.
