### ISSUE TITLE
Special characters not rendered in PDF

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#5693]
Certain special characters are not rendered in a pdf generated by OpenSlides.

Motion text:
![image](https://user-images.githubusercontent.com/20415092/98654695-eca34680-233e-11eb-9bf9-eca851f83a18.png)
PDF:
![image](https://user-images.githubusercontent.com/20415092/98654760-017fda00-233f-11eb-993f-c84f853a0863.png)

I assume the reason is that pdfmake uses Roboto font, which does not support Unicode characters.

**Comment by tsiegleauq** [comment]
This means that either, pdfmake does not support this characters (unlikely)
or the used pdf-font does not have have the characters included.

Try setting another font using mediafiles.

**Comment by emanuelschuetze** [comment]
should be done in os4
