### ISSUE TITLE
Bulk Presence Setting for SAML Users

### ISSUE THREAD

**Issue by mopication** [OpenSlides/OpenSlides#5715]
**Describe the bug**
I'm unable to edit presence for SAML Users if I select all users at once (Multiselect->Select all->Set presence)
I can only edit the presence for non SAML-Users

**How to Reproduce**
Steps to reproduce the behavior: preferably on [nighty](https://nightly.demo.openslides.org)

Have multiple users, some of them as SAML-Users (for synchronisation with zoom) some of them as non-saml-users

1. Go to 'Participants'
2. Click on 'three dots'
3. Click on 'Multiselect'
4. Click on 'Select all'
5. Click on 'Set presence'
6. Click on either of the presence-settings
7. Only non-SAML Users have the selected presence setting

**Expected behavior**
Every users presence should have the selected setting now

**System information**

- OpenSlides-Version: [3.2]
- Additional version information (if any): [not known]
- Python Version: [not known]
- Device: [PC]
- OS: [Windows 10]
- Browser: [firefox]
- Browser-Version: [e.g. 22]

**Additional context**
Unfortunatley i don't know any more info, as i'm not the one hosting the installation

**Screenshots**
N/A

**Comment by FinnStutzenstein** [comment]
Fixed in the current master
