### ISSUE TITLE
Help:  "New Ballot" doesn't work

### ISSUE THREAD

**Issue by BerberBerthold** [OpenSlides/OpenSlides#5716]
Hey I have your docker running for OpenSlides.  I followed your instructions in your readme.

Whenever I say "New Ballot", no new ballot is created.  I first thought it had to do with my nginx configuration and the different locations I have to reverse proxy or something, but I tried it directly from the server and it still didn't work.  What could the problem be?  Am I doing something wrong from inside OpenSlides?  I didn't change any settings.

**Comment by FinnStutzenstein** [comment]
Do you get an error, if you open the developer console (F12 for chromium and firefox)?

**Comment by BerberBerthold** [comment]
Yes!  You are right.  Sorry, I am not too experienced in troubleshooting, I should have tried this, though.

```ERROR Error: Uncaught (in promise): Error: Electronic voting is disabled. Only analog polls are allowed```

is what I get.  What is an analog poll?  How do I enable electronic voting?

Thanks for your help!

**Comment by BerberBerthold** [comment]
Ok I think I found my solution here.
https://github.com/OpenSlides/OpenSlides/blob/master/server/SETTINGS.rst

I need to edit the `.env` file.

**Comment by BerberBerthold** [comment]
I can't seem to get it to work, I am missing something.

Working directory is `docker/`.
I have the line `ENABLE_ELECTRONIC_VOTING=True` in my `.env` file.
Then I ran `( set -a; source .env; m4 docker-stack.yml.m4 ) > docker-stack.yml`
Then I ran `./build.sh all`.

I still get the same error in the developer console.  Electronic Voting is still disabled.  What did I miss?

**Comment by FinnStutzenstein** [comment]
Modifying the `.env` is correct and rebuilding the `docker.-stack.yml`, too. At least, if you do a docker swarm deployment. If you are using docker ocmpose, this is the wrong file. Rebuilding is not necessary, so I assume, that you did not stop, *remove* and restart all server containers since the variables are only read on startup.
