### ISSUE TITLE
Multiple OpenSlides Instances on one docker host

### ISSUE THREAD

**Issue by MichaelZiegler** [OpenSlides/OpenSlides#5737]
Hi,
i am trying to install multiple OpenSlides instances on one docker host, that should be running at the same time.
As reverse proxy I am using that one: https://hub.docker.com/r/jwilder/nginx-proxy.
I cloned the OpenSlides docker directory and changed the URLs in the docker compose file. Also I tried to use different docker networks for the different instances. When I execute "docker-compose up" the first instance is starting and working without any problems. When I now try to start the next instance, "docker-compose up" is also working, but I cannot login the second instance. If I shut down the first one via "docker-compose down" and then start the second one, this instance is working. But I didn't succeeded in running two instances at the same time.
Has anyone any solution for this problem? Thanks!

**Comment by FinnStutzenstein** [comment]
I suspect that docker compose uses equal container names and gets confused by this. The container names are put together by the foldername the `docker-compose.yml` is in and the name in the `docker-compose.yml`. Try to name the folders where the `docker-compose.yml` lies in differently. Another thing: The setup in the docker-compose repo is obsolete. You can use the current master *of this repo* since it has a nicer docker setup and does not involve a secondary repository.

**Comment by MichaelZiegler** [comment]
> 
> 
> I suspect that docker compose uses equal container names and gets confused by this. The container names are put together by the foldername the `docker-compose.yml` is in and the name in the `docker-compose.yml`. Try to name the folders where the `docker-compose.yml` lies in differently. Another thing: The setup in the docker-compose repo is obsolete. You can use the current master _of this repo_ since it has a nicer docker setup and does not involve a secondary repository.

**Comment by MichaelZiegler** [comment]
I also had the idea to change the foldernames. So I tried already folders like "OpenSlidesEvent1/docker_event1" and "OpenSlidesEvent2/docker_event2", but that wasn't the solution. The containernames are so different, but the problem consists.

**Comment by ManniLoe** [comment]
I'm also guessing that there is a problem with duplicate container names.

I have two instances of slides running on the same Docker host without any problems.
However, I set the docker-compose option "project-name" for each of the instances.
Try it at instance 1: `docker-compose -p os1 up --build -d`
and for instance 2: `docker-compose -p os2 up --build -d`
(-p => Specify an alternate project name (default: directory name))

**Comment by MichaelZiegler** [comment]
> 
> 
> I'm also guessing that there is a problem with duplicate container names.
> 
> I have two instances of slides running on the same Docker host without any problems.
> However, I set the docker-compose option "project-name" for each of the instances.
> Try it at instance 1: `docker-compose -p os1 up --build -d`
> and for instance 2: `docker-compose -p os2 up --build -d`
> (-p => Specify an alternate project name (default: directory name))

Unfortunatly that's not the solution. I tried explicit projectnames (the docker-folders got different names earlier), but that seems not be the solution for my problem.
Generally it is no problem to start instance 2 and instance 3, but when they are up, most of the time I cannot log into the instance. Sometimes it is working for some minutes, but wenn I try later, I don't get access to the instance. Sometimes I can see the welcome screen while the loading-sign is rotating, but after some seconds I'm back on the login-page
At the same time instance 1 is working without any problem. 

Has anybody of you some more ideas that could help me?
Thank you very much!

**Comment by FinnStutzenstein** [comment]
I recently had problems where I shared one (database) volume across multiple postgres containers, since postgres does not want to share it's data in parallel. Which settings do vou have for your database, especially the volumes?

**Comment by jsangmeister** [comment]
outdated
