### ISSUE TITLE
Error during server setup ERROR: connection to database failed: Temporary failure in name resolution

### ISSUE THREAD

**Issue by theimperior** [OpenSlides/OpenSlides#5740]
**Describe the bug**
When starting the containers with docker-compose up, the inital setup of the postgres cluster cannot resolve a hostname. The pgnode tries to setup a primary node and fails in name resolution of pgnode1. It finally exits with code 1. 

> pgnode1_1         | INFO: Begin cluster setup
pgnode1_1         | INFO: Configuring repmgr (/etc/repmgr.conf).
pgnode1_1         | INFO: Creating Postgres cluster's pg_hba.conf.
pgnode1_1         | '/var/lib/postgresql/pg_hba.conf' -> '/etc/postgresql/11/main/pg_hba.conf'
pgnode1_1         | INFO: The current primary node is unknown.
pgnode1_1         | INFO: Configuring cluster as primary node according to configuration.
pgnode1_1         | INFO: Generating /var/lib/postgresql/.ssh/ssh_host_ed25519_key.
pgnode1_1         | INFO: Generating /var/lib/postgresql/.ssh/id_ed25519.
pgnode1_1         | INFO: Generating /var/lib/postgresql/.ssh/id_ed25519_pgproxy.
pgnode1_1         | INFO: Setting up SSH keys and config for localhost.
pgnode1_1         | INFO: Configuring cluster.
pgnode1_1         | ALTER SYSTEM
[...]
pgnode1_1         | ALTER SYSTEM
pgnode1_1         | INFO: Enabling WAL archiving.
pgnode1_1         | ALTER SYSTEM
pgnode1_1         | ALTER SYSTEM
pgnode1_1         | INFO: Begin repmgr setup.
pgnode1_1         | WARNING: following problems with command line parameters detected:
pgnode1_1         |   database connection parameters not required when executing PRIMARY REGISTER
pgnode1_1         | INFO: connecting to primary database...
pgnode1_1         | ERROR: connection to database failed:
pgnode1_1         |   could not translate host name "pgnode1" to address: Temporary failure in name resolution
pgnode1_1         |
pgnode1_1         | DETAIL: attempted to connect using:
pgnode1_1         |   user=repmgr connect_timeout=2 dbname=repmgr host=pgnode1 fallback_application_name=repmgr

Therefore setting up the whole system is stuck in a loop with:

> media_1           | db:5432 - no response
media_1           | Waiting for Postgres server 'db' to become available...
server-setup_1    | db:5432 - no response
server-setup_1    | Waiting for Postgres cluster to become available...

**How to Reproduce**
I followed the installation instructions for the dockerized setup of OpenSlides step by step. (https://github.com/OpenSlides/OpenSlides).
I did not modify any configuration files other than those from the instructions. 

**Expected behavior**
Successfull startup of all docker services.

**System information**
- V-Server
- Ubuntu 18.04.5 LTS‬
- Docker version 19.03.13, build 4484c46
- docker-compose version 1.17.1, build unknown
- managed with Plesk Obsidian 18.0.31 Update Nr. 2

I attached the full output during the startup of the container and also my docker-compose.yml file. 

Hopefully I gave enough information for some help, feel free to ask for more! I'm familiar with docker, less with docker-compose and quite new to postgres and cluster setups with repmgr. 
Am I missing something here? Do I need a running postgres server on the docker host? I really appreciate any help!

(Sidenote: I would welcome the possibility to use a existing MySQL database on the host. My Plesk License did not support Postgres, thus I tried to make openslides talk to the existing database without success. I had to upgrade my License now as we have an upcoming event.)

[docker-compose.yml.txt](https://github.com/OpenSlides/OpenSlides/files/5621784/docker-compose.yml.txt)

[docker-compose.log](https://github.com/OpenSlides/OpenSlides/files/5621782/docker-compose.log)

**Comment by gsiv** [comment]
I'm afraid, I cannot reproduce the problem.

> > pgnode1_1         |   could not translate host name "pgnode1" to address: Temporary failure in name resolution

Here you have a service, `pgnode1`, that cannot even resolve its own hostname.  I doubt this problem is related to the OpenSlides configuration.

> I attached the full output during the startup of the container and also my docker-compose.yml file.

The log you provided is, unfortunately, not from a fresh start because it does not include the network and volume setup.  However, the virtual networks are, of course, a possible cause for your problem.

I recommend that you first fully bring down the stack, removing the networks: `docker-compose down`.  Afterwards, you can start anew.

To simplify debugging, you can specifically start the required service: `docker-compose up pgnode1`.  You should see the networks being recreated.  If pgnode1's setup succeeds you can stop it and start all services at once: `docker-compose up`.

If it still won't work, hopefully we will at least get more interesting logs out of it.  You are going to want to check your syslog at that point.

> **System information**
>     * docker-compose version 1.17.1, build unknown

I don't suspect any of the mentioned software versions to be a problem but, for your information, the current version of docker-compose is 1.27.4.

**Comment by theimperior** [comment]
Thanks for the quick reply! It seems that I found the reason why it is not working. My server is hosted with Strato and they officially don't support docker: 
https://www.strato.de/faq/server/welche-server-und-betriebssysteme-bei-strato-sind-docker-ready/
The problem ist not very obvious as I have two more containers running without any problems.

**Comment by jmeyerdo** [comment]
It seems I have the same error. I tried your suggestion docker-compose up pgnode1.
Output is the same as from docker logs: No error but an exit:
`Starting docker_pgnode1_1 ... done
Attaching to docker_pgnode1_1
pgnode1_1       | INFO: Begin cluster setup
pgnode1_1       | INFO: Configuring repmgr (/etc/repmgr.conf).
pgnode1_1       | INFO: Creating Postgres cluster's pg_hba.conf.
pgnode1_1       | '/var/lib/postgresql/pg_hba.conf' -> '/etc/postgresql/11/main/pg_hba.conf'
pgnode1_1       | INFO: The current primary node is unknown.
pgnode1_1       | INFO: Configuring cluster as primary node according to configuration.
pgnode1_1       | INFO: Generating /var/lib/postgresql/.ssh/ssh_host_ed25519_key.
docker_pgnode1_1 exited with code 0
`
Any ideas how to further debug this?
BR, Jens

**Comment by gsiv** [comment]
> It seems I have the same error.

Maybe it has been too long since I have looked at this issue but I it doesn't look like the same problem to me at all.

> Any ideas how to further debug this?

Try investigating the exited container's status with `docker inspect`.

**Comment by rasos** [comment]
Having the same issue after a fresh build of all dockers. 

If I run `docker-compose up pgnode1` all seems fine. When firing up all dockers, I get:

```
pgbouncer_1     | Fetching /var/lib/postgresql/.ssh/id_ed25519.pub from database...
pgbouncer_1     | Fetching /var/lib/postgresql/.ssh/known_hosts from database...
pgbouncer_1     | Trying all configured nodes (pgnode1)...
pgbouncer_1     | Warning: Permanently added the ED25519 host key for IP address '172.19.0.2' to the list of known hosts.
pgnode1_1       | 2021-04-10 20:06:41,626 INFO reaped unknown pid 285
pgnode1_1       | 2021-04-10 20:06:41,626 INFO reaped unknown pid 285
pgbouncer_1     | ERROR: Failed to find primary node.  Pausing all connections.
server-setup_1  | pgbouncer:5432 - no response
server-setup_1  | Waiting for Postgres cluster to become available...
```
`docker inspect docker_pgnode1_1` says when started alone or with all other dockers:

       "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 32562,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-04-10T20:11:43.92112327Z",
            "FinishedAt": "2021-04-10T20:06:56.979170964Z"
        },

**Comment by gsiv** [comment]
> Having the same issue after a fresh build of all dockers.

You _also_ don't have the same issue at all.  At least, I don't see `could not translate host name "pgnode1" to address: Temporary failure in name resolution` in your logs.

That is not to say that you didn't encounter a bug but please open a new issue.  And when you do, please include more output from `pgnode1`'s and `pgbouncer`'s startup procedures as well as `docker inspect` output for both services.
