### ISSUE TITLE
Add descriptions for additional information in the models.yml

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#5743]
All the properties below are not ducomented. It is not clear, what they do:

- read_only
- default
- required
- maxLength (should be max_length...)
- description
- enum
- minimum
- equal_fields

@normanjaeckel Since you have introduced the models.yml and some of these attributes. Please add documentation on top of the file. It is not clear what some of them do: https://github.com/OpenSlides/OpenSlides/pull/5728#issuecomment-734775738

**Comment by FinnStutzenstein** [comment]
@normanjaeckel ping..

**Comment by normanjaeckel** [comment]
See #5794

**Comment by normanjaeckel** [comment]
`maxLength` should stay as is because it is a JSON Schema property
