### ISSUE TITLE
Permission to show names interferes with ballots of delegated votes

### ISSUE THREAD

**Issue by tibetischeszentrum** [OpenSlides/OpenSlides#5744]
**Describe the bug**
OpenSlides does not show ballots for delegated votes, when the delegates group does not have the permission to show names of other participants in the participants list.

Therefore it is not possible to not display the list of all members that have been entered into openslides and still have delegated votes. This connection is also not at all obvious, since there is no warning or error message; the voting buttons will just silently not show op for the delegated votes.

**How to Reproduce**
1. create delegates and transfer votes for some of them to other delegates
2. remove persmission to show names of users from the delegates group
3. create a ballot
4. the delegates will not see voting buttons for the votes delegated to them

**Expected behavior**
Delegates should be able to the votes they have received delegations for. 
The general permission to show the names of other users should not interfere with the voting process.

**System information**

- OpenSlides-Version: 3.3

**Comment by tsiegleauq** [comment]
probably a won't fix for me. `users.can_see` has been defined as a bare minimum requirement for the vote delegation to work well.

**Comment by FinnStutzenstein** [comment]
Hm, I recently fixed voting itself with vote delegations and the absence of `users.can_see_names` since I noticed it myself. What exact version do you use. It would be great, if you can give a commit hash or so.

**Comment by tibetischeszentrum** [comment]
If the problem itself won't be fixed, there needs to be a warning message of some kind, that this permission will effectivly disable delegated voting. Otherwise - like it happend to us - the entire event may have to be cancelled because of this bug and not being able to find it's cause "live on stage".

**Comment by FinnStutzenstein** [comment]
> If the problem itself won't be fixed

meybe yes, if you provide the commit hash and we can look into it..

**Comment by tibetischeszentrum** [comment]
> > If the problem itself won't be fixed
> 
> meybe yes, if you provide the commit hash and we can look into it..

How do I get the commit hash? I installed it via docker-compose. Version 3.3

**Comment by FinnStutzenstein** [comment]
Ok, is the problem still present?

**Comment by tibetischeszentrum** [comment]
> Ok, is the problem still present?

Yes, it is fixed now. Didn't check before now, because in this thread I didn't get the understanding that it even was attempted to be fixed. 
Thank you very much!
