### ISSUE TITLE
Delegated votes get counted inspite of the receiving user not being present

### ISSUE THREAD

**Issue by tibetischeszentrum** [OpenSlides/OpenSlides#5745]
**Describe the bug**
Users who delegated their voice get counted in spite of the users to whom the vote was delegated not being set to present.

**How to Reproduce**
1. create users and delegate a vote to another user
2. set all users to not present
3. create a motion
4. the number of votes to be given should be 0, but equals the number of delegated votes.

**Expected behavior**
If a user who received delegated votes is not set to present, those delegated votes should not be counted.

**System information**

- OpenSlides-Version: 3.3

**Comment by tsiegleauq** [comment]
Users who delegates their vote will count to the number of votes for a given motion poll or assignment poll, regardless of weather the recipient of the vote weight is present or not.

**Comment by FinnStutzenstein** [comment]
> Users who delegates their vote will count to the number of votes for a given motion poll or assignment poll, regardless of whether the recipient of the vote weight is present or not.

But the user who received the delegation must also be present. So in every case (voting for oneself without delegation and voting for another person) the person who sends the vote must be present. If noone is present, noone can cast a ballot.

**Comment by tibetischeszentrum** [comment]
> Users who delegates their vote will count to the number of votes for a given motion poll or assignment poll, regardless of whether the recipient of the vote weight is present or not.

Yes, you are describing the problem here. This is not how it should be. Or if you disagree, then please make it optional.

**Comment by tsiegleauq** [comment]
@FinnStutzenstein in this case, the server has to ensure that you

- [ ] cannot delegate your vote right to users who are not present
- [ ] unset vote delegations if the users presence status changes

The way the client determines the amount of max votes was defined here.
https://github.com/OpenSlides/OpenSlides/blob/8c28b03ffc60bb32c3757f2cee96e35ba3599ca3/client/src/app/site/polls/components/poll-progress/poll-progress.component.ts#L42-L51
The behavior under the restrictions mentioned above was desired, thus this is a `won't fix` from my side.

**Comment by tibetischeszentrum** [comment]
> @FinnStutzenstein in this case, the server has to ensure that you
>     * [ ]  unset vote delegations if the users presence status changes

It is very hard to track the online status of 200+ participants and then manually remove the delegations for that user when they leave and then again if they come back. 
Also I can not imagine a situation where you would desire a behaviour like this, where the delegated votes are counted when the receiver is absent and therefore can not vote. 

> The behavior under the restrictions mentioned above was desired, thus this is a `won't fix` from my side.
The comment reads "are present or have their right to vote delegated". Sounds to me that whoever wrote that, just forgot the condition: have their rights to vote delegated AND that user is present.
Mistakes happen. This very much looks like an oversight.

**Comment by normanjaeckel** [comment]
Votes: Own vote and delegated vote are always visible. Else you need *.can_manage or poll must be published and you have *.can_see

**Comment by FinnStutzenstein** [comment]
Should be fixed with https://github.com/OpenSlides/OpenSlides/pull/5761
