### ISSUE TITLE
Database doesn‘t start up 

### ISSUE THREAD

**Issue by mb-if** [OpenSlides/OpenSlides#5752]
**Describe the bug**

pgnode, pgbounce -> server-setup can not connect to postgres database. 

wait-for-it: redis:6379 is available after 0 seconds
server-setup_1    | wait-for-it: waiting 15 seconds for redis-slave:6379
server-setup_1    | wait-for-it: redis-slave:6379 is available after 0 seconds
server-setup_1    | wait-for-it: waiting 15 seconds for redis-channels:6379
server-setup_1    | wait-for-it: redis-channels:6379 is available after 0 seconds
server-setup_1    | running migrations
server-setup_1    | SECRET_KEY="inXw6bXGkY5Wb4OkNRZk6kAYBC6E001nO3UeTymEYngYY3rjw88keQl7mHDhRyB6"
server-setup_1    | RESET_PASSWORD_VERBOSE_ERRORS="False"
server-setup_1    | AUTOUPDATE_DELAY="1"
server-setup_1    | DEMO_USERS= (default)
server-setup_1    | EMAIL_HOST="postfix"
server-setup_1    | EMAIL_PORT="25"
server-setup_1    | EMAIL_HOST_USER="" (default)
server-setup_1    | EMAIL_HOST_PASSWORD="" (default)
server-setup_1    | EMAIL_USE_SSL="False" (default)
server-setup_1    | EMAIL_USE_TLS="False" (default)
server-setup_1    | EMAIL_TIMEOUT= (default)
server-setup_1    | DEFAULT_FROM_EMAIL="noreply@example.com"
server-setup_1    | DATABASE_USER="openslides"
server-setup_1    | DATABASE_PASSWORD="openslides"
server-setup_1    | DATABASE_HOST="pgbouncer"
server-setup_1    | DATABASE_PORT="5432"
server-setup_1    | DATABASE_USER="openslides"
server-setup_1    | DATABASE_PASSWORD="openslides"
server-setup_1    | DATABASE_HOST="pgbouncer"
server-setup_1    | DATABASE_PORT="5432"
server-setup_1    | REDIS_HOST="redis"
server-setup_1    | REDIS_PORT="6379"
server-setup_1    | REDIS_SLAVE_HOST="redis-slave"
server-setup_1    | REDIS_SLAVE_PORT="6379"
server-setup_1    | REDIS_CHANNLES_HOST="redis-channels"
server-setup_1    | REDIS_CHANNLES_PORT="6379"
server-setup_1    | REDIS_SLAVE_WAIT_TIMEOUT="10000"
server-setup_1    | AMOUNT_REPLICAS="1"
server-setup_1    | CONNECTION_POOL_LIMIT="100"
server-setup_1    | ENABLE_SAML="False"
server-setup_1    | ENABLE_ELECTRONIC_VOTING="False"
server-setup_1    | JITSI_DOMAIN= (default)
server-setup_1    | JITSI_ROOM_NAME= (default)
server-setup_1    | JITSI_ROOM_PASSWORD= (default)
server-setup_1    | DJANGO_LOG_LEVEL="INFO"
server-setup_1    | OPENSLIDES_LOG_LEVEL="INFO"
server-setup_1    | [2020-12-02 20:34:55 +0100] [44] [INFO] openslides.utils.redis_connection_pool [qPZY] CONNECTION_POOL_LIMIT=100
server-setup_1    | [2020-12-02 20:34:55 +0100] [44] [INFO] openslides.utils.redis [qPZY] Redis address redis://redis:6379/0
server-setup_1    | [2020-12-02 20:34:55 +0100] [44] [INFO] openslides.utils.redis [qPZY] Redis read only address redis://redis-slave:6379/0
server-setup_1    | [2020-12-02 20:34:55 +0100] [44] [INFO] openslides.utils.redis [qPZY] AMOUNT_REPLICAS=1
server-setup_1    | [2020-12-02 20:34:55 +0100] [44] [INFO] openslides.utils.redis [qPZY] REDIS_SLAVE_WAIT_TIMEOUT=10000
server-setup_1    | [2020-12-02 20:34:56 +0100] [44] [INFO] openslides.mediafiles.models [qPZY] Using a standalone mediafile database
server-setup_1    | [2020-12-02 20:34:56 +0100] [44] [INFO] openslides.mediafiles.views [qPZY] Using a standalone mediafile database
server-setup_1    | Traceback (most recent call last):
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
server-setup_1    |     self.connect()
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
server-setup_1    |     self.connection = self.get_new_connection(conn_params)
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
server-setup_1    |     connection = Database.connect(**conn_params)
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
server-setup_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
server-setup_1    | psycopg2.OperationalError: ERROR:  pgbouncer cannot connect to server
server-setup_1    | 
server-setup_1    | 
server-setup_1    | The above exception was the direct cause of the following exception:
server-setup_1    | 
server-setup_1    | Traceback (most recent call last):
server-setup_1    |   File "manage.py", line 11, in <module>
server-setup_1    |     exit(main())
server-setup_1    |   File "/app/openslides/__main__.py", line 41, in main
server-setup_1    |     execute_from_command_line(sys.argv)
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
server-setup_1    |     utility.execute()
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
server-setup_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
server-setup_1    |     self.execute(*args, **cmd_options)
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
server-setup_1    |     output = self.handle(*args, **options)
server-setup_1    |   File "/app/openslides/core/management/commands/migrate.py", line 25, in handle
server-setup_1    |     super().handle(*args, **options)
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
server-setup_1    |     res = handle_func(*args, **kwargs)
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 87, in handle
server-setup_1    |     executor = MigrationExecutor(connection, self.migration_progress_callback)
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
server-setup_1    |     self.loader = MigrationLoader(self.connection)
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
server-setup_1    |     self.build_graph()
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
server-setup_1    |     self.applied_migrations = recorder.applied_migrations()
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
server-setup_1    |     if self.has_table():
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
server-setup_1    |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
server-setup_1    |     return self._cursor()
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
server-setup_1    |     self.ensure_connection()
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
server-setup_1    |     self.connect()
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
server-setup_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
server-setup_1    |     self.connect()
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
server-setup_1    |     self.connection = self.get_new_connection(conn_params)
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
server-setup_1    |     connection = Database.connect(**conn_params)
server-setup_1    |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
server-setup_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
server-setup_1    | django.db.utils.OperationalError: ERROR:  pgbouncer cannot connect to server
**How to Reproduce**
Steps to reproduce the behavior: preferably on [nighty](https://nightly.demo.openslides.org)
Followed step by step the installation guide on Openslides/openslides.
Tried on fresh debian 10 and ubuntu 20 server.
Issue comes up since restructure.

**Expected behavior**

**System information**

- OpenSlides-Version: 3.3
**Additional context**
Add any other information to comprehend your problem

**Screenshots**

**Comment by gsiv** [comment]
> server-setup_1 | running migrations

> server-setup_1 | django.db.utils.OperationalError: ERROR: pgbouncer cannot connect to server

Correct me if I'm wrong but, to me, it looks like `server-setup` can establish
a database connection at first and then loses it.

Could you provide logs for the `pgnode1` and `pgbouncer` services as well?

> **How to Reproduce**
> Followed step by step the installation guide on Openslides/openslides.
> Tried on fresh debian 10 and ubuntu 20 server.

FWIW, I cannot reproduce the problem on Debian 10 following the instructions.

**Comment by tna76874** [comment]
Hi,
actually the very same error message drives me crazy for days. I checked out and build openslides v3.3. Locally on my PC the compose starts up fine and the server is running. On my VPS, with the same OS/docker/docker-compose versions it throws the error mb-if described. I tried to use the docker images I build locally on my PC - but same error.

Any ideas ?

Regards

**Comment by gsiv** [comment]
> Any ideas ?

Only what I wrote in my last message.  Can you provide more info?

**Comment by teichsta** [comment]
same issue here … please find attached my log: https://gist.github.com/teichsta/4bae212acbe4f3687f79d81b18a91736

**Comment by gsiv** [comment]
Thank you for the comprehensive log.  So the error happens early with pgbouncer and has nothing to do with the server services because this does not look right:
```
pgbouncer_1     | 2021-02-02 15:45:42.345 7 LOG C-0x5556d9e6b940: (nodb)/(nouser)@192.168.144.3:53868 registered new auto-database: db=root
pgbouncer_1     | 2021-02-02 15:45:42.345 7 WARNING C-0x5556d9e6b940: (nodb)/(nouser)@192.168.144.3:53868 pooler error: no such user: root
pgbouncer_1     | 2021-02-02 15:45:42.345 7 LOG C-0x5556d9e6b940: (nodb)/(nouser)@192.168.144.3:53868 login failed: db=root user=root
```

There shouldn't be any attempts to connect as/to root, so it would be helpful to find out what causes that.

It is also not clear to me if the following error is a related or a separate problem:
```
pgbouncer_1     | 2021-02-02 15:45:42.380 7 WARNING sbuf_connect failed: Cannot assign requested address
````

Here are some ideas for debugging:
  - Add `set +x` to pgbouncer's entrypoint to get more output.
  - Only start `pgnode1` and `pgbouncer`; the other services aren't helpful for now.

**Comment by teichsta** [comment]
thanks for your answer @gsiv !

As i am using the dockerized setup i am not quite sure how to add `set +x` as well just starting parts of the whole setup with deconstructing the docker-compose file und thus introducing new possible error causes. As of now the docker-compose file is untouched.
