### ISSUE TITLE
Casting a vote of one user leads to reset of ballot for other users

### ISSUE THREAD

**Issue by tibetischeszentrum** [OpenSlides/OpenSlides#5754]
**Describe the bug**
While in autopilot, casting a vote (submitting the ballot) in an election leads to a refresh that resets the checkboxes of other users that are in the process of filling out that ballot.

**How to Reproduce**

1. Create an election
2. Start voting with multiple users
3. Fill out ballot with one user
4. Cast a vote with different user
5. See ballot of first user to clear out

**Expected behavior**
Filling out the ballot without it getting reset multiple times in the process.

**System information**

- OpenSlides-Version: 3.3
- Browser: Tested with uptodate Firefox, Chrome and Safari with fresh profiles without any addons

Also have a Video to document the issue, if needed. Here it is: https://www.youtube.com/watch?v=EVpNVP32lRk
But basically you just see the ballot being reset before sending it. 
When doing this with 10 or more users, it becomes close to impossible to cast your vote, because the reset happens every couple of seconds, until most users have managed to submit their ballot.

**Comment by tsiegleauq** [comment]
This issue has been identified and fixed by @jwinzer before in https://github.com/OpenSlides/OpenSlides/pull/5673 
please add your exact commit hash.

**Comment by tibetischeszentrum** [comment]
I will gladly add my commit hash if you tell where to find it.
The ticket you linked to does not sound related to the issue to me, but I would gladly test it. I run the most up to date version of OpenSlides through the official docker-compose. How can I verfiy that this is supposed to be the fixed version?

**Comment by tsiegleauq** [comment]
from: https://github.com/OpenSlides/OpenSlides/pull/5673
> When a (...) poll is active and a delegate makes a vote selection and then wants to send the vote, his selection is cancelled and he needs to start again **as soon as another delegate sends his vote**.

Sounds about like what you did experience.

How did you install OpenSlides and when was the list time you did update your installation?
If you downloaded the version from GitHub you can extract the commit has using
`git rev-parse HEAD`

**Comment by tibetischeszentrum** [comment]
You were right. That does sound like our problem. 
Git commit hash was:
06044e81c07d3029dea489e63e238dff0fca6bf4
Updated it. New commit hash is:
2943c969abb68cc48bd2db448af41e68289b57f8

Tested it again, Problem is fixed. Thank you for the help.
