### ISSUE TITLE
Initial Password Doesn't Work

### ISSUE THREAD

**Issue by zmberber** [OpenSlides/OpenSlides#5763]
I followed the guide exactly.  I even had a colleague go over it with me step by step (with docker compose).

I can't login with the password I set.  When I set no password, I also don't get login credentials at the login screen (as claimed in the README).

It has worked previously, but I started a new setup and cloned the most recent version and I get this behaviour.  I tried multiple times to set it up from scratch and I can never get past the login screen.

**Comment by tsiegleauq** [comment]
if you followed the guide exactly you could see

`server_1          | [2020-12-09 xx:xx:xx +0100] [xxx] [WARNING] openslides.requests.errors [npjA] /apps/users/login/ 0 {'detail': 'Username or password is not correct.'}`

If the were sending the wrong password to the server. Is this the case?

Did you create your own vim `adminsecret.env`?

**Comment by FinnStutzenstein** [comment]
After a fresh start, please post your logs for `docker-compose logs server-setup`. In the last potion, there should be something like ```
server-setup_1    | Password of user admin successfully changed.
server-setup_1    | Retrieving secure user credentials
server-setup_1    | Adding user: John Doe
...
server-setup_1    | Created user John Doe.
```

It would be nice to try it with a fresh database, so you may have to clear volumes (Attention: this will delete all data).

**Comment by BerberBerthold** [comment]
first of all, sorry for the late reply.

also, sorry about the bug tag, i wasn't sure how else to do this issue, it seemed like it did this automatically, whoops.

i have my own `adminsecret.env`, it reads

```
## secrets/adminsecret.env is sourced by the server container to set the initial
## admin user password.
OPENSLIDES_ADMIN_PASSWORD=hallo123
```

the logs contain the following:
```
server-setup_1    | Retrieving secure admin password
server-setup_1    | Changing admin password
server-setup_1    | SECRET_KEY="<censored>"
server-setup_1    | RESET_PASSWORD_VERBOSE_ERRORS="False"
server-setup_1    | AUTOUPDATE_DELAY="1"
server-setup_1    | DEMO_USERS= (default)
```
(i added the lines afterwards just to put it into context) it doesn't look like quite the way finnstutzenstein described it.

after trying to log in i do indeed get
```
server_1          | [2020-12-12 18:52:44 +0100] [42] [WARNING] openslides.requests.errors [Nrxo] /apps/users/login/ 0 {'detail': 'Username or password is not correct.'}
```

also i do have a complete fresh setup, i tried it multiple times.  i deleted the cloned git repository and recloned again and started everything up from scratch (multiple times)

thanks for your help!

**Comment by tsiegleauq** [comment]
Tried multiple times, could not reproduce. Probably not an OpenSlides issue. @FinnStutzenstein might be able to help you out

**Comment by BerberBerthold** [comment]
interesting.  thanks for trying it out.  so then i guess that you are probably right and there is something on my end that is wrong.  i'll see if i can find the problem.

**Comment by FinnStutzenstein** [comment]
>  I also don't get login credentials at the login screen

Which is correct (see readme): If you do not set a custom admin password, there will be credentials (admin/admin). The way the code is written indicates, that the admin does not have admin as password anymore, so something was set in the DB.

Is the secret key the same for the server and server-setup?

**Comment by FinnStutzenstein** [comment]
Another question: Do you have just this one instance running or do you use multiple instances of OpenSlides?

**Comment by BerberBerthold** [comment]
Sorry for the late reply, I am trying again now.

What I meant when I don't get log in credentials at the login screen is, that when I comment out the admin password in `adminsecret.env`, I don't get the login credentials, eventhough the log tells me "`INSECURE ADMIN ACCOUNT CONFIGURATION`".

I have once instance of OpenSlides running.  I tried to do everything from scratch, I deleted my old folder, made a fresh pull from this repository and tried again.  I get the same problems.

**Comment by FinnStutzenstein** [comment]
`INSECURE ADMIN ACCOUNT CONFIGURATION` sounds good, so the login should be admin/admin. Can you log in with admin/admin after starting the setup? So when loading `http://localhost:8000` (or your domain whatsoever), you will be redirected to `/login` and can log in with admin/admin. But the message `Use admin and admin for your first login.` is missing?

**Comment by BerberBerthold** [comment]
yes, that message is missing, and i have tried it.  i have tried setting the password manually and tried it, and i have tried it without setting the password, and i tried admin/admin (and furthermore i don't get said message).  neither works.

**Comment by FinnStutzenstein** [comment]
So you actually are just trying to get the `Use admin and admin for your first login.` message? Every thing else works?

**Comment by BerberBerthold** [comment]
it seems like everything else is working, yes.  well, i will know for sure if i can log in.

**Comment by FinnStutzenstein** [comment]
Ok, I'll try to guide you to step through some steps. First, we will see, if it is a server or client problem. Are you familiar with the `development tools` in your browser? In chrome or firefox you can press F12 to open them. There is a checkbox "disable cache". Make sure it is checked.

Logout, so you can see the login page. With the dev tools open reload the page. Go the the "network" tab in the dev tools (Note: I use chrome, it might be slight different if you use firefox). Can you spot a request to "/apps/users/login"? It might only show as "/login" in the list; chrome likes to hide full urls...

If so, click on it. On the right side are some meta info. Is the status code 200? There is a tab "response" on the right side. Can you provide the content?

**Comment by BerberBerthold** [comment]
status code 200 OK

JSON
```
privacy_policy	""
legal_notice	"<a href=\"http://www.openslides.org\">OpenSlides</a> is a free web based presentation and assembly system for visualizing and controlling agenda, motions and elections of an assembly."
theme	"openslides-default-light-theme"
logo_web_header	Object { display_name: "Web interface header logo", path: "" }
display_name	"Web interface header logo"
path	""
user_id	null
guest_enabled	false
user	null
auth_type	"default"
permissions	[]
```

Response Payload
```
{"privacy_policy":"","legal_notice":"<a href=\"http://www.openslides.org\">OpenSlides</a> is a free web based presentation and assembly system for visualizing and controlling agenda, motions and elections of an assembly.","theme":"openslides-default-light-theme","logo_web_header":{"display_name":"Web interface header logo","path":""},"user_id":null,"guest_enabled":false,"user":null,"auth_type":"default","permissions":[]}
```

**Comment by FinnStutzenstein** [comment]
Ok, server problem since `login_info_text` is not in the response. The response data is generated here: https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/users/views.py#L934

We are definitely in the else part since the key `login_info_text` is not present. In the code it is tried to get the user with username `admin` and it is checked, if the password is `admin`. If so the missing message will be provided within the key `login_info_text`.

So either no user with username `admin` was found or if found, the password "admin" is not accepted. But you can log in with admin/admin?

Are you able to change the code and rebuild the server docker image? See the changes [here](https://github.com/FinnStutzenstein/OpenSlides/commit/c1533a6d2b5d5c04520ace13feae84a3274c6401). They are available in https://github.com/FinnStutzenstein/OpenSlides/tree/debug5763, so you can use this branch to build new images.

I've added three prints: One for the else-part (which should always print) and two for the two cases above. This is printed on every request to /apps/users/login, so you should see it in the logs when refreshing the page.

What of these statements do you see?

**Comment by BerberBerthold** [comment]
```
server_1        | Else-branch
server_1        | Passwort is not admin
```

**Comment by FinnStutzenstein** [comment]
Ok, can you log in, change the admin password to something else, check if it worked and change it back to `admin`? Does the message appears?

**Comment by BerberBerthold** [comment]
i am sorry, i don't think i understand.  what do you mean by "log in"?  i can't log in.  at all.  that's the big problem i have.

i tried setting the admin password in `adminsecret.env`, tried to log in with that, and it doesn't work.  the log does mention that i set it, though:
```
server-setup_1  | The admin has not the default password. Done.
```

**Comment by FinnStutzenstein** [comment]
> i can't log in

I've ask you multiple times, if you can log in and you always answered yes.

When you delete the `server/personal_data/var/db.sqlite3` and restart the server. Do you see the migrations running?

**Comment by BerberBerthold** [comment]
sorry, i am rereading what i wrote.  there was a misunderstanding.  i can't log in.  i am not just trying to get the `Use admin and admin for your first login.`, i am also just trying to log in in any way.  i wanted to say that neither setting it nor not setting it works, and when i not set it, i don't get that message.  i replied wrongly by saying "everything else works".  i meant it seems like everything else should work once i am able to actually log in.  whatever.  sorry for the confusion.

the `server/personal_data` directory doesn't exist on my setup...  when does it get created?  it seems like i have done womething wrong.

**Comment by FinnStutzenstein** [comment]
Ah well, you are using a productive setup. Stop your setup and delete your database: `docker volume rm docker_dbdata1` (`dbdata1` is the default name in the `docker-compose.yml`; the `docker_` is the prefix put before every service belonging to the compose setup). Start the setup again.

(I assume you have the default config with one pg node enabled)
