### ISSUE TITLE
Docker build failed at client npm ci

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#5764]
**Describe the bug**
I am trying to install the current master as it is described in the Readme (install with Docker-Compose).  The only command that I called was `./build.sh all`.

The first time it freezes at `[nodejs 10/14] RUN npm ci`. I waited for 20 minutes.

The second time the same command failed with the message:

```
 => ERROR [nodejs 10/14] RUN npm ci                                                                                                                                                      38.3s
------
 > [nodejs 10/14] RUN npm ci:
#16 38.24 npm ERR! cb() never called!
#16 38.24 
#16 38.24 npm ERR! This is an error with npm itself. Please report this error at:
#16 38.24 npm ERR!     <https://npm.community>
#16 38.31 
#16 38.31 npm ERR! A complete log of this run can be found in:
#16 38.31 npm ERR!     /home/openslides/.npm/_logs/2020-12-09T16_14_41_146Z-debug.log
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c npm ci]: runc did not terminate sucessfully
```

The third time the command `npm ci` worked, but it failed at with 

```
 => ERROR [internal] load git source https://github.com/OpenSlides/openslides-docker-compose.git#:postfix  
```

But I think this is a separate error.

Is it possible to make the docker-install more stable?

**System information**

- OpenSlides-Version: git 78cfa4875ef1484461642c1ae862ef4ca1259738  
- Python Version: 3.9
- Device: Notebook
- OS: Archlinux

**Comment by tsiegleauq** [comment]
I tried to reproduce this, I pruned my docker containers, volumes and images, and can run `./build.sh all` on the very same commit without problem.

**Comment by FinnStutzenstein** [comment]
Yes, this also is my current point of view. So we need a way to reproduce it or so.

**Comment by gsiv** [comment]
> The third time the command `npm ci` worked, but it failed at with
> 
> ```
>  => ERROR [internal] load git source https://github.com/OpenSlides/openslides-docker-compose.git#:postfix  
> ```
> 
> But I think this is a separate error.

You are right; Postfix has nothing to do with NPM or the client image.  The most likely explanation I can come up with is that your network connection went down.

**Comment by FinnStutzenstein** [comment]
> The most likely explanation I can come up with is that your network connection went down.

Would be a good explaination

**Comment by Ranger234** [comment]
I'm facing the problem of ostcar today (22.Jan.2021). I've tried the process (./build.sh all) on Ubuntu Server 18.04 (two different virtual machines) and on Ubuntu Server 20.04. All running as VM on KVM based on Ubuntu. 

After several attempts at different times of the day with an obviously well working internet connection I would say:
> > The most likely explanation I can come up with is that your network connection went down.
> 
> Would be a good explaination
is a quiet far-fetched bug source. 

In my observations the process is not freezing, it just starts a massive download at  Step 12/19.

```
Step 12/19 : RUN npm ci
 ---> Running in 671a4b7694ba
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/openslides/.npm/_logs/2021-01-22T14_27_16_024Z-debug.log
The command '/bin/sh -c npm ci' returned a non-zero code: 1
 
```
Hope this helps.

**Comment by gsiv** [comment]
> > > The most likely explanation I can come up with is that your network connection went down.
> > 
> > 
> > Would be a good explaination
> 
> is a quiet far-fetched bug source.

Sure, there may be other explanations that are equally likely.  His nameserver
might have had an outage, or maybe GitHub.  What is less likely is that the
connection error is rooted in a bug in the build script.

Please note that this guess was specifically about the Postfix image problem,
not the NPM error you're describing below.  

> ```
> npm ERR! This is an error with npm itself. Please report this error at:
> npm ERR!     <https://npm.community>
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/openslides/.npm/_logs/2021-01-22T14_27_16_024Z-debug.log
> The command '/bin/sh -c npm ci' returned a non-zero code: 1
>  
> ```
> 
> Hope this helps.

I'm afraid it doesn't.  It would be interesting, however, if you could also
provide `2021-01-22T14_27_16_024Z-debug.log`.

**Comment by Ranger234** [comment]
> if you could also
> provide `2021-01-22T14_27_16_024Z-debug.log`.

Here it is
[2021-01-22T14_27_16_024Z-debug.log](https://github.com/OpenSlides/OpenSlides/files/5857066/2021-01-22T14_27_16_024Z-debug.log)

**Comment by FinnStutzenstein** [comment]
This is a duplicate to #5579 

As I said there, it is not an OpenSlides issue but rather a npm one. I have anohter very small react project and I sometimes get the error there, too. Please consider opening an issue at npm directly.

Additionally, the error itself says, that it is an npm problem and it should be reported there:
```
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
```

**Comment by parthmern** [comment]
I solve it by just closing my VPN / PROXY connection

After 3 hrs without using vpn i am facing same issue
