### ISSUE TITLE
Test Docker build

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#5766]
**Describe the bug**
Currently, the Docker-Build does not work.

There is issue #5764. And it also fails, because the `openslides-docker-compose` does not seem to work.

I would be nice if there would be a travis or github-action test to ensure it.

**Comment by tsiegleauq** [comment]
on OpenSlides 4 docker was already tested using github actions. OpenSlides 3 will not be tested for docker. Building the productive docker setup inside a CI environment takes way too much time on every PR.

**Comment by ostcar** [comment]
We could configure the test, that a PR can be merged before the test passes. In this case we get eventually informed, that the master branch is broken. I think this is better then the current situation, that it is not tested at all

**Comment by FinnStutzenstein** [comment]
Are you talking about OS3, OS3+ or OS4?

**Comment by tsiegleauq** [comment]
> We could configure the test, that a PR can be merged before the test passes.

ah yes, I forgot that this is possible. Other projects are using these state badges to indicate if the project passes the (prod) build process. I'll think about that.

**Comment by ostcar** [comment]
It was for OS3 and is not relevant anymore.
