### ISSUE TITLE
Make all endpoint URLs configurable on consuming containers

### ISSUE THREAD

**Issue by InterFelix** [OpenSlides/OpenSlides#5771]
**Is your feature request related to a problem? Please describe.**
If the server container has DNS-Name different from "server", the client won't be able to reach it, since there is no way to inform the client about a different endpoint.

**Describe the solution you'd like**
Make all containers use Env-Variables for endpoints they consume. Should be fairly straightforward, if my limited knowledge serves me right.

**Additional context**
I'm currently working on a helm chart for OpenSlides and need to be able to prefix all DNS-Names for the containers with a shared "Release name", so that there are no conflicts if multiple instances of my chart are deployed in one environment.

**Comment by tsiegleauq** [comment]
OpenSlides 4 already supports configurable URL endpoints.

**Comment by InterFelix** [comment]
Just curious, is there an official helm chart planned?

**Comment by FinnStutzenstein** [comment]
No, currently not.
