### ISSUE TITLE
Exchangable Videoplayer for Livestream

### ISSUE THREAD

**Issue by sistein** [OpenSlides/OpenSlides#5772]
**Is your feature request related to a problem? Please describe.**
I would like to use LL-HLS to enable a very low latency stream back to the user. Unfortunaly VideoJS is not supporting LL-HLS by now. 

**Describe the solution you'd like**
I would like to be able to change the videoplayer to something else.

**Comment by tsiegleauq** [comment]
I am currently working on supporting live streams from youtube. I don't think that we are to replace video.js anytime soon.
For videojs, your feature request was discussed here https://github.com/videojs/http-streaming/issues/721 but not too much has happened.
What player do you suggest?

**Comment by sistein** [comment]
Hi tsiegleauq,

I'm quite new into this topic but was able to reduce the latency using Jitsi via  Jibri via Wowza back to me below 5 seconds. 

In my tests I used https://www.theoplayer.com/ . This player is however not free in every case. 

Another thinkable solution would be WebRTC.

**Comment by tsiegleauq** [comment]
Jitsi is WebRTC, thus not quite the applicable solution for huge gatherings due to natural bandwidth limitation in clients. The player you mentioned cannot be included due to the unfitting license.

**Comment by sistein** [comment]
Would it be possible to have a iframe where simple HTML Code might be pasted? Then I could even with a unfitting license add the player or any other as well. 

Regarding my mention WebRTC solution:

It would still be: 
Openslides -> Jitsi -> Jibri -RTMP-> Wowza -WebRTC-> User

**Comment by tsiegleauq** [comment]
> Would it be possible to have a iframe where simple HTML Code might be pasted? Then I could even with a unfitting license add the player or any other as well.

That is essentially what I am doing with youtube right now (see: https://github.com/OpenSlides/OpenSlides/pull/5770/files#diff-08783f8a98b7c3b8c33917b1c6100401fb2cbebd1fdad8dada147fdd5d3ee52aR7-R14 )
sideloading custom URLs can probably be done. How would a iFrame showing wowza look like?

**Comment by rasos** [comment]
I would like to use Peertube as a streaming server. However, it does not start playing with the current videoplayer, see [this example link](https://fair.tube/videos/watch/a5bcc9ab-221c-4e25-afdb-88d837741b61).

**Comment by fcqpl** [comment]
I came here from video.js issue. I'm not using OpenSlides... but maybe try https://github.com/AirenSoft/OvenMediaEngine?
It's webrtc streaming server with player. It support incoming RTMP streams.
