### ISSUE TITLE
Check and update modelsvalidator

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/OpenSlides#5781]
The changes from https://github.com/OpenSlides/OpenSlides/pull/5769 have to be reflected in the validator. I hacked a temporary solution so the validator passes again, please check that as well. Also we should add more checks like @normanjaeckel mentioned here: https://github.com/OpenSlides/openslides-backend/pull/339#issuecomment-743313173

**Comment by jsangmeister** [comment]
The description in the `models.yml` should be up to date on the possible values.

**Comment by jsangmeister** [comment]
Another thing, kinda off-topic: Should we move the `models.yml` from the `docs` folder to something better suited? The times when it was "just docs" are long gone and the file is now an important part of the whole system so I don't think it belongs in the `docs` folder.

**Comment by normanjaeckel** [comment]
Ok for me.

**Comment by FinnStutzenstein** [comment]
https://github.com/OpenSlides/OpenSlides/pull/6041#discussion_r622931865

**Comment by normanjaeckel** [comment]
Please reopen a new issue if some concrete checks are missing.
