### ISSUE TITLE
Adapte models.yml to new permission wording

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#5787]
https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/models.yml#L1331

https://github.com/OpenSlides/openslides-permission-service/blob/master/permissions.yml

The wording in models.yml has to be changed according to the new permissions strings.

**Comment by tsiegleauq** [comment]
Was changed in https://github.com/OpenSlides/openslides-permission-service/commit/2c3ae33c7948ad100da8e40bb404882003af232e
