### ISSUE TITLE
Rename meeting-superadmin to admin

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#5788]
Currently, the name "superadmin" has two meanings. There is the [organization superadmin](https://github.com/OpenSlides/OpenSlides/blob/a3dce30e1df12f72316eafa2d42461a5c07487d8/docs/models.yml#L79) and the [meeting superadmin](https://github.com/OpenSlides/OpenSlides/blob/a3dce30e1df12f72316eafa2d42461a5c07487d8/docs/models.yml#L718).

Could we rename the meeting-superadmin to admin? It would help to talk about the permissions.

**Comment by FinnStutzenstein** [comment]
ok for me

**Comment by tsiegleauq** [comment]
I guess that was done up until last Friday at the meeting. If it was not done in a service, it will soon stumble upon this change anw. Closing.
