### ISSUE TITLE
Create new collection for vote delegation

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#5789]
The permission service requires that the vote delegation feature gets a new collection (e. g. `vote_delegation` with reference to the two involved users). @ostcar may describe the problem.

**Comment by FinnStutzenstein** [comment]
This is not good, since it is conflicting with the autoupdate format. We currently **need** the structured fieds for users to seperate the relation on a per-meeting basis. The autoupdate format cannot deal with m2m tables.
