### ISSUE TITLE
Wrong vote result with general approval/rejection

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#5807]
With voting method Yes per candidate and General approval enabled you get wrong vote results.

Here are two test cases demonstrating this:

[Wahlgang (1)](https://nightly.demo.openslides.org/assignments/polls/25)

Administrator voted explicitly for f and g. I expected General approval to be 0. However, it mistakenly says (200 %) 2.

[Wahlgang (2)](https://nightly.demo.openslides.org/assignments/polls/26)

Administrator voted for General Approval. Amount of votes was 2 but only one vote was counted - for h.

Solution proposal: If amount of votes < number of candidates, general approval does not make sense and should be disabled. If amount of votes >= number of candidates, all candidates MUST be elected if general approval is checked.

Similar issue with No per candidate and General rejection.

[Wahlgang (3)](https://nightly.demo.openslides.org/assignments/polls/28)

Administrator voted explicitly against f. General approval says (100 %) 1 but should be 0.

[Wahlgang (4)](https://nightly.demo.openslides.org/assignments/polls/29)

3 votes, 3 candidates. Administrator voted General rejection. Only candidate f was rejected. I expect ALL 3 candidates to be rejected.

**Comment by FinnStutzenstein** [comment]
This is due to the way the general vote is saved. This is fixed in OS4, but I see that wrong results should not be shown. One solution would be to set global_yes to false on votes method `Y` and the same for `n` with global_no, right?

**Comment by jwinzer** [comment]
I like to have global_yes for votes method Y but as I pointed it should only be enabled if number of votes >= number of candidates. And for named voting the single votes should indicate that a global_yes was cast. The same is true for global_no and votes method N.

**Comment by FinnStutzenstein** [comment]
Sorry, I can't really follow your problem. Since it seems not to be a technical problem but rather a logic one, maybe talk directly to emanuel.

**Comment by jwinzer** [comment]
Thanks, Finn. I've already started to discuss this with Emanuel.

**Comment by jsangmeister** [comment]
outdated
