### ISSUE TITLE
Loading indicator in Firefox runs indefinitly

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/OpenSlides#5813]

**Comment by lplatzer** [comment]
You'll need to add more information. One possible issue could be apache, which can be solved as described [here](https://github.com/OpenSlides/OpenSlides/issues/5596#issuecomment-729940572) (you might need to enable certain apache modules as described in the comment below the linked post.)

**Comment by FinnStutzenstein** [comment]
Hi, thanks for your interest in OpenSlides!

This is just a reminder issue for me, that with the new communication stack (#5533 was merged just a few days ago, has nothing to do with apache/WebSockets) the browser loading indicator in FF does not disappear.

**Comment by FinnStutzenstein** [comment]
I tested FF 78.4.1esr locally and it worked. @jsangmeister I do have this issue with our team instance, maybe it is somethingjitsi-related. I'll ask Sean how to debug this.

**Comment by FinnStutzenstein** [comment]
It is the productive build: With this type of build the loading indicator hangs due to autoupdate/notify/projector. Todo: Check, why the resquests are too early.
