### ISSUE TITLE
Point of order are in wrong order

### ISSUE THREAD

**Issue by Habichtsberg** [OpenSlides/OpenSlides#5816]
When two persons submit a point of order, the second point of order get's the new first one, not the second one as it should be.

**How to Reproduce**
1. You have a speakers list, maybe with some speakers on it.
2. Person A submits a point of order and is shown at position one of the speaking list with the red triangle with the exclamation mark.
3. Person B submits another point of order and is now shown as the new position one of the speaking list. The former submitted point of Order of Person B is on position 2 now.

The result looks sth. like this.
1. Person B (!)
2. Person A (!)
3. Speaker 1
4. Speaker 2
5. Speaker 3

**Expected behavior**
The behavior is wrong.
Point of order is prioritized above regular speakers list.
But the are also handled be the order they where submitted.
First in, first speaks.
Second submitted point of order is handled after the first one.

The result should look like this:
1. Person A (!)
2. Person B (!)
3. Speaker 1
4. Speaker 2
5. Speaker 3

**System information**
- OpenSlides-Version: 3.4
- Does not depend on the users browser. Seems to be a general problem.

**Comment by tsiegleauq** [comment]
Works as intended. Later Points Of Orders usually take the priority. This directly resembles points of orders to other points of orders.

**Comment by FinnStutzenstein** [comment]
Yes, If you set yourself on the list of speakers as a point of order, you take preference about current waiting speakers including all point of order speakers.

> not the second one as it should be

Where is it defined, that it should be the second one?

**Comment by Habichtsberg** [comment]
It is common practice at party congresses that several persons are able to raise a point of order. In this case, the points of order are dealt with individually in exactly the order in which they were raised.
First first, then the second etc.

**Comment by emanuelschuetze** [comment]
@Habichtsberg Yes, you are right. I can confirm your bug report. The expected behavior is:

1. Person A (!)
1. Person B (!)
1. Speaker 1
1. Speaker 2
1. Speaker 3

We will fix it. Thanks for your report.
