### ISSUE TITLE
Vote weighting not available when adding a new participant

### ISSUE THREAD

**Issue by flaric** [OpenSlides/OpenSlides#5818]
Although vote weighting in participant settings is activated, there is no field where it can be entered when adding a new participant.  

**System information**

- OpenSlides-Version: 3.3
- Additional version information (if any):
- Python Version: [e.g. 3,5, 3.6, 3.7]
- Device: Raspberry Pi B+
- OS: Raspbian
- Browser: Chrome 
- Browser-Version: Version 87.0.4280.141 (Offizieller Build) (64-Bit)

**Additional context**
Add any other information to comprehend your problem

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/77780391/105339036-88bdb980-5bdc-11eb-990a-4383dada2d38.jpg)

![2021-01-21 11_29_22-New participant - OpenSlides](https://user-images.githubusercontent.com/77780391/105339066-907d5e00-5bdc-11eb-9d77-47adcd4a5e57.png)

**Comment by tsiegleauq** [comment]
Should be right of participant number. Cannot confirm for OS 3.3+ master

How did you build OpenSlides?

![image](https://user-images.githubusercontent.com/10233032/105512609-9bfe8100-5cd1-11eb-9ba7-2db203d9452b.png)

**Comment by tsiegleauq** [comment]
Could not be reproduced. No response within some months. Closing.
