### ISSUE TITLE
Where is the client

### ISSUE THREAD

**Issue by sanojkl** [OpenSlides/OpenSlides#5820]
I install via pypi /pip the version 3.3. I need to change something with has to do with the live stream features, which was handled over the client. Where are my client folder?

**Comment by sanojkl** [comment]
espacially where the static content is to server them directly instead of the nginx proxy and where the html files are to built in the youtube stream

**Comment by tsiegleauq** [comment]
You installed a productive version. The client in your build is productive, uglified JS code and cannot simply be altered.
If you need to alter the client you have to build OpenSlides yourself.

**Comment by sanojkl** [comment]
ok i get it, but i cant build it myself because lots of problems with npm package versions and so on
@tsiegleauq can you send me a buolt version with the youtube url commit?
sorry for my questions, i know they arent professional

**Comment by tsiegleauq** [comment]
The youtube commit can be found there:
https://github.com/OpenSlides/OpenSlides/pull/5770

I cannot really recommend using it. There are some conceptual issues to resolve. Currently it will be a a great bandwidth hogger if you use multiple tabs in OpenSlides. Perhaps you want to request a feature if you need to alter something.
