### ISSUE TITLE
SSL handshake failure with haproxy

### ISSUE THREAD

**Issue by mightynico** [OpenSlides/OpenSlides#5824]
I try to install openslides on Debian 10. But after i start the Docker-Compose and try to visit the Openslide instance with my browser i get the error haproxy_1       | 172.24.0.1:53852 [26/Jan/2021:07:56:33.407] https/1: SSL handshake failure

I user Apache 2 with following vhost config
ProxyPreserveHost on
ProxyPass / http://127.0.0.1:8000/
ProxyPassReverse / http://127.0.0.1:8000/
RewriteEngine on
RewriteCond %{SERVER_NAME} =xxx.xxxxx.de
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

ssl config
ServerName xxx.xxxxx.de
ProxyPreserveHost on
ProxyPass / http://127.0.0.1:8000/
ProxyPassReverse / http://127.0.0.1:8000/
SSLProtocol -all +TLSv1.2 +TLSv1.3
SSLCertificateFile /etc/letsencrypt/live/xxx.xxxxx.de/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/xxx.xxxxx.de/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf

docker log in the file attaached
[docker-log.txt](https://github.com/OpenSlides/OpenSlides/files/5872010/docker-log.txt)

Thanks for helping me

**Comment by FinnStutzenstein** [comment]
Simple "fix": Use https ;)

go explicitly to https://localhost:8000

There is a current bug in haproxy that doesn't let us create a https redirect for the same port...

**Comment by mightynico** [comment]
Thanks thats it
