### ISSUE TITLE
Validate the example data

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#5826]
Finish validating the `docs/example-data.json` with the `docs/models.yml`. This is the first try by Norman: https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/modelsvalidator/check_json.py

**Comment by reiterl** [comment]
I have tried to improve the check_json.py and get a lot of missing fields in the initial_data.json.
Check for ../../docker/initial-data.json failed:
Collection meeting 1. Missing fields: speaker_ids, poll_default_group_ids, poll_default_100_percent_base, assignment_poll_ballot_paper_selection, poll_default_method, poll_ballot_paper_number, poll_default_type, poll_sort_poll_result_by_votes, poll_ballot_paper_selection, assignment_poll_ballot_paper_number, conference_stream_poster_url, poll_default_majority_method.
Collection group 1. Missing fields: used_as_poll_default_id.
Collection group 2. Missing fields: used_as_poll_default_id.
Collection group 3. Missing fields: used_as_poll_default_id.
Collection group 5. Missing fields: used_as_poll_default_id.
Collection group 6. Missing fields: used_as_poll_default_id.

**Comment by FinnStutzenstein** [comment]
Ok, these are indeed issues. Please check again with the changes in #5831 included. Please check the `docker/initial-data.json` as well as `docs/example-data.json`.

**Comment by FinnStutzenstein** [comment]
First checks are done. Still a TODO:
- Check template fields
- More checking of fields and error handling: What happens if an id is not an int, ...
