### ISSUE TITLE
Motions import cannot find column supporters

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#5830]
After selecting a file in Import Motions there is no preview available.
The console reports an error:

![image](https://user-images.githubusercontent.com/20415092/106132451-3fcdae00-6164-11eb-9dd7-5f7d4ce9ff99.png)

Also noticing that the motions import sample file is missing the supporters column.

**Comment by jsangmeister** [comment]
fixed in new import
