### ISSUE TITLE
Build process behind proxy fails

### ISSUE THREAD

**Issue by stephanhendl** [OpenSlides/OpenSlides#5833]
**Describe the bug**
I've tried to build OpenSlides via docker on a Debian 10 host behind a proxy. Due to security reasons there is no way to get a direct internet access. I've put the proxy configuration in /etc/systemd/system/docker.service.d/http-proxy.conf

```
[Service]
Environment= "HTTP_PROXY=http://<ip>:<port>" "HTTPS_PROXY=http://<ip>:<port>" "NO_PROXY=..."
```

as well as included a "--build-arg" option in the "server/build.sh" script

```
docker build --build-arg http_proxy=http://<ip>:<port> --build-arg https_proxy=http://<ip>:<port> --tag "${img:-openslides/openslides-${service_name}:latest}" \
  --pull "${OPTIONS[@]}" -f docker/Dockerfile .
```

This works until step 19/19 and fails within the building of media-services where repositories cannot be found.

```
Building openslides/openslides-media-service:latest...
Sending build context to Docker daemon  117.2kB
Step 1/10 : FROM python:3.8.1
3.8.1: Pulling from library/python
Digest: sha256:7be36bd79ab0d754c2a6db5351b7bf91ebe7161cd0d80a15e47ab2c211a0828b
Status: Image is up to date for python:3.8.1
---> efdecc2e377a
Step 2/10 : RUN apt-get -y update && apt-get -y upgrade &&   apt-get install --no-install-recommends -y     postgresql-client
---> Running in 2e96a3c4f078
Err:1 http://security.debian.org/debian-security buster/updates InRelease
  Could not connect to debian.map.fastlydns.net:80 (199.232.138.132). - connect (111: Connection refused) Could not connect to security.debian.org:80 (151.101.192.204). - connect (111: Connection refused) Could not connect to security.debian.org:80 (151.101.0.204). - connect (111: Connection refused) Could not connect to security.debian.org:80 (151.101.64.204). - connect (111: Connection refused) Could not connect to security.debian.org:80 (151.101.128.204). - connect (111: Connection refused)
Err:2 http://deb.debian.org/debian buster InRelease
  Could not connect to debian.map.fastlydns.net:80 (199.232.138.132). - connect (111: Connection refused) Unable to connect to deb.debian.org:http:
Err:3 http://deb.debian.org/debian buster-updates InRelease
  Unable to connect to deb.debian.org:http:
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Could not connect to debian.map.fastlydns.net:80 (199.232.138.132). - connect (111: Connection refused) Unable to connect to deb.debian.org:http:
W: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease  Could not connect to debian.map.fastlydns.net:80 (199.232.138.132). - connect (111: Connection refused) Could not connect to security.debian.org:80 (151.101.192.204). - connect (111: Connection refused) Could not connect to security.debian.org:80 (151.101.0.204). - connect (111: Connection refused) Could not connect to security.debian.org:80 (151.101.64.204). - connect (111: Connection refused) Could not connect to security.debian.org:80 (151.101.128.204). - connect (111: Connection refused)
W: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  Unable to connect to deb.debian.org:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package postgresql-client
The command '/bin/sh -c apt-get -y update && apt-get -y upgrade &&   apt-get install --no-install-recommends -y     postgresql-client' returned a non-zero code: 100
```

**System information**

- OpenSlides-Version: 3.3
- Additional version information (if any): [e.g. commit hash or installation-month]
- Python Version: 3.7.3
- Device: Server
- OS: Debian 10

**Comment by tsiegleauq** [comment]
> Could not connect to debian.map.fastlydns.net:80 (199.232.138.132)

If you cannot access the docker images from debian, you need to build OpenSlides yourself.
This is not an OpenSlides issue. What kind of solution would you expect?

**Comment by stephanhendl** [comment]
I can access docker images as well as Debian repositories from the underlaying OS itself and during the build-process with the "--build-arg" in the build.sh-script as well. I don't know where the "Building openslides/openslides-media-service:latest" is startet from. From inside one of the docker images or is there another build-script used where I should configure proxies separately?

Regards,
Stephan

**Comment by FinnStutzenstein** [comment]
You may have to adjust this line, too: https://github.com/OpenSlides/OpenSlides/blob/master/docker/build.sh#L99
This is the line where the media service is built.

**Comment by stephanhendl** [comment]
@FinnStutzenstein Thank you! That was the solution.

A an enhancement I would suggest that if there is a proxy configuration in docker (e.g. /etc/systemd/system/docker.service.d/http-proxy.conf) the same proxies should be configured to the build.sh scripts.

**Comment by FinnStutzenstein** [comment]
I never used proxies for docker builds, but I'm curious here: I would assume that settings in ` /etc/systemd/system/docker.service.d/http-proxy.conf` are system wide, so why do you have to set some env variables? And maybe I'm wrong here: The variables are for the host system, not the container?

**Comment by stephanhendl** [comment]
AFAIK the variables in http-proxy.conf are for docker itself, e. g. if docker image should be pulled from docker hub. The tags in the docker build command are for usage of proxies during build process as well as inside the container. In this case additinal packages had to be installed in the Debian container.

**Comment by jsangmeister** [comment]
outdated
