### ISSUE TITLE
Amendments hidden

### ISSUE THREAD

**Issue by sanojkl** [OpenSlides/OpenSlides#5834]
**Describe the bug**
The Amendments aren not shown in the list, only the counter said 0 from XX. I am loged in as admin, this means that i have the permissions to see the amendments. When i toggle that the amendments should also be shown in motion lists, it was shown in the motion list but not in the amendment list at all.

**How to Reproduce**
i didnt found out why, the following are shown when i debug the website:

ERROR Error: Inconsistency or invalid call of this function detected (to)
    serializePartialDomToChild https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    extractRangeByLineNumbers https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    getAmendmentParagraphsLines https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    getAmendmentParagraphLines https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    getAmendmentParagraphLines https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    get https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    handleRelation https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    handleCachedRelation https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    get https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    get parentAndLineNumber https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    get https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    sortItems https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    updateSortedData https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    updateSortedData https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    inputDataSubscription https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    __tryOrUnsub https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    next https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    _next https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    next https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    _subscribe https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    _trySubscribe https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    _trySubscribe https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    subscribe https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    _subscribe https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    subscribe https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    initSorting https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    i https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    S https://domain.de/polyfills-es2015.e5492a75d8d9e9705470.js:1
    i https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    initSorting https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    getListObservable https://domain.de/2-es2015.1ff02381f0148496b59d.js:1
    ngOnInit https://domain.de/2-es2015.1ff02381f0148496b59d.js:1
    i https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    S https://domain.de/polyfills-es2015.e5492a75d8d9e9705470.js:1
    i https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    ngOnInit https://domain.de/2-es2015.1ff02381f0148496b59d.js:1
    qt https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    Xt https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    Gt https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    Ui https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    Gi https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    template https://domain.de/60-es2015.13b80fe814ce13a10345.js:1
    ar https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    rr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    Or https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    rr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    rr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    rr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    rr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    Or https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    rr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    rr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    rr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    rr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    Or https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    rr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    rr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    sr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    Pr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    Pr https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    detectChanges https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    tick https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    next https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    invoke https://domain.de/polyfills-es2015.e5492a75d8d9e9705470.js:1
    onInvoke https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    invoke https://domain.de/polyfills-es2015.e5492a75d8d9e9705470.js:1
    run https://domain.de/polyfills-es2015.e5492a75d8d9e9705470.js:1
    run https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    next https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    i https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    __tryOrUnsub https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    next https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    _next https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    next https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    next https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    emit https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    Ec https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    onHasTask https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
    hasTask https://domain.de/polyfills-es2015.e5492a75d8d9e9705470.js:1
    _updateTaskCount https://domain.de/polyfills-es2015.e5492a75d8d9e9705470.js:1
    _updateTaskCount https://domain.de/polyfills-es2015.e5492a75d8d9e9705470.js:1
    runTask https://domain.de/polyfills-es2015.e5492a75d8d9e9705470.js:1
    b https://domain.de/polyfills-es2015.e5492a75d8d9e9705470.js:1
    invokeTask https://domain.de/polyfills-es2015.e5492a75d8d9e9705470.js:1
    p https://domain.de/polyfills-es2015.e5492a75d8d9e9705470.js:1
    h https://domain.de/polyfills-es2015.e5492a75d8d9e9705470.js:1
main-es2015.e8681f0f9c9a05a25134.js:1:412528

**Expected behavior**
The list of amendments is shown.

**System information**

- OpenSlides-Version: 3.3.
- Additional version information (if any): [e.g. commit hash or installation-month]
- Python Version: [e.g. 3,5, 3.6, 3.7]
- Device: different mobile and desktop devices
- OS: varios
- Browser: chrome and firefox
- Browser-Version: [e.g. 22]

**Additional context**
Add any other information to comprehend your problem

**Screenshots**
![grafik](https://user-images.githubusercontent.com/62906783/106267918-a5846d80-622a-11eb-957c-5d7a855a1d2d.png)

**Comment by tsiegleauq** [comment]
And another one for #5131.

```
serializePartialDomToChild https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
extractRangeByLineNumbers https://domain.de/main-es2015.e8681f0f9c9a05a25134.js:1
```
This usually happens if the `line-numbering-service` was not able to identify the HTML in your motions. My best guess is that you somehow broke the html code in your amendments and therefore seeing this issue.

This issue has nothing to reproduce and insufficient information. Closing.
