### ISSUE TITLE
Enable customization for password reset mail

### ISSUE THREAD

**Issue by adfcwebmaster** [OpenSlides/OpenSlides#5839]
I'm not a python expert. That's why it took me quite time to discover, that the password reset email is NOT created by _djangos contrib.auth_ module. Body an subject are hard coded in _openslides.users.PasswordResetView_ method _post_ and are NOT translated.
As I want to set up an openslides installation for german users I would like to create my own password reset mail subject and body.
How about improving this or is there some magic configuration to switch to the _django.contrib.auth_ view?
Thanks

**Comment by FinnStutzenstein** [comment]
Right, these messages are not translated. Since we do not have translations on the server, the client sends its localized strings. We do this e.g. with the invitation emails.

If someone wants to implement it in the same way, it is appreciated

**Comment by tsiegleauq** [comment]
Since we will not use django within the next version anymore, this has little value.

**Comment by adfcwebmaster** [comment]
Ok, so I changed the title to a request without django.
For a new implementation has to be considered that the password reset request does not comes from a session so no language info is available from there. A possible solution would be to derive it from browser locale or to make it selectable in the dialog. 
As I'm not a python expert I hesitate to take the job of implementing this feature.

**Comment by jsangmeister** [comment]
Now possible and translatable.
