### ISSUE TITLE
OpenSlides behind nginx reverse proxy

### ISSUE THREAD

**Issue by InterFelix** [OpenSlides/OpenSlides#5840]
Hello,
I need to run OpenSlides behind an nginx reverse proxy. I ran into the problem also described in #5596 with the indicator spinning indefinitely.
I would suggest either a sample reverse proxy configuration for nginx, haproxy, apache, whatever, or a description of what the reverse proxy specifically needs to forward. I understand there needs to be some kind of WebSocket forwarding, but I could not figure out on which ports etc.

**Comment by InterFelix** [comment]
Well, I'm looking to run the whole of OpenSlides behind a Reverse Proxy, together with other applications. So there already is an existing Reverse Proxy setup, and I want to add OpenSlides to it. The haproxy config you linked is an "internal" RP for Openslides, used for pulling together the server and the autoupdate server, right? So I can't quite deduce what I need to change about my nginx config to make it work from that. What I need is only a list of everything I need to pass through to the client in order for it to work properly behind my reverse proxy. Which headers to pass though, or add or delete or whatever, are there locations that need to be treated differently (`/ws` for example?), which settings to use and so on. Most of these things are quite easily transferrable from one RP software config to another, so it would be sufficient if there was an example for nginx or haproxy or whatever with everything you need to know in it.

**Comment by tsiegleauq** [comment]
I suppose @gsiv will be able to answer that in detail.

> What I need is only a list of everything I need to pass through to the client in order for it to work

What the client needs to access was defined here
https://github.com/OpenSlides/OpenSlides/blob/master/client/proxy.conf.json

**Comment by InterFelix** [comment]
Oh, thanks a lot! That helps me out quite a bit. I think I can build a valid nginx config from that.

**Comment by tsiegleauq** [comment]
I suppose we used to have a more detailed one before we dockerized everything. Some artifacts where like:

```
        location / {
            try_files $uri $uri/ /index.html;

        }
        location /apps {
            proxy_pass http://localhost:8000;
        }
        location /media {
            proxy_pass http://localhost:8000;
        }
        location /rest {
            proxy_pass http://localhost:8000;
        }
        location /ws {
            proxy_pass http://localhost:8000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
```

**Comment by InterFelix** [comment]
That looks great, thanks. Especially the information about the `/ws` location about `proxy_http_version` and the headers is really useful. I have found that in a generic guide on proxying WebSocket-Connections already, so I got that working. But this looks great!
For clarification, this config is basically what the client does internally, right? So the only thing I need to do in my external RP config is something like this:

```nginx
server {
  server_name openslides.example.com;
  listen 80;
  
  location / {
    proxy_pass http://localhost:8080 # if I set up my compose file so that the client container's port 80 is exposed on the server's port 8080
  }
  location /ws {
    proxy_pass http://localhost:8080/ws;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
  }
}
```

**Comment by InterFelix** [comment]
Or for an nginx RP that's running as a container with the OS client container in a network shared between both of them:
```nginx
server {
  server_name openslides.example.com;
  listen 80;
  
  location / {
    proxy_pass http://client:80/ # port 80 added for clarification purposes
  }
  location /ws {
    proxy_pass http://client:80/ws;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
  }
}
```

**Comment by tsiegleauq** [comment]
More or less I suppose that is it.
The client will try to load it's own files from `/`.
CRUD Operations will be send to, for example `/rest/agenda/list-of-speakers/` where the proxy has to forward `/rest` to the backend server

**Comment by InterFelix** [comment]
Yes. But the client does that forwarding internally, correct?

**Comment by tsiegleauq** [comment]
not really, that's the proxies job. The `.json` file I posted above is used for internal angular development, i.e you have the python backend and the angular frontend running in your machine. The snippet from the `nginx.conf` applies to a productive environment. You'll ship the client over an nginx webserver, that webserver will need to proxy the clients requests to the correct backend and to the correct port, namely: `/apps`, `/media`, `/rest`, `/ws` and `/system`.

If you host the client on `:80` it'll simply fire a new motion against
`openslides.example.com/rest/motions/motion/` without any internal forwarding

**Comment by tsiegleauq** [comment]
> I am working on DigiV's fork of OpenSlides right now

I'd advise to either update or migrate to OpenSlides 3.3. Especially for voting, the external auto update is a more than just nice to have. However, the only really critical condition is that your branch is newer than Nov. 20

https://github.com/OpenSlides/OpenSlides/security/advisories/GHSA-w5wr-98qm-jx92

**Comment by FinnStutzenstein** [comment]
both nginx sample configs @InterFelix posted above are correct for older OpenSlides versions. With the newer upgrade explained by @tsiegleauq http2 is required, so a https connection is necessary. Note that we dropped WebSockets and using streaming http responses. This required to set the response timeout[1] to a rather high value, so the proxy does not kill the stream.

[1] In haproxy (the config linked by @tsiegleauq) it is set to one hour. I do not know about nginx/apache or so, especially their h2 handling.

**Comment by akemper** [comment]
For the upcoming annual meeting of my sports club, I'd again like to set up Openslides together with Jitsi on a shared server with separate domains. Since websockets have be replaced with HTTP streaming the previous Nginx SSL proxy (site) configuration isn't working anymore, i.e. after login it gets stuck loading the page. Any tips what to change / add there in Nginx config or is it even impossible to use Nginx as SSL termination with domain separation when proxying HTTP streams? If the latter is the the case, would it be possible to run Jitsi on another port and correspondingly provide this in the docker-compose.yml or even any other simple / better solution to this?

Thx - Andreas

**Comment by akemper** [comment]
Solution to support HTTP streaming has been rather simple like this:

    location / {
        proxy_buffering off;
        proxy_pass http://localhost:8000;
    }

**Comment by glatteis** [comment]
> Solution to support HTTP streaming has been rather simple like this:
> 
> ```
> location / {
>     proxy_buffering off;
>     proxy_pass http://localhost:8000;
> }
> ```

Dude you just saved my day!!!! :)

**Comment by aabeinsst** [comment]
All the links in this issue are outdated and i am struggeling with setting up OpenSlides behind a nginx reverse proxy. Is there maybe an expamle one could share or a useful source you could share?

**Comment by jsangmeister** [comment]
@peb-adr maybe you can help here?

**Comment by DerUtz** [comment]
I got this problem:

Using OpenSlides over HTTP 1.1 or lower is not supported. Make sure you can use HTTP 2 to continue.

Can anyone help?
