### ISSUE TITLE
Port 80

### ISSUE THREAD

**Issue by blinky0110** [OpenSlides/OpenSlides#5845]
Hello everybody,

how do I get Opensliders to run on port 80?

I'm using Ubuntu 20.4 server

**Comment by gsiv** [comment]
You can configure the port assigned to a particular instance by specifying `EXTERNAL_HTTP_PORT` in its `.env`.  Please be aware that it will be an HTTPS service no matter which port you configure.

**Comment by blinky0110** [comment]
Thank you
