### ISSUE TITLE
How to user youtube livestream

### ISSUE THREAD

**Issue by lukas-mc** [OpenSlides/OpenSlides#5859]
Tried to use the lates commit for youtube video as livestream url.

I can not get this running. I see che changes in my cloned git.  I  created a new image using docker-compose create.
I can run m3u8 livestream but no success with youtube...

I'm not clear what to use as url.
Used https://www.youtube.com/watch?v=someID and get Errors from video.js.....
1. Access to fetch at 'https://www.youtube.com/watch?v=someID' from origin 'https:/myhost.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2. GET https://www.youtube.com/watch?v=someID 504 (Gateway Timeout)
3. VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.

Think I'm wrong at some point.

Regards Lukas

**Comment by sanojkl** [comment]
the master only works with youtu.be links at the moment

**Comment by lukas-mc** [comment]
O, understand.... my stream is redirected to youtube.com so I get this ,, no compatible xource found" from videojs.

I will try a later version.

**Comment by tsiegleauq** [comment]
> I will try a later version.

Don't bother. This is most likely everything we will support regarding youtube.
What I need to get the embedded youtube-player to work is essentially the video-id. For easier usability I extract the VideoID from

> the master only works with youtu.be links at the moment

This is wrong. Both Browser URLs and Share URLs will work.
> https://www.youtube.com/watch?v=XXX
and
> https://youtu.be/YHtyKcmpyjI
should will both work.

**Comment by tsiegleauq** [comment]
@lukas-mc 
What I am suspicous about is that line:

> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.

It looks to me like you did not manage to update properly. The moment you enter any URL that includes `youtub.be` or `youtube.` vjs will not load.
https://github.com/OpenSlides/OpenSlides/blob/09bc7f093a8b628ef87653d626fdc8597df71501/client/src/app/shared/components/video-player/video-player.component.ts#L170-L176
