### ISSUE TITLE
Switch proxy to Caddy

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#5861]
We replaced haproxy with caddy. But there are a lot of old artifacts in the repo. For example the folder `haproxy` or that `make run-dev` creates a dockerfile for haproxy.

So the repo needs some cleanup

**Comment by ostcar** [comment]
This is not fixed. There is still the folder "haproxy"

**Comment by FinnStutzenstein** [comment]
Ahh, the `meta` and `OpenSlides 4` labels were not set - I thought this was an OS3 cleanup

**Comment by ostcar** [comment]
Sorry

**Comment by ostcar** [comment]
This seams to be fixed
