### ISSUE TITLE
User import preview group column empty

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#5873]
The user import preview group column does not show the _group names_. Nevertheless, groups are imported without any problems.

![image](https://user-images.githubusercontent.com/20415092/107238839-8e166300-6a28-11eb-9868-89e9f8dbe06e.png)

After successfully importing _group ID's_ are shown. I would prefer to see group names:

![image](https://user-images.githubusercontent.com/20415092/107238921-a5555080-6a28-11eb-8f72-c1beeb9bad34.png)

![image](https://user-images.githubusercontent.com/20415092/107376466-39d3b780-6aea-11eb-917b-dc27a5cb2912.png)

**Comment by emanuelschuetze** [comment]
Should be fixed in current master with #5823
