### ISSUE TITLE
Indicate user import duplicate error via tooltip

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#5878]
There is no indication when a user import fails due to being a duplicate.

This could easily be accomplished by adding another mat-icon to user-import-list.component.html:

![image](https://user-images.githubusercontent.com/20415092/107488397-976a1180-6b87-11eb-9956-bb6551333599.png)

**Comment by FinnStutzenstein** [comment]
Please create a PR if you already have the code right.

**Comment by tsiegleauq** [comment]
the importers are ... *well neglected*.

**Comment by jsangmeister** [comment]
fixed in new import
