### ISSUE TITLE
Error in documentation the proxy is not listening on ssl

### ISSUE THREAD

**Issue by lukas-mc** [OpenSlides/OpenSlides#5887]
**Describe the bug**
Installes acual version today.  Tried to connect using nginx proxy or haproxy and got ,,bad gateway"

**How to Reproduce**

Install openslides on localhost and try to connect https://localhost:8000 using a local browser.
You get a ,,Secure connection failed" error.

**Expected behavior**
The documentation states:
**OpenSlides runs on https://localhost:8000/.**

So I expected to connect using https.

So the documentation should state:

_OpenSlides runs on http://localhost:8000/._

**System information**

- OpenSlides-Version: 3.4-latest
- Additional version information (if any): cloned 2021.02.11
- Browser: any

**Additional context**

connecting plain http is working so far. 

So using haproxy in front of openslides and using http forward wil work. I changed proxy port to - "8000:8000" in docker-compose.yml to get this working and was not using nginx reverse proxy on the local host.

**Screenshots**

Regards Lukas

**Comment by FinnStutzenstein** [comment]
Hi, you are right, this does not work as it should. Since we have this new proxy since last week, there is still some work to do: https://github.com/OpenSlides/OpenSlides/issues/5889

I'm going to work on this next week.

**Comment by lukas-mc** [comment]
Ok, I see.
But I see more errors on a fresh install.
When I connect to the web interface, after a while I see ,,Offline" mode.
Could this also be result of the new proxy?

I adjusted docker-compose.yml at:
services:
proxy:
  ports:
      - "8000:8000"

So I can reverse proxy by using haproxy on the outside firewall to the docker-host  without the need to have nginx as reverse proxy on the docker-host itself.

And I see this in the logs:
proxy_1         | {"level":"error","ts":1613150983.676106,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}



I see this in firefox console:

Unknwon notify message 
{…}
​
error: {…}
​​
msg: "Ups, something went wrong!"
​​
type: "InternalError"
​​
<prototype>: Object { … }
​
<prototype>: {…}
​​
__defineGetter__: function __defineGetter__()
​​
__defineSetter__: function __defineSetter__()
​​
__lookupGetter__: function __lookupGetter__()
​​
__lookupSetter__: function __lookupSetter__()
​​
__proto__: 
​​
constructor: function Object()
​​
hasOwnProperty: function hasOwnProperty()
​​
isPrototypeOf: function isPrototypeOf()
​​
propertyIsEnumerable: function propertyIsEnumerable()
​​
toLocaleString: function toLocaleString()
​​
toString: function toString()​​
valueOf: function valueOf()
​​
<get __proto__()>: function __proto__()
​​
<set __proto__()>: function __proto__()
main-es2015.5b3db822e6326c53d541.js:1:1955983
startListening https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    messageHandler https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    handleMessage https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    subscription https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    __tryOrUnsub https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    next https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    _next https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    next https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    notifyNext https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    _next https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    next https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    c https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    invokeTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    onInvokeTask https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    invokeTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    runTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    invokeTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    p https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    h https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    (Async: EventListener.handleEvent)
    I https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    scheduleTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    onScheduleTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    scheduleTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    scheduleTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    scheduleEventTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    W https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    handle https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    _trySubscribe https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    subscribe https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    l https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    _innerSub https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    _tryNext https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    _next https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    next https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    n https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    _trySubscribe https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    subscribe https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    call https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    subscribe https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    p https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    subscribe https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    connectWithWrapper https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    n https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    S https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    n https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    connectWithWrapper https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    handleError https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    o https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    invoke https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    onInvoke https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    invoke https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    run https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    O https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    invokeTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    onInvokeTask https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    invokeTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    runTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    b https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    invokeTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    invoke https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    0 https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    (Async: setTimeout handler)
    s https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    scheduleTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    onScheduleTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    scheduleTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    scheduleTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    scheduleMacroTask https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    u https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    o https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    r https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    delayAndCheckReconnection https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    S https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    delayAndCheckReconnection https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    delayAndCheckReconnection https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    n https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    S https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    n https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    delayAndCheckReconnection https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    handleError https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    n https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    S https://omv.xxxx.org/polyfills-es2015.f065c3c97a69edde31b8.js:1
    n https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    handleError https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    connectWithWrapper https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    subscription https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    __tryOrUnsub https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1
    error https://omv.xxxx.org/main-es2015.5b3db822e6326c53d541.js:1

Regards Lukas

**Comment by FinnStutzenstein** [comment]
I'm not sure, what your setup exactly is. You need to make sure, that connections are not closed by your own proxy.

**Comment by lukas-mc** [comment]
Thanks for your replay,

Well I do have the same setup for a older setup, which we will use for a general meeting. I do not see this ,,offline" on that instance.  I now tried to use the newer version to get ,,,youtube" streaming as livestream running. 

What I also noticed was:

1. When the client got offline he can not reconnect to /autopilot  this will end up in endless ,,loading data". I can then connect to other pages.
Can I support with some logs or some else?

Regards Lukas

**Comment by FinnStutzenstein** [comment]
Hm, we fixed several things over the last days. Maybe try it again and update your instance.

**Comment by lukas-mc** [comment]
Hi Finn,

I have tested now...

This looks good to me.  I can access the youtube streams and also can access the instance using haproxy with ssl enabled (no ssl certificate check). Used the self singed certificate on caddy.

Great Thanks Regards Lukas
