### ISSUE TITLE
Work related to Caddy

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#5889]
TODOs:
- use `format console`, see https://caddyserver.com/docs/caddyfile/directives/log. @emanuelschuetze  and I both did not succeed in applying the config and get it working. It produces too much logs (at least during development). For the production @gsiv may want it to be reduced, too.
- Fix the ssl protocol error when deploying productive version. Currently http works, https gives the error.
- Add a configuration option to use http, https (self signed), https (provide custom cert)

**Comment by jsangmeister** [comment]
outdated
