### ISSUE TITLE
Persist Caddy data

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#5893]
From the dockerhub description (https://hub.docker.com/_/caddy?tab=description):

> However, it's very important to persist the data directory.

@ostcar @gsiv Is it necessary (The warning seems to be really important)? Did you care about this?

**Comment by ostcar** [comment]
I did not know about it.

But it does not seem necessary in our case. If I understand correctly, it is only necessary for TLS data. We don't use TLS with caddy

**Comment by FinnStutzenstein** [comment]
> We don't use TLS with caddy

Not in our own prod setup, but we support it for other users

**Comment by gsiv** [comment]
> > We don't use TLS with caddy
> 
> Not in our own prod setup, but we support it for other users

I concur with @ostcar; I don't see why we would need to persist the data directory.

I must admit, though, that I'm also unaware of how other users would go about enabling TLS.  To me, it looks like they would need to customize the provided Caddyfile and build a new image.

Granted, it would be nice to include an example TLS setup with a note saying that, when enabling TLS, Caddy's data directory must be persisted.

**Comment by FinnStutzenstein** [comment]
This is the basic https setup: https://github.com/OpenSlides/OpenSlides/pull/5894

It should be sufficient for other users to quikcly use https and provides enough flexibility I think.

**Comment by FinnStutzenstein** [comment]
> Granted, it would be nice to include an example TLS setup with a note saying that, when enabling TLS, Caddy's data directory must be persisted.

Ok, I'll add it there.
