### ISSUE TITLE
Optional deposit of by-laws, rules of order and by-laws requests for specific paragraphs and/or sections

### ISSUE THREAD

**Issue by Lukas2112** [OpenSlides/OpenSlides#5954]
In the current version of OpenSlides, it is already possible to store bylaws. The same functionality might be useful for the rules of procedure. Unfortunately, as far as I can see, it does not work in the current version of OpenSlides that motions for bylaws and rules of procedure can be based on specific paragraphs and/or subparagraphs. This would perhaps make the workflow even easier for committees that (want to) use OpenSlides.

**Comment by tsiegleauq** [comment]
Try to stick to the issue template.

In what way are bylaws different to rules of procedure? OpenSlides supports what we call "statute paragraphs". From what I see you require the same feature with a different title. Using custom translations you can rename every part of OpenSlides in runtime.

**Comment by Lukas2112** [comment]
For example, there is a general meeting of a non-profit association. This has its own rules of procedure. The potential I see would be that first the rules of procedure of body X could be entered and then motions for explicit paragraphs could be made.
