### ISSUE TITLE
build prod 3 and 4 on the same machine

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#5955]
**Describe the bug**
If you develop on os3 and os4 and run the build-script on both, you can container with the same name.

For example, the name "openslides-autoupdate-service" is used for the os3-autoupdate-serve and for the os4-autoupdate-service.

The funny result is, that when you start os4, it is possible, that os3 container are started.

If would be helpful, that the build-script in os3 adds a prefix to all(?) containers.

**Comment by FinnStutzenstein** [comment]
This only affects productive images, right?

**Comment by ostcar** [comment]
Yes

**Comment by FinnStutzenstein** [comment]
Hm, I'm somewhat conflicted:
- The os3 dev containers have os3 as prefix, so the os3 prod containers could have the same naming scheme
- This would interfere with our productive setup and would require to change every instance

I would propose to consequently name OS4 images `openslides4-<service>(-dev)`. This would make the image tags unique and allows in our prod setup to differentiate between images, if we are going to have the first instances.

**Comment by normanjaeckel** [comment]
The problem is that we may change the major version number to 5 or 6 without changing the image structure. So we may use openslides4 images for OpenSlides 5.x which might be confusing. When we established the new repositores we decided against attending the version number to the repo names (openslides-backend) and not openslides4-backend. I also proposed the name of a nice animal which was rejected by @emanuelschuetze .

**Comment by normanjaeckel** [comment]
Maybe just rename the openslides 3 autoupdate image. This is the only one that interferes here, right?

**Comment by FinnStutzenstein** [comment]
I spoke with @gsiv and we came to the conclusion, that equal image names are fine and also ok for our productive setup. Instead, you have to set your tags right. For convenience I'll change the default tag for OS4 to latest-4 in an upcomming PR.

**Comment by ostcar** [comment]
This is not relevant anymore
