### ISSUE TITLE
Custom "Enter live conference" URL

### ISSUE THREAD

**Issue by Paul-1986** [OpenSlides/OpenSlides#5959]
It would be great to have an "Enter live conference" URL custom field in the settings. A new window opens with the custom URL and the Livestream window closes after clicking the "Enter live conference" button.

Other video conferencing solutions than Jitsi can be integrated in this way.

**Comment by tsiegleauq** [comment]
Try to stick to the issue template.

> It would be great to have an "Enter live conference" URL custom field in the settings.

Currently we do not want users to change the Live Conference URL at runtime. That might change in the future, especially to allow the usage of multiple rooms.

> A new window opens with the custom URL and the Livestream window closes after clicking the "Enter live conference" button.

Connecting the Live Conference to the Current List Of Speakers was the main motivation here.
If you need to forward your users to an external live conference, simply put the link on the start page of OpenSlides.

Integrating other WebRTC based conferencing solutions has been considered, but did currently not justify the effort.

**Comment by Paul-1986** [comment]
> > A new window opens with the custom URL and the Livestream window closes after clicking the "Enter live conference" button.
> 
> Connecting the Live Conference to the Current List Of Speakers was the main motivation here.
> If you need to forward your users to an external live conference, simply put the link on the start page of OpenSlides.

That's an option. But it would be better if the user does not have to leave the autopilot to join the video conference (Zoom, GoToMeeting, ...) and can only join if he / she is on the Current List Of Speakers. For better understanding, the idea is to set up the following setting: streaming the video conference with OBS or built-in live streaming function (available with zoom) on YouTube (https://github.com/OpenSlides/OpenSlides/pull/5770), joining only if you want to speak.

**Comment by rasos** [comment]
Agree to prefer Jitsi integration and remain open source and GDPR compliant that way. As Europeans we probably prefer to host Jitsi ourself,  [search for a free service](https://jitsi.github.io/handbook/docs/community/community-instances) hosted in the EU or embed a professional Jitsi Meet service provider (fairmeeting, ...).

**Comment by Paul-1986** [comment]
It is just an additional way to integrate third party video conference software, not a replacement. It is a decision of the organization, which video conference software the members prefer...

**Comment by emanuelschuetze** [comment]
We use Jitsi integration only for our video conference use cases - also in OS4. Closed.
