### ISSUE TITLE
Cache not Ready

### ISSUE THREAD

**Issue by pedda4711** [OpenSlides/OpenSlides#5964]
Hello, 
i've build all based on the master branch from today (Fedora 33). All container start, but i can not login.
I've not set admin password, so i can use the default admin:admin.

The console show always this error(?):
autoupdate_1    | 2021/03/18 12:04:02 Cache not ready. Try again in 3 seconds
autoupdate_1    | 2021/03/18 12:04:05 Cache not ready. Try again in 3 seconds

What can i do become the cache ready?

Greetings,

Peter

**Comment by FinnStutzenstein** [comment]
Hi, I suppose you are using the productive setup as described in the readme? What do the logs for `server` say? (e.g. `docker-compose logs server`)

**Comment by pedda4711** [comment]
server_1        | ERROR: Django secret key undefined!  Cannot continue.
server_1        | /usr/local/sbin/entrypoint: line 6: /run/secrets/django: Permission denied
server_1        | ERROR: Django secret key undefined!  Cannot continue.
server_1        | /usr/local/sbin/entrypoint: line 6: /run/secrets/django: Permission denied
server_1        | ERROR: Django secret key undefined!  Cannot continue.
server_1        | ERROR: Django secret key undefined!  Cannot continue.
server_1        | /usr/local/sbin/entrypoint: line 6: /run/secrets/django: Permission denied
server_1        | /usr/local/sbin/entrypoint: line 6: /run/secrets/django: Permission denied
server_1        | ERROR: Django secret key undefined!  Cannot continue.
server_1        | /usr/local/sbin/entrypoint: line 6: /run/secrets/django: Permission denied

The file i created based on the install description is secrets/django.env

**Comment by FinnStutzenstein** [comment]
> /run/secrets/django: Permission denied

Secrets are mounted into the containers. Make sure that the docker daemon can access your secret on the host machine.

**Comment by pedda4711** [comment]
Hmm.  

now i compose as root instead of my docker user.
docker-compose rm
docker-compose up
same problem.

which container is  setting the path to /run/secrets/django to secrets first?
(the  file secrets/adminsecret.env is loaded fine. without this file, there are more errors)

**Comment by pedda4711** [comment]
i've connect the container docker_autoupdate_1  and went into the path /run/secrets:

/run/secrets # ls -alt
ls: ./django: Permission denied
total 0
drwxr-xr-x    2 root     root            20 Mar 18 15:01 .
drwxr-xr-x    1 root     root            21 Mar 18 15:01 ..
/run/secrets #

**Comment by FinnStutzenstein** [comment]
Which user are you inside the docker container?

**Comment by pedda4711** [comment]
ah. ok. in this test i was my docker-user not root
now i'will test it also as root.

**Comment by pedda4711** [comment]
also as root, permission denied

**Comment by pedda4711** [comment]
in my environment, i normaly do anything as docker-user

git, compile startup, create secrets and so on.
the container start as docker-user with the same rights as the files i created.

So i think, the path to secrets in the container is missing or wrong

**Comment by FinnStutzenstein** [comment]
I assume, that you did create the `secrets/django.env` in the docker folder, right?

**Comment by pedda4711** [comment]
yes (the username is slider)
The full path is /opt/slider/OpenSlides/docker
/opt/slider is the home-directory of user slider
I have set chmod 777 to docker.env, but this does not help

[slider@fc-docker01 ~/OpenSlides/docker]$ ls
build.sh  docker-compose.dev.yml  docker-compose.yml  docker-compose.yml.m4  docker-stack.yml.m4  postgresql.dev.conf  secrets
[slider@fc-docker01 ~/OpenSlides/docker]$ ls -l secrets/
insgesamt 20
-rw-r--r--. 1 slider docker 152 18. Mär 12:22 adminsecret.env
-rw-r--r--. 1 slider docker 152 18. Mär 09:30 adminsecret.env.example
-rwxrwxrwx. 1 slider docker  85 18. Mär 12:24 django.env
-rwxrwxrwx. 1 slider docker 132 18. Mär 09:30 django.env.example
-rw-r--r--. 1 slider docker 198 18. Mär 09:30 usersecret.env.example

**Comment by pedda4711** [comment]
I've do another fresh install and pipe the build.sh all output to file.
At step 11/19 an django-File created.
Is it possible that this file has the wrong permission?


-------------------------------------------------
Step 8/19 : RUN go build ./cmd/autoupdate
 ---> Running in 4ff2bfb7b040
Removing intermediate container 4ff2bfb7b040
 ---> 6f6a05a53f4e
Step 9/19 : FROM builder as development
 ---> 6f6a05a53f4e
Step 10/19 : RUN mkdir -p /run/secrets
 ---> Running in 1086a992acfb
Removing intermediate container 1086a992acfb
 ---> 50427b4fa96a
Step 11/19 : RUN echo "DJANGO_SECRET_KEY='development'" > /run/secrets/django
 ---> Running in 59112552494f

**Comment by pedda4711** [comment]
Hello Finn, 
this problem is fixed. I've disabled selinux complete. 
The bind volumes must mounted with :z flag if selinux is on
https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label

**Comment by FinnStutzenstein** [comment]
Ok, glad you found the issue!

**Comment by pedda4711** [comment]
Hello Finn,

another fresh install from master this morning (All docker-containers removed --- systemctl stop docker; rm -fr /var/lib/docker/*; systemctl start docker; rm -fr OpenSlides, net git clone..... django.env is set, adminsec.env also set),
all other settings default, without change anything.

New errors:

server-setup_1  | [2021-03-19 08:40:24 +0100] [31] [INFO] openslides.utils.redis_connection_pool [VdfI] CONNECTION_POOL_LIMIT=100
server-setup_1  | [2021-03-19 08:40:24 +0100] [31] [INFO] openslides.utils.redis [VdfI] Redis address redis://redis:6379/0
server-setup_1  | [2021-03-19 08:40:24 +0100] [31] [INFO] openslides.utils.redis [VdfI] Redis read only address redis://redis-slave:6379/0
server-setup_1  | [2021-03-19 08:40:24 +0100] [31] [INFO] openslides.utils.stream [VdfI] Redis stream maxlen None
server-setup_1  | [2021-03-19 08:40:24 +0100] [31] [INFO] openslides.mediafiles.models [VdfI] Using a standalone mediafile database
server-setup_1  | [2021-03-19 08:40:24 +0100] [31] [INFO] openslides.mediafiles.views [VdfI] Using a standalone mediafile database
server-setup_1  | Operations to perform:
server-setup_1  |   Apply all migrations: agenda, assignments, auth, chat, contenttypes, core, mediafiles, motions, sessions, topics, users
server-setup_1  | Running migrations:
server-setup_1  | [2021-03-19 08:40:24 +0100] [31] [WARNING] openslides.utils.redis [VdfI] Redis Exception: . Do not reuse connection...
server-setup_1  | [2021-03-19 08:40:24 +0100] [31] [WARNING] openslides.utils.cache_providers [VdfI] Redis was flushed before method 'get_collection_data'. Ensures cache now.
server-setup_1  | [2021-03-19 08:40:24 +0100] [31] [INFO] openslides.utils.cache [VdfI] Building config data and resetting cache...
server-setup_1  | [2021-03-19 08:40:24 +0100] [31] [INFO] openslides.utils.models [VdfI] Loading core/config
server-setup_1  | [2021-03-19 08:40:24 +0100] [31] [WARNING] openslides.utils.redis [VdfI] Redis Exception: ('MultiExecError errors:', [ValueError('args[0] is empty dict')]). Do not reuse connection...
server-setup_1  | Traceback (most recent call last):
server-setup_1  |   File "/app/openslides/utils/cache_providers.py", line 473, in eval
server-setup_1  |     result = await redis.evalsha(hash, keys, args)
server-setup_1  | aioredis.errors.ReplyError: cache_reset
server-setup_1  | During handling of the above exception, another exception occurred:
server-setup_1  | Traceback (most recent call last):
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 339, in thread_handler
server-setup_1  |     raise exc_info[1]
server-setup_1  |   File "/app/openslides/utils/cache_providers.py", line 101, in wrapped
server-setup_1  |     result = await func(cache_provider, *args, **kwargs)
server-setup_1  |   File "/app/openslides/utils/cache_providers.py", line 358, in get_collection_data
server-setup_1  |     read_only=True,
server-setup_1  |   File "/app/openslides/utils/cache_providers.py", line 478, in eval
server-setup_1  |     raise CacheReset()
server-setup_1  | openslides.utils.cache_providers.CacheReset
server-setup_1  | During handling of the above exception, another exception occurred:
server-setup_1  | Traceback (most recent call last):
server-setup_1  |   File "manage.py", line 11, in <module>
server-setup_1  |     exit(main())
server-setup_1  |   File "/app/openslides/__main__.py", line 41, in main
server-setup_1  |     execute_from_command_line(sys.argv)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
server-setup_1  |     utility.execute()
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
server-setup_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
server-setup_1  |     self.execute(*args, **cmd_options)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
server-setup_1  |     output = self.handle(*args, **options)
server-setup_1  |   File "/app/openslides/core/management/commands/migrate.py", line 25, in handle
server-setup_1  |     super().handle(*args, **options)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
server-setup_1  |     res = handle_func(*args, **kwargs)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
server-setup_1  |     fake_initial=fake_initial,
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
server-setup_1  |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
server-setup_1  |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
server-setup_1  |     state = migration.apply(state, schema_editor)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
server-setup_1  |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
server-setup_1  |     schema_editor.alter_field(from_model, from_field, to_field)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 535, in alter_field
server-setup_1  |     old_db_params, new_db_params, strict)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/schema.py", line 124, in _alter_field
server-setup_1  |     new_db_params, strict,
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 649, in _alter_field
server-setup_1  |     new_default = self.effective_default(new_field)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 233, in effective_default
server-setup_1  |     return field.get_db_prep_save(self._effective_default(field), self.connection)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 212, in _effective_default
server-setup_1  |     default = field.get_default()
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 801, in get_default
server-setup_1  |     return self._get_default()
server-setup_1  |   File "/app/openslides/agenda/models.py", line 364, in list_of_speakers_initially_closed
server-setup_1  |     return config["agenda_list_of_speakers_initially_closed"]
server-setup_1  |   File "/app/openslides/core/config.py", line 54, in __getitem__
server-setup_1  |     self.get_collection_string(), self.get_key_to_id()[key]
server-setup_1  |   File "/app/openslides/core/config.py", line 62, in get_key_to_id
server-setup_1  |     async_to_sync(self.build_key_to_id)()
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 147, in __call__
server-setup_1  |     return call_result.result()
server-setup_1  |   File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
server-setup_1  |     return self.__get_result()
server-setup_1  |   File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
server-setup_1  |     raise self._exception
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 212, in main_wrap
server-setup_1  |     result = await self.awaitable(*args, **kwargs)
server-setup_1  |   File "/app/openslides/core/config.py", line 83, in build_key_to_id
server-setup_1  |     self.get_collection_string()
server-setup_1  |   File "/app/openslides/utils/cache.py", line 257, in get_collection_data
server-setup_1  |     collection
server-setup_1  |   File "/app/openslides/utils/cache_providers.py", line 107, in wrapped
server-setup_1  |     await cache_provider.ensure_cache()
server-setup_1  |   File "/app/openslides/utils/cache_providers.py", line 278, in ensure_cache
server-setup_1  |     await self._ensure_cache()
server-setup_1  |   File "/app/openslides/utils/cache.py", line 107, in async_ensure_cache
server-setup_1  |     await self.build_cache(default_change_id)
server-setup_1  |   File "/app/openslides/utils/cache.py", line 131, in build_cache
server-setup_1  |     default_change_id=default_change_id, schema_version=schema_version
server-setup_1  |   File "/app/openslides/utils/cache.py", line 151, in _build_cache
server-setup_1  |     await self.cache_provider.reset_full_cache(config_mapping, change_id)
server-setup_1  |   File "/app/openslides/utils/cache_providers.py", line 301, in reset_full_cache
server-setup_1  |     await tr.execute()
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/aioredis/commands/transaction.py", line 180, in execute
server-setup_1  |     return_exceptions=return_exceptions)
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/aioredis/commands/transaction.py", line 299, in _do_execute
server-setup_1  |     return (await self._gather_result(return_exceptions))
server-setup_1  |   File "/usr/local/lib/python3.7/site-packages/aioredis/commands/transaction.py", line 201, in _gather_result
server-setup_1  |     raise self.error_class(errors)
server-setup_1  | aioredis.errors.MultiExecError: ('MultiExecError errors:', [ValueError('args[0] is empty dict')])

**Comment by sknopp** [comment]
hi, i've got the same error as @pedda4711 on a fresh server with a new untouched docker installation. I would be very interested in a solution too!

**Comment by FinnStutzenstein** [comment]
Lets keep track in #5974
