### ISSUE TITLE
Do not require the db-setup container to hang around forever

### ISSUE THREAD

**Issue by neumantm** [OpenSlides/OpenSlides#6020]
**Is your feature request related to a problem? Please describe.**
I think it is bad design to have the db-setup container hang around forever serving an empty dir.

**Describe the solution you'd like**
I'd prefer if the successful completion of the db-setup could be checked in another way.

One possibility would be to use a container-orchestration feature for this.
In kubernetes init-containers would be appropriate. Docker-compose also just recently added a similar feature: https://github.com/docker/compose/issues/6855

**Describe alternatives you've considered**
Another possibility would be to check for the existence of some database table or something in the server entrypoint.
(Instead of waiting for the port 8000 on the db-setup container) 

**Additional context**
Relevant lines: 
https://github.com/OpenSlides/OpenSlides/blob/4f35770769eeb71c22935a885bf82534a2be8934/server/docker/entrypoint-db-setup#L82
https://github.com/OpenSlides/OpenSlides/blob/4f35770769eeb71c22935a885bf82534a2be8934/server/docker/entrypoint#L17

**Comment by gsiv** [comment]
> In kubernetes init-containers would be appropriate. Docker-compose also just recently added a similar feature: [docker/compose#6855](https://github.com/docker/compose/issues/6855)

Unfortunately, at openslides.com we're not quite ready to switch away from Swarm, so at least I'm personally not convinced quite yet. :)

For now, I would be happy to look at alternatives that work with Swarm though.  I imagine it could even be as simple as `exit 0` in combination with the correct `restart_policy`.

For the longer term, thanks for pointing out init containers.

> Another possibility would be to check for the existence of some database table or something in the server entrypoint.
> (Instead of waiting for the port 8000 on the db-setup container)

Well, it kind of used to work that way but it wasn't sufficient.

If I remember correctly, the main reason for introducing the specialized `server-setup` service was to avoid race conditions.  By never scaling `server-setup` beyond 1 and letting it handle the setup we can also spawn multiple `server` containers without having them all try to do database migrations simultaneously.

This is certainly a workaround.  A more elegant solution would probably use database locks but I don't know how feasible changing that would be.

**Comment by FinnStutzenstein** [comment]
Yes, init containers sounds right. If it is fully released (I didn't checked the status) someone can try it out.

**Comment by neumantm** [comment]
> Unfortunately, at openslides.com we're not quite ready to switch away from Swarm, so at least I'm personally not convinced quite yet. :)

As I understand, the mentioned docker-compose feature is also available in docker swarm.

**Comment by gsiv** [comment]
> As I understand, the mentioned docker-compose feature is also available in docker swarm.

I don't think so.  From what I understand, the feature is implemented as a new condition `service_completed_successfully` to `depends_on`, cf. https://github.com/compose-spec/compose-spec/blob/master/spec.md#depends_on.  `depends_on` is, unfortunately, not supported by Docker Swarm.
