### ISSUE TITLE
Welcome Mail with more variables

### ISSUE THREAD

**Issue by kaffeeringe** [OpenSlides/OpenSlides#6022]
When I send the invite to my users I can use several variables:

- event_name
- url
- username
- password

I don't know if it is already possible but it would be useful for me to be able to use "groups". So they know why they got this mail. people seem to be confused when they aren't delegates...

**Comment by FinnStutzenstein** [comment]
If someone wants to do this, groups can be added here: https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/users/models.py#L252

**Comment by peb-adr** [comment]
We picked up this on this idea. This will be worked on in https://github.com/OpenSlides/openslides-backend/issues/2634 from now on.
