### ISSUE TITLE
Diff View: Amendments in lists are showing to many changes in main motion

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#6030]
**Describe the bug**
Amendments in lists (ul, ol), which otherwise appear fine, show too many changes in the main motion.
They appear correctly in the scope of their own amendment-detail-view tho. 

**How to Reproduce**

1. Create a new motion (Screenshot 1)
```html
<p>Mein Text</p>
<ul>
<li>Eins</li>
<li>Zwei</li>
<li>Drei</li>
<li>Vier</li>
</ul>
```
2. Create an amendment of line 2
```html
<ul>
<li>Eins One</li>
</ul>
```
3. The amendment looks fine on it's own (Screenshot 2)
4. The motion with the amendment does not (Screenshot 4)

**Expected behavior**
The appearance of an amendment in the main motion should be the same as in their corresponding amendment detail view.

**System information**

- OpenSlides-Version: 3,4 master
- Device: all
- OS: all
- Browser: Chrome, FF
- Browser-Version: current

**Screenshots**

How motion as is
![image](https://user-images.githubusercontent.com/10233032/116089709-68057400-a6a3-11eb-8cf1-e034981ade93.png)

The amendment:
![image](https://user-images.githubusercontent.com/10233032/116089781-7a7fad80-a6a3-11eb-9e3c-2921c2f920f4.png)

The Error: How the amendment was rendered in the main motion:
![image](https://user-images.githubusercontent.com/10233032/116089851-8a978d00-a6a3-11eb-8fe4-4134b5bb2b22.png)

**Comment by CatoTH** [comment]
Here is an attempt to fix this, including a disclaimer: https://github.com/OpenSlides/OpenSlides/pull/6047
