### ISSUE TITLE
Build.sh takes more than one hour

### ISSUE THREAD

**Issue by fabianschurz** [OpenSlides/OpenSlides#6033]
**Describe the bug**
I'm running the build.sh script for over one hour now and the finish line still seems far away.

**How to Reproduce**
Run the build.sh script

**Expected behavior**
Build that takes less than one hour

**Additional context**
I'm running the build in a gitlab ci. The job fails because the execution took longer than 1h0m0s seconds. The reason why the build takes so long is that the `apt upgrade` command is run in every docker build. In my opinion (building software and using docker for some years now) `apt upgrade` shouldn't be run if there is no special need for it - maybe there is, just correct me on that :)

**Comment by FinnStutzenstein** [comment]
Which container(s) took so long? In my experience most parts are quite "fast" (like 10-15 mins), but building the client can take a huge amount of time.

**Comment by tsiegleauq** [comment]
> I'm running the build in a gitlab ci.

That is probably the culprit. This will not be supported (during version 3 at least). For version 4 we might provide images ourselves.

**Comment by fabianschurz** [comment]
Every build that does an apt upgrade takes it's time. The gitlab ci does not matter. Local it's the same. Gitlab also just runs a docker build ^^. 

I guess providing images vie docker hub would be awesome and really helpful.

For now i think this issue can be closed then. My "solution" idea would be to use latest base images and not doing an apt upgrade inside the build.
