### ISSUE TITLE
Error with "docker-compose up"

### ISSUE THREAD

**Issue by VaultKid** [OpenSlides/OpenSlides#6059]
**Describe the bug**
The command `# docker-compose up` fails with the following error message:

```
Pulling client (openslides/openslides-client:latest)...

ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. 
Consider backing up your data before continuing.

Continue with the new image? [yN]
```

**How to Reproduce**

1. git clone https://github.com/OpenSlides/OpenSlides.git --recurse-submodules
2. cd docker
3. ./build.sh all
4. create/modify secret files 
5. m4 docker-compose.yml.m4 > docker-compose.yml
6. docker-compose up

**Expected behavior**
OpenSlides is accessible on http://localhost:8000/ (or https, if configured).

**System information**

- OpenSlides-Version: master (as of 09.05.2021)
- Python Version: 3.9
- Docker Version 20.10.4
- Docker-Compose Version 1.29.1
- Device: VM provided by my university
- OS: Windows Server 2019

**Additional context**
A similar issue was opened in February, but the problem solving methods there (correcting the forgotten "all" in "./build.sh all" or changing the version of the go language in `autoupdate/Docker`) didn't help me to solve my issue.
-> https://github.com/OpenSlides/OpenSlides/issues/5883

**Comment by FinnStutzenstein** [comment]
Hi, the steps seems right. Since docker compose cannot find the client image, maybe try to build it again. Maybe something happend during the build: `./build.sh client`.

**Comment by tsiegleauq** [comment]
> openslides/openslides-client:latest

That is odd. openslides-client is a part of OpenSlides4, OpenSlides3, which you are supposed to use, has no dedicated client image. You were therefore not cloning `git clone https://github.com/OpenSlides/OpenSlides.git`, make sure you are on master 3.4 and try again.

**Comment by FinnStutzenstein** [comment]
No, OS3 also has a client image: https://github.com/OpenSlides/OpenSlides/blob/master/docker/docker-compose.yml.m4#L25

**Comment by tsiegleauq** [comment]
interesting. Thought the whole packe is one thing plus the autoupdate

**Comment by VaultKid** [comment]
> 
> 
> Hi, the steps seems right. Since docker compose cannot find the client image, maybe try to build it again. Maybe something happend during the build: `./build.sh client`.

I tried building just the client, but it didn't help. I made a screenshot of the console window poping up (there was some other text afterwards, that I couldn't screenshot due the window closing so fast):
![grafik](https://user-images.githubusercontent.com/32182528/117685536-8db37280-b1a5-11eb-96e0-608771d3986f.png)

**Comment by tsiegleauq** [comment]
That would probably be helpful. We usually build from linux. Manually navigating to your openslides dir should not close the windows tho, you are probably running automatic scripts?

**Comment by VaultKid** [comment]
Alright, I gonna try the WSL then. Do I understand right, that I need to install Docker inside of the WSL then before building?

**Comment by FinnStutzenstein** [comment]
I do not know about WSL and docker, but what you told above

> (there was some other text afterwards, that I couldn't screenshot due the window closing so fast)

sounds like an error. In normal operation, there will be more text, but this takes several minutes. I assume, that it aborts with an error and the image is not built. So in the next step, the image cannot be found. With WSL you might have a change of seeing the error.

**Comment by VaultKid** [comment]
So right now I am running docker from windows and tried `./build.sh all` inside of WSL (Ubuntu 18.04 with docker-ce installed), which output this:

```
Building openslides/openslides-repmgr:latest...
free(): invalid pointer
SIGABRT: abort
PC=0x7fe4dc44efb7 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc42004fcc0, 0xc42004fce8)
        /usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc42004fc90 sp=0xc42004fc50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x1a90d80)
        github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc42004fcc0 sp=0xc42004fc90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x1a90d80)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc42004fcf8 sp=0xc42004fcc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc420014370)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc42004fda0 sp=0xc42004fcf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc42004fe88, 0x410022, 0xc4200142c0)
        <autogenerated>:4 +0x46 fp=0xc42004fde0 sp=0xc42004fda0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc42004fe68 sp=0xc42004fde0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7fffd6f8b617, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc42004fed8 sp=0xc42004fe68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc42004ff58 sp=0xc42004fed8
main.main()
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc42004ff88 sp=0xc42004ff58
runtime.main()
        /usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc42004ffe0 sp=0xc42004ff88
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42004ffe8 sp=0xc42004ffe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7fffd6f8b0c0
rcx    0x8
rdx    0x0
rdi    0x2
rsi    0x7fffd6f8ae50
rbp    0x7fffd6f8b1c0
rsp    0x7fffd6f8ae50
r8     0x0
r9     0x7fffd6f8ae50
r10    0x8
r11    0x8
r12    0x7fffd6f8b0c0
r13    0x1000
r14    0x0
r15    0x30
rip    0x7fe4dc44efb7
rflags 0x246
cs     0x33
fs     0x53
gs     0x2b
Sending build context to Docker daemon  36.86kB
Step 1/23 : FROM debian:buster
buster: Pulling from library/debian
no matching manifest for windows/amd64 10.0.17763 in the manifest list entries
```
Internet recommends to enable the experimental mode in docker or switching to linux container mode. Both suggestions didn't help to solve my problem unfortunatly. Maybe it's an issue with running WSL 1. WSL 2 is not possible with my machine unfortunately.

**Comment by FinnStutzenstein** [comment]
It seems like it is a problem with docker itself. Unfortunately, we cannot help there.

You can try building your images somewhere else and move them to your windows machine. Or wait for https://github.com/OpenSlides/OpenSlides/pull/6058 where prebuild images are uploaded to github's docker registry.
