### ISSUE TITLE
Fix models validator bugs

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/OpenSlides#6061]
see https://github.com/OpenSlides/OpenSlides/pull/6052/

**Comment by jsangmeister** [comment]
See also https://github.com/OpenSlides/OpenSlides/pull/6062

**Comment by FinnStutzenstein** [comment]
Check for all fields, e.g. `descriptin` is a spelling mistake for `mediafile/filename` which is not caught.

**Comment by jsangmeister** [comment]
Also, it must be ensured that for template relation fields the field-related attributes are actually set on the field level and not on the template level. See https://github.com/OpenSlides/OpenSlides/pull/6162
