### ISSUE TITLE
Documentaion how to analyze / speed up performance of Docker install

### ISSUE THREAD

**Issue by roadrunnerjb** [OpenSlides/OpenSlides#6064]
Hi,
my first post here. 

We are running openslides 2.x instances since sept 2020 and switched to 3.4 docker setup in jan 2021.

Docker setup is implemented in a KVM VM with 4 VCPU's and 4 GB memory.

Host is behind an apache reverse proxy and an internet connection with 1 Gbit down 50 Mbit upload.

We did a meeting with about 60 participants. With every vote we had to wait for several minutes to get all votes counted.

In the proxy logs I find the following:

proxy_http:error] [pid 7959:tid 140485017335552] (70007)The timeout specified has expired:

May be this is a hint for something is too slow in the openslides vm. But no glue what.

If we add more ressources to the vm what to configure in docker / openslides ... to speed up this instance ?

Any ideas, links to docs, ... are welcome

Regards
Joachim

**Comment by tsiegleauq** [comment]
> With every vote we had to wait for several minutes to get all votes counted.

Yes, voting is slow. This is well a well known ... "thing".

**Comment by roadrunnerjb** [comment]
Hi,
what do you mean with:
"Actually I am surprised you can build the client with so little ram"
The vm memory. It's no issue to give the VM more ram but giving ram is one thing the other thing is to telle the components to use it. When I look on hypervisor level only 50% of ram is ever used.

Do you have some suggestions ? They are really welcome...

Same thing with autopilot users complain about beeing slow even with oonly 10 participants.

**Comment by jsangmeister** [comment]
outdated
