### ISSUE TITLE
 OpenSlidesProxy (Caddy) stuck at reboot: Caddyfile: /etc/caddy/Caddyfile:20 - Error during parsing: Unexpected EOF

### ISSUE THREAD

**Issue by maltsero** [OpenSlides/OpenSlides#6071]
> Hello, 

Any advices for: 
**Caddyfile: /etc/caddy/Caddyfile:20 - Error during parsing: Unexpected EOF after docker-compose stop / start ???**

Openslides does not work with Proxy Container after reboot or stop.

**Describe the Problem:**
After build with ./build.sh all and install certs and create the docker-compose.yml and do a docker-compose up the Proxy first started well, after a reboot the container stuck and wont boot. 
Caddyfile: /etc/caddy/Caddyfile:20 - Error during parsing: Unexpected EOF

**How to Reproduce**
- OS System: Debian Buster 10 
- Install docker with docker-compose
- Clone https://github.com/OpenSlides/OpenSlides.git --recurse-submodules
- cd docker & ./build.sh all ( Readme.rst ) 
- docker-compose up -> it works! And then reboot
- docker-compose stop 
- doker-compose start
- docker-compose ps 
- Proxy Container (EXIT) with current log:

*Log (Proxy_OpenSldies) (Caddy) - stuck at 2nd start:**
`Configured https
All hosts allowed
{"level":"info","ts":1621589464.1111493,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
2021/05/21 09:31:04 [WARNING] No files matching import glob pattern: invalid_host*
2021/05/21 09:31:04 [WARNING] No files matching import glob pattern: redirect*
{"level":"info","ts":1621589464.114204,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
{"level":"info","ts":1621589464.1154115,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00032f420"}
{"level":"warn","ts":1621589464.1202776,"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [localhost]: no OCSP server specified in certificate"}
{"level":"info","ts":1621589464.1204474,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1621589464.1219966,"logger":"tls","msg":"cleaned up storage units"}
{"level":"info","ts":1621589464.1223342,"msg":"autosaved config","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1621589464.1223524,"msg":"serving initial configuration"}
{"level":"info","ts":1621589617.492956,"msg":"shutting down apps then terminating","signal":"SIGTERM"}
{"level":"info","ts":1621589618.5005355,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc00032f420"}
{"level":"info","ts":1621589619.0008929,"logger":"admin","msg":"stopped previous server"}
{"level":"info","ts":1621589619.000929,"msg":"shutdown done","signal":"SIGTERM"}`
- shutdown container with docker-compose stop

- start container with docker-compose start 
- following error caddy: 

`Configured https
All hosts allowed
{"level":"info","ts":1621589685.2459145,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
2021/05/21 09:34:45 [WARNING] No files matching import glob pattern: invalid_host*
2021/05/21 09:34:45 [WARNING] No files matching import glob pattern: redirect*
run: adapting config using caddyfile: /etc/caddy/endpoint:3: unrecognized directive: https://:8001`

- After try start manually
`Configured https
All hosts allowed
{"level":"info","ts":1621592599.4638484,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
2021/05/21 10:23:19 [WARNING] No files matching import glob pattern: invalid_host*
2021/05/21 10:23:19 [WARNING] No files matching import glob pattern: redirect*
**run: adapting config using caddyfile: /etc/caddy/Caddyfile:20 - Error during parsing: Unexpected EOF**`

- Complete docker-compose logs
https://pastebin.com/vWCyV0kH

**Comment by FinnStutzenstein** [comment]
Thanks for the report. The auto-generated config files were appended to, so after a second starts (The entrypoints runs again), the config is duplicated which leads to syntax errors. Not the files are overwritten: #6083
