### ISSUE TITLE
Error during server setup

### ISSUE THREAD

**Issue by bananakaba** [OpenSlides/OpenSlides#6104]
**Describe the bug**
When starting the containers with `docker-compose up`, the inital setup of the postgres cluster exits with code 1.
Bringing all containers down with `docker-compose down` and just trying to start pgnode1 with `docker-compose up pgnode` following information is printed:

> Creating network "docker_back" with the default driver
> Creating network "docker_dbnet" with the default driver
> Creating network "docker_front" with the default driver
> Creating docker_pgnode1_1 ... done
> Attaching to docker_pgnode1_1
> pgnode1_1       | INFO: Begin cluster setup
> pgnode1_1       | INFO: Configuring repmgr (/etc/repmgr.conf).
> pgnode1_1       | INFO: Creating Postgres cluster's pg_hba.conf.
> pgnode1_1       | '/var/lib/postgresql/pg_hba.conf' -> '/etc/postgresql/11/main/pg_hba.conf'
> pgnode1_1       | INFO: The current primary node is unknown.
> pgnode1_1       | INFO: This cluster has been set up already.
> pgnode1_1       | INFO: Assuming node configuration is correct.  Starting up.
> pgnode1_1       | Removed stale pid file.
> pgnode1_1       | Error: /usr/lib/postgresql/11/bin/pg_ctl /usr/lib/postgresql/11/bin/pg_ctl start -D /var/lib/postgresql/11/main -l /var/log/postgresql/postgresql-11-main.log -s -o  -c config_file="/etc/postgresql/11/main/postgresql.conf"  exited with status 1: 
> pgnode1_1       | 2021-06-03 23:55:20.157 UTC [20] LOG:  listening on IPv4 address "0.0.0.0", port 5433
> pgnode1_1       | 2021-06-03 23:55:20.157 UTC [20] LOG:  listening on IPv6 address "::", port 5433
> pgnode1_1       | 2021-06-03 23:55:20.600 UTC [20] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5433"
> pgnode1_1       | 2021-06-03 23:55:21.595 UTC [21] LOG:  database system was interrupted; last known up at 2021-06-02 22:39:16 UTC
> pgnode1_1       | pg_ctl: server did not start in time
> docker_pgnode1_1 exited with code 1

Container is restarting in a loop after about a minute.

**How to Reproduce**
I followed the installation instructions for the dockerized setup of OpenSlides step by step. (https://github.com/OpenSlides/OpenSlides).

**Expected behavior**
Successfull startup of all docker services.

**System information**
- Debian 10 run in VirtualBox
- Docker version 20.10.7, build f0df350
- docker-compose version 1.21.0, build unknown

**Additional context**
I already deleted the Docker Image "openslides/openslides-repmgr" and created it again with the "build.sh" script (`sudo ./build.sh repmgr`). Also deleted all Docker Images and ran `sudo ./build.sh all` again.
Im not familiar with repmgr so if the problem is related to this please provide me with some instructions how to solve this problem.
If you need any further information for solving this issue feel free to ask for them.

**Comment by gsiv** [comment]
The error is not related to repmgr; it's `pg_ctl start` that fails.  Your cluster either does not start or does not start quickly enough.

Just to clarify, can you reliably reproduce the problem with new instances/volumes or are you always trying to get this particular cluster to start?  To help narrow down the problem, please try starting a fresh database.

**Comment by bananakaba** [comment]
Hi,

I set up a new VM and had the same problem again, after trying to fix this problem I gave it a new try and installed Ubuntu Server in VirtualBox where I did not had any problems with `pg_ctl start`.
As it worked with Ubuntu Server I did not made any trouble shoot with Debian so this Issue can be closed.
