### ISSUE TITLE
Form field does not display selected value of search-value-selector

### ISSUE THREAD

**Issue by jwinzer** [OpenSlides/OpenSlides#6117]
The selected value of _voting right delegated_ to **is not displayed** in the form field if you select a list item with **list index > 12**. It's interesting that the value **is displayed** for item with list **index <= 12**.

**Steps to repeat**

1. Select any item with list index 13 or greater
![image](https://user-images.githubusercontent.com/20415092/122352720-a99df700-cf4f-11eb-85b6-749724c5b72e.png)
![image](https://user-images.githubusercontent.com/20415092/122352960-df42e000-cf4f-11eb-9d03-9690c51352d3.png)

2. Click Save

3. Reopen the details dialog
![image](https://user-images.githubusercontent.com/20415092/122353053-f97cbe00-cf4f-11eb-9b61-dacc65ce63cd.png)

I get the same issue for _voting right received from_ if only one item is selected.

**Comment by tsiegleauq** [comment]
That is due to lazy loaded lists. The things do not exist in the DOM anymore, or rather, your DOM only loads a tiny subset of users so you can scroll through some thousands without lagg. But I thought I have fixed that before, strange.

**Comment by tsiegleauq** [comment]
Moved to TODO milestone. This is an open angular issue. Cannot currently provide a fix.
https://github.com/angular/components/issues/13087

**Comment by emanuelschuetze** [comment]
outdated, should be fixed in os4.
