### ISSUE TITLE
New field: `meeting/imported_at`

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#6122]
This field is set by the backend to the time and date a meeting is imported, see https://github.com/OpenSlides/openslides-backend/issues/764. It has to be added to the models.yml.

**Comment by tsiegleauq** [comment]
autoclose did not work.
https://github.com/OpenSlides/OpenSlides/pull/6125

**Comment by jsangmeister** [comment]
> autoclose did not work.
> #6125

I think the autoclose line must be the first of the PR description
