### ISSUE TITLE
Configurable help and contact information

### ISSUE THREAD

**Issue by Lukas2112** [OpenSlides/OpenSlides#6140]
**Is your feature request related to a problem? Please describe.**
Maybe: Playing on too many channels?

**Describe the solution you'd like**
Channelling support requests in a helpdesk system, such as Zammad (or OTRS).

**Describe alternatives you've considered**
Helpdesk via Jitsi, as already available in OpenSlides-dev branch.

**Additional context**

**Comment by tsiegleauq** [comment]
I cannot extract any information from this request.

**Comment by Lukas2112** [comment]
I could imagine that using Jitsi-Meet as a helpdesk, i.e. using another channel, might be too much effort in the long run. However, if companies / NGOs etc. already use Zammad or OTRS as a helpdesk system, integrating them might make more sense.

**Comment by tsiegleauq** [comment]
The jitsi-meet helpdesk us usually used as an additional support channel for virtual assemblies, where the users tend to require quick help on using OpenSlides. What you require, on the other hand, is a central area to display arbitrary information in a meaningful way. I'll talk with our designers about that, perhaps we can offer something that goes in that direction. For the time being, arbitrary help information can be put on the start page of OpenSlides, which can be designed using HTML at runtime.

**Comment by emanuelschuetze** [comment]
seems to be done (start page or jitsi helpdesk room)
