### ISSUE TITLE
Add autoupdate calculated fields (e.g. `content`) to the models.yml

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#6143]
To have an overview, which fields exists, also the calculated fields by the autoupdate should be added to the models.yml. They should get a flag like `autoupdate_calculated: True`, so the backend can just ignore these fields. E.g. they must be ignored when importing since they never appear in the datastore.

**Comment by tsiegleauq** [comment]
@ostcar is that something you can provide? I don't know which fields the AU would create

**Comment by ostcar** [comment]
I think this of a very good idea.

Currently, there is only one calculated field:

projection/content

The field has the type JSON.

Do you need other infos?
