### ISSUE TITLE
Add pronouns as a free Textfield for users

### ISSUE THREAD

**Issue by LaluSys** [OpenSlides/OpenSlides#6179]

**Comment by LaluSys** [comment]
![SmartSelect_20210721-135524_Chrome](https://user-images.githubusercontent.com/86659426/126484841-65fdad96-54c3-4cba-9ff9-8cc26876d6d5.jpg)

**Comment by LaluSys** [comment]
Or options like:

He/him
she/her
they/them
and a free text field.

**Comment by tsiegleauq** [comment]
we will probably not offer this as a feature directly, but can address this in several other ways.

To address this properly, we may add configurable additional fields to users that the administration can set themselves. This would eliminate other fields that are rarely used, like comment and participant number, and would allow organisations to provide every other information desired as well, for example: being vegetarian or vegan or the said pronoun.

For the time being, you can either add the pronoun as a part of the name or the structure level. The word "structure level" can then be customized using the custom translation feature to pronoun. I'll add some images below. The structure level will show whenever the users "full name" was requested, that happens i.e on the list of speakers and in the projector, so the moderation can directly see how to address someone.

User Detail:
![image](https://user-images.githubusercontent.com/10233032/126633003-87ba0b03-04ef-4380-8cb6-97bf0aa950f5.png)

User Edit:
![image](https://user-images.githubusercontent.com/10233032/126633026-e6ea5a27-8fcf-4ba3-8dae-b21af853cf36.png)

List Of Speakers:
![image](https://user-images.githubusercontent.com/10233032/126633057-5c408045-3752-4c65-9436-0acd55518906.png)

Projector Slide with List-Of-Speakers:
![image](https://user-images.githubusercontent.com/10233032/126633118-b514a636-4aef-44e8-ae0d-92f4249d83fa.png)

**Comment by LaluSys** [comment]
That implementation looks really good! I am exited to use it and will give Feedback. <3

**Comment by jsangmeister** [comment]
done for 4.0 with https://github.com/OpenSlides/openslides-backend/pull/1166 and https://github.com/OpenSlides/openslides-client/pull/828
