### ISSUE TITLE
Expand the Gender Options with a free text field

### ISSUE THREAD

**Issue by LaluSys** [OpenSlides/OpenSlides#6180]
![SmartSelect_20210721-135538_Chrome](https://user-images.githubusercontent.com/86659426/126484976-a0f8b230-09b0-4b04-9e66-d7599eb871e4.jpg)

**Comment by tsiegleauq** [comment]
this discussion is currently at:
https://github.com/OpenSlides/openslides-backend/issues/847

**Comment by emanuelschuetze** [comment]
done in os4
