### ISSUE TITLE
Agenda is displayed in wrong order inspite of numbering

### ISSUE THREAD

**Issue by tibetischeszentrum** [OpenSlides/OpenSlides#6249]
**Describe the bug**
Added an agenda with main points (1,2,3,4,5,..) and subpoints (1.1, 1.2, 1..3, ...) but the subpoints always display after the main points (8, 9, 1.1, 1.2, 1.3, 2.1, 2.2, ...)
When using the sort function the hierarchy get's displayed correctly, but when returning to the agenda view, they are displyed again in the wrong order.

**How to Reproduce**
1. click agenda
2. add points 1 - 9
3. add subpoints  
4. use automated numbering
5. verify numbering, i.e. point 1.3 really has number 1.3
6. displayed order is wrong

**Expected behavior**
Ordering like 
1.
  1.1
  1.2
2.
  2.1
...

**System information**

- OpenSlides-Version: 3.4
- Additional version information (if any): commit hash 8d20c40ca
![image](https://user-images.githubusercontent.com/73660878/136789465-6c7cc559-3903-4630-b3a7-c1d0eacfa96f.png)

**Comment by emanuelschuetze** [comment]
Thanks for reporting. We know this bug. 
Current workaround: open agenda sort view (which shows correct order), move one item (e.g. to the end and back to correct position) -> then save the (unchanged) order -> agenda tree is now rebuild and looks correct in agenda view. Hope this helps. We will fix this in OS4.
