### ISSUE TITLE
Change the `list_of_speakers_id` of mediafiles in the models.yml from `required: true` to `required: false`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/OpenSlides#6250]
Affected versions: 4.0-dev

Since #6246 the `list_of_speakers_id` is marked as `required: true` for mediafiles. This is wrong, because mediafiles do not even have an `agenda_item`...

**Comment by emanuelschuetze** [comment]
@r-peschke this issues is solved with #6255 right?

**Comment by r-peschke** [comment]
> @r-peschke this issues is solved with #6255 right?

yes, it is.
