### ISSUE TITLE
[Meta] Communication between manage tool, manage service and other OpenSlides services during initial startup and for serveral admin actions

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#6257]
## What is this about

This issue is about how the manage tool, the manage service and other services should do the job. We have the following steps here:

## Initial setup

The manage tool is used to create the Docker configuration (e. g. a `docker-compose.yml` file) and some more directories and files like secrets. The user can provide one or more config files to customize this step.

## Starting Docker

The user is responsible to download or build all images, create all containers and start them all. He can do this e. g. with `docker-compose up`. There is no explicit support for this step by the manage tool.

## Inserting initial data and setting superadmin password

How to get the initial data into the datastore?

### Current proposal

The manage tool connects the manage service. Therefor it uses the proxy witch recognizes the HTTP header (`Content-Type: application/grpc`) and forwards the request to the manage service.

The manage service authenticates the request using a Docker secret that the manage tool has to provide with the request in a respective header (`authorization: <base64 encoded password as given in the secret file>`).

The manage service then calls an internal route of the backend with a HTTP POST request. The JSON payload is `{"initial_data": <object>, "superuser_password": <string>}` with an initial data object in the format [we already have](https://raw.githubusercontent.com/OpenSlides/OpenSlides/master/docker/initial-data.json).

This request does not contain any authentication headers set by the auth service, so the backend must handle this request either without any authentication check or – if necessary – just by checking a shared Docker secret: The manage service would provide a HTTP header `authorization: <base64 encoded password as given in the secret file>` and the backend may read the secret from `/run/secrets/...` and compare it with the received header.

The backend then validates the given data (including check that a user with id 1 is given) and sends them to the datastore. The current migration index is included in this request. The backend also sets the password of the user with id 1 to the given superuser password.

If the manage service does not send any initial data the backend uses the current default initial data.

There is no initial migration.

#### Is it necessary that the manage service uses a Docker secret in his request to the backend?

I think it is not because the network settings and the proxy ensure that the internal route can not be called from outside.

#### Where does the backend find the default initial data?

I think it would be best if the current (up-to-date) `default-intial-data.json` lay together with the current (up-to-date) `models.yml` in the main repository. If there are changes the backend has to regenerate its `models.py` and has to create a new migration file (if the migration index changed). During this step it can also fetch the initial data into a generated `default-initial-data.py`.
The advantage is that both files stay together. It is the responsibility of the main repository maintainer to check that all services that make code generation out of the `models.yml` (like backend and autoupdate) use the same version.

Extra proposal: The `models.yml` should contain the current migration index. So that we know which version of the file belongs to which migration status.

## Creating new users

There are two ways how the manage tool can create new users.

1. The manage tool makes a login request to OpenSlides and then uses the common `user.create` action with the respective auth headers. The manage service itself is not involved.

2. The manage tool connects to the manage service the same way as described above in the initial data section. The manage service the uses the `user.create` action via an internal route without any credentials or only with the shared Docker secret.

The problem of 1. is that the admin can not create a new superuser to get access to OpenSlides in case of changed or lost credentials (changed username or password) or other problems like superuser was deleted, disabled or has lost his organization management level. What can he do in this case?

The problem of 2. is that we do not know which user performs this action and should be mentioned in the event. We can take user id 0 but this looks like that an anonymous user can make critical requests to OpenSlides.

Opinions?

## Updating images and running migrations 

If there is an update the admin first has to update the Docker configuration, e. g. by recreating the `docker-compose.yml` with updated image tags. In the next step he has to stop and remove the containers and create the new ones. Therefor he can use something like `docker-compose down && docker-compose pull && docker-compose up`.

If the migration index changed the backend containers should not start as usual but idle and check the migration index in the datastore every n seconds.

Now the admin can use the manage tool to initiate migrations. The manage tool connects to the manage service in the same way as described above in the initial-data section. The manage service then performs a request to a internal backend route to run the respective migration command. This request is again either without any authentication headers or only with a shared secret.

Opinions?

**Comment by ostcar** [comment]
> 
> 
> @normanjaeckel we came internally to the conclusion that the movement of all the files to the backend the best way is. @ostcar already gave his okay. If that is also okay for you, we will do that move next week.

I am against this change, but I can live with it.

With this change, there will be a dependency from the autoupdate-service (and all other go services) to the master of the backend. It will not be possible in the future to fix an older version of the autoupdate repo without including the changes from the models.yml from the backend. Not the tagged version of the services of the main repo will be deciding, but the master of the backend. I don't know if this will be a problem after the 4.0 release.

My "okay" is under the condition, that I don't have to include any hacks in the autoupdate service to "fix" this problem. If after the 4.0 release this problems will occur, then you have to move the files back to the main repo.

**Comment by jsangmeister** [comment]
My suggestion would be that the dependency is not to the master, but instead to a fixed commit hash. This way, the dependency stays consistent and can be adjusted as needed.

**Comment by jsangmeister** [comment]
> There are other problems. There are a lot of internal routes in the services that can be accessed from the proxy. For example there are a lot of [internal routes from the auth service](https://github.com/openslides/openslides-auth-service#internal-routes). Also the vote service has internal routes, and I added an internal metic url to the autoupdate-service.

Ok, I did not know that - then I guess we'll have to do it there the same way. We can use the same secret for all services however.

> If you can not garantie, that the proxy blocks this urls, all this internal urls need another layer of protection.

As far as I understood it, it's not about us not guaranteeing that the proxy works, but more that it is just not in the task scope of the proxy to work as a security mechanism.

**Comment by normanjaeckel** [comment]
See https://github.com/OpenSlides/openslides-backend/pull/1029

**Comment by r-peschke** [comment]
To fulfill the backend requirements of this issue, there are following actions:
[organization.initial_data](https://github.com/OpenSlides/OpenSlides/wiki/organization.initial_import)
[user.set_password](https://github.com/OpenSlides/OpenSlides/wiki/user.set_password)

@jsangmeister: I'm not quite sure whether they work on internal route without user permissions

**Comment by jsangmeister** [comment]
(wrong issue @r-peschke)

**Comment by r-peschke** [comment]
@jsangmeister : Look at the `Inserting initial data and setting superadmin password` paragraph on top of this issue:D

**Comment by jsangmeister** [comment]
Ok, but I think the communication about this feature belongs in https://github.com/OpenSlides/openslides-backend/issues/1035 :D but I agree that it is not quite clear

**Comment by jsangmeister** [comment]
closing this since I think it served it purpose.
