### ISSUE TITLE
Let GitHub actions work properly

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#6258]
Regardless of whether the initial data should be updated in the manage service or not we have a respective GitHub action, that should open an issue in the manage service.

This action does not work but is skipped every time.

Some ideas?

**Comment by tsiegleauq** [comment]
Removed the actions:
https://github.com/OpenSlides/OpenSlides/pull/6291

Cleaned the yml and template to make it more maintainable and move it to backend:
https://github.com/OpenSlides/openslides-backend/pull/1041

They should work now, we'll see later. Keeping this open until I can confirm that they work after PRs were merged

**Comment by tsiegleauq** [comment]
works as intended:
https://github.com/OpenSlides/openslides-backend/issues/1042
