### ISSUE TITLE
Stuck in "Data will be loaded" when using SSL

### ISSUE THREAD

**Issue by stebla27** [OpenSlides/OpenSlides#6260]
I have OpenSlides 3.4 as docker installed. OpenSlides uses no SSL and the proxy docker image listens on external HTTP port 3000.
Another Docker image "Nginx Proxy Manager" is running which defines a reverse proxy from a domain to unsecure port 3000. The Nginx Proxy Manager provides a SSL certificate and forces a secured connection. Web Sockets are enabled.
This setup worked with OpenSlides 3.3 without problems. Nothing was changed on SSL/Reverse proxy configuration.
However first loading of OpenSlides with SSL was working without problems. But after some refresh the website stucks in "Daten werden geladen. Bitte warten..." mode (= Data will be loaded. Please wait...).
Deleting browser cache does not fix the problem.
When loading the website on another device, it stucks also in this mode.
Sometime randomly it works again.
When connecting without SSL, it works without problems!
On a PC where it randomly worked again, I logged in and just created a new Chat. And suddenly the page loaded on all other devices again. Just like it had cleaned up a lock...

Note:
- Exactly this setup works with OpenSlides 3.3.
- I use Safari as Browser. But it also happens with Firefox. Mobile Safari sometimes crashes when website is in this [mode.
![IMG_AFB68E23F428-1](https://user-images.githubusercontent.com/29398110/138126063-b48ee638-ea02-4037-a9b0-5c61bc727574.jpeg)
]

Sometimes this Zombie mode happens (white background, no data,...):
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/29398110/138129697-e640b1d6-1ca3-46d6-8689-72706ec145fa.png">
Again: Deleting Browser Cache does not help. But when loading the page on other devices it works. So the client stucks.
But when manually deleting cookies, it works again!

**Comment by tsiegleauq** [comment]
sounds not like an error in OpenSlides but a setup error on your side. Perhaps one of our administrators can help you out:
@gsiv @peb-adr

**Comment by gsiv** [comment]
From what you have written, it is unclear to me whether you have configured OpenSlides for HTTPS or not.  In most cases, you are going to want to use plain HTTP between the reverse proxy and OpenSlides.

For the purpose of debugging the issue, please always access the OpenSlides instance directly (on port 3000), circumventing the reverse proxy.  The problem may very well be Nginx's configuration.  If the problem persists, please share the contents of your `.env` and/or the generated `docker-compose.yml` files.

Also, did you check the instance's logs for clues?

**Comment by stebla27** [comment]
@gsiv Before I used OpenSlides without https configured. I wanted exactly that behavior you're describing. An unsecured connection between the reverse proxy and OpenSlides and only the reverse proxy has a SSL certificate.
In this setup I had exactly the problem described above. With OpenSlides 3.3 this setup worked without problems, with OpenSlides 3.4 it doesn't work anymore.
But then @tsiegleauq said:

_OpenSlides uses no SSL and the proxy docker image listens on external HTTP port 3000.
might be an issue. This section of the readme:
https://github.com/OpenSlides/OpenSlides/tree/stable/3.4.x#using-https
is mandatory (I should mention this somewhere I suppose). OpenSlides itself needs ssl_

So this is the reason why I now also activated HTTPS on the OpenSlides itself.
With the effect that if I access OpenSlides directly without the reverse proxy (internal network) the error is gone, but if I use the reverse proxy the error is still there.
It seems for me an error in the OpenSlides 3.4 implementation.

**Comment by stebla27** [comment]
@gsiv @tsiegleauq 
Now I removed the reverse proxy and used directly SSL in OpenSlides.
If I'm logged in with several devices on the same account, sometimes OpenSlides still stucks in "Please wait! Loading data".
This happens for example if I'm logged in with my iPhone and then try to login simultaneously with my Windows PC.
The Windows PC then hangs in  "Please wait! Loading data".
Then I have to do some actions on the iPhone e.g. creating a new chat, editing a page or whatever and then the Please wait loop quits on the the Windows PC!
Any ideas?

**Comment by tsiegleauq** [comment]
The "loading data" spinner is usually an indicator that the client does not reach the stable state (angular appref https://angular.io/api/core/ApplicationRef). Once "stable" was reached, the spinner would disappear. If it's not disappearing, either something in the client (or the browser) is wrong, or the setup hangs somewhere somehow. The former could be confirmed by seeing your browsers console. There should be additional error logging. The later can either be seen in dockers own error log or indicates a faulty setup.

What you describe (spinner -> manual autoupdate-triggering -> spinner disappears) sounds like an error in the integration of the autoupdate service (shot in the blue)

We cannot really debug anymore without seeing your setup.
From what you describe, our own productive setup (that we use for instances hosted over openslides.com) is pretty similar to yours, so I doubt that there is an error in the implementation of OS3.4

**Comment by jsangmeister** [comment]
OpenSlides3 is no longer maintained.
