### ISSUE TITLE
OS4 media service does not start

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#6282]
In current OS4 dev master, the mediaservice does not boot up. This might a configuration issue in the documented dev setup or the proxy.

```
docker-media-1             | postgres:5432 - accepting connections
docker-media-1             | psql:src/schema.sql:6: NOTICE:  relation "mediafile_data" already exists, skipping
docker-media-1             | CREATE TABLE
docker-media-1             | psql:src/schema.sql:12: NOTICE:  relation "resource_data" already exists, skipping
docker-media-1             | CREATE TABLE
docker-media-1             | Password for user root:
docker-media-1             | psql: fe_sendauth: no password supplied
docker-media-1 exited with code 2
```

**Comment by peb-adr** [comment]
To me it looks like a problem in the startup routine of the media-service.
it can be worked around by changing `docker/docker-compose.dev.yml` like this:

    media:
      environment:
        - OPENSLIDES_DEVELOPMENT=1
        - MEDIA_DATABASE_HOST=postgres
        - MEDIA_DATABASE_PORT=5432
        - MEDIA_DATABASE_USER=openslides
        - MEDIA_DATABASE_PASSWORD=openslides

So somewhere the postgres user and password are set incorrectly.

Though it is rather strange to me, that apparently at one point a connection can be established for creating/checking the schema.
Looks like that connection is then closed and a new one is opened when actually starting the media server.
And that final connection seems to use wrong credentials (Password for user root:).

My guess is that actually no credentials at all are used upon establishing connection, hence defaulting to root and prompting for password.

**Comment by normanjaeckel** [comment]
Maybe have a look at the entrypoint of the service. There I found another but concerning postgres credentials.

**Comment by peb-adr** [comment]
fixed by https://github.com/OpenSlides/openslides-media-service/pull/38
