### ISSUE TITLE
Proxy does not start in dev environment

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#6289]
Sometime, when I run make run-dev, the proxy does not start. It stops with the log messages:

```
docker-proxy-1  | /entrypoint: line 11: can't open /caddy_base.json: no such file
docker-proxy-1  | jq: error: Could not open file /caddy_base.json: No such file or directory
```

I don't know when it happens, But if it happens, stopping the stack and starting it again does not help.

What helps for me is to delete all containers `docker container prune`.

**Comment by GabrielInTheWorld** [comment]
I suppose, that #6284 should fix this behavior.

**Comment by peb-adr** [comment]
#6284 was merged, closing.
@ostcar reopen, should you still experience problems.
