### ISSUE TITLE
Change name of field in the client

### ISSUE THREAD

**Issue by TheLucasNorth** [OpenSlides/OpenSlides#6314]
**Is your feature request related to a problem? Please describe.**
Related to other discussions, I'm trying to change the name of the "Structure level" field in the user-detail view to be "pronouns" instead. I feel like I'm missing something obvious that means the change isn't reflected in the browser.

**Describe the solution you'd like**
Any way for it to show "pronouns" as the field header. Using custom translations doesn't work because the base language is English.

**Describe alternatives you've considered**
I've been trying to change this, as follows:
In `client/src/app/site/users/components/user-detail/user-detail.component.html` I have updated the `<ng-template #showView>` section like so

        <div *ngIf="user.structure_level">
            <h4>Pronouns</h4>
            <span>{{ user.structure_level }}</span>
        </div>

I then run `./build.sh client` from within the docker folder, and `docker-compose restart client`. However when I refresh the browser, the change is not shown.

I feel like it's something very obvious that I've missed, sorry - just a step I forgot but can't work out.

**Additional context**
OS is Ubuntu 18.04 . Using OpenSlides v3.4

**Comment by tsiegleauq** [comment]
> Any way for it to show "pronouns" as the field header. Using custom translations doesn't work because the base language is English.

This is a bug, but a minor one. English does not support custom translations yet. This will most likely not change with 3.4.1 but in 4.0.
Custom pronoun support will would be added as a custom field on 4.1 oder later (if, any), as described in the other issue.

For changing the template, you need to get into developing OpenSlides and building your custom version.

You will want to use 3.4 for the time being (just trust me on this).
Thus, follow this [documentation until](https://github.com/OpenSlides/OpenSlides/blob/stable/3.4.x/DEVELOPMENT.rst) until `make run-dev`.

Effectively, you are adjusting your client (and nothing else). The client is static code. You will need to build the client and deliver it on your own web server.
