### ISSUE TITLE
Build.sh for stabel/3.4.x failed at ,,openslides/postfix" build 

### ISSUE THREAD

**Issue by lukas-mc** [OpenSlides/OpenSlides#6334]
Hey All.

Not sure I need some help or something is broken on building stable/3.4.x.

What I did is checkout branche 3.4.x. with: 
`git clone https://github.com/OpenSlides/OpenSlides.git --recurse-submodules -b stable/3.4.x`

update submodules:
`git submodule update --init`

Then running ./build.sh inside of docker I get

`....
Successfully tagged openslides/openslides-autoupdate:latest
Building openslides/openslides-postfix:latest...
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: fatal: Konnte Remote-Referenz master nicht finden.
: exit status 128
`

I checked build.sh, which calls:
`[media]="https://github.com/OpenSlides/openslides-media-service.git"
  [pgbouncer]="https://github.com/OpenSlides/openslides-docker-compose.git#:pgbouncer"
  [postfix]="https://github.com/OpenSlides/openslides-docker-compose.git#:postfix"
  [repmgr]="https://github.com/OpenSlides/openslides-docker-compose.git#:repmgr"
`

So commenting out all this lines will build the other images, but the 4 above are missing.

Do I need to checkout opensildes/docker-compose to build stable/3.4.x or how to fix?

Thanks for advise

Lukas

**Comment by davidmehren** [comment]
I could work around this by editing the TARGETS array like this:
```
TARGETS=(
  [client]="$(dirname "${BASH_SOURCE[0]}")/../client/docker/"
  [server]="$(dirname "${BASH_SOURCE[0]}")/../server/docker/"  [proxy]="$(dirname "${BASH_SOURCE[0]}")/../caddy/"
  [autoupdate]="$(dirname "${BASH_SOURCE[0]}")/../autoupdate/"
  [media]="https://github.com/OpenSlides/openslides-media-service.git#stable/3.4.x"
  [pgbouncer]="https://github.com/OpenSlides/openslides-docker-compose.git#main:pgbouncer"
  [postfix]="https://github.com/OpenSlides/openslides-docker-compose.git#main:postfix"
  [repmgr]="https://github.com/OpenSlides/openslides-docker-compose.git#main:repmgr"
)
```

The branch names of the repos seem to have been changed, without adapting `build.sh`.

**Comment by lukas-mc** [comment]
Thanks davidmehren :-)

I do have not so much experience in building docker images.  Learned where to find the settings to get the right Target now :-)

Changed it in my local copy and it's running perfect now. 

Regards Lukas
