### ISSUE TITLE
HTTP support not working since 3.3

### ISSUE THREAD

**Issue by burningT** [OpenSlides/OpenSlides#6335]
A while ago I tried setting up OpenSlides for a LAN configuration using HTTP only. I started with version 3.4 and had a hard time to figure out that I had to go back to 3.2 to get HTTP running. HTTPS setup would work for me on any version but was out of question due to the intended network. It seems to me as if HTTP shall be supported but in fact is not running since 3.3.

OpenSlides was setup for HTTP as described in the installation instructions. It was running on Ubuntu 20.04.3 Server within a virtual machine. However, the HTTP port was not listened on (running OpenSlides 3.4 configured for port 8080):
```
$ sudo ss -tunlp
[sudo] password for cpdadmin:
Netid  State   Recv-Q   Send-Q        Local Address:Port     Peer Address:Port  Process
udp    UNCONN  0        0          10.0.2.15%enp0s3:68            0.0.0.0:*      users:(("systemd-network",pid=637,fd=19))
udp    UNCONN  0        0             127.0.0.53%lo:53            0.0.0.0:*      users:(("systemd-resolve",pid=639,fd=12))
tcp    LISTEN  0        4096          127.0.0.53%lo:53            0.0.0.0:*      users:(("systemd-resolve",pid=639,fd=13))
tcp    LISTEN  0        128                 0.0.0.0:22            0.0.0.0:*      users:(("sshd",pid=710,fd=3))
tcp    LISTEN  0        128                    [::]:22               [::]:*      users:(("sshd",pid=710,fd=4)
```

**Comment by tsiegleauq** [comment]
https://github.com/OpenSlides/OpenSlides/tree/stable/3.4.x#using-https
