### ISSUE TITLE
Print listening address and port to command line

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#634]
Tornado should print the address and port to command line once before start, so that people with browser problems can open the webinterface manually.

**Comment by jsaalfeld** [comment]
Since Tornado isn't in use anymore and this issue is more than 5 years old, I'm gonna close it.

Please reopen if I'm wrong about this.

**Comment by normanjaeckel** [comment]
> Let's think how to get the real ip address and print this to command line and into the PDF.

This is still valid and has nothing to do with tornado.

**Comment by tsiegleauq** [comment]
> Let's think how to get the real ip address and print this to command line and into the PDF.

I'd prefer that you make another issue for that.
Somewhat related:
#4327

**Comment by FinnStutzenstein** [comment]
not possible anymore with docker: The server does not have a change to access the host system.
