### ISSUE TITLE
Moving development away from github

### ISSUE THREAD

**Issue by bug0001** [OpenSlides/OpenSlides#6351]
I'm not familiar with Github, but this is my understanding of it (and of OpenSlides) :

1) It is proprietary/non-free software.
2) It is owned by Microsoft
3) At OpenSlides, looking at the list of participants, >90% of contributions seem to be done internally, not by outside contributors

There are probably many other good reasons to move away from Github (poor privacy policy, hosted in the United States, ...) that would become apparent upon further inspection, but these alone ought to be enough.

Alternatives that I can think of : - Gitea (either self-hosted or there are good gratis providers) - Sourcehut (self-hosted or modest fee) - Gitlab (same, even gitlab.com would be better at this point).

I don't understand what business a project financed by a free software company has doing here.

Hopefully this can lead to a collective discussion/decision-making.

**Comment by normanjaeckel** [comment]
I understand the issue. GitHub itself is proprietary.

But OpenSlides is not. The code is free and we also try to provide any help to everybody who wants to use OpenSlides self-hosted. I know that our documentation is not very good at the moment. The active developers are focusing on fixing bugs and implementing new features (of course for paying customers, this is not unusual as we hopefully all agree). Esp- for OpenSlides 4 we try to provide and easy way to install and start OpenSlides self-hosted using the manage tool.

This has all nothing to do with the question whether to work with GitHub (in a public repository) or not. At the moment the policy of GitHub (and Microsoft behind it and even the U.S. jurisdiction) does not prevent us in developing free software and giving everybody access to it. So I propose to say here as long as this platform has the best features for us. That's may opinion here (at the moment).

**Comment by jsangmeister** [comment]
I agree with @normanjaeckel. I don't see any issue with an OpenSource project hosting its code on Github - in fact, a lot of companies/projects do that; I would even argue it's a very common thing.

**Comment by emanuelschuetze** [comment]
+1 for @normanjaeckel and @jsangmeister

**Comment by bernhardreiter** [comment]
There are a number of good reason to develop Free Software on a different platform than Github. (I'm not going into details here, as they are not the main point as I can see it.) The Openslides development happens here out of its history. And it is difficult to move it somewhere else. 

If we'd start a new Free Software product's development now, we do it on a different platform, e.g. with heptapod. But moving an existing development process and community is something else. Still we probably propose to move Openslides off github in the future.

>  as long as this platform has the best features for us.

This is subject to evaluation. It is quite likely from what I know that the gitlab CC based Free Software platforms like heptapod have surpassed Github proprietary feature set for a while now.

>  in fact, a lot of companies/projects do that; I would even argue it's a very common thing.

Sure, it is a common thing to do, but this is argument does not carry a lot of weight. It was also common to use Microsofts Word for steering resolutions in an assembly, probably still is, but we do propose Openslides which is uncommon. ;)

**Comment by YveIce** [comment]
For me, this is a (very) stupid Richard Stallman like diskussion. Saying things like _"don't use github for opensource, because its non-free software"_ it's like saying "don't use an proprietary cpu to compile your opensource-code, because the microcode of your cpu is non-free software".

**Comment by bernhardreiter** [comment]
@YveIce thanks for sharing your view on the matter.

We will try to focus the discussion on the specific arguments of interest to Openslides and its development and user community. And try to avoid too general arguments. (Personally I think Richard Stallman is an exceptional thinker, so your attribution is not helping the specific argument, please refrain from calling something or someone stupid in the future.)
