### ISSUE TITLE
[3.4.x] OpenSlides 3.4 building fails on Debian 11

### ISSUE THREAD

**Issue by Lapotor** [OpenSlides/OpenSlides#6352]
**Describe the bug**
I tried to install Openslides 3.4.x on a freshly installed debian 11 VPS from netcup.
It fails on setting up the postfix container.

**How to Reproduce**
1. Get VPS
2. Get debian 11
3. Install OpenSlides 3.4.x

**Expected behavior**
Installing just fine.

**System information**
- OpenSlides-Version: 3.4
- Python Version: none on host
- OS: Debian 11

**Screenshots**
![grafik](https://user-images.githubusercontent.com/17144397/152703163-30fca9e2-3be3-4c7e-a8f6-7d4228e0ca3c.png)
[install.log](https://github.com/OpenSlides/OpenSlides/files/8011319/install.log)

**Comment by NullDev** [comment]
Most likely a dependency problem on your system. Try 

```sh
sudo apt install -f
```

and run the installer again.

**Comment by Lapotor** [comment]
@NullDev na this is all inside the Build process of the docker container:
![grafik](https://user-images.githubusercontent.com/17144397/152769570-9f9ec721-c356-44cc-a32e-8254cc61a11a.png)

**Comment by bug0001** [comment]
Hi, thanks for reporting the issue. I'll have a look and will report later

**Comment by bug0001** [comment]
I installed the latest Debian 11 and was able to run "./build.sh all" with no exiting errors.

To clarify : which step of the documentation (https://github.com/OpenSlides/OpenSlides/tree/stable/3.4.x) are you stuck in?

"./build.sh all" or "docker-compose up" or else?

To help yourself, you may wish to install OS3 in a local environment. If that works, then it should be something on the server provider (network, system restrictions...)

**Comment by Lapotor** [comment]
I just did `./build.sh all`
Will try in a VM Local

**Comment by bug0001** [comment]
I'm assuming you've been able to move forward. Please open a new issue if you encounter further problems. Thank you
