### ISSUE TITLE
OpenSlides 3 (stable) documentation needs overhaul

### ISSUE THREAD

**Issue by bug0001** [OpenSlides/OpenSlides#6353]
https://github.com/OpenSlides/OpenSlides/tree/stable/3.4.x

1) "./build.sh all"

This won't run as described, for the same reasons that the Docker procedure in OS4 doesn't work without more explanation (either sudo is needed, or Docker needs to be configured to not use sudo)

2) "Use can also use daemonized instance:"

You can also use?

3) "m4 docker-compose.yml.m4 > docker-compose.yml"

m4 should be listed explicitly as requirement (just as make is). It does not come installed on most broad-use systems.

update : a previous problem has been fixed by (now closed, merged) pr 6356 / 6359

**Comment by bug0001** [comment]
As for 3.

https://www.commandlinux.com/man-page/man1/m4.1.html

This should be listed explicitly as requirement (just as make is). It does not come installed on most broad-use systems.

**Comment by bug0001** [comment]
The m4 file is not in the local folder, but in the (remote) repository

https://github.com/OpenSlides/OpenSlides/blob/stable/3.4.x/docker/docker-compose.yml.m4

**Comment by jsangmeister** [comment]
> This won't run as described, for the same reasons that the Docker procedure in OS4 doesn't work without more explanation (either sudo is needed, or Docker needs to be configured to not use sudo)

I would argue that the correct configuration of your local docker installation should not be part of the OS4 documentation. I think the comment you added in https://github.com/OpenSlides/OpenSlides/pull/6350 should be enough for this.

**Comment by bug0001** [comment]
(these are different documentations, one for stable one for 4, and will be done separately)
