### ISSUE TITLE
Remove the gender *-crap

### ISSUE THREAD

**Issue by Hoerli1337** [OpenSlides/OpenSlides#6371]
Give the admin the option to disable the gender crap.
Really no one needs and looks stupid.

**Comment by ostcar** [comment]
The "gener star" is not part of openslides core, but of the german translation.

You can find all translations here: https://github.com/OpenSlides/openslides-client/tree/main/client/src/assets/i18n

If you don't like the translation we provide, you can feel free to create your one. 

You can also change the translation in the ui. Got to https://demo.os4.openslides.com/1/settings/custom%20translations There you can add your own translation strings.

If you think it is to hard to add a new translation file or to change a lot of existing translation strings, you can open an issue in the [client repo](https://github.com/openslides/openslides-client)

So there is nothing to do here.

One hint: You will probably get better help from us, if you don't call our work "crap".
