### ISSUE TITLE
Openslides behind haproxy and apache

### ISSUE THREAD

**Issue by thommierother** [OpenSlides/OpenSlides#6378]
Sorry not really a feature request but a documentation request.

I am struggeling with openslides 3.3 operating on the following setup:

1. central load balancer/ssl terminator haproxy, delivering https with LE certs
2. local apache for rev. proxy setup according to  https://github.com/OpenSlides/OpenSlides/issues/5596#issuecomment-729940572

I get a successful https connection for the openslides logon screen but after logon, the spinner never closes.  
There is also an issue with http mentioned at https://github.com/OpenSlides/OpenSlides/issues/6335 but nor confirmed yet ...

Does anybody have an idea how to solve or at least debug my problem?

**Comment by tsiegleauq** [comment]
Similar questions did occur sometimes. The configuration of your backend is, of course, not in the scope of the software.
Perhaps the other issues might help you to get started:

https://github.com/OpenSlides/OpenSlides/issues/5840
https://github.com/OpenSlides/OpenSlides/issues/5824
https://github.com/OpenSlides/OpenSlides/issues/5840

The loading indicator can mean many things. The JS Console usually has more information about what is going on.

**Comment by thommierother** [comment]
Shure, backend operation is not part of the software itself. But it would be helpful to see some working examples for discussion. This would help in a case where other SW products in the same environment work without problems, except OpenSlides ...
