### ISSUE TITLE
Wrong Form Shown

### ISSUE THREAD

**Issue by m-andreas** [OpenSlides/OpenSlides#6399]
**Describe the bug**
Wrong Form Loaded when clicking + Icon ( User Form Expected)

**How to Reproduce**
1. Go to https://youropenslidesurl.com/committees/1
2. Click on the +  in the Top Right

**Expected behavior**
Form for new User

**System information**

- OpenSlides-Version: 4 beta

**Comment by jsangmeister** [comment]
This is working as intended. You are in the committee detail view and the plus button will create a meeting in this committee. If you want to create users, you can do this via the "Accounts" view, where you can also assign them to a committee, if needed.

**Comment by m-andreas** [comment]
OK Thanks!
