### ISSUE TITLE
Can't edit Home page text

### ISSUE THREAD

**Issue by akemper** [OpenSlides/OpenSlides#6403]
**Describe the bug**
When I try to change the predefined text on Home / Startseite I just get a server error.

**How to Reproduce**
Try to save the edit of this section after clicking on the pen icon.

**Expected behavior**
Changes to be confirmed

**System information**
- OpenSlides-Version: 3.4.1
- Device: Server
- OS: Debian 10
- Browser: Firefox latest version

**Screenshots**
server_1        | [2022-04-17 23:23:41 +0200] [114] [WARNING] openslides.requests.errors [zYaI] /rest/core/config/bulk_update/ 1 unknown exception: clean() got an unexpected keyword argument 'styles'
server_1        | [2022-04-17 23:23:41 +0200] [114] [ERROR] django.request Internal Server Error: /rest/core/config/bulk_update/
server_1        | Traceback (most recent call last):
server_1        |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
server_1        |     response = get_response(request)
server_1        |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
server_1        |     response = self.process_exception_by_middleware(e, request)
server_1        |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
server_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
server_1        |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
server_1        |     return view_func(*args, **kwargs)
server_1        |   File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 125, in view
server_1        |     return self.dispatch(request, *args, **kwargs)
server_1        |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
server_1        |     response = self.handle_exception(exc)
server_1        |   File "/app/openslides/utils/rest_api.py", line 136, in handle_exception
server_1        |     return super().handle_exception(exc)  # type: ignore
server_1        |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
server_1        |     self.raise_uncaught_exception(exc)
server_1        |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
server_1        |     raise exc
server_1        |   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
server_1        |     response = handler(request, *args, **kwargs)
server_1        |   File "/app/openslides/core/views.py", line 466, in bulk_update
server_1        |     config[entry["key"]] = entry["value"]
server_1        |   File "/app/openslides/core/config.py", line 172, in __setitem__
server_1        |     value = validate_html_permissive(value)
server_1        |   File "/app/openslides/utils/validate.py", line 117, in validate_html_permissive
server_1        |     return base_validate_html(html, allowed_tags_permissive)
server_1        |   File "/app/openslides/utils/validate.py", line 126, in base_validate_html
server_1        |     html, tags=allowed_tags, attributes=allowed_attributes, styles=allowed_styles
server_1        | TypeError: clean() got an unexpected keyword argument 'styles'
server_1        | [2022-04-17 23:23:41 +0200] [114] [INFO] openslides.utils.timing [zYaI] request: 1: 0.01458 2: 0.00000 sum: 0.01459

**Comment by jsangmeister** [comment]
This is probably related to an update to the `bleach` package. The versioning issue will be fixed with https://github.com/OpenSlides/OpenSlides/pull/6401. If you want, you can go ahead and try if the PR fixes your problem or wait until we merge it. If you do the former, make sure to completely shut down all containers before rebuilding them or the update won't be applied.

**Comment by akemper** [comment]
It's working with the updated installation instructions.
