### ISSUE TITLE
New translation language request approvals are not proceeding on Transifex!

### ISSUE THREAD

**Issue by heidiwenger** [OpenSlides/OpenSlides#6478]
About 95% of the world don't speak English as a first language, and 75% don't speak English at all, so these things, i think, are important.

**Comment by tsiegleauq** [comment]
Thanks for bringing this up. We generally tend to trust language contributors who provide new languages over transifex.

Czech, Italian, Russian, French and Portuguese were successfully provided by community members already, what did you contribute and what happened?

**Comment by heidiwenger** [comment]
> Thanks for bringing this up. We generally tend to trust language contributors who provide new languages over transifex.
> 
> Czech, Italian, Russian, French and Portuguese were successfully provided by community members already, what did you contribute and what happened?

Noi mean: for example the Finnish language has been REQUESTED, but the request has not been handled in any way. It is there on the queue to be approved!

**Comment by heidiwenger** [comment]
![Screenshot from 2022-09-19 16-11-23](https://user-images.githubusercontent.com/82445727/191025112-9adab6cb-19e1-4107-b8e8-820856f34d7f.png)

See? So the willing translators for Finnish cannot get to work. Also Estonian is missing, yet REQUESTED. 

https://explore.transifex.com/openslides/openslides/

**Comment by jsangmeister** [comment]
Finnish is now accepted and can be translated. I see no request for Estonian - if that is still relevant, feel free to create a new one.
