### ISSUE TITLE
Initial logon with superadmin / superadmin not working

### ISSUE THREAD

**Issue by zell-mbc** [OpenSlides/OpenSlides#6536]
Hi there, I wanted to try out OpenSlides and somehow embarrassingly get stuck with the superadmin user account.

OpenSlides is running behind Nginx, Letsencrypt certificate and I can get to the site just fine. By the way, super easy setup, didn't take more than 10 minutes.

However, when trying to logon with superadmin / superadmin as per the documentation I get a wrong password error?
I did look around and found what might be password file for this user:
```
  cat ./secrets/superadmin          
  superadmin% 
```
Looks ok to me?
Anyone got an idea what might be going on?

**System information**

- OpenSlides-Version:  Don't really know, whatever 'wget github.com/…releases/download/latest/openslides' delivers today
- docker-compose version 1.29.2, build unknown
- OS: Ubuntu 22.04.1 LTS x86_64
- Browser: Tried Firefox, Chromium, Safari

![image](https://user-images.githubusercontent.com/29018767/212468253-2c35140c-82f9-4a26-8236-c3a9140d8895.png)

By the way, you got a typo in your documentation:
![image](https://user-images.githubusercontent.com/29018767/212468586-cd677cac-cf8d-4b5d-943a-4e57454325b1.png)

**Comment by jsangmeister** [comment]
If that is really your content of the password file and not just a typo, your password is `superadmin%` and not `superadmin` ;) Otherwise please report back and we'll investigate.

**Comment by zell-mbc** [comment]
I think that % is just the CR/LF, so yes, that's what's in my file :-)
I didn't touch it all, just browsing around as things didn't work as expected.

![image](https://user-images.githubusercontent.com/29018767/212471305-55244baa-39e6-4a56-a9cb-b21f43210c8b.png)

**Comment by normanjaeckel** [comment]
Please provide some log output and have a look at the db with the `openslides` tool:

```bash
$ ./openslides get user
$ docker-compose logs
```
Thanks.

**Comment by zell-mbc** [comment]
Thanks guys for getting back so quickly.

Both commands led to: 
`Error: connecting to gRPC server: creating gRPC client connection with grpc.DialContext(): context deadline exceeded`

And I realize I may have forgotten to do the data initialization the first time round

So what I now did was the following:
1. removed the old images, `sudo docker-compose down --rmi all`
2. Pulled the images again via `sudo docker-compose pull && sudo docker-compose up`
3. Let things settle down before pulling the log
[log.txt](https://github.com/OpenSlides/OpenSlides/files/10417407/log.txt)

4. Tried to initialize the db again
  `sudo ./openslides initial-data    
  Error: connecting to gRPC server: creating gRPC client connection with grpc.DialContext(): context deadline exceeded`

**Comment by InterFelix** [comment]
I believe this is due to the missing initialization.
Keep in mind the docker-compose.yaml creates a volume for postgres that's not removed whenever you want to start over.
So you have to execute `docker-compose down` followed by `docker volume prune` in order to remove this volume.
If you start over without removing the postgres volume, OpenSlides won't come up correctly because the old postgres credentials are still found in the volume so postgres uses them, but the OpenSlides containers try to use the newly generated credentials.

Once you've done that, re-run `./openslides setup .`, `docker-compose up -d` and `./openslides initial-data`.

However, this is where I run into another problem:
I still cannot log in with superadmin credentials.
It seems to recognize the credentials, because I get a "wrong password" message for other credentials, but still, OpenSlides doesn't load. I get the perpetually spinning circle:
![grafik](https://user-images.githubusercontent.com/29462559/212475680-361f49ca-3a3f-4315-b499-df32b4f1bd93.png)

Logs don't reveal much, everything looks normal:

```log
proxy_1             | {"level":"error","ts":1673704913.646304,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:53 +0000] "GET /login HTTP/1.1" 200 858 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:53 +0000] "GET /runtime.e3beb01ee04a191c.js HTTP/1.1" 200 3686 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:53 +0000] "GET /polyfills.f17aba8021711a30.js HTTP/1.1" 200 13438 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:53 +0000] "GET /main.3ffa7078e506ed0b.js HTTP/1.1" 200 717279 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:53 +0000] "GET /scripts.3e8686243e9e85f6.js HTTP/1.1" 200 13073 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:53 +0000] "GET /fira-sans-latin-400.f3ad8fc78ed45cf1.woff HTTP/1.1" 200 57536 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:53 +0000] "GET /styles.87022618430d6e05.css HTTP/1.1" 200 73206 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:53 +0000] "GET /fira-sans-latin-400.f3ad8fc78ed45cf1.woff HTTP/1.1" 200 57536 "https://openslides.example.com/styles.87022618430d6e05.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /assets/i18n/en.json HTTP/1.1" 200 0 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /2067.232a302eeed70a72.js HTTP/1.1" 200 6469 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /assets/img/favicon.png HTTP/1.1" 200 581 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /assets/i18n/de.json HTTP/1.1" 200 30702 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /5115.fa2a8e4914aa26f1.js HTTP/1.1" 200 1508 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /9043.b4f68a9d4611dbc5.js HTTP/1.1" 200 17052 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /common.2df474e8e1571885.js HTTP/1.1" 200 13054 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /9867.8ed4c1d0f219ceee.js HTTP/1.1" 200 3571 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /assets/img/openslides-logo-dark.svg HTTP/1.1" 200 17589 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /8128.115c0cfc85faccdc.js HTTP/1.1" 200 2186 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /3505.e006a20719fc03b7.js HTTP/1.1" 200 4666 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /1326.986da7a11961883f.js HTTP/1.1" 200 3891 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /1688.08c29ce51c027ccf.js HTTP/1.1" 200 2196 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /5224.d01e71fe142b2f40.js HTTP/1.1" 200 1521 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /8243.2234c2b6f6f51aa3.js HTTP/1.1" 200 1682 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /159.cc3962ac4ce872bf.js HTTP/1.1" 200 1832 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /6355.5dd5003a71c471e0.js HTTP/1.1" 200 1330 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /8437.fb4808b664f73523.js HTTP/1.1" 200 20038 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /2931.b0c9f8fd5b18675f.js HTTP/1.1" 200 2526 "https://openslides.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /fira-sans-latin-500.0dbff61e75912d22.woff HTTP/1.1" 200 58088 "https://openslides.example.com/styles.87022618430d6e05.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:54 +0000] "GET /MaterialIcons-Regular.d1b99623aaa86364.woff2 HTTP/1.1" 200 125116 "https://openslides.example.com/styles.87022618430d6e05.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
auth_1              | 2023-01-14T14:01:54.714Z http://openslides.example.com: POST -- /system/auth/who-am-i/
datastoreReader_1   | [2023-01-14 14:01:54 +0000] [9] [INFO] GET-request: {'fqid': 'user/1', 'mapped_fields': ['id', 'username', 'password', 'is_active', 'meta_deleted']}
auth_1              | 2023-01-14T14:01:54.847Z http://openslides.example.com: POST -- /system/auth/who-am-i/
datastoreReader_1   | [2023-01-14 14:01:54 +0000] [12] [INFO] GET-request: {'fqid': 'user/1', 'mapped_fields': ['id', 'username', 'password', 'is_active', 'meta_deleted']}
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:55 +0000] "GET /ngsw-worker.js HTTP/1.1" 200 18045 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
client_1            | 172.31.0.11 - - [14/Jan/2023:14:01:59 +0000] "GET /ngsw.json?ngsw-cache-bust=0.5697966158816652 HTTP/1.1" 200 9726 "https://openslides.example.com/ngsw-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
auth_1              | 2023-01-14T14:02:03.499Z http://openslides.example.com: POST -- /system/auth/login/
datastoreReader_1   | [2023-01-14 14:02:03 +0000] [12] [INFO] FILTER-request: {'collection': 'user', 'filter': {'field': 'username', 'value': 'superadmin', 'operator': '='}, 'mapped_fields': ['id', 'username', 'password', 'is_active', 'meta_deleted']}
datastoreWriter_1   | [2023-01-14 14:02:03 +0000] [25] [INFO] Created position 11
datastoreWriter_1   | [2023-01-14 14:02:03 +0000] [25] [INFO] Events executed (1 UPDATE)
datastoreWriter_1   | [2023-01-14 14:02:03 +0000] [25] [INFO] UPDATE: ['user/1']
auth_1              | 2023-01-14T14:02:03.568Z http://openslides.example.com: POST -- /system/auth/who-am-i/
datastoreReader_1   | [2023-01-14 14:02:03 +0000] [13] [INFO] GET-request: {'fqid': 'user/1', 'mapped_fields': ['id', 'username', 'password', 'is_active', 'meta_deleted']}
```

**Comment by InterFelix** [comment]
I have just now realized, whenever I try to log in, after a couple of minutes, I get a bunch of proxy messages like this one:
```log
proxy_1             | {"level":"error","ts":1673704983.5277898,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
```

**Comment by zell-mbc** [comment]
<<creates a volume for postgres that's not removed >>

Absolutely correct, I realized that after posting and have since moved the database from a docker volume to a local folder via changing the volume statement in docker compose to this:
`volumes:
      - ./postgres-data:/var/lib/postgresql/data`

because that's what I do with all my other compose environments and because I like to keep things together.

And after restarting I can see that it's starting to an empty database. But even then I get the `Error: connecting to gRPC server: creating gRPC client connection with grpc.DialContext(): context deadline exceeded` when trying to initialize.

I also see the proxy error you mention…and I am glad I am not the only one with this issue :-)

**Comment by InterFelix** [comment]
Have you by any chance modified the port proxy_1 is exposing? I haven't had any luck with a port other than 8000.
There is a cli flag `-a` you can supposedly use to specify an address like `localhost:8001`, but I haven't had any luck with that either. 
I've even moved to an entirely different VM for testing purposes.
When I launch the default configuration without changing anything (except for the System URL) and execute `./openslides initial-data` without any options, at least this command completes successfully.

**Comment by zell-mbc** [comment]
I haven't, the only changes I made were adding my email details and `enableLocalHTTPS: false` to my customization.yml file. And then changing the postgres volume as mentioned higher up other than that I didn't touch anything.

**Comment by normanjaeckel** [comment]
Try the `--no-ssl` flag of the `openslides` command.

**Comment by zell-mbc** [comment]
Aha, getting there :-)
```
sudo ./openslides initial-data --no-ssl        
Initial data were set successfully.


senak at senak in /opt/docker/openslides
$ ./openslides get user --no-ssl
{"1":{"id":1,"password":"47b1752e3c31d78c12cb5b7534f6338d3c935aba27c5b82c3625c01146a53fb64jVSJtTkcWEnT+Qof8jDzPOnYg/mk+/qMDHcH7N8RLIhi5FF2nK2ZS58zDXytKqcOnjDFRjWJOTpZzL+GxS+9A==","username":"superadmin","is_active":true,"last_name":"Administrator","meta_deleted":false,"meta_position":2,"organization_id":1,"is_physical_person":true,"default_vote_weight":"1.000000","can_change_own_password":true,"organization_management_level":"superadmin"}}

```

Both commands completed successfully, and now I am stuck where @InterFelix is stuck.
The credentials were accepted by the look of it but it doesn't move beyond the logon screen, stuck with a spinning wheel:

![image](https://user-images.githubusercontent.com/29018767/212481823-299c83be-4b59-4178-b2ee-76237655c4e5.png)

Proxy_1 is giving these errors:
```
proxy_1             | {"level":"error","ts":1673712125.6814332,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
proxy_1             | {"level":"error","ts":1673712125.681442,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
proxy_1             | {"level":"error","ts":1673712131.2804544,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
```

Is there maybe something particular which needs to be in the nginx config file? Right now mine is very basic:

```
server {
    server_name openslides.bakdos.de;

        location / {
            proxy_pass http://localhost:8000;
            proxy_set_header   Host               $host:$server_port;
            proxy_set_header   X-Real-IP          $remote_addr;
            proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto  $scheme;
            proxy_set_header   Upgrade            $http_upgrade;
            proxy_set_header   Connection         "upgrade";
        }
    listen 443 ssl; # managed by Certbot
    …
```

```

**Comment by peb-adr** [comment]
I could imagine this basic ngnix configuration doesn't allow HTTP2 connections to be made.
The autoupdate service which feeds the data into the client after login needs to be able to establish a HTTP2 connection

**Comment by InterFelix** [comment]
My config contains `listen 443 ssl http2;`, I did this after seeing a message about http2. The message isn't displayed anymore, but I still can't log in.

**Comment by zell-mbc** [comment]
> I could imagine this basic ngnix configuration doesn't allow HTTP2 connections to be made. The autoupdate service which feeds the data into the client after login needs to be able to establish a HTTP2 connection

I replaced my `listen`statement with this:
`    listen 443 ssl http2;
    listen [::]:443 ssl http2;
`
restartet both nginx and the docker containers (just in case) and…drum roll…I'm in.

**Comment by InterFelix** [comment]
umm... That's really curious.
My setup involves no IPv6 anywhere, and my `listen` statement already includes the `http2` directive...

Regardless, I tried. No luck.
Can you send your nginx site file for reference? I believe my config is basically the same, but just to be sure...

**Comment by zell-mbc** [comment]
I am happy to send my config, but looks like I sounded the bell too early, when returning to my session I saw I was logged out, and when trying to logon again stuck again at the spinning wheel and the proxy error higher up. 

So I tried to restart the images and just as things started to shut down my browser gets through...
Need to play with this some more I guess…

**Comment by InterFelix** [comment]
Okay, that's what I observed too. For some reason, when the services are shutting down, the login goes through (or at least i looks like it does, since you can't actually do anything because the services are shut down)

Happened on all browsers and devices (Firefox desktop, Chrome desktop and Firefox on Android) I had tried this on.

**Comment by zell-mbc** [comment]
Restart right away and continue on with the session which just got through, it will still work…until you drop out for a reason after which you can't logon again.

Happened again just now again.
So I guess my initial problem is fixed, but we seem to deal with a nginx compatibility issue? Question for the OpenSlides team, shall I close this one and open another issue?

**Comment by InterFelix** [comment]
Probably, this has gotten quite convoluted.
