### ISSUE TITLE
Ability to create groups of multiple users and select them as submitters of motions

### ISSUE THREAD

**Issue by InterFelix** [OpenSlides/OpenSlides#6546]
**Is your feature request related to a problem? Please describe.**
Our organisation has a number of working groups, each devoted to a specific topic.
In one of our committees, these working groups have the right to file motions.
Currently, there is no clean way to have these working groups be listed as submitters of motions.

**Describe the solution you'd like**
I would like to be able to create "groups" of users in the account management section of OpenSlides to map the working groups into our OpenSlides instance. Of course, to really be useful, it would be necessary to be able to select these "groups" as submitters of motions.

**Describe alternatives you've considered**
I'm aware that I can create new committees in order to map the working groups, but since the working groups have no need to use OpenSlides for their meetings, it's a bit overkill and would make my job as chairman of the committee more complicated than it needs to be, since I would have to first create a committee in OpenSlides for the working group, create a meeting for that committee, create a motion, mark it as accepted and forward it to the committee I actually want to create the motion for.
The more obvious workaround would be to create an account for each working group, but since all members of these working groups are members of the committee as well, these accounts would not be used for anything other than to be selected as submitters of motions and only clutter up the accounts overview. The cleaner solution would be groups of some kind.

**Comment by InterFelix** [comment]
I just saw forwarding committees are also treated as accounts.
I don't think this is a particularly useful behaviour, but it makes me think my second "workaround" is the intended way to solve my problem.

**Comment by jsangmeister** [comment]
Yes, you are right, your second approach would be the "intended" way to solve this, if you want to call it that ;) (The solution to create users for the forwarding committees was one with much discussion, we are aware of the drawbacks of this, but came to the conclusion that it was the most effective regarding all factors and circumstances.)

Implementing such a feature sounds pretty specific to your use case (although I'm not too familiar with the workflow of other organizations) and the work to implement this IMO outweighs the drawback to use the workaround, so I don't think this will be implemented anytime soon. Thank you for your suggestion anyway!

**Comment by InterFelix** [comment]
Okay, thanks for the clarification! Closing.
