### ISSUE TITLE
3 to 4 Upgrade instructions

### ISSUE THREAD

**Issue by thegcat** [OpenSlides/OpenSlides#6551]
Is there any upgrade path from OpenSlides 3 to 4 and is it documented somewhere?

Either way this should be added somewhere in the README or the INSTALL instructions, so that people install OpenSlides are aware if whether data from previous installations can be migrated or not.

**Comment by jsangmeister** [comment]
Yes, you can export your OS3 instance as JSON (Settings -> dot menu -> Export to OpenSlides4) and then import it as a meeting in your new OS4 instance (Committees -> <your committee> -> dot menu -> Import meeting). I agree that this should be documented.
