### ISSUE TITLE
Motion forwarding does not work as expected

### ISSUE THREAD

**Issue by InterFelix** [OpenSlides/OpenSlides#6563]
**Describe the bug**
When forwarding a motion from one meeting to a meeting of another committee, the motion is not forwarded correctly.
The message card always states "0 motions successfully forwarded", 

**How to Reproduce**
1. Create two committees
2. Create a meeting for each committee
3. Allow committee No.1 to forward motions to committee No.2 
4. Create a motion in the meeting for committee No.1
5. Forward this motion to the meeting of committee No.2
6. The message "0 motions successfully forwarded" will be shown
7. The motion will not appear in the meeting of committee No.2

**Expected behavior**
The motion is correctly forwarded and appears in the meeting for committee No.2.

**System information**
- OpenSlides-Version: 4.0
- Device: any
- OS: any
- Browser: any

**Additional context**
There is no error message in the output of `docker-compose logs`, the only relevant entries are:
```logs
backendAction_1     | INFO:openslides_backend.shared.handlers.base_handler:Performing action motion.create_forwarded.
backendAction_1     | INFO:openslides_backend.shared.handlers.base_handler:Request was successful. Send response now.
```

**Comment by InterFelix** [comment]
This was exactly it.
I was not aware forwarding was not allowed by default in any state, so I assumed the feature was broken after trying in every possible state.

**Comment by jsangmeister** [comment]
Nice, happy to help. I agree that this was confusing (which is why we fixed it) - also because the backend did not send any errors, as you noticed as well.
