### ISSUE TITLE
Internal Server Error popup

### ISSUE THREAD

**Issue by tanjix** [OpenSlides/OpenSlides#6565]
Hi Guys,

I recently upgraded to OpenSlides Version: 4.0.1-main-20230309-497e22e

When trying to save some settings, e.g. under "Settings" on the left menu, I get a popup at the footer saying:

`<html> <head> <title>Internal Server Error</title> </head> <body> <h1><p>Internal Server Error</p></h1> </body> </html> `

Settings are not saved.

What can I do?

Thanks!

**Comment by tanjix** [comment]
I found this on the logs:

```
backendAction_1     | [2023-03-09 16:25:51 +0000] [10] [ERROR] Error handling request /system/action/handle_request
backendAction_1     | Traceback (most recent call last):
backendAction_1     |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
backendAction_1     |     keepalive = self.handle_request(req, conn)
backendAction_1     |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
backendAction_1     |     respiter = self.wsgi(environ, resp.start_response)
backendAction_1     |   File "/app/openslides_backend/http/application.py", line 103, in __call__
backendAction_1     |     return self.wsgi_application(environ, start_response)
backendAction_1     |   File "/app/openslides_backend/http/application.py", line 93, in wsgi_application
backendAction_1     |     response = self.dispatch_request(request)
backendAction_1     |   File "/app/openslides_backend/http/application.py", line 44, in dispatch_request
backendAction_1     |     response_body, access_token = view_instance.dispatch(request)
backendAction_1     |   File "/app/openslides_backend/http/views/base_view.py", line 117, in dispatch
backendAction_1     |     return func(request)
backendAction_1     |   File "/app/openslides_backend/http/views/action_view.py", line 30, in action_route
backendAction_1     |     assert_migration_index()
backendAction_1     |   File "/app/openslides_backend/migrations/__init__.py", line 33, in assert_migration_index
backendAction_1     |     datastore_migration_index = get_datastore_migration_index()
backendAction_1     |   File "/app/openslides_backend/migrations/__init__.py", line 23, in get_datastore_migration_index
backendAction_1     |     datastore_migration_index = read_db.get_current_migration_index()
backendAction_1     |   File "/usr/local/lib/python3.10/site-packages/datastore/shared/postgresql_backend/sql_read_database_backend_service.py", line 347, in get_current_migration_index
backendAction_1     |     raise InvalidDatastoreState(
backendAction_1     | datastore.shared.util.exceptions.InvalidDatastoreState: The datastore has inconsistent migration indices: Minimum is 27, maximum is 39.
```

However, I did the upgrade and it returned no errors to me:

```
(...)
Position 1142 from MI 27 to MI 39 ...
Position 1143 from MI 27 to MI 39 ...
Position 1144 from MI 27 to MI 39 ...
Position 1145 from MI 27 to MI 39 ...
Position 1146 from MI 27 to MI 39 ...
Position 1147 from MI 27 to MI 39 ...
Done. Finalizing is still needed.
root@ga:~/openslides# ./openslides migrations finalize -a MYIPADDRESS:443
Progress:
Finalize migrations.
No migrations to apply, but finalizing is still needed. Current migration index: 39
Cleaning collectionfield helper tables...
Calculate helper tables...
Deleting all migration keyframes...
Swap events and migration_events tables...
Set the new migration index to 39...
Clean up migration data...
root@ga:~/openslides#
```

I suspect, according to the error on the log, there's an issue with the upgrade.
What can I do?

Thanks!

**Comment by jsangmeister** [comment]
Hi, sorry for the late answer. If it's still relevant and for future reference: I'm unsure of the origin of this error, but assuming the migrations where indeed successfull, you can manually set the migration index to your current version by executing `UPDATE positions SET migration_index=39`. This may however have unusual errors as a consequence if the migrations were for some reason not successful.

**Comment by chengler** [comment]
I do have the same problem when following the install instructions of openslides 4 when entering `./openslides initial-data`

`./openslides check-server` gives a `Server is ready.`

where to enter `UPDATE positions SET migration_index=39` ?

**Comment by jsangmeister** [comment]
This is not a general solution, but rather a last resort. Try other things like restarting the whole stack first (there currently is a known caching problem with the migration index, so this might already help) or running `./openslides migrations finalize".

What exactly is your error when executing `./openslides initial-data`? It sounds like another problem.


If you however want to try it anyway (be warned that this may make your database unusable!), you can run the following command to forcefully update the migration index: 
```
docker-compose exec postgres psql openslides -U openslides -c 'UPDATE positions SET migration_index=39'
```
(You must be in the same folder as the openslides executable and the generated docker compose file for this to work. Also, you must use the maximum migration index available as given by the `./openslides migrations finalize` command.)
