### ISSUE TITLE
Release 4.0.1-main-20230413-c48d340 was for PR contents

### ISSUE THREAD

**Issue by res2k** [OpenSlides/OpenSlides#6574]
**Describe the bug**
I'm running OpenSlides using Docker Compose, as described in the install instructions.
I just so happened to pull the "latest" images.
I was curious what changes that may include, so I checked the version number, which is "OpenSlides Version: 4.0.1-main-20230413-c48d340".
However, on close inspection of the commit hash, I noticed that this commit is _not_ part of the actual main branch! Rather, it's a commit in a PR (specifically, #6573).

So it seems merely creating a PR can trigger a new release?
Is that intended?

**How to Reproduce**
Steps to reproduce the behavior: preferably on [nighty](https://nightly.demo.openslides.org)

1. Pull "latest" OpenSlides images from GHCR
2. Check version in Legal Notice

**Expected behavior**
OpenSlides images contain "main" branch changes exclusively. I can't create & publish images by creating a PR.

**Comment by res2k** [comment]
OK, I realized this is probably invalid: reviewing the GH Actions the "Build Docker images" actions was apparently triggered manually.
So most likely a human mistake.

Still, I'll leave this bug open for now... I think it's at least discussion-worthy, and perhaps some additional measures to reduce the future likelihood of such "PR releases" can be provided.

**Comment by jsangmeister** [comment]
Thanks for the report! I suppose this happened because https://github.com/OpenSlides/OpenSlides/pull/6573 was pushed directly to a branch in the repository instead of a fork and the workflow has no restriction as to which branches it should run on. I will change this ASAP.
