### ISSUE TITLE
Use redis:alpine?

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/OpenSlides#6593]
I would like to use the `redis:alpine` image rather than `redis:latest` (debian based) for production.
In order to keep dev and prod setup similar, would it be a problem for anyone to change the `docker-compose.dev.yml` to use `redis:alpine`?

**Comment by jsangmeister** [comment]
I don't see any problem with it, functionality-wise it should be the same

**Comment by ostcar** [comment]
@normanjaeckel Can you also make the change in the manage-tool?

**Comment by peb-adr** [comment]
https://github.com/OpenSlides/OpenSlides/pull/6602
https://github.com/OpenSlides/openslides-vote-service/pull/204
https://github.com/OpenSlides/openslides-manage-service/pull/223

have been merged. Closing.
