### ISSUE TITLE
Issues upgrading to 4.0.7 from 4.0.6 on new install

### ISSUE THREAD

**Issue by colinmahns** [OpenSlides/OpenSlides#6633]
**Describe the bug**
Upgrading from 4.0.6 to 4.0.7 on a self-hosted instance of OpenSlides does not successfully work after following the install instructions in INSTALL.md. `openslides` admin tool does not appear to be aware of new changes to OpenSlides in v4.0.7 when running the container configuration command. 

**How to Reproduce**

1. Update `tag:` to `4.0.7` in `config.yml`
2. Run `openslides config -c config.yml .`
3. `docker compose up --detatch`
4. Visit OpenSlides in Browser

**Expected behavior**
OpenSlides will be updated to version 4.0.7 and load in user browsers. 

**System information**
- OpenSlides version: 4.0.6
- Additional version information (if any): N/A
- Device: Desktop, Android
- OS: Debian 12, Android 11
- Browser: Firefox (Linux and Android)
- Browser version: 116

**Additional context**
The new `docker-compose.yml` file for version 4.0.7 does not upgrade the new variable names per [INSTALL.md](https://github.com/OpenSlides/OpenSlides/blob/main/INSTALL.md#update-to-a-new-version)
> Incompatibilities
 > 4.0.7
>  The environment variables DATASTORE_DATABASE_* were renamed to DATABASE_*. If custom values were used, this must be reflected in config files.

Manually updating docker-compose.yml to the new variable names does not resolve this issue. This is also overridden each time I run `openslides config -c config.yml` which reverts the `DATABASE_*` variables back to `DATASTORE_DATABASE_*`

**Screenshots**
N/A

**Comment by peb-adr** [comment]
Hello!

Thanks for pointing out flaws in the described update process.
I think the cause of problems has two major roots:

1. The change of the environment variables names is actually not yet included in 4.0.7 . It was planned, but will come in 4.0.8 . So sorry for the oversight in the document.

However with that I would think that if in your `docker-composel.yml` the vars are still named `DATASTORE_DATABASE_*` the instance should actually update like expected. Some more info would be helpful e.g.
  - what makes you conclude the update hasn't worked? The notification in the client can sometime take a bit longer to appear (a force reload with Ctrl+F5 can fetch the new client immediately)
  - output of `docker-compose ps` after running `docker-compose up -d` to see if the new images were applied correctly
  - output of `docker-compose logs` if the instance for some reason seems to not startup correctly

2. The manage-tool is lacking proper versioning. While the versioning was fixed for the openslides services images the manage-tool was forgotten. I will look into fixing that too and adjust the docs such that it's clear which version of the `openslides` binary can / is needed to operate which version of OpenSlides docker stack.

I think at this point I would recommend skipping 4.0.7 for now and wait for 4.0.8.

**Comment by Magolv** [comment]
Hello!

I had the exact same problem when upgrading from version `4.0.6` to `4.0.7` via `docker-compose pull` some days ago.
I could not log in to OpenSlides and saw only an page with a spinning sign, waiting for the login page to load.

The container `openslides_auth_1` did not start properly and was not listed as running in the output from `docker compose ps`.

In your output from `docker compose ps` the `openslides_auth_1` is missing as well.
In your output from `docker compose logs` I find the same error I had:

> openslides-auth-1              | redis:6379 is available
openslides-auth-1              | redis:6379 is available
openslides-auth-1              | 2023-08-15T12:07:49.358Z Database: redis:6379
openslides-auth-1              | 2023-08-15T12:07:49.443Z Database: redis:6379
openslides-auth-1              | 2023-08-15T12:07:49.444Z Message bus: redis:6379
openslides-auth-1              | node:internal/fs/utils:347
openslides-auth-1              |     throw err;
openslides-auth-1              |     ^
openslides-auth-1              | 
openslides-auth-1              | 
**openslides-auth-1              | Error: ENOENT: no such file or directory, open '/run/secrets/internal_auth_password'**
openslides-auth-1              |     at Object.openSync (node:fs:590:3)
openslides-auth-1              |     at Object.readFileSync (node:fs:458:35)
openslides-auth-1              |     at SecretService.readFile (/app/api/services/secret-service.js:57:29)
openslides-auth-1              |     at SecretService.loadSecrets (/app/api/services/secret-service.js:49:47)
openslides-auth-1              |     at new SecretService (/app/api/services/secret-service.js:19:14)
openslides-auth-1              |     at Function.factory (/app/node_modules/final-di/dist/cjs/di/container.js:46:30)
openslides-auth-1              |     at /app/node_modules/final-di/dist/cjs/decorators/factory.js:7:47
openslides-auth-1              |     at DecorateProperty (/app/node_modules/reflect-metadata/Reflect.js:553:33)
openslides-auth-1              |     at Reflect.decorate (/app/node_modules/reflect-metadata/Reflect.js:123:24)
openslides-auth-1              |     at Object.__decorate (/app/node_modules/tslib/tslib.js:99:96) {
openslides-auth-1              |   errno: -2,
openslides-auth-1              |   syscall: 'open',
openslides-auth-1              |   code: 'ENOENT',
openslides-auth-1              |   path: '/run/secrets/internal_auth_password'
openslides-auth-1              | }

As a workaround I simply changed the `docker-compose.yml` from this:
```
auth:
    image: ghcr.io/openslides/openslides/openslides-auth:latest
```
to this:
```
auth:
    image: ghcr.io/openslides/openslides/openslides-auth:4.0.6
```

With `docker-compose pull` the `openslides_auth_1` container will now revert back to version `4.0.6`.
In my case that did the trick so far and my system is running again.

**Comment by peb-adr** [comment]
I'm sorry for the problems with the update.
If you get this error
```
openslides-auth-1 | Error: ENOENT: no such file or directory, open '/run/secrets/internal_auth_password'
```
the problem is that the auth service is missing the secret `internal_auth_password` since the implementation of SSO via SAML.

One quick solution is to revert `auth` to `4.0.6` as @Magolv described.
This can also be done using the following snippet in your `config.yml`:
```yaml
services:
  auth:
    tag: 4.0.6
```
(also see: https://github.com/OpenSlides/OpenSlides/blob/main/INSTALL.md#configuration-of-the-generated-docker-compose-yaml-file)

Another workaround is to edit the `docker-compose.yml` after generation (but before starting the stack) to include the missing secrets for the `auth` service.


For the coming update `4.0.8` this is already sorted out and I am currently working on improving the versioning for the manage-tool to prevent issues like this in the future.
