### ISSUE TITLE
Upgrade from V3.3 to V3.4 - Docker images missing

### ISSUE THREAD

**Issue by Zorgosto** [OpenSlides/OpenSlides#6640]
**Describe the bug**
We want to upgrade Openslides from version 3.3 to 3.4. When we first set up openslides we used the docker image for it. But now the docker images don't seem to exist anymore. We tried to export the data from 3.3 but the export feature was added in 3.4 and is not available in 3.3.

How could we upgrade from version 3.3 to 3.4 without losing data? Or how could we export the data on 3.3?
In the end we want to move to version 4.0.

**System information**

- OpenSlides version: 3.3
- OS: Ubuntu 20.04.6 LTS

**Comment by jsangmeister** [comment]
If the problem still persists, please reopen a new issue. OS3 is no longer maintained.
