### ISSUE TITLE
Add documentation for saml configuration – why is SP metadata an empty field?

### ISSUE THREAD

**Issue by im-fabian** [OpenSlides/OpenSlides#6642]
**Is your feature request related to a problem? Please describe.**
Yes it is: 4.0.5 added SAML as auth-option but I am unable to set it up due to a lack of documentation. The setup form requests attribute matching, IdP metadata, SP metadata and SP private key. 

All but SP metadata is selfexplainatory. Usually with software that offers SAML as a SP the **SP metadata** is provided by the SP software automaticly to be inported at the IdP. That OpenSlides as SP-Software requests one to enter the SP metadata is confusing.

**Describe the solution you'd like**
The best solution would be if a metadata url is provided where the metadata can be downloaded as xml. However as a workaround documentation what to enter in the form would be suitable.

**Describe alternatives you've considered**
There aren't any.

**Additional context**
![Settings_-_OpenSlides](https://github.com/OpenSlides/OpenSlides/assets/31921275/425c7af7-7429-4642-9e0c-e3d6e25afe8b)

**Comment by jsangmeister** [comment]
Since this is a first implementation of this feature, the settings must be entered manually in this version. In the future, we hope to automate this further.

We will add documentation for this feature. For now, the [example_metadata_sp.xml](https://github.com/OpenSlides/openslides-auth-service/blob/main/auth/src/example_metadata_sp.xml) might help you - this is an example for what should be entered in the field.

**Comment by DerUtz** [comment]
which X509Certificate should be used for the Service Provider?

**Comment by peb-adr** [comment]
You should be able to generate a keypair using
```
openssl req -new -x509 -days 3652 -nodes -out sp.crt -keyout sp.key
```

**Comment by sOUTHX1337** [comment]
any way to get some more docs - i'm quite struggling with keycloak. getting following error:

"Fehler: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received an instance of Object"

**Comment by rrenkert** [comment]
We have a basic SAML documentation in the [Wiki](https://github.com/OpenSlides/OpenSlides/wiki/SSO) now. The generation of SP metadata will be handled in a new issue in the auth-service/backend and is on our agenda.
Therefore I close here.
