### ISSUE TITLE
couldn't start; docker image doesn't exist

### ISSUE THREAD

**Issue by lix2303** [OpenSlides/OpenSlides#6662]
I followed the steps to install OpenSlides exactly as described on the page (https://github.com/OpenSlides/OpenSlides/blob/stable/3.4.x/README.rst#installation). When I got to the last step and wanted to start the software with "`docker-compose up`" I get an error message. It reads: "`Error response from daemon: pull access denied for openslides/openslides-client, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`". 

![Bild_2023-09-30_161028567](https://github.com/OpenSlides/OpenSlides/assets/145917485/cc55fa9e-99b3-49ab-8e7b-80331acec1a4)

It doesn't work after docker login either. 
Now when I search Docker itself for openslides/openslides-client, I find that it does not exist. 

What can I do now? Or have I made a mistake at some point? 

Thanks in advance. :)

**System information**
- OpenSlides version: i think 3.4.x
- Device: Notebook
- OS: Windows 11

**Comment by schlich** [comment]
did you figure this out? If you are still stuck, what is your output for `ls` and `pwd`?

**Comment by lix2303** [comment]
Hello schlich, 

thank you for your answer. No, unfortunately I have not yet found out what the problem is. I must also admit, I do not have the greatest idea about computers and programming. 

When I enter the command `ls`, I get the output `build.sh* docker-compose.dev.yml docker-compose.yml docker-compose.yml.m4 docker-stack.yml.m4 postgresql.dev.conf secrets/` . When I enter the `pwd` command, I get the output `/c/Users/#####/OpenSlides/docker` .

![Screenshot 2023-10-14 161536](https://github.com/OpenSlides/OpenSlides/assets/145917485/5c4bb970-cf78-4aff-8780-88701861a037)

I tried to install version 3 because, for one thing, I was directed to version 3.4 from the official OpenSlides site (https://openslides.com/de), and didn't question this initially. In addition, however, also that I could not really do much with the installation instructions of version 4 and was also a little overwhelmed with it. 

Thank you in advance. :-D

**Comment by jsangmeister** [comment]
Please try to install OpenSlides4. OpenSlides3 is no longer maintained and has limited support from our side.
