### ISSUE TITLE
Need help debugging mail

### ISSUE THREAD

**Issue by Poolitzer** [OpenSlides/OpenSlides#6682]
Hello there,

I tried adding email support to my selfhosted openslides instance. I copy pasted https://github.com/OpenSlides/OpenSlides/blob/main/INSTALL.md#email, inserted my credentials (double checked them), then ran setup to reconfigure the yaml, and restarted with docker-compose

I ran `docker-compose up` and when I press on send email in openslides, the following loglines appear.

```
backendAction_1     | INFO:openslides_backend.shared.handlers.base_handler:Performing action user.send_invitation_email.
backendAction_1     | INFO:openslides_backend.shared.handlers.base_handler:Request was successful. Send response now.

```
But neither do I get an email, nor does the website agree with that log line apparently :D It tells me something went wrong, potentially a problem communicating to the mail server.

How can I further debug this?

**Comment by jsangmeister** [comment]
Can you try again and look in the network tab what the actual response from the backend request is? In there, there should be additional details about the individual mail results.

**Comment by Poolitzer** [comment]
Found it, thanks!
_Unspecified mail connection exception on sending invitation email to server postfix, port 25: [Errno -2] Name or service not known_

And I probably forgot to delete the old docker-compose before trying to generate the new one. Thanks for pointing this out to me, have a good day.
