### ISSUE TITLE
Unclear effect of `SYSTEM_URL` setting

### ISSUE THREAD

**Issue by mdickopp** [OpenSlides/OpenSlides#6689]
**Describe the bug**

`INSTALL.md` states:

> You may at least want to customize the `SYSTEM_URL`. The variable is used to get the correct URL in PDF or email templates.

However, setting `SYSTEM_URL` does not seem to have any effect whatsoever. The URL in email templates, at least, is initially `https://example.com`, no matter what `SYSTEM_URL` is set to. (I have not tested generating PDFs.)

Furthermore, the only reference to `SYSTEM_URL` in the source code I can find is in the default config, so it is unclear to me which code, if any, is supposed to read the variable.

**How to Reproduce**

- Install OpenSlides according to instructions in `INSTALL.md`. Set `SYSTEM_URL` to any value (or leave it set to the default, `localhost:8000`) in the step where the instructions mention it.
- Set up a user with an email address.
- Send invitation email to the user.

**Expected behavior**

Either the value of `SYSTEM_URL` (the customized value or the default, `localhost:8000`) should be contained in the invitation email, or, if `SYSTEM_URL` is obsolete/has no effect intentionally, it should be removed from `INSTALL.md` and the default config.

**System information**

OpenSlides version: 4.0.9 or 4.016 (both show the issue)

**Comment by jsangmeister** [comment]
I will need to double check, but I think you are right - this is a remainder which we forgot to remove. The only currently relevant URL field should be `organization/url`. Thanks for spotting this!
