### ISSUE TITLE
Renaming default custom database and settings

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#673]
What do you think about inserting the version number in the default name of the settings and the database file. Esp. the database has to be updated when OpenSlides is upgraded to a new version but users might not find the reason for database errors for they might not find the database file hidden in the deep of their home directory.

**Comment by ostcar** [comment]
We decided to use migrations.

I let this pull request open as a reminder to add the migrations file before the release of the 2.0

**Comment by normanjaeckel** [comment]
We now have migrations, so this can be closed.
