### ISSUE TITLE
Update github actions to use docker compose v2

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/OpenSlides#6767]
As of april 1st docker-compose v1 was removed from the github action images and needs to be replaced. 

See https://github.com/actions/runner-images/issues/9557

Workflows that need adjustment:
- [x] [openslides-auth-service](https://github.com/OpenSlides/openslides-auth-service/blob/3a8530dff268472b0984a8e8e0a0658558ff21eb/.github/workflows/continuous-integration.yml) https://github.com/OpenSlides/openslides-auth-service/pull/333
- [x] [openslides-backend](https://github.com/OpenSlides/openslides-backend/blob/1d93105b42a596d42ea5b1cb30a10544bb9c626a/.github/workflows/continuous_integration.yml) https://github.com/OpenSlides/openslides-backend/pull/2349
- [x] [openslides-client](https://github.com/OpenSlides/openslides-client/pull/3501) https://github.com/OpenSlides/openslides-client/pull/3501
- [x] [openslides-datastore-service](https://github.com/OpenSlides/openslides-datastore-service/blob/fcf8b327ff0dc9440a06be50db38bcaccee5536c/.github/workflows/continuous_integration.yml) https://github.com/OpenSlides/openslides-datastore-service/pull/338
- [x] [openslides-media-service](https://github.com/OpenSlides/openslides-media-service/blob/5e6179b32e93661075d994f511528e6e82539589/.github/workflows/continuous_integration.yml) https://github.com/OpenSlides/openslides-media-service/pull/100
- [x] [openslides-vote-service](https://github.com/OpenSlides/openslides-vote-service/blob/439a0e75effb2b86d11277c91b129c8e247f7aa3/.github/workflows/test.yml) https://github.com/OpenSlides/openslides-vote-service/pull/261
- [x] [Openslides](https://github.com/OpenSlides/OpenSlides/pull/6769)
  - https://github.com/OpenSlides/OpenSlides/pull/6769
  - https://github.com/OpenSlides/OpenSlides/pull/6770
- [x] `openslides-meta`: https://github.com/OpenSlides/openslides-meta/pull/70
 
Aside from workflow adjustments it is also possible that Makefiles need to be updated.

**Comment by jsangmeister** [comment]
Added PRs to update the main repo docs and the meta Makefile. From my perspective, that should be all places

**Comment by jsangmeister** [comment]
Only doc updates in the main repo remain -> removing `blocker`
