### ISSUE TITLE
Missing Git tags 4.1.1..4.1.6

### ISSUE THREAD

**Issue by andreaswolf** [OpenSlides/OpenSlides#6768]
**Describe the bug**

I only see a Git tag for 4.1.0, but not for the subsequent patch-level releases. This seems to apply for both this repository and all referenced submodule repositories.

The missing tags kept me from noticing that there are versions after 4.1.0.

**Expected behavior**

All versions should be clearly tagged to allow for reproducible builds and enable users to easily track changes between versions.

**Comment by jsangmeister** [comment]
We recently changed our update process and will also create tags for patch-level releases in the near future.

**Comment by m-schieder** [comment]
We have now adjusted our update process. From now on, all patch-level releases will get a tag. I hope that you have received a notification for 4.1.11.

**Comment by simonschwarzmueller** [comment]
[4.1.0](https://github.com/OpenSlides/OpenSlides/releases/tag/4.1.0) is still shown as the [latest release](https://github.com/OpenSlides/OpenSlides/releases). Also, I did not recieve a notification even though I set a "watch" notification for new releases.

**Comment by m-schieder** [comment]
We currently only do 'GitHub releases' for Major and Minor releases. For patches we only use [tags](https://github.com/OpenSlides/OpenSlides/tags). We will discuss internally if we also do 'GitHub releases' for patches so you can use the watch function for this.

**Comment by peb-adr** [comment]
We have agreed on doing per-patch github releases starting with version `4.2.0` which is planned for the not-so-far future :^) .

**Comment by peb-adr** [comment]
Version `4.2.0` was released on friday and with it came a workflow for creating github releases with every patch we release.
I hope this will improve update visibility for you guys.
