### ISSUE TITLE
Projector displays candidate names as "User undefined" in election result view

### ISSUE THREAD

**Issue by b2daniel** [OpenSlides/OpenSlides#6778]
**Describe the bug**
When projecting an election result instead of showing candidate names Openslides projector only shows "User undefined" for every candidate name.

**How to Reproduce**
Steps to reproduce the behavior: (https://demo.os4.openslides.com/11/assignments/1)

1. Go to a meeting
2. Create an election, add candidates
3. Create, close and publish a ballot
4. project the ballot and see result in projector view or autopilot

**Expected behavior**
projector shows names of candidates

**System information**

- OpenSlides version: 4.1.7
- Additional version information (if any): also on fresh installation

**Comment by Elblinator** [comment]
The issue is a dupe 
The fix will be protocolled in https://github.com/OpenSlides/openslides-client/issues/3612
