### ISSUE TITLE
Anonymous user 

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/OpenSlides#6798]
**Rough description behaviour**
While you are not logged in you should be able/allowed to go into guest meetings. As a guest....
- you can see the dashboard and every meeting which is opened for the public
- in a meeting you have a guest-group which has necessarily only reading rights, 

**More detailed wanted behaviour:**
Some point have a "(?)" these points still need clarification
Login mask: 
- below the internal login should be a button with "Login as guest" as text
- If this button is pressed the anonymous user should be:
   - If only one meeting is public -> should be navigated to the public meeting
   - If more than one meeting is public -> should be navigated to the dashboard, where every public meeting is display 
   - (? @luisa-beerboom @bastianjoel, is it possible to create a url which can directly navigate into a public meeting for guests, in order to skip the "login as anonymous -> search for the meeting -> click on the meeting)

General: 
- If you are using OpenSlides as a guest... In the top right corner 
  - the "My profile" should be hidden
  - The "Logout" button should be a "Login" button, if pressed you should be navigated to the login page "..../login"
  - The icon should be "no_accounts"

Orga-level: 
- Only "Dashboard" should be visible
- In the dashboard every meeting which is public should be displayed there

Meeting:
- Settings:
   - There will be a new setting after Locked from inside (https://github.com/OpenSlides/openslides-client/pull/3869) is merged
   - This (this issue) new setting to make a meeting public should be below locked_from_inside
      - first time activation automatically creates a guest group 
      - name of the guest group should be "anonymous"
      - it should be a checkbox 
      - the label (for now) should be "Allow anonymous users"
      - There should be a hint below this settin, the hint should be as follows
         - If the guest group has no permissions at all: "The guest group will become visible at the url:  '##/participants/groups', please configure what your guest are allowed to see"
         - If the guest group has one or more permissions: "The guest group is at url:  '##/participants/groups'. Your guest group is already allowed to see some of your contents, please configure the wanted 'To see'- rights for your guests"
   - Locked_from_inside and make a meeting public should **NOT** be allowed to be true at the same time 
     - a locked meeting from the inside is not allowed to be public 
     - a public meeting is not allowed to be locked from the inside
   - we also have the new setting to lock a single participant out (https://github.com/OpenSlides/openslides-client/pull/3815). That setting can be active while a meeting is public --> these two settings are independent from each other
 - Group-Matrix:
   - There should be an additional "anonymous" -Group
   - The group should only be visible if the setting "meeting is public" is activated
   - Guest-group is only allowed to have reading-permissions, every writing permission should be off and disabled
   - If the setting is activated for the first time every permission in the group should be disabled

 An anonymous user should be allowed to see everything what the permissions allow

**Additional context**
If a participant is locked out of a meeting but the meeting is public then the logged in user still cannot see this meeting. If they want to see this meeting they need to be logged out

**Comment by luisa-beerboom** [comment]
We should discuss whether the backend should hard-forbid setting the non-see permissions for the guest group, or whether they should just simply be ignored by the other services if set to true

**Comment by bastianjoel** [comment]
> (? @luisa-beerboom @bastianjoel, is it possible to create a url which can directly navigate into a public meeting for guests, in order to skip the "login as anonymous -> search for the meeting -> click on the meeting)

With the current implementation this is the norm. You access a meeting via its link.

**Comment by Elblinator** [comment]
Each subrepo now has it's own Issue(s) please look at these issues for the specifics. The Issues there will be updated and commented if requirements change

**Comment by rrenkert** [comment]
This feature is merged in all subrepos.
