### ISSUE TITLE
Cannot find auth token, stuck in "Data will be loaded"

### ISSUE THREAD

**Issue by sistason** [OpenSlides/OpenSlides#6817]
**Describe the bug**
After logging out and logging in again with SAML enabled, infinite spinner with Connection lost with autoupdate service and "Can not find auth token" on reconnect.
Spinner appears after logging in again, after authentication already succeeding

**How to Reproduce**
Log out and log in with SAML enabled.
Demo OS4 has no SAML.

**Expected behavior**
delete all cookies / local state and login again.

**System information**

- OpenSlides version: latest
- Firefox
- default docker OS4 with SaToSa as SAML Proxy, see [#6804]

**Additional context**
reload does not fix, strg+F5 fixes it -> local state is not correctly deleted on SAML logout or overwritten on SAML login.

**Screenshots**

![Screenshot from 2024-10-02 20-47-47](https://github.com/user-attachments/assets/ea1e507b-80a4-4d13-bcbb-93dae7b3d40d)

**Comment by Elblinator** [comment]
We reworked our loading page and it is now impossible to run into the "Data will be loaded" page
