### ISSUE TITLE
Meta: Make better release notes

### ISSUE THREAD

**Issue by hejjoe** [OpenSlides/OpenSlides#6827]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to know which new features are included in a new version of openslides like here: 
https://github.com/OpenSlides/OpenSlides/releases/tag/4.0.0

**Describe the solution you'd like**
Make notes in new release.

**Describe alternatives you've considered**
Make readable changlog somewhere else and link to it in the release notes.

**Additional context**
Some good examples:
https://github.com/mastodon/mastodon/releases/tag/v4.0.0
https://github.com/Zverik/every_door/releases/tag/v4.0
https://github.com/alephdata/aleph/releases/tag/4.0.0

**Comment by Elblinator** [comment]
Our most-up-to-date release notes are here (engl./ger.): 
https://support.openslides.com/help/en-gb/45-uber-openslides/80-versionshistorie
You can find this link in the legal notice from every openslides instance (e.g. https://demo.os4.openslides.com/info)
Additionally, you can find the faq if you want more in depth explanations of some features

Our github official realease information can be found here: 
https://github.com/OpenSlides/OpenSlides/blob/main/CHANGELOG.md
