### ISSUE TITLE
Clean up LocalizedModelMultipleChoiceField in utils.forms

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#720]
The method could be simplified. It might work like in the new LocalizedModelChoiceField, but this has to be tested first.

**Comment by ostcar** [comment]
@normanjaeckel was this fixed with #1400 ? If not, can you describe what has to change to close this issue

**Comment by normanjaeckel** [comment]
The file was removed so this issue is out of date.
