### ISSUE TITLE
New version created if supporters are changed by manager 

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#789]
To reprocude (with 1.4c1) as admin; with config complex workflow and supporters > 0:
- create new motion without supporters
- permit motion
- edit motion and add some supporters
  => New version (2) is created.
  Expected: no new version if meta data (supporters, submitters etc.) changed only.

**Comment by jsaalfeld** [comment]
Since this Issue seems to be obsolete, I'll close this issue. Please reopen if i'm wrong.

**Comment by normanjaeckel** [comment]
This is still valid I think

**Comment by ostcar** [comment]
No it is not (We use another editor that does not change the text field
