### ISSUE TITLE
Use event_organizer

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#804]
This config variable is not used anywhere at the moment.

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Is this still up-to-date?

**Comment by emanuelschuetze** [comment]
Currently (in 2.1.1) we don't use the config `general_event_organizer` anywhere. Any idea where it would be helpful? Otherwise we can remove this config field.

@donovaly @normanjaeckel @FinnStutzenstein Any opinion?

**Comment by normanjaeckel** [comment]
Remove it until someone wants to use it.

**Comment by donovaly** [comment]
I would need it. The plan is to store there e.g. which part of a party organizes the even. If possible this info should be displayed at the lower left of the foot line in the projector. This would be helpful for public conventions ("Podiumsdiskussion") etc.

**Comment by emanuelschuetze** [comment]
I'll remove the config field.

**Comment by donovaly** [comment]
Why did you remove it? I made a proposal where it would have been useful.
