### ISSUE TITLE
Find better solution for frequently loading of INSTALLED_APPS

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#907]
A possible solution could be: caching of INSTALLED_APPS modules.

``for app in settings.INSTALLED_APPS`` is used for creating tab navigation, search-filter, global urls and widgets.

**Comment by ostcar** [comment]
This should be very easy with the django 1.7 app loading:

https://docs.djangoproject.com/en/1.7/ref/applications/#application-registry

@emanuelschuetze do you think you can fix this for the 2.0 release? If yes, please change the milestone

**Comment by emanuelschuetze** [comment]
I'll try it for 2.0.

**Comment by emanuelschuetze** [comment]
@ostcar I don't know what you/we want to do here for 2.0... Can you explain it or just do it (if important).

**Comment by ostcar** [comment]
The right way (since django 1.7) is to use the app framework. We do this. I don't know any place where we still use settings.INSTALLED_APPS directly. If we do, it is a bug and has to be fixed. The issue with the general question can be closed
