### ISSUE TITLE
Multiple Projectors

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#930]
Have more then one projector.

Fix https://github.com/OpenSlides/OpenSlides/pull/916#issuecomment-26693901 by the way.

**Comment by emanuelschuetze** [comment]
see concept page https://github.com/OpenSlides/OpenSlides/wiki/De%3AKonzept-Multiprojektor

**Comment by FinnStutzenstein** [comment]
closed if PR #2379 is merged

**Comment by emanuelschuetze** [comment]
done with #2379
