### ISSUE TITLE
Flexible projector header, footer and clock

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#938]

**Comment by normanjaeckel** [comment]
We don't have the old style overlay system but can use projector elements. The goal of this issue would be now to enable something like "fullscreen": The header of a projector slide might be also a projector element which can be switched off via REST API PATCH or PUT request. @emanuelschuetze Please consider this when writing new projector templates.

**Comment by emanuelschuetze** [comment]
It would be nice to deactivate header, footer and clock of projector slide manually. But it is not really important for 2.0. So moved to TODO.

**Comment by emanuelschuetze** [comment]
Now, header, footer and clock can deactivated in projector settings.
