### ISSUE TITLE
CKEditor for various form fields

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/OpenSlides#944]
Reference to #626 and #440. We need a generic solution to setup WYSIWYG-Editors in every text form field, where the app designer likes to do so. See @rolandgeider proposal in #626.

**Comment by normanjaeckel** [comment]
Pull request #1661 is ready but the editor has to be configured well.

**Comment by emanuelschuetze** [comment]
Done in current master. CKEditor is now available for customslide, motion, about_me.
