### ISSUE TITLE
Move reusable functions out of __main__.py

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#961]
Move any function, that could be used in another script out of **main**.py and into utils.main.py

Remove any print statement from them, so other scripts can make their own output.

**Comment by ostcar** [comment]
can be closed with the merge of #1412

**Comment by FinnStutzenstein** [comment]
@ostcar Ping.

**Comment by emanuelschuetze** [comment]
@ostcar I'll close this issue (because #1412 is already merged). Please reopen if something is still open.
