### ISSUE TITLE
Use pattern_name instead of url_name in RedirectView

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#964]
Since Django 1.6 the RedirectView has an argument pattern_name. At the moment we use url_name. We should switch to the (new) standard.

See: https://docs.djangoproject.com/en/dev/ref/class-based-views/base/#django.views.generic.base.RedirectView.pattern_name

**Comment by emanuelschuetze** [comment]
@ostcar is this still required for 2.0

**Comment by ostcar** [comment]
no
