### ISSUE TITLE
Improve API for additional development features.

### ISSUE THREAD

**Issue by DebVortex** [OpenSlides/OpenSlides#972]
During the development of the pdf.js function, i encountered some difficulties, what led to some workarounds. To avoide those, the API has to be enhanced. You can find the discussion during my in my [pullrequest](https://github.com/OpenSlides/OpenSlides/pull/923/files#r7272649).

There are 2 points i would like to see in the API to clean up the code:
* a [set_active_slide](https://github.com/OpenSlides/OpenSlides/blob/master/openslides/projector/api.py#L170)-function without updating the projector
* a clean way to do additional stuff in the ActiveView (currently in the [pre_redirect](https://github.com/DebVortex/OpenSlides/blob/bd332bd3d5b25d8b77e3f48800bd4730370c71ef/openslides/projector/views.py#L88)-function and should be moved to mediafile)

**Comment by emanuelschuetze** [comment]
There is already a new projector (rest) API for 2.0 ... So closed here.
